### ISSUE TITLE
Style API Docs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1002]
**Goal**: Clean up the API docs to make them more usable and branded.

**Comment by noahmanger** [comment]
Check it out:

![screen shot 2015-07-01 at 5 11 13 pm](https://cloud.githubusercontent.com/assets/1696495/8467516/328a5f46-2014-11e5-98c9-139297bcc2fb.png)

![screen shot 2015-07-01 at 5 10 32 pm](https://cloud.githubusercontent.com/assets/1696495/8467510/1a74a416-2014-11e5-8e1b-a248bb5db9bb.png)

**Comment by noahmanger** [comment]
Also I know @emileighoutlaw had some text edits. Did those get in or not? I'm not sure where they were made.

**Comment by LindsayYoung** [comment]
Those should already be included. Thanks for making it look like we have talented designers and it belongs with the rest of the site!

**Comment by emileighoutlaw** [comment]
Yep! Made my edits last week. Feeling lucky to have had any hand in this document— it's amazing, y'all!

**Comment by noahmanger** [comment]
Nice. Ready for review https://github.com/18F/swagger-ui/pull/1
