### ISSUE TITLE
Figure out what information will be included in dates and dealines endpoint

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1025]
We need to determine what information will be included in the dates / deadline endpoint in order to know how to design the way it will be implemented on committee pages and the calendar.

**Comment by LindsayYoung** [comment]
Here is the data for reference:
https://docs.google.com/spreadsheets/d/14Zr1OgKY_ipmWi1uDGuvNV7R_rV8N8BVbm7Z9z-sBDY/edit#gid=0

**Comment by noahmanger** [comment]
Oh great. Thanks. Will this also include individual dates that vary by
state?

On Mon, Jul 6, 2015 at 11:20 AM, Lindsay Young <notifications@github.com>
wrote:

> Here is the data for reference:
>
> https://docs.google.com/spreadsheets/d/14Zr1OgKY_ipmWi1uDGuvNV7R_rV8N8BVbm7Z9z-sBDY/edit#gid=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1025#issuecomment-118944857>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
Yes, there are less of those because it is an odd-numbered year but you can see examples on the bottom of the sheet. Headers marked (internal) don't need to be shared, they are dates that filing reminders get sent out

**Comment by noahmanger** [comment]
Oh duh. I totally missed that. Great.

On Mon, Jul 6, 2015 at 11:35 AM, Lindsay Young <notifications@github.com>
wrote:

> Yes, there are less of those because it is an odd-numbered year but you
> can see examples on the bottom of the sheet. Headers marked (internal)
> don't need to be shared, they are dates that filing reminders get sent out
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1025#issuecomment-118951595>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
Done.
