### ISSUE TITLE
Sample CMS

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1029]
- [x] Django-CMS
 - [x] Mezzanine
 - [x] Wagtail

**Comment by patphongs** [comment]
Django-CMS seem like a nice system. I was playing around with Django-CMS on their demo site, it seems more user friendly. The ability to switch between structure and content and also seeing the Live and Draft mode slider is nice and intuitive. This allows users to easily select a page type (full width, two columns, side bars, etc), add content by double clicking components, and rearranging the structure of the components. It would be interesting to see how difficult it would be to develop custom components for it.

**Comment by leahbannon** [comment]
We've settled on Wagtail, so I'm closing this :+1:
