### ISSUE TITLE
Route staging traffic through API Umbrella

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1053]
The staging server should behave as much as possible like the production server, so that we can be confident that a successful deploy to staging will also work as expected on production. Staging is currently deployed without using the API Umbrella; we should add a new API and route staging traffic through it.

**Comment by LindsayYoung** [comment]
That's a good point

**Comment by jmcarp** [comment]
This happened. Thanks @cmc333333 for help with configuration. We still need to get an SSL cert for staging--will do next week.
