### ISSUE TITLE
To let users try out endpoints without knowing ids Add cand_id suggestions in documentation?

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1065]
Provide id suggestions for documentation. 

From twitter https://twitter.com/chachasikes/status/621038984391593984

I am thinking we could show both Obama and Ronmey's ids for those examples. We need to check with FEC to see if they are comfortable with using real people in examples. If not, we could try mock examples with fictional people, or something.

**Comment by chachasikes** [comment]
Cool -- following this.

**Comment by chachasikes** [comment]
I just looked more closely at the Swagger documentation. If you can't supply the ID's (the first one I found was 'H2CA01110') then also it might be possible to make a javascript widget that gets displayed in the field documentation that shows '5 random samples' as a table that is visually distinct enough that it shows it's live data from the API. 

Also possible to populate an inline piece of documentation after the field descripiton:
"Examples: _____, _____, and _____ are some popular values in the current dataset."

 The use case in my situation is for getting an idea of what the data looks like. The "try it out" button is also hard to notice. That might be a separate issue/separate 18f repository, cause it's more an issue of API interface design —showing this kind of data automatically for API's (in general) would be helpful.

In any case, this is great & keep up the awesome work! :)

**Comment by noahmanger** [comment]
Great ideas. I actually have a patch coming soon to make the "Try it out"
button bigger and bolder, so hopefully that helps somewhat.

On Wed, Jul 15, 2015 at 9:48 AM, Chach Sikes <notifications@github.com>
wrote:

> I just looked more closely at the Swagger documentation. If you can't
> supply the ID's (the first one I found was 'H2CA01110') then also it might
> be possible to make a javascript widget that gets displayed in the field
> documentation that shows '5 random samples' as a table that is visually
> distinct enough that it shows it's live data from the API.
>
> Also possible to populate an inline piece of documentation after the field
> descripiton:
> "Examples: _____, _____, and _____ are some popular values in the current
> dataset."
>
> The use case in my situation is for getting an idea of what the data looks
> like. The "try it out" button is also hard to notice. That might be a
> separate issue/separate 18f repository, cause it's more an issue of API
> interface design —showing this kind of data automatically for API's (in
> general) would be helpful.
>
> In any case, this is great & keep up the awesome work! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1065#issuecomment-121676363>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
Captured in this story: https://18f.storiesonboard.com/m/fec/!card/iP_VyxlBWXBzijnUEFZhfg
