### ISSUE TITLE
email and url fields?

### ISSUE THREAD

**Issue by pardery** [18F/openFEC#1070]
Hello.  Firstly, thank you very much for creating and publishing this project, it's awesome!  

According to the documentation, the /candidates endpoint feeds data provided on [Form1] (http://www.fec.gov/pdf/forms/fecfrm1.pdf) and [Form2](http://www.fec.gov/pdf/forms/fecfrm2.pdf).  Form1 includes the registrant's email address and web address.  I do not see these fields in the current response from the /candidates endpoint and was wondering if this data will be available in a future release of the API.

Thanks again!

**Comment by LindsayYoung** [comment]
The /candidates endpoint is good for finding basic information. Some of the more obscure information lives in other endpoints. 

We do have the website and email for committees that fill out that information. 

Here is an example call where you use a candidate ID to find website and email of committees:
https://api.open.fec.gov/v1/candidate/P80003353/committees?designation=P&designaiotn=A&api_key=DEMO_KEY

Hope that is helpful!

**Comment by pardery** [comment]
I must have overlooked that, thanks very much!
