### ISSUE TITLE
rate limiting

### ISSUE THREAD

**Issue by pardery** [18F/openFEC#1075]
I have encountered the RATE_LIMIT for maximum requests.  I see that this limit is handled by API Umbrella, but I couldn't find any more details on the limit itself in the openFEC documentation.  Might I be overlooking something?  If not, could you provide some details on how the limiting is handled so that I can adjust my code accordingly?  More generally, do you think it would be feasible to run upwards of 2000 requests on a nightly/weekly basis?

The ultimate goal of my code is to pull a list of candidate IDs for the most recent cycle with per_page = 5000 (1 request currently), then pull the committee data for each resulting candidate ID for the same cycle (currently 1290 given the 2016 candidates).  Ideally, we'd like to set this job up to run nightly, or maybe weekly to discovery any new content in the API database.

So, right now, the process would make 1291 requests, and we could definitely implement a wait time between each request if that would ease the network load.

**Comment by LindsayYoung** [comment]
Thank you for telling us the rate limiting is being problematic. We will take this into consideration. To confirm, you are using your own key and not DEMO_KEY- the demo key has a lower rate limit. 

Also, I think you can keep your data up to date with less queries. `last_file_date` comes from the receipt date of the most recent form 1 filing (That is where we are collecting the email and website information that you mentioned before). So, we can order those queries to see which committees have updated their paper work or filed for the first time. 

If you are looking for candidate committees, you can filter for those directly on the `/committees` endpoint. Candidate committees will have a designation of P, or A. 

The per-page max is 100. 

Here is the call I would use to see the updated committees:
https://api.open.fec.gov/v1/committees?api_key=DEMO_KEY&sort=-last_file_date&cycle=2016&designation=A&designation=P&page=1&per_page=100

To get the web addresses and emails, you would still need to call the `/committee/<id>` endpoint, but you could just check the ones who have filed paperwork within a few days of the last time your script ran.

Good luck! It sounds like you are working on a really interesting project.

**Comment by pardery** [comment]
Thanks for the input Lindsay.  Yes, I am using my own key (not the DEMO key).  I am not sure how many queries it took to hit the max, but if you know what the maximum queries for a given time frame is, I can adjust accordingly.

Also, thanks for the last_file_date tip.  I'll look into that.

**Comment by s2t2** [comment]
Hey, I'm running into the rate limit (1000 calls) during an attempt to page through all 1020 pages of candidates.

```` rb
{"error"=>
  {"code"=>"OVER_RATE_LIMIT",
   "message"=>"You have exceeded your rate limit. Try again later or contact us at https://api.open.fec.gov/contact for assistance"}}
````

To avoid hitting the limit I tried slowing down the request rate to 1 second per call, then 3 seconds per call, but neither was successful. I'm writing to share this use case and the expectation for rate limit replenishment to handle a request rate of 1-3 seconds.

As an alternative I increased the `per_page` option to 100, and was able to get through the entire list. Thanks for the tip!

**Comment by LindsayYoung** [comment]
Thanks for reaching out! To clarify, the current rate limit is 1,000 requests an hour.

**Comment by boblannon** [comment]
I'm trying to write something into a py wrapper that respects the rate limit and backs off, but i'm getting a 429 error long before i make 1000 calls. is it possibly defined for a shorter span of time?

**Comment by boblannon** [comment]
it would be helpful to be able to request one's rate limit status (eg, [twitter](https://dev.twitter.com/rest/reference/get/application/rate_limit_status)). is that a capability that apiumbrella has?

**Comment by s2t2** [comment]
Check the response headers for rate limit status. 

```` sh
curl -I https://api.open.fec.gov/v1/candidates?api_key=MY_KEY&sort=name&page=1&per_page=20
````

You should see the following headers:
 +  `X-RateLimit-Limit: 1000`
 + `X-RateLimit-Remaining: 997`

**Comment by boblannon** [comment]
ooh great. thanks!

**Comment by dannguyen** [comment]
On a side note, it'd be cool to note the `per_page` limit being `100` in the documentation...just to save bulk-freeloaders like me the work of  "let's see what happens with *this* request" :)

**Comment by LindsayYoung** [comment]
Good point @dannguyen! We'll add that.
