### ISSUE TITLE
Write aggregate updates using SQLAlchemy

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1077]
Incremental updates for our large aggregates (Schedule A and B) are currently written as SQL stored procedures. This means that adding another aggregate requires copying and pasting an existing aggregate, then replacing a few column names in the stored procedure (compare https://github.com/18F/openFEC/blob/develop/data/sql_incremental_aggregates/prepare_schedule_a_aggregate_zip.sql and https://github.com/18F/openFEC/blob/develop/data/sql_incremental_aggregates/prepare_schedule_a_aggregate_state.sql). Not that this is news to anyone, but copy-and-pasted code is hard to maintain and test. I propose that we refactor the stored procedures to a Python / SQLAlchemy helper that we can more easily parameterize, so that we don't have to copy code between aggregates anymore.

@arowla: does this seem right to you?

**Comment by arowla** [comment]
Sorry to leave this hanging. I'm not quite sure what these would look like in SQLAlchemy, but it does seem like some kind of templated/SQL generated solution, at the very least, would be better than copy and paste.

**Comment by noahmanger** [comment]
Is this still relevant?
