### ISSUE TITLE
Expose aggregates by candidate

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1084]
In support of https://github.com/18f/openfec-web-app/issues/297, the API needs to provide per-candidate aggregates by contribution size, contributor location, etc. We currently have aggregates by committee, but not by candidate. It looks like we'll want to add aggregates like this:

`/schedules/schedule_a/by_size/by_candidate?cycle=2012&candidate_id=H001&candidate_id=H002...`

These aggregates would sum over all principal and authorized committees associated with each candidate for the requested cycle.

Sound good to you @LindsayYoung @noahmanger?

**Comment by noahmanger** [comment]
Yep, this is exactly what we're looking for, afaik.

On Fri, Jul 24, 2015 at 3:58 PM, Joshua Carp <notifications@github.com>
wrote:

> In support of 18F/openFEC-web-app#297
> <https://github.com/18F/openFEC-web-app/issues/297>, the API needs to
> provide per-candidate aggregates by contribution size, contributor
> location, etc. We currently have aggregates by committee, but not by
> candidate. It looks like we'll want to add aggregates like this:
>
>
> /schedules/schedule_a/by_size/by_candidate?cycle=2012&candidate_id=H001&candidate_id=H002...
>
> These aggregates would sum over all principal and authorized committees
> associated with each candidate for the requested cycle.
>
> Sound good to you @LindsayYoung <https://github.com/LindsayYoung>
> @noahmanger <https://github.com/noahmanger>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1084>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
Done in #1086.
