### ISSUE TITLE
Add itemized communication costs.

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1098]

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/I0bne6Rqsx8cNznTwmRr_g

**Comment by noahmanger** [comment]
Bump!

**Comment by noahmanger** [comment]
Dependency: https://github.com/18F/openFEC/issues/1404

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1058
