### ISSUE TITLE
Add line number filtering to schedule A

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1102]
To make the aggregate totals reproducible we need to let users filter the `/schedule/schedule_a` endpoint by line numbers.

**Comment by leahbannon** [comment]
Has this already been addressed?

**Comment by jmcarp** [comment]
The aggregates are a little more complicated than that--folks would need to be able to filter by line number, memo code, memo text, receipt type, and amount to reproduce the filters we're using. It might be simpler to expose our `is_individual` column instead. This would be straightforward to add to the proposed itemized refactor at #1218.

What do you think @LindsayYoung? I can add to #1218 if that makes sense.

**Comment by LindsayYoung** [comment]
Exposing is_individual seems like a good solution. We should also take the opportunity to document the logic on that.

**Comment by jmcarp** [comment]
Added. To be clear, we currently allow filtering on the derived `is_individual` flag, not on line number, because the former is necessary to reconstruct our aggregates.
