### ISSUE TITLE
Add party and challenge / incumbent status to candidate comparison table

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1106]
On election pages, the table at the top should show the candidate party, their incumbent / challenger status, and _ideally_ if they won or not (not sure what the plan for the data for this piece is).

**Comment by LindsayYoung** [comment]
I would like that too- I would love to harvest the FEC data for this.

**Comment by jmcarp** [comment]
This information is added to the API output in proposal #1165. I haven't added it to the webapp so far since the table is already pretty full, but adding it should be simple once #1165 is ready. Maybe we could highlight the row of the winner in the table (if there is one) so we can show the information without adding an extra column. What do you think @noahmanger @LindsayYoung?

**Comment by noahmanger** [comment]
Yeah I like the idea of something like that. Or maybe a star next to their name? Or a :trophy: emoji? (Only  half-joking)

**Comment by LindsayYoung** [comment]
I think there might be a good emoji approach- something other than a trophy.

**Comment by noahmanger** [comment]
Maybe just a plain unicode star http://www.fileformat.info/info/unicode/char/2605/index.htm

**Comment by noahmanger** [comment]
Or we could create our own custom icon. Thoughts @jenniferthibault ?

**Comment by jenniferthibault** [comment]
I love the idea of a star showing the office holder. How about this one though, which is a little bit softer that the standard unicode. I believe it's based on a CFPB design:

![star](https://cloud.githubusercontent.com/assets/11636908/9686843/e3161dca-52f3-11e5-8c13-ef40db1b050c.png)

**Comment by leahbannon** [comment]
:+1:

**Comment by noahmanger** [comment]
Can you drop that in the icon file?

**Comment by noahmanger** [comment]
How does this work for folks? I removed the "incumbent status" column and added the key?

![screen shot 2015-09-04 at 8 53 02 am](https://cloud.githubusercontent.com/assets/1696495/9688200/9389f3e6-52e2-11e5-8119-31d57cc39347.png)


@jmcarp i just added an optional parameter to `buildEntityLink` to add a class to candidate names that are incumbents. That work for you?

**Comment by LindsayYoung** [comment]
Can we call it "current office holder" that way we don't have to keep track if they are really running again?

**Comment by noahmanger** [comment]
They only show up in this table if they're running, right?

**Comment by noahmanger** [comment]
Could be good to add the current office-holder in the header though. Which in the case of an incumbent would be a duplicate.

**Comment by LindsayYoung** [comment]
I am seeing a lot of people in there, especially in Senate that I don't think are running.

That issue is #1176, there are some examples there

**Comment by noahmanger** [comment]
So you're saying they show up in the table even if they're not running?

**Comment by LindsayYoung** [comment]
There committees still have activity. Maybe we could solve this by only including candidates that have filed a form 2 for that election year?

**Comment by noahmanger** [comment]
Oh yeah. I think that's definitely the expected behavior. Any reason not to?
