### ISSUE TITLE
API server randomly returns empty results

### ISSUE THREAD

**Issue by dannguyen** [18F/openFEC#1113]
This may have been addressed in another issue...I did a quick search and didn't see anything or didn't look closely enough to find a similar issue...Anyway, in this example query:

https://api.open.fec.gov/v1/committee/C00411330/totals?api_key=DEMO_KEY

Sometimes, I'll get results. Sometimes I won't (I'm making calls with my own key, not the DEMO_KEY). The discrepancy can happen when I simply refresh the browser page as I'm testing the URL. I don't know of any other way to deterministically reproduce this, so the best I can do is post my request and response headers. You can see how the `Content-Length` values reflect the results

-------

## Request headers

|                                                               Successful                                                              |                                                                 Empty                                                                 |
|---------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------|
| GET /v1/committee/C00411330/totals?api_key=DEMO_KEY HTTP/1.1                                                                          | GET /v1/committee/C00411330/totals?api_key=DEMO_KEY HTTP/1.1                                                                          |
| Host: api.open.fec.gov                                                                                                                | Host: api.open.fec.gov                                                                                                                |
| Connection: keep-alive                                                                                                                | Connection: keep-alive                                                                                                                |
| Pragma: no-cache                                                                                                                      | Pragma: no-cache                                                                                                                      |
| Cache-Control: no-cache                                                                                                               | Cache-Control: no-cache                                                                                                               |
| Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8                                                    | Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8                                                    |
| Upgrade-Insecure-Requests: 1                                                                                                          | Upgrade-Insecure-Requests: 1                                                                                                          |
| User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36 | User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36 |
| DNT: 1                                                                                                                                | DNT: 1                                                                                                                                |
| Accept-Encoding: gzip, deflate, sdch                                                                                                  | Accept-Encoding: gzip, deflate, sdch                                                                                                  |
| Accept-Language: en-US,en;q=0.8                                                                                                       | Accept-Language: en-US,en;q=0.8                                                                                                       |

## Response headers

|                      Successful                      |                        Empty                         |
|------------------------------------------------------|------------------------------------------------------|
| HTTP/1.1 200 OK                                      | HTTP/1.1 200 OK                                      |
| accept-ranges: bytes                                 | accept-ranges: bytes                                 |
| access-control-allow-methods: GET                    | access-control-allow-methods: GET                    |
| access-control-allow-origin: *                       | access-control-allow-origin: *                       |
| access-control-max-age: 3000                         | access-control-max-age: 3000                         |
| age: 174                                             | age: 560                                             |
| cache-control: public, max-age=3600                  | cache-control: public, max-age=3600                  |
| content-encoding: gzip                               | content-encoding: gzip                               |
| Content-Type: application/json                       | Content-Type: application/json                       |
| Date: Mon, 10 Aug 2015 18:30:30 GMT                  | Date: Mon, 10 Aug 2015 18:29:01 GMT                  |
| location:                                            | location:                                            |
| Server: nginx                                        | Server: nginx                                        |
| strict-transport-security: max-age=31536000          | strict-transport-security: max-age=31536000          |
| vary: Accept-Encoding, Accept-Encoding               | vary: Accept-Encoding, Accept-Encoding               |
| via: 1.1 varnish-v4                                  | via: 1.1 varnish-v4                                  |
| x-cache: HIT                                         | x-cache: HIT                                         |
| x-cf-requestid: bafc3682-dbc9-4077-5f53-8f5ccd354fd0 | x-cf-requestid: 06ee113c-2cee-467b-5d1e-9174b46f1ca7 |
| x-content-type-options: nosniff                      | x-content-type-options: nosniff                      |
| x-frame-options: DENY                                | x-frame-options: DENY                                |
| X-RateLimit-Limit: 1000                              | X-RateLimit-Limit: 1000                              |
| X-RateLimit-Remaining: 984                           | X-RateLimit-Remaining: 986                           |
| x-varnish: 20024088 20153470                         | x-varnish: 44599430 43934986                         |
| x-xss-protection: 1; mode=block                      | x-xss-protection: 1; mode=block                      |
| Content-Length: 1193                                 | Content-Length: 97                                   |
| Connection: keep-alive                               | Connection: keep-alive                               |

**Comment by mihi-tr** [comment]
I do seem to consistently get empty results now for committee totals...

**Comment by LindsayYoung** [comment]
Thank you for reporting this. We will look at this now.

**Comment by LindsayYoung** [comment]
It seems like we need to do some data updates, those should run tonight. I will check to make sure the problem is resolved in the morning.

**Comment by LindsayYoung** [comment]
OK this should all be working again- https://api.open.fec.gov/v1/committee/C00411330/totals?api_key=DEMO_KEY

Please tell us if you experience any problems. 

Also, just incase is useful- I wanted to mention FRIENDS OF BERNIE SANDERS is his Senate committee C00411330, the Presidential Committee is BERNIE 2016 C00577130.

**Comment by dannguyen** [comment]
Thanks!
