### ISSUE TITLE
by_state and by_zip aggregate endpoints 500'ing

### ISSUE THREAD

**Issue by boblannon** [18F/openFEC#1137]
the following endpoints are returning 500 errors:

`/schedules/schedule_a/by_state`
`/schedules/schedule_a/by_zip`

`/committee/{committee_id}/schedules/schedule_a/by_state` [example](https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_state)
`/committee/{committee_id}/schedules/schedule_a/by_zip` [example](https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_zip)

**Comment by jmcarp** [comment]
Thanks for reporting this! Turns out to be an issue we resolved in develop that hadn't made its way to production yet--I'm applying the fix to production now. It'll take a few hours to rebuild the tables, so I'll close the issue when they're back.

**Comment by boblannon** [comment]
:smile:

**Comment by jmcarp** [comment]
They're back!
