### ISSUE TITLE
by_size aggregate endpoints missing data

### ISSUE THREAD

**Issue by boblannon** [18F/openFEC#1138]
the results from the `committee/{committee_id}/schedules/schedule_a/by_size` endpoint are omitting many contributions in their aggregates.  for example, [bucketing contributions to Hillary for America](https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_size) is only returning the total of unitemized contributions.

```
{
  "api_version": "1.0",
  "pagination": {
    "page": 1,
    "count": 1,
    "pages": 1,
    "per_page": 20
  },
  "results": [
    {
      "total": 8098550,
      "count": null,
      "size": 0,
      "committee_id": "C00575795",
      "cycle": 2016
    }
  ]
}
```

This isn't accurate: that committee raised more than $38M in itemized contributions.

It doesn't seem to be a consistent problem, though. There are non-empty itemized buckets for [Cruz for President](https://api.open.fec.gov/v1/committee/C00574624/schedules/schedule_a/by_size):

```
{
  "api_version": "1.0",
  "pagination": {
    "page": 1,
    "count": 5,
    "pages": 1,
    "per_page": 20
  },
  "results": [
    {
      "total": 1832878,
      "count": null,
      "size": 0,
      "committee_id": "C00574624",
      "cycle": 2016
    },
    {
      "total": 175956.31,
      "count": 693,
      "size": 200,
      "committee_id": "C00574624",
      "cycle": 2016
    },
    {
      "total": 194254.1,
      "count": 385,
      "size": 500,
      "committee_id": "C00574624",
      "cycle": 2016
    },
    {
      "total": 364502,
      "count": 358,
      "size": 1000,
      "committee_id": "C00574624",
      "cycle": 2016
    },
    {
      "total": 1835613,
      "count": 502,
      "size": 2000,
      "committee_id": "C00574624",
      "cycle": 2016
    }
  ]
}
```

**Comment by boblannon** [comment]
bumping this to make sure it didn't get lost alongside another, similar issue that i opened just beforehand.  the data still seems to be missing. are my expectations incorrect, or is there possibly an aggregation issue?

**Comment by boblannon** [comment]
any info? paging @LindsayYoung @jmcarp

**Comment by LindsayYoung** [comment]
Hey Bob, sorry for the delayed response.

I see now that this was not documented. I think that paging, rate limiting and a few other things need to be better explained too. 

We are doing this on purpose for some charts on the website,  where we tackle individual donations separately. It doesn't make sense to do the aggregations for employer or state with the I can see the utility of having the size of donations include other political groups, but we also wanted to make the aggregations consistent. 

Thank you again!

**Comment by boblannon** [comment]
ah, i see. that explains it! thanks.

**Comment by boblannon** [comment]
wait, actually, I still don't understand.  C00575795 has raised over $38M in individual contributions, including $8M in unitemized (<$200) individual contributions. 

You're saying, I think, that the `by_size` endpoint leaves out pac-to-pac contributions, which makes sense, but what about the other individual contributions?  Only the unitemized ones are included in the results.

**Comment by LindsayYoung** [comment]
OK, that sounds like an error. I will look into it.

**Comment by jmcarp** [comment]
This will be fixed with the next release to production, which we're going to start in the morning. Some of the aggregate tables will take a while to update--I'll let you know and close the issue when they're done.

**Comment by LindsayYoung** [comment]
OK, we have already fixed this on our development branch and we will push this with the next round of updates.

**Comment by jmcarp** [comment]
Looking good now:
```
{
    "api_version": "1.0",
    "pagination": {
        "page": 1,
        "per_page": 20,
        "count": 5,
        "pages": 1
    },
    "results": [
        {
            "size": 500,
            "total": 1398853.02,
            "committee_id": "C00575795",
            "count": 2686,
            "cycle": 2016
        },
        {
            "size": 200,
            "total": 1243855.69,
            "committee_id": "C00575795",
            "count": 4763,
            "cycle": 2016
        },
        {
            "size": 0,
            "total": 9104291.91,
            "committee_id": "C00575795",
            "count": null,
            "cycle": 2016
        },
        {
            "size": 2000,
            "total": 39908804.9,
            "committee_id": "C00575795",
            "count": 11891,
            "cycle": 2016
        },
        {
            "size": 1000,
            "total": 3359676.33,
            "committee_id": "C00575795",
            "count": 3060,
            "cycle": 2016
        }
    ]
}
```

Thanks for reporting!
