### ISSUE TITLE
To provide context to receipts aggregates, show total and/or percentage of total

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1145]
Paul and I were thinking the grids need a way for the viewer to see how each row fits into the overall. Like adding a percentage of total column to the State, Contribution Size, Employer and Occupation grids.

That or put the total amount at the top of each grid like this:

Receipts by State (total - $6,233,44)

Whatever works best.

**Comment by noahmanger** [comment]
I still am interested in this idea eventually. Seems helpful.
