### ISSUE TITLE
Record web analytics?

### ISSUE THREAD

**Issue by konklone** [18F/openFEC#1146]
The landing page at https://api.open.fec.gov doesn't have any analytics reporting, for 18F or DAP.

**Comment by leahbannon** [comment]
related: https://github.com/18F/openFEC-web-app/issues/373

**Comment by jmcarp** [comment]
Questions:
* Do we want separate or combined analytics for the three apps (API, data app, and CMS)?
* Should we use 18F Google Analytics, DAP, or both?

**Comment by konklone** [comment]
> Should we use 18F Google Analytics, DAP, or both?

I strongly recommend both. Getting analytics for a single site out of DAP is definitely possible, but involves annoying custom reports and filters, and occasionally sampling errors.

**Comment by leahbannon** [comment]
Yep - 18F and DAP is standard for our projects. By combined analytics, do you mean the same UA code? If so, yes, combined is better.
