### ISSUE TITLE
Inconsistent dates in `vw_filing_history`

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1147]
The `vw_filing_history` view includes several columns with date information, but no single column can be used across all form types. Examples: the `report_year` and `election_year` columns are always set to `0` for F1 filings; `receipt_date` is always `null` for RFAI filings. When we filter filings from this view by year, it's unclear which column(s) we should use to determine the year.

It also looks like some date information that's available in FEC Viewer isn't included in `vw_filing_history`. For example, RFAI filings have a "Filed On" date in FEC Viewer, but I'm not seeing that information in `vw_filing_history`.

@jwchumley and @paulclark2: Would it be feasible to populate at least one date column consistently for this view? For example, it would be helpful if `report_year` were always populated, so that we could use a single column for date filtering. If not, can you suggest a method for us to identify the year a given filing was filed? As a (possibly temporary) fix, I'm using `report_year` if present, else the year from `receipt_date`.

**Comment by PaulClark2** [comment]
@jmcarp 
VW_FILING_HISTORY
Form 1 - election year null
	This is correct.  Election years are not part of the Form 1 filing.  

Form 1 - report year null
	This is an error.  I've asked our DBA team to update the script that generates VW_FILING_HISTORY.

RFAI - receipt date null
	This is an error.  The RFAI Date will be used to populate receipt date in VW_FILING_HISTORY. I've asked our DBA team to update the script that generates VW_FILING_HISTORY. 

I'll let you know when the script changes and table updates are completed.

**Comment by jmcarp** [comment]
Thanks! I'll leave the issue open for now, and close once we have updated data and I've reverted the temporary workaround I added to the API to deal with missing data.

**Comment by jmcarp** [comment]
@PaulClark2: Has the DBA team gotten back to you about this?

**Comment by PaulClark2** [comment]
No  ... not yet

**Comment by LindsayYoung** [comment]
So following up on this. There are now no null report_years, so that is great. But I am still seeing 26 nulls in receipt_date.

**Comment by PaulClark2** [comment]
I can fix these two of these and will do that tomorrow.  

FORM_TP | SUB_ID | CAND_CMTE_ID | BEGIN_IMAGE_NUM | END_IMAGE_NUM | PAGES | RPT_YR | RPT_TP | RECEIPT_DT
------------ | --------------------------- | --------------------- | --------------------------- | ------------------------ | --------- | ------------ | ------------ | ----------------
F3X | 1011120120009257265 | C00465294 | 12030703229 | 12030703234 | 6 | 2011 | YE | 1/5/2012
F5 | 1030620080000617836 | C90006701 | 24971680418 | 24971680418 | 14 | 2004 | Q3 | 10/15/2004

**Comment by PaulClark2** [comment]
The other 24 are really old and I'll need to ask Public Records for help finding the microfilm.  

FORM_TP | SUB_ID | CAND_CMTE_ID | BEGIN_IMAGE_NUM | END_IMAGE_NUM | PAGES | RPT_YR | RPT_TP | RECEIPT_DT
------------ | --------------------------- | --------------------- | --------------------------- | ------------------------ | --------- | ------------ | ------------ | ----------------
F3 | 3032920021022188531 | H6PA00076 | 76011004013 | 76011004014 | 2 | 1976 | Q2 | 
F3 | 3032920021022148418 | C00052076 | 76011010671 | 76011010689 | 19 | 1976 | Q2 | 
F3 | 3032920021022087105 | C00025734 | 76011010690 | 76011010694 | 5 | 1976 | Q2 | 
F3 | 3032920021022087106 | C00025734 | 76011043083 | 76011043090 | 8 | 1976 | 10D | 
F3 | 3032920021022187027 | H6NC10018 | 76011051696 | 76011051698 | 3 | 1976 | 30D | 
F3 | 3032920021022087323 | C00026302 | 76011141679 | 76011141686 | 8 | 1976 | Q2 | 
F3 | 3032920021022182214 | C00067645 | 76011160022 | 76011160026 | 5 | 1976 | 30D | 
F3X | 3032920021022359807 | C00008110 | 76011163386 | 76011163387 | 2 | 1976 | 30D | 
FRQ | 3032920021022773806 | C00035204 | 76030084583 | 76030084583 | 1 | 1976 | YE | 
F3X | 3032920021022357160 | C00002790 | 76030111526 | 76030111532 | 7 | 1975 | Q1 | 
F3X | 3032920021022360399 | C00009290 | 76030130443 | 76030130451 | 9 | 1975 | Q2 | 
F3X | 3032920021022359782 | C00008078 | 76030330133 | 76030330145 | 13 | 1976 | Q3 | 
F3X | 3032920021022365735 | C00030478 | 76030333195 | 76030333205 | 11 | 1976 | Q3 | 
F3X | 3032920021022358147 | C00004275 | 76030382953 | 76030382955 | 3 | 1976 | M7 | 
F3X | 3032920021022368288 | C00038943 | 76030421262 | 76030421279 | 18 | 1976 | 30D | 
F3 | 3032920021022190556 | P60002375 | 76030423165 | 76030423171 | 7 | 1976 | 30D | 
F3 | 3032920021022147803 | C00050682 | 76030433518 | 76030433523 | 6 | 1976 | Q2 | 
F3 | 3032920021022187257 | H6NJ06070 | 77011202990 | 77011202990 | 1 | 1976 | 30D | 
F3 | 3032920021022185535 | H6LA06042 | 77011203083 | 77011203083 | 1 | 1976 | YE | 
F3 | 3032920021022063485 | H6CA04024 | 77011210044 | 77011210047 | 4 | 1977 | 10D | 
F3 | 3032920021022070079 | C00100586 | 82012233758 | 82012233758 | 1 | 1982 | 12P | 
F3 | 3032920021022071170 | C00113662 | 82012241439 | 82012241455 | 17 | 1982 | Q2 | 
F3X | 3032920021022461407 | C00123117 | 82032433923 | 82032433930 | 8 | 1981 | YE | 
F3X | 3032920021022404304 | C00067231 | 82032442559 | 82032442564 | 6 | 1982 | M9 |

**Comment by PaulClark2** [comment]
This could be something we address more systematically as we work on the database consolidation on our side.  We could create a generic date column that is populated for all form types.

**Comment by LindsayYoung** [comment]
I'm closing this since we are planning on moving off this table anyway.
