### ISSUE TITLE
Candidate page summary amounts and rounding

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1152]
https://fec-dev-web.cf.18f.us/candidate/P00003392?cycle=2016

TTL receipts, disbursements and ending cash are all rounded to $100 or sometimes to the $0 (bernie Sanders Disb) Debt is not rounded. I think it should probably not round anything but if it does they should all be treated the same way.

**Comment by jmcarp** [comment]
We aren't rounding any of these values at the moment--we're just adding up the values from (in this example) `factpresidential_f3p`. It looks like some committees report round numbers, like in the example you posted, and some don't--for examples, https://fec-dev-web.18f.gov/candidate/P60008059.

@jwchumley: do you want us to take any action here, or is the current behavior (not rounding) what you want?

**Comment by jwchumley** [comment]
Odd. When I look at candidate Hillary Clinton we have 47,549,949 and you are showing 47,549,900. That is just one example. There are many.

select * from FACTPRESIDENTIAL_F3P where cmte_sk = 10056935;

**Comment by jmcarp** [comment]
I'm not sure which column you're looking at, but I don't see that value in any of our databases. From staging:
```
fec=> select ttl_receipts_per from FACTPRESIDENTIAL_F3P where cmte_sk = 10056935;
 ttl_receipts_per
------------------
      47549900.00
(1 row)
```

This is the value we're showing on the site. I don't see any columns for Clinton with the value you found--maybe the data are being changed during or before they're sent through Golden Gate. @PaulClark2 may have some insight here.

**Comment by jwchumley** [comment]
When I run that statement in the source tables I get 47549949.64.  I'll look at it with Paul and see if we can figure out where the change is happening.

**Comment by jwchumley** [comment]
I think I've at least figured out where the problem lies. It looks like data from the initial load is correct but data loaded via nightly update has an issue where any 8 digit number is rounding to the nearest 100. I've sent it to Rohan but they are working on a major hardware update so he may not look into it until next week.

**Comment by jwchumley** [comment]
Rohan fixed it. Numbers are correct now. No more rounding

**Comment by jmcarp** [comment]
Great, thanks for figuring this out.
