### ISSUE TITLE
Questionable link on candidate pages

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1153]
https://fec-dev-web.18f.gov/candidate/P60006723?cycle=2016

"Source: July Quarterly 2015" is inaccurate. it implies that the numbers come from the July Quarterly 2015 report column B but they are actually summed from Column A of all reports in the two year period. I think it is better not to link there at all. It is already clear on the other side of the screen where it says "Calculated from reports filed 2015–2016".  If you want to link to source documents it should be to a list of all the reports that contribute to the numbers, not just the most recent one.

**Comment by noahmanger** [comment]
Take-aways from discussion:
- [ ] Include coverage dates 
- [ ] Include links to underlying reports

**Comment by noahmanger** [comment]
@LindsayYoung and I chatted about her picking this up. I know there's stuff from usability testing and other discussions with @onezerojeremy and @jenniferthibault . I'm fine if you three sort it out. I don't think I have anything further to offer.

**Comment by LindsayYoung** [comment]
So we are all on the same page. I am adding the coverage dates and linking to the forms in the browse view that make up that total. 

![screen shot 2015-09-11 at 12 13 57 pm](https://cloud.githubusercontent.com/assets/4406333/9820072/84eb66a6-587f-11e5-97c7-f1e03b8f06ca.png)

@onezerojeremy can you confirm that this will be within the range of what user expect?

**Comment by onezerojeremy** [comment]
Sorry for the delay, just getting caught up on email/github messages. 

I do not think linking numbers directly to PDF forms is expected, and would probably advocate against it on this page. My sense is that looking at the PDF forms is more of a power user move. 

I think for now, I'd say let's hold off on linking at all.

**Comment by LindsayYoung** [comment]
I wan't thinking of linking to the pdf either, I was suggesting the filings browse view with the documents that make up that total.  At one time we had view data icons planned to link to things like that. At some point, I would like to have links that take users to underlying data for our totals.  Since there is confusion, I won't start this now. Thanks!

**Comment by leahbannon** [comment]
Ooh I like that idea, Lindsay

**Comment by noahmanger** [comment]
What's the status on this? Have we resolved it?

**Comment by LindsayYoung** [comment]
I added the link to the source forms as a line that says view source forms with a link18f/openFEC-web-app#710 That seems to be merged but I am not seeing it on dev.

**Comment by noahmanger** [comment]
Looking good.
