### ISSUE TITLE
Amendment Indicator should only have New or Amended on Candidate filings tab (issue #1)

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1154]
https://fec-dev-web.cf.18f.us/candidate/P60006111?cycle=2016&tabs=filings

Amendment Indicator should only have New or Amended. The other options don't apply to the candidate because the candidate only files form 2 and occasionally misc documents.

**Comment by noahmanger** [comment]
This table no longer has filters. Closing.
