### ISSUE TITLE
Report Type should be Removed from Candidate Filings Tab (tab issue #3)

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1156]
https://fec-dev-web.18f.gov/candidate/P60006111?cycle=2016&tabs=filings

Report Type should be Removed. Doesn't apply to form 2

**Comment by jmcarp** [comment]
No longer an issue; filters have been removed from the candidate filings view. See https://fec-dev-web.18f.gov/candidate/P60006111.
