### ISSUE TITLE
Candidate Filings list not showing Form 2 on candidate filings tab (issue #4)

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1157]
https://fec-dev-web.18f.gov/candidate/P60006111?cycle=2016&tabs=filings

Candidate Filings list not showing Form 2 which is pretty much the only thing that should be there along with disavowal notices.

**Comment by jmcarp** [comment]
Fixed in https://github.com/18F/openFEC-web-app/pull/523.
