### ISSUE TITLE
Committee Filings Tab duplicating operating expenditures

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1158]
https://fec-dev-web.18f.gov/committee/C00554261?cycle=2016

Expand the disbursements list and the top entry is duplicated. Looks like it might be a simple upper/lower case thing.

**Comment by leahbannon** [comment]
Expand how? View more results per page? Do you mean these two?

<img width="1032" alt="screen shot 2015-08-26 at 2 01 49 pm" src="https://cloud.githubusercontent.com/assets/4323988/9504686/22f31556-4bfb-11e5-848e-a591e39919ff.png">

**Comment by leahbannon** [comment]
Financial Summary tab > expand Total Disbursements

**Comment by LindsayYoung** [comment]
<img width="1070" alt="screen shot 2015-08-31 at 3 52 59 pm" src="https://cloud.githubusercontent.com/assets/4406333/9588835/6fe63644-4ff8-11e5-8eeb-14997e383f00.png">

**Comment by LindsayYoung** [comment]
So the second entry is really net operating expenditures, which will often be the same. I'll add "net" to the label.
