### ISSUE TITLE
Filings search form 1

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1159]
https://fec-dev-web.18f.gov/filings

Form 1s are listed as Document[year] instead of Form 1. Also the monetary values are populated with zeros where they should be null.

**Comment by LindsayYoung** [comment]
also posted 18F/openFEC-web-app#458

**Comment by noahmanger** [comment]
Let's not lose sight of the first part, which is coming up with a better name to display than just "Document".

**Comment by LindsayYoung** [comment]
Not having good names for documents is issue #544

**Comment by noahmanger** [comment]
Oops, just saw that. Thanks.

On Mon, Aug 31, 2015 at 9:39 AM, Lindsay Young <notifications@github.com>
wrote:

> Not having good names for documents is issue #544
> <https://github.com/18F/openFEC/pull/544>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1159#issuecomment-136424037>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by leahbannon** [comment]
Appears that this is covered elsewhere, so I'm closing. Please reopen if I'm wrong.
