### ISSUE TITLE
Filings search report type order

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1160]
The pulldown for report type needs to be in a more sensible order. Here is the order and grouping we've used in the past:

<table>
<tr><td class="titleCol">Report Type :</td></tr>
<tr style="height:25px;">
  <td width="360" valign="middle">
    <select class="multiSelect" multiple="" size="4" id="reportType" name="reportType" style="width: 340px">
	<optgroup style="font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 11px;font-style:normal;padding-left: 3px;margin-left: 0;" label="Monthly Reports">
						<option value="M2">February Monthly</option >
						<option value="M3">March Monthly</option >
						<option value="M4">April Monthly</option >
						<option value="M5">May Monthly</option >
						<option value="M6">June Monthly</option >
						<option value="M7">July Monthly</option >
						<option value="M8">August Monthly</option >
						<option value="M9">September Monthly</option >
						<option value="M10">October Monthly</option >
						<option value="M11">November Monthly</option >
						<option value="M12">December Monthly</option >
						<option value="YE">Year-End</option >
	</optgroup>
	<optgroup style="font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 11px;font-style:normal;padding-left: 3px;" label="Quarterly Reports">
		<option value="Q1">April Quarterly</option >
						<option value="Q2">July Quarterly</option >
						<option value="Q3">October Quarterly</option >
						<option value="YE">Year-End</option >
	</optgroup>
	<optgroup style="font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 11px;font-style:normal;padding-left: 3px;" label="Semi-annual Reports">
		<option value="MY">Mid-Year</option >
						<option value="YE">Year-End</option >
	</optgroup>
	<optgroup style="font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 11px;font-style:normal;padding-left: 3px;" label="Election Sensitive Reports">
		<option value="12P">Pre-Primary</option >
						<option value="12C">Pre-Convention</option >
						<option value="12G">Pre-General</option >
						<option value="12R">Pre-Runoff</option >
						<option value="12S">Pre-Special</option >
						<option value="30G">Post-General</option >
						<option value="30R">Post-Run-Off</option >
						<option value="30S">Post-Special</option >
						<option value="30P">Post-Primary</option >
						<option value="60D">Post-Election</option >
	</optgroup>
	<optgroup style="font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 11px;font-style:normal;padding-left: 3px;" label="Other Reports">
		<option value="TER">Termination</option >
						<option value="24">24-Hour Notification</option >
						<option value="48">48-Hour Notification</option >
						<option value="90D">Post-Inaugural</option >
						<option value="90S">Post-Inaugural Supplement</option >
						<option value="CA">Comprehensive Amendment</option >
						<option value="ADJ">Comprehensive Adjusted Amendment</option >
	</optgroup>
	<optgroup style="font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 11px;font-style:normal;padding-left: 3px;" label="Bundling Reports">
		<option value="M7S">July Monthly / Semi-Annual</option >
						<option value="MSA">Monthly Semi-Annual (MY)</option >
						<option value="MSY">Monthly Semi-Annual (YE)</option >
						<option value="MYS">Monthly Year-End / Semi-Annual</option 
						><option value="Q2S">July Quarterly/Semi-Annual</option >
						<option value="QSA">Quarterly Semi-Annual (MY)</option >
						<option value="QYE">Quarterly Semi-Annual (YE)</option >
						<option value="QYS">Quarterly Year-End / Semi-Annual</option >
						<option value="QMS">Quarterly Mid-Year / Semi-Annual</option >
	</optgroup>
				    </select>
  </td>
 </tr>
</table><option value="QMS">Quarterly Mid-Year / Semi-Annual</option >

**Comment by LindsayYoung** [comment]
covered in 18F/openFEC-web-app/issues/360
