### ISSUE TITLE
I created an example python implementation to fetch data from the api

### ISSUE THREAD

**Issue by manuganji** [18F/openFEC#1161]
Hey, do you think this is useful? [Link to my repo](https://github.com/manuganji/fec-api-crawler)

**Comment by leahbannon** [comment]
Cool, thanks! We love seeing how people are using the API. You might also want to play around with [this swagger feature](https://github.com/swagger-api/swagger-codegen).

**Comment by manuganji** [comment]
Wow! Thanks for telling me about Swagger, @leahbannon. How much time it saves  for everyone! :+1:
