### ISSUE TITLE
Differentiate Glossary links from normal links

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1167]
Usability testing revealed that individuals sometimes confuse the glossary links, which trigger an in-page modal drawer and normal links, which users use to a navigate to a new page. A tweak to the visual display is probably in order. 

![screen shot 2015-08-31 at 11 17 21 am](https://cloud.githubusercontent.com/assets/474916/9594337/bab07e76-5027-11e5-84b3-b1967b151bbf.png)
(the problem manifested itself in this screenshot when users clicked "total receipts" to trying to get to "money received"; my sense is that it could be a problem anywhere both link types exist )

Assigning to @jenniferthibault but as always, available to help, probably worth tagging @noahmanger as well.

**Comment by jenniferthibault** [comment]
We have a solution for this, I just don't think it was implemented. cc @noahmanger 

Glossary links won't be underlined, but will show the book icon. When you hover over the book (or click/focus on mobile/screen reader) the whole word will highlight itself, and then on click the glossary will pop out.

Regular links will have dotted underlines.

**Comment by onezerojeremy** [comment]
sounds perfect! 

(Just wanted to issue it so we didn't lose it.)

**Comment by jenniferthibault** [comment]
:+1: roger that — also getting it out of my head to keep track of it somewhere :)

**Comment by noahmanger** [comment]
Assigning to myself now.

**Comment by noahmanger** [comment]
Great. Sorry, I forgot we had that solution.

On Wed, Sep 2, 2015 at 7:30 AM, Jennifer Thibault <notifications@github.com>
wrote:

> [image: :+1:] roger that — also getting it out of my head to keep track
> of it somewhere :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1167#issuecomment-137103201>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
