### ISSUE TITLE
To help users find relevant committees, provide more emphasis on links to the candidate-committees on the candidate page

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1168]
Usability testing revealed that people were still a little unclear on the candidate -> candidate-committee hierarchy on the candidate page. The new designs demonstrated marked improvement over the previous iteration; in most cases users were eventually able to navigate to the candidate-committee page, but it wasn't their first instinct. 

![screen shot 2015-08-31 at 11 17 50 am](https://cloud.githubusercontent.com/assets/474916/9594523/d074a51e-5029-11e5-87c8-46f06c2906fc.png)

The task had to do with fundraising, and each test, the users clicked not the candidate-committee head link, but rather the "money received" link. This demonstrated that our newest iteration is clearly on the right track; clicking "money spent" in the candidate-committee card helps teach the user about the information hierarchy between candidate-committees and candidates. 

Providing a bit more emphasis on the child links "money spent", "money received" on the candidate-committee cards on the candidate page would probably go a long way, but there may be other solutions as well.

**Comment by LindsayYoung** [comment]
The money received link is a good link to click on that is the breakdowns of how much money the candidate's committee raised. 

Maybe we would want to add some top-line totals to in the receipts tab and disbursements tab so this answers the question for the users?

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/HcvodnQtnJIeXDnUEFZhfg

**Comment by jenniferthibault** [comment]
Updates addressed in Release 1:
![screen shot 2015-12-18 at 10 44 03 am](https://cloud.githubusercontent.com/assets/11636908/11900508/6553209e-a574-11e5-9442-d1443fae3b31.png)
