### ISSUE TITLE
Differentiate registration actions from registration learning links

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1169]
On the registration home page, registration options page, and congressional candidate checklist page, users were confused about whether a link would trigger an action, or provide more information about completing an action. For instance the "start your registration process" link on the registration homepage indicated to users that they'd be filling out a registration form, not in fact learning about the requirements of the registration process. 
![screen shot 2015-08-31 at 11 39 14 am](https://cloud.githubusercontent.com/assets/474916/9594613/1e1bb54a-502b-11e5-8e6a-c12e3b355a87.png)

This pattern reappeared on the registration options page
<img width="1014" alt="screen shot 2015-08-31 at 9 56 43 pm" src="https://cloud.githubusercontent.com/assets/474916/9594643/81ddba24-502b-11e5-9e5e-a6632f929645.png">

and on the checklist page. 
<img width="756" alt="screen shot 2015-08-31 at 9 58 17 pm" src="https://cloud.githubusercontent.com/assets/474916/9594649/915f04c6-502b-11e5-8535-869bcbbed175.png">

@emileighoutlaw has some proposed language here, plus it will probably go a long way to provide checklist items that involve both the actual link to complete the action (the "do") and the link to learn about the action (the "how").

**Comment by leahbannon** [comment]
Also the checkboxes (which I happen to love) seem to confuse people --> they think this should be something they actually check off like on a form.

**Comment by emileighoutlaw** [comment]
Once implemented, these revisions should address this issue: https://docs.google.com/document/d/1wyHWy6wAhVcMeHMaaEojUfvRrRhZXTEnYPMWl4Bj-q4/edit

**Comment by onezerojeremy** [comment]
I think these content revisions will absolutely help!

I also think we'll need to address the individual checklist item; though at this point I think it solving the microcopy issue will only take us half way: providing ways to start the process steps as well as learning more about the process steps seems like the right move.

**Comment by jenniferthibault** [comment]
I think it would be totally fine to remove the "checklist" interface from this. We could certainly make it a bulleted list, which at this point is more accurate. Maybe a downloadable checklist that people could print off themselves would be a nice bonus, but not launch critical. Does that help, @onezerojeremy ?

**Comment by onezerojeremy** [comment]
There are two things happening here: One is that, yes, I think that people do expect to click on the checkboxes, but I'm not sure that this is a big deal, as there are no repercussions of clicking in the boxes, and users quickly learn that it doesn't do anything.* What the checkbox visuals do that is important, I think, is convey the idea that these are things that they need to do. I'm of course amenable to any layout, boxes or not, that effectively indicates that folks need to do the things listed here. I fear that simple bullets would very likely not convey this. 

The second, and more important usability issue above is that the checklist items names indicate that they trigger actions, rather than what they actually are, which is open learning about actions. 
<img width="245" alt="screen shot 2015-09-04 at 2 00 23 pm" src="https://cloud.githubusercontent.com/assets/474916/9690949/5d4a3d38-530d-11e5-9e9e-5c65e860ae6e.png"> 
For instance, users thought that clicking on "register as a candidate" would actually link them to a form for doing such, as opposed to linking to a web page that would describe the process. Both of these (that is, learning about an action and taking that action) are totally reasonable things to assume, and further, I'd posit, are things that users should be able to do from this page. I think that a checklist item (and i apologize in advance for this copy) like this would successfully differentiate, but I'm sure there are other options. 


*- people mentioned being a little confused about the boxes, but no one was actually hung up on them, everyone who got to this page was able to finish the task. The tricky part of user testing is sometimes just to know what people are getting hung up on versus what they will react to, what might feel a little weird at first blush but might be helping them understand.

**Comment by jenniferthibault** [comment]
Good thoughts on the checklist-y-ness as required actions! I think we could also help people out a little bit if we were better about linking certain words, instead of all of them. @noahmanger and I talked about this for a minute yesterday.

For example instead of linking
 - [Register a candidate](#)
 - [Register a candidate committee](#)

We could do something like
- [Register](#) a candidate. [Learn more](#) about how and why

or
- [Register](#) a committee  |  [Learn more](#) about how and why


Def agree with @onezerojeremy 's strategy, but would look to @emileighoutlaw to help construct the right type of sentence that does this, with the aid of more thoughtful linking throughout the site.

**Comment by leahbannon** [comment]
This is fascinating :+1:

**Comment by emileighoutlaw** [comment]
I do like the sentences Jen suggest. Otherwise, what do you all think of
the content revisions I suggested here:
https://docs.google.com/document/d/1wyHWy6wAhVcMeHMaaEojUfvRrRhZXTEnYPMWl4Bj-q4/edit
?

**Comment by emileighoutlaw** [comment]
I think the Google doc ^^ does address the individual content issues by suggestion something like: 

Learn how to:
- Get a tax ID
- Get a bank account
- Get a treasurer
- Register as a candidate
            - Register now
- Register as a committee
             - Register now


Thoughts? I do very much like @jenniferthibault's microcopy suggestion, too.

**Comment by jenniferthibault** [comment]
Oof, sorry @emileighoutlaw, I missed the Google Doc entirely. Excuse the text-only mockup below, but adding in checkboxes and links, are we comfortable with the following format to move forward with?

**Learn how to:**
- [ ] Get a [tax ID](#)
- [ ] Get a [bank account](#)
- [ ] Get a [treasurer](#)
- [ ] Register as a [candidate](#)  |  [Register now](#)
- [ ] Register as a [committee](#)  |  [Register now](#)

Final point of clarity, I think, would be: do you prefer "Register" being the linked word on the last two, or the group name, as it is @emileighoutlaw ?

@onezerojeremy how does this square with you?

**Comment by onezerojeremy** [comment]
Oh sorry @emileighoutlaw, i read the doc, but totally missed the "learn how to" list head in my skim. I think I would like to A/B test it, but we don't have users yet. Yet.

If I had to choose, I think I'm probably leaning toward the sentence construction that @jenniferthibault put forth, if only for the reason that my skim didn't actually pick up the "learn how to" list head, and think others might not either (when scanning a web page, my intuition is that people are first looking for links, and possibly reading the words around them, and likely to miss words not in line with it). I also recognize that this makes the content job more complicated, as no one really want a list that has 7 "learn more"s in a row. :\

**Comment by jenniferthibault** [comment]
Yeah, I don't really want seven "Learn more's" in a row either. We could make the "learn how to" more prominent with a type treatment?

**Comment by emileighoutlaw** [comment]
I love Jen's construction. Let's definitely go with that!

For the others. I do think A/B testing would be :bomb:. In my gut I feel like with a bold *learn more about:* people will see and understand it. But that could just be because I really want them to.

**Comment by onezerojeremy** [comment]
let's try the bold prominent learn more. it's the simplest possible fix, right? 

if people are confused, we can revisit.

**Comment by emileighoutlaw** [comment]
I second that!

So, a bold "learn more" and then the suggested bullet points in the google doc, with the exception of "Register as a candidate" because I would like to go with Jen's "Register a committee | Learn more about how and why"  

?

**Comment by noahmanger** [comment]
Are we going with the "linking just a few words" approach too?

**Comment by leahbannon** [comment]
Yes --> that + very prominent "Learn how to" at the top (and we'll test to see if that worked)

**Comment by noahmanger** [comment]
Ok, how's this look?

![screen shot 2015-09-09 at 4 13 08 pm](https://cloud.githubusercontent.com/assets/1696495/9776488/b59ae74a-570d-11e5-9791-866e617a6f1f.png)

**Comment by leahbannon** [comment]
When I look at this, my eyes keep going straight to the checklist. And when I read "Get a tax ID" I think that's what will happen when I click on the link.

What if we did something that removed the "get a" action language? Like...

Learn more about things you will need:
- [ ] A [tax ID]()
- [ ] A [bank account]()
- [ ] A [treasurer]()
- [ ] Information about registering as a [candidate]() _link to actually registering is on the page this links to_

**Comment by noahmanger** [comment]
The main issue here was resolved by https://github.com/18F/fec-cms/pull/40

We can keep wordsmithing separately.
