### ISSUE TITLE
incumbent challenger wording

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1176]
Right now, there are quite a few instances, where the data doesn't make sense. I think we need to clean the data or apply some additional logic to how we display incumbent, challenger and open seat.

@paulclark2 any advice?

It seems to happen frequently for Senate races:
http://localhost:3000/elections/senate/MD/2016/
http://localhost:3000/elections/senate/CA/2016/
http://localhost:3000/elections/senate/FL/2016/

this discussion was started in 18F/OpenFEC-web-app#549

**Comment by noahmanger** [comment]
Whats the status on this?

**Comment by LindsayYoung** [comment]
This would be a breaking change on an endpoint that is getting a fair amount of use. 

Ideally, I would prefer to take a deep dive at the naming scheme and do another round of API testing. Then, have a versioned batch of changes. We could attack this piecemeal but I think a bunch of little breaking changes might annoy users.

**Comment by LindsayYoung** [comment]
OK, the data is still the same, but we are displaying it better on the web app. The way that ici is bing tracked creates some issues, but @PaulClark2 already knows this and has talked abut making it better. I am going to close this out for now.
