### ISSUE TITLE
Content review of api docs before launch

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1177]
To do, in order: 

- [ ] Are docs done and ready for review? Or do you expect more changes in the next few weeks?
- [ ] Leah edits
- [ ] Emileigh edits

**Comment by jmcarp** [comment]
As far as I know, the docs are ready for review, unless there's anything @LindsayYoung has in mind to change first. Will we want FEC to review the API docs as well?

**Comment by LindsayYoung** [comment]
Adding a rate limiting and page limit explanation would be good too, we don't explain that and it is  confusing users. It is a quick tweak that I can add today.

**Comment by leahbannon** [comment]
closed with #1233
