### ISSUE TITLE
404 page needs minor improvements

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1180]
This is the current 404 page. I'd like to change the language at the bottom to: "Still can't find what you're looking for? Contact support by [emailing us](18F-FEC@gsa.gov) or [opening an issue in GitHub](https://github.com/18f/fec/issues/new)."

It also needs some design fixes.

<img width="1042" alt="screen shot 2015-09-04 at 5 48 10 pm" src="https://cloud.githubusercontent.com/assets/4323988/9696457/48db9016-532d-11e5-93b6-72b114cf2b66.png">

**Comment by emileighoutlaw** [comment]
Good thought! How about:

`Get support by emailing us or opening a GitHub issue`

**Comment by noahmanger** [comment]
How's this look? 
![screen shot 2015-09-08 at 8 46 44 pm](https://cloud.githubusercontent.com/assets/1696495/9752920/c1067ce6-566a-11e5-89b7-4096a583c973.png)
