### ISSUE TITLE
Usability Testers were not able to find Super PACs support/oppose information

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1183]
In usability testing, users did not associate the activity of Super PACs in support or opposition of candidates with those candidates given election. They did not select "Search by Zip Code", or click "All Independent Expenditure Committees active 2015-2016" (though I think the later is not working) 

First and foremost, they attempted to find this information on the browse committees page, but were not successful as this does not contain opposition or support information. 

Second, some also looked on the candidate summary page, which also does not include Super PACs that are associated. 

Recommended action: 
This probably needs discussion, but some things that might be worth thinking about:
- including Super PACs associated (either supporting or opposing) on the candidate page. (would need to be designed)
- including Super PACs support information on committee pages.
- revising the navigation item "search by zip code". referenced in #1184  

Usability Task: 
You’ve heard that the presidential race has a lot of activity from super PACs Use the site to find out who they are supporting and opposing? 

tagging @jenniferthibault and @noahmanger as well: happy to have a chat on this one.

**Comment by jenniferthibault** [comment]
@onezerojeremy can you explain this first part a bit more?
> users did not associate the activity of Super PACs in support or opposition of candidates with those candidates given election. 

To be honest, I don't even know how I would go about doing this task. We don't use the words "super PAC" anywhere. If I can unravel what we're trying to lead people towards, hopefully i can help with a better solution!

**Comment by onezerojeremy** [comment]
The idea with the task was that people hear about super PACs (through the media, etc), and we now show who they are supporting and opposing [here](https://fec-dev-web.18f.gov/elections/president/2016/?tab=spending), which is awesome. 

I think this probably calls for a synchronous ixd discussion; but the short answer is that I think you're right, we don't use the words super PAC very often (it appears as a filter on the browse tables for committees). We also reference them by their technical name "Independent Expenditures Only Committees" on the Browse Homepage. 

![screen shot 2015-09-08 at 8 14 56 pm](https://cloud.githubusercontent.com/assets/474916/9750481/73db7fd8-5666-11e5-93bd-7f47339a5d60.png)

Going in to user testing last week one of the things I wanted to find out was if our users identified _Independent Expenditure Only Committees_ as _Super PACS_, **and** if they look for them with respect to elections. What we found is that people are not necessarily familiar with the terminology, and do not necessarily associate it with elections. 

 My guess is that including a table showing "Super PAC spending supporting/opposing with this candidate" on the candidate page would go a long way; similarly, showing "Candidates this Super PAC supports or opposes" on the committee page would also be helpful. Obviously this language is clunky; just trying to talk about the information I'm trying to describe first. 

I'm not sure if that helps or not, @jenniferthibault.

**Comment by emileighoutlaw** [comment]
Ohh. Interesting though. 

Something like:
_Super PAC spending supporting and opposing this candidate_
_Candidates this Super PAC supports and opposes_

?

It seems like the "and" construction is right to me, because they're shown together on the outside spending page.

**Comment by LindsayYoung** [comment]
I would love outside spending on the candidate pages and if this conclusion is supported by user research, I think that makes the case stronger. 

I also think that a more prominent link from the candidate page to the election page would also help people find that great page.

**Comment by noahmanger** [comment]
New issue for implementing IEs on candidate pages here: https://github.com/18F/openFEC-web-app/issues/700

New issue for figuring out a solution to showing "other spending" on committee pages here: https://github.com/18F/openFEC-web-app/issues/701
