### ISSUE TITLE
Super PACs check box on browse committees is often obscured by the PACs dropdown

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1185]
Super PACs check box on browse committees is often obscured by the PACs dropdown, where people often look for it. 

URL: https://fec-dev-web.18f.gov/committees?cycle=2016&cycle=2014&cycle=2012

![superpacs](https://cloud.githubusercontent.com/assets/474916/9745505/410b8ee8-5640-11e5-8edb-d6fc6528e09a.gif)
It's also not clear to users that Super PACs are not available in the committees drop down. 

Recommendation is to move it above committees, or possibly include it in the committees. I suspect that it may have been there at one point but was moved (possibly even before I was onboarded). 

Uncovered in usability testing task: 
You’ve heard that the presidential race has a lot of activity from super PACs Use the site to find out who they are supporting and opposing?

**Comment by noahmanger** [comment]
Nice catch! I think it makes sense to have it broken out form regular PACs, but I like the idea of maybe moving it above. I could also see moving all of the various committee type filters above the "party" and "state" filters, which really are less important I think.

**Comment by onezerojeremy** [comment]
Moving super pacs above the committee dropdown sounds like it'll help immensely. 

We don't yet have any usability testing data to suggest moving all the committees up above state is necessarily warranted; my uninformed guess is that the committee filter is more advanced and that lay users will more likely be looking by state and party than committee type, so I guess I'd advocate for waiting until we can determine filter usage before the larger resort.

**Comment by noahmanger** [comment]
Makes sense to me. Assigning to me to move.
