### ISSUE TITLE
clean data

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1189]
Delete P60012184, the candidate is expired but still showing up in our systems.

**Comment by AlJohri** [comment]
http://www.fec.gov/fecviewer/CandidateCommitteeDetail.do?candidateCommitteeId=P60012184&tabIndex=1

still seems to be showing up for me

**Comment by LindsayYoung** [comment]
Thanks for writing in!

This repo is only for the beta.fec website and the open.fec API

It doesn't' show up here https://beta.fec.gov/data/?search=trump&search_type=candidates
