### ISSUE TITLE
Poor Documentation

### ISSUE THREAD

**Issue by pulkitnandan** [18F/openFEC#1191]
May be only me but this thing doesn't works, none of the installations works and nowhere it is explained why to go through such installations, where is the rest api? api.bla bla bla says rest api at api.v2 while suffix works for v1,  I need to track my network request on wireshark to get that.

**Comment by LindsayYoung** [comment]
Sorry about the typo, the API is on v1 We will fix that.

**Comment by LindsayYoung** [comment]
Thank you for reporting that we have deployed a fix. Please tell us if there are any other things we can do to improve our documentation. 

h/t to @jmcarp for figuring out the swagger compiling issue!

**Comment by pulkitnandan** [comment]
I'm stuck @ tmuxinator fec-local where it fails with error.
In installation steps it doesn't mentions to install packages virtualenv virtualenvwrapper using pip or directory from ubuntu's repository, neither that tmuxinator is to be installed from gem.

Can this github repo be used to setup an local api and thus making unlimited calls to the api.
I'm currently trying to create a system that will need to be scheduled to check for any updates in data. So this 100 calls per hour limits my maintenance script.

**Comment by LindsayYoung** [comment]
You can set up the API with a subset of test data. If I am understanding you correctly, that doesn't sound like what you want.

The good news it that you can make 1,000 calls an hour. You are limited to 100 results per page to keep the API from crashing. 

We are happy to help optimize your queries if you are having issues. Additionally, the FEC provides [bulk data](http://www.fec.gov/finance/disclosure/ftpdet.shtml) for those cases where you need all the data.
