### ISSUE TITLE
In order to help users learn the size of the data set through the relative scale of the in-line bars, consider basing the scale on the whole data set, not just the page visible.

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1197]
The bars that represent relative size on the occupation tab here:
https://fec-stage-web.18f.gov/committee/C00000422?cycle=2016&tab=receipts

change based on the page. So in the example above a $3000 row on page 1 has a tiny bar because of a very large bar in row #1. On page 2 a $1500 row has a huge bar because it is the biggest on the page.  I think the bars should be based on the largest in the set no the largest on the page.

**Comment by noahmanger** [comment]
Closing this in favor of similar issue filed here https://github.com/18F/FEC/issues/133
