### ISSUE TITLE
In order to show users the filing information most helpful to them, decide which columns to show and sort in the filings tab.

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1198]
The filings tab is an odd place to have "total Independent Expenditures" as a column. Most filing entities don't report those. Only form 3X, form 5 and form 24 filers. Also, the choice to sort by amount columns is unusual here. Maybe not a bad idea but not at the cost of sorting by ending coverage date.

I would think document type, Receipt Date and Ending coverage dates would be the three most important sorting columns (plus a logical complex sort by default and a button to return to the default sort. 

For internal users Beginning and Ending image numbers and page count will be way more important than dollar amounts in the filings grid.

**Comment by noahmanger** [comment]
I agree. We should be sorting by coverage date here. I think we used to have it and maybe it broke in a recent update. 

@LindsayYoung what do you think about the IE question? Can we infer from the type of committee whether or not it makes sense to show this column?

**Comment by PaulClark2** [comment]
@jwchumley @noahmanger @LindsayYoung @jmcarp 

Agreed the columns currently being displayed on the filings search result pages are not useful.  We should not display Total receipts, Total disbursement or Total independent expenditures on the filings tab.  Page counts and image numbers are much more useful here.  

![untitled](https://cloud.githubusercontent.com/assets/11817734/9876223/6bd6332a-5b82-11e5-89c2-f6029d3ff4d8.png)

**Comment by LindsayYoung** [comment]
Form a reporter's standpoint, the totals are handy for sorting to find the biggest filings in a given time period. 

We can add sorting to coverage date- we just need to add an index and tweak the code. 

I would still like to add the preview panes for more information for this view.

**Comment by jwchumley** [comment]
The number of pages identifies the larger reports too and takes up a lot less space. The columns in our current filings view have been pretty carefully worked out over time to fill the needs of the internal users. Adding columns OK. I don't think leaving out existing columns is a good idea. 

![image](https://cloud.githubusercontent.com/assets/12615919/9878464/d3fb9644-5b90-11e5-93d7-bba5e9e88fd1.png)

**Comment by PaulClark2** [comment]
I agree with @jwchumley .  If we do add financial columns we should include "total receipts," "total disbursements," "debts owed" and "cash on hand."  If we include financial columns on the filings page, we should not include "total independent expenditures."

**Comment by jmcarp** [comment]
As a temporary fix, we're hiding the independent expenditures column as of https://github.com/18F/openFEC-web-app/pull/675. Longer term, let's decide which columns to show. We're planning on adding detail overlays for more form types, so eventually we'll be able to click on any row in the filings table for a more complete representation of the filings. Let's continue discussion here.

**Comment by noahmanger** [comment]
This is a sub-component of the broader issue here: https://github.com/18F/openFEC-web-app/issues/815

Referencing this and closing it as a duplicate.
