### ISSUE TITLE
Receipt aggregates by contributor type are overestimated

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1203]
Aggregated receipts by contribution type (individual vs non-individual) often add up to far more than the candidate's reported totals. For example, Obama for America's total receipts in 2011-12 were about $740m, but the sum of its individual and non-individual aggregates for the same period are over $1.4b. I'm guessing this is because we're double-counting some earmarked contributions. We're using a formula from @jwchumley and @paulclark2 to exclude earmarks in aggregates by state, contribution size, etc., but it doesn't seem like those rules would make sense for this aggregate, since they exclude all non-individual contributions. I suspect that the same issue applies to aggregated receipts by donor committee.

@jwchumley and @paulclark2: is there a good way to exclude duplicate contributions for receipts that don't all come from individuals? Let me know if the question isn't clear--happy to chat about this sometime if not. This doesn't need to be addressed before our meeting on Wednesday, but should definitely be resolved before launch.

h/t @noahmanger @leahbannon

**Comment by LindsayYoung** [comment]
I think we should get contributor type from the summary data instead of adding the line items.

**Comment by jmcarp** [comment]
@LindsayYoung that's an option for individual vs non-individual contributions, but not for aggregated receipts by committee. Which is a good start. Can we infer non-individual contributions by subtracting individual contributions from total contributions, or do we have to account for details like amount of refunded individual contributions?

**Comment by LindsayYoung** [comment]
We could take this as an opportunity to give some better breakdowns. Individual giving is important but we could also show loans, transfers, candidate contributions, party contributions etc.

**Comment by LindsayYoung** [comment]
To be clear, we don't need to add the other types before launch.

**Comment by jwchumley** [comment]
I started looking at this when you first posted it and have gotten side tracked. I think one big thing might be line 17 transfers. They have similar issues to earmarks. A single transfer for a presidential candidate may have a value in the tens of millions and have thousands of supporting items thus pretty much doubling the total. I'll post some examples in a few minutes.

**Comment by jwchumley** [comment]
@jmcarp : Are the inflated numbers coming from line 18 (presidential)?

There are multiple uglinesses going on here. First, transfers from joint fundraisers will pretty much never add up. In the case below there was a lump sum transfer of $28,500,000 from Obama Victory Fund.  This probably was devided between Obama for America and the DNC so the total amount raised isn't reflected there. They also report all the contributors from the joint fundraiser as code 15j transactions but they include all of them so if you sum them up you get $39,841,186.96. 

Ugliness #2. Splitting large transactions.
In Obama for America's 2012 M10  the $28,500,000  transfer has tran_id C22557505. At that time our amount column wasn't wide enough to take it so we had to delete it and re-enter it as three $95,000,000 transactions giving a suffix to the tran_id as follows:
C22557505_S000
C22557505_S001
C22557505_S002

Whether that is ugly or not really depends on what we decide to do about the numbers. More on that later.

The actual correct amount that shows how much money Obama for America received is $28,500,000 as they reported on their summary page for line 18. If you sum the 15J transactions you will be including money that didn't go to Obama for America even though the transactions are on the report. I know. Bummer.

So technically I think if you want to sum the transactions you have to sum the lump sum transfers and not sum the memo entries that show each person's contribution. Anyone that adds them up will see a big difference but we'll have to account for that in the glossary section about transfers.

 @paulclark2, what do you think?

**Comment by PaulClark2** [comment]
I knew we had some words to explain this.  Christian helped me find them:  

Pages 137-144 of the FEC's Campaign Guide for Congressional Candidates and Committees: http://www.fec.gov/pdf/candgui.pdf:

"Before conducting a joint fundraiser, all participants must enter into a written agreement that identifies the joint fundraising representative and states the allocation formula—the amount or percentage that the participants agree to use for allocating proceeds and expenses."

"After the joint fundraising representative distributes the net proceeds, each participating political committee reports its share as a transfer-in from the joint fundraising representative on Line 12 (Transfers from Other Authorized Committees) and itemizes the transfer on a separate Schedule A for that Line. Using the records received from the joint fundraising representative, a participating committee also must itemize its share of gross receipts as contributions from the original donors on a memo entry Schedule A (to the extent required by the rules on itemization—see Chapter 13, Section 4). When itemizing gross contributions, the participant must report the date of receipt as the day the joint fundraising representative received the contribution. 102.17(c)(3)(iii) and (c)(8)(i)(B)."
