### ISSUE TITLE
Improve performance on receipts and disbursements queries

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1204]
Some queries against the receipts and disbursements tables are slower than expected. Performance should be improved here. Slow queries may include the following:

* [ ] Queries by state or city for rare states and cities
* [ ] Full-text queries against disbursement purpose
* [ ] Full-text queries combined with other filters

I'd like to get all of these queries, and anything else that folks find, to respond within a few seconds at most. I have some ideas about improving performance here and will update the issue as queries get faster.

h/t @leahbannon

**Comment by LindsayYoung** [comment]
Sorting by amount takes a while too
