### ISSUE TITLE
Contributor_occupation in sched A broken

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1208]
give a server error on dev, work on production.

**Comment by LindsayYoung** [comment]
This works for me locally on the dev branch.

**Comment by jmcarp** [comment]
Looks like we need to rebuild the fulltext table. Will close when that's done.

**Comment by noahmanger** [comment]
Just curious: does this issue fit any sort of pattern? Or is it just a random glitch. Trying to think of how we can systematically catch / prevent it in the future.

**Comment by jmcarp** [comment]
Fixed in #1218. @noahmanger this should be something we can monitor more proactively with newrelic--I'll look into this post-launch.
