### ISSUE TITLE
Add banner to dev and staging denoting them as such

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1216]

**Comment by leahbannon** [comment]
- [ ] @emileighoutlaw write content
- [ ] @jenniferthibault design
- [ ] @noahmanger implement

**Comment by jenniferthibault** [comment]
I'm not sure what these typically look like, so feel free to send examples of others, but here's one straightforward concept. The grey would distinguish it from the rest of the design, since it's not a color in our palette.

Questions in my mind: should it be fancier? more designed? what's the interaction here, and is there any desired functionality?

![screen shot 2015-10-01 at 12 44 50 pm](https://cloud.githubusercontent.com/assets/11636908/10227258/46e908e8-683a-11e5-89cd-521002806b91.png)

**Comment by emileighoutlaw** [comment]
I think this looks beautiful (as always) @jenniferthibault! I think the content looks good, too— but I've also never this type of banner copy before, so I'm curious if @leahbannon wants to weigh in on that piece.

**Comment by leahbannon** [comment]
I think the main interaction/functionality here is that a new user would notice right away that they are not on the main site. So this looks good to me -- perhaps it should be a little more noticeable?

**Comment by jenniferthibault** [comment]
@emileighoutlaw I asked around and was shown the example of CAP: dev https://c2-dev.18f.gov/ vs production https://cap.18f.gov/ Based on these I tweaked the original lingo a bit, but what do you think is best?

A few more higher-contrast color options:

Black:
![menu - 0 copy 2](https://cloud.githubusercontent.com/assets/11636908/10343921/6b0c16c6-6cee-11e5-8797-d204a10b8b5d.png)

Dark red:
![menu - 0 copy 3](https://cloud.githubusercontent.com/assets/11636908/10343920/6b0bca5e-6cee-11e5-817f-8ae72da3b7da.png)

Bright red:
![menu - 0 copy](https://cloud.githubusercontent.com/assets/11636908/10343919/6b0997c0-6cee-11e5-986e-d63a996f0ddb.png)

All are 508 :+1:

**Comment by carodew** [comment]
_nosing in_

I like the plain language. As for color, I think black is too easy to overlook, but I think the red is too alarming. Maybe there is a middle ground? $0.02

**Comment by carodew** [comment]
Or could you explain to the lay person "this is where we test out code and not everything may work as expected. Feel free to look around but if you really need X, check out the official site here." 

Could be wordsmithed, just an idea.

**Comment by jenniferthibault** [comment]
I'm with you on the colors @carodew The bright feels like it's an error of sorts, but the dark red fits with the color palette too much on later pages. I'd like to go with this blue for now #164F85, which is in the palette so doesn't feel out of place, but isn't used in big swatches, so won't blend in to other pages. 

![menu - 0 copy 4](https://cloud.githubusercontent.com/assets/11636908/10345412/6c7941e2-6cf7-11e5-9cbe-87948e9d464c.png)

Lingo: do your thing @emileighoutlaw :)

**Comment by emileighoutlaw** [comment]
I think Carolyn's language suggestion raises an interesting point — if someone stumbles on this site, do we want them to poke around? 

I'm leaning toward something like:

`This site is for testing new ideas and code. View the most accurate data on the live site.`

The language is pretty soft and doesn't tell people they *should* redirect — my thought is that folks who reaallyy want to check it out will.

**Comment by jenniferthibault** [comment]
Seems like a good place to start to me! I'd say this is ready for implementation @noahmanger.

"Staging" Headline is Karla bold, all caps
copy underneath is Karla Regular
Blue is #164F85

![menu - 0 copy 4](https://cloud.githubusercontent.com/assets/11636908/10370406/a181cfca-6dac-11e5-8c23-e9ab0a4b0148.png)

**Comment by noahmanger** [comment]
Question on this: do we need to distinguish Staging from Develop? Or can we have a generic banner that simply differentiates them both as not being production? @leahbannon ?

**Comment by jenniferthibault** [comment]
I think it would be helpful (at least to me, use case of 1) for it to be specific. Even if it's just the title that changes (though descriptor text changes would be A++)

**Comment by noahmanger** [comment]
I suppose if we want to move to a set up where we have different staging and dev environments this would be helpful. @jmcarp can we set separate variables for dev and staging?

**Comment by emileighoutlaw** [comment]
To my thinking, it seems we can use the same text and just change the header to `Staging` or `Development` ?
