### ISSUE TITLE
Social media metadata needed for CMS sites

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1217]
This is from my notes but I don't remember what it means. @jmcarp do you? :grin:

**Comment by LindsayYoung** [comment]
I think this was for social media badges.

**Comment by leahbannon** [comment]
Ah yes! Thanks!

**Comment by jenniferthibault** [comment]
@noahmanger see https://github.com/18F/openFEC-web-app/pull/764 for images, or if you can show me where to put them, I'm glad to start a branch for this

**Comment by jenniferthibault** [comment]
https://github.com/18F/fec-style/pull/118 Put all the images into the FEC-style repo

**Comment by noahmanger** [comment]
Done
