### ISSUE TITLE
Identify amended Schedule E transactions

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1226]
Unlike the Schedule A and B tables, which are updated in place when amendments are filed, the Schedule E table may include multiple amended versions of the same transaction. That's why @noahmanger noticed the same PAC both supporting and opposing Hillary Clinton in #742. @paulclark2 explained that this happening because Schedule E transactions that are reported on 24- and 48-hour reports haven't been aggregated by unique transaction. In the long term, we'll want to figure out how to properly group those transactions, but this may be complicated and will probably have to be handled by @paulclark2 and @jwchumley (I'm happy to help but much less familiar with the details of the data). In the short term, @paulclark2 and I agreed that we should exclude Schedule E transactions from 24- and 48-hour reports from the aggregates. That means we'll be missing some data, but at least we won't be counting multiple versions of the same transaction.

I'll put in a quick patch to implement tonight. If we go with this approach for the time being, we'll need some explanatory text, probably from @emileighoutlaw. Also flagging @LindsayYoung and @noahmanger for thoughts on this.

**Comment by dwillis** [comment]
I agree that handling Schedule E transactions is complicated, but I think excluding them from 24 and 48-hour reports makes the API much less useful from a timeliness standpoint. Imagine this scenario: multiple IE reports come in on the Monday before a Tuesday election, but don't get into the API until the following week.

**Comment by jmcarp** [comment]
To be clear, this issue is only talking about aggregated Schedule E data by candidate. We'll continue to include all available Schedule E transactions in the itemized view.

**Comment by LindsayYoung** [comment]
To re-iterate we are not filtering out any data from the api, this is just for a methodology to figure out how much outside money is used to oppose or support certain candidates.

Filings will be available here: 
   [https://api.open.fec.gov/v1/filings/?api_key=DEMO_KEY](https://api.open.fec.gov/v1/filings/?api_key=DEMO_KEY)
The line items will be available here:
   [https://api.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY](https://api.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY)
