### ISSUE TITLE
In order to improve query performance, evaluate partitioning on large tables.

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1228]
@arowla has suggested that partitioning should speed up writes, and possibly also reads, on our large tables, `sched_a` and `sched_b`. I'm optimistic that this will improve performance, but also uncertain about read performance on queries that span many (or all) partitions, such as a query for the 30 largest contributions:
```
select * from ofec_sched_a order by contb_receipt_amt desc, sched_a_sk desc limit 30;
```

In the best case, this will have to run a subquery for each partition, sorted by amount and primary key, then combine and re-sort and limit the results. Which still might be pretty fast--the query planner is generally pretty smart. I think we should run some simple tests on simulated and/or real data to decide whether this is a good strategy.

Definitely a post-launch task.

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/m05dWp2-irq2HznUEHzR2Q

**Comment by LindsayYoung** [comment]
Partitioned tables are now in dev!
