### ISSUE TITLE
Change incumbent_challenge and incumbent_challenge_full to use challenger

### ISSUE THREAD

**Issue by dwillis** [18F/openFEC#1231]
The Candidate response includes two attributes, `incumbent_challenge` and `incumbent_challenge_full`, which represent the status of the candidacy (the values being I for Incumbent, C for Challenger and O for Open Seat). Since the full value for C is Challenger, for consistency's sake I think the attributes should be `incumbent_challenger` and `incumbent_challenger_full`.

**Comment by LindsayYoung** [comment]
Thanks for the suggestion, it makes sense. There are a few other naming inconsistencies we want to tackle too.
