### ISSUE TITLE
Missing data on C00326801

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1232]
The July Quarterly filing for committee C00326801 (TAMMY BALDWIN FOR SENATE) reports $129,290.69 for total contributions for the period, but the `ttl_contb_per` value for the corresponding report in `facthousesenate_f3` is $0.

The original image: http://docquery.fec.gov/cgi-bin/fecimg?201507200200209270
The data in the fact table:
```
fec=> select ttl_contb_per, * from facthousesenate_f3 where cmte_sk = 10028863 and two_yr_period_sk = 2016;
 ttl_contb_per | facthousesenate_f3_sk | form_3_sk | cmte_sk  | reporttype_sk | two_yr_period_sk | transaction_sk | cvg_start_dt_
---------------+-----------------------+-----------+----------+---------------+------------------+----------------+--------------
     154768.21 |              10291704 |   1867411 | 10028863 |      10000033 |             2016 |        1867411 |        100149
          0.00 |              10470896 |   4926184 | 10028863 |      10000034 |             2016 |        4926184 |        100150
(2 rows)
```

@paulclark2, can you take a look?
cc @LindsayYoung

**Comment by LindsayYoung** [comment]
I am not seeing an update to the Baldwin error.

**Comment by PaulClark2** [comment]
Baldwin's 2015 Q2 still has not processed correctly.   The raw data file has multiple issues.   I'm working with EFO and the data entry contractor to get this resolved.

**Comment by PaulClark2** [comment]
Baldwin's 2015 Q2 processed into the DB correctly last night.  

select ttl_contb_per, * from facthousesenate_f3 where cmte_sk = 10028863 and two_yr_period_sk = 2016;

**Comment by LindsayYoung** [comment]
:+1: 
Looks right to me. Thanks Paul!
