### ISSUE TITLE
To have good data, Proactively identify data errors

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1234]
So far, we've been identifying data entry errors one by one, as interested folks report them to us. This is time-consuming, and it means that data errors may be in the wild before we find and fix them. I'm wondering if we can take a few basic steps to identify data errors before users encounter them. For example, total contributions by period as reported on Form F3 is supposed to be entered as the sum of contributions from individuals, party committees, other political committees, and the candidate. If the total contributions value isn't the same as the sum of those four values, we can infer that there was either a data entry error or a filer error. It might be worth identifying these suspicious filings and reviewing them (or a subset) manually to catch errors. This kind of procedure might have helped us catch issues like #1232 more quickly.

These records aren't hard to find. For the example above, the following query finds filings where the totals are off by over $100:

```
fec=> select count(*) from facthousesenate_f3 where abs(ttl_indv_contb_per + pol_pty_cmte_contb_per + other_pol_cmte_contb_per + cand_contb_per - ttl_contb_per) > 100;
 count
-------
  1209
(1 row)
```

Curious to hear what @paulclark2 and @jwchumley think about this.
cc @LindsayYoung @noahmanger

**Comment by LindsayYoung** [comment]
I like this idea, maybe we should make a list of the biggest discrepancies and check those?

**Comment by PaulClark2** [comment]
I think it's a good place to start @jwchumley

**Comment by jwchumley** [comment]
I'm looking at these. There are several issues. Many are simply filed with numbers that don't add up but there are several categories that we can improve. 

First, on your end. We often deal with the fact that there are two places to put several of the numbers on the forms such as total contributions which appears on the detailed summary page and also on the summary page (where you are supposed to take the calculated value from the detailed summary page and plug it in). Sometimes the numbers don't match. In most cases you should just display the one on the summary page but if one is populated with a non zero number and the other is null or zero then use the non zero number. 

Unfortunately the other is me plowing through and fixing stuff. Joy. I'm working on it.

**Comment by jmcarp** [comment]
@PaulClark2 and @jwchumley: Could you describe what kind of automated checks RAD or other teams are already doing on the data, and if there are differences in checking between the Oracle DB and the DW? Sometimes it seems like one database has the right data while the other doesn't.

What I'm imagining here is a set of sanity checks that we run periodically, which would produce a digest of new data that require manual checking. Off the top of my head, sample checks might include:
* Verify that subtotals (approximately) add up to totals
* Verify that each election has (approximately) one incumbent
* Verify that filings have feasible dates

If this kind of thing would be useful, I can start assembling a few sanity checkers and expand them as we encounter new and exciting issues. Suggestions welcome @LindsayYoung.

**Comment by LindsayYoung** [comment]
Could we also check for report year, since it causes problems for committee information when it is absent.

**Comment by LindsayYoung** [comment]
Looking for non-unique image_ids in filings

**Comment by noahmanger** [comment]
Storymap card: https://18f.storiesonboard.com/m/fec/!card/hbgu5GvJC_3_gznUD8RvAQ
