### ISSUE TITLE
Form F11 filings have report_year set to 0

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1235]
All rows in `vw_filing_history` with `form_type` of "F11" also have `report_year` set to 0. Is this expected @paulclark2 @jwchumley? No urgency on this--we're putting in a patch to resolve a related issue on our side, and the number of relevant filings is very small.

**Comment by PaulClark2** [comment]
@jmcarp Nope they should have report years.  

FYI:  Form 11 only existed from 2002 to 2008.  It was a requirement of the "Millionaire's Amendment" of the BCRA.  The Supreme Court ruled the "Millionaire's Amendment" unconstitutional in 2008.

**Comment by jmcarp** [comment]
@PaulClark2 interesting! All right, sounds like we should get this fixed--does this view come from the data warehouse or someplace else? Once that's done, I'll revert the workaround that I added to our code today.

**Comment by PaulClark2** [comment]
This has been fixed:  select * from vw_filing_history where form_type = 'F11' and report_year is null;

**Comment by LindsayYoung** [comment]
Thanks Paul
