### ISSUE TITLE
candidate status issue

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1244]
Compare candidate status and name. 

https://api.open.fec.gov/v1/candidates/?api_key=DEMO_KEY&q=obama&cycle=2012
https://fec-dev-api.18f.gov/v1/candidates/?q=Obama&cycle=2012

**Comment by LindsayYoung** [comment]
This might be a data error, rather than a logical error.

I am looking at dimcandproperties with candproperties_sk =10100408
The receipt date for that record is 2015-09-26 -- I think it should be 2011-04-04

@PaulClark2 - I think this is new I spot check that record frequently. Is it possible that the data warehouse is generating new receipt dates when data is bing fixed?

**Comment by PaulClark2** [comment]
No, I don't think so.  9/26/15 is the correct receipt date for Obama's most recent F2.  He filed a F2 amendment on 9/26/16, docquery.fec.gov/pdf/752/201509269002783752/201509269002783752.pdf

![untitled](https://cloud.githubusercontent.com/assets/11817734/10234325/b6b087f6-6861-11e5-886f-92e13f5e91b4.png)

**Comment by LindsayYoung** [comment]
Hey Paul, thanks for looking into the Obama record. It's good to know it is not a wider issue. 

It looks like there is a data problem. The record I am seeing has null cand_status and cand_ici in the dimcandproperties table. 

It looks right on the dimcandstatusici table. If I remember correctly, we started off using that, but there were inconsistencies there too.

**Comment by PaulClark2** [comment]
Not sure why.   The most recent F2 for Obama has ICI and Status information.  I entered a F2Z for both Obama and Romney to correct a name display issue.  I included the ICI and Status information in the 2Z.  Let's see if that resolves the issue in dimcandstatusici.

![untitled](https://cloud.githubusercontent.com/assets/11817734/10252115/55e629c4-6903-11e5-8b0e-8cffdccbec4f.png)

**Comment by LindsayYoung** [comment]
Thanks Paul!

**Comment by LindsayYoung** [comment]
It's correct again. Thanks Paul!
