### ISSUE TITLE
In order to make it easier to use fec_bootstrap.sh, don't ignores command failures

### ISSUE THREAD

**Issue by evankroske** [18F/openFEC#1246]
If any of the commands run by fec_bootstrap.sh fail, I think that the script should exit immediately.

- [ ] Add `set -e` to fec_bootstrap.sh.

http://www.gnu.org/software/bash/manual/bashref.html#The-Set-Builtin

**Comment by noahmanger** [comment]
Thanks for letting us know. I just re-wrote the issue title to match a new format we're trying, but here was the original for posterity's sake. We'll look into this.

**Original title:** fec_bootstrap.sh ignores command failures but shouldn't

**Comment by evankroske** [comment]
I was mistaken: `set -e` is not the way to go:

http://david.rothlis.net/shell-set-e/

Apparently, ending each line with `&&` has more-predictable semantics than `set -e`.
