### ISSUE TITLE
primary/unique key in models such as filings & reports

### ISSUE THREAD

**Issue by pulkitnandan** [18F/openFEC#1247]
While trying to create a local cache for queries to api.open.fec I'm stuck to figure out a way to update my local database using the fec's schema which states no unique key for schema's such as filings. So how can my database be consistent with the fec's api one where I'm periodically querying fec's api for data and as there's no primary key, I can't update a record at my end, while I can stop duplicate insertion by query sql db that a particular row is present or not. Is there anything I'm missing in respect to my database or fec's api is not meant for such things.

**Comment by LindsayYoung** [comment]
For filings,  beginning_image_number and ending_image_number are unique, as is the document's url, which is based on the beginning image number. 

Hope that is helpful!

**Comment by pulkitnandan** [comment]
Oh Ok. Yes it solves my issue.

Thanks

**Comment by LindsayYoung** [comment]
That shouldn't happen, we will look into the cause of that.

**Comment by LindsayYoung** [comment]
That was due to a data error and the FEC has fixed it. Thanks for taking the time to report this and make the project better.

**Comment by fedex1** [comment]
I agree with @pulkitnandan that it would be helpful to have a single UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier)  and it would be helpful if the openfec API was consistent across all endpoints.

For example, add uuid field for each endpoint.

My question is specific to Schedule A

See http://www.fec.gov/finance/disclosure/metadata/DataDictionaryContributionsbyIndividuals.shtml

There seems to be a lot of references to "unique" but none of the fields are actually unique for the individual contribution.  Even when used in combination.

![screenshot from 2015-10-20 10 31 14](https://cloud.githubusercontent.com/assets/167614/10610532/4b031370-7716-11e5-93bc-e980dd02c084.png)


Can you tell me what the UUID is for Schedule A API https://api.open.fec.gov/v1/schedules/schedule_a

**Comment by LindsayYoung** [comment]
For `schedule_a`:
`file_num` in the bulk data should translate to `file_number` in the API.
`sub_id` should translate directly to `sub_id` in the API.

Tell us if you are you getting non-unique results you getting different results than the bulk data.

Thanks!

**Comment by fedex1** [comment]
Hi @LindsayYoung 

Thanks for answering.

It appears `file_number` is ONLY unique to the particular form submitted  (just a guess)

But the form can contain thousands of individual contributions.

And the `sub_id` does NOT uniquely describe the individual contribution.

It appears that `tran_id` is the field that uniquely identifies the individual contribution but it seems to apply only to electronic submissions

And in fact, I see cases where the actual form has a DIFFERENT Transaction ID than the API results.

see http://docquery.fec.gov/cgi-bin/fecimg/?15020176457

In fact, why is there a `transaction_id` and `tran_id` in the API results?

![screenshot from 2015-10-20 11 17 16](https://cloud.githubusercontent.com/assets/167614/10611881/3a710ee4-771c-11e5-9de6-4a11379db6f3.png)


And the API shows:

![screenshot from 2015-10-20 11 12 58](https://cloud.githubusercontent.com/assets/167614/10611770/968de504-771b-11e5-975a-92b155776c9e.png)

Why is the transaction id  VN874BSJ4Y9 in the actual form and tran_id: 'SA07101564575722' and transaction_id: 2298378 in the API results?

**Comment by LindsayYoung** [comment]
Thank you for reporting this in detail!

For the API we are trying to give you all the information we have. There are a few systems that make up the data infrastructure and there are a few different kinds of ids.  

`file_number` and `beginning_image_number` should be unique for each document. 'image_number' should be unique for each page, (pages are generated for electronic filings too). 

@PaulClark2 do you know why the transaction IDs would vary and why the sub IDs wound't be unique?

**Comment by PaulClark2** [comment]
The example above is a paper filer (it's a Senate party committee report).  We do not capture the transaction IDs that are printed on the page by the committee.  The transaction ID in the data file is an artifact of internal processing.  Transaction IDs should only be considered if the filing is electronic.

**Comment by PaulClark2** [comment]
The sub IDs are unique.  If trying to merge OTH and PAS2 files for some reason, PAS2 is a subset of OTH.  

File Number is unique.  It's a sequence as files are uploaded to EFO.  

For electronic filers, transaction ID is unique for a specific committee for a specific report.  In other words, if committee, C1, files a Q3 New with transaction SA123 and then files 3 amendments to the Q3 transaction SA123 will be identified by transaction ID SA123 in all 4 filings.  I'll update the documentation on the website to make this clearer.

**Comment by fedex1** [comment]
@PaulClark2 Thanks for the reply.  

One question: 
Do you mean by "sub IDs are unique" that `sub_id` uniquely identifies all contributions?

See this case:

https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&sort=-contribution_receipt_date&per_page=2&last_contribution_receipt_date=2018-10-18&last_index=232170504

Look at  `>>>>> sub_id: 4122320131204234000,`

It appears to be a duplicate `sub_id` and there at least hundreds of these cases in the very small subset of data that I looked at

```
link https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&sort=-contribution_receipt_date&per_page=2&last_contribution_receipt_date=2018-10-18&last_index=232170504
     servername: null,
     servername: null,
     servername: null,
        servername: null,
        servername: null,
        hostname: 'api.open.fec.gov',
        pathname: '/v1/schedules/schedule_a/',
  contributor_first_name: null,
  contributor_name: 'HAYDEN, MARK',
  contributor_last_name: null,
  sub_id: 2012220131179028700,
  contribution_receipt_amount: 325,
  back_reference_schedule_name: null,
  contributor_middle_name: null,
   { treasurer_name: 'JAY T DOWNEN',
     name: 'MONTANA ACTION COMMITTEE FOR RURAL ELECTRIFICATION',
  contributor_first_name: 'JAMES',
  contributor_name: 'BEAMS, JAMES R.',
  contributor_last_name: 'BEAMS',
>>>>> sub_id: 4122320131204234000,   <*************DUPLICATE********************************
  contribution_receipt_amount: 4000,
  back_reference_schedule_name: null,
  contributor_middle_name: 'R.',
   { treasurer_name: 'ANDERSEN, BRENT J.',
     name: 'MASSACHUSETTS REPUBLICAN PARTY',
link https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&sort=-contribution_receipt_date&per_page=2&last_contribution_receipt_date=2017-11-26&last_index=232170499
     servername: null,
     servername: null,
     servername: null,
        servername: null,
        servername: null,
        hostname: 'api.open.fec.gov',
        pathname: '/v1/schedules/schedule_a/',
  contributor_first_name: 'JOHN',
  contributor_name: 'CANDON, JOHN D.',
  contributor_last_name: 'CANDON',
 >>>>> sub_id: 4122320131204234000, <***************DUPLICATE*********************************
  contribution_receipt_amount: 50,
  back_reference_schedule_name: null,
```

**Comment by jmcarp** [comment]
@fedex1: Some `sub_id` values exceed integer precision in some languages (notably javascript). It looks like your http client is truncating the last three places of `sub_id` for the records you're looking at. I just submitted a patch at #1290 that will serialize `sub_id` values as strings instead of integers so that they won't be cut off during json parsing. I'll update this issue once the patch is deployed to the production api.

Thanks for your help with debugging!

**Comment by fedex1** [comment]
Hi @PaulClark2 Thanks you are correct.

When using Node and Javascript, `sub_id` values that are greater than 2<sup>53</sup> are quietly changed.  This is true for any integer over 2<sup>53</sup>

That is amazing and thanks for pointing this out and changing `sub_id` from number to string.

For others that are curious, just try this in the browser console window:

```
> 4122320131204234123
4122320131204234000
> Number.MAX_SAFE_INTEGER
9007199254740991
> Number.isInteger(4122320131204234123)
true
> Number.isSafeInteger(4122320131204234123)
false
```

It is really interesting that 4122320131204234123 returns 4122320131204234000.  Wow!

**Comment by LindsayYoung** [comment]
Consulting issues, there are a lot of good thoughts here, that we can keep track of in #1355
