### ISSUE TITLE
Create aggregates for pre-2011 receipts and disbursements

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1250]

**Comment by jmcarp** [comment]
@paulclark2 and @jwchumley: can you recommend cutoff years for aggregated receipts / disbursements / independent expenditures? If we wind up including years with partial coverage, we'll probably also want some text explaining what's going on.

**Comment by noahmanger** [comment]
Related issue for explaining the logic around whatever cutoffs here: https://github.com/18F/openFEC-web-app/issues/809

**Comment by PaulClark2** [comment]
I couldn't attach the spreadsheet so I sent it by email.   For independent expenditures, I labeled the column all filers and that means all Form 3X and Form 5 regular reports (not 24-hour and 48-hour reports of independent expenditures)

**Comment by jmcarp** [comment]
Thanks, Paul! My main question (for everybody involved) is whether we want to build aggregates for election cycles for which we only have partial data. For example, we have all itemized contributions from 2006, electronic and coded paper filings from 2002-2005, and only coded transactions before that. So aggregates from 2005-2006 will have complete coverage for some of the period and partial coverage for the rest. Any earlier aggregates will also be missing various proportions of transactions. There are similar complications for disbursements and independent expenditures.

Seems like we have two main options:
* Create aggregates for all two-year periods for which we have any transactions, even if we're missing data. Under this scenario, aggregates wouldn't be comparable over time, and earlier aggregates would be potentially very different from reported totals; we'd need to include careful explanations of differences in aggregates over time.
* Only create aggregates for two-year periods with complete transaction data. This means we'd show less data, but aggregates would be homogeneous (always built from the same data) and easier to explain.

I would lean toward the second option. I'm guessing data will be missing in a non-random way, such that excluding non-coded transactions could seriously skew the aggregates. I also don't want to encourage naive users to see trends where they don't exist--if we build aggregates for cycles with partial data, it's going to look like receipts and disbursements shot up as soon as we started to get complete data.

Either way, I think we'll want to continue exposing all available transactions through the browse views--to be clear, I'm only talking about aggregates for now.

What do you all think @PaulClark2 @LindsayYoung @noahmanger?

**Comment by LindsayYoung** [comment]
I think starting aggregates with the 2008 cycle seems the reasonable, low-risk thing to do.

It would be nice to show the 2002 - 2006 cycle for just the electronic and coded paper groups, but unless there is a sure way to separate them from the 2006-only records, it might be a bad idea.

**Comment by noahmanger** [comment]
Yeah, I agree that it's best to be as homogenous as possible, so limiting aggregates to only cycles where we have complete data. My hunch is it's easier to explain "we don't have subtotals for these because the data was reported differently" than it is to explain "these aggregates are partially true". Or at the very least, the former has lower risk than the latter as we're not giving people incomplete information and requiring them to read a disclaimer to understand it.

**Comment by PaulClark2** [comment]
I agree with the three of you.  We should focus on creating aggregates for 2007-2008 to 2015-2016
