### ISSUE TITLE
one last_index value not returning results for Hillary for America

### ISSUE THREAD

**Issue by CarlaAstudillo** [18F/openFEC#1263]
Hi,

I've been trying to get all contributors found in the Schedule A filings for Hillary for America, and I keep running into a last_index value that returns empty results. Whenever I request the row set with the last_index of 237568115, it brings up no results, errors out and pretty much breaks my Python loop. I know I'm not hitting my API call limit because when I try to call the data with that last_index by itself, it keeps saying that it's empty. What's going on? Thank you!

**Comment by LindsayYoung** [comment]
We will look into it now, thanks for reporting!

**Comment by LindsayYoung** [comment]
I am guessing that it is just the end of the records. The page counts are estimates and not exact. What is the previous last index before it errors and how many records per_page are you viewing?

**Comment by CarlaAstudillo** [comment]
I was viewing 100 records per_page which gave me 435 pages and 43452 records. The loop stops at 390 which is where it hits that last_index. The previous last_index was 237568100.

**Comment by LindsayYoung** [comment]
I just did an exact count there are 38,815 schedule_a records with `cmte_id='C00575795'`. 

It takes several minutes to do an exact count for the schedule data, so that is the reason we don't have exact counts in the API. The estimates are not great, but it is the best we can do without cutting data or taking ridiculously long to make a call.

**Comment by CarlaAstudillo** [comment]
Ah, okay, got it! Thank you so much for answering and for all of your work on the API. It's been a tremendous help.

**Comment by LindsayYoung** [comment]
Happy to help!
