### ISSUE TITLE
problem retrieving schedule a contributions for senate candidate committees

### ISSUE THREAD

**Issue by walkermo** [18F/openFEC#1267]
Trying to get the first 100 schedule a contributors from committees of Senate candidates (at least the few that I tried) returns no results. Doesn't seem to be an issue for House committees.

Example with Sen. Roy Blunt: https://api.open.fec.gov/v1/committee/C00304758/schedules/schedule_a/by_contributor/?per_page=100&&api_key=API_KEY

**Comment by noahmanger** [comment]
Looks like this is working now.
