### ISSUE TITLE
Bug Reporter display bug on smaller screen size 

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1269]
![displaybug-reporter](https://cloud.githubusercontent.com/assets/474916/10469690/550d593e-71d5-11e5-9779-61316ed09288.gif)
In chrome. Appears to have to do with the ratio of screen height to width:
![displaybug-reporter2](https://cloud.githubusercontent.com/assets/474916/10469769/e3ec5592-71d5-11e5-8ff5-6f602bdc93c1.gif)

**Comment by jenniferthibault** [comment]
Also see https://github.com/18F/openFEC-web-app/issues/829 for feedback tool positioning bug
