### ISSUE TITLE
bug: Incorrect office districts for various candidates

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1271]
While debugging https://github.com/18F/openFEC-web-app/issues/766, I noticed that many candidates seem to have incorrect office districts, with values of 99 instead of their true values. So far, I haven't seen a clear pattern here: both recent and older records are affected, and all the relevant records so far have come from F2 (and not F2Z) records. Also, these records all appear to be correct on FEC Viewer.

@PaulClark2 and @jwchumley: I've included a few sample queries and results below (for Dennis Heck, James Sensenbrenner, and David Giles). Please let me know if I'm using the wrong queries here.

cc @LindsayYoung 

```
fec=> select office_district, * from dimcand join dimcandoffice using (cand_sk) join dimoffice using (office_sk) where cand_id = 'H0WA03161';
 office_district | office_sk | cand_sk  |  cand_id  | form_sk | form_tp |      load_date      | expire_date |         pg_date
-----------------+-----------+----------+-----------+---------+---------+---------------------+-------------+--------------------
 03              |  10000509 | 10008223 | H0WA03161 | 1458283 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:20:42
 99              |  10000516 | 10008223 | H0WA03161 | 1458283 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:20:42
 99              |  10000516 | 10008223 | H0WA03161 | 1458283 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:20:42
 99              |  10000516 | 10008223 | H0WA03161 | 1458283 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:20:42
(4 rows)
```

```
fec=> select office_district, * from dimcand join dimcandoffice using (cand_sk) join dimoffice using (office_sk) where cand_id = 'H8WI09050';
 office_district | office_sk | cand_sk  |  cand_id  | form_sk | form_tp |      load_date      | expire_date |         pg_date
-----------------+-----------+----------+-----------+---------+---------+---------------------+-------------+--------------------
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 99              |  10000526 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 05              |  10000522 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 05              |  10000522 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 05              |  10000522 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 05              |  10000522 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 05              |  10000522 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 05              |  10000522 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
 05              |  10000522 | 10031976 | H8WI09050 | 1538510 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:25:12
(18 rows)
```

```
fec=> select office_district, * from dimcand join dimcandoffice using (cand_sk) join dimoffice using (office_sk) where cand_id = 'H6AZ09010';
 office_district | office_sk | cand_sk  |  cand_id  | form_sk | form_tp |      load_date      | expire_date |         pg_date
-----------------+-----------+----------+-----------+---------+---------+---------------------+-------------+--------------------
 99              |  10000028 | 10035952 | H6AZ09010 | 1499562 | F2      | 2015-06-24 00:00:00 |             | 2015-07-09 06:27:58
(1 row)
```

**Comment by PaulClark2** [comment]
@jmcarp I think your query is fine.  It seems to be a DW problem that doesn't properly deal with states having different numbers of districts.  From 1972 to 1992 Wisconsin had 9 congressional districts but currently it only has 8.  I think what's happening is any district greater than "08" is being considered as invalid and gets a "99" inserted into the district column.  This will not be a quick fix on our side.

OFFICE_DISTRICT | CAND_ID | RECEIPT_DT | CAND_ELECTION_YR
----------------|---------|------------|-----------------
99 | H8WI09050 | 12/5/1977 | 1978
99 | H8WI09050 | 10/2/1979 | 1980
99 | H8WI09050 | 4/12/1982 | 1982
99 | H8WI09050 | 3/11/1983 | 1984
99 | H8WI09050 | 12/6/1988 | 1988
99 | H8WI09050 | 11/10/1986 | 1990
99 | H8WI09050 | 11/6/1992 | 1992
99 | H8WI09050 | 11/10/1994 | 1996
99 | H8WI09050 | 11/12/1996 | 1998
99 | H8WI09050 | 11/9/1998 | 2000
99 | H8WI09050 | 10/22/2003 | 2002
5 | H8WI09050 | 12/2/2002 | 2004
5 | H8WI09050 | 4/28/2009 | 2006
5 | H8WI09050 | 11/4/2008 | 2008
5 | H8WI09050 | 11/25/2009 | 2010
5 | H8WI09050 | 4/12/2011 | 2012
5 | H8WI09050 | 4/25/2013 | 2014
5 | H8WI09050 | 5/5/2015 | 2016

 select o.office_district, d.cand_id, c.receipt_dt, c.cand_election_yr
 from dimcand d 
 join dimcandoffice c on d.cand_sk = c.cand_sk
 join dimoffice o on c.office_sk = o.office_sk 
 where d.cand_id = 'H8WI09050'
 --and O.OFFICE_DISTRICT = '99'
 order by c.cand_election_yr;

**Comment by PaulClark2** [comment]
Using cand_valid_fec_yr might be a solution.  

MS-01 and IL-18 both have two incumbents for the 114th Congress.  This is correct Mr. Nunnelee died and Mr. Schock resigned after the 114th Congress began.   NY-11 only has one incumbent because Mr. Grimm resigned before being seated in the 114th Congress.  

select
c.cand_office_st, c.cand_office_district, c.cand_name, cand_id, c.cand_election_yr
from CAND_VALID_FEC_YR c
where c.fec_election_yr = 2016 
and c.cand_election_yr in (2015, 2016) 
and c.cand_ici = 'I'
and c.cand_office = 'H'
order by c.cand_office_st, c.cand_office_district, c.cand_name;
442 rows today --- 443 rows tomorrow after the Donovan update is processed

select
c.cand_office_st, c.cand_office_district, c.cand_name, cand_id, c.cand_election_yr
from CAND_VALID_FEC_YR c
where c.fec_election_yr = 2016 
and c.cand_ici = 'I'
and c.cand_office = 'S'
order by c.cand_office_st, c.cand_office_district, c.cand_name;
100 rows.

**Comment by jmcarp** [comment]
That sounds promising @PaulClark2. So instead of getting candidate districts by joining `dimcandproperties` on `dimcandoffice` and `dimoffice`, we'd join `dimcandproperties` directly on `cand_valid_fec_yr`.

I spent a few minutes exploring this approach and noticed that a few columns are different between `dimcandproperties` and `cand_valid_fec_yr`. For example, Al Franken has a `cand_status` of "P" in 2008 in `cand_valid_fec_yr`, but we're currently showing his `cand_status` as "C", since we use the most recent record in `dimcandproperties` for candidate status in each cycle. Which value is correct in this case?

Anyway, if this approach makes sense, I'll write up a patch and revert #1277. Do you foresee any obstacles here @PaulClark2 and @LindsayYoung?

**Comment by jmcarp** [comment]
By the way, @PaulClark2 is there a script that's used to update `cand_valid_fec_yr` that we can take a look at? I'm still not completely clear on where this table comes from.

**Comment by PaulClark2** [comment]
It looks like Franken's (S8MN00438) 2008/2008 row in cand_valid_fec_yr should have a candidate status = "C."  Just so that you are aware FEC never uses candidate status for disclosure purposes.  Candidate status is primarily used internally as shorthand for a campaign that has receipts or disbursements of $5,000 or more.   

The disclosure offices do not control this data element -- the compliance offices control this data element.

**Comment by PaulClark2** [comment]
I should be able to send you the script for cand_valid_fec_yr sometime tomorrow.
