### ISSUE TITLE
How soon after deadline are FEC Quarterly filings updated to the API?

### ISSUE THREAD

**Issue by CarlaAstudillo** [18F/openFEC#1274]
Hi,

This isn't really an issue, but a question I have. How soon after the FEC Quarterly Reports filed are they added to the API? Is it right when the PDF/HTML version is available online or is there a bit of a waiting period? I mainly ask because I know that the filing deadline for October Quarterly Reports are today by midnight, so I was wondering when they would be available in the API. Thank you so much.

**Comment by LindsayYoung** [comment]
The API is updated nightly

**Comment by arm5077** [comment]
So... updates tomorrow night, then? Bush's endpoint still showing 6/30 as the most recent date. https://api.open.fec.gov/v1/committee/C00579458/totals/

**Comment by LindsayYoung** [comment]
Yes, that did not make it into last night's batch update.

**Comment by LindsayYoung** [comment]
It's there. (I think it was there yesterday, but I did not get a chance to check.)
https://api.open.fec.gov/v1/committee/C00579458/totals/?api_key=DEMO_KEY
