### ISSUE TITLE
bug: candidate missing from search (Larry Lessig)

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1275]
Larry Lessig is a candidate P60009685, but he doesn't come up when searching for "Lessig." (Only a different Andrew Lessig is returned.)

**Comment by jmcarp** [comment]
This would be fixed by rolling back #1252. I see that there are some data issues still under discussion in that patch, but I'm inclined to revert now and revisit later. Thoughts @LindsayYoung?

**Comment by LindsayYoung** [comment]
No objections
