### ISSUE TITLE
To make sub-totals easier to understand, visually distinguish them on the Detailed Summary

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1280]
In the Detailed Summary on committee pages, "Itemized individual contributions" and "Unitemized individual contributions" are both sub-totals of "Individual contributions", but appear as sibling line items rather than children. 

<img width="982" alt="screen shot 2015-10-16 at 4 58 27 pm" src="https://cloud.githubusercontent.com/assets/1696495/10555648/4508dece-7427-11e5-9970-3c870784b0eb.png">

We're talking about refactoring this code into a Javascript component, so no reason to touch this yet, but it might be worth beginning with some design work.

**Comment by LindsayYoung** [comment]
We also have net totals. We might want to break those out in some way too because they also look like siblings in the current scheme.

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/suJmV4xKbKUmLDnUEFZhfg
