### ISSUE TITLE
contribution receipt date is 15 years in the future for schedule_a endpoint

### ISSUE THREAD

**Issue by fedex1** [18F/openFEC#1286]
Can someone help explain how the `contribution_receipt_date` can be 15 years in the future?

See http://docquery.fec.gov/cgi-bin/fecimg/?14960323139

![screen shot 2015-10-21 at 10 02 06 pm](https://cloud.githubusercontent.com/assets/167614/10655100/9d1900d2-783f-11e5-8be1-cb8b15dc8321.png)

And the API dutifully reports the `contribution_receipt_date` as year 2031

Is there not any checking that at the very least (for electronic submission, which this one appears to be) that you cannot submit for 15 years in the future?

Or is future dated `contribution_receipt_date` actually correct?  

If future dated `contribution_receipt_date` is correct, then can we sort the endpoint https://api.open.fec.gov/v1/schedules/schedule_a by `receipt_date`

When I try this (https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&sort=-receipt_date) I see
`body: '{\n  "message": {\n    "sort": [\n      "Cannot sort on value \\"-receipt_date\\""\n    ]\n  },\n  "status": 422\n}' }`

There are many of these future dated items.

```
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?14960323139',
  contribution_receipt_amount: 2600,
  receipt_date: '2014-01-31',
  contribution_receipt_date: '2031-09-30',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?14020832955',
  contribution_receipt_amount: 2600,
  receipt_date: '2014-10-15',
  contribution_receipt_date: '2025-08-25',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?14021334286',
  contribution_receipt_amount: 2600,
  receipt_date: '2014-12-04',
  contribution_receipt_date: '2025-08-25',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?12020434096',
  contribution_receipt_amount: 500,
  receipt_date: '2012-06-29',
  contribution_receipt_date: '2023-03-18',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?12020343212',
  contribution_receipt_amount: 1000,
  receipt_date: '2012-04-30',
  contribution_receipt_date: '2022-04-19',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?12020881777',
  contribution_receipt_amount: 500,
  receipt_date: '2012-10-15',
  contribution_receipt_date: '2021-08-22',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?14031302082',
  contribution_receipt_amount: 45,
  receipt_date: '2014-10-06',
  contribution_receipt_date: '2019-09-19',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?14031302077',
  contribution_receipt_amount: 125,
  receipt_date: '2014-10-06',
  contribution_receipt_date: '2019-09-19',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?14031302076',
  contribution_receipt_amount: 20,
  receipt_date: '2014-10-06',
  contribution_receipt_date: '2019-09-19',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?14031302076',
  contribution_receipt_amount: 195,
  receipt_date: '2014-10-06',
  contribution_receipt_date: '2019-09-19',
{ pdf_url: 'http://docquery.fec.gov/cgi-bin/fecimg/?12030954667',
  contribution_receipt_amount: 325,
  receipt_date: '2012-11-26',
...
```

**Comment by LindsayYoung** [comment]
We are looking for ways to address issues like these in #1234

Thanks for taking the time to report!

Below is a picture of the filer's car:
![delorean_-_flickr_-_jns001](https://cloud.githubusercontent.com/assets/4406333/10667260/5d1c67d4-78a4-11e5-9b55-89830d185bc0.jpg)

**Comment by noahmanger** [comment]
This issue is captured in #1234 so I'm closing.
