### ISSUE TITLE
Handle committees that file F3s before F1s

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1287]
Some committees begin to file F3* forms before filing their first F1. For example, committee C00507384 filed its first F1 in 2011, but filed year-end F3X forms in 2007 and 2008. We're currently pulling basic committee information from `dimcmteproperties` (name, treasurer, party, etc.), and because there are no records in that table before 2011, the API returns empty results for the 2008 and 2010 cycles.

The current FEC site does show data for these cycles, and I'm guessing it comes from `cmte_valid_fec_yr`, since the relevant information isn't available from F1 filings or `dimcmteproperties` alone. If that's correct, then I propose that we switch from `dimcmteproperties` to cmte_valid_fec_yr` to fetch basic committee details. This would bring us in line with the current site, and resolve https://github.com/18F/openFEC-web-app/issues/875.

Does this sound right @PaulClark2 @LindsayYoung?

**Comment by PaulClark2** [comment]
Sounds right to me.
