### ISSUE TITLE
So that users understand our code, update READMEs on all repos

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1297]
We need to make sure the README's are up-to-date and accurate across all repos:
- FEC
- OpenFEC
- OpenFEC-web-app
- FEC-CMS
- FEC-Style

And didn't we discuss renaming the OpenFEC repos?

**Update (via Emileigh):**

### Steps to completion
- [ ] Address issue of outdated or not-in-use repos

#### CONTRIBUTING
- [ ] Draft standard CONTRIBUTING.md language (@emileighoutlaw)
- [ ] Core team approves updated language
- [ ] Implement language (@emileighoutlaw)

#### README
- [ ] Draft standard README.md language (@emileighoutlaw)
- [ ] Core team approves updated language
- [ ] Implement language (@emileighoutlaw)

Draft language being worked on in this Google Doc: https://docs.google.com/document/d/1QERJaLp1I1ilMqCAzWkl-3_DBmZzuSYdLITQUNz7Wss/edit

**Comment by emileighoutlaw** [comment]
What about these repos that I have never used but exist and are affiliated? 

- fec-alpha
- fec-proxy
- fec-graph-search
- openFEC-documentation
- fec-infrastructure

**Comment by LindsayYoung** [comment]
Graph search was Amos' thing back in the day. What is 18F's policy for dealing with older repos we aren't using? @amoose any ideas on what to do with that repo?

fec-infrastructure was Sean's bootstrap script, I don't think we are using that anywhere, correct me if I am wrong. 

openFEC-documentation was the old version of documentation written by @micahsaul 

fec-alpha is an empty repo with some good readme stuff about writing tickets.

We do use fec-proxy,  is what we use to rout urls to the cms or data site. 

Also, we have a fork of Swagger that we use for the API documentation: https://github.com/18F/swagger-ui
