### ISSUE TITLE
"false" is displaying on screen

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1302]
https://fec-proxy.18f.gov/data/disbursements/?disbursement_description=travel&min_date=01-01-2015&max_date=12-31-2016  

If you look at this list and click on the flyout arrow for the first transaction the memo_cd displays the word "false".  Not to be worried about before the demo unless it is a five minute fix.

**Comment by jmcarp** [comment]
Would it be clearer if the memo code were "X" or blank? That's a one-line change.

cc @LindsayYoung @noahmanger

**Comment by jwchumley** [comment]
Yes.

**Comment by LindsayYoung** [comment]
Moving like issues together, this is part of #1354

**Comment by jmcarp** [comment]
I would say this issue is distinct from #1354, which is about how values are labeled in the API. This issue is about how values are displayed on the data site, and it probably belongs on the other repo. IMO we should reopen or copy this to https://github.com/18f/openfec-web-app.

**Comment by noahmanger** [comment]
Agreed.
