### ISSUE TITLE
To have confidence in our data, verify logic for contributor aggregates

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1303]
All receipts aggregates from individuals use a custom filter described by @jwchumley and @PaulClark2 to remove duplicate contributions (receipt type is one of "15", "15E", "15J", "18J" or amount < 200 and "earmark" not in memo, etc.). We handle the problem of duplicate earmarked contributions differently for aggregates of committee contributions, since this filter only applies to contributions from individuals. I don't think we've discussed this logic specifically, so I'd like to run our query by you and verify that it's correct.

Here's how we tally up contributions aggregated by donor committee. We're filtering out receipts with memo_code "X" (to filter out memoed subtotals), and with entity_type != "IND" (to filter out contributions routed through Club for Growth, ActBlue, etc.). Does this make sense @jwchumley @PaulClark2?

cc @LindsayYoung 

```
create table ofec_sched_a_aggregate_contributor as
select
    cmte_id,
    rpt_yr + rpt_yr % 2 as cycle,
    contbr_id,
    max(contbr_nm) as contbr_nm,
    sum(contb_receipt_amt) as total,
    count(contb_receipt_amt) as count
from sched_a
where rpt_yr >= :START_YEAR_AGGREGATE
and contb_receipt_amt is not null
and contbr_id is not null
and coalesce(entity_tp, '') != 'IND'
and (memo_cd != 'X' or memo_cd is null)
group by cmte_id, cycle, contbr_id
;
```

**Comment by noahmanger** [comment]
Ping @jwchumley and @paulclark2 on this.

Card: https://github.com/18F/openFEC/issues/1303

**Comment by noahmanger** [comment]
Is this resolved? I know we've had separate conversation in other issues around this.

**Comment by jmcarp** [comment]
@LindsayYoung can correct me if I'm wrong, but I don't believe this has been addressed--there have been ongoing discussions about adjusting the "individual" filter, but, as I described a few months back in this issue, we can't use that filter when aggregating contributions from committees.

**Comment by jmcarp** [comment]
I'm hoping @PaulClark2 and/or @jwchumley will have time to weigh in on this. To recap, we aren't using the `is_individual` filter to remove duplicates when we aggregate receipts by contributing committee ID, since by definition this aggregate shouldn't exclude receipts from non-individuals. I dropped in the SQL we're using at the start of this issue--it would be great to confirm that this is correct, or if it's not, figure out how to improve it.

**Comment by jwchumley** [comment]
I've been looking at this all day. There are a few things that aren't adding up for me on our end and I hope to figure them out before I go home but I may not be able to get back to you with anything substantive until tomorrow.

**Comment by jwchumley** [comment]
I came at this from a bunch of different angles yesterday but there is a large underlying issue that I can't get past. Most of the Line 11C/17C receipts are not coded and the contributor IDs in them come straight from the filer. There are two issues with this. First, they are not required to give us the ID so many of them are missing and second, while the quality I observed was very good for those that are reported, there is no review to make sure they use the correct ID. 

To do this from the receipts point of view I think you would have to use a where clause something like this:

Where ( form_tp in ('11C','17C') OR transaction_cd in (there is a fairly short list of transaction codes for transfers. I'll get them for you if you go this route)
and entity_tp!='IND'  --don't exclude nulls

Don't exlude null contbr_id

This means you can't aggregate on contbr_id and would have to use committee name or something which could be really ugly. There are many variations of committee names in the transactions.

We have never really used 11C/17C data for anything other than raw display. Whenever we need to show committees giving to other committees we always look at it from the giving committee's perspective, not the recipient. The  giving committee  reports it as a disbursement and it is coded and the other ID is reviewed and inserted or corrected during the coding process.

**Comment by PaulClark2** [comment]
I agree with Jeff's analysis.  Thanks for looking at the receipts from committees issue.

**Comment by LindsayYoung** [comment]
Make aggragates from schedule B to get this info. - From meeting 02/08
