### ISSUE TITLE
candidate search "Sanders, Bernard" returns an OOPS!

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1304]
![image](https://cloud.githubusercontent.com/assets/12615919/10736787/30152b4c-7be5-11e5-95e7-07e18872feed.png)

The candidate or committee search box on this page: https://fec-proxy.18f.gov/data/ 
If you type sanders b and then click on the Sanders, Bernard (president) row you get an oops

**Comment by jmcarp** [comment]
Looks like there are two separate issues here. Once is that a committee named "Palouse Says Enough" is listed as one of Sanders's principal committees in `dimlinkages`, but doesn't have any reports. The other issue is that committees without any reports can throw an error on the candidate page. I'll fix the latter issue now; @jwchumley and @PaulClark2, can you look into why this committee is showing up as one of Sanders's principal committees?

```
fec=> select cmte_tp, cmte_dsgn, * from dimlinkages where cand_id = 'P60007168' and cmte_id = 'C00589432';
 cmte_tp | cmte_dsgn | linkages_sk | fec_linkage_id | cand_sk  | cmte_sk  |  cand_id  | cand_election_yr | fec_election_yr |  cmt
---------+-----------+-------------+----------------+----------+----------+-----------+------------------+-----------------+-----
 P       | P         |     4948611 |         210123 | 10009887 | 10059737 | P60007168 |             2016 |            2016 | C005
(1 row)
```
