### ISSUE TITLE
Recipient Name in disbursement browse

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1306]
After Demo: 
There are four disbursements here. All of them are to Facebook and all of them show Pattie Curran Committee as the recipient instead of Facebook. 

https://fec-proxy.18f.gov/data/disbursements/?committee_id=C00574590&recipient_state=CA&disbursement_description=social+media&min_date=01-01-2015&max_date=12-31-2016

**Comment by noahmanger** [comment]
Very strange. This doesn't seem to be a problem for disbursements as a whole. And I see the correct info in the details panel.

**Comment by jwchumley** [comment]
I think it is related to the fact that they put their committee name in the candidate name field. If you look at the image of the first transaction you will see it.  Maybe be some code that says to display candidate name if not null. Shouldn't do that.

**Comment by jmcarp** [comment]
It looks like these disbursements have the correct `recipient_nm` of "FACEBOOK INC" but incorrectly set the contributing committee's ID as `recipient_cmte_id` ("C00574590"). Is one of these columns more reliable than the other? If `recipient_nm` is more reliable, we can always show that if it's present. But in that case, we'd have to be careful about the URL for the recipient committee link--we wouldn't want to show "FACEBOOK INC" but link to a separate committee.

@jwchumley: Would it be more accurate to use only recipient information from the transaction tables, and not join on the committee tables?

**Comment by jwchumley** [comment]
Anytime CMTE_ID=recipient_cmte_id  treat recipient_cmte_id as null. A lot of committees file this way. It is incorrect and they should never be the same.

**Comment by jwchumley** [comment]
Likewise in receipts. If contbr_id = cmte_id then contbr_id should be treated as null

**Comment by jmcarp** [comment]
Is this something that should eventually be fixed in the DW / FECP? Either way, I can put in a patch on our side for now. Will take a look at this tomorrow.

**Comment by jwchumley** [comment]
We would fix this at point of display not in the actual data though that would make it easier. The data is as filed. THe best place to fix it would be to disallow it in the efiling system but that would be a much bigger effort.

**Comment by jmcarp** [comment]
Makes sense. At the risk of nit-picking, let's define "point of display" more precisely. We know we want to ignore contributor IDs that match committee IDs on the data site, but what about in the API? Here's an example of an API request for a receipt with the same contributor and committee. Should we show the contributor ID as filed, and allow API users to draw their own conclusions? Or should we null the contributor ID?

I could go either way on this, but I'm leaning toward nulling the contributor ID in the API in these cases. If we don't, I think it would be easy for API users to unwittingly misrepresent the data in their own analyses and applications. We can add a disclaimer warning API users to ignore contributor IDs when they match committee IDs, but people aren't always going to read the fine print.

Wondering what @LindsayYoung thinks about this one.

**Comment by jwchumley** [comment]
Since there really is no case where a committee should report a 
transaction to or from itself I think it's safe to null it.
