### ISSUE TITLE
Why is actblue in this receipt search return set?

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1308]
https://beta.fec.gov/data/receipts/?contributor_type=individual&is_individual=true&contributor_name=roberts&contributor_city=harrisburg&contributor_state=PA&min_date=01-01-2015&max_date=12-31-2015

**Comment by jmcarp** [comment]
It looks like all the contributions from ActBlue in this result set have receipt types coded as "15E". According to the rules we laid out in https://github.com/18F/openFEC/issues/1141#issuecomment-132635114, these receipts should be counted as individual:

> Rule #1: If it has a receipt_tp in (15,15E, 15J, 18J) then include it

Do we need to change this rule?

@jwchumley @PaulClark2

**Comment by jwchumley** [comment]
OK. THanks. I'll look at them.

**Comment by jwchumley** [comment]
But why do they return when I search for "Roberts"?

**Comment by jmcarp** [comment]
Because those particular contributions were given by someone named Craig Roberts. We're not showing his name in the table because we present committee information if it's available--and in this case, the committee contributor is ActBlue.

**Comment by jwchumley** [comment]
We need to revisit this when Josh gets a chance. It's a really big problem for committees reporting earmarked contributions from actblue.  A 15E from actblue should report the individual contributor's name not actblue's name as the  contributor name. IF the issue is the fact that the ACTBLUE committee id is in the "other_id" column then I think we should ignor the other ID for 15E transactions.  It wouldn't be bad to see that it was earmarked through actblue on the "more information" flyout but right now you have to go all the way to the image to see who gave the money. @noahmanger  @jmcarp
