### ISSUE TITLE
Bug: details panels don't always open on first click

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1309]
Any search I do in disbursements or receipts, the first time I click on one of the little flyout arrows at the end of a row it pops open and disappears. After that it works normally.

**Comment by leahbannon** [comment]
We haven't been able to reproduce this -- @jwchumley can you confirm this is still an issue?

**Comment by jwchumley** [comment]
It isn't doing it now. It was very consistent before.  It did happen once 
on Wednesday while we were prepping for the demo but only once. I haven't 
seen it since then.

**Comment by noahmanger** [comment]
I'm going to close this and if we notice it again we can re-open.
