### ISSUE TITLE
Some committee's schedule As and Bs not returned

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1310]
Christie's and Kasich's schedule A and Bs don't appear in the API.

Cristie
https://api.open.fec.gov/v1/schedules/schedule_a/?committee_id=C00580399&api_key=DEMO_KEY

https://api.open.fec.gov/v1/schedules/schedule_b/?committee_id=C00580399&api_key=DEMO_KEY

Kasich
https://api.open.fec.gov/v1/schedules/schedule_a/?committee_id=C00581876&api_key=DEMO_KEY

https://api.open.fec.gov/v1/schedules/schedule_a/?committee_id=C00581876&api_key=DEMO_KEY

When I query the data it takes a really long time.

**Comment by jmcarp** [comment]
Looking into this. Can you be more specific about slow queries you're running into?

**Comment by LindsayYoung** [comment]
This one takes a few minutes on staging-
```
select * from sched_b where cmte_id='C00580399';
```

**Comment by jmcarp** [comment]
Thanks for catching this--the transaction tables failed to update because of duplicate primary keys. I fixed this manually, but we need to learn more about where the duplicate keys came from in the first place. @PaulClark2, is it expected that we'd see duplicate values for `sched_a_sk`, `sched_b_sk`, etc.? Is there a better column to use here?

**Comment by PaulClark2** [comment]
@jmcarp No there shouldn't be duplicates.  I don't find any duplicates in the DW.  I'll ask Rohan to check the tranfer.  

`select sched_b_sk, count(*) from sched_b where cmte_id='C00580399' group by sched_b_sk having count (*) > 1;` 
`select sched_a_sk, count(*) from sched_a where cmte_id='C00580399' group by sched_a_sk having count (*) > 1;`

`select sched_a_sk, count(*) from sched_a where cmte_id='C00581876' group by sched_a_sk having count (*) > 1;`
`select sched_b_sk, count(*) from sched_b where cmte_id='C00581876' group by sched_b_sk having count (*) > 1;`

**Comment by jmcarp** [comment]
It's possible that some rows were in our staging table for long enough that the primary keys were rotated in the DW in the meantime. How often does that happen? Also, if primary keys are stable in FITEM, then the answer to that question won't matter for long.
