### ISSUE TITLE
"total received" on disbursement screen

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1312]
https://beta.fec.gov/data/committee/C00461046/?cycle=2016&tab=disbursements

Could we perhaps change the column header from "total received" to "Total Amount". I know you could interpret it as received by the other party but the word "received" sounds wrong here.

**Comment by noahmanger** [comment]
This makes sense to me, but we should be consistent throughout. @emileighoutlaw what do you think?

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/KFFXUL5VTsxtYDnUEHzR2Q

**Comment by LindsayYoung** [comment]
Agreed, Total Amount seems more straight forward.
