### ISSUE TITLE
To have confidence in our data, clarify amendment-related variables

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1319]
Background: Amendments are handled differently in different tables. In itemized tables (`sched_a`, `sched_b`, etc.), we have an amendment indicator that describes whether each row is a new record or an amendment. However, once a row is amended, it is replaced with the new data, so that amendments and original data don't coexist. In the fact\* tables, we don't get an amendment indicator, but we do get both original reports and amendments; amendments are distinguished by non-`null` expiration dates.

It would be helpful to go over all the relevant tables and make sure we understand how each one handles amendments, and to audit our scripts to make sure we're treating amendments correctly in all cases. I bring this up because I noticed that we're filtering on `amndt_ind` in our materialized view of aggregated communication costs, and I'm not sure that's what we want to be doing.

Tasks:
- [ ] Verify amendment check in `ofec_communication_cost_aggregate_candidate_mv` and fix if necessary
- [ ] Write up a description of how amendment work in different tables. This may be excessive, but I think this would help minimize questions that we have to ask the FEC team.

cc @LindsayYoung @PaulClark2 @jwchumley

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/usK5ygEJPMbdUDnUEFZhfg

**Comment by noahmanger** [comment]
Waiting on column from Paul with the correct amendment information.

**Comment by noahmanger** [comment]
Moving to icebox in favor of tracking it here https://github.com/18F/openFEC/issues/1434
