### ISSUE TITLE
FEC Form 3, Post-election detailed summary page

### ISSUE THREAD

**Issue by KatzIsPolitical** [18F/openFEC#1324]
The FEC Form 3, post-election detailed summary page includes additional summary numbers specifically because this report crosses over two election cycles.   This information is not currently available in  /committee/{committee_id}/reports/ 

For example, see page 3, column C of:
http://docquery.fec.gov/pdf/748/13964525748/13964525748.pdf

**Comment by LindsayYoung** [comment]
The tables we are using don't have that information. We will see if we can get that into the system in the future. I will add a note in #1355 so we don't forget to look for them.
