### ISSUE TITLE
To improve data quality, migrate away from data warehouse tables

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1327]
In general, tables from the data warehouse (among others, tables named dim*) are less reliable than tables and views used to power FEC Viewer. As more of the latter tables are pushed to postgres, we should use more data from them and less from the data warehouse. Since some fields in the DW tables aren't available in the newly pushed views, we may want to change these views (e.g., `cand_valid_fec_yr`, `cmte_valid_fec_yr`) so that we don't need to rely on the DW.

Here's a partial list of DW tables that we'll eventually want to stop using:
* [x] dimcandproperties
* [ ] dimcmteproperties
* [ ] dimparty
* [x] dimcmtetpdsgn
* [x] dimlinkages
* [x] dimcandstatusici
* [ ] factpacsandparties_f3x
* [ ] factpresidential_f3p
* [ ] facthousesenate_f3
* [ ] factindpexpcontb_f5
* [ ] sched_a
* [ ] sched_b
* [ ] sched_e

@PaulClark2 and @LindsayYoung: Feel free to comment, change the list of tables, or otherwise improve this issue. We're also going to need to push over more tables before we can start on some of these--for example, at some point we'll want to get access to `F_REPORT`, and the FECP equivalent of `dimlinkages`.

Also, #1325 drops `dimparty` and `dimcmtetpdsgn`, and gets us pretty far toward dropping `dimcmteproperties`.

**Comment by jmcarp** [comment]
Since we're currently getting the `candidate_inactive` flag from `dimcandstatusici`, which we're planning to stop using, it would also be useful to get the `cand_inactive` table pushed over, as described in https://github.com/18F/openFEC/issues/1193#issuecomment-140137067. It would also be useful to get the FECP equivalent of `dimparty`.

**Comment by LindsayYoung** [comment]
One reason for the delay in totals getting to the API is that the data warehouse tables are taking longer to  show the updated data. This might make us want to prioritize moving away from the data warehouse tables.

For example:
Today is the 22, the filing deadline was the 20th, I can see the new records in `f_rpt_or_form_sub` but not in `factpresidential_f3p` I did a quick check using the Clinton and Rubio campaigns- C00575795, C00458844

FYI:
@PaulClark2 @jwchumley @noahmanger @wluoFEC

**Comment by noahmanger** [comment]
You mentioned the new tables have less info. What info specifically are they lacking?

**Comment by LindsayYoung** [comment]
I was going off of Josh's comment, but that looks like it might have been made before access to f_report. I could take another look, unless you remember @jmcarp

**Comment by PaulClark2** [comment]
V_SUM won't have image numbers or amendment indicators because it's designed to be an as-amended table but it's a simple joint to F_RPT to get that information

**Comment by PaulClark2** [comment]
I have a strong preference to move away from the DW tables as soon as we can

**Comment by jwchumley** [comment]
I second that motion!

**Comment by jmcarp** [comment]
One issue we started talking about last year was whether we should expose filings as-amended, or whether we should include original and amended filings. Last time I checked, `f_rpt` included some but not all of the information available in `v_sum`, meaning that if we wanted to show amended filings (which we do now), we'd lose some information about them. I wrote this up in https://github.com/18f/openfec/issues/1337#issuecomment-154081912. Based on the response at the time from @jwchumley, it sounds like we can (1) ask for a new table that includes all filings (amended and original) with all fields, which doesn't currently exist, (2) only show as-amended filings, or (3) show all filings, with missing fields on some. Sounds like it's time to pick an option and move forward. We can discuss here or in #1337, which is about this specific issue.

We're also still using `dimcmteproperties`, since I didn't see another place to get treasurer name and address, custodian name and address, fax number, leadership pac, lobbyist registrant pac flag, and party committee type. Are those fields available in FECP? Or can we drop them?

And we're using `dimparty` and `dimreporttype`. Are there equivalents in FECP?

**Comment by jwchumley** [comment]
You could join v_sum and f_report on v_sum.orig_sub_id=f_report.sub_id to 
get all the columns.

**Comment by jmcarp** [comment]
Sorry if I'm missing something, but how would joining `v_sum` and `f_rpt` give us all the columns? `v_sum` has more columns, but `f_rpt` has more rows. For amended filings that exist in `f_rpt` but not in `v_sum`, where should we find the columns that aren't available in `f_rpt`?

**Comment by jwchumley** [comment]
Sorry, I read your previous post wrong.

**Comment by jwchumley** [comment]
We could possibly augment the f_report table to include all the columns 
you are using from the v_sum table.  Do you have a list of the columns you 
would need?

**Comment by LindsayYoung** [comment]
Splitting this into smaller issues:
fact tables #1537
schedules #1538
small tables #1539


The fact tables will be the first priority, then schedules the small tables can be folded in.
