### ISSUE TITLE
Bug: "Palouse Says Enough" listed as a principal committee for Bernie Sanders

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1328]
Cross-posted from https://github.com/18F/openFEC/issues/1304#issuecomment-151236236:

A committee named "Palouse Says Enough" is listed as one of Bernie Sanders's principal committees in `dimlinkages`. @jwchumley and @PaulClark2, can you look into why this committee is showing up as one of Sanders's principal committees? I'm wondering if this is another issue that will be resolved for free when as we move away from the DW--it looks like the data are incorrect in `dimlinkages`, but hopefully they're correct in whatever the FECP equivalent of that table is. If that's the case, there's no need to investigate the issue in `dimlinkages`--we can just push over the FECP table and go from there.

```
fec=> select cmte_tp, cmte_dsgn, * from dimlinkages where cand_id = 'P60007168' and cmte_id = 'C00589432';
 cmte_tp | cmte_dsgn | linkages_sk | fec_linkage_id | cand_sk  | cmte_sk  |  cand_id  | cand_election_yr | fec_election_yr |  cmt
---------+-----------+-------------+----------------+----------+----------+-----------+------------------+-----------------+-----
 P       | P         |     4948611 |         210123 | 10009887 | 10059737 | P60007168 |             2016 |            2016 | C005
(1 row)
```

cc @LindsayYoung

**Comment by jwchumley** [comment]
Looking...

**Comment by jwchumley** [comment]
Found the disconnect. Jean set it up to process tonight and is working on 
a general fix. The issue is the unlink process which is used only to 
unlink a candidate and committee that should not have been linked.  It 
doesn't happen often. Looking for others.

**Comment by jmcarp** [comment]
It also looks like this problem doesn't come up in the corresponding table in FECP, `cand_cmte_linkage`--at least not for this specific candidate-committee link. I'll have a patch to switch from `dimlinkages` up soon, so hopefully we shouldn't have to spend time cleaning up the DW table.
