### ISSUE TITLE
Make pg_dumps public

### ISSUE THREAD

**Issue by Solomon** [18F/openFEC#1329]
I know you're moving over most of the FEC data into a postgres database. Would you be open to posting a monthly pg_dump of the database?

**Comment by LindsayYoung** [comment]
More discussion on this topic: 18F/FEC/issues/16

**Comment by soychicka** [comment]
I see the recent activity here - is there any movement towards or away from providing this data via a psql dump?  I went through the process of setting up a local api host and web server,  with the assumption that api/app setup was the labour intensive part of this project this project *facepalm* 

Else, is there documentation anywhere on the recommended way to slurp data for specific election cycles, etc?  Anything for consuming API data directly to the cfdm_test database?  just importing CSV files?  If this functionality is provided in some way through the cms (?), that isn't clearly indicated. 

[FWIW, I need to index over all of the schedule b payees and filings for cross-cycle queries.  I can handle elasticsearch and node, but I'm not as familiar with python project architecture, so please be gentle :) ]

**Comment by LindsayYoung** [comment]
Thanks for writing in, we are in the process of expanding the time range  of results for the itemized searches and have planned development to increase the download size. SQL dumps are not planned at this time but we are always iterating and making new plans to improve the system.

The cfdm_test data base is a random sample of data that we use for integration testing, so unfortunately, that won't help for this. 

Bulk data for candidate disbursements is available here:
http://classic.fec.gov/data/DataCatalog.do

In the API, the best way to get the schedule B data is to load it from here:
https://api.open.fec.gov/developers/#!/disbursements/get_schedules_schedule_b
