### ISSUE TITLE
Revisit rules for individual contributions

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1330]
Context: A few months back, we constructed a set of rules to identify individual contributions that aren't earmarked. Receipts must have a receipt type of 15, 15E, 15J, or 18J, or be less $200, appear on line number 11AI, 12, 17, 17A, or 18, and not have a word like "EARMARK" in their memo text to count as individual and non-earmarked; see https://github.com/18F/openFEC/issues/1141#issuecomment-132635114 for the original discussion and https://github.com/18F/openFEC/blob/develop/data/functions/individual.sql for our implementation.

These rules seem to work most of the time, but we're running into some exceptions:

* As pointed out by @jwchumley in #1308, some receipts that appear to be earmarks are classified as non-duplicates by our rules because they've been flagged with the internal 15E receipt type code. It's possible that the receipts in question were coded incorrectly, or that our rules should change to accommodate them.
* As reported by a user in https://github.com/18F/FEC/issues/126, the Right to Rise PAC has suspiciously few contributions--and all its contributions are < $200. Based on the F3 PDFs, it looks like Right to Rise has actually received a substantial amount in large-dollar contributions, but most of them have been coded with a `receipt_tp` of `10`, meaning that our rules exclude them. Again, I'm not sure if we should approach this by fixing the codes or changing our rules.

Since this category of issue affects at least one PAC that's likely to be in the news this cycle, I'm hoping we can make quick progress here. If we decide that we need to change our rules, I can implement this quickly.

cc @PaulClark2 @LindsayYoung @wluoFEC

**Comment by jwchumley** [comment]
Hmm. Superpacs file mostly 10s  but other entities have them too. I'm 
thinking we should treat 10s like 15s. They are reported on the same line 
(11ai for F3X)  I forwarded the email to Paul to see if he has any input 
but he is on vacation.

**Comment by jmcarp** [comment]
Update: we're including receipt type 10 in the rule as of #1332 (this will take a while to process). We still have the issue of some earmarked receipts being included in our rules, as described in #1308. In that specific case (earmarked contributions through ActBlue being included incorrectly), it looks like we could get rid of receipts like these by checking the `entity_tp` column (exclude all rows where `entity_tp != 'IND'`), or by checking `memo_cd` (exclude all rows where `memo_cd = 'X'`).

Come to think of it, is there a reason not to exclude all memoed receipts here? That would simplify our rules a bit, and it seems like memoed receipts should never be included in totals by definition anyway.

Thoughts @jwchumley @PaulClark2 @LindsayYoung?

**Comment by jwchumley** [comment]
Let me look. Entity type is notoriously inaccurate so I wouldn't want to 
hang anything on it. 

Do you mean exclude rows where memo_cd='X'  for ACTBLUE specifically?

**Comment by jmcarp** [comment]
Ideally our rules wouldn't have special cases for particular groups, so I wouldn't want to exclude memoed contributions specifically for ACTBLUE. I'm hoping we can land on a generic rule that will exclude the unwanted contributions through ACTBLUE--unless those contributions were coded incorrectly, in which case our rules may be fine.

Is it possible that memoed subtotals contributed by ACTBLUE were incorrectly coded with receipt type 15E? For the data that we're looking at, there are about 250,000 receipts coded at 15E that aren't memoed, and only 1943 coded as 15E that are memoed.

**Comment by jwchumley** [comment]
Generally speaking you don't want to exclude memos. Can you give me sql that show the set you are talking about?

**Comment by jmcarp** [comment]
Now that I'm remembering the original issue better, #1308 isn't related to our individual contribution rules--the problem is that the offending contributions list the name of the real contributor ("ROBERTSON, CRAIG") as `contbr_nm` and the ID of the bundling committee (C00401224, or ACTBLUE) as `contbr_id`. Our logic tries to use `contbr_id` first, and if that's `null`, we use `contbr_nm` instead.

* Is it expected that the committee ID of the bundling committee would be listed for `contbr_id` in cases like this?
* If so, is there a rule we can use to use `contbr_nm` instead of `contbr_id` in these cases?

The specific example I'm looking at has `sched_a_sk` 235497401, in case you want to take a look.
