### ISSUE TITLE
Load financial reports from FECP

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1337]
## Context

We're currently pulling data about F3* reports from the fact* tables, which AFAIK come from the data warehouse. We now have access to `v_sum_and_det_sum_report`, which includes all as-amended financial filings. But switching to the new table would entail one major change from the current behavior. We currently show both the most recent versions of reports and amended versions. If we switch to the new table, we would lose access to amended reports.

## Questions

* Is it important to include amended versions of reports in the API and display them on the data site? In my opinion, we should do this if at all possible, since our goal is to make as much data as possible available.
* Would it be possible to add amended reports to `v_sum_and_det_sum_report`, or to create a new view that includes both amended and final reports? How heavy a lift would this be for the FEC staff, and how long would it take? I'd be happy to help write scripts if it would be useful.

My preference would be to hold off on switching from the fact* tables to `v_sum_and_det_sum_report` until we're able to include amended reports, since we haven't run into many problems with these data so far. But even if we defer this migration, I don't want to lose track of it, since it has to happen sooner or later.

What do you all think @jwchumley @PaulClark2 @LindsayYoung @noahmanger?

Part of #1327.

**Comment by jwchumley** [comment]
When presenting campaign finance data over a period of time it is 
important to use v_sum. Other places like the list of filings f_report (do 
you have f_report?)  has everything. I think it is fine to make each new 
and amended report available but it has to be done in a way that makes it 
clear that grabbing them all and summing them would not be meaningful. I 
wouldn't want to change v_sum. It serves a very specific purpose.

**Comment by jmcarp** [comment]
To be clear, if we do switch to `v_sum_and_det_sum_report` as-is, we'd lose some data that we're currently showing on the beta site and API. I doubt we have enough power users for this to be a major concern, but I'm always wary of taking away features that we're already offering.

* Right now, users can see filings that have been amended at https://beta.fec.gov/data/filings/, and they can get details about those fillings by clicking on the arrow at the end of the row. Some of that detail information is available in `f_rpt_or_form_sub`, and some isn't. If we switch from the fact* tables to v_sum, we'd lose some detail information about amended filings.
* We also include complete data on amended reports in the API at e.g. https://api.open.fec.gov/v1/reports/presidential/?api_key=DEMO_KEY. If we switch to v_sum, we'd lose amended filings in the API. If anyone's using that data now, they'd lose access after the switch.

**Comment by jwchumley** [comment]
SO here is what we have and how we use it:

F_report has all reports. If a report has been amended three times it 
contains the original and all three amendments.
V_sum has only the most recent version of a report. If a report is amended 
three times only the most recent is there.
f_item has only the transactions that are related to the reports that are 
in v_sum

On the current website we show all reports using f_report (for the filings 
tab) but every place that has reports with summary figures and click 
throughs to transactions only use v_sum and f_item


If we need include all columns of all reports and all transactions we'll 
need to come up with something else. We would essentially have to either 
make another version of f_report with a lot more columns or send you the 
base tables such as nml_form_3, nml_form_3x, nml_form_3p, nml_form_5 etc. 
Also we would have to either create an f_item that contains all 
transactions (not just the as amended ones) or give you the base 
transaction tables like NMLSched_A, nml_sched_b etc.

 That would be somewhere in the neighborhood of 40% more transactions than 
f_item. We'd have to get together with Rohan on that.

**Comment by noahmanger** [comment]
Closed in favor of #1327

**Comment by jmcarp** [comment]
Reopening, since this issue tracks details that aren't included in #1327.

**Comment by LindsayYoung** [comment]
Closing to track this issue on #1537
