### ISSUE TITLE
Understanding Data Availability

### ISSUE THREAD

**Issue by gmj2053** [18F/openFEC#1338]
Some background and then two questions (I tried to review the google groups
https://groups.google.com/forum/#!forum/fec-data
and requested access a couple of days ago but haven't gotten anything back and we need to figure this out this soonest). 

We are developing an application at the Library of Congress to use the API to get candidates filing data for US Congressional and Presidential races.  We use that data to further process for records for candidates on the official ballot to then archive their candidate websites and make them available. 
http://www.loc.gov/collections/united-states-elections-web-archive/about-this-collection/
In the past we have asked for spreadsheets, but we are really excited about the api and facilitating our workflows and simplifying our tasks, especially mine. 

Our application will query your API weekly for new registrations ONLY (first_file_date) and if NO FEC_ID, then not ingest.

1.  We would not ingest
https://beta.fec.gov/data/candidate/NULL/?cycle=2016
because he has NO FEC_ID listed, although if you look at his filing, there is a FEC_ID and a race identified.   Just curious in this scenario, is this just a one-off?
FEC_ID=P60014255, RACE=Presidential

2.  If that isn't a one-off, we have have been using the first_file_date, is there a better option for us so that we don't dump duffy?  If so, I guess amendment status? plus last_file_date?

Sorry for update, typed last instead of first.

**Comment by leahbannon** [comment]
Hey for the google group, we don't have any pending requests, but as an admin I can add you. (Maybe something to do with some .gov email admins block their users from joining.)

**Comment by jmcarp** [comment]
The candidate with an ID of "NULL" looks to be a data error; we're tracking this in #1339. Duffy is the only candidate with that ID. I'll update this issue when we know more, but for now, I'd say it makes sense to exclude him from your data.

**Comment by gmj2053** [comment]
Thanks!

**Comment by gmj2053** [comment]
@leahbannon thanks, gjon@loc.gov or you can do my gmail, ginajones@gmail.com

**Comment by LindsayYoung** [comment]
Closing this issue in favor of #1339
