### ISSUE TITLE
Candidate with FEC ID "P60014255" has `cand_id` of "NULL"

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1339]
As reported in #1338, candidate DUFFY, HUNTER *should* have a candidate ID of P60014255 but instead has an ID of "NULL"--not `null` in the SQL sense, but the string "NULL". His F2 lists what looks like his real FEC ID: http://docquery.fec.gov/pdf/963/201508299001585963/201508299001585963.pdf. The offending ID is present in both the DW and FECP:

```
fec=> select * from dimcandproperties where cand_id = 'NULL';
 candproperties_sk | cand_sk  | form_sk | form_tp | cand_id | election_yr |    cand_nm    | cand_suffix | cand_prefix | cand_m_nm
-------------------+----------+---------+---------+---------+-------------+---------------+-------------+-------------+-----------
          10100474 | 10036958 | 4943670 | F2Z     | NULL    |        2016 | DUFFY, HUNTER |             |             |
          10100021 | 10036958 | 4938447 | F2      | NULL    |        2016 | DUFFY, HUNTER |             |             |
(2 rows)

fec=> select * from cand_valid_fec_yr where cand_id = 'NULL';
 cand_valid_yr_id | cand_id | fec_election_yr | cand_election_yr | cand_status | cand_ici | cand_office | cand_office_st | cand_of
------------------+---------+-----------------+------------------+-------------+----------+-------------+----------------+--------
           333912 | NULL    |            2016 |             2016 | N           | O        | N           | LL             | 00
(1 row)
```

Is this fixable @jwchumley @PaulClark2?

**Comment by jwchumley** [comment]
That form 2 row is deleted in fecp and I don't see anyplace where the 
cand_id P60014255  exists either.  I'll follow up with Jean about why it 
still exists in the warehouse.

**Comment by jmcarp** [comment]
We won't be using the DW to get candidate IDs for much longer, so there's no rush to fix entries in `dimcandproperties` on our behalf. I'm more concerned about this getting fixed in `cand_valid_fec_yr`.

**Comment by PaulClark2** [comment]
deleted old Form 2 and Form 2Z  .... re-entered Form 2 for Mr. Duffy.

**Comment by jmcarp** [comment]
I'm still seeing a candidate with an ID of "NULL" in `cand_valid_fec_yr`, `dimcandproperties`, and `dimcand` (I only care about the first table, just listing all three for completeness). Is that expected?

```
fec=> select * from cand_valid_fec_yr where cand_id = 'NULL';
 cand_valid_yr_id | cand_id | fec_election_yr | cand_election_yr | cand_status | cand_ici | cand_office | cand_office_st | cand_
------------------+---------+-----------------+------------------+-------------+----------+-------------+----------------+------
           333912 | NULL    |            2016 |             2016 | N           | O        | N           | LL             | 00
(1 row)

fec=> select * from dimcand where cand_id = 'NULL';
 cand_sk  | cand_id | form_sk | form_tp |      load_date      | expire_date |         pg_date
----------+---------+---------+---------+---------------------+-------------+-------------------------
 10036958 | NULL    | 4938447 | F2      | 2015-09-01 00:00:00 |             | 2015-09-01 03:30:15.346
(1 row)

fec=> select * from dimcandproperties where cand_id = 'NULL';
 candproperties_sk | cand_sk  | form_sk | form_tp | cand_id | election_yr |    cand_nm    | cand_suffix | cand_prefix | cand_m_n
-------------------+----------+---------+---------+---------+-------------+---------------+-------------+-------------+---------
          10100021 | 10036958 | 4938447 | F2      | NULL    |        2016 | DUFFY, HUNTER |             |             |
          10100474 | 10036958 | 4943670 | F2Z     | NULL    |        2016 | DUFFY, HUNTER |             |             |
          10102505 | 10036958 | 4943670 | F2Z     | NULL    |        2016 | DUFFY, HUNTER |             |             |
(3 rows)
```

**Comment by PaulClark2** [comment]
I deleted and re-entered the F2 for Mr. Duffy.  I'm not sure why the deleted row in cand_valid didn't drop.  I'm going to hard delete 333912 from cand_valid on FECP.  

select * from cand_valid_fec_yr where cand_valid_yr_id in (336388, 333912);
select * from cand_valid_fec_yr where cand_id in ('NULL', 'P60014255');

**Comment by jmcarp** [comment]
Thanks for the fix @PaulClark2! I don't see the offending records in `cand_valid_fec_yr` anymore--they're still in `dimcandproperties`, but since we aren't using that table anymore, the bad data isn't making it into our views. Closing.
