### ISSUE TITLE
Create research plan for identifying needs around legal systems

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC#1342]
To being understanding the needs for the legal system, create a research plan
Address: 
- [ ] team availability
- [ ] research participants

Story map card: [Begin research on the needs around legal systems](https://18f.storiesonboard.com/m/fec/!card/6yZi5SbkmR1wqTnT5jyk-w)

**Comment by noahmanger** [comment]
What more needs to be done on the plan?

**Comment by jenniferthibault** [comment]
Can we connect documentation to this issue? (i.e., link to a google doc or just copy the text here?)

**Comment by onezerojeremy** [comment]
Here's a link to the doc
https://docs.google.com/document/d/1wXDwp0EIlHJiF18l3cdo8DYPbZbBzmXFU73q2KzwgWU/edit#

Also, because of GSA linking issues, I guess I should include it in some other form. What's the best way?
