### ISSUE TITLE
In order to understand past/current behaviors, analyze existing FEC analytics on the legal system portion of fec.gov

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC#1343]
To begin understanding the needs for the legal system, based on existing structure and content, analyze existing FEC analytics on the legal system portion of fec.gov: 
- [ ] FEC to send analytics to 18F / @jwchumley (or other?) > @onezerojeremy 
- [ ] analyze analytics @onezerojeremy 

Story map card: [Begin research on the needs around legal systems](https://18f.storiesonboard.com/m/fec/!card/6yZi5SbkmR1wqTnT5jyk-w)

**Comment by noahmanger** [comment]
Ping on this. ANy updates?

**Comment by onezerojeremy** [comment]
Here's a link to the current doc. I'm still wading through server search logs, so I need to add that part. 

https://docs.google.com/document/d/1CBxO99tKjg2w2D4dMIxx_1KYEnbptK3VGqi8rJsDbt8/edit#

Would love comments/thoughts from the team for further expansion both in terms of things we might want to try to find in analytics, as well as research implications. 

(also i know there are linking issues with google docs now outside the org, so what's the best way to include it here?)
