### ISSUE TITLE
Understand schema of existing legal database

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC#1344]
To begin understanding the data and plan for a new system, learn about the existing database
- [ ] FEC to send database schema to 18F / @jwchumley (or @paulclark2 ) > @LindsayYoung & @noahmanger  

Story map card: [Begin research on the needs around legal systems](https://18f.storiesonboard.com/m/fec/!card/6yZi5SbkmR1wqTnT5jyk-w)

**Comment by jwchumley** [comment]
I'm working on this.

**Comment by jwchumley** [comment]
AOWEB is the searchable advisory opinions

EQS is the MURS after 1998. Salient is in the process of adding the 
archive murs to this schema so they may be making changes to accommodate 
the different data in the older murs.

EQS also contains Admin FIne and Alternative Dispute Resolution (ADR) 
cases.

SERs is the searchable rule makings

**Comment by jwchumley** [comment]
It looks like I can't upload a document here. I don't have permissions. I'll email it.

**Comment by jwchumley** [comment]
I emailed it to Lindsay, Josh and Leah yesterday. Did you get it?

**Comment by jmcarp** [comment]
Yep, thanks Jeff!
