### ISSUE TITLE
Download queries as CSV

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1356]
Start to build that interaction and see how many results can be returned right away, and what how many requests a query can ask for at a time.

Next steps:
create a queuing system
decide on limit for custom downloads

In parallel:
design and test the user interaction around the downloads

**Comment by LindsayYoung** [comment]
https://18f.storiesonboard.com/m/fec/!card/5wzt02F1sSSdiTnUBqI-VQ

**Comment by noahmanger** [comment]
This is done!
