### ISSUE TITLE
Double-check that we have all election activity periods data in API

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1357]
**[Story](https://18f.storiesonboard.com/m/fec/!card/JqiSFWrlBptCOjnT3Laojg):** So that filers various election activity periods, show them on a calendar, filterable by deadline-type and state.

We need to double-check that we have the following dates in the API:
- [ ] Pre- and post-election deadlines
- [ ] EC periods
- [ ] IE periods

**Comment by noahmanger** [comment]
@LindsayYoung have you been able to do this yet?

**Comment by LindsayYoung** [comment]
We have report due dates and elections. We know there are more tables so we can add additional information as the FEC gives it to us. We don't have the periods, they are straight forward, but I would like to confirm they are not already in a table before generating them. 

For reference:
 - Electioneering periods are 60 days prior to a general election or 30 days prior to a primary, nominating convention or caucus
 - FEC regulations require political committees and other persons who make independent expenditures at any time during the calendar year--January 1, 2009, up to and including the 20th day before an election (including a special election)--to disclose this activity within 48 hours each time that the expenditures aggregate $10,000 or more. See 11 CFR 104.4(b)(2) and 109.10(c). This reporting requirement is in addition to the requirement to file 24-hour notice of independent expenditures each time that disbursements for independent expenditures aggregate at or above $1,000 during the last 20 days--up to 24 hours--before an election (including a special election). See 11 CFR 104.4(c) and 109.10(d). http://www.fec.gov/info/charts_ie_dates_special.shtml

**Comment by LindsayYoung** [comment]
We might also need state information for the pre-general-post general reports.

**Comment by LindsayYoung** [comment]
I am seeing the new CAL_ tables now

**Comment by noahmanger** [comment]
Can we close this?
