### ISSUE TITLE
Which Schedule E itemizations are included in the aggregated candidate endpoint?

### ISSUE THREAD

**Issue by corbyhobbs** [18F/openFEC#1364]
This is either a question or a bug, but I can't figure out at all which itemizations are rolled up into the '/committee/{committee_id}/schedules/schedule_e/by_candidate/' endpoint. As an example, I looked at RNC spending against Hillary Clinton in 2016 on the aggregate endpoint and came up with a count of 22 and a total of $297,522.78 (https://api.open.fec.gov/v1/committee/C00003418/schedules/schedule_e/by_candidate/?page=1&sort_nulls_large=true&per_page=20&api_key=DEMO_KEY&candidate_id=P00003392
). However, when I plugged in the same parameters to the itemized schedule E endpoint, I got back 80 results totaling $1,094,190.56 (https://api.open.fec.gov/v1/schedules/schedule_e/?sort_nulls_large=true&per_page=100&api_key=DEMO_KEY&candidate_id=P00003392&cycle=2016&committee_id=C00003418). I then did the same thing on the data catalog dashboard for Hillary and the RNC (http://www.fec.gov/data/IndependentExpenditure.do?format=html&election_yr=2016) and got back 57 results for a total of $805,939.27.

I understand there are amendments that are altering the amount of expenditures, but even when I attempt to account for them I still can't manage to match any of the files together cleanly. For instance, when I take amendments out of the file I downloaded from the dashboard (which looks to me to be cleaner than the API), I get 25 expenditures totaling $321,531. Should these files all match up, and if so is there a straightforward way to account for amendments so that they do?

Itemized data from dashboard: [rnc-hillary-ie.txt](https://github.com/18F/openFEC/files/38553/rnc-hillary-ie.txt)
Itemized data from API: [rnc-hillary-api.txt](https://github.com/18F/openFEC/files/38554/rnc-hillary-api.txt)

**Comment by LindsayYoung** [comment]
24 and 48 hour reports are excluded from the aggregate endpoint because the information that is on the 24/48 hr reports is also on the form 5. The 24 and 48 hour reports are more likely to have dupes so we go with the quarterly reporting for more precise totals. You can still see the 24 and 48 hr reports in the schedule_e endpoint and they are useful because they are much closer to real time. 

[Here](https://github.com/18F/openFEC/blob/develop/data/sql_updates/create_sched_e_aggregate_candidate.sql) is the sql for the schedule e aggregate for that if you are interested

I am going to close this ticket, reopen if if you have additional questions or you think there is a bug.

Thanks!

**Comment by corbyhobbs** [comment]
Great, thanks for the clarification and sql Lindsay! It definitely helps to see the nuts and bolts behind the aggregation.

Based off the sql, I filtered out 24/48 hour reports (there were no memo notes) from the itemized endpoint showing RNC contributions to Hillary and came up with 24 transactions totaling $291,651. Pretty close to the aggregate endpoint's 22 transactions totaling $297,522, but still a little off and I'm not sure why. 

I also noticed several 48 hour reports that seem to not have followup official reports. For example, all five transactions where 'GOOGLE INC' is listed as a payee from the RNC in opposition to Hillary Clinton are classified as 48 hour reports (https://api.open.fec.gov/v1/schedules/schedule_e/?sort_nulls_large=true&payee_name=GOOGLE%20INC&per_page=100&api_key=DEMO_KEY&candidate_id=P00003392&cycle=2016&committee_id=C00003418
). They all took place in April and May of 2015 though, so if I understand correctly there should be an official monthly or quarterly report for that right? As of now, the logic that filters out 24/48 hour reports for the aggregate endpoint would filter all Google transactions out. Transactions for 'INDEPENDENT JOURNAL REVIEW', and 'MICROSOFT ONLINE INC.' are the same way.

**Comment by corbyhobbs** [comment]
Update: I looked at all the itemized transactions from the RNC against Hillary and saw that the payments to Google, Microsoft, and Facebook likely fall under the itemizations to American Express instead. There are memos for each of those transactions saying that earlier media buys with those companies were amended. I guess the RNC settled up the final amounts with their credit card provider instead of Google, Microsoft, and Facebook themselves? If that's the case, the money to those payees is accounted for, although it unfortunately makes aggregation by payee less accurate.

**Comment by corbyhobbs** [comment]
Final question: Seeing as 24/48 hour transactions aren't included in the aggregate endpoint, is there data that tells me what the last update date is for what's included? The closest thing I can find to a date in the aggregate endpoint is 'load_date', but I'm not sure if that's the right date to look at.

**Comment by corbyhobbs** [comment]
Hey Lindsay - Hope you had a good Thanskgiving!

I added some more comments to issue #1364 but I'm not sure I'm able to
reopen it on my own. From what I understand, once an issue is closed by a
repo collaborator, the original issue poster is unable to reopen it without
their permission. Just wanted to let you know in case you missed it.

I also came across an interesting issue with the "PROGRESSIVE VOTE AKA
PROGRESSIVE DEMOCRATS OF AMERICA" committee being listed as both supporting
and opposing Bernie Sanders according to the schedule E API (link to query
here
<https://api.open.fec.gov/v1/committee/C00402800/schedules/schedule_e/by_candidate/?page=1&sort_nulls_large=true&per_page=20&api_key=DEMO_KEY&candidate_id=P60007168&cycle=2016>).
Could be accurate, but it is definitely unusual so if it turns out to be a
data issue I thought you'd want to know.

Thanks!
Corby

On Thu, Nov 19, 2015 at 10:55 AM, Lindsay Young <notifications@github.com>
wrote:

> Closed #1364 <https://github.com/18F/openFEC/issues/1364>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1364#event-469323186>.
>



-- 


*Corby Hobbs* | Product Manager, InsideGov <http://insidegov.com/>
phone: 917.648.7562 | skype: corby.hobbs
www.graphiq.com | We're Hiring! <https://www.graphiq.com/careers>

**Comment by LindsayYoung** [comment]
I think that it is just a filing error. The FEC is going to represent the data that is turned in. I ran into that a lot when I used to use this data for reporting. 

Here are the transactions for that:
https://api.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY&candidate_id=P60007168&committee_id=C00402800&cycle=2016

(This also makes me realize filtering for `form_type` on that endpoint would be extremely useful.)

From that view, you can follow the pdf url on the oppose transaction's pdf url and see that is how the transaction was filed.  

Here is an example of conflicting information on the same page:
http://docquery.fec.gov/cgi-bin/fecimg/?201508209000925353

For the aggregates they are updated quarterly when the committee files their, if you are talking about the aggregates by candidate, that is updated on a rolling bases since the different groups can file at different times. Though for this it should be consistent. For the committees, looking on the filings endpoint for their last F5 or F3x, would be a good way to go.  

I closed the issue because I did not think we had more action items on it. I did not realize you could not reopen. Also, feel free to make new tickets. 

Hope that is helpful.

**Comment by corbyhobbs** [comment]
Got it. Thanks for those explanations, really appreciate it. Is it safe to
say that the Schedule E by Candidate endpoint is updated every day then?

Also, could you talk a little more about the significance of the 'form
type' field and why it would be useful? When I queried the candidate
endpoint for all presidential candidates, almost all the form types listed
there were 'F2Z' (there were some F2's thrown in there as well). They were
all almost exactly the same so I assumed the data was more or less
extraneous. Also, when I tried to find more info about these forms from the
Forms <http://www.fec.gov/info/forms.shtml> page I couldn't find anything
on 2Z (or 3X) so I'm not sure what to make of those.

Also wanted to link
<https://w.graphiq.com/w/3JfTHrtEm1v?&external_preview=1&data-script-version=true&rnd=91453817>
you to an example of a visualization I built using the Schedule E data for
Clinton so far. Thanks again for everything! Looking forward to making more
of these going forward.


On Mon, Nov 30, 2015 at 5:15 PM, Lindsay Young <notifications@github.com>
wrote:

> I think that it is just a filing error. The FEC is going to represent the
> data that is turned in. I ran into that a lot when I used to use this data
> for reporting.
>
> Here are the transactions for that:
>
> https://api.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY&candidate_id=P60007168&committee_id=C00402800&cycle=2016
>
> (This also makes me realize filtering for form_type on that endpoint
> would be extremely useful.)
>
> From that view, you can follow the pdf url on the oppose transaction's pdf
> url and see that is how the transaction was filed.
>
> Here is an example of conflicting information on the same page:
> http://docquery.fec.gov/cgi-bin/fecimg/?201508209000925353
>
> For the aggregates they are updated quarterly when the committee files
> their, if you are talking about the aggregates by candidate, that is
> updated on a rolling bases since the different groups can file at different
> times. Though for this it should be consistent. For the committees, looking
> on the filings endpoint for their last F5 or F3x, would be a good way to
> go.
>
> I closed the issue because I did not think we had more action items on it.
> I did not realize you could not reopen. Also, feel free to make new
> tickets.
>
> Hope that is helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1364#issuecomment-160779190>.
>



-- 


*Corby Hobbs* | Product Manager, InsideGov <http://insidegov.com/>
phone: 917.648.7562 | skype: corby.hobbs
www.graphiq.com | We're Hiring! <https://www.graphiq.com/careers>

**Comment by LindsayYoung** [comment]
Right now we are updating nightly but we are still working on getting the timing right with FEC updates, so it can be a day behind. We are working on that. 

F2z is not a form, but an internal update for things like seat status that are updated internally in the FEC. 

Also, that's a pretty graphic!
