### ISSUE TITLE
Discussion: Election aggregate interface

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1371]
The interface for election aggregates proposed in #1352 adds an optional `period` query parameter to various endpoints (candidate totals, election totals, etc.). If this parameter is false (the default), then values aren't aggregated by election--we return two-year values as normal. But if `period` is true, we return aggregates by election.

@arowla pointed out that this might not be the clearest name for this parameter. Other options might include `election_full`, `election_total`, `election_period`, etc. This isn't hard to change, but it's probably best to settle on a reasonable name now to avoid breaking changes in the API.

Thoughts on a better name @LindsayYoung @noahmanger?

**Comment by LindsayYoung** [comment]
Am I reading correctly that period is a boolean? If it is a boolean, I think `election_full` or `election_full_term` would make most sense.

**Comment by arowla** [comment]
Yes, it's a boolean. And `election_full` was my favorite, too.

**Comment by noahmanger** [comment]
:+1:

**Comment by jmcarp** [comment]
Renamed in 7dc3e65. Thanks all!
