### ISSUE TITLE
Discussion: Redirect on incompatible cycle and election aggregate

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1372]
With the proposed interface for election aggregates in #1352, it's possible for users to create URLs with incompatible query parameters. For example, it makes sense if a user looks up a presidential candidate with /candidate/C000/?cycle=2012&period=true, or /candidate/C000/?cycle=2010&period=false. The former query gets aggregates for the 2009-2012 election, and the latter gets two-year values for 2009-2010. But a user can also submit a query like /candidate/C000/?cycle=2010&period=true. The behavior of this kind of query isn't defined, since there isn't a presidential election that ends in 2010. I can think of three reasonable responses in this situation:

1. Throw a 404, since the resource the user asked for doesn't exist
1. Redirect to the specified off-year cycle with `period=false`
    * In this example, /candidate/C000/?cycle=2010&period=false
1. Redirect to the next election with `period=true`
    * In this example, /candidate/C000/?cycle=2012&period=true

Right now, the proposed code implements the second option, but @arowla expressed a preference for the third. Now that I think about it, either's fine with me. I'm curious to hear what others think about this issue. It's not urgent, since we can easily change the behavior after merging the feature, but may as well get it right to start with.

cc @noahmanger @jenniferthibault @LindsayYoung

**Comment by noahmanger** [comment]
Hmmm. I have a slight preference for #2 as I would think that of the two parameters, the user would be more likely to be correct in choosing the year they're looking for, but I'm not going on any more than a hunch. But I suppose if we're renaming the parameter to `election_full` than maybe that won't be as true. @arowla why do you vote 3?

I prefer either option to a 404.

**Comment by arowla** [comment]
I think indicating you want the whole election cycle should trump the year
entered.... If you say you want the whole election cycle, you probably
_really want_ the whole election cycle, not a portion of it.

On Tue, Nov 24, 2015 at 12:15 PM, Noah Manger <notifications@github.com>
wrote:

> Hmmm. I have a slight preference for #2
> <https://github.com/18F/openFEC/issues/2> as I would think that of the
> two parameters, the user would be more likely to be correct in choosing the
> year they're looking for, but I'm not going on any more than a hunch. But I
> suppose if we're renaming the parameter to election_full than maybe that
> won't be as true. @arowla <https://github.com/arowla> why do you vote 3?
>
> I prefer either option to a 404.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1372#issuecomment-159345424>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by noahmanger** [comment]
Ah. Ok I see it that way now. :+1:

**Comment by LindsayYoung** [comment]
I like option 3. It makes the most sense to me of the redirect options. 

I also wonder if returning an empty result set is most consistent with the rest of the behavior on the site. For example:
https://api.open.fec.gov/v1/candidates/?api_key=DEMO_KEY&cycle=1991

**Comment by jmcarp** [comment]
Thanks all! Implemented in https://github.com/jmcarp/openFEC-web-app/commit/60ff017b1b454593e1b52499b84e4ab6e86813ce.
