### ISSUE TITLE
Add notifications for CF deployments

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1375]
We should know which branch is deployed to each Cloud Foundry environment at all times. Code can be deployed both manually and automatically, via Travis CI, so it isn't always obvious which code is running where. I propose adding a post-deploy Slack notification, like this:

"openFEC/develop deployed to fec/dev via build c3ad10".

If this pollutes our channel too much, we can add a separate fec-deploy channel, but that's another question.

**Comment by LindsayYoung** [comment]
sounds like a good idea to me
