### ISSUE TITLE
Estimate times for data downloads

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1380]
E.g., how long does it take to download:
* All year-end filings since 2009 (~84k rows)
* All Schedule A records for Obama for America over $200 (~686k rows)
* All disbursements over $1000 (~1.9m rows)

This should be useful for setting preliminary caps on download sizes (see #1378). I'll take a look this week.

cc @LindsayYoung @noahmanger

**Comment by noahmanger** [comment]
Card for reference: https://18f.storiesonboard.com/m/fec/!card/5wzt02F1sSSdiTnUBqI-VQ

**Comment by noahmanger** [comment]
Do we still need this issue? I don't think we do.

**Comment by LindsayYoung** [comment]
I don't think so either
