### ISSUE TITLE
Query params on committees API do not appear to apply to result set

### ISSUE THREAD

**Issue by geoffharcourt** [18F/openFEC#1381]
I tried filtering committees at the candidate committees API endpoint by `designation` and `committee_type`, and neither filter appears to affect the query.

Here's an example, looking at Orrin Hatch's affiliated committees, filtering for by designation for his primary fundraising committee or leadership PACs, and filtering for only House- or Senate-committees (trying to avoid Joint-affiliation committees):

https://api.open.fec.gov/v1/candidate/S6UT00063/committees/?api_key=DEMO_KEY&designation=D&designation=P&committee_type=H&committee_type=S&per_page=20&sort_nulls_large=true&sort=name&page=1

The result set includes 20 committees, several of which don't match the filters.

**Comment by LindsayYoung** [comment]
Humm, I am not sure why this is not working for you. When I click on that link, I only get one committee returned.

**Comment by geoffharcourt** [comment]
I now only see one committee. Closing this out, thanks!

**Comment by LindsayYoung** [comment]
Glad that is working for you. Thanks for writing in!
