### ISSUE TITLE
Define filter output in download manifest

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1391]
We decided to try to add better descriptions of filters to the data download manifest yesterday. I started looking into this today and noticed a potential issue that I wanted to float past folks. My first thought was to pull filter documentation from our existing swagger docs for the filters that the user specified, so that we'd get something like this:

```
Filters:
    is_individual (Restrict to non-earmarked individual contributions): true
    contributor_state (State of contributor): NY, CA, TX
    ...
```

The problem I encountered here is that many of our swagger docs are long and complicated enough that they'd make this format look a little weird. For example, the filter documentation for the `candidate_status` parameter looks like this:

```
One letter code explaining if the candidate is:
- C present candidate
- F future candidate
- N not yet a candidate
- P prior candidate
```

This clearly doesn't fit a concise one-line-per filter style. Is that all right? We could make each filter a paragraph instead:

```
Filters:

is_individual: true
Restrict to non-earmarked individual contributions

candidate_status: C, N, P
One letter code explaining if the candidate is:
- C present candidate
- F future candidate
- N not yet a candidate
- P prior candidate
...
```

Thoughts @LindsayYoung @noahmanger?

**Comment by LindsayYoung** [comment]
I think making the filters into paragraphs sounds like a good option, I would rather give more explanation to the data since it gets complicated.

**Comment by jenniferthibault** [comment]
+1 to more explanation when it helps downloaders understand our system.

**Comment by leahbannon** [comment]
This looks good to me - maybe we should keep the parentheses or something, though? In some cases it might not be totally clear which is the description and which is the option chosen (like in that candidate_status) example.

**Comment by noahmanger** [comment]
+1 to paragraphs.

**Comment by emileighoutlaw** [comment]
+1 to more explanation (love how it is in easily scanned chunks)
