### ISSUE TITLE
Round up to next election in candidate summaries

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1400]
Some Senate candidates are marked as running in a future election year, but don't have candidate information or committee linkages in that year. For example, Tammy Baldwin (S2WI00219) is marked as running in 2018, but has no two-year history for 2017-2018. This leads to unexpected behavior on the candidate's detail page: if the URL includes the most recent election ("cycle=2018"), we get a 404, since the candidate has no history entries for that cycle.

One proposed solution: add an `election_full` flag to the candidate history endpoint; if `true`, return the most recent candidate history within the election cycle. Alternatively, we could allow users to pass an `election` or `election_year` parameter instead of the normal `cycle` parameter; querying by `election_year` would return the most recent cycle in the election period.

Preferences @LindsayYoung @noahmanger?

**Comment by noahmanger** [comment]
I'm not sure I super get the difference, but on first blush seems more friendly to add an additional flag rather than another parameter (`election`) that's very similar but still different from an existing one (`cycle`). But I defer to you two.

**Comment by jmcarp** [comment]
It's a pretty minor difference, and realistically, I'm thinking the data site will be the main or only user of the flag. But here's the difference:

`?cycle=2010&election_full=true`
vs
`?cycle=2010&election_year=2012`

I'm thinking the first one's right--it's a few characters shorter, and doesn't require the consumer to figure out the next election year themselves.

**Comment by noahmanger** [comment]
Ah got it. Yeah that makes sense.
