### ISSUE TITLE
Add remaining filters to schedule_e endpoint

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1405]
The [itemized IE table](https://github.com/18F/openFEC-web-app/pull/987) requires additional filters on the schedule_e endpoint. The only one I know for sure is currently "support / oppose". 

Do we want anything else? Filing date perhaps?

**Comment by jmcarp** [comment]
Dates are always nice. For consistency, should we use the min and max dates we've been using elsewhere?

**Comment by noahmanger** [comment]
That'd be good.
