### ISSUE TITLE
Restrict candidate-committee linkages by committee type

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1406]
Some candidates are linked to committees associated with the wrong office. For example, House candidate Tammy Baldwin is associated with Senate committee Tammy Baldwin for Senate in 2014. This has the undesired effects of counting receipts from Baldwin for Senate for both the House and Senate versions of the candidate. One solution here (I think @PaulClark2 mentioned this in an example query a while back) is to restrict linkages to committees whose type match the first letter of the candidate ID.

@PaulClark2, can you verify that this is correct? If so, I can submit this as a hotfix and get Tammy Baldwin's numbers fixed quick.

cc @LindsayYoung

**Comment by PaulClark2** [comment]
@jmcarp that's correct substr(cand_id,1,1) = cmte_tp

**Comment by jmcarp** [comment]
Now that I've had more time to look at the data, I'm noticing that this change would make the beta site different from the current site. FEC Viewer lists the principal committee of House candidate Tammy Baldwin as Baldwin for Senate in 2012 and onward. If we make this change, House candidate Tammy Baldwin will show up as having no principal committee after 2010. Is that correct @PaulClark2?

**Comment by PaulClark2** [comment]
@jmcarp 

These two links for Baldwin are bad and I will delete them.   She used her old house committee as her senate committee. 

198123	H8WI00018	2012	2014	C00326801	S
204626	H8WI00018	2012	2016	C00326801	S

select * CAND_CMTE_LINKAGE where cand_id = 'H8WI00018' and fec_election_yr >= 2014 and cmte_dsgn in ('P', 'A');

delete from CAND_CMTE_LINKAGE WHERE LINKAGE_ID IN (204626, 198123);

The Viewer shouldn't list Baldwin as a House candidate after 2012.  The bad links are causing this problem.

**Comment by jmcarp** [comment]
@PaulClark2 thanks, that makes sense. Meanwhile, I submitted a patch to ignore mismatched linkage rows in #1409. Will that fix still be necessary after the offending rows are deleted? I checked, and there are several hundred other mismatched rows in the linkages table.

**Comment by PaulClark2** [comment]
I'll need to review them.   In some cases, the mismatch might be ok if it only last for one cycle.  For example, if a house member retires mid-cycle and converts her house committee to a PAC the house link to the candidate should remain until the end of the current 2-year period.  The link should be broken at the beginning of the next 2-year period.  

The most problematic are candidate committees that change type because the candidate is running for a different office.

**Comment by jmcarp** [comment]
Looks like there are almost 400 mismatched linkage rows:

```
select cand_id, cmte_id, fec_election_yr, cand_election_yr, cmte_tp from cand_cmte_linkage where left(cand_id, 1) != cmte_tp and cmte_tp in ('P', 'S', 'H');
```

Those would all be excluded under the changes in #1409.

**Comment by jmcarp** [comment]
@PaulClark2, how would you like to proceed with this? Do you want to review the linkage rows whose candidate IDs don't match their committee types, or should we filter them out programmatically (there's a pull request in that would do this)?

**Comment by PaulClark2** [comment]
@jmcarp filter them out programmatically.   I've been reviewing the links this morning and the programmatic fix selects the correct link.  I'll clean-up the table as I have time. 

one example: 
|LINKAGE_ID| CAND_ID| CAND_ELECTION_YR| FEC_ELECTION_YR| CMTE_ID |CMTE_TP| note|
|_________|________|___________________|_________|________|___________|_______|
|41126|	H6MO07128|	2008|	2008|	C00304758|	H|	correct |
|151439|	H6MO07128|	2008|	2010|	C00304758|	S|	ok switched office|
|153875|	S0MO00183|	2010|	2010|	C00304758|	S|	correct |
|190526|	H6MO07128|	2008|	2012|	C00304758|	S|	invalid|
|191674|	S0MO00183|	2016|	2012|	C00304758|	S|	correct |
|197600|	H6MO07128|	2008|	2014|	C00304758|	S|	invalid|
|198703|	S0MO00183|	2016|	2014|	C00304758|	S|	correct |
|204227|	H6MO07128|	2008|	2016|	C00304758|	S|	invalid|
|205077|	S0MO00183|	2016|	2016|	C00304758|	S|	correct |

**Comment by jmcarp** [comment]
Done!
