### ISSUE TITLE
Figure out Act Blue data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1410]
Two things came up today:
1. Act Blue contributions are having employer and occupation fields show up, even though they are listed as coming from the committee, and not the individual.
2. They don't seem to be being filtered out via the "unique" filter. 

Maybe two separate issues, and I doubt it's new behavior, but flagging here.

**Comment by PaulClark2** [comment]
https://github.com/18F/openFEC/issues/1308  @jwchumley

**Comment by PaulClark2** [comment]
https://github.com/18F/openFEC/issues/1435
