### ISSUE TITLE
Add mirrors to production

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1415]
So that our servers can handle exporting receipts and disbursements, make the necessary infrastructure upgrades.

- [x] Send proposal to FEC
- [x] Purchase

**Comment by noahmanger** [comment]
Anyway we can do this before the close of the sprint?

**Comment by jmcarp** [comment]
I can definitely get the price per read replica tomorrow, and we can set one up anytime, but we're not actually going to be able to enable downloads on receipts or disbursements until we get partitioning reviewed and merged, and figure out the related behavior on the itemized data tables.

**Comment by jmcarp** [comment]
Looks like around $240 per replica per month.

<img width="794" alt="screen shot 2016-01-22 at 3 14 28 pm" src="https://cloud.githubusercontent.com/assets/1633460/12521821/e4cdd6e0-c11a-11e5-88e1-2d3b8e17f94b.png">

**Comment by noahmanger** [comment]
No longer relevant.

**Comment by noahmanger** [comment]
Oops, I misunderstood. Sounds like we still want to do this.

**Comment by noahmanger** [comment]
We've got the thumbs up to do this so just need to turn it on and add the necessary env variables.

**Comment by ccostino** [comment]
I'll be taking care of this tonight.  As a part of the work, I'll be updating the RDS instances to version 9.5.4 as well (just a minor version update, there should only be a few moments of downtime).

**Comment by ccostino** [comment]
The database instances have all been upgraded to version 9.5.4 and the production read replica is created.  Now we just need to restage/redeploy production to make use of it, but we're currently seeing a replication issue with it, so we need to investigate that first.

I also created documentation in our wiki on how to create, configure, manage, and test the read replicas here:  https://github.com/18F/openFEC/wiki/Creating-and-configuring-a-read-replica-in-Amazon-RDS

**Comment by ccostino** [comment]
The replication issue should be resolved at this point and we're using the replica in production!  Closing this issue. :-) 🎉
