### ISSUE TITLE
Add data dictionary to download manifest

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1416]
So that users understand the data they're getting in their downloads, include an automatically generated data dictionary in the manifest file.

**Comment by noahmanger** [comment]
Tasks for this sprint:
- [ ] FEC build out the dictionary in a doc
- [ ] 18F add to the API
- [ ] Add to the download manifest

**Comment by LindsayYoung** [comment]
I don't think we should do a document, I would like to get Paul or Jeff to propose edits directly.

**Comment by noahmanger** [comment]
:+1:

**Comment by noahmanger** [comment]
Status: data is here but we need to add it to the manifest.

**Comment by noahmanger** [comment]
@LindsayYoung this issue doesn't strictly fall into the priorities we identified. Should we remove it from "in progress"?

**Comment by vrajmohan** [comment]
Given the move away from a zipped file to a CSV file, this issue is no longer relevant.
