### ISSUE TITLE
find things for the micro-bid code auction

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1418]
Adding this so we don't forget to plan to spend some time on doing this, if we want to do this.

This is the example issue they did for the first auction: https://github.com/18f/calc/issues/255

Also, @vdavez's blog post about lessons learned from the first auction: https://18f.gsa.gov/2015/11/06/micro-purchase-lessons/

**Comment by evankroske** [comment]
If this project had an issue that was as self-contained and actionable as https://github.com/18F/calc/issues/255, I would work on it for free. However, if it were a code auction, I wouldn't start a company to participate.

**Comment by LindsayYoung** [comment]
Thanks Evan!

I feel like this project is great for the open source community. And you are right, we don't have any self-contained actionable requests. We should keep our eye out for these kinds of tasks and properly explain and tag them.

Is there any particular kind of dev work that you would like to contribute? Such as front end or back end? I will try to keep an eye out.

**Comment by evankroske** [comment]
I agree! openFEC is setting an example for developing in the open. If you
could look for a front-end project for me, I would really appreciate it!
