### ISSUE TITLE
Williams totals really high

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1424]
https://beta.fec.gov/data/candidate/P60005204/

it shows 11 million, instead of 11 thousand

**Comment by jmcarp** [comment]
It looks like that's what the candidate's committee reported in October 2015: http://docquery.fec.gov/pdf/612/201510260300030612/201510260300030612.pdf

**Comment by PaulClark2** [comment]
201510260300030612 was deleted and re-entered as a miscellaneous document.  So the financial data should not be included.  

![image](https://cloud.githubusercontent.com/assets/11817734/12011077/435a46a4-ac8e-11e5-935b-4b7f4f280633.jpeg)

**Comment by jmcarp** [comment]
I see. It looks like the relevant row hasn't been deleted from `factpresidential_f3p`:

```
fec=> select ttl_receipts_sum_page_per from factpresidential_f3p where begin_image_num = '201510260300030612';
 ttl_receipts_sum_page_per
---------------------------
               11505000.00
(1 row)
```

Once that row is deleted, the issue should be resolved.

**Comment by PaulClark2** [comment]
I've entered a delete transaction for 201510260300030612

CMTE_ID	| BEGIN_IMAGE_NUM	| END_IMAGE_NUM | SUB_ID | CHG_DEL_ID | STATUS
----- | ----- | ----- |----- | ----- | ----- 
C00558999 | 201510260300030612 | 201510260300030627 | 1122820150018164171 | 1102620150018000071 | 3

**Comment by LindsayYoung** [comment]
Thanks Paul!

**Comment by jmcarp** [comment]
It looks like the relevant row in `factpresidential_f3p` hasn't changed yet. Is there anything else we need to do here?

**Comment by PaulClark2** [comment]
We have manually update two rows: one for Whigham-Williams and one for Mercer.  Rohan has pushed these changes to your DB instances.  This should finally fix it.  


`update factpresidential_f3p set expire_date = '27-OCT-2015' where factpresidential_f3p_sk = 10020848;`
`update factpresidential_f3p set expire_date = '15-OCT-2015' where factpresidential_f3p_sk = 10020755;`


-------------------
ELAINE WHIGHAM-WILLIAMS 
`select * from dimcmte where cmte_id = 'C00558999';` 
`select * from factpresidential_f3p where cmte_sk = 10048938;`

MERCER, LEE 
`select * from dimcmte where cmte_id = 'C00428599';`
`select * from factpresidential_f3p where cmte_sk = 10039808;`
---------------------

**Comment by noahmanger** [comment]
Looks like this is resolved now.
