### ISSUE TITLE
Handle itemized receipts from individuals with committee contributor IDs

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1426]
There are several outstanding issues related to the behavior of the `is_individual` filter. I'd like to consolidate them here, and provide more concrete examples and proposals, with the hope of moving discussion to one place and finding a good resolution.

I've checked out several examples of itemized receipts that have been reported as showing up unexpectedly with the `is_individual` filter enabled. Most seem to follow a common pattern: they're correctly flagged as individual, based on e.g. the `receipt_tp` column. But they have both a `contbr_id` that points to a committee like ActBlue, and a `contbr_nm` referring to an individual contributor. Our front-end logic displays the contributor as a committee if `contbr_id` is present, then defaults to `contbr_nm`--that's why these contributions are displayed as coming from ActBlue and not from the individual contributor. What's puzzling to me is that, at least in the cases I've checked by hand, the original filings *don't* include the offending `contbr_id` value--it looks like those are being added somewhere in the coding process.

A few examples:
* A contribution of $1000 from Julian Anthony Haywood to the DSCC; the `sched_a_sk` is 247823485. This receipt is coded as individual because the `receipt_tp` is "15E". The `contbr_nm` value is correctly listed as Julian Anthony Haywood, but the `contbr_id` refers to ActBlue. As explained above, that means we display the contributor as ActBlue on beta.fec.gov. The original image does *not* list a contributor ID--this seems to be added during coding: http://docquery.fec.gov/cgi-bin/fecimg/?201511200200319340 (bottom row).
* A contribution of $200 from Donna L Rosen, also to the DSCC; the `sched_a_sk` is 247829880. Just like the previous example, `contbr_nm` is correct, but `contbr_id` refers to ActBlue. And again, the contributor ID doesn't seem to be present in the original filing: http://docquery.fec.gov/cgi-bin/fecimg/?201511200200321472.

Proposals:
* Change the front-end logic to use the contributor name instead of the information loaded from the associated committee, `contbr_id`. We could do this in all cases, or try to infer from the rest of the data whether `contbr_nm` or `contbr_id` is more reliable.
* Change the data. It seems counter-intuitive that receipt records would have conflicting contributor names and IDs. Are these data entry or coding errors? Can they be fixed on the FEC side?

Note: the `is_individual` logic seems to be working as expected here--as far as I can tell, this is an issue about how to handle conflicting data, not about filtering.

@PaulClark2 @jwchumley @LindsayYoung @noahmanger

**Comment by noahmanger** [comment]
Thanks for pulling this all together. My preference would be to try to fix the data. Building logic off of contributor name instead of what's associated with the committee id seems like it would make the data messier, no?

**Comment by jmcarp** [comment]
@noahmanger yes, that was my intuition too, which is why the current behavior is to use IDs over names where available. Agreed that it would be preferable to fix the data, but I'm not sure how much of a lift that would be--thoughts @PaulClark2?

**Comment by PaulClark2** [comment]
Haywood earmark
`select * from sched_a where cmte_id = 'C00042366' and sched_a_sk in ('247823485', '247823486');`

Rosen earmark
`select * from sched_a where cmte_id = 'C00042366' and sched_a_sk in ('247829879', '247829880');`

**Comment by PaulClark2** [comment]
I think there's a misunderstanding about the coding rules for earmarked receipts.   Earmarked receipts are reported in two rows:  the earmarking organization and the actual contributor.   When a contribution is earmarked the row containing the information about the actual contributor is categorized (coded) as receipt type "15E" and the earmarking organization's committee ID is entered in the contributor ID field.   This should be true for all earmarked receipts.  

`select count(*) from cfdm.sched_a where contb_receipt_dt between '01-JAN-2015' and '28-DEC-2015' and receipt_tp = '15E';`
58,334 15Es

`select count(*) from cfdm.sched_a where contb_receipt_dt between '01-JAN-2015' and '28-DEC-2015' and receipt_tp = '15E' and contbr_id is null;`
593 15Es do not have contributor IDs.  These need to be reviewed and I will send them to our coding and entry staff.  

I think we need to adjust the rule we are using to display contributor information for transaction type "15E" so that we do not use the contributor ID to populate contributor name.

**Comment by jmcarp** [comment]
Thanks for clarifying @PaulClark2. I didn't know that the ID of the earmarking organization was entered as the contributor ID for all rows coded 15E. One more question about this (hopefully the last one!): should we update our logic at the level of the API, or for the website only? I can imagine the current behavior being confusing for API users as well as users of the website, so we might want to address the issue by nullifying contributor IDs for 15E receipts on import. Or, if we want API users to have access to that (potentially confusing) information, we can keep the API as-is and make the change to the display rules on the website.

An example of what I mean about the API being confusing: the first result in a request to https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&image_number=14020104348 is coded as 15E, so the `contributor_name` and `contributor` fields don't match.

**Comment by PaulClark2** [comment]
@jmcarp I think knowing the earmarking organization is important to some people.  So, I'd rather not eliminate the information.   Also, if an API user has used the FTP files I think they would expect to see a contributor ID for 15E transactions.  

I think we should only update the website display rules.

**Comment by LindsayYoung** [comment]
I think we should keep the ids- they are useful for some people using the data and we should add some documentation around this. 

Also, I don't trust the committee ids in the transaction data as much as I do elsewhere, since it is more prone to  filer and processing errors. I am thinking for the schedule data we might not want to override the contributor name field. 

I think it is still good to have search by id, maybe we want to make that more explicit, by calling it search by committee id, and then have the typeahead help you find the name and show the id. What do you think @noahmanger?

**Comment by noahmanger** [comment]
> I am thinking for the schedule data we might not want to override the contributor name field.

It sounds like this is what we're doing now, correct?

> I think it is still good to have search by id, maybe we want to make that more explicit, by calling it search by committee id, and then have the typeahead help you find the name and show the id.

I started [this issue](https://github.com/18F/openFEC-web-app/issues/982) for figuring out a more cohesive experience for committee name / id / typehead filters, so let's move that discussion over there. That's a good point, and should be part of the overall design of that component.

Last question: I love that [here](https://github.com/18F/openFEC-web-app/pull/1012/files#diff-228ebc1bb4a5df545be9386325ff884fR19) we're still showing "Earmarked by". Is it possible (and if so, how) to filter for all receipts that have been earmarked by a particular committee? Does the regular committee contributor filter do this, or do we need a different one?

**Comment by LindsayYoung** [comment]
I think this is all being implemented, but I did not want to leave anything hanging. 

I think you would find earmarked contributions by searching by the committee id, it would not be a separate filter (to make that filter we would need to override things in the other fields and I think that would me more confusing than it is worth). Though, it might be worth it to filter by line number- that is a different discussion. 

I think earmarked by should show up in the information that slides out when you click on a row. That seems to be happening in 18F/openFEC-web-app/pull/1012
