### ISSUE TITLE
download counts:  display, manifest and csv

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#1430]
@jmcarp I don't know if this helps but it might be a starting point.  I downloaded committees by type.   There are count mismatches for presidential, house, person/group IEs and electioneering communication committees.  I also noticed when filtering for SSFs the organization type codes do not become part of the url.  

type |	display count |	manifest count |	csv count |	url |	note 
----- | ----- | ----- | ----- | ----- | ----- 					
Presidential (P) |	913 |	916 |	916 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=P |	 |
House (H) |	3,127 |	5,480 |	3,129 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=H | |	
Person/Group IEs (I) |	1,037 |	1,044 |	1,044 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=I | |	
Electioneering Comm (E) | 	111 |	113 |	113 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=E | |	
SSFs | 	3,458 |	3,458 |	3,458 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016 |	org type filters not in URL
Senate (S) |	704 |	704 |	704 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=S | |	
super PACs (O) |	1,697 |	1,697 |	1,697 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=O | |	
single candidate IEs (U) |	92 |	92 |	92 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=U |	 |
Lobbyist (desig B) |	1,438 |	1,438 |	1,438 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&designation=B |	multiple committee types
Leadership (desig D) |	691 |	691 |	691 |	https://fec-stage-proxy.18f.gov/data/committees/?designation=D |	multiple committee types
PACs (N and Q) | 	5,641 |	5,641 |	5,641 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=N&committee_type=Q	 |
Hybrid PACs (V and W) |	125 |	125 |	125 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=V&committee_type=W  |	
JFs (desig J) |	440 |	440 |	440 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&designation=J |	multiple committee types
Communication Cost (C) |	176 |	176 |	176 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=C |	
Delegate (D) |	4 |	4 |	4 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=D |	
Party (X, Y, Z)  |	449 |	449 |	449 |	https://fec-stage-proxy.18f.gov/data/committees/?cycle=2016&committee_type=X&committee_type=Y&committee_type=Z |

**Comment by jmcarp** [comment]
Resolved in dd3abcdee76618bf8ea1436cb2ddef636cb7fbfe. Thanks for the counts!
