### ISSUE TITLE
Messy calendar data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1441]
I know y'all are working hard to clean up calendar data, but I've been catching things as I've been working on the frontend so thought I'd catalogue them here to make sure you see them.

In December 2015, some duplicate events:

![screen shot 2016-01-07 at 5 27 06 pm](https://cloud.githubusercontent.com/assets/1696495/12187817/ee7a6ed2-b563-11e5-8ada-6fae7375db7c.png)

On March 3, 2016, null fields:
![screen shot 2016-01-07 at 5 31 42 pm](https://cloud.githubusercontent.com/assets/1696495/12187868/917c2d0a-b564-11e5-87a7-3d3d7fcdee9b.png)

I'm sure we'll find more, but wanted to get this started.

**Comment by noahmanger** [comment]
Also, I thought we weren't doing duplicate events for different states. I think that's what's happening here:
![screen shot 2016-01-07 at 5 47 15 pm](https://cloud.githubusercontent.com/assets/1696495/12188075/c410f988-b566-11e5-8107-f7a8959b6e4d.png)

**Comment by noahmanger** [comment]
Also, just randomly noticed that we don't have the March 15 Ohio primary in there.

**Comment by noahmanger** [comment]
Also, the time data for events seems to be off in various ways. For example:

![screen shot 2016-01-07 at 6 41 03 pm](https://cloud.githubusercontent.com/assets/1696495/12188893/4bc7d52a-b56e-11e5-88d4-750a9abb0889.png)

It says 12am start time, has no end time (thus shows up as all-day), but the body text says different.

**Comment by LindsayYoung** [comment]
End time is a field in the data, not from the text so if they don't give us an end time we don't try to parse it out.

**Comment by LindsayYoung** [comment]
We are not doing duplicate events for general election. When we looked at the current calendar it seemed that was the only thing that was not unique by state. We could add additional filters, but it is useful do have separate events when there are a small number of primaries etc. going on.

**Comment by jmcarp** [comment]
Fixed some of the incorrect time ranges in https://github.com/jmcarp/fec-cms/commit/b01fde54d6b94aeaaed1d27769dfd4ce806e9134. Meanwhile, what's next on this issue? Can we sort out which issues we can fix on our side and which will need a response from FEC?

cc @LindsayYoung @noahmanger

**Comment by jmcarp** [comment]
Fixed the missing Ohio primary in https://github.com/18F/openFEC/commit/06f5c80201d01d348989dff96dc1b5195ebf28ca.

**Comment by jmcarp** [comment]
@LindsayYoung I'm thinking we'll want to do more aggregation on reporting periods--the example @noahmanger pointed out has 18 reporting periods on the same day, which seem to be the same except for state. Want to take a look at that?

**Comment by LindsayYoung** [comment]
That would make sense to me. I can take a look at it tomorrow afternoon, feel free to jump on it if you have time before then.

**Comment by noahmanger** [comment]
So I just took a look between the actual FEC calendar and ours, and there's a bunch of inconsistencies:
![comparison](https://cloud.githubusercontent.com/assets/1696495/12525577/1bc9d97e-c11a-11e5-808b-a44ca1717f47.png)

- A bunch of our events seem to be 1 day ahead of their events
- We're missing various dates on our end (like the Feb 7 EC period start)

There might be more stuff, but that's what I noticed.

**Comment by noahmanger** [comment]
Not messy data, but a data formatting request: can we remove the space between the parentheses and the text in the event summaries?

<img width="301" alt="screen shot 2016-01-25 at 4 13 00 pm" src="https://cloud.githubusercontent.com/assets/1696495/12568899/ad971324-c37e-11e5-9b1f-24ec69482e95.png">

**Comment by noahmanger** [comment]
Next task: break into samller issues

**Comment by noahmanger** [comment]
A bunch of this stuff was resolved (thanks!) and the remaining things are moved to new issues:

https://github.com/18F/openFEC/issues/1475
https://github.com/18F/openFEC/issues/1474

Closing in favor of those.
