### ISSUE TITLE
release: Parasaurolophus

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#1447]
_I'm using this issue to test an approach I'm suggesting for release planning, hopefully fixes https://github.com/18F/openFEC-web-app/issues/1026._

Feature: 
* filter tags (on staging 1/13; :ship: 1/20)
* _[Noah's comment here](https://github.com/18F/Accessibility_Reviews/issues/9#issuecomment-169126885) might be a good example of how to do this once we get the features up on dev/staging._

Prep to :ship: next sprint:
* Other spending pages
* Additional downloads added
* Relevant tabs for committees

Checks
* [ ] will we want to announce this? (we'll need to do some comms planning)
* [ ] [open an issue in Accessibility Reviews repo](https://github.com/18F/Accessibility_Reviews/issues/new) with this checklist and give Bristow a heads up

```
  * Name of the Project:
  * URL:
  * Login details:
  * Date the review is needed:
  * Is this a DHS project?
```

Post links to issues that were created because of this testing in the comments.

**Comment by jmcarp** [comment]
Can this be closed @noahmanger?
