### ISSUE TITLE
Onboard @ccostino

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1453]
Add @ccostino to various services:

* [x] cloud.gov
* [x] api.data.gov
* [x] Stories on board
* [x] npm (fec-style)
* [x] Sentry
* [x] New Relic

Anything I'm forgetting @LindsayYoung @noahmanger?

**Comment by noahmanger** [comment]
Thanks for starting this. Nothing else comes to mind.

**Comment by LindsayYoung** [comment]
I added them to google docs. Can't think of anything else.

**Comment by ccostino** [comment]
Thank you! :-)

**Comment by noahmanger** [comment]
:white_check_mark: Stories on board

**Comment by jmcarp** [comment]
@LindsayYoung: I don't have permission to add users to the fec org or its spaces, so I'm going to assign that to you. It looks like you have the `OrgManager` role on the fec org, so you should have permission to do this--if not, we'll have to ask devops. Relevant docs are here: https://docs.cloudfoundry.org/adminguide/cli-user-management.html

**Comment by LindsayYoung** [comment]
Ok, I will do this tomorrow, thanks for finding the docs!

**Comment by noahmanger** [comment]
All set up.
