### ISSUE TITLE
Caucuses and primary conventions should be filterable as "primaries"

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1455]
Currently applying the "Primary election" filter hides the Iowa caucuses and other primary conventions. I know we had this conversation before, but I think it's important that all of these events be filterable as they are commonly understood, which is as primary elections. 

Is there a reason we can't or shouldn't do that?

**Comment by LindsayYoung** [comment]
The categories in the API don't line up with the 3 election types we are showing. 

We are not creating or tagging any of the data. We are creating categories based on their election codes. The Iowa caucus is tagged as a convention, "election-C" 

The options for all the categories are:
 AOs and Rules
 Commission Meetings
 Conferences
 Conferences and Outreach
 EC Periods
 election-C
 election-G
 election-GR
 election-P
 election-PR
 election-R
 election-SC
 election-SG
 election-SGR
 election-SP
 election-SPR
 Executive Sessions
 FEA Periods
 Federal Holidays
 IE Periods
 Litigation
 Open Meetings
 Other
 Public Hearings
 report-12C
 report-12G
 report-12GR
 report-12P
 report-12PR
 report-12R
 report-12S
 report-12SC
 report-12SG
 report-12SGR
 report-12SP
 report-12SPR
 report-30G
 report-30GR
 report-30R
 report-30S
 report-30SC
 report-30SG
 report-30SGR
 report-M10
 report-M11
 report-M12
 report-M2
 report-M3
 report-M4
 report-M5
 report-M6
 report-M7
 report-M8
 report-M9
 report-MY
 report-Q1
 report-Q2
 report-Q3
 report-YE
 Roundtables
 State Outreach Workshops


Here are what the letters mean in the election codes:

G = general
P = primary
R = runoff
C = convention
S = special

**Comment by noahmanger** [comment]
Gotcha. So what I'm suggesting is that either a) they should be categorized that way (for the sake of mapping onto a typical understanding of what kind of thing they are), or b) that we should have our primary filter also filter type C events, or c) if neither of those options work, we at least need to expose filters for those other types.

My preference is A or B, but I imagine there's side-effects to those that we may want to avoid. What do you think?

**Comment by LindsayYoung** [comment]
A) If we want new data, that would be something that is a task that is better-aligned for FEC experts and not the dev team. 

B) We would have to confirm that all convention types can be classified as primary. I am not sure there aren't outliers that would be wrong. 

We might want to "price out" the primary, general etc filtering as a feature in terms of how many users want/need this and how much time it would take, before sinking even more labor into this. If you are looking at the calendar, the primaries, general and runoffs are already kind of grouped by date. Especially if you are just looking at a month at a time. 

Can we consider 'elections' as a category as a good place to start this MVP version?

**Comment by noahmanger** [comment]
Cool cool. Yeah, you're right. I don't think this fine-grained of filtering is necessary, and simply having an "elections" category that included all elections would probably do the trick. 

The reason I thought this was an issue is that if you selected "primary elections" conventions wouldn't actually show up, which is a problem. But if we just show all elections with a single filter, then that solves that.

Is this a change better made on the API?

**Comment by LindsayYoung** [comment]
It is a small API change. And we have a separate election dates endpoint, so advanced data users can still look for more granular information there. 

The web app can then just look for category `election`

**Comment by noahmanger** [comment]
So when we replace multiple filters with just a single one, it looks a little weird. @jenniferthibault and @emileighoutlaw do you have suggestions? Or should we leave as is:

![screen shot 2016-02-05 at 2 00 53 pm](https://cloud.githubusercontent.com/assets/1696495/12860373/f5f37b54-cc10-11e5-9297-3797db728fdb.png)

**Comment by emileighoutlaw** [comment]
I've been thinking about this over the weekend. I'm not sure there's really a good synonym we could throw in for "elections" either place. Or, at least, nothing that would be as precise and clear as `Elections.`

We might be able to do something like
> Elections
[] All

But that seems like it'd be a different kind of interaction than the other check boxes. 

Curious to hear what Jen's thoughts are, too

**Comment by jenniferthibault** [comment]
Asking a question because I can't quite parse the categories above: Is there any ability to have 

> **Elections**
- [ ] All
- [ ] Presidential
- [ ] Senate
- [ ] House of Representatives

?

So that even if we can't break it down by primary/general yet, there can still be categories that overlap with filters we're applying to the data tables?

**Comment by noahmanger** [comment]
I believe we don't have those options as filters in this case. I think maybe @emileighoutlaw 's suggestion is the way to go.

**Comment by noahmanger** [comment]
Or what about "All elections" so that way that's what the tag says?

<img width="811" alt="screen shot 2016-02-08 at 5 04 21 pm" src="https://cloud.githubusercontent.com/assets/1696495/12904690/0e6d3806-ce86-11e5-99e1-82a60bbf2c66.png">

**Comment by jenniferthibault** [comment]
Ok, thanks. "All elections" works. 
@noahmanger way back when we were working out the logic for these collapsible sections, the first check box of each section was supposed to be an "All _____" that selected/deselected all child elements. Do you think we should work that in or leave it for a later sprint?

**Comment by noahmanger** [comment]
Oh right! Let's save that for when we implemented the accordions and we can
do it all together.

On Mon, Feb 8, 2016 at 5:39 PM, Jennifer Thibault <notifications@github.com>
wrote:

> Ok, thanks. "All elections" works.
> @noahmanger <https://github.com/noahmanger> way back when we were working
> out the logic for these collapsible sections, the first check box of each
> section was supposed to be an "All _____" that selected/deselected all
> child elements. Do you think we should work that in or leave it for a later
> sprint?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/1455#issuecomment-181661839>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by emileighoutlaw** [comment]
Sounds good to me.

Would creating a new calendar CMS for FEC help us solve this problem, too?

**Comment by noahmanger** [comment]
Potentially.
