### ISSUE TITLE
Server errors for certain candidates on dev

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1470]
Sanders Senate campaign has this issue: https://fec-proxy.18f.gov/data/candidate/S4VT00033/?cycle=2018&election_full=true

**Comment by LindsayYoung** [comment]
Is this still happening?

**Comment by adborden** [comment]
Not sure what the behavior was originally described as, but I just got a 500 on that link. Refreshing works and subsequent refreshes seem okay. I think it's the same issue we're seeing https://github.com/18F/fec-eregs/issues/132

No one is looking at this right now, but we are planning to add a retry within this sprint as a short-term fix :(

**Comment by LindsayYoung** [comment]
I think this original it was an issue we solved a while ago, that happened for particular congress people, (frequently for Senators) where they were being linked to cycles they did not run in.

I have seen the `('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))` error and I can see in Sentry, it happens regularly, and 99% of the time is triggered by a spider. Occasionally, I have seen this in our data updates. 

We aren't setting up new accounts at the moment, but we can pair if you want to dig into the errors on Sentry, it is easier to use and has good stack traces.
