### ISSUE TITLE
Combine reporting deadline dates for multiple states

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1474]
On February 18 (for example), there's a bunch of reporting deadlines for the same thing, but multiple states. Can we condense these to be the same event if they're the same category and just list the multiple states?

<img width="274" alt="screen shot 2016-01-29 at 2 23 12 pm" src="https://cloud.githubusercontent.com/assets/1696495/12689796/f8cfd016-c693-11e5-93f2-38c8c66e9b99.png">

**Comment by LindsayYoung** [comment]
Thanks for catching that, I have a PR for it now.
