### ISSUE TITLE
Audit calendar microcopy

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1475]
There's a few places where we're building description or summary fields in kind of unattractive ways. I'm going to log what I'm finding, and would love @emileighoutlaw 's guidance on what it should be:

1. `( report code )` parenthetical in summary:
<img width="301" alt="screen shot 2016-01-29 at 2 24 53 pm" src="https://cloud.githubusercontent.com/assets/1696495/12689861/4f7c22e8-c694-11e5-961f-19cfd57f2786.png">

2. State abbreviation repeated in multiple places:
<img width="268" alt="screen shot 2016-01-29 at 2 27 01 pm" src="https://cloud.githubusercontent.com/assets/1696495/12689878/66c5cd1e-c694-11e5-856e-e030dfedb076.png">

I'm not sure what to do about this one, because when we have an event with multiple state values, we want to say "Multiple states" in the title and then list the individual states in the summary, but when it's just one state, it feels silly.

**Comment by emileighoutlaw** [comment]
Yeah— I think there's definitely room for content work on the calendar microcopy. I think I just need to get into the actual code and see what I can and can't fiddle with. I know Lindsay said there are some constraints.

**Comment by noahmanger** [comment]
Another thing: Is it just me, or would reporting deadline events benefit from being worded a little different. So instead of...
<img width="295" alt="screen shot 2016-01-29 at 2 30 09 pm" src="https://cloud.githubusercontent.com/assets/1696495/12689962/f1f0b296-c694-11e5-87fb-f32b4fcca43d.png">
...**"NH Presidential Pre-Primary Report Due"**

**Comment by LindsayYoung** [comment]
Just talked to @emileighoutlaw 
 - adding "Due" to the description in 18F/openFEC/pull/1464
 - Let's just show the discription when you click on an event.

**Comment by emileighoutlaw** [comment]
Talking to Lindsay this morning was so helpful! Here are my takeaways:

1. Much of the calendar copy is being imported directly from FEC. Here's what that means:
    - Many of our content styling problems (`AM rather than a.m.`, inconsistent capitalizations), are being created by the Info Division person who enters the content into their system. 
    - If we want to make that information better, we need to go to the source (FEC input). 
    - The first step here is to actually capture the disparities between their current practice and our beta.fec.gov content style. I'm starting on that now.

2. We have a decent amount of control over the name and descriptions for elections and reports
    - What that means is, we can choose the order of the words. It's also possible (although not simple) to bolster descriptions.
    - As Lindsay mentioned in her comment, two small first steps we're making are (1) adding "due" to descriptions and (2) Only showing the description when you click on an event, rather than showing both the title and the description. The event description is usually nearly identical to the event title in terms of content. If anything, it includes a little more info, but never less. Making this trim will cut down on the amount of text folks have to read.

3. Lindsay's put a lot of great thought into the naming of calendar events. I'm going to keep looking at the fantastic work she's done so far and see what additional recommendations I can make.

**Comment by noahmanger** [comment]
Cool. That all makes sense to me. I have two questions on hiding the titles: 

1. Do we also want to hide them from the list view:

<img width="931" alt="screen shot 2016-02-02 at 4 22 22 pm" src="https://cloud.githubusercontent.com/assets/1696495/12769066/434dfb94-c9c9-11e5-9878-fe81b654cc96.png">

2. In some cases (such as AOs), the title is substantially shorter from the description, and it seems like it would hurt scanability to drop the title entirely:
<img width="1040" alt="screen shot 2016-02-02 at 4 24 17 pm" src="https://cloud.githubusercontent.com/assets/1696495/12769083/81b344a2-c9c9-11e5-8b46-acd488c7a51a.png">

**Comment by emileighoutlaw** [comment]
This is a great thought, Noah. My inclination is yes, we should hide them in list view.

@LindsayYoung — how heavy of a lift is it to add a couple custom pieces of text to descriptions? For example, on AO comment deadlines adding `Advisory Opinion deadline.` before the canned description we're pulling from FEC? 

I can take a look at all the events in list view and see if there are other things we want to add.

**Comment by LindsayYoung** [comment]
Nice thinking Emileigh! I could do that for all of the cal_events data, we should make sure it there is not a group of circumstances where it doesn't make sense.

**Comment by emileighoutlaw** [comment]
Spot on! I'll look at the data today.

**Comment by emileighoutlaw** [comment]
Just documenting our plan here— 

Lindsay and I looked at the data yesterday. AOs, court cases, and conferences are the three things that lose significant information when you drop the title and just keep the description. 

We documented the FEC codes for those three things. Our first solution was to add custom text to everything with an affected code. For example, things with the FEC code for AOs would get custom text along the lines of `Advisory Opinion deadline.` added to the front of the event.

Then we discovered that the FEC codes aren't unique. Which means the code for AOs is the same as the code for rules. So adding `Advisory Opinion deadline.` in front of every description with the AO code would also add it to rulings. So custom text doesn't seem like a feasible solution. 

In the end, we think the best solution is to do this— events with any of the three codes we identified as being problematic will get their event title added to the front of the description. 

I tried to explain this in the simplest way possible, but let me know if anyone has questions. I can answer!

**Comment by noahmanger** [comment]
Ok, so to summarize in terms of the code: if the category is one of: `[aos, litigation, conferences]` don't show their event title. 

What about: `roundtables`? And what about IE periods (`ie`)? 
![screen shot 2016-02-04 at 1 31 38 pm](https://cloud.githubusercontent.com/assets/1696495/12830404/00149474-cb44-11e5-8c49-21ca81c1d135.png)

**Comment by noahmanger** [comment]
Also, what do you think of showing their title, but not showing their description? That way, each item will always have a bold title.

**Comment by LindsayYoung** [comment]
@noahmanger I was going to change the discription on the API side. Should I not? I am happy to do one less calendar cleaning task. :)

**Comment by noahmanger** [comment]
Oh! API-side would definitely be preferred.

**Comment by emileighoutlaw** [comment]
And then the other piece of the question, I think the description for IE periods makes sense without the title (i.e., the title just feels repetitive.)

Looks like the calendar is down on Dev right now, so I can't see what the roundtable description looks like. Does it not look sufficient on its own, Noah?

**Comment by noahmanger** [comment]
My concern is more when it's in a list view. It's easier to read if there's a shorter bold title for each item.

**Comment by emileighoutlaw** [comment]
Yeah, it's definitely not an ideal solution. I still think it's our best option, since we can't actually alter the text, and I do think a majority of the items we'll have in the list are short descriptions (election dates and reporting deadlines). 

You're totally right that the paragraph description items will be harder scan, but I _think_ that's better than the long, repetitive list? 

And I definitely see this as a very temporary solution. I'm hoping we can get to the source at FEC and convince them to let us copyedit their calendar tables.

**Comment by noahmanger** [comment]
Sounds good!
