### ISSUE TITLE
Discussion: Null candidate IDs in Schedule E

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1478]
Several thousand rows in `sched_e` have `null` values for `s_o_cand_id`, meaning that we can't unambiguously link to the relevant candidate for those records. I'm not sure whether filers add candidate IDs in this case, or whether those are imputed by FEC. Is it possible for FEC to add the missing IDs? Either way, we'll handle the possibility of `null` IDs on the data site for now.

Note: this issue is the cause of https://github.com/18F/openFEC-web-app/issues/1057.

cc @PaulClark2 @jwchumley

**Comment by jwchumley** [comment]
We'll look but missing IDs are fairly common. Sometimes it is an actual 
candidate and an ID should be there. Other times filers Include state 
candidates or use candidate names that we can't match up to actual 
candidates and those will always be null.

**Comment by noahmanger** [comment]
Potentially related problem: Certain records on the IE page for Hillary Clinton currently link to Bill Clinton: https://beta.fec.gov/data/independent-expenditures/?max_date=02-04-2016

But it's not all of them. You'll notice these link correctly: https://beta.fec.gov/data/independent-expenditures/?candidate_id=P00003392&max_date=02-04-2016

**Comment by LindsayYoung** [comment]
These are the ones linked to the wrong id https://beta.fec.gov/data/independent-expenditures/?candidate_id=P20000642&max_date=02-04-2016
