### ISSUE TITLE
Discussion: Mis-formatted dates in communication costs

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1479]
Transaction dates in the `communication_costs_vw` table are stored as integers, so that today's date is represented as 20,160,201 (2016-02-01). This isn't a good way to represent a date--this column should probably be a `timestamp`. We're handling these values on our side, but it should be straightforward to fix them on the FEC side. Would it be possible to make this change? If so, we can revert our workaround.

cc @PaulClark2 @jwchumley

**Comment by jmcarp** [comment]
This has been fixed--much appreciated!

**Comment by PaulClark2** [comment]
you're welcome!
