### ISSUE TITLE
Missing coverage start date on some reports

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1488]
A small number (about 1000 out of 425,000) of non-termination congressional reports don't have coverage start dates. Currently, this means we throw a 500 on certain committee pages, like /committee/C00100586/, since the date formatting on our chart tick marks expects valid start and end dates. If these missing dates are expected, then we should accommodate them on the client side. If they're data errors that can be fixed (which I'm guessing they're not), then we shouldn't have to change our code.

Here's an example of a report without a start date. It's rendering here because I modified the code locally to figure out what's going on--but this page currently crashes in production. The middle report doesn't have a start date.

<img width="610" alt="screen shot 2016-02-05 at 12 47 41 pm" src="https://cloud.githubusercontent.com/assets/1633460/12854338/314644fc-cc07-11e5-99be-65278b9a28fc.png">

Assuming this isn't something we can fix on the data side, we could hide the missing date so that the tick mark just shows "04/29/82", or indicate that we don't have the date, as in "? - 04/29/82", or hide that report altogether.

cc @noahmanger @LindsayYoung @PaulClark2

**Comment by noahmanger** [comment]
Tricky. Let's see if we can solve with a data fix, but if not, we can talk about front-end adjustments. Thanks for catching.

**Comment by PaulClark2** [comment]
Generally, we will not be able to "fix" these because they were reported without a coverage start date.  The only time we populate a missing coverage date is when the the report is filed on paper and the coverage end date is missing.  We use the receipt date as the coverage end date.  See for example:  http://docquery.fec.gov/pdf/790/15031411790/15031411790.pdf

**Comment by jmcarp** [comment]
In the interest of getting this fixed quickly, since this is throwing occasional 500s in production, I submitted a quick patch at https://github.com/18F/openFEC-web-app/issues/1096.
