### ISSUE TITLE
Test new Typeahead

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1491]
- [ ] Ping @jmcarp on Wednesday to make sure the dev site is set up

**Comment by noahmanger** [comment]
We're going to need to figure out a way to have both the new typeahead branch up as well as the EC/CC page branch up. The FEC needs to review the latter, but we want to do usability testing on the former. It's too late to get this in for testing Thursday of this week, and if we're focused on reviewing the new pages for release, maybe this just needs to wait until those are deployed to production?

**Comment by brethauer** [comment]
@noahmanger 
Waiting until those are deployed sounds fine to me, unless the typeahead is important, or if you anticipate potential issues with it that will require reworking.

**Comment by noahmanger** [comment]
Testing complete.
