### ISSUE TITLE
Hide titles on calendar events

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1493]

**Comment by noahmanger** [comment]
Ok, here's how this shows up:

![screen shot 2016-02-05 at 2 00 12 pm](https://cloud.githubusercontent.com/assets/1696495/12860381/035deb9e-cc11-11e5-809d-8cfec7df64a2.png)
![screen shot 2016-02-05 at 2 00 03 pm](https://cloud.githubusercontent.com/assets/1696495/12860383/0361905a-cc11-11e5-9b9a-ac7987c52669.png)
![screen shot 2016-02-05 at 1 59 59 pm](https://cloud.githubusercontent.com/assets/1696495/12860382/035fad6c-cc11-11e5-94e4-c20616b9e2e6.png)

Change is in https://github.com/jmcarp/fec-cms/pull/4

**Comment by emileighoutlaw** [comment]
This looks much better to me! Thanks, Noah.

**Comment by noahmanger** [comment]
Implemented in the calendar branch.
