### ISSUE TITLE
Implement details panels for the office pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1496]

**Comment by noahmanger** [comment]
Resolved this in the meeting with FEC today. Next step is to implement.

**Comment by noahmanger** [comment]
Ok, pulling this info out of the master spreadsheet, these are the fields we want:

## All candidates + all office pages
Label | Value   
|---|----|
Candidate name | Name + link   
Election years | All years where filed to run; Link to election pages    
Office sought | Full office name    
Political party | Full party name   
State (if applicable) | Full state name   
District (if applicable) | Distrinct number    
First filing | First form 2 link + date    
Most recent filing | Most recent form 2 link + date    

## Additional fields for office pages
Label | Value   
|---|----|
Principal committee | Committee names + links (for current time period)
Authorized committees | Committee names + links (for current time period)
Total receipts | Total from authorized committees
Total disbursements | Total from authorized committees
Total debt | Total from authorized committees
Total ending cash on hand | Total from authorized committees

## Just for presidential
Label | Value   
|---|----|
Total federal funds accepted | Total from authorized committees

Of those, I believe that Total Federal Funds is the only one we need added to the new candidate financials endpoint (Issue: https://github.com/18F/openFEC/issues/1476)

Several others are available, but just at different endpoints (like first and last form 2s, authorized committees). So my question is do we want to add those to the existing main endpoint for each datatable, or set up the modal to work like we do for filings and make a separate API call for each row upon opening?

**Comment by LindsayYoung** [comment]
Wanted to clarify, (Issue: #1476) just asks for a boolean, so the value would not be Total from authorized committees it would be true or false and it would just be a filter. 

It makes sense to me to creatw "accepts federal funds" as a flag to filter on. Federal funds are part of total receipts, so I don't think it is necessary to list the value there. Also, I am thinking that the amount is not that interesting and it is rarely used anymore, so we might not want it taking up vertical space.

**Comment by noahmanger** [comment]
Works for me. I think we should still keep it as a row, but just show the boolean value. There's not too many items in here. Thanks for clarifying.

**Comment by noahmanger** [comment]
My second question above still stand: 
> Several others are available, but just at different endpoints (like first and last form 2s, authorized committees). So my question is do we want to add those to the existing main endpoint for each datatable, or set up the modal to work like we do for filings and make a separate API call for each row upon opening?

**Comment by noahmanger** [comment]
Bump. @jmcarp or @LindsayYoung ?

**Comment by LindsayYoung** [comment]
I started looking into this Yesterday. What we want is kind of circular when you look at the current import flow so I needed to think of what the least messy implementing. Also, thanks @ccostino for providing a sanity check on this. Starting the code for this now

**Comment by noahmanger** [comment]
Synced up on this and the preferred action for now is:

If the data exists at a single other endpoint, make the separate call on opening the details panel. And then down the road if we want we can optimize by including more details in the main endpoint. 

Transferring to @jmcarp for implementation if you have time, but anyone else who has time to get to this should feel free (myself included).

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1211
