### ISSUE TITLE
Discussion: Null rows in sched_b

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1503]
I noticed some rows in `sched_b` that seem to be missing most columns--I'm wondering if they should exist at all. For example, image 11020160718 includes three disbursements. But querying `sched_b` for that image number yields six results, three of which seem to be empty:

```
fec=> select sched_b_sk, cmte_id, recipient_nm, disb_dt, disb_amt from ofec_sched_b where image_num = '11020160718';
 sched_b_sk |  cmte_id  |         recipient_nm         |  disb_dt   | disb_amt
------------+-----------+------------------------------+------------+----------
   63047864 | C00193342 |                              |            |     0.00
   63047884 | C00193342 |                              |            |     0.00
   63047817 | C00193342 |                              |            |     0.00
   40952336 | C00193342 | DIRECT MAIL PROCESSORS, INC. | 2011-03-10 |   797.00
   40952335 | C00193342 | BON VIVANT CATERING          | 2011-03-10 |  1650.00
   40952334 | C00193342 | HUCKABY DAVIS LISKER INC.    | 2011-03-10 |  4065.00
(6 rows)
```

The last three results match up with the image at http://docquery.fec.gov/cgi-bin/fecimg/?11020160718. The first three results don't, and are missing columns that almost all rows in this table include. Should we include rows like this in our results?

@PaulClark2 @LindsayYoung @noahmanger

**Comment by PaulClark2** [comment]
@jmcarp One of are processing tables, all_entries, indicates these rows should have been deleted.  I'm not sure why the deletions didn't process correctly.  I've set them to delete during tonight's update process.   

Did you see this a bigger problem or was it limited to just this set?

**Comment by jmcarp** [comment]
@PaulClark2: based on a cursory look at the data, it looks like there's still a small number of itemized disbursements that may have been entered incorrectly. For example, there's about 130 items with a `null` disbursement date and an amount of $0.00. When I cross-referenced with the original filings, some of these were actually blank, but other items actually have dates and amounts in PDFs that aren't reflected in `sched_b`. These may just be OCR errors, since the examples I saw were all paper filings.
