### ISSUE TITLE
Format report due date decriptions

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1508]
In the API we should reformat the report descriptions to be more readable. 

**Current:**
<img width="281" alt="screen shot 2016-02-11 at 3 55 44 pm" src="https://cloud.githubusercontent.com/assets/1696495/12994806/fca8d3c4-d0d7-11e5-91cf-18710252a16b.png">

**Proposed:**
March monthly report due. Report code: M3

@emileighoutlaw what do you think of that change?

**Comment by emileighoutlaw** [comment]
I think it's a great change, but is it possible the way the data is set up, @LindsayYoung?

**Comment by LindsayYoung** [comment]
Yes, I can do this
