### ISSUE TITLE
Explicitly track dependencies between data views

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1515]
Some of our data views are built directly from the raw FEC tables, but others depend on a chain of our own views. For example, the candidate full-text search view (ofec_candidate_fulltext_mv) depends on the candidate detail view (ofec_candidate_detail_mv). If the views are created in the wrong order, the process will crash. If the views are updated in the wrong order, some views may be stale.

At the moment, we're using the very brittle approach of running sql files in alphabetical order by file name. Instead, I propose that we explicitly declare dependencies between data import and refresh steps and ensure that all steps run in an appropriate order. Airbnb's airflow library is designed to solve exactly this kind of problem and might be a good candidate--or if that's overkill, we can build a directed graph of view dependencies and run steps in topologically sorted order.

**Comment by noahmanger** [comment]
Resolved by #1610
