### ISSUE TITLE
Add "Transaction type" to Communication Costs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1524]
Request from Paul: Add transaction type to the Communication Cost download. 

Is this already in the API? And should we also include this in the detail panel?

**Comment by jmcarp** [comment]
Submitted API revisions the other day at https://github.com/18F/openFEC/pull/1518. Let me know if you want me to make a change on -web-app, or send in a patch, and I'll merge it after the API is updated.

**Comment by noahmanger** [comment]
Yeah, can you make the web-app change?
