### ISSUE TITLE
Communicate API change

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1525]
After https://github.com/18F/openFEC/pull/1504, we have an API change that should be communicated to the public. Assigning to Lindsay to figure out the best way to do this.

**Comment by jmcarp** [comment]
Might be worth taking a minute to check how many users have actually touched this endpoint.

**Comment by noahmanger** [comment]
+1. I'd love to see how to do that if anyone can show me.

**Comment by LindsayYoung** [comment]
Sounds like we are not planning on additional changes and this won't effect users. I am just going to close.
