### ISSUE TITLE
Broken link to candidate from committee page

### ISSUE THREAD

**Issue by edmullen** [18F/openFEC#1536]
On the live beta site, when looking at [a committee page](https://beta.fec.gov/data/committee/C00272161/), the [related candidate](https://beta.fec.gov/data/candidate/P20000642/?cycle=2000) link produces an error. 

The reason is that the search is asking for a cycle variable and there are no corresponding _candidate_ info for that cycle.

![image](https://cloud.githubusercontent.com/assets/2654503/13293213/c9407a2c-daec-11e5-865f-46b452b583d1.png)

https://beta.fec.gov/data/candidate/P20000642**/?cycle=2000**

![image](https://cloud.githubusercontent.com/assets/2654503/13293318/320a894e-daed-11e5-882b-6a9ec5ef2b5a.png)

[Removing the cycle variable works](https://beta.fec.gov/data/candidate/P20000642) and seems like what the user would want.

![image](https://cloud.githubusercontent.com/assets/2654503/13293290/10b731c0-daed-11e5-97dd-ec58dfbe9e33.png)

## To complete

[ ] Remove cycle variable from link to related candidate on the committee page

**Comment by noahmanger** [comment]
Ah! Thanks for catching this. I'm surprised nobody caught this sooner as it seems like a common scenario where the committee has activity for a cycle or two after the candidate last ran. 

@jmcarp and @LindsayYoung what do you think of just dropping the cycle param from this link? Any downside? Or is there a smarter way?

**Comment by jmcarp** [comment]
We handle this correctly in the other direction, linking from candidate pages to related committees, like so: https://github.com/18F/openFEC-web-app/blob/develop/openfecwebapp/views.py#L81-L87. We can either update the committee links to use similar logic or opt not to pass cycle through across these links in either case.

**Comment by noahmanger** [comment]
Cool. If it's simple enough to replicate the logic in the other direction, I think we should do it that way. I think it's helpful to be taken to the same point in time you were looking at.
