### ISSUE TITLE
Coming soon link for calendar should be removed

### ISSUE THREAD

**Issue by edmullen** [18F/openFEC#1540]
At the bottom of [Registration & Reporting page](https://beta.fec.gov/registration-and-reporting/) there is a disabled promo for the Reporting Calendar, which I believe is the same as the the new calendar filtered for Reporting Deadlines.

![image](https://cloud.githubusercontent.com/assets/2654503/13301860/07c6e380-db15-11e5-9794-7c7018bdf008.png)

Seems the link with the right filters set should be: https://beta.fec.gov/calendar/?category=EC+Periods&category=IE+Periods&category=report-E&category=report-M&category=report-Q

**Comment by noahmanger** [comment]
Thanks, Ed! Jen also just caught this. I just addressed it in a pull request, but closing this in favor of the first issue: https://github.com/18F/fec-cms/issues/217
