### ISSUE TITLE
QA new typeahead

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1547]
As discussed, we're just about ready to deploy the new typeahead filters, sans design refinements (which will come later). So the remaining tasks to do is to review that everything looks and works correctly.

When reviewing, verify the following actions work:
  - Committee ID lookup
  - Candidate ID lookup 
  - Candidate name search
  - Committee name search
  - Candidate typeahead selection
  - Committee typeahead selection

Here's the places to check:
- [x] Verify language main search + header searches work as expected
- [x] Verify searches on error and search results work as expected
- [x] Verify the correct filter is on the each page and the correct language is used (Noah + @emileighoutlaw ): 
  - [x] https://fec-proxy.18f.gov/data/candidates
  - [x] https://fec-proxy.18f.gov/data/committees
  - [x] https://fec-proxy.18f.gov/data/receipts
  - [x] https://fec-proxy.18f.gov/data/disbursements
  - [x] https://fec-proxy.18f.gov/data/filings
  - [x] https://fec-proxy.18f.gov/data/independent-expenditures
  - [x] https://fec-proxy.18f.gov/data/electioneering-communications
  - [x] https://fec-proxy.18f.gov/data/communication-costs

Am I missing anything?

**Comment by noahmanger** [comment]
PR coming with slight language tweaks based on convo with @jenniferthibault and @emileighoutlaw . Only functionality issue I found is on the disbursements page: 

`recipient_name` field doesn't seem to accept a committee ID: https://fec-proxy.18f.gov/data/disbursements/?recipient_name=C00575795&max_date=03-03-2016

**Comment by noahmanger** [comment]
Assigning to @jmcarp to figure out the above issue.

**Comment by jmcarp** [comment]
@noahmanger: I rebuilt the disbursements table on dev. Want to check again?

**Comment by noahmanger** [comment]
Works for me!
