### ISSUE TITLE
Forms and schedules

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#1551]
Some schedules have "form" in their names but are schedules.   I've listed them in the schedule section.  

| Forms | 18F | Source | Table name |
| --- | --- | --- | --- |
| Form 1 | N |  |  |
| Form 1Z (internal entry only) | N |  |  |
| Form 1S (supplement to Form 1) | N |  |  |
| Form 1M | N |  |  |
| Form 2 | N |  |  |
| Form 2Z (internal entry only) | N |  |  |
| Form 2S (supplement to Form 2) | N |  |  |
| Form 3 | Y | DW | facthousesenate_f3 |
| Form 3S (post-general summary pages electronic) | N |  |  |
| Form 3Z | N |  |  |
| Form 3P | Y | DW | factpresidential_f3p |
| Form 3PS (post-general summary pages electronic) | N |  |  |
| Form 3P31 (list of items to be liquidated – empty table on FECP) | N |  |  |
| Form 3X | Y | DW | factpacsandparties_f3x |
| Form 3L | N |  |  |
| Form 4 | N |  |  |
| Form 5 | Y | DW | factindpexpcontb_f5 / form_5 |
| Form 6 | N |  |  |
| Form 7 | Y | DW |  |
| Form 8 (no longer filed electronically) | N |  |  |
| Form 9 | Y | DW | form_9 |
| Form 10 (no longer used) | N |  |  |
| Form 11 (no longer used) | N |  |  |
| Form 12 (no longer used) | N |  |  |
| Form 13 | N |  |  |
| Form 99 | N |  |  |
| Form 24 | N |  |  |

| Schedules | 18F | Source | Table name |
| --- | --- | --- | --- |
| Schedule A | Y | DW | sched_a |
| Schedule B | Y | DW | sched_b |
| Schedule C | N |  |  |
| Schedule C1 | N |  |  |
| Schedule C2 | N |  |  |
| Schedule D | N |  |  |
| Schedule E | Y | DW | sched_e |
| Schedule F | N |  |  |
| Schedule H1 | N |  |  |
| Schedule H2 | N |  |  |
| Schedule H3 | N |  |  |
| Schedule H4 | N |  |  |
| Schedule H5 | N |  |  |
| Schedule H6 | N |  |  |
| Schedule I (no longer used) | N |  |  |
| Schedule L | N |  |  |
| Form 56 | N |  |  |
| Form 57 | Y | DW | form_57 |
| Form 65 | N |  |  |
| Form 76 | Y | DW | form_76 |
| Form 82 | N |  |  |
| Form 83 | N |  |  |
| Form 91 | Y | DW | form_91 |
| Form 94 | Y | DW | form_94 |
| Form 105 (no longer used) | N |  |  |
| Text | N |  |  |

@noahmanger

**Comment by noahmanger** [comment]
Excellent. Thank you. Could you do me the favor of identifying which ones we currently have?

**Comment by PaulClark2** [comment]
I made the original post a table and added additional information.  There are other tables 18F has like dimcmteproperties, dimcmtetpdsgn, dimcmtebank, etc. that uses information from the Form 1 table but it isn't just a copy of the Form 1 table.
