### ISSUE TITLE
Documentation improvements for new users in the API repo

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#1559]
As I've been onboarded more with the FEC project and have gone through the paces of setting things up for myself, there are several improvements I'd like to make to the documentation with @emileighoutlaw's help.  Specifically, I'd like to focus on the following in order to make the project easier to setup and use by others:

* [ ] Improve the README by reorganizing some of the content and removing old/incorrect information.
* [ ] Move advanced/specific installation steps to a separate file, and link out to existing guides for Python environment setup in general for those that would like the additional information and help.
* [ ] Maintain a quick-start guide to get up and running quickly.
* [ ] Add some missing steps required to get the app running and tested (e.g., several other environment variables and creating the `cfdm_unit_test` database before running tests).
* [ ] Update references to all FEC-related repos and other 18F repos utilized by the project.
* [ ] Add correct SSH details for Cloud Foundry (`cf create-app-manifest my-app ssh-manifest.yml` and 
`cf-ssh -f ssh-manifest.yml`).

Please see #1557 for a bit of extra information.

**Comment by emileighoutlaw** [comment]
Cool! Excited to start in on this with you!

**Comment by emileighoutlaw** [comment]
Also: Add description to glossary repo https://github.com/18F/glossary

**Comment by ccostino** [comment]
Thanks, @emileighoutlaw!  I added a task to capture that work. :-)

**Comment by noahmanger** [comment]
Sounds like this would be a good thing to do sooner rather than later while it's still fresh in your brain, but do we want to include it in this sprint?

**Comment by ccostino** [comment]
I'd definitely like to get this done sooner rather than later for exactly that reason. :-)

@emileighoutlaw, do you think you might have time to sit down with me later this week or early next week to review this?  If so, then I think it's doable for this sprint.

**Comment by emileighoutlaw** [comment]
Yes, definitely! Will I see you in the office tomorrow (Thursday)? If so, let's chat then!

**Comment by ccostino** [comment]
@emileighoutlaw:  Yup, I'll be there tomorrow and Friday this week, so ample time to catch up about this and review!  Calendar invite sent for tomorrow morning for a review and pairing session. :-)

**Comment by noahmanger** [comment]
Closed by #1577
