### ISSUE TITLE
As a frequent checker of candidate and committee filing, I'd like the ability to subscribe to updates to candidate/committees pages, so that I can stay current with the most recent changes as soon as they happen.

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#156]
Users have indicated they want ability to subscribe to updates to candidate/committees. May be a good place for those pages on openFEC.

**Comment by jmcarp** [comment]
Let's revisit this post-release. @leahbannon should we take this out of the backlog?

**Comment by leahbannon** [comment]
Yes, good call. This was in a backlog milestone, though, and we're no longer using milestones (using labels instead). I've cleaned up and removed the milestones. :+1:

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/0dY0U5bDOAwOVznT3Laojg
