### ISSUE TITLE
Sanders DC totals don't match totals on fec.gov presidential map

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1561]
I think this came from the beta feedback system. The pres map only has about $212,000 for Sanders from DC. The beta site has over $10,000,000. The problem is Sanders is reporting a single transaction for UNITEMIZED TOTAL contributions and has it listed as being from DC.  This isn't uncommon. Most places where it would cause a problem we filter out contributions where the upper contributor name contains "UNITEM". 

HIllary does this too. Others may as well.

**Comment by PaulClark2** [comment]
Just checking in on this one.  @LindsayYoung @ccostino

**Comment by LindsayYoung** [comment]
So the logic for this is [here](https://github.com/18F/openFEC/blob/develop/data/sql_incremental_aggregates/prepare_schedule_a_aggregate_state.sql#L13), I want to confirm we won't need this kind of additional filtering elsewhere.

Also, it seems so odd to me that people would file a location for unitemized donations, but here we are.

**Comment by jwchumley** [comment]
It is left over from prior to 2011 when the 3P had no unitemized line. That is how they used to file their unitemized amount. They shouldn't do it any longer but you should still filter out rows that have "UNITEM" in the name.

**Comment by LindsayYoung** [comment]
Thanks for the background, that makes sense as to why. 

Do you think we need to add this logic to any other filters so we don't double count? This ticket only mentions the by state subtotals, but do we need to look at the other subtotals- occupation, employer, candidate etc.? 

I want to confirm wether we want to add this to the broader [individual logic](https://github.com/18F/openFEC/blob/develop/data/functions/individual.sql) so we don't over count those other categories too.

**Comment by jwchumley** [comment]
IT is still a problem but I think I see another. If you click through to the dc transactions and sort by amount large to small you see two unitemized transactions but click through and look at the images of the two transactions and both are from NEW reports. Both reports have been amended so the amended transactions should have replaced the New transactions. Is this a data feed issue?

**Comment by LindsayYoung** [comment]
That is extremely important and let's move that discussion to #1716
