### ISSUE TITLE
Real Time Electronic Filing Tables

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1583]
Once the real time efiling inserts are available to you you will hit a snag. Well at least a choke point. Most of the tables make sense and pretty much mirror the fecp.disclosure tables. Here are some differences:

First, the repid (file_num) is the PK in all tables.

REAL_EFILE.REPS. - This table contains some basic data and metadata about a report.  
For example: Form type, Committee ID, Committee Name, Filed date, Coverage dates and image numbers

Form tables (F3, F3x F5 etc.)

The form tables only include data elements from page one of the report and in most cases don't include financial data. Form 3P is an exception and the first page of financial summary data is included in the F3P table. Other forms such as F5 that actually have financial activity reported on page 1 include those numbers in their Form table (real_efile.F5 for ex.)

Where are the rest of the numbers?

REAL_EFILE.SUMMARY:
In this table, instead of having a row of financial figures that corresponds to a row in the form table, there is a row for each financial data element so for example, a form 3 has 39 rows in the SUMMARY table.
This wouldn't be too bad except that each row is only identified by it's order. 1-39 (more or less for other forms) and there is no text descriptor to identify which element the row contains. Form 3 isn't too bad because the summary pages have not changed since the Oracle tables were created. Other forms like 3X and 3P have been updated so the elements can be out of order and they don't match the column order in the FEC.DISCLOSURE form tables where new elements are added to the end of the row.

Form 3P is especially confusing because unlike Forms 3 and 3X it includes the first page of summary figures in the real_efile.F3P row and begins the summary table with the second (detailed) summary page.

I've started a spreadsheet that maps the real_efile.summary (and real_efile.F?) table to the corresponding FECP.DISCLOSURE tables and to the numbering on the forms themselves. 

https://docs.google.com/spreadsheets/d/1UuI-Z36U7f5DdBMO2I5F43Cs_wdyvmhtzjdjk9wh_2o/edit#gid=0

I have 3, 3X and 3P and will be adding the other forms.

Schedules are more straight forward and don't have any weirdness.

@LindsayYoung @PaulClark2 @wluoFEC @ccostino

**Comment by LindsayYoung** [comment]
The REAL_EFILE.SUMMARY sounds like it will be hard to work with. Is there a way it could be formatted as it is pushed to us? 

If you don't think you can make it work, we can try re-formatting on our side. (Maybe we can use a [crosstab function](http://www.postgresql.org/docs/9.4/static/tablefunc.html) to pivot the table?)  But I am guessing you all will have a better handle on the format, since you are used to it. 

We can talk about it more later, to see if there are any faster or easier ways to make the data more approachable to maintain and for data users. 

Thanks again, I know this task already entails moving a mountain at breakneck speed.

**Comment by jwchumley** [comment]
I don't know. The routine that Salient is modifying to do the inserts is 
designed to replicate table for table and not manipulate the data or 
change structures.  Could you just create a view for the F3, F3x, F3p and 
f4 tables that includes the pivoted summary table values?

Or something?

**Comment by noahmanger** [comment]
Closing this since we got it working.
