### ISSUE TITLE
Make sure Upload data and Received date are both searchable and sortable from the API

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#159]
Once we get better date data, we want to make sure this is implemented.

**Comment by LindsayYoung** [comment]
This needs load_date to be accurate.

**Comment by fedex1** [comment]
# Related statements and questions are: 
(this is related to the https://api.open.fec.gov/v1/schedules/schedule_a endpoint)

* What is the flow of the "electronic records"?
* I see the most recent `load_date` is `2015-09-23 00:19:37` and  the corresponding `receipt_date` is 
`2015-09-21`
* Does this mean that the current API data is a month old (even for electronic filings)?
* I was hoping that the openfec api would give us real time access to the filings
* Is that not one of the purposes of an API?
* If the API data is, in face, a month old, then is there a plan to make it real time?
* One option to make the data SQL accessible would be the stream the data to a bigquery public table. see https://cloud.google.com/bigquery/streaming-data-into-bigquery  I can volunteer to work on this (if you agree)
 
# Related details:

This link https://github.com/18F/FEC/issues/14 describes "paper records" but I was hoping that electronic records are loaded in real time.

I loaded all the https://api.open.fec.gov/v1/schedules/schedule_a data sorted in descending order by `contribution_receipt_date`  (this seems to be the only sort option that contains a date) in bigquery See https://bigquery.cloud.google.com/table/personal-real-estate:usa.OPENFEC_schedule_a (requires a google account and project, but the data is all there and available for SQL queries)

See https://github.com/18F/openFEC/blob/develop/webservices/resources/sched_a.py
```
@use_kwargs(
        args.make_sort_args(
            validator=args.OptionValidator([
                'contribution_receipt_date',
                'contribution_receipt_amount',
                'contributor_aggregate_ytd',
            ]),
```

But I see this:

```

bq query "select contribution_receipt_date, load_date, receipt_date, pdf_url from [personal-real-estate:usa.OPENFEC_schedule_a] order by 2 desc limit 100"
Waiting on bqjob_r7c5f6883fa2cf5af_00000150a0ac905f_1 ... (0s) Current status: DONE    
+---------------------------+---------------------+--------------+------------------------------------------------------------+
| contribution_receipt_date |      load_date      | receipt_date |                          pdf_url                           |
+---------------------------+---------------------+--------------+------------------------------------------------------------+
| 2015-06-23                | 2015-09-23 00:19:37 | 2015-09-21   | http://docquery.fec.gov/cgi-bin/fecimg/?201509219002773514 |
| 2015-06-17                | 2015-09-23 00:19:37 | 2015-09-21   | http://docquery.fec.gov/cgi-bin/fecimg/?201509219002773826 |
| 2015-06-15                | 2015-09-23 00:19:37 | 2015-09-22   | http://docquery.fec.gov/cgi-bin/fecimg/?201509229002773984 |
| 2015-06-20                | 2015-09-23 00:19:37 | 2015-09-21   | http://docquery.fec.gov/cgi-bin/fecimg/?201509219002773708 |
| 2015-06-22                | 2015-09-23 00:19:37 | 2015-09-22   | http://docquery.fec.gov/cgi-bin/fecimg/?201509229002774015 |
| 2015-06-24                | 2015-09-23 00:19:37 | 2015-09-21   | http://docquery.fec.gov/cgi-bin/fecimg/?201509219002773543 |
| 2015-06-17                | 2015-09-23 00:19:37 | 2015-09-21   | http://docquery.fec.gov/cgi-bin/fecimg/?201509219002773560 |
| 2015-06-17                | 2015-09-23 00:19:37 | 2015-09-21   | http://docquery.fec.gov/cgi-bin/fecimg/?201509219002773358 |
| 2015-06-23                | 2015-09-23 00:19:37 | 2015-09-22   | http://docquery.fec.gov/cgi-bin/fecimg/?201509229002774009 |
| 2015-06-24                | 2015-09-23 00:19:37 | 2015-09-22   | http://docquery.fec.gov/cgi-bin/fecimg/?201509229002773995 |
| 2015-06-18                | 2015-09-23 00:19:37 | 2015-09-22   | http://docquery.fec.gov/cgi-bin/fecimg/?201509229002773958 |
| 2015-06-22                | 2015-09-23 00:19:37 | 2015-09-22   | http://docquery.fec.gov/cgi-bin/fecimg/?201509229002774043 |
| 2015-06-18                | 2015-09-23 00:19:37 | 2015-09-22   | http://docquery.fec.gov/cgi-bin/fecimg/?201509229002774034 |
```

**Comment by LindsayYoung** [comment]
The reports come in on the schedule of the filers. So if a committee files quarterly, All of the transactions from the last 3 months will come in on one form. The API is updated nightly.  E-filers seem to get into the API in a day or two. Paper filers have some key information keyed-in immediately, and the bulk of the filings is sent out for processing, that can take much longer to appear into the FEC data bases. Once they are in the FEC database, the information is updated nightly.

You want to look at the difference between the load_date and recipt_date to tell you the processing time. We are also looking into shifting when nightly processes run to further reduce lag in processing to get rid of 2-day delays.  In the future, we would like to refresh more frequently.

**Comment by fedex1** [comment]
Hi @LindsayYoung Thanks very much for the reply.

One question, I see the most recent `load_date` as `2015-09-23 00:19:37` for the schedule_a endpoint.

Is that correct?   And if not, how do I request the data sorted by most recently updated?  either `load_date`, `receipt_date`, `update_date` etc. etc.

Again thanks for this project, it is a great improvement over the previous data dump approach!

**Comment by LindsayYoung** [comment]
Thank you for taking your time to write out issues! We are always trying to improve. 

This endpoint is not sortable by load date or update_date, but I can see how that would be extremely useful. 

Glad you mentioned this so it was not overlooked. We will look into adding additional sorting options as we make improvements.
