### ISSUE TITLE
Update system diagram for the openFEC system

### ISSUE THREAD

**Issue by NoahKunin** [18F/openFEC#1591]
There's been a tremendous amount of progress on openFEC, so we need to draw an updated system diagram.

**Comment by LindsayYoung** [comment]
That makes sense, this project has really taken off. Thanks for making an issue. I have a few follow up questions.

- About when is the diagram needed by- 2 weeks ok
- Do you want one diagram for all of FEC, each project or one for each repo
- What do we do with the diagram once we make it- post it here, send it to you etc.

Thanks

**Comment by NoahKunin** [comment]
@LindsayYoung 

- I'd ask it be put in scope whenever your next sprint starts. I wouldn't crack a sprint to add this, there's not _that_ level of urgency. Once it is in a sprint, I would expect it to be done within 2 sprints. So in other words, I won't micro-manage the flow of the work, since there is no artificial external deadline at the moment. :) Just let me know when there's room for it to enter a sprint, and the deadline will emerge from that organically.

- Great question. I would like there to be a _singular_ file - but I would make it as big or as many  Ya'll are the experts on the system. Think about it this way - let's say everyone currently on the project had to go to Mars *tomorrow*. If you had to draw a new FEC team a picture of how the system works, would you draw one big diagram or (n) small ones

- You can put it where it makes sense to you! However, you just have to ensure the permalink gets into your SSP YAML file here: https://github.com/18F/openFEC/blob/develop/system-security-plan.yml#L53

If a singular diagram effectively represents its functional and networking state, you can use the same link for line 54 - again, depends upon the output of the bullet above.

**Comment by LindsayYoung** [comment]
Thanks @NoahKunin

**Comment by LindsayYoung** [comment]
List of things to diagram:

- 3 RDS instances with assess the internet so the FEC can push updates. Devs need access to Amazon so that they can scale up the instances in times of heavy traffic, like filing deadlines and schema updates. The team also responds to alerts as necessary. These are not hosted on cloud.gov
- The API needs S3 access to the fec bucket to create downloadable csv resources. Those resources expire daily. 
- Celery worker to create and maintain download que and start nightly refresh
- Redis swarm is needed to store download que
- API needs access to api.data.gov, which is whitelisted from production (Prod only)
- Mandrill API access for email error messages from the update processes
- Slack access for the apps to post what branch is deployed where
- The Proxy app needs access to DNS and to route traffic for beta.fec.gov, which consists of the Web app and CMS
- The Web app and CMS need access to Github to post user feedback
- The CMS uses a postgres database in cloud.gov
- Testing and deploys from Travis on successful builds
- Error monitoring: NewRelic, Sentry
- FEC legal resources is working on adding an elasticsearch instance for legal documents

**Comment by noahmanger** [comment]
Thanks for the write-up @LindsayYoung . I'm going to throw this in next sprint and then find time for us to pair on it.

**Comment by LindsayYoung** [comment]
Sounds perfect

**Comment by noahmanger** [comment]
Sorry for the delay on this @NoahKunin but here's a first swipe at it with @LindsayYoung .

Here's our production set up at the moment:

![fec system diagram](https://cloud.githubusercontent.com/assets/1696495/15877863/6416f172-2ccb-11e6-86ae-d61a94fe846c.png)

And here's what we have on dev and staging (one for each):
![fec system diagram - dev](https://cloud.githubusercontent.com/assets/1696495/15877872/713b68e2-2ccb-11e6-9b13-b6f24f244b95.png)

Note the latter includes grayed-out nodes for the upcoming legal resources system. @anthonygarvan and @adborden , anything to add here? 

Let me know if this is along the lines of what you're looking for or if you want any clarification or refinements. Thanks for everything!

**Comment by adborden** [comment]
:+1: Those grey areas are correct.

**Comment by NoahKunin** [comment]
Great, thanks! What did you use to diagram it out? I might recommend the same to other teams.

**Comment by noahmanger** [comment]
Omnigraffle. I can share my file if it's helpful.

**Comment by NoahKunin** [comment]
Indeed, thanks!

**Comment by LindsayYoung** [comment]
Taking a second look, I noticed some minor things. 

The CMS has the same error reporting as the web app: 
    cms to Sentry 
    cms to New Relic

There should be an additional cf credential service. "FEC cred service (CMS)" should be pointing to the cms and the current on should jsut say "FEC cred Service" and that is shared with the API and the web app.

The direction of the arrow between the api and s3 should be reversed, and users access downloads directly from S3 as well. 

@noahmanger this looks great!

**Comment by noahmanger** [comment]
Thanks for the edits. Does this look right @LindsayYoung for production? 
![fec system diagram](https://cloud.githubusercontent.com/assets/1696495/15904288/395b3e44-2d65-11e6-9bcd-2548fee01767.png)

**Comment by LindsayYoung** [comment]
Looks right! Thanks again

**Comment by porta-antiporta** [comment]
@noahmanger May i get the omnigraffle file?  i'd like to update the diagram.  This is to satisfy a request from another [issue](https://github.com/18F/Infrastructure/issues/643) to help us understand what is needed to ship regulations on beta.

**Comment by NoahKunin** [comment]
[fec system diagram.graffle.zip](https://github.com/18F/openFEC/files/305750/fec.system.diagram.graffle.zip)

@porta-antiporta Was on this thread anyway, here you go!

**Comment by LindsayYoung** [comment]
The most up to date diagram is now:
https://github.com/18F/fec-eregs/issues/125#issuecomment-224979847

**Comment by porta-antiporta** [comment]
attached is the omnigraffle file for that diagram.
[fec system diagram updated.zip](https://github.com/18F/openFEC/files/307670/fec.system.diagram.updated.zip)

**Comment by noahmanger** [comment]
Sounds like everyone has what they need, so closing this.

**Comment by LindsayYoung** [comment]
![fec-system-diagram](https://cloud.githubusercontent.com/assets/4406333/24611526/6bdcde5a-1850-11e7-9644-d3bae407e1d7.png)

**Comment by LindsayYoung** [comment]
![fec_system_diagram 2](https://cloud.githubusercontent.com/assets/4406333/25457069/f7ed4a88-2aa2-11e7-9fab-f3d0e082304b.png)

**Comment by LindsayYoung** [comment]
![system diaram 08 2f31 2f18](https://user-images.githubusercontent.com/4406333/29945583-acae007c-8e6f-11e7-9c71-08584d509feb.jpg)

**Comment by LindsayYoung** [comment]
![system diaram 01 2f18 2f18](https://user-images.githubusercontent.com/4406333/35114972-92b155c2-fc54-11e7-923a-3da51d3c7
adding more detail to RDS
