### ISSUE TITLE
Test typeahead filter in usability testing

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1594]

**Comment by onezerojeremy** [comment]
We found that while some folks got it, some folks struggled with a couple pieces of it. 
1. where to click to invoke the search term.  As is shown here, the user attempted to search for a pac by name, but didn't know they had to click below (or seem to notice the list below at all) and instead clicked on the search box's text in the idea that would trigger the search. 
![problems with type-ahead](https://cloud.githubusercontent.com/assets/474916/14750078/f02abb26-0890-11e6-93cc-e89ee56e2828.gif)
2. folks also seemed to have a different concept of what it meant for there to be multiple filters present. 
![mult names progressive](https://cloud.githubusercontent.com/assets/474916/14751023/df5076ec-0895-11e6-8ef7-359a84e5cb34.gif)

**Comment by onezerojeremy** [comment]
Testing it again on Thursday 5/12 revealed:

##Autocomplete triggering
 that the changes made to the autocomplete seemed to improve comprehension:
- added the ability to tab through results
- added the ability to hit enter to trigger the search
- added the ability to hit the search button to trigger the search
- added a color indicator of the search you would trigger upon hitting enter
- added the hint "searching for" to the contextual menu for free text search

design work still recommended:
- the dropdown indicator was not universally understood as a way to find an item by searching through a closed list of items, consider a new icon that is neither the magnifying glass search icon or the drop down list icon (though if choosing between the two, it seems the magnifying search indicator was a better trigger). 
- in contributor information, received from, have both "individuals" and "committees" checked by default, as this is the behavior of the default search. 
- the two kinds of selection are subtly but importantly different; (one allows free text search, the other requires a selection from a closed list of committees)- right now, this is largely only hinted at by the "Searching for" in the contextual menu. Suggested tweak: give the "searching for term" equal billing with the committee selection. 
- if user deselects "committees" in the "received from", do not suggest committees in the "contributor name or id" contextual menu, and consider removing "or ID" from the prompt.

##For the issue with "AND" versus "OR": 
- making the filter panel sticky helped users notice it more
- some users still have a lot of trouble understanding that it is an "OR" search. 
- try adding "OR" language or revising the visual layout of the sidebar and filter panel to reinforce this. 
- Will test this week: a reverse query, going from specific to general (e.g., bill gates, to gates)
- users expressed a desire to get rid of unused filters. This is only a predilection, and did not get in the way of their use and therefore is not priority, but we may still want to consider it. 

We're getting closer, folks. 

tagging @noahmanger @jenniferthibault for visual and interaction tweaks. tagging @emileighoutlaw to consider microcopy changes in sidebar/filter panel.

**Comment by emileighoutlaw** [comment]
I'm not exactly sure how to do this in the code, but is there a way to add the word `or` after search terms? So searching would look like this:

> **Contributor name or ID**
> [ ] "smith" or
> [ ] "john" or
> [ ] "john smith"


?

**Comment by onezerojeremy** [comment]
I think it would help. 

might only want the "or" to appear if you add a second filter, but that's probably obvious, and to be styled somewhat differently than the search term itself.

**Comment by noahmanger** [comment]
Testing on the head is complete. Creating new issues for changes.
