### ISSUE TITLE
Inconsistencies between FEC web search form and API when searching by contributor name

### ISSUE THREAD

**Issue by orendog** [18F/openFEC#1597]
When I use the following search:

https://api.open.fec.gov/v1/schedules/schedule_a/?api_key= [………] &min_date=12%2F12%2F1999&sort_nulls_large=true&contributor_name=abdur%2C%20al%2C&per_page=100

I get back four records: 

'contribution_receipt_date': '2012-10-22',
'contributor_name': 'ABDUR-RAHMAN, ALIYAH',

'contribution_receipt_date': '2012-10-24',
'contributor_name': 'ABDUR-RAHMAN, ALIYAH',

'contribution_receipt_date': '2012-11-04',
'contributor_name': 'ABDUR-RAHMAN, ALIYAH',

'contribution_receipt_date': '2016-01-12',
'contributor_name': 'ALLAWALA, ABDURRAHMAN',

However, when I use the same search on OpenSecrets ("abdur* al*"), I get back over 50 records from Abdurahman Alamoudi, and none from the two names above. When I search for his full name using the FEC website (http://www.fec.gov/finance/disclosure/norindsea.shtml), the same records come up. Furthermore, when I search the FEC website for the two names above, there are no records for either.

It's as if the API and the website search form are hooked into two different, non-overlapping databases. Needless to say, I am quite alarmed, as this calls into question the coverage of all the data from either source.

**Comment by LindsayYoung** [comment]
The API uses postgres and searches with a tsvector field. The current transaction search uses string matching, which can lead to a narrower set of results. The current FEC site also treats first and last name differently, if you enter "AlAmoudi" into the last name box and "AbdulRahman" into the first name box you will get additional results.

The (beta.fec.gov)[https://beta.fec.gov/] site does use the FEC API, if that service is of interest to you. The current returns on the API and beta website for the transactional data begin in 2011, we are working on expanding that time period and adding custom downloads. 

OpenSecrets is run by the non-profit  Center for Responsive Politics. They consume the data from the FEC and do additional data and processing, so the results from the FEC API and Open Secrets will not necessary match.

Thanks for writing in. We are happy to answer any additional questions.

**Comment by PaulClark2** [comment]
Mr. Alamoudi's first name has been reported several ways over the years. 

ALAMOUDI, ABDUL RAHMAN
ALAMOUDI, ABDULRAHMAN
ALAMOUDI, ABDUR AHMAN
ALAMOUDI, ABDURABMAN MR
ALAMOUDI, ABDURAHMAN
ALAMOUDI, ABDURAHMAN M
ALAMOUDI, ABDURAHMAN M.
ALAMOUDI, ABDURAHMTOR
ALAMOUDI, ABDURAMAN
ALAMOUDI, ABDURDHMAN M
ALAMOUDI, ARDURAHMAN

**Comment by noahmanger** [comment]
Is any further action needed on this?

**Comment by PaulClark2** [comment]
No, we can close this issue.
