### ISSUE TITLE
Zipcode search wrong about MD 20754 district

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1599]
I searched for 2075. It says this zip includes multiple congressional districts with elections in 2016 but it doesn't. 20754 is entirely within House district 5. Not even close to the edge.

It seems to do this will all Maryland zips and displays a second house link with no district number.

**Comment by LindsayYoung** [comment]
We made our own mapping so we can change it. 

https://github.com/18F/openFEC/blob/develop/data/natl_zccd_delim.csv

**Comment by jwchumley** [comment]
Good. I only see one entry on the list for 20754 (Row 14386) and it is 
correctly listed in District 5.

**Comment by LindsayYoung** [comment]
OK there is a stray blank MD entry, I tried my old silver spring zip and I see it there too.

![screen shot 2016-04-05 at 9 59 19 am](https://cloud.githubusercontent.com/assets/4406333/14284359/3c196ca0-fb15-11e5-87e5-35f32d058cf2.png)

**Comment by jwchumley** [comment]
Looks like FL has the same issue.  I tried 34232 which is FL 16. It shows that but also another FL House with no district number. In and around Orlando where many zips cross district lines they show both correct districts and the Ghost unnumbered district. Try 32801.
