### ISSUE TITLE
NEXT DEPLOY 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1600]
Notes to track additional tasks for deploy

- Delete web-a and web-b so that we don't have 3 apps running

**Comment by noahmanger** [comment]
Do we want to pull in the new release checklist here? https://github.com/18F/openFEC-web-app/blob/develop/RELEASE_CHECKLIST.md

**Comment by ccostino** [comment]
For this next release (04-13-2016), I have the following things slated as needing to happen:

* Make sure local copies of `master, `develop`, and `release/public-beta-20160413` branches are up-to-date.
* Run `git flow release finish`
* Run `git push --tags`
* Delete the `web-a` and `web-b` apps.
* Test the site.

Am I missing anything?

**Comment by LindsayYoung** [comment]
LGTM :+1: 

Should we specify deleting the `web-a` and `web-b` apps after confirming the new `web` is up, for visibility. (You and l know this so maybe that detail isn't necessary.)

**Comment by ccostino** [comment]
Yes, thank you!

**Comment by noahmanger** [comment]
Do we want to roll this stuff into the checklist?

**Comment by ccostino** [comment]
Yes, I'd like to get the specific commands in there, in the right order, so I don't forget.  I did run into a couple of snags too that'd be good to review.

**Comment by noahmanger** [comment]
Ok, I added those commands to the release checklist, so I'm going to close this. https://github.com/18F/openFEC-web-app/pull/1169
