### ISSUE TITLE
Figure out what to do with these instructions and notes

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#1608]
This was pulled out of our README since it is not entirely correct anymore.  It'd good to figure out what is still useful and find a new home for it, be it back in the README or somewhere else.

---

_Note: The following instructions could be automated using Boto or the AWS CLI if we continue on with this model and need to update snapshots frequently._

The production and staging environments use RDS instances that receive streaming updates from the FEC database.  The development environment uses a separate RDS instance created from a snapshot of the production instance.

To update the development instance (e.g. when schemas change or new records are added):
- Create a new snapshot of the production data
  
  ```
  RDS :: Instances :: fec-goldengate-target :: Take DB Snapshot
  ```
- Restore the snapshot to a new development RDS
  
  ```
  RDS :: Snapshots :: <snapshot-name> :: Restore Snapshot
  ```
  - DB Instance Class: db.m3.medium
  - Multi-AZ Deployment: No
  - Storage Type: General Purpose
  - DB Instance Identifier: fec-goldengate-dev-YYYY-mm-dd
  - VPC: Not in VPC
- Add the new instance to the FEC security group
  
  ```
  RDS :: Instances :: <instance-name> :: Modify
  ```
  - Security Group: fec-open
  - Apply Immediately
- Configure DNS to point to new instance
  
  ```
  Route 53 :: Hosted Zones :: open.fec.gov :: goldengate-dev.open.fec.gov
  ```
  - Value: <instance-endpoint>
    - Example: fec-goldengate-dev-YYYY-mm-dd...rds.amazonaws.com
- Wait up to `TTL` seconds for DNS records to propagate
- Verify that new instance is reachable at goldengate-dev.open.fec.gov
- Delete previous development instance

**Important**: Verify that all newly created instances are tagged with the same client
as the production instance.

**Comment by LindsayYoung** [comment]
I don't think we should automate because we don't need this- the dev instance is not a snapshot anymore.  I do like the stuff about our security groupings to check. I agree it doesn't need to be in the readme. Can we move some of this to a wiki or somewhere? It would be nice to keep it for documenting infrastructure needs.

**Comment by ccostino** [comment]
Sure!  I am fine with whatever is easiest and if the dev instance is no longer a snapshot, then there's no point in keeping this as is.  We could pull out parts of it that are still useful to us and incorporate them back in the README or put them elsewhere.

**Comment by ccostino** [comment]
I updated the title and description to reflect this.
