### ISSUE TITLE
Get Carlo set up with Amazon alerts

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1617]
Set up alerts for:
- CPU
- Space
- Number of connections

**Comment by LindsayYoung** [comment]
and memory

**Comment by ccostino** [comment]
Okay, I should be setup with this now, but will confirm with @LindsayYoung tomorrow in the office.

**Comment by ccostino** [comment]
I realized that I need to setup CloudWatch alerts for these specific things.  I have RDS notifications setup for when things like database modifications and backups take place, but CloudWatch is what handles alerts regarding CPU utilization, space thresholds, connections, RAM usage, etc.

**Comment by ccostino** [comment]
Okay, now I'm set!
