### ISSUE TITLE
Detailed information and interaction design of fundraising overview

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1620]

**Comment by noahmanger** [comment]
Been a while since I shared out on this, so here's where I am at the end of the sprint. Feel free to comment [on InVision](https://gsa.invisionapp.com/d/main#/console/6587470/154949867/preview) or here.

## General thoughts
I shifted my thinking around the fundraising and spending overview pages thanks to helpful conversations with @onezerojeremy and @jenniferthibault . I think the point of these pages, rather than providing a comprehensive set of visualizations for all possible views into fundraising or spending data, should instead highlight specific *frequently sought* and *illustrative* views of the data. 

The point here is to hook users in and give them a slightly deeper level of understanding of what data is available and how it works, and then provide them paths for further exploration. So because these visualizations are not meant to be universal or exhaustive, it's ok to, say, showcase a set of data that's only relevant to a particular type of group.

## What's new:
- Each visualization comes pre-filtered with a set of smart defaults, but users can adjust them (in the title area above the charts). The options would be tailored so that only options that make sense would be available. And further, the defaults could change depending on the point in the cycle we're at (e.g. default to presidential candidates in a presidential year, senate in an off year). This also solves our "apples to oranges" problem that @LindsayYoung and @amykort brought up recently.
- I added "share" buttons throughout
- I simplified the chart for "who's raising the most"
- Added examples of callout boxes that can accompany figures which can be designed to a) explain a particular aspect of the rules (e.g. contribution limits) or b) provide a route to an alternate avenue of exploration.

## Feedback:
Looking to discuss these in more depth next week, but in the mean time feel free to log thoughts on either the interaction design or the data design. Keeping in mind that there's still more pages to come, **is the data included here right?** Or is it in any way misleading, inaccurate, or just plain not useful?

![2 1 1 - fundraising overview](https://cloud.githubusercontent.com/assets/1696495/14906680/0c2b76a8-0d73-11e6-9bf8-f92fb40cc53a.png)

**Comment by noahmanger** [comment]
Reviewed these with the partners today, and we're ready to move into visual design and prototyping. I will update the InVision versions to include the requested changes, and including notes here about what we're expecting for each set of numbers.

**Standard filters:**
- Candidate:
  - President (default)
  - Senate
  - House
- PACs:
  - Super PACs
  - SSFs
  - Non-connected
  - Leadership PACs
  - Hybrid PACs
- National party committees

## Totals
- We will generate the "total raised" number with the formula Paul sent a few weeks back. Because of double-counting, the other numbers will not add up to this total, but the total is the truest representation of the "total amount of money raised"
- We need to explain the methodology in an info tooltip

## Who's raising the most
- Based on total receipts for candidates and committees
- Need to include coverage dates, and coverage dates will change depending on the filing frequency of the group shown
- Candidate data is currently included in the API; committee data coming
- Standard filters, default to presidential candidates

## Where do contributions come from?
- Shows individual contributions, using the same logic we've used elsewhere for tracking earmarked contributions
- Data will be updated later than totals because of processing time for itemized contributions. Need to explain this alongside coverage dates
- Clicking dollar amount takes you to Individual Contribution page filtered down to that state
- Standard filters plus "All" (which is the default)

## How big are contributions
- Shows individual contributions
- Pre-define buckets for each type of actor based on their contribution limits
- X-axis scales based on actor
- Standard filters

**Comment by noahmanger** [comment]
Here's the latest version:
![2 1 1 - fundraising overview](https://cloud.githubusercontent.com/assets/1696495/15201262/d541dca0-17a3-11e6-989a-512b4bc79700.png)

**Comment by LindsayYoung** [comment]
Maybe this is out of date anyways, but I don't understand the "How big are contributions" graph
