### ISSUE TITLE
Replace proxy app with cf paths

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1621]
https://18f.slack.com/archives/cloud-gov-support/p1460509594001110

If we can mount applications at arbitrary paths using cloud foundry, then we can drop the separate proxy app at 18f/fec-proxy, which would simplify deployment and close off a point of failure (or at least move a point of failure from the application code into cloud.gov). It sounds like paths can't be specified in the manifest yet, but that feature should be getting built soon: https://github.com/cloudfoundry/cli/issues/748. Once the cf cli respects the `route-path` attribute in the manifest, we should be able to use this feature without otherwise messing with our deploy setup.

**Comment by jmcarp** [comment]
Thanks @dlapiduz for flagging this!

**Comment by adborden** [comment]
I was thinking this would be a one-time change and having it as part of the manifest would just be gravy on top. But then I got thinking, how would zero-downtime deployment handle this? IIRC, autopilot has to know about the routes of an app. In that case if it's not supported in the manifest, then we won't be able to use it.

**Comment by jmcarp** [comment]
Exactly--one of the design goals of autopilot is to store all application state in the manifest, and to carry over zero state from one deploy to the next. If we really wanted to drop the proxy application today, we could fork autopilot and add an option to specify route paths, or use a different zero-downtime deploy helper. But since this already seems to be in the queue at the cf cli team, and since we change the proxy application very rarely, I think it makes sense to wait.

**Comment by adborden** [comment]
I was hoping to expedite this to address https://github.com/18F/openFEC-web-app/issues/1193 but now I'm not sure.

**Comment by adborden** [comment]
Also want to point out https://github.com/18F/fec-eregs/pull/55 where we used `cf map-route --path` and the app-level changes needed to address how fec-proxy and `cf map-route --path` work differently.
