### ISSUE TITLE
Transform legal search response for UI

### ISSUE THREAD

**Issue by adborden** [18F/openFEC#1624]
The web app is currently doing a transform on the response from the legal search endpoint. Doing this kind of transform would make more sense on the API and avoid an extra scan on the web app.

Here's an example of how the web app is currently transforming the AO data: https://gist.github.com/adborden/7ee28c959cc5669ec69c1cb3ba95cfd1

Here's the code currently doing this:
https://github.com/18F/openFEC-web-app/blob/86ad0b05406697174e3bdf7252a6a4fa17b75271/openfecwebapp/api_caller.py#L47-L80

**Comment by adborden** [comment]
Oops, wrong gist, updated. Notice the empty "murs" and "regulations" keys.

**Comment by adborden** [comment]
So, my gist above does not account for getting the counts on a per-document-type basis. e.g. I don't have the total number of hits of AOs vs Regs vs MURs. I'll update it...

**Comment by adborden** [comment]
Gist updated.

**Comment by adborden** [comment]
I think this done, right @anthonygarvan ?

**Comment by noahmanger** [comment]
Can this be closed?

**Comment by adborden** [comment]
Yep, this was fixed.
