### ISSUE TITLE
Missing Candidate

### ISSUE THREAD

**Issue by gmj2053** [18F/openFEC#1632]
This is an odd situation.  I cannot find Adam Bell CANDIDATE in either the fec.gov or beta.fec.gov DB
I can find his committee in fec.gov
C00612796
ADAM BELL POLITICAL CAMPAIGN	ZONA, LOUIS WILIAM JR.	2016	ALLEN	TX	DEMOCRATIC PARTY	H - HOUSE 	P - PRINCIPAL CAMPAIGN COMMITTEE OF A CANDIDATE

But, I can't find his fec ID in fec.gov, but he does have one, which is why I think he doesn't show at all in beta.fec.gov
Our election team found it in 
Green Papers  http://www.thegreenpapers.com/G16/TX   
H6TX03192

**Comment by LindsayYoung** [comment]
I did some queries on the forms and I do see some reports for his committee, but I don't see a statement of candidacy for him. Maybe he filed by paper and it hasn't been processed yet? I will keep digging.

**Comment by gmj2053** [comment]
I guess I don't the process of assigning FEC Candidate IDs, this is his first race

**Comment by LindsayYoung** [comment]
Not all candidates have to file with FEC, they only have to file after raising or spending a certain amount. It doesn't look like a website issue so closing.

Thanks for writing in @gmj2053
