### ISSUE TITLE
Make partitioned schedule A and B tables work for downloads

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1636]
This is follow up work to be done after https://github.com/18F/openFEC/issues/1429 is merged.  The following things need to happen:

* Enable (whitelist) the Schedule A and Schedule B models in the download tasks.
* Coordinate with @noahmanger on https://github.com/18F/openFEC-web-app/pull/1242 for restricting downloads to 2 year cycles

**Comment by noahmanger** [comment]
Remaining criteria for completion:
- [ ] Expose new column on API
- [ ] Restrict queries to tables by default

**Comment by ccostino** [comment]
The work is done, now we're testing!

**Comment by noahmanger** [comment]
In order for testing to be considered done, we need to see that it is hitting the partitioned tables as expected for the election cycle that you choose.
