### ISSUE TITLE
Schedule A & B Partitioning:  Use unique persistent identifiers instead of idx

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#1638]
This work involves identifying the persistent unique identifier in a table (in other words, a column) that represents a unique record and won't be subject to changes or corruption if the data were to be reloaded/changed/wiped out/etc.  Once we identify this column, we'll want to update the primary key definition for our schedule a and b tables and reference it instead of the `sched_x_sk` column we're currently using, as well as use it for any indexes that make use of `sched_x_sk`.

For this sprint we'll focus on just schedule a and b data since we will need to do a refresh of these anyway, but going forward we'll want to

**Comment by noahmanger** [comment]
**Remaining task for completion:**
- [ ] Add to documentation
- [ ] If necessary, expose to the API itself

**Comment by ccostino** [comment]
For the record, the identifier is the `sched_a_sk` and sched_b_sk` columns in the data warehouse tables, but `sub_id` in the new tables for both schedules.

**Comment by ccostino** [comment]
This is going to roll in with the work @jontours is doing with the data warehouse table migrations: https://github.com/18F/openFEC/pull/1694

**Comment by ccostino** [comment]
New PR is here:  https://github.com/18F/openFEC/pull/1780

**Comment by noahmanger** [comment]
Resolved.
