### ISSUE TITLE
Schedule A & B Partitioning:  Make identifiers filterable

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#1639]
In addition to adding the new unique persistent identifiers, we want to make them filterable as well, e.g., making it so that you can pull up a record by its unique identifier (transaction_id = x).

**Comment by ccostino** [comment]
@LindsayYoung:  This would be a matter of adding an endpoint to both `/schedules/schedule_a` and `/schedules/schedule_b` to take a `sub_id` directly, correct?  E.g., `/schedules/schedule_a/{sub_id}`?

**Comment by jontours** [comment]
@LindsayYoung @ccostino if that's all needed I can get started on that, shouldn't be too bad.

**Comment by noahmanger** [comment]
- [ ] Add documentation about this change

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1816
