### ISSUE TITLE
Build assets on CI and drop buildpack-multi

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#1643]
The buildpack-multi buildpack is now [deprecated](https://github.com/ddollar/heroku-buildpack-multi#deprecated). It also swallows logs and generally makes debugging and support more difficult. To avoid depending on buildpack-multi, I think we should compile static files on Travis and not on cloud.gov. This is the approach we've been using on [eregs](https://github.com/eregs/notice-and-comment/blob/master/.travis.yml#L21-L24), and it's been working well so far. Unless anybody has reservations, I'll send in some patches.

Repos:
* [x] openfec
* [x] openfec-web-app
* [x] fec-cms

cc @LindsayYoung @ccostino @adborden @anthonygarvan

**Comment by ccostino** [comment]
Hey @jmcarp, yes!  I have been noticing those warnings and had wanted to tackle them soon after the last few major things we're currently working on were cleared off our plate.  I think we'd all greatly appreciate you and your team's insight from eregs with this and would be happy to review any patches (or even just notes) you're able to send along.

Thank you!

**Comment by LindsayYoung** [comment]
Thanks @jmcarp!

**Comment by adborden** [comment]
https://github.com/18F/fec-cms/pull/353 the last piece is in.
