### ISSUE TITLE
Usability Finding: Calendar Grid View "hard to read"

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1648]
During testing on April 28, the test subject concluded that the grid view was hard to read "especially for older eyes". 
One contributing factor may be the use of relatively small text, combined with the hidden overflow makes the details of any event difficult to determine at a glance. Taken together, this may make the table format somewhat overwhelming. 
![screen shot 2016-05-09 at 11 50 16 am](https://cloud.githubusercontent.com/assets/474916/15118914/46c55010-15dc-11e6-816f-f47ce5f74ea7.png)

**One bright spot:** While the user did not find it on their own, once we pointed out the "list-view" the user noted: "I do like the list. With the list, at least I can see what it is"

**possible solution**: We may want to explore making list view the default, or explore other grid view options. 

(also: calendar was not the focus of our testing; the user brought it up as something they were trying to do on the site and could not easily understand)

**Comment by jenniferthibault** [comment]
Since we've implemented the list view as the default view, do we want to resolve this issue, or should I investigate visual changes here?

**Comment by onezerojeremy** [comment]
I agree that we should close it: we're at least side-stepping the issue by focusing on the list view, which users seemed to be able to use to perform the calendar tasks with much less confusion. I'd put a pin in the calendar grid view as something to revisit in maintenance phase.
