### ISSUE TITLE
Calendar microcopy

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1649]
The sql tasks from #1619 

### Calendar events
- [x] Remove report codes
- [x] Microcopy edits to events so they are more human readable.
    - [x] “held today” to all elections
    - [x] “due today” to all reports
    - [x] Add punctuation to descriptions. For example “MD: Senate Election, Primary Election held today”
    - [x] For content events specifically Spacing of information. Add commas or periods, so we don’t have content that runs together, like “Orlando Regional ConferenceThe final FEC regional conference of the 2015-16 election cycle for candidates, parties and PACs.”
    - [x] upping the limit for putting states in front, to 3, (Emeligh okayed this and the user feed back definitely prefers the state first)

**Comment by LindsayYoung** [comment]
I think the spacing issue was confined to court cases, advisory opinions and conferences, it should be fine now.

**Comment by noahmanger** [comment]
Resolved by #1659
