### ISSUE TITLE
Usability Finding: calendar state filtering confusing user

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1650]
A user, while attempting to use the filtering by state, became confused by the presence of other state content still showing, and assumed the filtering was broken. 

![screen shot 2016-05-09 at 12 10 36 pm](https://cloud.githubusercontent.com/assets/474916/15119497/348b6f4e-15df-11e6-9d74-66c4d8a041f1.png)

There are some underlying data issues (not all data is tagged by state); we may have to rethink how we approach state filtering.  

(also: calendar was not the focus of our testing; the user brought it up as something they were trying to do on the site and could not easily understand)

**Comment by jenniferthibault** [comment]
Related front end: https://github.com/18F/openFEC/issues/1675

**Comment by LindsayYoung** [comment]
Adding state filtering to reporting periods 18F/openFEC/pull/1664

**Comment by noahmanger** [comment]
The work for this is captured in multiple places, so I'm going to close.
