### ISSUE TITLE
Usability finding: confusion in how applied filters work

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1653]
On the [receipts page](https://beta.fec.gov/data/receipts/?committee_id=C00571372&contributor_name=Smith&contributor_name=Smith%2C+John&max_date=04-13-2016), users did not uniformly understand how the filters worked, especially when more than one of the same type of filter was applied.

![search-contributor](https://cloud.githubusercontent.com/assets/474916/15126298/5be5d80c-15ff-11e6-8af9-2eb07855ffd8.gif)

The other thing to note is that we don't necessarily need to assume the burden of all users looking at this page and immediately understand how it works (this is important because some users have interpreted the filters with an "and" mindset, others with an "or" mindset, and this might be hard to correct without adding instructions that could both clutter the interface and not be read). It might be easier to use an initial faulty search as a teaching moment, to clearly show the user that the filtering works differently than they anticipated. 

possible things we might try:
- moving the results number to closer to the action taken
- reducing the distance between the applied filter tags and the action taken
- changing the wording and/or visual design of the check boxes to reinforce the way it works
- changing the way rows are added and removed to the results tab (visually animating their removal/addition)

**Comment by jenniferthibault** [comment]
In https://github.com/18F/openFEC-web-app/issues/1224 and https://github.com/18F/openFEC-web-app/pull/1232 we are implementing a functionality tweak which makes the tag/download count area stick. 

A few weeks back when we tested this, we saw that users noticed it, and referenced the tags while they were applying filters. 

This will be included in the next release.

@noahmanger In thinking about how we could make use of animation to show a change in search results, making use of the "slide" effect that's already used on the filter panels and glossary feels like a good way to stay consistent. How much control to we have over the elements in the table breaking apart horizontally? Would it be possible to slide out just the rows that are eliminated when you narrow the results through a filter, and slide in just the rows that are added when you expand the results through a filter? Or would we have to slide the whole results panel out & in when the results change? Do we even have the ability to add animation to the table itself? To what extent? Or are we limited to animations over or around the table, but not inside it? I've never done it before.

**Comment by noahmanger** [comment]
So, we can't animate the table rows individually. When you adjust the filters, we just make a new call to the API create a new table. But we could do things to animate the panel as a whole. Do you have anything in mind?

**Comment by jenniferthibault** [comment]
Changes to improve this experience were included in the [August 3rd release](https://github.com/18F/FEC/blob/master/release_notes/release_notes.md#august-3-2016-release-notes) and [August 17th release](https://github.com/18F/FEC/blob/master/release_notes/release_notes.md#august-17-2016-release-notes)

**Comment by jenniferthibault** [comment]
Sorry, closed prematurely. The and/or logic currently under construction (and hopefully in the next release) still needs to be tested. I'll leave this issue open until testing
