### ISSUE TITLE
Onboard @jontours

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#1655]
This is a list of everything that @jontours needs access to:

- [x] cloud.gov
- [x] api.data.gov
- [x] Stories on board
- [x] npm (fec-style)
- [ ] ~~Sentry~~
- [x] New Relic
- [x] GitHub FEC group
- [x] Google Docs FEC folder
- [x] AWS (for Amazon RDS)

@noahmanger and @LindsayYoung, am I missing anything?  I'll get started with what's here.

**Comment by ccostino** [comment]
@noahmanger you might have to add @jontours to Stories on board, I don't think I have that permission.  Does this require you create an account yourself first?  I can't remember.

**Comment by noahmanger** [comment]
Invited to Stories on Board!

**Comment by ccostino** [comment]
FYI, Amazon RDS access is queued up with the infrastructure team.

**Comment by ccostino** [comment]
Just a quick update - Amazon access is on its way if you haven't received it already, @jontours, and we'll take care of the Sentry and New Relic access once @LindsayYoung is back as I can't quite remember how we set it up.  Everything else is good to go!

**Comment by ccostino** [comment]
@jontours:  Did you ever receive account info for AWS?  If not, we should follow up.

**Comment by jontours** [comment]
@ccostino I haven't.  Or if I have, I haven't been notified.

**Comment by ccostino** [comment]
AWS access is still pending, I just pinged again in the issue to check on progress (or if this will even be possible).

**Comment by noahmanger** [comment]
AWS approved! Closing.
