### ISSUE TITLE
Readme python tests running error

### ISSUE THREAD

**Issue by jontours** [18F/openFEC#1658]
I tried running the python tests today and noticed in the code that the database connection string that 
specifies the testing database is "postgresql:///cfdm-unit-test", but based on the instructions (and python naming conventions in general) it should be: postgresql:///cfdm_unit_test.  I changed it and verified the tests passed (they did fail prior to this change).

**Comment by jontours** [comment]
I don't know that this really needs to be an issue.  Just need to formalize myself with the process of updating minor code fixes.  Is a pull request needed for very minor fixes?  I've not used git flow before, but I have used these processes manually in Git.

**Comment by LindsayYoung** [comment]
Yea, go ahead an make a pull request for just about everything. I don't make issues on things that are super minor, but maybe that is a bad habit.

**Comment by noahmanger** [comment]
Yeah, always do a pull request (using the `git flow feature start` syntax). If it would be faster to just make the fix right then and there than it is to write an issue; go for it. But if you're not going to do it then, good to write an issue for visibility. I'm going to add this to this sprint.

**Comment by jontours** [comment]
Cool, I figured this was a low-impact way for me to carry out a pull request from start to finish.  Upon installing git flow and doing the above (git flow feature start) I get the following message:  

'fatal: Not a gitflow-enabled repo yet. Please run "git flow init" first.'

Is this to be expected?

**Comment by noahmanger** [comment]
Yep. `git flow init` has to be run on each local instance of a repo.

**Comment by noahmanger** [comment]
We resolved this, correct?

**Comment by jontours** [comment]
Yup.
