### ISSUE TITLE
Deliver a list of user centered reading sources 

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1660]
to help build the case for user centered work in FEC, deliver a list of articles, books, etc that help show why what we're doing isn't just feedback gathering with small sample sizes, and how and why user centered work works.

**Comment by onezerojeremy** [comment]
Updates: @noahmanger had started a great document on debunking myths, I've spent a fair amount of time today adding a bunch to it. 

https://docs.google.com/document/d/1ZkM_r0GBKniNFpRSon2OLTHCN3s_bOlINgCW2907KlQ/edit?ts=57461ebf#

**Comment by onezerojeremy** [comment]
Details: Some myths to be busted include: 

- [x] “Listening to users is what got us in this mess. What we need is for those of us who know it best to just go do it.”
- [x] “How can you get meaningful data from 5 users? I’ve talked to hundreds!” or the similar: “5 users! Bah! That’s not statistically significant!”
- [x] “I don’t have time or resources to do user research.”
- [x] “I’m not a designer/researcher/product person.”
- [ ] “We have this market research survey already, we don’t need more research”
- [ ] “We can’t focus on a specific user: our product has to serve all”
- [ ] “The laws or lawyers won’t let me talk to users”
- [x] “Apple doesn’t do user research and their design is great”

Across the board tasks:
- [ ] Need to include many more links to supporting articles and literature
- [ ] Need to flesh out "the homer" story, though this may be less necessary as a cheatsheet.

**Comment by noahmanger** [comment]
Noting: this will be done when it's in a good shape to share with the FEC, and then turning it into a blog post will be a separate process.

**Comment by onezerojeremy** [comment]
Felt like this was missing important resources so I asked our larger design team for help. Now have a strong list [here](https://docs.google.com/spreadsheets/d/125wXXhVKTf7L_xoEyx2_SwoPop-wTsea0ump1P8NMZM)!

**Comment by noahmanger** [comment]
Awesome! Are both of these in a good place to share with FEC?

**Comment by onezerojeremy** [comment]
latest update: https://docs.google.com/document/d/1KdBCnKNEhfudFpTqTgk0ywl3T7GtaP5_Odcyd4dXMig/edit#

For this sprint, draft completion criteria

- [ ] share a piece (a fact or two) of the above with the FEC
- [ ] share the compiled [reading list](https://docs.google.com/spreadsheets/d/125wXXhVKTf7L_xoEyx2_SwoPop-wTsea0ump1P8NMZM) 
- [ ] get feedback on both from FEC 
- [ ] from above, determine what direction the remaining content should take to be useful, and make smaller "sprint-sized" issues for these

**Comment by onezerojeremy** [comment]
Updated versions shared with FEC : 
https://docs.google.com/document/d/1jXaIDUEFIFGGAcWx20RLByFoM7pKF2jpMVCB60bxMkM/edit#

as well as the reading list
