### ISSUE TITLE
Strange inconsistencies between API returns and FEC website returns

### ISSUE THREAD

**Issue by orendog** [18F/openFEC#1668]
In comparing the outputs of the main FEC website frontend (http://www.fec.gov/finance/disclosure/norindsea.shtml), the FEC API data, and OpenSecrets, I have come across several instances in which the FEC website did not include transactions that were listed in the API return for the same search parameter (and which were also listed in OpenSecrets).

For example, taking the name "samir mokaddem," if you search him on OpenSecrets, you get three transactions (four, actually, but one of them has the names reversed):

https://www.opensecrets.org/indivs/search.php?name=samir+moka*&cycle=All&sort=R&state=&zip=&employ=&cand=&submit=Submit

If you search for his name on the main FEC website, you only get one transaction, the donation to Keith Ellison.

If you use the following API query, you get the other two transactions, the two donations to Andre Carson, but NOT the Ellison one (my API key is snipped):

https://api.open.fec.gov/v1/schedules/schedule_a/?api_key= […] &min_date=1998&sort_nulls_large=true&contributor_name=mokaddem,%20samir&per_page=100

Any ideas why this is happening?

**Comment by orendog** [comment]
Additional info: searching the FEC site with the names reversed (samir, mokaddem) returns no hits; however, querying the API gets you the same two donations to Andre Carson. (This could be because the original staffer actually reversed the order of the names when entering them on the form; and someone might have coded it both ways just to be sure?)

Neither search returns the fourth entry on OpenSecrets, the donation on 3/3/16.

**Comment by LindsayYoung** [comment]
Hello,

I don't see the donation on 3/3/16, either. I will look for that next week.

As far as the search results being different, for your reference, here was the discussion about the different searches: https://github.com/18F/openFEC/issues/1597

Thanks for writing in

**Comment by noahmanger** [comment]
Has this been resolved?

**Comment by LindsayYoung** [comment]
Yes, I see the 3-3-16 transaction sub_id = 4060120161293568915

https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&min_date=1998&sort_nulls_large=true&contributor_name=mokaddem&per_page=100
