### ISSUE TITLE
create more shareable directional research 

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1673]
In order to help both new folks better understand how we got to where we are with the designs and existing folks keep track of what we have done, create a set of easily shared, feature-set linked research and other decisions that have driven the design

**Comment by onezerojeremy** [comment]
Update: I started porting some of the directional research to the wiki. Basically, I think we'll have to take a mixed approach to getting it linked: some will probably make more sense as pdfs (presentations, especially), and others it just might be more expedient to move up as pdf docs until we have time to convert them to markdown. 

Here's a sample linked section [for the dashboard](https://github.com/18F/FEC/blob/master/feature_sets/dashboard.md)

Here's a sample linked section [for the legal resources](https://github.com/18F/FEC/blob/master/feature_sets/legal_resources.md)

The legal section has more linked pdfs, the dashboard docs are converted to markdown. 

thoughts?

**Comment by onezerojeremy** [comment]
update: a new (nearly) table-less update to the format for research repo: https://github.com/18F/FEC/blob/master/feature_sets/advanced_data_tables.md

**Comment by onezerojeremy** [comment]
This sprint we spent a good deal of time working through the process of adding research insights from the testing cycle to the a format that supports feature set insight lookup. Still dont have the process of weaving deeper directional research into this fully fleshed out yet.

**Comment by noahmanger** [comment]
Closing in favor of this next step https://github.com/18F/openFEC/issues/1785
