### ISSUE TITLE
Make front-end change to restrict schedule tables to two-year period

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1674]
In order to for users to download itemized receipt and disbursement data, we need to constrain those queries to within two-year periods. 

Here's my understanding of how the interaction works:
- We have a cycle-select filter that defaults to the current two-year period, but includes periods as far back as the data goes
- This filter will necessarily always be set to something
- Users can further refine the date of transaction using the min and max-date filters

But I have some questions:
- For @LindsayYoung  or @ccostino : Is the two-year period filter based on the date the transaction happened? The date it was reported? Or the two-year period that includes the election cycle it's for?
-  For @jenniferthibault how do we want to change the date filters so that they're clearly bound by the year filter? e.g. You should only be able to set date ranges within that two-year period, right?

For reference, here's the ([original designs and discussion.](https://github.com/18F/openFEC-web-app/issues/1023))

**Comment by noahmanger** [comment]
Updated the comment to with more description.

**Comment by noahmanger** [comment]
Notes from side conversations:
- The tables are partitioned by `rpr_yr` which refers to the year the report is *for*, not the year it was filed nor the year the transaction was made. e.g. You could have a transaction made in 2015 that is *for* the 2016 election, but which isn't reported until 2017 (e.g. in a post-election report). 

Unrelated, I don't think we need to have this filter affect the date range input. Technically the report year has nothing to do with the transaction date. If someone filters to "2016" and then tries to do a date range outside that, they won't get any results and can refine from there. If we find this to be a problem we can revisit, but I don't think this detail is worth holding anything up for.

**Comment by jenniferthibault** [comment]
Showing no results could be confusing because it could mean that there's no matches. It's not clear that there's no matches because the parameters were impossible.

I'd like to demystify this for users here by presenting an error alert under the filter in the scenario where they enter a date range that isn't with the two year cycle they've selected. Something like this, but I'd appreciate @emileighoutlaw 's take on the language:

![screen shot 2016-06-01 at 11 51 23 am](https://cloud.githubusercontent.com/assets/11636908/15716164/37204550-27ef-11e6-8891-b33219c15e6f.png)

**Comment by emileighoutlaw** [comment]
Great alert idea. I like this for content:

> The date you entered isn't within your selected two-year period. Please enter a date within **2015–2016**.

I think it's enough to tell users to pick a date within the selected range; I don't think we need to explicitly tell users they can change the two-year period. I think the most important piece here is raising awareness of the two-year constraint, in case folks missed it.

**Comment by noahmanger** [comment]
Remaining criteria for completion:
- [ ] Don't make query if date is not validated
- [ ] Verify it works against actual API change
