### ISSUE TITLE
Implement remaining UI changes on calendar

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1676]

**Comment by noahmanger** [comment]
Other than adjusting the state filter placement (which we have a separate issue for), are there any other changes that need to be made? Did we settle on whether or not to make the category labels tooltips or glossary terms?

**Comment by emileighoutlaw** [comment]
There were a couple small content things other than the state filter placement, but I captured them in that issue, so I don't think they need repeating here. I'm 👍 with everything else!

**Comment by emileighoutlaw** [comment]
There were a couple small content things other than the state filter placement, but I captured them in that issue, so I don't think they need repeating here. I'm 👍 with everything else!

**Comment by noahmanger** [comment]
Closing in favor of this issue, which has more detailed discussion of the remaining changes https://github.com/18F/fec-cms/issues/298
