### ISSUE TITLE
Update beta.fec.gov landing page with new content coming soon

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1677]

**Comment by jenniferthibault** [comment]
We haven't really made use of the section on the home page that allows us to highlight what we're working on, and what's newest.

I've been thinking on some options that will let us make better use of the space, but keep the lift for added work low.


### Option A
- Keep what we have of the "New features" section, until we have a major new site section to introduce, such as Legal resources. That section would then replace the content on one of the existing four cards.
- More actively update the "What's next?" bullets (lift for content design & project planning)
- Add a "Latest release notes" link. The format of these notes could be either
  - A link to a markdown page on GitHub, ( @noahmanger started [a good example](https://18f.slack.com/files/manger/F1AD63M9D/release_notes.md) internally on the last release )
  - A pop up or modal on the site with a bullet list of changes
  - A Release page on the main GitHub repo, [similar to what the US Web Design Standards is using](https://18f.slack.com/files/manger/F1AD63M9D/release_notes.md) 

![screen shot 2016-06-01 at 3 24 42 pm](https://cloud.githubusercontent.com/assets/11636908/15723267/ad3837d2-280f-11e6-8ee4-ec69884ab3ee.png)


### Option B
- Update the "Newest features" section with every release, but simplify it to just card content, not extra supporting text (lift for content design, project planning, prioritizing which four features to highlight)
 - Update the cards with corresponding new _simple_ icons every week to demonstrate the changes (lift to visual design)
- Add a "Full release notes" link, same options as above

![screen shot 2016-06-01 at 3 24 34 pm](https://cloud.githubusercontent.com/assets/11636908/15723475/8e75bbac-2810-11e6-823c-ef7cb8552f51.png)



What do you think @emileighoutlaw / @noahmanger / @porta-antiporta ? Feel free to tag in others that should weigh in as well

**Comment by noahmanger** [comment]
I love where you're going with this. +100 to adding release notes somewhere highly visible. What about as just a regular text-based page on the site, perhaps the same layout as the CMS content pages?

Of the two options, I think A works best. I think keeping the more frequent release notes in a light-weight place linked to from the home page will ultimately lead to less friction and over-head than trying to regularly update the cards. Plus, I worry about change-blindness (h/t @onezerojeremy for the term ) with these cards if we're just tweaking language. 

The only change I'd propose is perhaps emphasizing the release notes link more, and maybe even include the date of when it was last updated. We could also add a little notification dot similar to what Slack does when there's something new, and track if people clicked on it or not.

**Comment by adborden** [comment]
This is related, I think https://github.com/18F/fec-cms/issues/318

**Comment by jenniferthibault** [comment]
Good call @adborden ! I hadn't even seen that! @emileighoutlaw looks like we're working on similar things, and had very similar directions going 👯 

Here's the update with Emileigh's content from https://github.com/18F/fec-cms/issues/318 and an updated link to the release. I don't think we need to necessarily add an extra notification if we're including the date in the link title, but we should definitely be tracking analytics on if people click it.

![screen shot 2016-06-03 at 10 34 14 am](https://cloud.githubusercontent.com/assets/11636908/15782053/c19b9404-2976-11e6-9634-a2c65a2fc141.png)

A thought on the `What's next` section: If we're not going to update it regularly, let's chop it. Are those four bullets something we can reasonably commit to updating?

I'm not sure about keeping a CMS page for the release, to be honest, I don't see that as useful content for the FEC to maintain on their own site, when there's already GitHub functionality. Any particular thoughts on why you were thinking CMS, Noah? I'd be curious to hear Emileigh's thoughts, fresh from the content audit too :)

**Comment by emileighoutlaw** [comment]
Ah — somehow we've ended up with several issues about this. I'm going to close those and bring any outstanding thoughts into this one. 😁

**Comment by emileighoutlaw** [comment]
**I'm super in favor of a much streamlined version of this content, because:**
- What we have is unwieldy. There are a lot of words (and people don't read). 
- People come to the website to perform functions; we want to surface those functions, not spend a lot of time explaining _how_ to use them. 

**I'm really digging the full release notes.** 
**And I love that your draft highlights some of the newer features, Jen!** 

Here's what I might write and surface in our four cards:
> Unique pages with financial totals for presidential, Senate and House candidates.
> Tailored registration and reporting content for candidates, political party committees, corporations and labor organizations.
> A calendar of events that you can personalize and export.

I'm not sure what the fourth one should be. It seems like the alert messages, the $0 filter, and the mega-menu (while really important for us and consistency) aren't really big enough to warrant 1/4 of the homepage cards. Maybe I'm overthinking it.

**Comment by noahmanger** [comment]
Remaining questions:
- [ ] Decide where release notes live
- [ ] Decide if we're keeping coming soon content.

**Comment by emileighoutlaw** [comment]
I'm going to let @jeanninehunter lead the charge on editing our release notes every sprint. She has a brilliant eye for plain language.

**Comment by emileighoutlaw** [comment]
How about this for four highlights:
> - A legal resources section with a searchable, full-text version of Title 11 of the Code of Federal Regulations (CFR). 
> - Tailored registration and reporting content for candidates, political party committees, corporations and labor organizations.
> - A calendar of events that you can personalize and export.
> - Unique data pages with financial totals for presidential, Senate and House candidates.

And no "What's next" section.

**Comment by jenniferthibault** [comment]
Question: Where do each of those cards link to? I'm most challenged by the second and fourth bullets. The second could link to reg/reporting landing page, but the fourth is more specific. Should there be three links? Each (pres/ senate / house ) goes to that page?

**Comment by emileighoutlaw** [comment]
The second bullet could either:
- Go to the legal landing page, or 
- We could link to the essentials for each of the players, like so: _Tailored registration and reporting content for [candidates](https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/), [political party committees](https://beta.fec.gov/registration-and-reporting/essentials-political-party-committees/), [corporations and labor organizations](https://beta.fec.gov/registration-and-reporting/essentials-corporations-and-labor-organizations/)._

We have the same options for financial totals. Either:
- One link to https://beta.fec.gov/data/advanced/ (which has a clear callout to the presidential, Senate, and House pages), or 
- A link for each one: _financial totals for [presidential](https://beta.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true), [Senate](https://beta.fec.gov/data/candidates/senate/?election_year=2016&cycle=2016&election_full=true) and [House](https://beta.fec.gov/data/candidates/house/?election_year=2016) candidates._

**Comment by jenniferthibault** [comment]
I don't have strong feelings on how the two cards should link, as long as they both use the same approach, either linking to individual elements, or linking to the parent page.

Here's what this would look like, complete with refurbished complex icons. I've switched over to one bright color + neutrals on a white background in a $primary card, so that the other color can be used as a highlight for the release notes. After changes to the data landing page, https://github.com/18F/fec-cms/pull/340 and https://github.com/18F/fec-style/pull/393 get in, this will be the only place (for now) that we use complex, multicolored icons, so it will reset the pattern.

![screen shot 2016-06-14 at 2 48 01 am](https://cloud.githubusercontent.com/assets/11636908/16033528/75731a2c-31da-11e6-88dd-97bc557a29c4.png)
