### ISSUE TITLE
Disbursements: Payee search not returning results for certain terms

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1679]
@fec-issue-bot commented on [Thu May 19 2016](https://github.com/18F/FEC/issues/321)

## What were you trying to do and how can we improve it?
Disbursement search. I think it&#39;s broken.  I search for a payee and get the loading animation for a while before the animation disappears without any change to the data set.

## Details
* URL: https://beta.fec.gov/data/disbursements/?recipient_name=spiros&amp;max_date=05-19-2016
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

---

@noahmanger commented on [Thu May 19 2016](https://github.com/18F/FEC/issues/321#issuecomment-220386862)

Huh. Yeah, I'm seeing 502 errors on `https://api.open.fec.gov/v1/schedules/schedule_b/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&recipient_name=spiros&sort=-disbursement_date&per_page=30` .

But it doesn't seem to happen with other queries (like [Boston](https://beta.fec.gov/data/disbursements/?amp%3Bmax_date=05-19-2016&recipient_name=boston)).

**Comment by ccostino** [comment]
I'm able to replicate this in production but not locally.  The only thing I see in the logs though is a worker timeout in the API logs.  There appears to be no actual error, though this particular query does seem to take a bit of time (about 9 - 10 seconds to run).  Perhaps we're hitting a timeout limit?  I'll look into that to see.

**Comment by ccostino** [comment]
Just a few more details: the client is receiving 502 Bad Gateway errors in about 30 seconds or so, and sometimes a 504 Connection Timeout error at about 1 minute.  I'm only seeing the worker timeout error in the API logs, and a client connection lost error in the RDS logs.  No stack traces, though.

**Comment by ccostino** [comment]
I cannot reproduce this locally or in the `dev` environment, but I can reproduce it in `stage` in addition to `prod`.  I'm not seeing any settings or environment variables that indicate a difference that might allow this query to run locally/against `dev` and not elsewhere but I'll keep looking.

**Comment by LindsayYoung** [comment]
I am wondering if the indexes need to be updated on dev. That should be part of our regular process, but we might want to confirm.

**Comment by ccostino** [comment]
Hmm, if that's the case then wouldn't staging be okay?  Or is this a part of updating the itemized tables (since this is hitting schedule b ultimately)?  If so then that could very well be it.

**Comment by ccostino** [comment]
It looks like this is still an issue in production after our last release.

**Comment by ccostino** [comment]
Wait, I spoke too soon!  Now it's working?  It failed for me just a few minutes ago.  Maybe now that the query is cached, perhaps?

**Comment by noahmanger** [comment]
Looks good to me! Closing.
