### ISSUE TITLE
The get schedule_e doesn't appear to not be returning records for a payee_name

### ISSUE THREAD

**Issue by TheBigTurnip** [18F/openFEC#1682]
https://api.open.fec.gov/v1/schedules/schedule_e/?payee_name=Rigel%20Strategies%20LLC&max_date=5%2F21%2F2016&per_page=50&min_date=4%2F1%2F2016&api_key=DEMO_KEY

The above query should return the below record but it is not instead it's returning no records

http://docquery.fec.gov/cgi-bin/fecimg/?201605209015551941

**Comment by LindsayYoung** [comment]
Thanks for reporting this! 

We are working on a fix to these delays. I expect that record to show up in the next few days. Sorry for the inconvenience, this delay should not be a problem for future deadlines when we finish PR #1538 

(I checked and It looks like this record has not made it into `sched_e` yet but is in `fec_vsum_sched_e`.)
