### ISSUE TITLE
Update "contributor name or ID" field autosuggest 

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1684]
Upon doing a search for an individual contributor in the contributor search field, a user is often confronted with the statement "No results found". 
<img width="288" alt="screen shot 2016-05-23 at 4 09 19 pm" src="https://cloud.githubusercontent.com/assets/474916/15483166/4ff53daa-2101-11e6-8aca-6da4733a5e4a.png">

This "no results found" language is true only for the committee contributors, not the individual contributors that users may be using the box to search for (it does both). This caught some users up in usability testing. 

To fix, consider including messaging about the two kinds selections a user can make, and which kind of results that are and are not being found. For example, consider altering the language "no results found" to "no committee results found" or similar. 

An additional enhancement that would increase clarity would be to remove the committee type ahead contextual menu if "committees" is deselected in the "received from" check boxes.

**Comment by noahmanger** [comment]
Ah right. I meant to include this. How does this look? 

![image](https://cloud.githubusercontent.com/assets/1696495/15484260/0c6c370e-20ee-11e6-837c-7cd28c1024d8.png)

@emileighoutlaw what do you think about the language?

**Comment by onezerojeremy** [comment]
the language seems pretty good to me, but i defer to Emileigh as per usual.   


Because the field searches for two types of things, i think perhaps it's important to keep the user in the loop that they are doing both, which we were doing before but isn't here. Basically I think we should keep a target for the user to trigger a search for "dinosaurs" across the contributor name field in the selection area. Not sure exactly what to call that, but it's probably worth giving it equal billing (same bolding).  

<img width="318" alt="screen shot 2016-05-23 at 5 10 16 pm" src="https://cloud.githubusercontent.com/assets/474916/15484725/6c724ac4-2109-11e6-8569-025fcdf5915a.png">


It might work to move it after the committee results:
<img width="294" alt="screen shot 2016-05-23 at 5 13 12 pm" src="https://cloud.githubusercontent.com/assets/474916/15484762/ae912010-2109-11e6-9ff0-bfc944bc01cb.png">
we could probably keep the non-bold on that too.

**Comment by noahmanger** [comment]
Oh yep, I shared the one that doesn't allow free text. Here's how that works:
![image](https://cloud.githubusercontent.com/assets/1696495/15484865/04ff6718-20f1-11e6-95a4-cac3f5830d3e.png)

Because it's previously on top, I think it should stay on top.

**Comment by onezerojeremy** [comment]
Full disclosure: I don't have a solid sense of why people were a *little* mixed up by this box, and I think this version is better than what's live now: specifying that it's searching for committees should help, and that may be good enough. I am nitpicking here because folks generally read top to bottom, and may read the second thing as a response to the first thing, and therefore it may still be contributing to a touch of confusion. 

To be specific: the thing I'm trying to avoid is that folks think that 
_No committees found matching "dinosaur"_ is in response to 
_Search for: "dinosaur"_

**Comment by noahmanger** [comment]
Ah I see what you're saying. Thanks for clarifying.

You know, the other thing we could do is simply not show a message if there are no results but it accepts free text. (But keep the no results message if free text search isn't supported). That might be the most obvious.

**Comment by onezerojeremy** [comment]
That could work nicely! I like it.

**Comment by noahmanger** [comment]
I think that's the ticket! ![see](http://g.recordit.co/a9jGCaaHPc.gif)

**Comment by emileighoutlaw** [comment]
Love where y'all ended up! You didn't even need me :)

**Comment by onezerojeremy** [comment]
beautiful!

**Comment by noahmanger** [comment]
Done and released!
