### ISSUE TITLE
Consider revisiting record count and pagination on advanced data tables

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1685]
In usability testing, we ran into two related issues on the advanced data tables:
- some folks ran into an issue where they weren't sure what changed in the results section of the page
- some folks tried to use the pagination and weren't sure what changed in the results section of the page

There are likely a couple things going on here: 
# [change blindness](https://en.wikipedia.org/wiki/Change_blindness)
Or if you're feeling especially nerdy read [this](http://www2.psych.ubc.ca/~rensink/publications/download/Vision%26Attention-RR.pdf) 
When a user triggers an update of the filters, we trigger a results frame reload. While the results are loading, we show a full screen waiting indicator, then reset the results. This is similar to the effect that the paper talks about in introducing a blank scene between two scenes which are different. Because we are showing 30 records of what are generally result sets larger than 30 records of highly detailed information, all but the biggest changes may be hard to see. Short of rewriting how results enter in the stream of existing results (_shudder_ that sounds hard), this may not be easy to address. 

The other possible area where we can consider indicating the change that has happened is in 
# record counts
The record count provides a cue that the data has changed. Pagination & record counts appears in two sections of the page: 
<img width="1278" alt="screen shot 2016-05-23 at 5 39 22 pm" src="https://cloud.githubusercontent.com/assets/474916/15485445/5613842e-210d-11e6-9a30-b95ef9645304.png">

<img width="998" alt="screen shot 2016-05-23 at 5 39 02 pm" src="https://cloud.githubusercontent.com/assets/474916/15485434/4479b30a-210d-11e6-8ed3-4a581a1dc99c.png">

Both of these take up limited real estate and are far from the actions that change their function. Consider either or both moving it closer to the action the user has taken, and/or increasing the prominence of these elements to help show the user what change has happened. 

Thoughts? There are probably other ways to help the user see what changes their actions have made!

**Comment by jenniferthibault** [comment]
Resolved by the [August 3rd release](https://github.com/18F/FEC/blob/master/release_notes/release_notes.md#august-3-2016-release-notes)

**Comment by jenniferthibault** [comment]
To clarify — we've moved the record count closer to the tag field, and added validation to the filters as they are applied in the panel. That work was also part of the [August 17th release](https://github.com/18F/FEC/blob/master/release_notes/release_notes.md#august-17-2016-release-notes)
