### ISSUE TITLE
Last Name sort order

### ISSUE THREAD

**Issue by gmj2053** [18F/openFEC#1687]
I didn't see a ticket related to this, but this is a bit odd to me.
I would expect last names to sort, not last name + first name
https://beta.fec.gov/data/candidates/?cycle=2012&cycle=2014&cycle=2016&election_year=2016
BROWN, JAMES P 2016 
BROWN, KENNEDY KING MR. 2016 
BROWNLEY, JULIA 2012 - 2016 
BROWN, LIZ 2016 
BROWN, PAUL MICHAEL 2016 

 Keep up the great work!

**Comment by LindsayYoung** [comment]
Thanks for commenting! 

In this case, the name is all one field, since we don't always have a breakdown of first and last name, so it sorts on the entire string as the name field.

**Comment by gmj2053** [comment]
OK, thanks, good to know!
