### ISSUE TITLE
Presidential 12P reporting dates for 2016 (and presumably after that)

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1690]
Beginning this year we no longer display presidential preprimary/caucus/convention report filing deadlines on the calendar. Older entries should still show them but they should be filtered out as of 2016.

I believe the reason for this is that presidential committees that receive or expect to receive <=$100,000 or spend or expect to spend =$100,000 are required to file monthly during the election year and monthly filers by rule don't file pre-primary reports.

So the upshot is, the betaFEC calendar should display house and senate pre-primary/caucus/convention reporting dates but not presidential.

**Comment by LindsayYoung** [comment]
Right now we are filtering out reports with report_type '12C' and '12P'. Are there additional codes that we should be filtering out for now?

See full sql [here] (https://github.com/18F/openFEC/blob/develop/data/sql_updates/omnibus_dates.sql#L92) if that helps with context.

**Comment by jwchumley** [comment]
Yes. That's the problem. We added 12CAU and 12CON so you could distinguish 
the difference since both use 12C. Exclude  presidential 12CAU and 12CON.

**Comment by LindsayYoung** [comment]
Thanks!

**Comment by LindsayYoung** [comment]
OK, I am adding these codes too. We check for office sought in the query, so as long as that is correct, don't worry about that aspect.
