### ISSUE TITLE
Flask .11 compatibility

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1695]
We can peg things to .10 for now, but we should solve the issue to get onto the next stable version of flask

**Comment by noahmanger** [comment]
Let's make this task focused on research:

**Completion criteria:**
- [ ] Identify what all will need to change in order to support the new Flask app

**Comment by noahmanger** [comment]
So can we close this now that #1717 is done?

**Comment by LindsayYoung** [comment]
Yes!
