### ISSUE TITLE
Schedule E is off data warehouse tables

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1700]
*Completion criteria:*
- [x] Summary forms (form 3x) use new tables
- [x] 24/ 48 hour reports use new tables

Dependency: need 24/48 hour data from FEC.

Both of these need to happen together, or else we lose data. 

## Update
After doing this, make sure it has resolved the following issues:
- [ ] https://github.com/18F/openFEC/issues/1927
- [ ] https://github.com/18F/openFEC/issues/1811

There might be more too.

**Comment by jontours** [comment]
This might not be blocked anymore, I think they added some of the needed tables.  I can check.

**Comment by noahmanger** [comment]
Update: according to @PaulClark2 we have everything we need to do this:
```
tables (monthly and quarterly filings)
public.fec_vsum_f3x
public.fec_vsum_sched_e
public.fec_vsum_f5
public.fec_vsum_f57
views (24-hour and 48-hour reports of independent expenditures)
public.fec_f24_notice_vw
public.fec_sched_e_notice_vw
public.fec_f5_notice_vw
public.fec_f57_notice_vw
```

**Comment by jontours** [comment]
@PaulClark2 I'm trying to understand the relationship of all these tables and how they should be exposed.  Currently we generate the table `ofec_sched_e` based on the `sched_e` table.  Now `sched_e` has been replaced by the `fec_vsum_sched_e` table, understanding the new mapping was easy enough.

But with the other forms lifted up above, which do we need to use to expose 24/48?  I did some perusing and can ell that some of these are self-explanatory, like `fec_f24_notice_vw`.  How about these other tables like `fec_vsum_f5`?  I know that correlates to real world entity called form 5, but how does it relate to `fec_vsum_sched_e`.  Does it contain the same information as that table?  Basically asking how these are all related, and how they will map to the `ofec_sched_e` table.  

Sorry for all the questions but trying to get a grasp on this.

**Comment by PaulClark2** [comment]
Some context for IE filings:  

Form 3X – Schedule E and Form 24 – Schedule E
Political committees that make independent expenditures (IEs) file a Form 3X (F3X) which includes Schedule E (SE). Itemized IEs are disclosed on SE. Committees file F3X on a regular reporting schedule. 

Committees making IEs may have additional reporting requirements depending upon the amount of the expenditure and number of days before an election. These additional reports are 24-hour and 48-hour reports of independent expenditures. These reports are filed on Form 24 (F24) and include SE. The itemized IEs reported on 24-hour and 48-hour reports of independent expenditures are reported again on the F3X SE.

Form 5 – Form 57
Persons other than political committees that make IEs file Form 5 (F5)  which includes Form 57 (F57). Itemized IEs are disclosed on F57. Persons other than political committees file F5 if they meet certain thresholds on a regular reporting schedule.

Like political committees, persons other than political committees making IEs may have additional reporting requirements depending upon the amount of the expenditure and number of days before an election. These additional reports are 24-hour and 48-hour reports of independent expenditures. These reports are filed on F5 and include F57. The report type for these filings is "24" or "48." The itemized IEs reported on 24-hour and 48-hour reports of independent expenditures are reported again on the F5X F57.

**Comment by PaulClark2** [comment]
@jontours now for your specific questions:
`fec_f24_notice_vw` contains the parent rows for `fec_sched_e_notice_vw` and `fec_f5_notice_vw` contains the parent rows for `fec_f57_notice_vw`

If we follow a similar model as for other transactions, we are only exposing the rows from `fec_sched_e_notice_vw` and `fec_f57_notice_vw`

An important caveat for both `fec_sched_e_notice_vw` and `fec_f57_notice_vw` is they contain transactions from new and amended reports.

**Comment by jontours** [comment]
Thanks @PaulClark2!  I'll digest that a bit and post back here if I'm unclear on anything.

**Comment by noahmanger** [comment]
It is with the utmost joy that I can close this PR because it was implemented in https://github.com/18F/openFEC/pull/1730

Thanks @jontours !
