### ISSUE TITLE
FEC Reviews and verifies new data on dev

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1701]
**Fact table completion criteria:**
- [x] Verify summaries are correct on candidate pages
- [x] Verify summaries are correct on committee pages
- [x] Verify summaries are correct on election pages

**Schedule A & B completion criteria:**
- [ ] Verify aggregates are correct candidate pages
- [ ] Verify aggregates are correct committee pages
- [ ] Verify aggregates are correct elections pages
- [ ] Verify data is correct on receipts page
- [ ] Verify data is correct on disbursements page

**Schedule E completion criteria:**
- [ ] Verify data is correct on independent expenditure page

**Comment by PaulClark2** [comment]
CA-12 election page 
	candidates and dollar amounts match current website
Some senate numbers, like McCain, are inflated see https://github.com/18F/fec-style/issues/433

Ryan - House - H8WI01024
candidate page aggregates are good
committee page - individual contributions (probem with is_individual: GitHub https://github.com/18F/openFEC/issues/1832)
	Ryan contributions from individuals from Texas
	TX inflated by $133,050.00 (18Js should be excluded)
	coded is_individual	$  928,887.76
	18Js		$  133,050.00
	is_inferred_individual	$    58,986.00
			$1,120,923.76

Paul - Senate - S0KY00156
6-year and 2-year aggregates are good
	question about size of contribution aggregate table.
	
On DEV, I'm getting different results when I run these queries: 
select sum(contb_receipt_amt) from ofec_sched_a_2015_2016 where cmte_id = 'C00496075' and is_individual = 't' and abs(contb_receipt_amt) between 200.01 and 499.99;

select * from ofec_sched_a_aggregate_size where cmte_id = 'C00496075' and cycle = 2016 and size = 200;

select sum(contb_receipt_amt) from  ofec_sched_a_master where cmte_id = 'C00496075' and two_year_transaction_period = 2016 and abs(contb_receipt_amt) between 200.01 and 499.99 and is_individual = 't' ;

select sum(transaction_amt) from F_ITEM_RECEIPT_OR_EXP where rpt_yr in (2015, 2016) and cmte_id = 'C00496075' and sched_tp_cd = 'SA' and abs(transaction_amt) between 200.01 and 499.99;

ofec_sched_a_2015_2016:       $76,844.85
ofec_sched_a_aggregate_size:  $77,759.85
ofec_sched_a_master:              $76,844.85
FECP:                                      $78,654.85 (I expect this to be different)

Clinton - President - P00003392
4-year and 2-year aggregates are good; correctly displays 2014 PCC and 2016 PCC
Top 10 disbursements by recipient match FECP

We need to revisit purpose of disbursement but this is not a hold for today's release  (example: Clinton travel beta $34k; FECP $4.6 million) https://github.com/18F/openFEC/issues/1833

select purpose, sum(transaction_amt) from F_ITEM_RECEIPT_OR_EXP where rpt_yr in (2015, 2016) and sched_tp_cd = 'SB' and cmte_id = 'C00575795' and memo_cd is not null group by purpose order by 2 desc;

Trump - President - P80001571
4-year and 2-year aggregates are good (correct - no 2013-2014 data)

revisit Disbursements received from committees (https://github.com/18F/openFEC/issues/1834)
Disbursements received from committees seems to incorrectly includes earmarked contributions as if they were contributions from the conduit committee

Disbursements to committees displays some aggregates for entities that are not committees
