### ISSUE TITLE
Visual design of spending overview page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC#1703]
Using the wireframes from https://github.com/18F/openFEC/issues/1620 and https://github.com/18F/openFEC-web-app/issues/1188, it's time for some visual styling, associated fundraising issue is in #1656

**Comment by jenniferthibault** [comment]
Alrighty! I have an [InVision mockup](https://invis.io/ZM7NUDSRN#/167132268_Spending-Overview) with the latest designs.

The interaction patterns are identical to what we've established on the Raising side, and you can find background in this issue: https://github.com/18F/openFEC/issues/1656

Mobile patterns will also echo the Raising side, and mockups/explanation here: https://github.com/18F/openFEC/issues/1656#issuecomment-226357839

I don't have mobile mockups finished for the Spending side yet, but I'm planning on completing those tomorrow, and updating both InVision prototypes with more functionality.  Just wanted to get an update started now, but I'll follow up when the prototype is updated tomorrow.

**Comment by jenniferthibault** [comment]
Alrighty, mobile mockups have been updated [HERE](https://invis.io/4P7NTV93E#/167671957_Spending-Mobile1)

And desktop mockups have been updated [HERE](https://invis.io/ZM7NUDSRN#/167132268_Spending-Overview)

Most things are clickable, so give them a whirl.

**Comment by jenniferthibault** [comment]
[Mobile prototype has been updated here](https://invis.io/R97U6AEAU#/171023876_Spending-Mobile1)

**Steps to completion**
I'd like to separate the remaining interaction questions into issues that aren't about styling and assign to @onezerojeremy or @noahmanger 
Those questions include:
 - what is the graphic/map/table interaction on desktop & mobile for 
  - "What's spend on day-to-day operating activitites" topic page
  - "Where money is spent to support and oppose candidates" topic page
- [ ] Sign off/ style changes from 18F team

**Comment by noahmanger** [comment]
I'd just repeat my comment from https://github.com/18F/openFEC/issues/1656#issuecomment-230057538 . This is awesome stuff. We'll take care of the remaining interaction issues elsewhere.
