### ISSUE TITLE
Committee pages: use the same scale for bar charts across all tabs so that users can get an idea of how a value on tab 3 compares to the highest value on tab 1

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC#1704]
@fec-issue-bot commented on [Thu Nov 05 2015](https://github.com/18F/FEC/issues/133)

## Feedback
On the following page (and its tabs), there are bars shown on the right to make it easy to see how each piece of data compares to other rows in a group:

https://beta.fec.gov/data/committee/C00575795/?cycle=2016&amp;tab=disbursements

However, whenever you switch pages, the gauges of the bars are reset to only compare against the rows that are currently shown. For example, the bar is full for the highest value on page 1 (which could be $1,000,000), and then on page 2, the bar is still filled for the highest value (which could be $10,000). It would be nice if all the bars were placed on a logarithmic scale so that I can get an idea of how a value on page 3 compares to the highest value on page 1.

Thanks! The website is a great improvement over the old fec.gov so far!!!!!!

## Details
* URL: https://beta.fec.gov/data/committee/C00575795/?cycle=2016&amp;tab=disbursements
* User Agent: Mozilla/5.0 (Windows NT 6.1; rv:41.0) Gecko/20100101 Firefox/41.0

---

@jenniferthibault commented on [Fri Dec 04 2015](https://github.com/18F/FEC/issues/133#issuecomment-162002823)

I'd like to second this piece of feedback. I was using the site to research who a certain gun-focused committee contributed $$ to, and I was expecting tho see the bar charts progressively get smaller as I advanced pages. Instead, it reset at every screen, which is disorienting! If I hadn't helped build the site, I wouldn't understand why this was happening. 

You can see what that looks like when I advance through the pagination here: https://beta.fec.gov/data/committee/C00053553/?tab=disbursements

![fruxhvjvm7](https://cloud.githubusercontent.com/assets/11636908/11593928/072979e6-9a75-11e5-8710-0e9c122f2a89.gif)

---

@noahmanger commented on [Fri Dec 04 2015](https://github.com/18F/FEC/issues/133#issuecomment-162028251)

That's a good point. I'd give it a bump too.

---

@jenniferthibault commented on [Fri Jun 03 2016](https://github.com/18F/FEC/issues/133#issuecomment-223675839)

Bumping this over to another repository so that we can work it into our project planning flow.

**Comment by noahmanger** [comment]
I have this fixed in https://github.com/18F/openFEC-web-app/pull/1313

![demo](http://g.recordit.co/ERxWnbmkhz.gif)

**Comment by jenniferthibault** [comment]
YEEESSSSS 🚀 🎇 ✨

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1313
