### ISSUE TITLE
Test Plan, June 6-10

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1710]
# Research Test Plan Week June 6-10

### Recruitment Activities
- [x] Recruit 5 users for Legal Prototype testing @ethanheppner @onezerojeremy @edmullen (schedule - any day)
  - [x] legal user
  - [x] legal user
  - [x] legal user
  - [x] legal user
  - [x] legal user
- [x] Recruit internal users for AO Search Quality @edmullen 
- [x] Recruit external users for standard usability testing @ethanheppner  (Thursday)
  - [x] user
  - [x] user
  - [x] user
  - [x] user
  - [ ] user
- [x] Recruit 30ish users for treejack 
  - [x] ask users who we emailed but didn't sign up for normal testing to try out Treejack [Wednesday/Thursday] @ethanheppner 
  - [x] figure out revision to ethnio ask for treejack recruitment @onezerojeremy

### Test Plans & Scripts 
- [x] Finish & Launch IA treejack : @edmullen @emileighoutlaw 
- [x] Develop standard usability [test plan](https://github.com/18F/FEC/blob/master/test_scripts/2016-6-9.md) @onezerojeremy 
- [x] [Launch AO Search Quality](https://github.com/18F/fec-eregs/issues/93) test @edmullen 
- [x] [Develop legal prototype](https://github.com/18F/fec-eregs/issues/122) test @edmullen

**Comment by emileighoutlaw** [comment]
Treejack draft is complete. @edmullen hast it to review (but I want to be sensitive that I handed it off to him at 5:15 p.m., ET).

@ethanheppner, do you need any help writing that email? (Same to you @onezerojeremy with the ethnio revisions)

**Comment by edmullen** [comment]
Treejack looks good to me. 👍

**Comment by edmullen** [comment]
### AO Search Quality test

Information will be gathered using [this form](https://docs.google.com/a/gsa.gov/forms/d/1HNijon8V9odGox3rLa6fMrqyykiG6S_ukpSoJS64U0k/edit?usp=sharing).

I'm initially sending it to Cheryl, get her thoughts, and ask her to send it on to others at FEC.

**Comment by ethanheppner** [comment]
@emileighoutlaw: sure can you get me started with a draft? I'm thinking I could send it to the group of people who didn't respond to our first email, and could also individually invite people who couldn't participate in our regular testing this week due to scheduling conflicts.

**Comment by emileighoutlaw** [comment]
Yes I can! Anyone can make edits to this!


Hi there,

It's a busy time of year, and we completely understand that a 45-minute chat is tough to schedule. But we'd still love to get your feedback on our new designs for the FEC. Do you have 5 minutes to check out something we're working on? If so, would you take a [sneak peak]-(link) at something we're working on and answer four quick, questions?

Thanks so much,
Ethan

**Comment by ethanheppner** [comment]
Looks good to me! Do you have the link ready? Apologies if you posted it elsewhere and I'm just totally missing it.

**Comment by emileighoutlaw** [comment]
Oh! That's my bad. Sorry, Ethan. :)

https://usagov.optimalworkshop.com/treejack/611a1j53

**Comment by emileighoutlaw** [comment]
Also, for the people who had conflicts, I think you can probably use the same email and just substitute in "Hi _name_" for "Hi there,"

**Comment by onezerojeremy** [comment]
Usability test script, now [linked](https://github.com/18F/FEC/blob/master/test_scripts/2016-6-9.md). still putting the finishing touches on it (adding a filtering task)

**Comment by onezerojeremy** [comment]
ethnio edits w link to treejack are live!

**Comment by onezerojeremy** [comment]
ethnio edited to remove link to treejack. 

Looks like we're only looking for the recruiting and outreach on the search quality findings. @edmullen: I'm thinking it might make sense to close this issue out and reopen one focused on that, since that'll probably take a bit longer to come back. What do you think?

**Comment by edmullen** [comment]
Sorry, I got four people at FEC for this. We've currently received responses from two of them. You can [follow the issue here](https://github.com/18F/fec-eregs/issues/93) if interested. I've checked off the tasks above.

I also checked off the treejack tasks because that's finished.

**Comment by onezerojeremy** [comment]
Excellent! Since that's tracked separately I'll close this.
