### ISSUE TITLE
Filings tab default sort

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1711]
The default sort on the filings tab and in the grid for the filings search needs work. This is the sql we use to sort the filings tab in the viewer: This sort order has been worked out over many years to support internal users (there are many who use the filings list heavily)

SELECT    f.document_filed,
          f.form_tp,
          f.rpt_tp,
          f.to_from_ind,
          f.request_tp,
          f.amnd_desc as Amended,
          f.receipt_dt  AS filed_on,
          f.cvg_start_dt AS from_date,
         (CASE
             WHEN f.form_tp = 'FRQ'
             THEN
                NVL (f.cvg_end_dt, f.receipt_dt)
             ELSE
                f.cvg_end_dt
          END)
            AS end_date,
         f.pages,
         f.BEGIN_IMAGE_NUM AS image_num,
         replace(f.full_url,'http://','') as full_url,
         replace(decode(f.form_tp,'F24','docquery.fec.gov/pdf/PAPER/'||f.BEGIN_IMAGE_NUM||'.pdf#navpanes=0', f.pdf_url),'http://','') as pdf_url,
         f.rpt_yr,
         replace(f.download_url,'http://','') as download_url,
         replace(f.html_url,'http://','') as html_url
        FROM disclosure.export_sdrform98 f
           WHERE f.cand_cmte_id = upper('C00140715') 
       ORDER BY rpt_yr DESC,
         s_type,
         s_var_date,
         s_rpt,
         s_3l desc,
         s_date,
         (CASE
             WHEN form_tp = 'FRQ'
             THEN
                s_rec || '-' || rfai_sub_id
             ELSE
                s_rec || '-' || sub_id
          END),
         s_rec,
         s_form,
         (CASE WHEN s_form = 'SM' THEN s_amend END),
         begin_image_num;

The filings search probably should have a different sort. Maybe based on the output grid for this:
http://www.fec.gov/finance/disclosure/efile_search.shtml

It is used extensively by RAD to grab .fec files for review. It is pretty much in committee name/filenum desc. order. Probably should work with RAD/Pubrec/Press/Coding and Entry folks to get this sort right.

**Comment by LindsayYoung** [comment]
Thanks for getting this to us Jeff! We will definitely want this for filings when we transition to the new table. We still need the underlying `SDR_FORMS98` table for that, I don't see it yet. (Correct me if I am wrong.)

**Comment by jwchumley** [comment]
I thought we were already sending you sdrform98 but I see we are not. If we do add that this will be useful. If not, I also have the logic for applying the s_type, s_var_date and s_rpt values for sorting.

**Comment by noahmanger** [comment]
At long last, this has been implemented. We may still have some fine tuning, but it should be a lot better.
