### ISSUE TITLE
Update deploy task to account for cloud.gov SSO

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#1714]
The recent change to cloud.gov to use SSO for logging in has partially broken our deploy task due to the login step.  We should investigate how we can incorporate this change to make the deploy task still run seamlessly for us and update our deploy instructions accordingly.

Perhaps we could add a check to see if you're already authenticated first and if so, just run `cf target` to change the org and space instead and if not, fall back to logging in.

**Comment by adborden** [comment]
The approach I took was to assume you're already logged in unless you explicitly set the env vars with your credentials. I only had a chance to implement this in the web app here https://github.com/18F/openFEC-web-app/commit/e6c6ab71d36e08771583922e3847af51c372aad6

I'd be happy to pick this up to implement it for the other apps.

**Comment by ccostino** [comment]
Oh that's right, I had forgotten that you looked into this already @adborden, thanks!  Yes, that'd be awesome if you want to run with it for the API and CMS apps too.  I also can't remember if this is already merged, if it isn't, let's get that in there. :-)

**Comment by adborden** [comment]
This one is already merged. I'll pick up the other apps soon.

**Comment by ccostino** [comment]
Awesome, thanks @adborden!

**Comment by noahmanger** [comment]
This is done! Thanks all.
