### ISSUE TITLE
Difference in contributor count between beta data table and classic map

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1719]
@fec-issue-bot commented on [Tue May 24 2016](https://github.com/18F/FEC/issues/329)

## What were you trying to do and how can we improve it?
did a search yesterday on the beta for NM contributors to Trump
https://beta.fec.gov/data/receipts/?committee_id=C00580100&amp;contributor_state=NM&amp;max_date=05-24-2016

and it comes up with 27 contributions… 

but when i use the map function
http://www.fec.gov/disclosurep/pnational.do
click on NM and download the csv for Trump it’s 54 … not sure what’s up with that?

## Tell us about yourself
Jeremy, relaying from a nice usability tester who emailed it to us

## Details
* URL: https://beta.fec.gov/data/receipts/?committee_id=C00580100&amp;contributor_state=NM&amp;max_date=05-24-2016&amp;is_individual=true
* User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

---

@onezerojeremy commented on [Tue May 24 2016](https://github.com/18F/FEC/issues/329#issuecomment-221377748)

Here's the 54 count csv from http://www.fec.gov/disclosurep/pnational.do: 
[P80001571-NM.zip](https://github.com/18F/FEC/files/280340/P80001571-NM.zip)

---

@noahmanger commented on [Wed May 25 2016](https://github.com/18F/FEC/issues/329#issuecomment-221628157)

Oh interesting. I wonder if it's that the main FEC site is double-counting contributions (inferred from 27 * 2 = 54). Usually the problem is in reverse, that beta has double the records. @PaulClark2 what do you think?

---

@sandrafish commented on [Wed May 25 2016](https://github.com/18F/FEC/issues/329#issuecomment-221633133)

i don't think that's the deal (i'm the originator of this issue) - i checked for that and the amounts for individuals were the same in both files, but there were missing donors from the beta...

---

@noahmanger commented on [Wed May 25 2016](https://github.com/18F/FEC/issues/329#issuecomment-221637242)

Huh. Well that's fishy indeed. We'll keep you in the loop @sandrafish . Thanks for raising the issue!

**Comment by LindsayYoung** [comment]
The estimated counts on the large schedules are approximate, an accurate count would take over a minute per query. 

I think we should follow up with this as part of testing downloads to make sure there is not another issue, but we can't tell by looking at the API count estimate.

**Comment by noahmanger** [comment]
Are the counts approximate even for results as small as 27? I thought they were only approximate when we were talking in the hundreds of thousands / millions of records.

**Comment by LindsayYoung** [comment]
all counts on the schedules/schedule_b and schedules/schedule_a endpoints use the postgres explain function and not count()

https://18f.gsa.gov/2015/07/15/openfec-api-update/

**Comment by LindsayYoung** [comment]
Can we move this to #1716?

**Comment by noahmanger** [comment]
Sure.

**Comment by LindsayYoung** [comment]
close #1719 in favor of #1716
