### ISSUE TITLE
Bug: Receipts for a committee aren't showing up

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1720]
@fec-issue-bot commented on [Tue Jun 07 2016](https://github.com/18F/FEC/issues/345)

## What were you trying to do and how can we improve it?
Trying to download data from a quarterly report,  to use in Excel

## General feedback?
I found the link to the file by accident once. I recall clicking on a total, and it led to the data source. Now, I can&#39;t find that. I can find the pdf of the report, but not the data. Very frustrating.

## Tell us about yourself
reporter, interested in a particular candidate&#39;s contributions.

## Details
* URL: https://beta.fec.gov/data/committee/C00610436/?cycle=2016&amp;tab=receipts
* User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by noahmanger** [comment]
Moving this from the feedback repo. To refresh from the Slack conversation we had around this: the issue  I believe is that the data on the receipts pages for this committee is not showing up at all, despite having reported itemized receipts.

**Comment by LindsayYoung** [comment]
Do you mind if we close this and move this to #1716?
