### ISSUE TITLE
When seeking filing deadlines, users routinely go first to Registration & Reporting

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1721]
Users routinely seek out filing deadline information by going first to the registration and reporting, rather than calendar where this information is. This finding is robust across a few weeks of testing. [tested 6-9](https://github.com/18F/FEC/blob/master/test_scripts/2016-6-9.md) 

Possible fixes
🔧 Create prominent pathways from registration and reporting to calendar deadlines

🔧 Clarify interlinkages between candidate and candidate data; enhance committee links to candidate --- particularly apparent in mobile. The fix?: Collapse some information in mobile that appeared overlooked by testers today

🔧 Interlinkages between candidate and candidate data (whether the candidate data is in the committee or candidate advanced data table )

🔧 (?) Visual difference between a link that take you to a profile page, and links that take you to a data table

**Comment by noahmanger** [comment]
Just noticed that it looks like a the last three 🔧 are for a different issue.
