### ISSUE TITLE
Advanced data table filter panel mobile usability findings 

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1726]
This issue has a couple of related usability findings on the advanced data tables filters:

1. Once users have added filters they did not close the panel, it was not clear that the filter panel could be closed. This led users to think they had to reset the filters in order to add more. [tested 6-9](https://github.com/18F/FEC/blob/master/test_scripts/2016-6-9.md)

  - :wrench: Make sure the process (order/placement) of using filters and tags : a. Feels like it's part of the same tool, and b. reflects the process that users would go through in using it [desktop & mobile]

2. Users interpreted the call to action on the page as export data, as it is the largest button. [tested 6-9](https://github.com/18F/FEC/blob/master/test_scripts/2016-6-9.md) 

3. Users did not necessarily understand that the results were updating upon changing filters, as this was happening off-screen with no discernable alert.[tested 6-9](https://github.com/18F/FEC/blob/master/test_scripts/2016-6-9.md)

4. On desktop (as well as mobile, see above) users did not necessarily see when a small results set was shown from their position down screen. [tested 6-9](https://github.com/18F/FEC/blob/master/test_scripts/2016-6-9.md) 

  - :wrench: Differentiate between results state and no-results state and an error state

tagging: @noahmanger @jenniferthibault 
[research repo: advanced data tables](https://github.com/18F/FEC/blob/master/feature_sets/advanced_data_tables.md)

**Comment by jenniferthibault** [comment]
Changes to improve this experience were included in the [August 3rd release](https://github.com/18F/FEC/blob/master/release_notes/release_notes.md#august-3-2016-release-notes) and [August 17th release](https://github.com/18F/FEC/blob/master/release_notes/release_notes.md#august-17-2016-release-notes)
