### ISSUE TITLE
Home button not obvious on mobile

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1732]
One tester noted they couldn't find their way from the advanced data tables screen to the mobile home screen. While this finding was not replicated across other users, the issue was problematic enough and the design change of making a more evident home pathway was non-controversial in synthesis. 

🔧 Add home as a discrete link on the mobile menu.

[Navigation feature set in research repo](https://github.com/18F/FEC/blob/master/feature_sets/ia_primary_nav_menu.md)
tagging: @jenniferthibault @noahmanger @jeanninehunter @emileighoutlaw @edmullen as likely interested parties.

**Comment by jenniferthibault** [comment]
Great writeup 👏
