### ISSUE TITLE
Content for overview pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC#1733]
Document here: https://docs.google.com/document/d/1oWFr-pK--tccSOIhEDZpa-1Pfxddwm_5Clqbqgr8FYI/edit

Related to: https://github.com/18F/openFEC/issues/1656#issuecomment-226357839

**Comment by emileighoutlaw** [comment]
I've been tweaking the content, but I don't actually think there's a ton that you need from me for the main content. So I'm pulling it out into this issue directly, so you don't have to hunt around in Google Drive.

My content recommendation:

> **Who’s raising the most**
> How much _candidates_ for _president_ have raised.

> **Where individual contributions come from**
> The individuals* who have contributed to _all candidates and committees_.

> **The size of contributions** 
> A breakdown, by size, of how much _PACs_ that are _super PACs_ have raised.



_Last thing,_ does anyone have any objections to something more along the lines of:

> **You might also like:**

(as opposed to _Where can I go to learn more?_)



cc @jenniferthibault @noahmanger

**Comment by jenniferthibault** [comment]
Thanks Emileigh! Admittedly, I have not been 100% responsive to content issues this week, but that will change now that I can pull my head out of the design direction sand.

👍  to "You might also like" , it's in the latest mockups.

The middle one is still a little off to me, because we're showing a list of states and a map. This version makes me expect a list of names. Would you be up fortinkering on that @emileighoutlaw ?
> **Where individual contributions come from**
> The individuals* who have contributed to all candidates and committees.

**Comment by emileighoutlaw** [comment]
Oh great point. How about something like:

> **Where contributions come from**
> A state-by-state breakdown of individual* contributions to _all candidates and committees_.

**Comment by jenniferthibault** [comment]
👍 

We need to address the titles on the Spending overview. I don't think I'll be able to get them into the demo in time, so I'll caveat that the exact wording of the questions aren't 💯 
Here's what we have now:

> **Who's spending the most**
> Amount spent by _candidates_ for _president_

> **How groups spend operating expenses**
> Operating expenditures by _all groups_

> **Where groups make independent expenditures**
> Locations of independent expenditures by _PACs_ that are _super PACs_

**Comment by emileighoutlaw** [comment]
Yeah, that's a good call. I still need to think about this wording anyway. I'll start working and let you know when I have a draft ready to review.

**Comment by emileighoutlaw** [comment]
Heyyyyy, taking into account the feedback from FEC yesterday, what do you think of:

> **Who's spending the most**
> How much _candidates_ for _president_ have spent.

> **Operating expense breakdown**
> See how _all groups_ account for operating expenditures.

> **Where groups make independent expenditures**
> A state-by-state breakdown of independent expenditures made by _PACs_ that are _super PACs_.

**Comment by jenniferthibault** [comment]
👍 on 1 and 3 (spending/IE's)

2: Operating expense breakdown feels more opaque to me, and less declarative than the rest of the bunch. How might we transform this in to a Who/what/where/when format that guided these at the outset? I'm also not sure what we mean by `account for` here. Account like Accounting? Or break down?

**Comment by emileighoutlaw** [comment]
Yeah, I know that one's the most weak, but it's such a technical thing I'm struggling to make it more plain language-y.

We could go with something that takes "operating expenditures" out of the title entirely, like:

> **Day-to-day expenditures made by committees**
> See operating expenditures for _all groups_.


The day-to-day bit should be okay, because it's straight from the campaign guide.

**Comment by jenniferthibault** [comment]
What about: 

> **What funds are spent on**  | OR |  **What money is spent on**
> See operating expenditures* for _all groups_   | OR |   See day-to-day operating expenditures* for _all groups_

This feels like it's distilled down to the simplicity of the others, and gives us the chance to define operating expenditures with the glossary.

**Comment by emileighoutlaw** [comment]
I'm worried that would be misleading, because operating expenses are just a small slice of what funds/money are spent on. I wouldn't want people to think that was a full picture of where all funds are directed. 

If we need more action-oriented language, we could try something like:
> **Understand operating expenses**
> Day-to-day expenditures made by _all groups_.

> **Visualize operating expenses**
> Day-to-day expenditures made by _all groups_.

> **View operating expenses**
> Day-to-day expenditures made by _all groups_.


This one might be more contentious with our partners, but we could also try something like: 
> **What it costs to run a committee**
> Operating expenditures for _all groups_.

**Comment by emileighoutlaw** [comment]
No I so much appreciate getting to pair with you on this! I added the operating expenditures as a glossary term, so we can link to it now from our subhead. What do you think of:

> **What is spent on day-to-day operating activities?**
> Operating expenditures for _all groups_.

**Comment by jenniferthibault** [comment]
Yes! Though we'd make it declarative to match, right?

> What's spent on day-to-day operating activities
> Operating expenditures for all groups.

Are we in a good spot to check it w/ Amys?

**Comment by emileighoutlaw** [comment]
Yes! (duh to declarative.) 

We can gut check this with @amypike (as Amy K. is out). 

Amy P., do you have any reason to think a chart with this title would raise red content flags?

>**What's spent on day-to-day operating activities**
> Operating expenditures for all groups.

We'd add a glossary definition link on "operating expenditures"

**Comment by amypike** [comment]
Hi @emileighoutlaw @jenniferthibault!  I think this looks good.  I would, however, say "operating expenditures for all *committees* or *entities registered as political committees with the FEC* (too lawyerly?) instead of *groups* because only registered political committees report operating expenditures.  A group that finances an IE (but is not a committee, for example) does not report operating expenditures.   Ditto for a group that finances an EC.

**Comment by emileighoutlaw** [comment]
I think _all committees_ would work fine. We'd have

> **What's spent on day-to-day operating activities**
> Operating expenditures for _all committees_

And then the drop-down for all committees would like this, I think?

> - _all committees_
> - _candidate committees_
> - _PACs_
> - _super PACs_
> - _party committees_
> - _separate segregated funds (SSFs)_

**Comment by jenniferthibault** [comment]
This was auto-closed by a pull request, but I'm not sure if it's done. Re-opening  so it doesn't get lost

**Comment by emileighoutlaw** [comment]
I do think this is finished and approved by FEC. Closing now. If there are new content questions with these views, I will happily open a new issue.
