### ISSUE TITLE
Treejack usability findings (6/16/16)

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC#1734]
## Results overview
- Test ran June 10–15
- 58 people completed 
- Test was 4 tasks
- Test took less than 3 minutes (on average) to complete

I'm including screenshots of all four tasks and results analysis. (Click each image to see a larger view)
**1.**
![screen shot 2016-06-16 at 10 25 41 am](https://cloud.githubusercontent.com/assets/10552702/16120934/4c74c806-33af-11e6-8938-3b34c1cde522.png)
**2.**
![screen shot 2016-06-16 at 10 25 47 am](https://cloud.githubusercontent.com/assets/10552702/16120939/508af97e-33af-11e6-94fe-e1578bd7a1ef.png)
**3.**
![screen shot 2016-06-16 at 10 25 52 am](https://cloud.githubusercontent.com/assets/10552702/16120947/546ef7ac-33af-11e6-9daf-023b703577d1.png)
**4.**
![screen shot 2016-06-16 at 10 25 57 am](https://cloud.githubusercontent.com/assets/10552702/16120948/566626b6-33af-11e6-97f0-8a01d4419256.png)

## Results synthesis
_Very broad:_ tasks 1 and 2 had lower success rates than tasks 3 and 4. Our top-level hierarchy is most important, because that gets users closer to the right answer. 

**Task 1:** The "incorrect" answers people selected led us to conclude that the question itself was overly broad— people weren't necessarily going down wrong paths; they had different interpretations of what materials were necessary to stay "up to date" with FEC events. For examples, some people went to advisory opinions for updated information. This would be a valid path for a legal researcher to follow.

**Task 2:** The most common incorrect paths were through **Campaign finance data**, **Legal resources**, and **Education and training**.

**Task 3:** Testers were largely successful but split in whether they looked in **Legal resources** or **Enforcement**. This seems to confirm strongly our decision to include enforcement within **Legal resources** as well as on its own as a top level navigation item. 

**Task 4:** Our most successful task, users also completed this task the fastest (~15 seconds). The most common pathway was through **FEC activities**, with **Calendar** and **Education and training materials** in second place, garnering roughly the same number of clicks.

## Fixes
🔧 Create prominent pathways from data to legal content

🔧 Create prominent pathways from data to registration and reporting content

🔧 Rename "Education and training" category and "Policy and guidance" category to be more specific

## Next steps
- [ ] Revise the hierarchy and retest. Include new questions that test other areas of the hierarchy.
- [ ] Build a treejack based on the current FEC.gov hierarchy and test that (for baseline information).

**Comment by emileighoutlaw** [comment]
@amykort and @amypike— here are the results from our information architecture test. I'd love to share it out with a wider group of folks at FEC, if you think that would be helpful. :)

(also cc @jenniferthibault, @noahmanger)

**Comment by AmyKort** [comment]
Awesome!! Let's plan to share this out.

**Comment by emileighoutlaw** [comment]
Woohoo! Is there a format that would be best for me to get this to you? PDF okay?

**Comment by AmyKort** [comment]
pdf is great!
