### ISSUE TITLE
RAD analyst endpoint

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1740]
So that API users can find the RAD analyst associated with a particular committee, create an endpoint that returns RAD analysts by committee ID.

**Criteria for completion:**
- [ ] API client can send a `committee_id` to the endpoint and receive an analyst name in response

Requested week of the 27th or the week of the 4th

**Comment by noahmanger** [comment]
I updated the original comment with a more proper story and criteria for completion. Is that accurate? Or is there more this endpoint needs to be able to do?

**Comment by LindsayYoung** [comment]
Yea, I made the analysts name searchable while I was in there, and added tests. It's ready for review
