### ISSUE TITLE
Add missing filters and fields to committees totals endpoint

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1742]
So that users can see the top raising and spending PACs and party committees, add the necessary API functionality to support the "Top Lists" on the new data landing page:

![image](https://cloud.githubusercontent.com/assets/1696495/16166325/37568af4-349f-11e6-8352-96c602e41c0c.png)

I believe that the `/totals/{committee_type}` [endpoint](https://api.open.fec.gov/developers/#!/financial/get_totals_committee_type) is what we want to use for this, but it's missing some necessary functionality.

**Criteria for completion:**
- [x] API endpoint supports requests for multiple committee types (e.g. `committee_type=N&committee_type=P`). Necessary in order to get, say, all PACs
- [x] API endpoint supports sorting by total receipts
- [x] API endpoint supports sorting by total disbursements
- [x] API response includes committee name

**Comment by noahmanger** [comment]
Updated this issue with more description.

**Comment by LindsayYoung** [comment]
For the fist chart, we would want something more like the /elections/ endpoint because we need the candidates totals to come form multiple committees in some cases. https://api.open.fec.gov/developers/#!/financial/get_elections

Though, I think it might be better if we can keep those totals by office and have people select which office they want to see, unless that feature is going to be on a different page. Because, running for president is on a different scale than running for Senate or House and we would want a way for people to get the overviews for those offices too.

**Comment by jontours** [comment]
Unless I'm crazy, think I found maybe an issue in how the parameters are parsed in the api for that endpoint.  Because, if you trace the code, the parameters passed via the url arguments are then used as the key to a dict, from line 22 in webservices/common/models/reports.py:

reports_type_map = {
    'house-senate': 'H',
    'presidential': 'P',
    'ie-only': 'I',
    'pac-party': None,
}

However based on the example provided: committee_type=N&committee_type=P.

So, in order for this code to work how it seems to have been coded, the arguments should be, e.g. "presidential".  In fact, that map isn't even needed.  Since it seems the values in the map are what was sought after.

**Comment by LindsayYoung** [comment]
These are currently divided by the forms they file on because the different forms produce different schemas:
  f3 - House and Senate candidates
  f3p - Presidential
  f3x - Pacs and Parties

**Comment by jontours** [comment]
So those should map to the P, H, S, and N arguments?    Regardless of what arguments are passed (P, N, etc) on the api they are all resolving, to the default schema and model: 

`default_schemas = (models.CommitteeTotalsPacParty, schemas.CommitteeTotalsPacPartyPageSchema)`

I'm assuming this was not intended right?

**Comment by noahmanger** [comment]
@LindsayYoung the "top candidates" figure is using the same end point as the candidate office totals pages are (e.g. https://beta.fec.gov/data/candidates/president/ ) which should be totaling amounts from all authorized committees.

Re: filtering by office, yeah, that feature actually is reserved for another page. With these you can't see beyond 5, and it's really just here to A) give people something immediately actionable by surfacing entities with a lot of activity B) illustrate what is included in the three respective categories.

**Comment by jontours** [comment]
@noahmanger "With these you can't see beyond 5"

Unless I'm mistaken I don't think that's currently working.  Regardless of what argument is passed in, the api resolves to this model: models.CommitteeTotalsPacParty.  So for example, if an API client passes in the 'P' or 'H' flag, they are returned the CommitteeTotalsPacParty model.  So in reality only results for 1 model is being returned, assuming the user passes in those 'P' or 'H' codes for type.  However, if they passed in 'presidential', they would see committee totals for the presidential type.

**Comment by jontours** [comment]
Sorry for beating a dead horse on this, want to make sure I understand it.

**Comment by LindsayYoung** [comment]
Let's see if I am understanding:
We need 3 overviews candidate, pac and party.
The candidate overview is taken care of in the `/candidates` endpoint.

The task we need to accomplish is adding an extra field that filters to just show PACs or parties on the `committee/totals/pac-party` endpoint.

Does that sound correct to everyone?

Also, @noahmanger thanks for the answer about office!

**Comment by noahmanger** [comment]
☝️ Yes, we just need new capabilities for the `committee/totals` endpoint. An @jontours I'm less familiar with the API code, but I think what I see you saying is exactly what we need to address. 

For the "Top PAC raisers / spenders" figure we need to include committees that meet one of multiple types of committee types. Correct me if I'm wrong, but we don't have a single flag for "PACs"; instead PACs is a general term that includes committees of various types: Q, N, etc. And same for party committees.

I'm agnostic as to how the API handles that.

**Comment by jontours** [comment]
Ah okay, I think I see what you are saying.  I think the reason I got confused was that the committee types in the data are currently represented as one character strings: H, S, P etc.  But the API was implemented such that the parameters were the unabbreviated form: "house-senate" for 'H', 'presidential' for 'P'.  Which is different than other parts of the API (I think).

**Comment by LindsayYoung** [comment]
Yea that is confusing. Those strings are only used in that model as abbreviations, they are not really codes. 

I would be up for changing them if there are things that would make sense. I would abbreviate with f3, f3p and f3x, but maybe you can thing of something more straight forward?

**Comment by LindsayYoung** [comment]
@PaulClark2 or @jwchumley 

What committee codes should be included under the  PAC umbrella?
What committee codes should be included under the party umbrella?

**Comment by noahmanger** [comment]
If it helps, here's a PR where the candidates list is implemented: https://github.com/18F/openFEC-web-app/pull/1290

Most of the work is already into develop, that PR just starts to expose it. I'm open to other was to do it, but here's what I set up currently:
- Added an `api_caller.py` [function](https://github.com/18F/openFEC-web-app/blob/develop/openfecwebapp/api_caller.py#L148) to get top candidates, sorted by a parm (either `-receipts` or `-disbursements`)
- [A macro](https://github.com/18F/openFEC-web-app/blob/develop/openfecwebapp/templates/macros/overviews.html#L51) parses the response to create the lists

**Comment by jwchumley** [comment]
Party is X and Y

PAC is messier and we should probably discuss whether we want to treat 
traditional PACs differently from the various newer forms (Carey, Super 
etc) but here they are:

N
Q
O
V
W

I think that's all of the relevant ones. It depends on what you are doing 
with them as to which ones you use. For big picture numbers from "PACs" 
user them all

**Comment by PaulClark2** [comment]
@jontours `'ie-only': 'I',` committee type "I" is a "persons other than a political committee independent expenditure."  Committee type "O" is IE only (Independent expenditure-only political committee).


Code |	Description 
----- |----
C |	COMMUNICATION COST
D |	DELEGATE
E |	ELECTIONEERING COMMUNICATION
H |	HOUSE
I |	INDEPENDENT EXPENDITURE - PERSON OR GROUP NOT A COMMITTEE
N |	NON-QUALIFIED NON-PARTY
O |	INDEPENDENT EXPENDITURE-ONLY COMMITTEE
P |	PRESIDENTIAL
Q |	QUALIFIED NON-PARTY
S |	SENATE
U |	SINGLE CANDIDATE INDEPENDENT EXPENDITURE COMMITTEE
V |	NON-QUALIFIED NON-PARTY WITH NON-CONTRIBUTION ACCOUNT
W |	QUALIFIED NON-PARTY WITH NON-CONTRIBUTION ACCOUNT
X |	NON-QUALIFIED PARTY
Y |	QUALIFIED PARTY
Z |	NATIONAL PARTY ORGANIZATION. NON FED ACCT.

**Comment by jontours** [comment]
#1772, pull this branch to test out current implementation.  The endpoint now filters as before, with the addition of "pac" and "party" path parameters, eg. pacs sorted by receipts -> http://localhost:5000/v1/totals/pac/?per_page=20&sort=-receipts&page=1

**Comment by noahmanger** [comment]
Resolved!
