### ISSUE TITLE
Content feedback for raising and spending overviews

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC#1746]
For feedback on the mockups. 

Related to: https://github.com/18F/openFEC/issues/1703
Related to: https://github.com/18F/openFEC/issues/1656

**Comment by AmyKort** [comment]
DATA LANDING OVERVIEW

Elections by Location
Is there a word missing from the description? Or should it just be “Compare elections and candidates running in them by zip code or state.”

Raising Overview
“This chart shows total receipts for the past year. Receipts include contributions and any other funds received by a committee.” Or, just link to glossary definition for receipts.

Spending Overview
(Is this supposed to be expenditures or disbursements? If it is the counterpoint to receipts, it should be disbursements, not expenditures. Disbursements include any payment or purchase made by a committee. Expenditures only include money spent to influence a federal election (so, for example, a charitable donation would be a disbursement, but not a contribution).

“This chart shows total disbursements for the past year. Disbursements include all payments and purchases made by a committee.” Or just link to glossary definition for disbursements.

PAC Overview
Top raising PACs (the s should be lowercase)

**Comment by AmyKort** [comment]
At the bottom for "you might also like," the Spending Overview maybe should just say "how committees spend their funds.

**Comment by AmyKort** [comment]
Oh wait, did I move to a page that's not part of this thread? That's the drill down page.

**Comment by AmyKort** [comment]
On the spending overview: I think it is odd to say groups spend operating expenses. Do you spend expenses? Maybe you do . . . just not in Nebraska :8ball: 

Either way, we can link to the glossary definition of operating expenditure, and I think that will help folks out.

**Comment by emileighoutlaw** [comment]
@amykort How about this for the **data landing overview**? This should take into account your notes here and Cheryl's notes in the InVision mock-up.

If it's good, we'll give to @jenniferthibault and @noahmanger for implementation. (I'll keep working on spending overview content separately):

> **Elections by location**
> Find elections near you— search by state or ZIP code.

> **Raising overview**
> This chart shows total receipts* for the past year. Receipts are any funds received by a committee, including contributions.

> **Spending overview**
> This chart shows total disbursements* for the past year. Disbursements include all payments and purchases made by a committee.

**Comment by AmyKort** [comment]
Looks good to me!

**Comment by emileighoutlaw** [comment]
@jenniferthibault @noahmanger looks like we have just a few small tweaks for the data landing content:

> **Elections by location**
> Find elections near you— search by state or ZIP code.

> **Raising overview**
> This chart shows total receipts* for the past year. Receipts are any funds received by a committee, including contributions.

> **Spending overview**
> This chart shows total disbursements* for the past year. Disbursements include all payments and purchases made by a committee.


Let me know if there's somewhere more helpful I can put this.

**Comment by AmyKort** [comment]
One more edit:

Raising overview
This chart shows total receipts* for the past year. Receipts include all money, goods, services or property received by a committee.

**Comment by emileighoutlaw** [comment]
Sounds good!

**Comment by emileighoutlaw** [comment]
Closing this. Happy to open a new issue if new content questions arise.
