### ISSUE TITLE
Rename receipt_date field on schedule A and B

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1750]
In order for users of the API and people who download the data to better understand what the fields / columns mean, rename `receipt_date` on the schedule A and B endpoints to `report_receipt_date`.

**Criteria for completion:**
- [ ] Add a new column to schedule A endpoints for `report_receipt_date`
- [ ] Add a new column to schedule B endpoints for `report_receipt_date`
- [ ] If possible, hide the old `receipt_date` column in downloads in order to reduce confusion

The original `receipt_date` fields should remain on the API so we don't break things, but should eventually be deprecated after notifying API users and allowing for a grace period.

**Comment by LindsayYoung** [comment]
Actually,  `receipt_date` is going away with the table switch.

**Comment by noahmanger** [comment]
Will it be replaced by `report_receipt_date`?

**Comment by LindsayYoung** [comment]
The current plan is for it to go away in the schedules.

**Comment by noahmanger** [comment]
So there won't be a column for `report_receipt_date`? Will there be any equivalent in the new tables?

**Comment by LindsayYoung** [comment]
You bring up a good point, since we won't have that, we will want to index file_number and add it as a filter to the /filings endpoint so people can easily look up that date.

**Comment by noahmanger** [comment]
👍  I'm going to close this issue then.
