### ISSUE TITLE
Migrate NML_FORM_76

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1789]
In order to have the most up-to-date data, migrate the line-item expenditures for communication costs off the data warehouse.

**Completion criteria:**
- [x] Data warehouse table replaced with new one

**Comment by jontours** [comment]
@LindsayYoung Should I be looking in `communication_cost.sql` and `communication_cost_by_candidate.sql` for the migration?  And is the old warehouse table for this `communication_costs_vw`?

**Comment by LindsayYoung** [comment]
Yep you got all the details right.  We want to replace 'communication_costs_vw' with 'nml_form_76' in  `/data/sql_updates/communication_cost.sql` Feel free to follow up if it is not as straight forward as we think it will be.

**Comment by jontours** [comment]
Need to point the endpoint model to the correct data table.  Most work _should_ be done.
