### ISSUE TITLE
Create reports data table pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1790]
In order to more easily browse the definitive version of reports for committees, create separate reports views for each main type of report.

**Completion criteria:**
Use existing reports endpoint to create the following views:
- [x] Add data table for presidential reports (form 3P)
- [x] Add data table for house and senate reports (form 3)
- [x] Add data table for PAC and party reports (form 3X)
- [x] Add data table for IE only reports (form 5)

Each page will need to:
- [x] Have the correct filters for that report type
- [x] Link to the committee from the committee column
- [x] Include the necessary fields in the details panel for each report type

Also: 
- [x] Add links from the menus
- [x] Add links from the advanced data page
- [x] Link from totals to reports queries
- [ ] Create a way to tell what amended what (might be tricky)

(Keep an eye on how this fits in overall site IA.)

**Comment by noahmanger** [comment]
Additionally, it would be nice to use the same templates for the details panels for these reports as we do for the filings. I'm finding some inconsistency with the way that variables are named, though, that requires us to use different templates. If it's an easy enough fix, great, but I just wanted to capture them here:

- On filings, we have `document_description`, but on reports, we have `form_type_full`
- On filings, we have `amendment_indicator`, on reports we have `is_amended`

There might be more, but those are what I'm catching.

**Comment by noahmanger** [comment]
Oops. I meant to post that on the API issue. Cross-posting.

**Comment by noahmanger** [comment]
I've been spending some time with the details panels for the reports, and the more I look at them, the more it feels like we're lacking a rhyme or reason for what goes in there. Reports have a lot of information, and our goal isn't to include all of it in the details panel. But how do we determine what we do include? I'd like to come up with a better set of rules.

**Comment by LindsayYoung** [comment]
I think you are right about the panels, but before we start pairing things down, we might need it an html view of the report. (And a beta.fec.gov pdf browser view for the reports too.)
