### ISSUE TITLE
Test expectations around overview interactions with static prototypes

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1792]
After answering info viz and interaction design questions, test the static comps with users to validate user expectations around interactions.

cc @onezerojeremy @ethanheppner @jenniferthibault

**Comment by jenniferthibault** [comment]
InVision prototypes:

Desktop: https://invis.io/KH7TNKQEB#/170607544_Data-Landing-Overview
Mobile: https://invis.io/R97U6AEAU#/171023868_Landing-Mobile-Raising

**Comment by onezerojeremy** [comment]
test script here: https://github.com/18F/FEC/blob/master/test_scripts/2016-07-07.md

2 users scheduled.

**Comment by onezerojeremy** [comment]
Update on this one: 
We've tested this with three users over the last two weeks. For the hurdles uncovered, I'm tagging @jeanninehunter & @ethanheppner, who have a better idea of the detailed findings after we re-run the tests this week and synthesize.

**Comment by noahmanger** [comment]
I believe we're just waiting on capturing findings for this issue to close it. Is that on @ethanheppner , @jeanninehunter or @onezerojeremy ?
