### ISSUE TITLE
Improve instructions for usability testing rig

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1794]
Improve the instructions for running the usability testing rig and share with the FEC.

**Completion criteria:**
- [x] Refine [instructions](https://docs.google.com/document/d/1XQMYrFJuDqww0MwrJHxfvh3xrm7EIjscjOCFF0fs0gA/edit)
- [x] Test instructions internally 
- [ ] Finalize instructions in 18F pages
- [ ] Share instructions with FEC

**Comment by ethanheppner** [comment]
Visual instructions in progress here-- goal is to finish by Wednesday at noon before vacation:

[How to recruit](https://docs.google.com/drawings/d/1x-oc5eMaBMK13hOzSRHKuZDnY2SwmSn62Nq6mm65OVg/edit)
[How to set up Hangouts rig](https://docs.google.com/drawings/d/16mRfEU-KdDmUjMs4rBcrm7pZossVZ8xvtxv6f52Z55U/edit)
[How to set up join.me rig](https://docs.google.com/drawings/d/18YwOa_tTwcuq-uJaNQl48Jm3livWAX2aInb5NSt-4z8/edit)

**Comment by jeanninehunter** [comment]
The plan is to conduct an internal test of the instructions during the week of August 8 before shipping to FEC earlier the following week. @ethan @noahmanger

**Comment by ethanheppner** [comment]
Internal test successful! Will be transferring over to Pages in Sprint 21, @nickykrause and I will discuss how we want to split up usability recruiting and how to transition process to FEC.
