### ISSUE TITLE
Fix container rendering bug

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#181]
Sometimes when a page loads the content is at full width instead of a fixed container. Refreshing the page fixes this. Not sure what's going on, but maybe @theresaanna does?

**Comment by noahmanger** [comment]
I cannot figure this out. @theresaanna can you take a look if  you have a chance?

**Comment by LindsayYoung** [comment]
@noahmanger is this fixed?

**Comment by noahmanger** [comment]
I _think_ this is fixed now.
