### ISSUE TITLE
Sort broken on /elections

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1819]
I assume it is the same sqlalchemy bug. :(

I used it for my class this week and had to re-write the lesson to use the `candidates/totals` endpoint with extra calls instead. 

We should also document `candidates/totals` it is not included in the API documentation.

**Comment by jontours** [comment]
I can look into doing the documentation.

**Comment by noahmanger** [comment]
Is this related to https://github.com/18F/openFEC-web-app/issues/1355 ?

**Comment by noahmanger** [comment]
Oops. Just saw @LindsayYoung already made that connection 😎

**Comment by jontours** [comment]
PR for this here: https://github.com/18F/openFEC/pull/1825

**Comment by ccostino** [comment]
@jontours finished the API fix and it's been merged!  It looks like all that's left is the documentation piece?

**Comment by jontours** [comment]
Yes the documentation is for the candidate totals endpoint.  I'll be taking a look at that today.

**Comment by LindsayYoung** [comment]
In case you haven't done that before, you will want to register it in rest.py and do a quick check it has things defined https://github.com/18F/openFEC/blob/develop/webservices/rest.py#L271

**Comment by jontours** [comment]
Thanks @LindsayYoung !
