### ISSUE TITLE
Indicator that a filing is paper-only, not electronic

### ISSUE THREAD

**Issue by dwillis** [18F/openFEC#1824]
For committees that file both electronic and paper reports ([here is an example](http://www.fec.gov/fecviewer/CandidateCommitteeDetail.do?candidateCommitteeId=C00616144&tabIndex=3)), it would be very useful for the API to indicate whether a particular filing is electronic or paper. Right now, filing objects in the API have no such way to tell. By looking at a committee's page you can tell that a filing is paper-only if there is no HTML version posted.

One way to accomplish this would be to add a `filing_id` attribute that represents the ID of the electronic filing to the filings responses. A null value would indicate a non-electronic filing.

**Comment by LindsayYoung** [comment]
Yes, we are working on switching the table source for filings so we have the image_id and filing_id for the filings endpoint.

**Comment by dwillis** [comment]
Thanks!

**Comment by LindsayYoung** [comment]
Thanks for the follow up and the issues!

I am hoping the new filing table will solve some issues like this, it has
the has the filing_id. Here is the issue, we will probably start next
sprint https://github.com/18F/openFEC-web-app/issues/1371

In the meantime, can you send me examples of .fec files that are not
formatted correctly. I am trying to get that fixed and some examples could
go a long way.

Best,
Lindsay

**Comment by noahmanger** [comment]
We have the means to do this now. Here's the steps for completion:
- [ ] Include a parameter for `means_filed: paper` or `means_filed: electronic` returned on `/filings/` and `/reports/` 
- [ ] Add a filter to `/reports/` and `/filings/` for this parameter
- [ ] Include the flag on the front-end on filings and reports pages

**Comment by noahmanger** [comment]
Took a little while but we just shipped this @dwillis ! API responses now have a `means_filed` property that either has `paper` or `e-filing`. Hope that helps!
