### ISSUE TITLE
Unify text input filter patterns

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1828]
As we're implementing progress indicators for the text inputs, now's a good time to address another slight inconsistency in our text input filter patterns. In addition to the typeahead filters, which provide suggestions by searching against a particular dataset, these inputs just accept free text, without making suggestions.

Type 1:
![image](https://cloud.githubusercontent.com/assets/1696495/16933290/030c73b0-4d01-11e6-9989-65c8c5ecc5bf.png)
- Plain old text input
- Only accepts one value
- Doesn't create a checkbox

Type 2: Free-text-only typeahead
![type 2](http://g.recordit.co/FPAdgb2uEL.gif)
- An instance of the `TypeaheadFilter` class that only accepts free-text input
- Used when a filter can accept multiple values (used on the [Individual Contributions](https://beta.fec.gov/data/receipts/individual-contributions) page)
- Turns a text value into a checkbox

Note: whether or not a filter accepts multiple values is based on the API. Things can certainly be changed on that end, but it requires additional API work, which we're currently trying to avoid.

Some questions:
- Given the new validation styles are adding a button to the Type 1 inputs, do we want those icons to be the same or different?
- Do we want to do away with Type 2 in favor of just using Type 1 to generate a checkbox? It could do this in all instances, but if it's a filter that only accepts one value, it could make the input disabled if there's a checkbox already applied

CC @jenniferthibault @onezerojeremy @xtine

**Comment by onezerojeremy** [comment]
Little slow on this, but here are my recs. Basically I like your idea of going with type 1 to enter a text box, since in the new filters world, each input will have a trigger (therefore, the "search for" contextual menu doesn't seem as necessary).  The one thing I think I'd do is that instead of disabling the input, I think it might make for a better experience to disable the first checkbox when a user submits a second. Like this:
![text fields](https://cloud.githubusercontent.com/assets/474916/17252788/f3b8c6b0-557b-11e6-9a1c-a52b6038b18b.png)


Note that i've also added a strikethrough on unchecked checkbox tags. Might be able to get away without it, but I think it might help keep the user in the loop a bit more about what's happening. It's also entirely possible (likely even) that a different visual effect of the fact that a given checkbox tag is no longer applied is better.

**Comment by jenniferthibault** [comment]
A few rambling thought > hypotheses > suggestions:

- If you can only select one, would it be more accurate to make it a radio button than a check box? (hypothesis: yes)
- if it's text a user puts in, and we don't offer typeahead matching to help with their spelling, should we use "quotations" to show text entered exactly as it was? (hypothesis, if a user spells something wrong, they may not realize it, but they might trouble-shoot in the tag or generated radio buttons)
- Is the fill color change on the radio button/check box background different enough to indicate the state change? (hypothesis: this + radio button will be a strong enough cue that you can only select one, and which one is clearly selected at that moment)

Suggestion based on ^ : 

<img width="305" alt="screen shot 2016-08-03 at 5 51 58 pm" src="https://cloud.githubusercontent.com/assets/11636908/17386818/01a71a58-59a3-11e6-90f9-fb275a013200.png">

**Comment by noahmanger** [comment]
@LindsayYoung seeing your issue https://github.com/18F/openFEC/issues/1867, what's the lift like to make any text input field the kind of field that can accept multiple parameters? We don't have a ton of them, but if we could make them all behave the same, it would make designing a consistent interaction a lot easier.

**Comment by LindsayYoung** [comment]
I think for city it is definitely worth it. Adding them everywhere would be ideal,  we would just need to check that we were not adding queries that would take too long to process for performance issues and keeping things up.

**Comment by noahmanger** [comment]
Cool. Code-wise, is it a pretty simple switch to just change the type of filter (performance monitoring aside)?

**Comment by LindsayYoung** [comment]
It should be a simple-ish code change with a larger benchmarking task.

**Comment by noahmanger** [comment]
👍 

Looking through the plain text filters we have, I only see these:
- Committee treasurer
- Contributor occupation
- Contributor city
- Contributor employer
- Payee city
- Disbursement description

The other text filters we have are all for min and max amounts, which I think should be treated as a separate pattern since it wouldn't make any sense to set multiple minimums or maxes. 

So my proposal is that from a design standpoint, we should approach all the non-range text filters the same and design an interaction that works for all. And then once we have capacity to implement backend changes, we can implement the frontend. How does that sound?

**Comment by noahmanger** [comment]
And for the financial range filters, do we want to act on @emileighoutlaw 's issue here? https://github.com/18F/openFEC-web-app/issues/1373

I'm interested in applying the date range style @jenniferthibault is exploring with the side-by-side filters in this case as well.

**Comment by jenniferthibault** [comment]
@noahmanger was that comment supposed to go on the date range issue? https://github.com/18F/openFEC-web-app/issues/1375

**Comment by noahmanger** [comment]
Kinda applies to both. I put it here because those are the only other text-type inputs we have in the filters, but they're notably different than the others I listed above.

**Comment by jenniferthibault** [comment]
Summarizing the team design critique on Friday: 
We should definitely approach all the non-range text filters the same (yay consistent experiences!) and generate a checkbox list with validation based on what the user enters. Each category should be able to have multiple filters applied. Here's the flow:

<img width="719" alt="screen shot 2016-08-08 at 12 04 56 pm" src="https://cloud.githubusercontent.com/assets/11636908/17487303/4be31e56-5d62-11e6-9833-84b236ac4e00.png">

**Comment by noahmanger** [comment]
So, I just checked the API and it sure looks like all of these fields already accept multiple parameters:
- Committee treasurer
- Contributor occupation
- Contributor city
- Contributor employer
- Payee city
- Disbursement description

I'll make a new issue for implementation.

**Comment by noahmanger** [comment]
Looks great @jenniferthibault . Closing this issue, with a new implementation issue over here: https://github.com/18F/fec-style/issues/457
