### ISSUE TITLE
is_individual

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#1832]
https://github.com/18F/openFEC/blob/bbfe794284c5ac78a2b1d5d8a2c3601c7a44fb40/data/functions/individual.sql

The current list of transaction codes for "is_individual" is incomplete and includes one transaction code "18J" that it should not include.

TRAN_CODE	|	TRAN_CODE_DESC
----	|	----
10	|	NON-FEDERAL RECEIPT FROM PERSONS
15	|	CONTRIBUTION
15E	|	EARMARKED CONTRIBUTION
15J	|	MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN
~~18J~~	|	~~MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN~~
30	|	CONVENTION ACCOUNT RECEIPT - INDIVIDUAL
30T	|	CONVENTION ACCOUNT RECEIPT - TRIBAL
31	|	HEADQUARTERS ACCOUNT RECEIPT- INDIVIDUAL
31T	|	HEADQUARTERS ACCOUNT RECEIPT - TRIBAL
32	|	RECOUNT ACCOUNT RECEIPT- INDIVIDUAL

The correct list of transaction codes for "is_individual" should be:  

TRAN_CODE	|	TRAN_CODE_DESC
----	|	----
10	|	Contribution to Independent Expenditure-Only Committees (Super PACs), Political Committees with non-contribution accounts (Hybrid PACs) and nonfederal party "soft money" accounts (1991-2002) from a person (individual, partnership, limited liability company, corporation, labor organization, or any other organization or group of persons)
10J	|	Memo - Recipient committee's percentage of nonfederal receipt from a person (individual, partnership, limited liability company, corporation, labor organization, or any other organization or group of persons)
11	|	Native American Tribe contribution
11J	|	Memo - Recipient committee's percentage of contribution from Native American Tribe given to joint fundraising committee
15	|	Contribution to political committees (other than Super PACs and Hybrid PACs) from an individual, partnership or limited liability company
15E	|	Earmarked contributions to political committees (other than Super PACs and Hybrid PACs) from an individual, partnership or limited liability company
15J	|	Memo - Recipient committee's percentage of contribution from an individual, partnership or limited liability company given to joint fundraising committee
30	|	Convention Account receipt from an individual, partnership or limited liability company
30T	|	Convention Account receipt from Native American Tribe
30J	|	Convention Account - Memo - Recipient committee's percentage of contributions from an individual, partnership or limited liability company given to joint fundraising committee
31	|	Headquarters Account receipt from an individual, partnership or limited liability company
31T	|	Headquarters Account receipt from Native American Tribe
31J	|	Headquarters Account - Memo - Recipient committee's percentage of contributions from an individual, partnership or limited liability company given to joint fundraising committee
32	|	Recount Account receipt from an individual, partnership or limited liability company
32T	|	Recount Account receipt from Native American Tribe
32J	|	Recount Account - Memo - Recipient committee's percentage of contributions from an individual, partnership or limited liability company given to joint fundraising committee

@LindsayYoung @ccostino @jwchumley

**Comment by ccostino** [comment]
Great, thank you @PaulClark2!
