### ISSUE TITLE
revisit Disbursements received from committees

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#1834]
https://fec-dev-proxy.18f.gov/data/committee/C00580100/?tab=between-committees

Conservative Action Fund did not give direct contributions to Trump for President. CAF passed earmarked contribution on to Trump for President.

beta:

| Committee | Total |
| --- | --- |
| TRUMP VICTORY | $2,201,313.93 |
| CONSERVATIVE ACTION FUND | $10,030.24 |
| NEVADA STATE DEMOCRATIC PARTY | $8,000.00 |
| GREAT AMERICA PAC | $6,234.00 |
| NEXSTAR BROADCASTING GROUP INC. POLITICAL ACTION COMMITTEE | $5,000.00 |
| PANCAKE POLITICAL ACTION COMMITTEE | $5,000.00 |
| TACO POLITICAL ACTION COMMITTEE | $5,000.00 |
| SALEM COMMUNICATIONS CORPORATION POLITICAL ACTION COMMITTEE | $5,000.00 |
| LONGHORN PAC | $3,000.00 |
| QSR LEADERS POLITICAL ACTION COMMITTEE INC | $2,700.00 |
| J. H. FLETCHER & CO. POLITICAL ACTION COMMITTEE | $2,700.00 |
| STRONG COUNTRY FOR TODAY AND TOMORROW (SCOTTPAC) | $2,500.00 |
| REPUBLICAN FEDERAL COMMITTEE OF PENNSYLVANIA | $425.00 |
| ALAMEDA COUNTY REPUBLICAN PARTY (FED) | $226.64 |
| INDIANA REPUBLICAN STATE COMMITTEE, INC. | $57.62 |

What I think it should be

| CMTE_ID | CMTE_NM | SUM(F.TRANSACTION_AMT) |
| --- | --- | --- |
| C00618389 | TRUMP VICTORY | $2,201,313.93 |
| C00321158 | SALEM COMMUNICATIONS CORPORATION POLITICAL ACTION COMMITTEE | $5,000.00 |
| C00330118 | TACO POLITICAL ACTION COMMITTEE | $5,000.00 |
| C00482463 | PANCAKE POLITICAL ACTION COMMITTEE | $5,000.00 |
| C00567388 | NEXSTAR BROADCASTING GROUP INC. POLITICAL ACTION COMMITTEE | $5,000.00 |
| C00402602 | LONGHORN PAC | $3,000.00 |
| C00496257 | J. H. FLETCHER & CO. POLITICAL ACTION COMMITTEE | $2,700.00 |
| C00560821 | QSR LEADERS POLITICAL ACTION COMMITTEE INC | $2,700.00 |
| C00560003 | STRONG COUNTRY FOR TODAY AND TOMORROW (SCOTTPAC) | $2,500.00 |
| C00044842 | REPUBLICAN FEDERAL COMMITTEE OF PENNSYLVANIA | $425.00 |

@ccostino @LindsayYoung @jwchumley

**Comment by noahmanger** [comment]
This view was removed in the last refresh to committee pages.
