### ISSUE TITLE
Add additional logging for partitioning

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#1838]
Our update process currently does not surface any information about the partitioning steps that may take place so we are unable to see where in the process it might be at any given time.  It would be good to add some logging statements around the following events:
- When partitioning for a particular table starts
- When a child table starts being processed
- When a child table finishes being processed
- When the partitioning for a table completely finishes

If anyone can think of any other events we should add logging for to increase visibility into what is happening during our update process, please feel free to add them!

**Comment by LindsayYoung** [comment]
That sounds good. Timestamps would be nice for each step too- I think that is what you already had in mind.

**Comment by jontours** [comment]
Maybe it would be possible to sense when indexes for a table have started and finished?  As that was particularly a problem yesterday.

**Comment by ccostino** [comment]
Both good suggestions!  I believe the timestamps are already included as a part of the logging statements but we should double check.

**Comment by LindsayYoung** [comment]
If it is not too hard to throw in, it would be nice to have a different email subject line when there is an error. 

maybe if there are no errors keep it he same:
FEC Update: dev | celery-worker
and if there is an error:
[ERROR] FEC Update: dev | celery-worker
