### ISSUE TITLE
Big discrepancy between money raised by state from schedule_a

### ISSUE THREAD

**Issue by hobbes3** [18F/openFEC#1839]
For example, I'm seeing a big discrepancy between the money raised for Trump by state between

https://api.open.fec.gov/v1/committee/C00580100/schedules/schedule_a/by_state/?api_key=DEMO_KEY

(just showing the top 10):

    State	        Total contributed
    California	    $511,060.10
    Texas	        $504,427.40
    Florida	        $482,277.56
    New York	    $333,749.76
    Massachusetts	$191,603.89
    Pennsylvania	$148,913.64
    Georgia	        $139,566.91
    New Jersey	    $132,496.71
    Illinois	    $120,563.57
    Virginia	    $119,082.93

and

https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&committee_id=C00580100

When I take all of schedule_a with `committee_id=C00580100` (Trump) and add up all of the `contribution_receipt_amount` by `contribution_state` I get a completely different result (just showing the top 10):

    contributor_state	raised	        count
    NY	                $46,537,108.05	1325
    DC	                $1,347,794.52	44
    CA	                $544,526.58	    1820
    TX	                $522,027.40	    1456
    FL	                $493,317.63	    1469
    MA	                $195,503.89	    421
    PA	                $159,223.04	    594
    GA	                $144,516.91	    493
    NJ	                $134,247.71	    576
    VA	                $133,412.57	    432

I'm also seeing overall discrepancies between aggregating all of schedules_a vs using the API endpoints to get the pre-aggregated statistics like `by_state`, `totals`, or `by_employer`. 

I'll appreciate any help or tips since I'm new to this data source. Thanks!

**Comment by LindsayYoung** [comment]
Hello , thanks for writing in!

For the by state totals our methodology is looking at individual, unique donors, rather than all receipts. For example, the huge difference in the DC total makes sense because many committees are based in DC.

To replicate the methodology you will want to use `is_individual=true`

Here is an example of Trump Vermont contributions that make up the total from Vermont: 

https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&committee_id=C00580100&contributor_state=VT&two_year_transaction_period=2016&min_date=01-01-2015&max_date=07-22-2016&sort=-contribution_receipt_date&per_page=30&is_individual=true

**Comment by hobbes3** [comment]
Thanks @LindsayYoung!

If I only looked at `is_individual=true` then I get results that (very closely) matches the `/by_state/` endpoint:

    contributor_state	raised	    count
    CA	                $528,760.10	1810
    TX	                $522,027.40	1456
    FL	                $491,277.56	1467
    NY	                $341,499.76	1199
    MA	                $195,503.89	421
    PA	                $155,173.64	593
    GA	                $143,266.91	488
    NJ	                $133,996.71	575
    IL	                $121,413.57	461
    VA	                $119,332.93	430

However now if I only sum up all of Trump's receipt where `is_individual=true` then I only get Trump raising $4,696,443.00. If I include all receipts then I get $52,307,545.60.

Could you please help me understand how to get the $64,576,403.60 amount from https://beta.fec.gov/data/candidate/P80001571/ or https://beta.fec.gov/data/committee/C00580100/?cycle=2016&tab=summary?

My closest guess is that I'm supposed to sum up all of schedule_a (including individual and non-individual) and then add the `individual_unitemized_contributions` from https://api.open.fec.gov/v1/committee/C00580100/totals/?api_key=DEMO_KEY. So

    (sum of all contribution_receipt_amount of schedule_a) + (individual_unitemized_contributions from committee totals)

    $52,307,545.60 + $12,489,932 = $64,797,477.6

However this approach completely fails for Hillary (`committee_id=C00575795`):

    $255,042,028.45 + $44,958,555 = $300,000,583.45 (reported to be $238,211,482.49)

https://beta.fec.gov/data/committee/C00575795/

**Comment by LindsayYoung** [comment]
Summary totals and itemized totals often do not match up. The summary numbers are more likely to be right, so we use them for candidate totals. If you are doing sub-aggregates, you have to use the itemized, schedule data. 

To look up summary numbers, you will want to use the [reports endpoints](https://api.open.fec.gov/developers/#!/financial).

Here is how you get the underlying data for the two-year totals:
Trump-
https://api.open.fec.gov/v1/committee/C00580100/reports/?is_amended=false&api_key=DEMO_KEY&cycle=2016

Hillary-
https://api.open.fec.gov/v1/committee/C00575795/reports/?is_amended=false&api_key=DEMO_KEY&cycle=2016




I also find looking at the form that the data comes from makes things make more sense: http://www.fec.gov/pdf/forms/fecfrm3p.pdf

**Comment by hobbes3** [comment]
Thanks Lindsay.

Could you help me understand why the itemized totals don't add up? Are the documents missing? Also even the total breakout by states ($10.6 million) doesn't add up to the total Trump contribution either ($64.5):

    $10,658,194.43=448.75+4209.9+92538.97+301492.41+3964.97+133984.32+500.0+810804.97+3510324.6000000001+398955.82+227841.0+61734.54+69066.18+2477613.8399999999+1724457.03+1944.28+81494.78+156481.23+97180.91+503155.93

If the itemized totals don't add up then what calculations are you guys using to get the summary total?

**Comment by LindsayYoung** [comment]
The summary information and the itemized information is filled in by the filer. Lots of filers are diligent about it, and some have trouble. When there is a large discrepancy, the Reports and Information Division will send a letter to the filer. Generally, it is a math mistake or some filings did not make it on the report and the report is amended later. 

Individual contributions that are $200 and under don't need to be itemized. If you expand total receipts on [the committee page](https://beta.fec.gov/data/committee/C00580100/) you can see that Trump has $24,599,294.00 in unitemized individual contributions, so those entries won't have state coding. 

Additionally, the state data is sometimes omitted from the transaction information on the report, so they don't get included in the total either.

**Comment by hobbes3** [comment]
Thanks Lindsay! I have a better understanding of the dataset and the reasons behind the numbers now.

**Comment by LindsayYoung** [comment]
Glad I could help!
