### ISSUE TITLE
cash on hand nulls

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1850]
I think this has something to do with going to the non-DW tables, they might just work slightly differently. 

we should
 -  see if the data is in the underlying table or if it is on our end
 - If the data is in the freport table, we will want to see why it is not being pulled,
   (my guess is that we will have to go back to the grater statment and that checks a field when something can be reported in multiple places) 

From the data google group:

Endpoint: /committee/{committee_id}/totals/
Affected Field: last_cash_on_hand_end_period

API Demo Examples that Reproduce the Error:
IL US-SEN Tammy Duckworth (C00574889)
API: https://api.open.fec.gov/v1/committee/C00574889/totals/?api_key=DEMO_KEY&page=1&cycle=2016&per_page=20&sort=-cycle
Current CoH: $5,563,795
API Reutrn: null

IL US-SEN Mark Kirk (C00350785)
API: https://api.open.fec.gov/v1/committee/C00350785/totals/?api_key=DEMO_KEY&page=1&cycle=2016&per_page=20&sort=-cycle
Current CoH: $3,123,984
API Reutrn: null

API Demo Examples that Produce Expected Results:
IL-1 Bobby Rush (C00257121)
API: https://api.open.fec.gov/v1/committee/C00257121/totals/?api_key=DEMO_KEY&page=1&cycle=2016&per_page=20&sort=-cycle
Current CoH: $57,521
API Reutrn: 57521.27

IL-2 Robin Kelly (C00539866)
API: https://api.open.fec.gov/v1/committee/C00539866/totals/?api_key=DEMO_KEY&page=1&cycle=2016&per_page=20&sort=-cycle
Current CoH: $369,357
API Reutrn: 369357.89

**Comment by ScottTKennedy** [comment]
Note: whatever the issue was it appears to have been resolved now as the data is appearing as expected as of this morning.  Thank you.

**Comment by noahmanger** [comment]
Sounds like this is resolved.
