### ISSUE TITLE
Figure out how to make the join with efile summary 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1859]
**Completion criteria:**
- [ ] We know how to do the join
- [ ] It's fast
- [ ] Know how to map out the data from the summary table to the corresponding form type

**Comment by LindsayYoung** [comment]
![slack for ios upload-1](https://cloud.githubusercontent.com/assets/4406333/17308433/faf48bce-5807-11e6-8099-f62185cb4f69.jpg)

**Comment by jontours** [comment]
In this picture, I'm assuming the table `real_e_file` on the right has no primary key?  or if it does is different than just the P.key column?

**Comment by LindsayYoung** [comment]
The table is `real_efile_summary` it says:
```
   "real_efile_summary_pkey" PRIMARY KEY, btree (repid, lineno)
```

**Comment by LindsayYoung** [comment]
in the drawing p_key is really `repid`

**Comment by jontours** [comment]
Thanks!  Just took a look at it on dev.

**Comment by ccostino** [comment]
Hmm, the counts of this table are 0 in both `dev` and `prod` and `staging` doesn't even have the table it seems.

**Comment by LindsayYoung** [comment]
@PaulClark2 and @jwchumley Do you know what tables are and aren't getting pushed?  As you know, real_efile_summary would be a top priority to get going.

**Comment by ccostino** [comment]
Furthermore, the counts in the related tables that we were discussing, such as `real_efile_f3` an `real_efile_f3p` are very low too: 124 and 18, respectively.

**Comment by jontours** [comment]
I may be having a massive brain fart, but what is the complexity with this join exactly?

**Comment by LindsayYoung** [comment]
start with the f3 table, left join to the summary table. Each item in the summary table will be one element that appears on the form.

**Comment by jontours** [comment]
Ok, that's what I'm understanding too.  So for example, that left join, with a select *, would result in a table like so:

pkey  com_id  pkey # value
A1      C123     A1     1  200
A1      C123     A1     2  32
.....

right?

**Comment by jwchumley** [comment]
REPID	LINENO	COLA	COLB	CREATE_DT
1091829	1		23948.97	8/1/2016 10:17:49 AM
1091829	2	33941.79		8/1/2016 10:17:49 AM
1091829	3	77659.39	165117.28	8/1/2016 10:17:49 AM
1091829	4	111601.18	189066.25	8/1/2016 10:17:49 AM
1091829	5	80325.85	157790.92	8/1/2016 10:17:49 AM
1091829	6	31275.33	31275.33	8/1/2016 10:17:49 AM
1091829	7	0		8/1/2016 10:17:49 AM
1091829	8	0		8/1/2016 10:17:49 AM
1091829	9	21954.96	42991.96	8/1/2016 10:17:49 AM
1091829	10	54344.85	119665.74	8/1/2016 10:17:49 AM
1091829	11	76299.81	162657.7	8/1/2016 10:17:49 AM
1091829	12	0	0	8/1/2016 10:17:49 AM
1091829	13	0	1000	8/1/2016 10:17:49 AM
1091829	14	76299.81	163657.7	8/1/2016 10:17:49 AM
1091829	15	0	0	8/1/2016 10:17:49 AM
1091829	16	0	0	8/1/2016 10:17:49 AM
1091829	17	0	0	8/1/2016 10:17:49 AM
1091829	18	359.58	359.58	8/1/2016 10:17:49 AM
1091829	19	0	0	8/1/2016 10:17:49 AM
1091829	20	1000	1100	8/1/2016 10:17:49 AM
1091829	21	0	0	8/1/2016 10:17:50 AM
1091829	22	0	0	8/1/2016 10:17:50 AM
1091829	23	0	0	8/1/2016 10:17:50 AM
1091829	24	77659.39	165117.28	8/1/2016 10:17:50 AM
1091829	25	77659.39	165117.28	8/1/2016 10:17:50 AM
1091829	26	0	0	8/1/2016 10:17:50 AM
1091829	27	0	0	8/1/2016 10:17:50 AM
1091829	28	58395.17	58395.17	8/1/2016 10:17:50 AM
1091829	29	58395.17	58395.17	8/1/2016 10:17:50 AM
1091829	30	0	0	8/1/2016 10:17:50 AM
1091829	31	4959.8	5589.8	8/1/2016 10:17:50 AM
1091829	32	12350.88	13350.88	8/1/2016 10:17:50 AM
1091829	33	0	0	8/1/2016 10:17:50 AM
1091829	34	0	0	8/1/2016 10:17:50 AM
1091829	35	0	0	8/1/2016 10:17:50 AM
1091829	36	4120	4120	8/1/2016 10:17:50 AM
1091829	37	0	0	8/1/2016 10:17:50 AM
1091829	38	0	0	8/1/2016 10:17:50 AM
1091829	39	4120	4120	8/1/2016 10:17:50 AM
1091829	40	500	76335.07	8/1/2016 10:17:50 AM
1091829	41	0	0	8/1/2016 10:17:50 AM
1091829	42	0	0	8/1/2016 10:17:50 AM
1091829	43	0	0	8/1/2016 10:17:50 AM
1091829	44	0	0	8/1/2016 10:17:50 AM
1091829	45	80325.85	157790.92	8/1/2016 10:17:50 AM
1091829	46	80325.85	157790.92	8/1/2016 10:17:50 AM
1091829	47	76299.81	163657.7	8/1/2016 10:17:50 AM
1091829	48	4120	4120	8/1/2016 10:17:50 AM
1091829	49	72179.81	159537.7	8/1/2016 10:17:50 AM
1091829	50	58395.17	58395.17	8/1/2016 10:17:50 AM
1091829	51	359.58	359.58	8/1/2016 10:17:50 AM
1091829	52	58035.59	58035.59	8/1/2016 10:17:50 AM

**Comment by jwchumley** [comment]
Like this. Here are the first ten rows of the summary table for report #1091829 (there are 52 rows)

REPID	LINENO	COLA	COLB	         CREATE_DT
1091829	1		                23948.97	         8/1/2016 10:17
1091829	2	33941.79		                         8/1/2016 10:17
1091829	3	77659.39	        165117.28	 8/1/2016 10:17
1091829	4	111601.18	189066.25        8/1/2016 10:17
1091829	5	80325.85	        157790.92	 8/1/2016 10:17
1091829	6	31275.33	        31275.33	         8/1/2016 10:17
1091829	7	0		                                 8/1/2016 10:17
1091829	8	0		                                 8/1/2016 10:17
1091829	9	21954.96	        42991.96	         8/1/2016 10:17
1091829	10	54344.85	        119665.74	 8/1/2016 10:17

**Comment by PaulClark2** [comment]
REPID	|	LINENO	|	COLA	|	COLB	|	CREATE_DT
----	|	----	|	----	|	----	|	----
1091829	|	1	|		|	23948.97	|	8/1/2016 10:17
1091829	|	2	|	33941.79	|		|	8/1/2016 10:17
1091829	|	3	|	77659.39	|	165117.28	|	8/1/2016 10:17
1091829	|	4	|	111601.18	|	189066.25	|	8/1/2016 10:17
1091829	|	5	|	80325.85	|	157790.92	|	8/1/2016 10:17
1091829	|	6	|	31275.33	|	31275.33	|	8/1/2016 10:17
1091829	|	7	|	0	|		|	8/1/2016 10:17
1091829	|	8	|	0	|		|	8/1/2016 10:17
1091829	|	9	|	21954.96	|	42991.96	|	8/1/2016 10:17
1091829	|	10	|	54344.85	|	119665.74	|	8/1/2016 10:17
1091829	|	11	|	76299.81	|	162657.7	|	8/1/2016 10:17
1091829	|	12	|	0	|	0	|	8/1/2016 10:17
1091829	|	13	|	0	|	1000	|	8/1/2016 10:17
1091829	|	14	|	76299.81	|	163657.7	|	8/1/2016 10:17
1091829	|	15	|	0	|	0	|	8/1/2016 10:17
1091829	|	16	|	0	|	0	|	8/1/2016 10:17
1091829	|	17	|	0	|	0	|	8/1/2016 10:17
1091829	|	18	|	359.58	|	359.58	|	8/1/2016 10:17
1091829	|	19	|	0	|	0	|	8/1/2016 10:17
1091829	|	20	|	1000	|	1100	|	8/1/2016 10:17
1091829	|	21	|	0	|	0	|	8/1/2016 10:17
1091829	|	22	|	0	|	0	|	8/1/2016 10:17
1091829	|	23	|	0	|	0	|	8/1/2016 10:17
1091829	|	24	|	77659.39	|	165117.28	|	8/1/2016 10:17
1091829	|	25	|	77659.39	|	165117.28	|	8/1/2016 10:17
1091829	|	26	|	0	|	0	|	8/1/2016 10:17
1091829	|	27	|	0	|	0	|	8/1/2016 10:17
1091829	|	28	|	58395.17	|	58395.17	|	8/1/2016 10:17
1091829	|	29	|	58395.17	|	58395.17	|	8/1/2016 10:17
1091829	|	30	|	0	|	0	|	8/1/2016 10:17
1091829	|	31	|	4959.8	|	5589.8	|	8/1/2016 10:17
1091829	|	32	|	12350.88	|	13350.88	|	8/1/2016 10:17
1091829	|	33	|	0	|	0	|	8/1/2016 10:17
1091829	|	34	|	0	|	0	|	8/1/2016 10:17
1091829	|	35	|	0	|	0	|	8/1/2016 10:17
1091829	|	36	|	4120	|	4120	|	8/1/2016 10:17
1091829	|	37	|	0	|	0	|	8/1/2016 10:17
1091829	|	38	|	0	|	0	|	8/1/2016 10:17
1091829	|	39	|	4120	|	4120	|	8/1/2016 10:17
1091829	|	40	|	500	|	76335.07	|	8/1/2016 10:17
1091829	|	41	|	0	|	0	|	8/1/2016 10:17
1091829	|	42	|	0	|	0	|	8/1/2016 10:17
1091829	|	43	|	0	|	0	|	8/1/2016 10:17
1091829	|	44	|	0	|	0	|	8/1/2016 10:17
1091829	|	45	|	80325.85	|	157790.92	|	8/1/2016 10:17
1091829	|	46	|	80325.85	|	157790.92	|	8/1/2016 10:17
1091829	|	47	|	76299.81	|	163657.7	|	8/1/2016 10:17
1091829	|	48	|	4120	|	4120	|	8/1/2016 10:17
1091829	|	49	|	72179.81	|	159537.7	|	8/1/2016 10:17
1091829	|	50	|	58395.17	|	58395.17	|	8/1/2016 10:17
1091829	|	51	|	359.58	|	359.58	|	8/1/2016 10:17
1091829	|	52	|	58035.59	|	58035.59	|	8/1/2016 10:17

**Comment by ccostino** [comment]
@jontours, thanks for asking that, I had the same question. :-)

@jwchumley and @PaulClark2, thank you for the examples, that is a huge help!

**Comment by jontours** [comment]
Ah ok, I think now I see, the line numbers can map to different things based on what form it originated from.

**Comment by PaulClark2** [comment]
Exactly, Jon.

**Comment by LindsayYoung** [comment]
This is how the FECh library deals with the efiling mapping:
https://github.com/NYTimes/Fech/blob/00be4e253b13f8259e7bb1cab9a140006f5ddde1/lib/fech/map_generator.rb

Here are the mappings for the ones we are working on, just look at the first two columns for the most recent mapping scheme. 

F3 summary
https://github.com/dwillis/fech-sources/blob/master/F3.csv

F3p summary
https://github.com/dwillis/fech-sources/blob/master/F3P.csv

F3x summary
https://github.com/dwillis/fech-sources/blob/master/F3X.csv

**Comment by PaulClark2** [comment]
https://github.com/dwillis/fech-sources/blob/master/F3.csv is not a mapping for real_efile_summary. It's a mapping for a .csv file. FECh parses .csv files pulled from http://docquery.fec.gov/cgi-bin/forms/...... FECh used these, http://www.fec.gov/elecfil/eFilingFormats.zip , files to construct the efiling mappings. The format of the .csv files is not the same as the real_file tables.

The .csv files have a "header" row, a "form" row that includes the summary and detailed summary information and then schedule rows (SA, SB, etc.). 

The data contained in the .csv that FECh parses is found in various tables: real_efile_reps, real_efile_f3, real_efile_summary and the appropriate schedule tables.
 
A specific example of the format difference:

Form 3 Line 6(a) is in position 24 of row 2 of the .csv file (and FECh). Line 6(a) is LINENO 1 in real_efile_summary.
![untitled](https://cloud.githubusercontent.com/assets/11817734/17346332/203cf940-58d8-11e6-8322-7bf55de661ab.png)

**Comment by LindsayYoung** [comment]
Thanks for flagging that @PaulClark2! I think the reference for the column to rows is still going to be helpful. We do have the spreadsheet documentation that Jeff passed on, so we can go off of that. Unfortunately, this means we will have to spend more time decoding values. Happy to lend a hand with that @jontours

**Comment by ccostino** [comment]
It looks like for the join itself, this is what we're going for:

```
-- With "on" syntax:
select * from real_efile_f3 as f3 left join real_efile_summary as summary on f3.repid = summary.repid;

-- With "using" syntax:
select * from real_efile_f3 as f3 left join real_efile_summary as summary using ("repid");
```

This seems to group and order things for us nicely as is, producing output identical to the example @PaulClark2 posted.  Can anyone think of anything we're missing here or any other concerns?  We know that we're going to eventually have to account for size/scale of data, but until we know what exactly we're dealing with I'd rather not prematurely optimize or over-complicate things since the mappings and endpoints are going to be challenging enough. :-)

**Comment by jontours** [comment]
Thanks @ccostino!

**Comment by noahmanger** [comment]
👍  Can we close this issue then?

**Comment by jontours** [comment]
Yeah I think so, especially since the join isn't really the complex part of the issue.
