### ISSUE TITLE
DW migration

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#1865]
@LindsayYoung @ccostino @jontours can you indicate if we are still using the DW tables below?

| DW tables | Still using |
| --- | --- |
|  | Yes/No |
| DIMCAND |  |
| DIMCANDOFFICE |  |
| DIMCANDPROPERTIES |  |
| DIMCANDSTATUSICI |  |
| DIMCMTE |  |
| DIMCMTEAGENT |  |
| DIMCMTEBANK |  |
| DIMCMTEPROPERTIES |  |
| DIMCMTERELATED |  |
| DIMCMTETPDSGN |  |
| DIMDATES |  |
| DIMELECTIONTP |  |
| DIMLINKAGES |  |
| DIMOFFICE |  |
| DIMPARTY |  |
| DIMREPORTTYPE |  |
| DIMYEARS |  |
| FACTHOUSESENATE_F3 |  |
| FACTINDPEXPCONTB_F5 |  |
| FACTPACSANDPARTIES_F3X |  |
| FACTPRESIDENTIAL_F3P |  |
| FORM_5 |  |
| FORM_57 |  |
| FORM_7 |  |
| FORM_76 |  |
| FORM_9 |  |
| FORM_91 |  |
| FORM_94 |  |
| VW_FILING_HISTORY |  |
| SCHED_A | No |
| SCHED_B | No |
| SCHED_E |  |

**Comment by ccostino** [comment]
@PaulClark2, do you mind if we just edit your table and fill in the info?

Also, it looks like a handful of the ones at the top are not necessarily used at all, but they are referenced in our tools for retrieving sample test data for development.  We'll dig deeper to verify.

**Comment by LindsayYoung** [comment]
@LindsayYoung @ccostino @jontours can you indicate if we are still using the DW tables below?

DW tables	|	Still using
---	|	---
	|	Yes/No
DIMCAND	|	No
DIMCANDOFFICE	|	No
DIMCANDPROPERTIES	|	No
DIMCANDSTATUSICI	|	No
DIMCMTE	|	No
DIMCMTEAGENT	|	No
DIMCMTEBANK	|	No
DIMCMTEPROPERTIES	| Yes
DIMCMTERELATED	|	No
DIMCMTETPDSGN	| No	
DIMDATES	|	No
DIMELECTIONTP	|	No
DIMLINKAGES	|	No
DIMOFFICE	|	No
DIMPARTY	|	Yes
DIMREPORTTYPE	|	Yes
DIMYEARS	|	No
FACTHOUSESENATE_F3	|	No
FACTINDPEXPCONTB_F5	|	No
FACTPACSANDPARTIES_F3X	|	No
FACTPRESIDENTIAL_F3P	|	No
FORM_5	|	Yes
FORM_57	|	Yes
FORM_7	|	No
FORM_76	| No
FORM_9	|	No
FORM_91	|	No
FORM_94	|	No
VW_FILING_HISTORY	|	Yes
SCHED_A	|	No
SCHED_B	|	No
SCHED_E	|	yes

We need `NML_SCHED_E - 24/28` to finish the schedule e transition  https://github.com/18F/openFEC/pull/1730

Does this look right to you @ccostino

**Comment by ccostino** [comment]
Yes, this list looks right to me, thanks @LindsayYoung!

**Comment by noahmanger** [comment]
Any further action required on this?

**Comment by jontours** [comment]
Made further edits to the table above, currently there are only four tables left so no surprises there.  We can mark them off as soon as the latest PR for the filings is vetted, tested and merged.

**Comment by LindsayYoung** [comment]
off of DW!
