### ISSUE TITLE
Search for multiple cities

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1867]
We probably want to add the ability to look for multiple cities on receipts and disbursements. 

Noticed we did not have that when I read #1828

**Comment by noahmanger** [comment]
This is currently supported by the API already: https://api.open.fec.gov/v1/schedules/schedule_a/?contributor_city=portland&contributor_city=los%20angeles&per_page=20&two_year_transaction_period=2016&api_key=DEMO_KEY

Closing, because front-end implementation is happening in another issue.
