### ISSUE TITLE
DB updates

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1868]
- [x] make sure we delete queue immediately after the update action (Carlo)
 - [x] add rollbacks on add statements sched A and B
 - [x] only update schedule E once (get rid of command) (Lindsay)
 - [x] clear bad data (Lindsay)
 - [x] re-run updates (Lindsay)

**Comment by LindsayYoung** [comment]
did the deletes and updates are running

**Comment by ccostino** [comment]
@LindsayYoung and @jontours:  I just completed my first pass of moving the queue deletes to happen after the processing takes place and it yielded an important realization around when they need to take place.  That `refresh_child` method where the actual deletes and inserts take place against a child table is run for each child table in the partition.  If we clear the queues out after those delete and insert steps that we were looking at earlier (starting here: https://github.com/18F/openFEC/blob/develop/webservices/partition/base.py#L177), then the queues will be cleared after each child is processed.

In other words, as soon as we start processing the queues will be cleared out entirely after the first child table is processed.  if that happens, we'll lose the data we want to process for all of the remaining child tables.

There are two approaches that come to mind in how to address this:

 * Proceed as we originally discussed, but modify the `delete` statements for the queues to only delete the records that match what was processed for the current child table.  At the end of refreshing all of the children, we could add an additional check to see if any records still remain in the queues and if so, add a bit of information to our nightly report letting us know some data was not processed.  This could be taken even further in the future if we figure out how we want to handle the data that got stuck in the queue (theoretically this shouldn't happen, but you never know!).
* Keep the statements clearing the queues where they are, but this is entirely dependent on adding some `try/excepts` with rollback support then.

I'd like to go with the first approach, but wanted to check with both of you to see if there were any concerns or if there were any other ideas first.

**Comment by LindsayYoung** [comment]
I think we might want to go with try/excepts with rollback support. If there is a failure and we use the first method, we would sill want the work that was half finished to be rolled back.  So, if we are doing rollbacks anyway, approach 2 sounds simpler to implement. 

I also like the idea of breaking up this huge nightly process with try excepts because a lot can go wrong and I don't think it is worth halting everything.

**Comment by ccostino** [comment]
Okay, that's definitely doable, thanks @LindsayYoung!  In addition to this then, it'd probably make sense to not clear out the queues either in the event of any error that results in a rollback.

Big +1 on the `try/excepts` to at least let independent pieces of the nightly updates finish as opposed to everything stopping.

**Comment by LindsayYoung** [comment]
Agreed on only clearing queues on success! Tell me if you need a hand.

**Comment by ccostino** [comment]
#1838 is ready to go and accounts for all of the remaining tasks here!

**Comment by noahmanger** [comment]
Can this be closed?
