### ISSUE TITLE
Design specific tag UI for date ranges and financial ranges

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1872]
For the new filter tag UI, we need to design how tags for date and financial ranges should look. Currently they generate separate tags for min and maxes, but perhaps there's a way to unify them. 

For date ranges in particular, we should also try to unify with the tag generated for the "Transaction period", which cannot be removed. So this tag system needs to accommodate:
- A transaction period that will by default set a min and max range from 01/01/YYYY - 12/31/YYYY
- A custom start and end date can be set within that range
- If no custom start or end date is defined, it needs to show the default start and end date

Assigning to @jenniferthibault but if you would rather @onezerojeremy take a swipe at interaction design first, that's cool.

**Comment by jenniferthibault** [comment]
This issue will take it's cues from the form patterns in https://github.com/18F/openFEC-web-app/issues/1375 and https://github.com/18F/openFEC-web-app/issues/1373

To be honest, I'm not sure if I will be able to complete this task in this sprint, as I understand that the CMS page templates in https://github.com/18F/fec-style/issues/455 are higher priority.

**Comment by noahmanger** [comment]
Cool. You're right that the page templates are higher priority.

**Comment by jenniferthibault** [comment]
Here's my first take on what the tags should do:
- If you can't remove a tag, use the info tooltip (the same one that's in the filter panel, with the same style on the calendar tags) to tell people _why_
- If the filters create a range, group them in the same grey box, but do not use _**or**_ 

![screen shot 2016-08-12 at 1 41 00 pm](https://cloud.githubusercontent.com/assets/11636908/17631673/03c7f216-6093-11e6-89c2-244fd796a6b5.png)
![screen shot 2016-08-12 at 1 44 31 pm](https://cloud.githubusercontent.com/assets/11636908/17631674/03ce3e32-6093-11e6-846d-26529071d23d.png)

I know this doesn't capture each interaction step, but wanted to get something started to check the visual logic of.

**Comment by emileighoutlaw** [comment]
I love the work you've done here, Jen! And I wholeheartedly agree that "if the filters create a range, group them in the same grey box, but do not use **or**"

I also like including a tooltip explaining transaction period. (I want to play with language some, but it's premature for that kind of work yet.) Curious to hear others weigh in on this.

**Comment by jenniferthibault** [comment]
👍 @emileighoutlaw I grabbed that wholesale from the existing tooltip,  (but added `you must apply a transaction period, and` ) so if you revise, let's make sure it gets carried through to the original filter as well!

**Comment by noahmanger** [comment]
Sorry for the long delay. I finally had time to think about this and sketch out some ideas that I want to share. Basically I think we can get away with not explicitly defining the "transaction period" as a separate filter tag apart from the min and max dates. Instead, we just show min and max dates, but intelligently make them removable or not depending on if it's a custom beginning or ending date. Here's how it would work:

![image](https://cloud.githubusercontent.com/assets/1696495/17819683/edae005e-65fd-11e6-8635-3030946da24d.png)

This could incorporate the tooltip when the tags aren't removable. But I think by removing the multiple date ranges (transaction period + beginning and ending dates) it becomes less complicated. And it also allows us to piggy back on the new "or" pattern, just replacing it with "to".

What do you think?

**Comment by jenniferthibault** [comment]
I'm a little nervous about making one tag unit change between removeable and non-removeable in the tag field. _We_ know why this would be so, but it's not something a user expects. For that reason my (totally non-data-informed) hunch is that this intelligent-removable-switching is a bit over-engineered, and might be too auto-pilot for users. (post-vacation brain is fuzzy, but on the date picker, didn't we decide as a principle not to force an opposite start/end date?) This feels like the other side of that coin.

On changing the "or" field to a "to" field for ranges, I'd prefer we hold off on using adapting that pattern to this purpose until/if our search enables people to include and/or/not/etc search types. Using just the "or" contraction feels like it's creating a stable pattern with the site's current functionality, and is a pattern that I'm not sure we want to create variance within _yet_. If you feel strongly about this, I'd maybe start with an en-dash between the fields, in regular weight. In other words, use it to show how the tags are related, but keep it from looking like a search type indicator.   

I wonder if one step between the two would be to do something like this, where a user can change the date (through the filter panel) but they can never remove it through the tag field:
<img width="950" alt="screen shot 2016-08-22 at 11 11 22 am" src="https://cloud.githubusercontent.com/assets/11636908/17859841/38ee50de-6859-11e6-9bc8-9b77ad39d9ef.png">

This would correlate on financial ranges to this, which retains our plain language single tags, and sticks to the principle of not auto-generating the opposite limit
<img width="843" alt="screen shot 2016-08-22 at 11 07 55 am" src="https://cloud.githubusercontent.com/assets/11636908/17859903/69392908-6859-11e6-8f60-1b7e097c23d4.png">
:

**Comment by noahmanger** [comment]
Great points. I agree that it could get a little too automagical. I feel pretty strongly that in this context using a conventional way to show ranges (like the en dash) communicates what's going on with the filter a lot clearer. But I see your point about "to" and think that your proposal here seems like a solid approach.

**Comment by jenniferthibault** [comment]
Sounds like a good way forward to me! I'll move this to implementation.
