### ISSUE TITLE
Schedule A Data Does Not Include Transaction ID

### ISSUE THREAD

**Issue by zachoj10** [18F/openFEC#1878]

**Comment by LindsayYoung** [comment]
Thanks for writing in I see how that could be confusing. Transaction_id is only for electronic filings, the unique identifier is sub_id.

https://api.open.fec.gov/developers/#!/schedules%2Fschedule_a/get_schedules_schedule_a_sub_id

**Comment by zachoj10** [comment]
So then it's not possible to match the electronic filing records to the records in the API?

**Comment by LindsayYoung** [comment]
OK, I think i misunderstood before, records that have been efiled should have transaction_id we can check on that.
