### ISSUE TITLE
Implement front-end for efiling view of filings

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1881]
So that users can get the most recent efilings, add the ability to view efilings to the filings data table page.

**Comment by LindsayYoung** [comment]
Now, receipt date is a date, but they are going to make that a date time, which is helpful for people but we will want to handle it in a way that makes it as consistent as possible.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1528
