### ISSUE TITLE
Provide link to .fec file on filings

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1882]
So that power users can download the official .fec file version of a report, provide links to the .fec file in the API filings and reports responses.

---

Similar to CSVs, these files follow a regular URL pattern. 

**Criteria for completion:**
- [x] CSV link included in `/reports/*/` responses
- [x] CSV link included in `/filings/` responses
- [x] CSV link included in `/efile/filings/` responses
- [x] CSV link included in `/efile/reports/*/` responses

**Comment by LindsayYoung** [comment]
We want this on the API side, right?

**Comment by noahmanger** [comment]
Yep!

**Comment by noahmanger** [comment]
Updated with criteria for completion.

**Comment by jontours** [comment]
@jwchumley What is the format for the url for the `.fec` files?  I've tried a few with the pattern that was shared on the other issue and none seem to link anything.  Do you have an a working example of .fec link?  Thanks.

**Comment by jwchumley** [comment]
Electronic Filings:  docquery.fec.gov/dcdev/posted/[filenum].fec


Paper filings:  docquery.fec.gov/paper/posted/[filenum].fec




________________________________

**Comment by jontours** [comment]
Thanks @jwchumley, and sorry for the questions.  So those urls make sense, also how do I determine for example say a filing is electronically or paper reported, for example the image for the filing here is electronically filed: http://docquery.fec.gov/pdf/487/201601109004446487/201601109004446487.pdf.

How do I glean that from the data tables, as of yet I've found no indicator for this.  Thanks again for the help.

**Comment by jwchumley** [comment]
Ah. That's a secret.


But I'll tell you.


 If the image number is the long form (18 digits) like these:

201602080300048778

201602040200066702

201602089008442693

201602169008465532


 The 9th and 10th digits determines paper vs electronic. 9 is electronic and anything else is paper.


Older images with 11 digits like these:

14020175033
14030175058
14990620060
14970620071
14960620075
14950620082

14940620132


The 3rdand 4th digits determine paper or electronic. 02 and 03 are paper (senate and everything else respectively)  and 94-99 is electronic.





________________________________

**Comment by jontours** [comment]
Thanks @jwchumley.  So for the long form `image_number` what role does the 10th digit play?  I see alot of records with the 9th digit being 9, so if 10th digit is 9 then also electronic?

**Comment by jontours** [comment]
@jwchumley can you also verify the url for `.csv` urls for paper filings?  We aren't seeing any of those working, at least in the few examples we've tried.  Thanks.

**Comment by noahmanger** [comment]
.fec links resolved by https://github.com/18F/openFEC/pull/1986 

Making a new issue to turn on .csv links once those URLs are stable.
