### ISSUE TITLE
Scrape press releases

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1895]
So that the 18F team can migrate the press releases from the old site into the [Wagtail CMS](https://github.com/18f/fec-cms), scrape the existing press releases into a database that can later be imported into the Postgres database used by the CMS.

**Criteria for completion:**
- Scrape all of the [press releases available on FEC.gov](http://www.fec.gov/press/news_releases.shtml), grabbing the content in the `#press_release_content` `div`
- Parse out:
  - Title
  - Authors / Contacts
  - Dates
  - Category
- Strip out miscellaneous `style` attributes
- Ideally, save data in Postgres, but any datastore will do

**Comment by noahmanger** [comment]
Should we also grab the PDF url separately? 
![image](https://cloud.githubusercontent.com/assets/1696495/17790682/77a36072-654c-11e6-89a6-047c5703e4c0.png)

**Comment by LindsayYoung** [comment]
Check with @emileighoutlaw I thought we were only moving html if something existed as a pdf and html?

**Comment by noahmanger** [comment]
Ok cool. I just thought it might be useful to have as data, but maybe not. Also, I added "Title" to the parsing list.

**Comment by emileighoutlaw** [comment]
Lindsay's correct! 

HTML and PDF migrates as HTML only
PDF only migrates as PDF only

**Comment by pkarman** [comment]
Sounds fun. 

Do you want the code in Python for inclusion in this repo via PR? Or just a standalone script attached to this ticket, language negotiable?

**Comment by LindsayYoung** [comment]
Hi Peter,

The final destination will be a postgres db in this repo https://github.com/18F/fec-cms

In general we have a preference for python, ruby or node, but I see these as one-off scripts that can be in any language. 

We will accept your contribution anyway you prefer- it can be a script on this ticket, a pr or it can be in your own repo. 

Happy to answer any questions you might have. 

Thank you!

**Comment by PaulClark2** [comment]
We do want the PDF url.

**Comment by pkarman** [comment]
> Strip out miscellaneous style attributes

Does this mean removing all HTML from the `. press_release_content` div? Or formatting-specific HTML only? Or just the `style` attribute on any elements?

**Comment by noahmanger** [comment]
I think we should just start with the `style` attributes, just in case there's tables or such that are necessary for layout. 

And since we need the PDF url, it would be good to have that pulled out as a separate field.

**Comment by pkarman** [comment]
started here: https://github.com/pkarman/fec-press-release-scraper

about 90% done. need to add some tests to verify various formats over the years.

**Comment by pkarman** [comment]
TODO

* [ ] parse Contacts
* [ ] parse PDF link
* [ ] parse older than 2013 style releases
* [ ] tests

**Comment by noahmanger** [comment]
Awesome stuff. Thanks for the update @pkarman !

**Comment by pkarman** [comment]
Parsing out the contacts is problematic since they are usually only indicated via a heading `Contact` but the names themselves are buried elsewhere in a table cell for formatting reasons. I.e. nothing semantic about the markup to indicate that a given string in a given table cell is a contact name. How important are contacts?

**Comment by pkarman** [comment]
I'd appreciate someone taking the code for a spin to see if I'm headed in the right direction.

**Comment by LindsayYoung** [comment]
Sure, thanks!

**Comment by LindsayYoung** [comment]
Running the code now. I will see how it goes. Thanks again!

**Comment by noahmanger** [comment]
This is complete. Thanks again @pkarman !
