### ISSUE TITLE
Upgrade Postgres in Amazon RDS

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#1897]
We're currently running Postgres version 9.4.5 in our Amazon RDS instances, but version 9.5.2 has been out for some time now and is officially supported by Amazon RDS.  We would be able to benefit from the security improvements and feature updates (we have had our eye on `upserts` to improve our update processes further).

Furthermore, Paul and Rohan are experimenting with the next version of GoldenGate and working with Postgres 9.5.2 locally.  It would help to be running the same version on RDS.

In order to perform the upgrades, we would follow the steps here:  http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion

Note that any replicas (we have one in `dev`) will need to be recreated as a part of this process.  Because of this, we'd like to take care of this before #1415.

We'll upgrade `dev` and `stage` first and verify the upgrade steps, note any issues, and formalize a plan for production before touching the `prod` instance.

**Comment by ccostino** [comment]
In reading over the upgrade steps in Amazon's RDS guide, here is everything we need to do to upgrade our instances:

1. Check for prepared transactions that are still open and either commit them or roll them back - we can check for any with this query:

  ```sql
SELECT count(*) FROM pg_catalog.pg_prepared_xacts;`
  ```

2. Remove all `reg*` data types - we can check for any with this query:

  ```sql
SELECT count(*) FROM pg_catalog.pg_class c, pg_catalog.pg_namespace n, pg_catalog.pg_attribute a 
  WHERE c.oid = a.attrelid 
      AND NOT a.attisdropped 
      AND a.atttypid IN ('pg_catalog.regproc'::pg_catalog.regtype, 
                         'pg_catalog.regprocedure'::pg_catalog.regtype, 
                         'pg_catalog.regoper'::pg_catalog.regtype, 
                         'pg_catalog.regoperator'::pg_catalog.regtype, 
                         'pg_catalog.regconfig'::pg_catalog.regtype, 
                         'pg_catalog.regdictionary'::pg_catalog.regtype) 
      AND c.relnamespace = n.oid 
      AND n.nspname NOT IN ('pg_catalog', 'information_schema');
  ```

3. Perform a [`VACUUM`](https://www.postgresql.org/docs/9.4/static/sql-vacuum.html) operation.  The upgrade documentation doesn't say anything about performing a full `VACUUM` or running `VACUUM ANALYZE`.  Running just `VACUUM` does not obtain an exclusive lock on the tables that it processes, so read/write operations continue to occur normally.

**NOTE:** In the case of `dev`, we also need to delete the existing read replica and recreate a new one with the upgraded version.

We would need to upgrade any extensions we are using as the upgrade process does not do this for us automatically.  To my knowledge we're not using any, but if we are, the command would be something like this (taken from the documentation):

```sql
ALTER EXTENSION POSTGIS UPDATE TO '2.2.2'
```

At this point, the only thing I'm unsure about is roughly how long the actual upgrade will take place.  Downtime is required as noted at [the beginning of the upgrade guide](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html), but I'm not seeing any estimates.  Once we perform this in at least `dev` we'll have a much better sense.

**Comment by ccostino** [comment]
At this point, the `dev` database instance has been updated to version 9.5.2, including the read replica!  The process was very straightforward, it just took some time:  about 4 hours for the `VACUUM` operation and about 5 and a half hours for the upgrade itself.  Recreating the read replica took about 10 minutes.

I imagine that the upgrades will take slightly longer in `stage` and `prod` given the increased size, but I don't anticipate any issues, either.

**Comment by ccostino** [comment]
I also modified the steps to move `VACUUM` first as that takes a long time.  The state of the DB could change while it's running so it makes sense to perform the other two checks after it finishes, right before starting the upgrade itself.

**Comment by ccostino** [comment]
We're going to kick off the staging upgrade today, it should be done sometime tomorrow.

**Comment by ccostino** [comment]
Staging update is done!  The `VACUUM` process took 2 - 3 hours and the upgrade itself in RDS was a matter of about 30 minutes total, if that.

**Comment by LindsayYoung** [comment]
Nice!

**Comment by noahmanger** [comment]
We still need to do this in prod, right?

**Comment by ccostino** [comment]
Yup!  `prod` is the only one that remains.

**Comment by ccostino** [comment]
Production upgrade is being planned for tomorrow evening.

**Comment by ccostino** [comment]
Production upgrade is done and all three environments have been rebooted once more to account for final upgrade steps.  We're done!
