### ISSUE TITLE
Remaining work for efiling summary endpoint 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1905]
In order to support the remaining features needed to ship the efiling summary work, we need a few more fields. Off the top of my head:
- PDF url (derived from beginning and ending page numbers
- document description OR full form type. I think either could work

Anything else I'm missing?

**Comment by jontours** [comment]
I believe right now that covers all missing functionality.  Also have to add in sorting on needed fields, the code is actually there, just has to be uncommented.  That's so insignificant it could be added to the release branch.

**Comment by noahmanger** [comment]
Have you made these changes yet @jontours ?

**Comment by jontours** [comment]
I've made an initial branch but no commits yet, I should have this done quickly given that there is no confusion on my part about how those extra fields are mapped to the efile report tables.

**Comment by noahmanger** [comment]
Ok cool. This would be great to get into this release if at all possible.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1919
