### ISSUE TITLE
Add form 5 independent expenditures to itemized IEs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1909]
_Discussion happening over [in the original feedback issue.](https://github.com/18F/openFEC-web-app/issues/1436). Will update this issue with completion criteria once we have things sorted out._

**Comment by LindsayYoung** [comment]
I think this is just about switching over from the data warehouse? We have a ticket, and last I looked, we did not have all the data. https://github.com/18F/openFEC/pull/1730

I can double check but I thought we were covered here:
https://api.open.fec.gov/developers/#!/independent_expenditures/get_schedules_schedule_e

**Comment by noahmanger** [comment]
So they sure seem to all be in there as-is, so maybe more work isn't necessary.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1565
