### ISSUE TITLE
Add itemized loans (schedule C) transactions

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1911]
So that users can view itemized loan data, add the schedule C data to the API. 

This endpoint should follow the structure of the `/schedules/schedule_*/` endpoints for consistency. So response field and filter names should be as close to existing conventions as possible.

Without being more familiar with the data, here's a first take at what it should definitely have:

**Completion criteria:**
- [x] All schedule C data available on `/schedules/schedule_c/`
- [x] All items include a link to the PDF page they appear on
- [x] Filterable by:
	- [x] Committee ID
	- [x] Transaction amount
	- [x] Transaction date
- [x] Sortable by:
	- [x] Transaction amount
	- [x] Transaction date

I think the purpose of this task really is just to get it into the system. Once it's in, we can continue to add filters.

**Comment by noahmanger** [comment]
Updated the initial comment with a better description of the task. @LindsayYoung anything to add?

**Comment by LindsayYoung** [comment]
This is another small dataset where everything can be sortable.
I would add candidate_id, loan_src_nm,  

I think we need filtering on payment_to and loan_balance because if I understand @jwchumley correctly, the debt can go in different directions.

**Comment by jontours** [comment]
I'm gonna interpret transaction amount as `loan_amount` and transaction date as `incurred_date`.  Those seem to be the most logical mappings.

**Comment by jontours** [comment]
Besides the writeup for the swagger front end docs, I dare say this is done!

**Comment by noahmanger** [comment]
![image](https://media.giphy.com/media/zPVRKhPsUP5lK/giphy.gif)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1915
