### ISSUE TITLE
Add itemized party coordinated expenditures (schedule F) data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1912]
So that users can view itemized party coordinated expenditures, add the schedule F data to the API. 

This endpoint should follow the structure of the `/schedules/schedule_*/` endpoints for consistency. So response field and filter names should be as close to existing conventions as possible.

Without being more familiar with the data, here's a first take at what it should definitely have:

**Completion criteria:**
- [x] All schedule F data available on `/schedules/schedule_f/`
- [x] All items include a link to the PDF page they appear on
- [x] Filterable by:
	- [x] Committee ID
	- [x] Transaction amount
	- [x] Transaction date
- [x] Sortable by:
	- [x] Transaction amount
	- [x] Transaction date

I think the purpose of this task really is just to get it into the system. Once it's in, we can continue to add filters.

**Comment by noahmanger** [comment]
Comment updated with a better description. @LindsayYoung @jontours anything to add?

**Comment by LindsayYoung** [comment]
There are only  74,000 records here, we can make it sortable by anything.

We will want it filterable by multiple cand_id as well.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1928

Nice work!
