### ISSUE TITLE
Add itemized debts (schedule D) data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1913]
So that users can view itemized debt data, add the scheduleDC data to the API. 

This endpoint should follow the structure of the `/schedules/schedule_*/` endpoints for consistency. So response field and filter names should be as close to existing conventions as possible.

Without being more familiar with the data, here's a first take at what it should definitely have:

**Completion criteria:**
- [x] All schedule D data available on `/schedules/schedule_d/`
- [x] All items include a link to the PDF page they appear on
- [x] Filterable by:
	- [x] Committee ID
	- [x] Transaction amount
	- [ ] Transaction date
- [ ] Sortable by:
	- [x] Transaction amount
	- [x] Transaction date

I think the purpose of this task really is just to get it into the system. Once it's in, we can continue to add filters.

**Comment by noahmanger** [comment]
Original comment updated. CC @LindsayYoung @jontours

**Comment by jontours** [comment]
@LindsayYoung @noahmanger Didn't mention during the meeting but this resource has no transaction date, so maybe just use pg_date aka `load_date`.  Also looking at the linked pdfs, the forms have no field for date so I believe a missing transaction date makes sense.  Other than that this resource is ready.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1938 . Nice work!
