### ISSUE TITLE
Investigate number of processes and connections to the DBs

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1920]
Find the origin of non-ec2 connections and make sure we are managing them well

**Comment by noahmanger** [comment]
Let's timebox this to one hour before deciding further work.

**Comment by ccostino** [comment]
It looks like the bulk of the connections are from FEC, and another handful are from AWS.

**Comment by noahmanger** [comment]
Sounds good. Thanks for resolving. I'm going to close.
