### ISSUE TITLE
Add downloads for new resources

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1925]
Enable downloads for: 
 - reports 
 - efiling reports
 - efiling files

**Comment by noahmanger** [comment]
We should also add the candidate office pages while we're at it. Those shouldn't be hard, right?

**Comment by noahmanger** [comment]
Additional thing to investigate is what it would take to allow users to download the various schedule A and B aggregates (like `/schedules/schedule_a/by_employer/`). Implementing on the front-end is another question, but I just want to know how easy it is to provide the backend. Are these also just resources that can be whitelisted?

**Comment by ccostino** [comment]
As far as I can tell yes, it's a matter of finding the corresponding views to them.  I see some, but not all of them, though they might live in places I'm not expecting so I have to keep looking.  I do see a `ScheduleAByEmployerView` object, but need to see where that's also exposed on the web app.

**Comment by LindsayYoung** [comment]
The url and model mapping in rest.py might be useful for that, then you can look for the endpoints in the web app

**Comment by ccostino** [comment]
Ah, yes, thanks @LindsayYoung!

**Comment by ccostino** [comment]
After a conversation in Slack with @noahmanger, we're going to keep the scope of this issue reduced to just filings/e-filings and reports.  We have other issues that we need to tackle this sprint that are high priority, and the candidate office downloads are proving to be difficult to get working.

The itemized aggregates shouldn't be an issue, but for the sake of focusing on current sprint priorities we'll save those for later as well.  I'll make new issues for both of these things.

**Comment by noahmanger** [comment]
Resolved by #1945
