### ISSUE TITLE
Include committee name in all schedule downloads

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1940]
In order for users to understand the committees associated with the data they download, include the committee name in each row.

At some point, we removed the committee object from the schedule download files for the purposes of removing all the extraneous committee fields that came with it, but in so doing, we removed the actual committee name from the file, whether the spender or recipient. 

This needs to be implemented for:
- [x] Schedule A
- [x] Schedule B
- [x] Schedule E

Other issues referencing this bug:
https://github.com/18F/FEC/issues/467
https://github.com/18F/openFEC-web-app/issues/1438
https://github.com/18F/openFEC/issues/1894

**Comment by noahmanger** [comment]
Another ping on this issue just came in https://github.com/18F/FEC/issues/478

**Comment by ccostino** [comment]
I'll take a look soon, either shifting gears from the downloads work or right after I wrap things up.  Giving myself to the end of today to see where I end up.

**Comment by noahmanger** [comment]
Resolved by #1951
