### ISSUE TITLE
Add URL to CSV on filings and reports endpoints

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1954]
So that users can view the entire contents of a report as a CSV, provide a link to the new CSV files for reports.

---

**Criteria for completion:**
- [x] CSV link included in `/reports/*/` responses
- [x] CSV link included in `/filings/` responses
- [x] CSV link included in `/efile/filings/` responses
- [x] CSV link included in `/efile/reports/*/` responses

**Comment by jontours** [comment]
Algorithm is as follows: http://docquery.fec.gov/csv/XXX/ REPID.csv

With exception of 1-99.csv, e.g. http://docquery.fec.gov/csv/000/99.csv

**Comment by noahmanger** [comment]
Updated this with a stab at the completion criteria. Let me know if that looks off base. @LindsayYoung are you down to take this on?

**Comment by jontours** [comment]
@noahmanger I can take reports since it's kind of my baby at this point.  so maybe assign to both of us?

**Comment by noahmanger** [comment]
Sure! Happy for you two to divvy up work however you like.

**Comment by jontours** [comment]
I asked this question in the issue but do we know what format the .csv urls are for the regular reports, i.e. `/reports/*` and `/filings/`?  Was the algorithm for that specified by the Jeff (they don't have rep_ids/file numbers)?

**Comment by noahmanger** [comment]
Not sure. @jwchumley ?

**Comment by jwchumley** [comment]
Define "regular reports"

**Comment by jontours** [comment]
Ah sorry, by "regular" I meant processed reports for committees, reports that are reported on form f3x.  The tables corresponding to those in the database don't have `rep_id`s they are keyed by `sub_id`, so I'm not sure how the url for the .csv is generated.

**Comment by jwchumley** [comment]
Do they not have File_num? that is the same as repid.

________________________________

**Comment by jontours** [comment]
Ah, ok, that's kind of what I figured didn't get around to experimenting to see if that would work.  Thanks @jwchumley.

**Comment by jontours** [comment]
Ok, I'm seeing `file_num`.  So does the algorithm apply the same as it did for efilings?  I'm seeing some issues for that, as some of the file_numbers are negative.  So how does one go about generating a unique url in that case?

**Comment by jwchumley** [comment]
Negative Filenums are assigned to paper filings when the pass1 (summary) is entered and before the transactions are converted to data. At this point the only link should be to the image. Once the transactions come back and go through exception processing and are loaded into the disclosure database a positive file_num is assigned at which point the links should be good.


CSV URL:

docquery.fec.gov/paper/fepcpprcsv/[filenum].fec


.fec URL = docquery.fec.gov/paper/posted/[filenum].fec


________________________________
