### ISSUE TITLE
Formatting goes wonky when toggling between candidate and committee profile search

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC#1955]
![candidate profiles](https://cloud.githubusercontent.com/assets/10552702/18963842/274d8db2-863c-11e6-9c28-1b61ef02464a.gif)

cc @noahmanger @xtine

**Comment by noahmanger** [comment]
Duplicate of https://github.com/18F/openFEC-web-app/issues/1606 which is fixed in https://github.com/18F/fec-style/pull/527 

Thanks @emileighoutlaw

**Comment by emileighoutlaw** [comment]
Whoops! Thanks. :)
