### ISSUE TITLE
Move to Golden Gate tables

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1957]
Update following tables to disclosure schema in all python and sql references:
- [x] COMMITTEE_SUMMARY, 
- [x] CAND_CMTE_LINKAGE, 
- [x] CAND_VALID_FEC_YR, 
- [x] CMTE_VALID_FEC_YR
---

Update from backlog grooming:

**Completion criteria:**
- [x] Verify that counts that they're reporting to us now are accurate
- [x] Verify that the endpoints that use these work properly

**Comment by jontours** [comment]
There is nothing to modify for committee_summary, as we are currently not referencing that table at all.  But should we be?

**Comment by LindsayYoung** [comment]
No worries about committee summary, I made the list of the tables that were not bing synced anymore if we already moved off of that one, that is great!

**Comment by noahmanger** [comment]
Have we verified the two points under completion criteria above?

**Comment by jontours** [comment]
I haven't verified the counts yet.  Now that it's merged into the release branch I can update the schemas and verify the counts match.

**Comment by noahmanger** [comment]
Cool. Yeah let's be sure to do that before release.
