### ISSUE TITLE
Draft usability testing script

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#196]
**Goal:** v1 of a usability test script that can be used on upcoming usability tests.

**Criteria:** A script that covers current tasks possible in the app. 

**Steps:** 
- [x] List all tasks
- [x] Create paths to success for each
- [x] Add other questions
- [x] Add necessary disclaimer language
- [ ] Pilot with 1 or 2 18Fers

**Comment by rjmajma** [comment]
Let me know how I can help with this!

**Comment by noahmanger** [comment]
Here's (the doc)[https://docs.google.com/a/gsa.gov/document/d/1JPgSoVJq9DS_KjOgRg7Fi6a43Y9-bx7ZrbSxgxrB_N4/edit?usp=sharing] I've been working on. Take a look at it and if you have thoughts let me know. 

Also, you can take on adding the disclaimer / intro language. There's a number of other usability test scripts out there at 18F that have the language we could use.

**Comment by rjmajma** [comment]
Added in some disclaimer/intro language. Take a look and see if you need me to tweak/add more.

**Comment by noahmanger** [comment]
Ok I'm feeling pretty good about this script. Going to pilot with a couple 18F people asap.

**Comment by rjmajma** [comment]
I'll do the same in DC.

**Comment by rjmajma** [comment]
Closing. Moving to Invision and testing with that.
