### ISSUE TITLE
Create summary endpoint for location of individual contributions

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1973]
So that users learn how much money comes from individuals in different states, create an endpoint that shows the total amount raised via individual contributions from each state for various types of groups. 

---

This issue is for creating the endpoint that will serve the data for this visualization:
![map](https://cloud.githubusercontent.com/assets/1696495/19176069/34584e56-8bf1-11e6-9a82-d29cf30f5820.png)

For more details, check out 

**Completion criteria (originally from [this comment](https://github.com/18F/openFEC/issues/1620#issuecomment-218630091)):**
- [ ] The endpoint returns the _total_ amount raised via individual contributions by all groups combined from individuals from a certain state
- [ ] The endpoint returns the total amount raised via individual contributions by each of these kinds of groups:
  - All candidates
  - Presidential candidates
  - Senate candidates
  - House candidates
  - All PACs
  - Super PACs
  - SSFs
  - Non-connected
  - Leadership PACs
  - Hybrid PACs
  - National party committees

**Comment by noahmanger** [comment]
In the epic, @LindsayYoung added these notes:

- use ofec_sched_a_aggregate_state_tmp join by committee_id to ofec_committee_detail_tmp, the groupings are going to be the same ad the large_aggragates.sql that I am working on
- make sure dependency is mapped in webservices/flow.py

**Comment by LindsayYoung** [comment]
And I think we should do the groupings listed above and not the same one as the big table.

**Comment by noahmanger** [comment]
I just re-read the list above and realized the first to-do item is to show the _total total_, so to all groups combined. Do we want to do this?

**Comment by LindsayYoung** [comment]
It will just be totaling our totals, so it should be easy. We could take it out later if people don't like it or find it confusing. If it is more complicated for some unforeseeable reason, we can make it a reach goal

**Comment by ccostino** [comment]
@noahmanger, as I am piecing together the data that will live behind this endpoint, how does this look to you as far as what should be returned/available?

```javascript
{
    total_amount,
    cycle,
    state,
    state_full,
    committee_type,
    committee_type_full
}
```

Is there anything else you'd like to see, or anything that shouldn't be here?

**Comment by noahmanger** [comment]
I don't think we need `state_full` (`state` should do). Also, we might want to come up with a better name than `committee_type` since it's actually a mix of Committee Designation and Committee Type, right?

**Comment by noahmanger** [comment]
But structurally, that all makes sense.

**Comment by ccostino** [comment]
Good deal on the state info (so only the two letter abbreviation will come back.  As far as `committee_type`, I'm not sure, but the list of values that are currently present are the following:

committee_type | committee_type_full
------------- | -------------------
 I | Independent Expenditor (Person or Group)
 H | House
 S | Senate
 Y | Party - Qualified
 D | Delegate Committee
 Q | PAC - Qualified
 O | Super PAC (Independent Expenditure-Only)
 U | Single Candidate Independent Expenditure
 Z | National Party Nonfederal Account
 X | Party - Nonqualified
 V | PAC with Non-Contribution Account - Nonqualified
 E | Electioneering Communication
 C | Communication Cost
 N | PAC - Nonqualified
 P | Presidential
 W | PAC with Non-Contribution Account - Qualified

**Comment by LindsayYoung** [comment]
We are not teasing out joint committees, so I think this will work that is what we used designation for in the other charts

**Comment by LindsayYoung** [comment]
Just going to point out that we have the things by committee type, which is slightly different from the selections listed above

We would need to add designation to make a sub-set of PACs that are 
 - leadership PACs
 - hybrid PACs

**Comment by noahmanger** [comment]
Resuscitating this issue from the icebox in service of the findings from https://github.com/18F/openFEC-web-app/issues/2167 (cc @PaulClark2 )

**Comment by jenniferthibault** [comment]
This looks like it got closed in the great repo clean up of fall 2017, but is actually needed for the election summary workstream. Reopening.
