### ISSUE TITLE
Please check: Duplicate event entry on calendar

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC#1983]
I've been navigating around the calendar quite a bit today, and I noticed that the October Monthly Report entry was showing up twice on the calendar when I had the `Monthly` and `Quarterly` filters selected.

https://beta.fec.gov/calendar/

<img width="1271" alt="screen shot 2016-10-18 at 2 37 33 pm" src="https://cloud.githubusercontent.com/assets/11636908/19491309/8380750a-9540-11e6-96cd-0a3098e41549.png">

I tried to stress test and re-create the issue by applying/removing filing deadline filters, and it made the duplicate disappear, then I couldn't replicate the issue again.

<img width="1267" alt="screen shot 2016-10-18 at 2 41 15 pm" src="https://cloud.githubusercontent.com/assets/11636908/19491437/f738a18e-9540-11e6-9143-236cc78af7d6.png">

This is really weird, because the duplicate was hanging around long enough that I came here to file the issue, and now I can't re-create it.

Whaaaaaat 👻  ?? Maybe worth someone else trying to replicate this, and if you're not able, we can close & dismiss the issue.

**Comment by noahmanger** [comment]
Not able to replicate this, so closing (with Jen's blessing :) )
