### ISSUE TITLE
Report endpoint fails to filter on committee_type

### ISSUE THREAD

**Issue by jontours** [18F/openFEC#1985]
Found this issue while implementing the `.fec` urls.  The fix is proving to be particularly challenging.

**Comment by jontours** [comment]
Resolved by PR here: https://github.com/18F/openFEC/pull/1986.  Just a little bit of sql alchemy work.  Joins can do some weird things if a filter is added that the library can't glean what table is needed to query from the join.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1986
