### ISSUE TITLE
ATO renewal process

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1993]
- [x] Meet with Jez and understand the questions
- [x] divide sections across the devs
- [ ] complete sections
- [ ] collective review

**Comment by LindsayYoung** [comment]
Jez was extremely helpful! and I got a hold of Noah. This is better than I thought it would be.

(page numbers will change as we fill out the form)

## Site security plan tasks
 - [ ] Categorization of information types  2.1 (page 9) list the kinds of information we have in the system, and implications if there are interruptions in integrity, and availability. (Leave confidentiality blank)
 - [ ] User roles and privlages 9.2 (page 15) Admin, FEC and Public, describe their roles and privlages
 - [ ] Network Diagram 9.4 (page 16)
 - [ ] Software inventory 10.1 (page 17) List major things we use like EC2 and RDS boxes
 - [ ] Data flow diagram 10.1.4 (page 19)
 - [ ] System interconnections 11-1 (page 20) work with FEC to list system that gives us data

(Don't worry about most of the sections or the sections where the comments mention Noah)

@adrianwebb and @jontours feel free to add to the comments or this list if I missed anything.

**Comment by ccostino** [comment]
I believe the software inventory is mostly finished, but I would definitely appreciate other 👀 on it!

**Comment by PaulClark2** [comment]
Do you need anything else from FEC? Or, was the information from Rohan I forwarded sufficient?

**Comment by LindsayYoung** [comment]
What Rohan gave us was great, Paul. There might me follow up questions, but not at this stage. Thanks again!

**Comment by noahmanger** [comment]
We have issues for the remaining tasks, so I'm closing this.
