### ISSUE TITLE
Missing Archive MUR pdfs

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#1996]
This may already be covered somewhere but there are missing PDFs in the archive mur system. I think most of them have been merged with other MURs but I'm working on finding out. Here is the list that are   @adrianwebb 

1228
 1793 
 1829
 1999
 2152
 2174
 2222
 2229
 2263
 2526
 2593
 2597
 2630
 2652
 2707
 3051
 3078
 3087
 3111
 3226
 3303
 3320
 3407
 3416
 3428
 3516
 3542
 3560
 3867

**Comment by adrianwebb** [comment]
Waiting on research from FEC to see how these could be connected

**Comment by LindsayYoung** [comment]
@jwchumley can we close this?

**Comment by PaulClark2** [comment]
I'm not Jeff, but yes.
