### ISSUE TITLE
Create endpoint for total IEs per state

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#1997]
So that users can see how much money was made in IEs for and against candidates by location, create an endpoint to show this data.

![example](https://cloud.githubusercontent.com/assets/1696495/19176160/08c29f16-8bf2-11e6-9cf3-21f284f44447.png)

**Completion criteria:**
- [ ] Total money spent for _or_ against a candidate per state, divided by House and Senate candidates
- [ ] Provide totals for as far back as we can go
- [ ] Results can be filtered by two year period

**Comment by jontours** [comment]
@noahmanger @ccostino  figuring out the sql needed here for this.  To clarify, the locale of the expenditure should be based on where the contribution came from?  So for example that would be `payee_state`. And finally how is that different from the other issue: #1973?

**Comment by noahmanger** [comment]
The locale is actually the state of the candidate that was either support or opposed by the IE. So if you're looking at a state, the amount is the total amount of IEs made for or against house and senate candidates running in that state.

**Comment by noahmanger** [comment]
Also: We decided in sprint planning that we weren't going to worry about the filtering or sub-totals for this right now. We're just interested in the total amount, regardless of which type of committee made it.
