### ISSUE TITLE
create goldengate update log

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2004]
There was a update discrepancy and it would be good to know what golden gate logs we are given. So, I purpose instead of deleting the queue when we update we move that into a processed table so we can more easily investigate where any holes might exist.

**Comment by LindsayYoung** [comment]
## Background:

We have noticed some instances where data is in the underlying fec_vsum_schedule_a  but doee not get into the corresponding ofec_schedule_a_ table. schedule A and B work the same way, so if there is a problem with A, the same problem almost surely exists in schedule B. These are our largest tables. Schedule A is itemized receipt information and schedule B is itemized disbursement information. 

Every night we run `manage.py update_aggregates`  This refreshes our materialized views and partitioned tables. 
 
In particular, to refresh schedules A and B, that will run: 
  partition.SchedAGroup.refresh_children()
  partition.SchedBGroup.refresh_children()

Those functions draw from a queue of changes. For schedule A that would be ofec_sched_a_queue_old and ofec_sched_a_queue_new. Records are added deleted or replaced using those queues. Those queues get created 

Those queues get created initially when we partition and then are updated and are updated with a trigger. 

Schedule A and B work the same way, so if there is a problem with one, the same problem almost surely has the same problem.

## This issue:

We have been deleting the logs as we update, but it makes it hard to pin down where errors are coming form so one of the ideas is to move the possessed record to a new queue that we could check. That was what this issue was intended for, but if you find another lead or have better ideas, we can shift focus.

Thanks!

**Comment by ccostino** [comment]
@vrajmohan, please feel free to reach out to us with any additional questions, a walkthrough of the process, etc.  Happy to help!

**Comment by LindsayYoung** [comment]
This cropped up again.

It is probably a timing issue. We are looking at when they are timestamped on the FEC side to identify what records are new. There are separate process that trigger this update, if the record was delayed along the way, it might miss the processing window. There could be something else going on here but that is my best guess.

Here are options:

1) create a back up process, after updates look at recent records and upsert any that are missing and create a log of records that were missed.
      - less risky because it keep the current process in place, but augments it and documents what the problem is.

2) Adapt the current process to look at a wider range of dates and make sure it can handle records that have already 
   - less redundant but would require more work and checking
   - would not fix the problem if the root issue is not timing

For schedule E, it would be best to add indexes to the view and use it directly (check with Rohan and Paul if this is okay to try on dev)

**Comment by noahmanger** [comment]
This should resolve this issue https://github.com/18F/openFEC/issues/2117 

Check back in on that after we do this.
