### ISSUE TITLE
Add legal data to the test dataset 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2006]
Grab some data from the DB and add those tables to data/subset.dump
- [ ] AOs
- [ ] MURs

**Comment by LindsayYoung** [comment]
@anthonygarvan can you get to this? It would be helpful for the FEC folks ramping up

**Comment by LindsayYoung** [comment]
Rohan might be up for doing this I am checking with him.

**Comment by noahmanger** [comment]
@LindsayYoung Can this wait until next sprint?

**Comment by LindsayYoung** [comment]
There is an email thread were people setting up the DB need some test data. If it is being created now, it should be checked in, so we don't lose it and and have to reproduce it later.  

If FEC doesn't create it or need it now, then it can wait.
