### ISSUE TITLE
ofec_sched_a_aggregate_state has 271 distinct state values

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2010]
While I was starting work on #1973 I was trying to piece together totals by state, only to seem some very bizarre values.  Investigating further with a `select distinct state, state_full from ofec_sched_a_aggregate_state order by state;` on the table yielded 271 different kinds.

We should look into how we can fix/clean this data up, if at all possible.  As a sampling of some of the values:

| state | state_full |
| --- | --- |
| - |  |
| ?? |  |
| . |  |
| .. |  |
| # |  |
| 0 |  |
| 01 |  |
| 02 |  |
| 03 |  |
| 06 |  |
| 1 |  |
| -1 |  |
| 10 |  |
| 11 |  |
| 12 |  |
| 13 |  |
| 15 |  |
| 17 |  |

**Comment by ccostino** [comment]
It could be that some of these states are being referenced by an alternative code as opposed to the usual state abbreviations.  There's a great [reference on Wikipedia[(https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations) that shows a lot of the different codes and identifiers.

We also have a table called `ofec_fips_states` that has these mappings, so it might be a matter of just doing some data cleanup where possible?

**Comment by jontours** [comment]
And since this is a `ofec` table thankfully we have complete control over how it's created.

**Comment by ccostino** [comment]
Another thought came across my head - this will likely have to happen as a refresh task, so this is something that should likely be cleaned before other tables are built with the data it relies on.  Or is there some place even earlier in the process that we should be cleaning state values?  This is derived from `ofec_sched_a` as it is, so is it possible that we should have a state/territory clean/validate function?

**Comment by jontours** [comment]
Yeah that would probably be the better place to clean the states field up, via a function.
