### ISSUE TITLE
Groom product feature backlog

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2018]
We need to begin PI planning with a groomed backlog of product *features* (not stories). These features should be fleshed out to explain what we're after and why we're after it. 

---

My thought is that I'll take the lead on doing this for product features. @adrianwebb do we also want to do this for the transition work as well?

**To do:**
- [ ] Do first pass at grooming backlog for data, content and legal
- [ ] Review and discuss backlog with FEC partners

**Comment by adrianwebb** [comment]
@noahmanger: Yep, I'll take the lead on doing this for the transition work.

**Comment by LindsayYoung** [comment]
I think next sprint is a great time for bugfixes, do some security upgrades and start moving what we can to govcloud, I might be late to the grooming for data but here are the tasks I know of.

Moving to gov cloud:
- create FEC org with dev staging and prod spaces (we have not used feature too much lately)
- create cs service
- move s3 buckets (data downloads, legal and content)
    - give pat creds to the new content bucket
- cms
    - move db and upgrade to postgres (James Scott said he might help with this)
    - use built-in routing feature instead of the proxy app
    - make sure new relic is going
    - make sure deployment works with the invoke task
    - make sure deployment works by travis
- API
    - move and upgrade elastic search
    - move celery
    - move celery beat
    - use built-in routing feature instead of the proxy app
    - make sure we can maintain our integration with data.api.gov 
    - make sure we have access to our RDS boxes 
    - make sure new relic is going
    - make sure there is access to mandril for error emails
    - make sure deployment works with the invoke task
    - make sure deployment works by travis
- webapp
    - use built-in routing feature instead of the proxy app
    - make sure new relic is going
    - make sure github is reachable by the app for feedback
    - make sure ethnio is reachable by the app for feedback
    - make sure deployment works with the invoke task
    - make sure deployment works by travis
- fec eregs
    - move and upgrade elastic search
    - make sure new relic is going
    - make sure deployment works

ATO tasks:
   - upgrade Django on the cms and eregs
   - set X-Frame-Options Header (from concorse, possible false positive)

**Comment by noahmanger** [comment]
Thanks, @LindsayYoung . I just made new issues for these, broken out in a way that seemed to make sense.
