### ISSUE TITLE
Incomplete info and duplicates for schedule E

### ISSUE THREAD

**Issue by hobbes3** [18F/openFEC#2022]
I recently did a new pull of Schedule E for both Clinton and Trump and it's very short:

Opening file /data/trump_schedule_e.json
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&per_page=100&is_notice=False&api_key=DEMO_KEY&candidate_id=P80001571
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=1.23&last_index=4101320161340957359&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=3.13&last_index=4101320161340960514&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=34.2&last_index=4101320161340960576&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=34.2&last_index=4101320161340960796&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=44.8&last_index=4101320161340961130&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=250.0&last_index=4101920161344296815&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=750.01&last_index=4102420161344575573&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=164978.48&last_index=4102520161345202865&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=107435.72&last_index=4102720161345547366&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=2846.0&last_index=4121020151259622857&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=2622.09&last_index=4121420151259686650&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=1159.72&last_index=4121420151259686684&is_notice=False&candidate_id=P80001571&per_page=100&api_key=DEMO_KEY
Done for /data/trump_schedule_e.json

Opening file /data/clinton_schedule_e.json
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&per_page=100&is_notice=False&api_key=DEMO_KEY&candidate_id=P00003392
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=1.08&last_index=4091220161316995590&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=2.59&last_index=4091220161316996202&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=3.0&last_index=4101320161340937464&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=3.13&last_index=4101320161340949493&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=3.13&last_index=4101320161340956375&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=5.32&last_index=4101320161340957973&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=9.3&last_index=4101320161340958116&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=9.5&last_index=4110820131198635115&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=46.65&last_index=4110820131198635613&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=785.85&last_index=4110820131198635621&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=901.85&last_index=4110820131198635666&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=3217.98&last_index=4123120081103535357&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=19193.05&last_index=4123120081103535387&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=1539.71&last_index=4123120081103535397&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
https://api.open.fec.gov/v1/schedules/schedule_e/?sort=expenditure_amount&last_expenditure_amount=1026.07&last_index=4123120081103535399&is_notice=False&candidate_id=P00003392&per_page=100&api_key=DEMO_KEY
Done for /data/clinton_schedule_e.json

Also there seems to be a lot of duplicates. For example this entry appears 11 times!

    {"payee_suffix":null,"memo_code_full":null,"schedule_type":"SE","candidate_first_name":"DONALD J","payee_prefix":null,"payee_state":"DC","payee_middle_name":null,"filer_first_name":"ADAM","dissemination_date":"2015-11-12T00:00:00","candidate_name":"TRUMP, DONALD J","back_reference_transaction_id":null,"conduit_committee_street1":null,"payee_city":"WASHINGTON","memo_code":null,"candidate_prefix":null,"candidate_office":"P","office_total_ytd":1152076.01,"action_code":"A","expenditure_amount":32.68,"original_sub_id":null,"memoed_subtotal":false,"report_type":"M12","conduit_committee_city":null,"cand_office_district":"00","conduit_committee_name":null,"category_code_full":null,"notary_sign_name":null,"filer_suffix":null,"committee_id":"C00487470","payee_name":"CLUB FOR GROWTH","category_code":null,"notary_commission_expiration_date":null,"payee_last_name":null,"payee_street_2":"SUITE 600","filer_middle_name":null,"action_code_full":"ADD","back_reference_schedule_name":null,"line_number":"24","conduit_committee_state":null,"conduit_committee_street2":null,"candidate_id":"P80001571","election_type_full":null,"report_year":2015,"candidate":{"idx":60723,"two_year_period":2016.0,"candidate_id":"P80001571"},"support_oppose_indicator":"O","file_number":1035455,"election_type":"P2016","schedule_type_full":"ITEMIZED INDEPENDENT EXPENDITURES","payee_zip":"20036","expenditure_description":"PRESS RELEASE (FROM ADVANCE LINE 21)","filer_prefix":null,"committee":{"party_full":null,"committee_id":"C00487470","state_full":null,"expire_date":null,"cycles":[2016,2012,2010,2014],"treasurer_name":"ADAM ROZANSKY","party":null,"committee_type_full":"Super PAC (Independent Expenditure-Only)","street_1":"2001 L ST NW STE 600","candidate_ids":[],"street_2":null,"state":"DC","designation":"U","committee_type":"O","organization_type":null,"zip":"20036","organization_type_full":null,"name":"CLUB FOR GROWTH ACTION","designation_full":"Unauthorized","city":"WASHINGTON","cycle":2016},"notary_sign_date":null,"payee_street_1":"2001 L ST., NW","expenditure_date":"2015-11-12T00:00:00","candidate_last_name":"TRUMP","conduit_committee_zip":null,"conduit_committee_id":"C00487470","independent_sign_date":"2015-12-11T00:00:00","image_number":"201512119004174350","memo_text":null,"filer_last_name":"ROZANSKY","independent_sign_name":"ROZANSKY, ADAM","link_id":4121120151259670259,"sub_id":"4121420151259686654","candidate_suffix":null,"candidate_middle_name":null,"payee_first_name":null,"is_notice":false,"cand_office_state":"IA","filing_form":"F3X","pdf_url":"http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201512119004174350"}

I did a count of how many transactions are exact copies:

    copies  count
    1	    330
    2	    538
    3	    90
    4	    203
    5	    49
    6	    39
    7	    35
    8	    8
    9	    12
    11	    7

Also when I remove the duplicates (by `expenditure_date`, `committee`, `support_oppose_indicator`, `expenditure_amount`, and `candidate_id`) then the total `expenditure_amount` is $-274,817 (yes, actually negative).

**Comment by LindsayYoung** [comment]
Thanks for reporting this. We will take a look at what is going on.

**Comment by LindsayYoung** [comment]
OK the sort is acting inconsistently, for a reason we have not determined yet.

Right now, you can bypass the sort and get the data through download, if that is helpful. https://beta.fec.gov/data/independent-expenditures/?is_notice=false&candidate_id=P00003392&max_date=11%2F01%2F2016

We want to get this fixed ASAP

**Comment by hobbes3** [comment]
Thanks. The CSV download changes the way I was pulling in the data (my script was written to handle JSON), but are you suggesting the CSV will be more accurate?

I was sorting by `expenditure_amount` because you guys said there was a bug with the default sorting by `expenditure_date` before (some transactions had no `transaction_date`).

**Comment by LindsayYoung** [comment]
Just wanted you to know the CSV is a band-aid you can use as we work toward the solution, if you want.  We will try to get the fix in soon.

**Comment by LindsayYoung** [comment]
OK, we just deployed a fix. You won't need last expenditure amount or last expenditure date anymore but it should not throw it off if you do. 

There seems to still be an issue paging through nulls, which you can avoid by sorting by amount. We will fix the null issue in an additional PR.

We will also be writing additional sorting tests to ensure this does not happen again. 

Thank you for your patience

**Comment by hobbes3** [comment]
I did a recent pull and the data looks good! Thanks!

Now my only problem is the no spending in the past 3-4 weeks, but I believe you said I have to merge `is_notice=false` (what I'm only pulling now) with `is_notice=true` then de-duplicate it?

**Comment by LindsayYoung** [comment]
So glad this is working for you! Also talked with @jontours, who did the hard work of getting this going again, and he recommends still using last expenditure amount or last expenditure date.

For your totals, you want to look at the coverage dates of the summary reports and add notices that came in after the coverage date ends.

**Comment by jontours** [comment]
For now those extra sort parameters are needed.  This PR https://github.com/18F/openFEC/pull/2029 will make them optional, and also allow paging through rows that have nulls for the sort column.  Which for most of the data isn't a problem but there are a small subset of entities that have high incidence of incomplete data, i.e. null fields.
