### ISSUE TITLE
Make robust sorting test

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2025]
In the wake of sort-gate, lets add some tests that look at one of the schedules, ont per page and make sure sorting is working

 - that the value is going up or down as expected
 - that the sub ids can fluctuate and won't be dropped from results

**Comment by jontours** [comment]
I wrote a script that parses through sched_e pages (yes, sortgate is that bad) to test that things are working right.  May be able to adapt it into a test.

**Comment by LindsayYoung** [comment]
That would be wonderful!

**Comment by noahmanger** [comment]
This was the issue you said you had a fix for, correct @jontours ?

**Comment by jontours** [comment]
Yup this is it.

**Comment by noahmanger** [comment]
Is this resolved by https://github.com/18F/openFEC/pull/2029?

**Comment by jontours** [comment]
Yes.
