### ISSUE TITLE
last_index losing precision for itemized endpoints

### ISSUE THREAD

**Issue by jontours** [18F/openFEC#2026]
Change `last_index` to BigInteger (_should_ be trivial).  Last resort would be changing to string but may break some functionality.

**Comment by jontours** [comment]
As suspected this is an issue with chrome rounding off the last couple of integers.  To see for yourself, load a page like receipts, and instead of viewing the json output in the browser window.  Open developer tools and look at the unparsed payload of the http get, the `last_index` has no loss of precision.  So, in short, this is not an issue with us.  I'll leave open here in case we want to maybe notify users of the issue?

**Comment by noahmanger** [comment]
As discussed in standup yesterday, we can consider this resolved since it's a weird edge-case use where this would ever actually appear.
