### ISSUE TITLE
Create new cloud.gov org

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2030]
This issue is to get the new cloud.gov organization set up with the following basics:
- [x] Create spaces:
  - [x] production
  - [x] staging
  - [x] dev
  - [x] feature
- [x] Create cf service for secrets

**Comment by LindsayYoung** [comment]
submitted a request to get an org on gov cloud

**Comment by LindsayYoung** [comment]
I ported the credentials exactly as is, we will want to make some changes later, so that it points to the new API etc, as that gets created.
