### ISSUE TITLE
Move API to new cloud.gov

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2032]
The purpose of this task is to move the OpenFEC API to the new cloud.gov hosting. This requires the following tasks: 

- [x] Move and upgrade elastic search
- [x] Move celery
- [x] Move celery beat
- [x] Make sure we can maintain our integration with data.api.gov
- [x] Make sure we have access to our RDS boxes
- [x] Make sure new relic is going
- [x] Make sure there is access to mandril for error emails
- [x] Make sure deployment works with the invoke task
- [x] Make sure deployment works by travis
- [x] Move dev/staging/prod to cloud.gov url instead of 18F
- [ ] confirm cors is set correctly for public buckets

**Comment by LindsayYoung** [comment]
adding a cors check for public docs
we are still using the proxy for other things anyway, so I am taking that off the list

**Comment by LindsayYoung** [comment]
- API is having trouble connecting to Redis so the 
- Need to add index on election_date
