### ISSUE TITLE
Set X-Frame-Options Header

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2033]
As part of our ATO renewal, we need to set the X-Frame-Options Header from Concourse.

(I'm not sure what this means. Just carrying over from here https://github.com/18F/openFEC/issues/2018#issuecomment-258452576)

**Comment by jmcarp** [comment]
Just a drive-by comment, but everything that goes through cloud.gov should have the `X-Frame-Options` header set automatically, so this *should* already be done.

**Comment by LindsayYoung** [comment]
Your comments are always welcome! 

It came up in the concourse scan, so we were going to follow up with them. I have also notice the number of issues can vary wildly, when there are no code changes.

**Comment by LindsayYoung** [comment]
@adelevie made the coolest tool that separates out false positives- and we have 100s of them 

This was a false positive 

Thanks all
