### ISSUE TITLE
Note about expenditures

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#204]
17B data index it per file and paginate it by line order

**Comment by jmcarp** [comment]
Not sure what this means--can you elaborate (or close) @LindsayYoung?

**Comment by LindsayYoung** [comment]
Sorry for the cryptic message!

To do this, we would need to filter schedule B by line number- 17B are operating expenditures. Having the records in the order they appear on the form is important because sometimes people will write "see above" or something like that. 

I think this originated from a request of @jsfenfen

**Comment by noahmanger** [comment]
Still relevant?

**Comment by LindsayYoung** [comment]
We would need to add a filter by line order to schedule_b and verify that there is a way to order them by the order they appear on the reports. This is one of the things I want to keep but we have a bunch of other things we should probably address first.

**Comment by LindsayYoung** [comment]
Moving this conversation to #1355
