### ISSUE TITLE
Allow search for legal documents by both old and new citations (across reclassifications)

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2048]
Statutory citations have been remapped according to http://uscode.house.gov/editorialreclassification/t52/Reclassifications_Title_52.html. E.g., `2 USC 432` became `52 USC 30102`. Legal documents may mention the old statute, the new statute, or both. There is a requirement to search for these documents using _either_ the old citation _or_ the new citation.

**Comment by noahmanger** [comment]
Does this make sense to just roll into the issue for cleaning up citation data, or do we want to keep this separate? https://github.com/18F/openFEC/issues/2123

**Comment by vrajmohan** [comment]
As long as we have a solution for the user interface aspect of searching by a citation that is not actually present _in the same form_ in the legal document, this can be rolled into the issue for cleaning up citations.

**Comment by noahmanger** [comment]
Ok, UX issues being sorted out elsewhere and this work is included in this ticket https://github.com/18F/openFEC/issues/2123 , so closing.
