### ISSUE TITLE
Migrate off dimcmteproperties

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2049]
Warehouse | Postgres
--|--
dimcmteproperties | disclosure.fec_vsum_f1

This might be the tricky one to make sure we have the same fields

"We're also still using dimcmteproperties, since I didn't see another place to get treasurer name and address, custodian name and address, fax number, leadership pac, lobbyist registrant pac flag, and party committee type. Are those fields available in FECP? Or can we drop them?"
see full conversation: https://github.com/18F/openFEC/issues/1327

**Comment by jontours** [comment]
The only table in the database that contains these fields in the database is `disclosure.nml_form_1`.  @PaulClark2 @jwchumley It seems that replacing `dimcmteproperties` with `fec_vsum_f1` is a valid mapping to support migrating off that data warehouse table.  Can this please be confirmed?  Thanks.

**Comment by PaulClark2** [comment]
Yes, that should work. 

`fec_vsum_f1` will not include information from `nml_form_1z`

@jwchumley can you think of another way to replace `dimcmteproperties`?

**Comment by jontours** [comment]
We are about to merge this into the release and forgot about the column `expire_date` in dimcmteproperties, is that column deprecated?  Is it important to still have?

**Comment by PaulClark2** [comment]
I don't think it's important. We can determine the valid date range for a Form 1 based on it's receipt date and the receipt date of the F1 that amends (if it's amended).

**Comment by jontours** [comment]
Thanks @PaulClark2
