### ISSUE TITLE
Remove archived MURs from Elasticsearch so that current MURs can be released

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2053]
Removing archived MURs documents from `Elasticsearch` will allow releasing `betaFEC` with the current MURs functionality. A possible approach is:
- backup/export all MURs into an external format that can be processed and restored later
- delete all MURs from the indexes
- run only `load_current_murs`

This approach has the following advantages:
- the external export of MURs will allow us to fix the faulty `ids` discovered in https://github.com/18F/fec-eregs/issues/309, which can then be restored.
- the export can be used for re-import when upgrading `Elasticsearch` or migrating to `gov cloud`.

@anthonygarvan : Please review.

**Comment by vrajmohan** [comment]
I have backed up all MURs in each Elasticsearch instance (`dev`, `staging` and `prod`) to an index named `docs_backup`. I then deleted the MURs from the `docs` index and re-ran `load_current_murs`.

**Comment by noahmanger** [comment]
Excellent. Do we need to do anything else on this issue then?

**Comment by vrajmohan** [comment]
We should have someone test this in `dev` and `stage` environments. I have done this myself but we should have someone else do it as well.

**Comment by noahmanger** [comment]
Great. Can I tag @anthonygarvan or @tadhg-ohiggins in here?

**Comment by vrajmohan** [comment]
Assigning to @anthonygarvan for testing.

**Comment by vrajmohan** [comment]
Used https://www.npmjs.com/package/elasticdump to copy documents from `docs` to `docs_backup` using a command of the form:
```
elasticdump --input=https://elastic_url/docs/murs --output=https://elastic_url/docs_backup/murs
```
