### ISSUE TITLE
Add API support for initial AO filters

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2056]
In order to allow users the ability to further refine their search from a broad universe to a smaller one, add an initial set of filters to the AO search based on what we currently have data to support:

- AO number
- AO name
- AO issued date

This task is just to add the API support for these fields. I will make a separate issue for front-end implementation.

**Criteria for completion:**
- [ ] AO number accepts multiple values and returns all AOs with those numbers
- [ ] AO name accepts multiple values and returns all AOs with that name
- [ ] AO issued date accepts `min_date` and `max_date` and returns all AOs issued within the range

**Questions:**
For AO number and name, are we doing a fuzzy match or exact match? i.e. Does searching `197` in AO Number return `AO 1979-53: Ownership Campaign`? Does searching `Own` in AO Name return it?

For further background discussion, see https://github.com/18F/fec-eregs/issues/276.

**Comment by vrajmohan** [comment]
https://github.com/18F/openFEC/pull/2091 references this issue. It will be helpful if this issue has answers to the questions raised in the main summary. I tried following the referenced background discussion and got lost :-)

**Comment by noahmanger** [comment]
You're asking about the question about fuzzy matching AO numbers and names? Yeah, we never answered that (and it wasn't answered in the background discussion). It was more of a question that I was curious about. 

I don't know that we know what the desired behavior is (exact vs. fuzzy). @nickykrause do you know? If we don't know, I propose we just go with whatever we have on by default and then refine from there.

**Comment by vrajmohan** [comment]
I was asking because the answer has a bearing on the code that I am reviewing.

**Comment by nickykrause** [comment]
@noahmanger I don't know the answer--- but then, I'm not sure that I know the question. I'm assuming we're asking about whether or not a not-exact ("fuzzy") match for an AO number would be acceptable when searching (meaning: it would return results that are by some criteria deemed "close" to the original query). 

I would imagine that fuzziness would be okay for the AO name but not for the number, but that is solely my opinion -- not based on any evidence

**Comment by noahmanger** [comment]
Ah sorry for not resolving this sooner. To rephrase, I'm wondering about partial matches. To use my example above: Does searching `197` in AO Number return `AO 1979-53: Ownership Campaign` because `197` is part of `1979`? Or do you need to search `1979-53` to get that? I think I agree with Nicky that we'd want this to be exact, otherwise you'd get a lot of false hits.
