### ISSUE TITLE
Add API support for additional AO filters

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2057]
In order to allow users the ability to further refine their search from a broad universe to a smaller one, add additional filters to the AO search beyond the [initial filters](https://github.com/18F/openFEC/issues/2056):

**Completion criteria:**
- [x]  **Pending AO:** Should be a boolean flag based on whether an AO has been closed with either a final opinion or withdrawn. 
- [x] **Document type:** Accepts the following options:
  - Final Opinion
  - Withdrawal of Request
  - AO Request, Supplemental Material and Extensions of Time
  - Comments and ex parte Communications
  - Draft Documents
  - Commissioner Statements
  - Votes
- [x] **Requester entity type:** Accepts one or more of the following options:
![image](https://cloud.githubusercontent.com/assets/1696495/21246866/2f4a631a-c2e0-11e6-8ba2-dffe98ac576f.png)
- [x] **Requester name:** Accepts multiple strings that return matches of the name of the entity who requested the AO

For further background, see [this issue](https://github.com/18F/fec-eregs/issues/276).

**Comment by nickykrause** [comment]
description of [entity type](http://saos.fec.gov/saos/tips.html#_Entity_Roles_and)

**Comment by noahmanger** [comment]
After talking this through with @nickykrause just now, I realized that there's a few more open questions around all of this stuff and that I lost somethings in translation. So to clarify:

First, I think the original determination [made here](https://github.com/18F/fec-eregs/issues/276#issuecomment-258505291) to treat "Pending AOs" as a possible value in "Document type" is actually incorrect. I believe what we want here is actually a boolean flag that's set on the AO _as a whole_ that says whether or not this AO has been resolved or if it's still pending.

This is different from a "Document type" filter which essentially is a refinement tool on the keyword search, telling the system to _only_ search within the selected documents _within_ an AO for matches. @AmyKort is this understanding correct? 

And if so, @anthonygarvan do we have the necessary data to support a `pending: true / false` type flag? Do we even have the pending AOs? I see there's [just a couple](http://saos.fec.gov/saos/searchao;jsessionid=51CB60DED462B492F42996DA17B6C74A?SUBMIT=pending).

As for the "Document type" filter, it accept one or more of the 7 possible values: 
  - Final Opinion	
  - Withdrawal of Request
  - AO Request, Supplemental Material and Extensions of Time	
  - Comments and ex parte Communications
  - Draft Documents	
  - Commissioner Statements
  - Votes

When a value is checked, the keyword search should be limited to the selected documents and the search results should display the hits in each of those documents. There's a few questions around how exactly this should be presented, but Nicky has some good thoughts from looking at this for so I don't think we're far from an answer.

I have a separate set of things about the entity name / type filters, but I'll let us resolve this first.

@anthonygarvan I set up time for us and @nickykrause to sync up on Thursday about this so that we can get you started with what we can.

**Comment by AmyKort** [comment]
Yes, if I'm understanding this right. I don't think you would want to restrict a search within an AO file to "pending."  That wouldn't make a lot of sense. 

If an AO is pending, you're looking at it with the understanding that a question is out there and an answer is coming. So, its pending status isn't a subset of the information in the file--it's the nature of the whole file.

**Comment by noahmanger** [comment]
Thanks @AmyKort . I've updated the main issue with a more accurate set of criteria that separates out the "pending" status from "document type". 

After talking with Nicky, we also think we should narrow down "entity" stuff to just "requestor" for now. That's the only role that currently supports the "entity type" filter, so I think it makes sense to have a field called `requester type` and one called `requester name`.

**Comment by noahmanger** [comment]
Resolved by #2127
