### ISSUE TITLE
Identify which filters and sorting options to include for raw efile data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2064]
In order to have a performant system that also meets the needs of users, we need to identify the bare minimum _sorting_ and _filtering_ options to include for itemized efile data sets. 

---

This should be done in tandem with design and dev to make sure we're choosing the right things that also keep the system running smoothly. 

**Completion criteria:**
- [x] List of filters and sorting options for receipts
- [x] List of filters and sorting options for disbursements
- [x] List of filters and sorting options for independent expenditures

**Comment by noahmanger** [comment]
Alright, here's a first pass at what I think we need. I started with the bare minimum that I think we need to make each of these useful, and added some "Maybes" as well. 

## Schedule A
Filter:
- Recipient committee ID 
- Contributor name
- _Maybe: City, state or employer_

Sort:
- Date
- Amount

---

## Schedule B
Filters:
- Spending committee ID
- Recipient name
- Recipient committee ID
- _Maybe: Description or purpose_

Sort:
- Amount
- Date

---

## Schedule E
Filter:
- Spender ID
- Candidate ID
- Support oppose indicator
- _Maybe: Filing form_ 
- _Maybe: `is_notice`_

Sort:
- Amount
- Date


What do you think @LindsayYoung @jwchumley @PaulClark2 and @ChristianHilland think.

**Comment by jwchumley** [comment]
Shouldn't the filters pretty much match the already existing transaction search filters?


That aside, here are some comments on the ones you have listed:


SA - OK


SB - Recipient committee ID will only be partially populated and not terribly reliable. Those get added and corrected during exception processing which doesn't happen to the realtime efiling data.


SE - Candidate ID is also added or corrected during exception processing and won't be as useful here as it is in the processed data. A quick check on Schedule E shows about 40,000 rows in 2016 that were corrected during exception processing out of about 290,000 total rows.





________________________________

**Comment by noahmanger** [comment]
Ah! This is exactly what we needed to figure out. In order to keep things performant, we need to keep the number of filters and sorting options small. So I wanted to identify the bare minimum and then we can add from there.

For SA & SE, do you have the recipient / candidate **name** as text? Should we do that instead?

**Comment by jwchumley** [comment]
Typically yes, the text is there.

________________________________

**Comment by LindsayYoung** [comment]
I think for this, it depends on who the user is. We might need to do both. If I have a program running this data the text is probably not good enough to use, unless I am only looking at a subset of candidates. For people querying directly, name might be more useful.

**Comment by noahmanger** [comment]
@LindsayYoung what do you mean by do both? As I understand it from Jeff, the IDs aren't in the raw data; that's part of the value-add process.

**Comment by PaulClark2** [comment]
@noahmanger you are correct.

SB - recipient committee ID is not always populated in the submitted .fec files. 

SE - candidate ID is not always populated in the submitted .fec files.

**Comment by LindsayYoung** [comment]
Yea, @noahmanger @jwchumley is right no candidate ID at all... adds that to the efiling study

**Comment by noahmanger** [comment]
Ok, so here's my revised suggestion. If it's possible to have a candidate name text search on SE I think that would be really helpful. 

## Schedule A
Filter:
- Recipient committee ID 
- Contributor name
- _Maybe: City, state or employer_

Sort:
- Date
- Amount

---

## Schedule B
Filters:
- Spending committee ID
- Recipient name
- _Maybe: Description or purpose_

Sort:
- Amount
- Date

---

## Schedule E
Filter:
- Spender ID
- Candidate mentioned (name only, not ID)
- Support oppose indicator
- _Maybe: Filing form_ 
- _Maybe: `is_notice`_

Sort:
- Amount
- Date

**Comment by noahmanger** [comment]
Following up from our conversation in grooming, we're going to start with this set of filters, including all of the maybes, and evaluate performance and can scale back as necessary. Closing this in favor of upcoming implementation issues.
