### ISSUE TITLE
Statutory citations with elided sections are loaded incorrectly

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2069]
When statutory citations specify the subsection but not the section (in which case it is a subsection of the section indicated by the previous item in a group), they are not loaded correctly by `load_current_murs`. E.g., in https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/6159/, the citation should be for _52 U.S.C. 30118(b)(3)(C)_, not _2 U.S.C. None(C)_.

**Comment by vrajmohan** [comment]
There are ugly edge cases like:
1.  434(a)(1),(a)(4)(A)(i),(a)(4)(A)(iii) - the entire subsection is specified
2. 432(c)(5), 434(b)(2),(3), 434(b)(4),(6)(B)(v) - a portion of the subsection is also elided
3. 433(a), 434(a)(2)(A)(i) and (iii), 434(a)(6)(A), 434(a)(11), 434(b), 434(b)(1),(2),(3) and (4), 434(b)(8), 441b, 441a(f), 441d(a)(1) | 103.4(b)(4), 104.3(d), 104.11(a), 104.18(a)(1) and (2) - elision uses `,` and `and` for association with the predecessor

**Comment by noahmanger** [comment]
Flagging this for @amypike @amykort . Question for all: is this something that needs to be resolved before this first release?

**Comment by AmyKort** [comment]
Yes.

**Comment by vrajmohan** [comment]
After a discussion with @jenniferthibault, @nickykrause , @emileighoutlaw and @anthonygarvan, we decided that we will only display one link per distinct _target_ citation. E.g., as we cannot link directly to 52 U.S.C. 30118(b)(3)(B) and can only link to 52 U.S.C. 30118, we will concatenate the text of all citations that have this link target and have a single link for them. This has the following benefits:
1. Considerable reduction in the use of vertical space.
2. Less user frustration as we avoid having multiple links to the same target.
3. It should be easer for humans to comprehend the elided citations at a glance as we do not bother to expand them. E.g., we would display "434(b)(2),(3), 434(b)(4),(6)(B)(v)" instead of "434(b)(2),434(b)(3), 434(b)(4),434(b)(6)(B)(v) ".
4. We will defer clean up of list conjunctions into a consistent form to a later sprint/issue. We will leave the use of commas, semicolons, "and", etc as is in the original source data.

In addition, we will implement a consistent citation text style as described in https://github.com/18F/fec-cms/issues/544, and copied here:

- 11 CFR _112.1(a)_
- 52 U.S.C. _§30123_
- (Periods and section symbol for `U.S.C.`
- No period or section symbol for `CFR`
- Linking only the part of the citation that follows `CFR` or `U.S.C.`

**Comment by AmyKort** [comment]
Sounds good. Thanks!
