### ISSUE TITLE
Enable stemming on searches for AOs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2074]
So that legal researchers receive the most relevant set of records, enable stemming on searches for AOs. 

---

Users need to have results show up when searching for variants of words: plurals, different tenses, etc. Whatever we did for MURs should be enabled for AOs as well.

It looks like this is already enabled on staging, and from looking at [the PR](https://github.com/18F/openFEC/pull/2016) it looks like it's just a command that needs to be run, correct? 

So is this just something to run with the next release?

**Comment by vrajmohan** [comment]
Recreated indices and re-ran the load of legal docs on all envs. This should be complete now.

**Comment by noahmanger** [comment]
This is active now. Thanks!
