### ISSUE TITLE
New filings endpoint missing receipt_date

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2080]
I just checked [the filings page on staging](https://fec-stage-proxy.18f.gov/data/filings/?data_type=processed) and am seeing `Invalid date` in the `Receipt date` column. I checked the [raw JSON](https://fec-stage-api.18f.gov/v1/filings/?api_key=&sort_hide_null=true&data_type=processed&sort=-receipt_date&per_page=30&page=1) and it looks like the responses are missing this field.

![image](https://cloud.githubusercontent.com/assets/1696495/20855232/200b4886-b8b0-11e6-9b9f-45d36a4c3b82.png)

**Comment by jontours** [comment]
Taking a look now.

**Comment by jontours** [comment]
Ah looks like the column changed to an integer date type as opposed to a date type column; super weird that it didn't complain when referencing this column; looks like the exception (if there was one) was just swallowed.

**Comment by jontours** [comment]
With that being said a PR to fix this should be coming shortly, I'll also make sure no other columns are mismatched types.
