### ISSUE TITLE
Committee search failing on production

### ISSUE THREAD

**Issue by jontours** [18F/openFEC#2088]
There is an issue with search failing on the backend for a committee search, is related somehow to the filings migration, the url is `https://api.open.fec.gov/v1/committees/?sort=name&page=1&api_key=DEMO_KEY&per_page=20&q=romney
`.  The failure is some postgres casting issue `sqlalchemy.exc.InternalError: (psycopg2.InternalError) failed to find conversion function from unknown to text`.

**Comment by jontours** [comment]
More detail on the bug can be found in the PR.

**Comment by noahmanger** [comment]
Is this still an issue?

**Comment by LindsayYoung** [comment]
closed by https://github.com/18F/openFEC/pull/2105
