### ISSUE TITLE
Some penalties missing from canonical MUR page when there are multiple penalties for the same disposition

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2092]
When there are multiple penalties for the same disposition, the canonical MURs page fails to display some of the penalties and associated respondents and citations. E.g., for MUR 4322, the page shows only:

<img width="851" alt="screen shot 2016-12-08 at 2 12 24 pm" src="https://cloud.githubusercontent.com/assets/2066204/21023884/69e535d0-bd50-11e6-9422-8151951ddb86.png">

The correct results should be:

<img width="724" alt="screen shot 2016-12-08 at 2 13 41 pm" src="https://cloud.githubusercontent.com/assets/2066204/21023914/8fa9904a-bd50-11e6-9237-802410f65bfb.png">

**Comment by nickykrause** [comment]
@vrajmohan Thank you for fixing this! I didn't realize it was a bug when I saw it. Glad you followed up!
