### ISSUE TITLE
Remove fec_url property from RFAI responses

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2094]
As originally noted [via the feedback tool](https://github.com/18F/FEC/issues/543), we're displaying links to .fec files for RFAIs, which don't actually have them.

![image](https://cloud.githubusercontent.com/assets/1696495/21058843/c897f83e-bdf4-11e6-84c8-1da0e966ad23.png)

We're checking for these URLs on the front-end and only display a link if the response is there, so I checked and it looks like [these responses](https://api.open.fec.gov/v1/filings/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&data_type=processed&form_type=RFAI&sort=-receipt_date&per_page=30&page=1) have this broken URL in the field:
`"fec_url": "http://docquery.fec.gov/paper/posted/.fec",`

We should only include a `fec_url` property if there's a real value. 

This isn't a pressing bug, but we should address soon.

**Comment by LindsayYoung** [comment]
This should be an easy add to the API logic
