### ISSUE TITLE
Missing presidential candidates from 1992

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2095]
https://api.open.fec.gov/v1/candidates/totals/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&election_year=1992&cycle=1992&election_full=false&sort=-receipts&per_page=30&page=1&office=P

It does return a count of 116 but no results.
The years before and after generate results.

**Comment by noahmanger** [comment]
Could this be another bug introduced by the data warehouse migration?

**Comment by LindsayYoung** [comment]
I can get the stuff to appear if it there is no sort hide null. 1992 presidential totals are null for some reason- this is an oddly specifically bug and it looks like it is on staging too.
