### ISSUE TITLE
Move some tables from public schema to other schemas

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2097]
move to **disclosure** schema:
- cand_inactive,
- cmte_valid_fec_yr

move to the **fecapp** schema:
- cal_category, 
- cal_event_category, 
- trc_election, 
- trc_election_dates, 
- trc_report_due_date, 

The trick to this is getting the test data right on other schemas. I think Jon has done this successfully. @jontours could explain how to do that?

**Comment by jontours** [comment]
The I think I did get a working implementation, and the trick was to keep the test data in public schema for the integration tests, but in the deployed configuration use whatever schema the table is stored under.  I belive I got that to work.  I can take a look at the the old PR for that and reference that here.
