### ISSUE TITLE
Add additional API fields for MURs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2099]
So that legal researchers can find the MURs to help them answer their questions, they should be able to filter MURs by various additional criteria.

---

This issue is for building out the API support for advanced filtering on MURs. We have a separate issue for adding the ["Document type" filter](https://github.com/18F/openFEC/issues/2071) and need to do additional scoping of the work for adding citations, so this issue is for adding the following:

- Case number
- Respondent name
- Election cycle
- Final commission disposition

The final commission disposition values are:
![image](https://cloud.githubusercontent.com/assets/1696495/21207863/8ed4dfac-c21f-11e6-847f-bce05aa70aa9.png)

**Completion criteria:**
- [x] `Case number` field accepts multiple values and returns results that exactly match the MUR number
- [x] `Respondent` field accepts multiple values and returns results whose respondent field includes the value
- [x] `Election cycle` field accepts multiple values and returns results with matching "election cycle" values 
- [x] `Final disposition` field accepts multiple values and returns results with the matching disposition

Anything else I can add here @vrajmohan or @anthonygarvan ?

**Comment by vrajmohan** [comment]
Need to leave this issue open for `respondents` and `final dispositions`.
