### ISSUE TITLE
triple check we are off data warehouse

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2102]
# Warehouse tables

blank entries signify there is not direct replacement

original schema | table/view name | new schema | new table name | confirmed
---|---|---|---|---
public | cal_category | fecapp | cal_category |  x
public | cal_category_subcat |  fecapp | cal_category_subcat |  not used
public | cal_event |  fecapp | cal_event |  x
public | cal_event_category | fecapp | cal_event_category | x
public | cal_event_status | fecapp | cal_event_status | not used (but want to ask what this is and if we should be using it?)
public | trc_election | fecapp | trc_election | x
public | trc_election_dates | fecapp | trc_election_dates | x
public | trc_report_due_date |  fecapp | trc_report_due_date | x
public | operations_log | staging operations_log | n/a
public | f_item_receipt_or_exp |  disclosure | f_item_receipt_or_exp | not used
public | f_rpt_or_form_sub |  disclosure | f_rpt_or_form_sub | x
public | v_sum_and_det_sum_report | disclosure | v_sum_and_det_sum_report | not used
public | CAND_CMTE_LINKAGE |  disclosure | cand_cmte_linkage | x
public | CAND_INACTIVE |  disclosure | cand_inactive | x
public | CAND_VALID_FEC_YR |  disclosure | cand_valid_fec_yr | x
public | CANDIDATE_SUMMARY |  disclosure | candidate_summary | not used
public | CMTE_VALID_FEC_YR |  disclosure | cmte_valid_fec_yr | x
public | COMMITTEE_SUMMARY |  disclosure | committee_summary | not used
public | EXPORT_SDRFORM98 | | | not used 
public | DIMCAND | | | not used 
public | DIMCANDOFFICE | | | not used 
public | DIMCANDPROPERTIES | | | not used 
public | DIMCANDSTATUSICI | | | not used 
public | DIMCMTE | | | not used 
public | DIMCMTEAGENT | | | not used 
public | DIMCMTEBANK | | | not used 
public | DIMCMTEPROPERTIES |  disclosure | cmte_valid_fec_yr | not used
public | DIMCMTERELATED | | | not used 
public | DIMCMTETPDSGN | | | not used 
public | DIMDATES | | | not used 
public | DIMELECTIONTP | | | not used 
public | DIMLINKAGES | | | not used 
public | DIMOFFICE | | | not used 
public | DIMPARTY | staging ref_pty | | not used
public | DIMREPORTTYPE |  staging | ref_rpt_tp | x
public | DIMYEARS | | | not used 
public | FACTHOUSESENATE_F3  | | | not used 
public | FACTINDPEXPCONTB_F5  | | | not used 
public | FACTPACSANDPARTIES_F3X | | | not used 
public | FACTPRESIDENTIAL_F3P | | | not used 
public | FORM_5 | | | moved to nml_form_5
public | FORM_57 | | | moved to nml_form_57
public | FORM_7 | | | not used 
public | FORM_76 | | | not used 
public | FORM_9 | | | not used 
public | FORM_91 | | | not used 
public | FORM_94 | | | not used 
public | SCHED_A |  x
public | SCHED_B |  x
public | SCHED_E |  x
public | VW_FILING_HISTORY |  disclosure | f_rpt_or_form_sub |

**Comment by LindsayYoung** [comment]
found a VW_FILING_HISTORY that needs to be removed

**Comment by noahmanger** [comment]
@LindsayYoung so does this table mean that any entry with "new table name" is blank are tables that need to be removed?

**Comment by LindsayYoung** [comment]
If it is blank, those have been moved to another table, not the same version of that table. If it says "not used" we are good because there is not a reference to that table in our codebase.

**Comment by noahmanger** [comment]
Hmm ok. But I'm having trouble understanding. What remaining changes do we need to do to completely get off the warehouse / for this issue to be closed ?

**Comment by LindsayYoung** [comment]
For completion of this issue, just look at the last row and "not used" or "x" are done

Task wise, we need to get off of `VW_FILING_HISTORY` in one place in the code. 

I think we are off sched_a, sched_b and sched_e but I need to check them. It just takes longer to check because when you look at the code we have things that use those names and you need to look at each time it comes up in the code to make sure it is a code reference and not a table reference.

**Comment by LindsayYoung** [comment]
also found a fec_vsum_f76 straggler
