### ISSUE TITLE
Clean up MUR reg and statute citation metadata and serve over API

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2123]
So that legal researchers can find MURs by the citations they make, clean up the metadata around these citations. 

---

As discussed in grooming, we decided that the best approach (for now) to searching for MURs by citation was to use the metadata associated with them, since the document text was going to be even messier and opens the door for false positives, like zip codes or phone numbers.

In order to do this, we need to do some data normalization of the existing meta data, as well as scrape certain documents for additional citations that we can then normalize and add to the metadata. 

Additionally, I think it also makes sense to add the bi-directional mapping of the reclassified code so that searching for USC 2 or USC 52 returns results that cite USC 2 or 52. I know we implemented this in one direction, but I believe we need to implement it in the other direction. 

**Completion criteria:**
- [ ] Scrape citations from MUR general counsel's report, final notifications and vote certifications
- [ ] Normalize all regulatory and statute citations in MURs to common format
- [ ] Complete mapping of reclassified code 
- [ ] Provide all citations in API response

Does this make sense @vrajmohan and @anthonygarvan ?

**Comment by vrajmohan** [comment]
Moved AO related tasks to a separate issue: https://github.com/18F/openFEC/issues/2164

**Comment by vrajmohan** [comment]
@jenniehbee: Can you please let us know the document types in which we should search for citations?

**Comment by vrajmohan** [comment]
The quality of the OCR of MUR documents is so poor that parsing them for citations is futile.
https://cg-191800bb-c3e9-42e8-bbe9-66c882ad858f.s3.amazonaws.com/legal/murs/current/55033.pdf is OCR'd as:
[55033.orig_ocr.txt](https://github.com/18F/openFEC/files/746479/55033.orig_ocr.txt). Of the 6 CFR citations in that document, only 1 can be parsed. In addition to the OCR present in the `fecmur` DB, I tried OCRing the doc using `Apache Tika` and the `python slate` library. Both these approaches yielded similar (poor) results.

**Comment by vrajmohan** [comment]
IMO, we should suspend this story until we can get better OCRs of the document images.

**Comment by noahmanger** [comment]
Sounds good to me.
