### ISSUE TITLE
Add AO citations to AO page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2124]
So that users can understand the relationship between different AOs, show which AOs cite a given AO and which AOs a given AO cites (both directions).

---

This is a front-end task for implementing the AO citations (both to and from an AO) on the AO page.

**Dependency:** [API support](https://github.com/18F/openFEC-web-app/issues/1759)

**Dependency:** [Finalizing designs of canonical pages]

**Completion criteria:**
- [x] Link to all AOs cited in this AO's final opinion
- [x] Link to all AOs that cite this AO in their final opinions

**Comment by jenniferthibault** [comment]
Original issue with mockup:
https://github.com/18F/fec-eregs/issues/193

**Comment by noahmanger** [comment]
Implemented and looking awesome. Nice work!
