### ISSUE TITLE
Committee endpoint issue

### ISSUE THREAD

**Issue by jontours** [18F/openFEC#2129]
An example endpoint `/v1/candidate/P80005341/committees/` is throwing a 500 error.  Ultimately the reason is that in the view `fec_vsum_f1_vw` the column `filing_form` is generated via a statement such as `filing_form = 'f1'`.  When the material views are refreshed this column gets converted to an unknown and then SqlAlchemy fails.  Altering the view `fec_vsum_f1_vw` and casting the column should resolve the problem (and then running update_schemas).

**Comment by jontours** [comment]
After thinking about this more we may have to tread cautiously around this problem, as it may be a problem in other spots.  I mean we can update this specific view in question, i.e. change to `filing_form = 'f5'::text` but there may be other spots where this syntax exists.  So we either need to notify the FEC (who created the view `fec_vsum_f1` that string literals need to be cast or explore further why postres refresh (or something) keeps converting these columns to the inferred type to `unknown`.

**Comment by LindsayYoung** [comment]
Pining here because we got a user who still needs this

**Comment by jontours** [comment]
I can take care of it, it takes dropping some views in and rerunning update_schemas.  Nothing crazy but may be temporary outage on production, maybe do later tonight?

**Comment by jontours** [comment]
Now fixed on staging and production.  Dev is a straggler as the views still need to be created there.

**Comment by noahmanger** [comment]
I missed this today because it's not in an epic. Is there more work needed on this still?

**Comment by jontours** [comment]
It's resolved.  I tried researching to see if I can find a root cause to no avail.   If any other columns need to be casted they probably would have become problems by now.  I don't like verification empirically but sometimes it's the best we have.
