### ISSUE TITLE
/schedule_e/efile/ filters and fields

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2135]
While developing the front-end for the raw schedule E data, I hit a couple missing features of the `/schedule_e/efile/` endpoint that would be nice to have:

- Nested committee info: the main sched_e endpoint returns a nested committee object, which would be nice to have here
- Full `payee_name` value. I see that there's `payee_first_name` and `payee_last_name`, could we combine them like on the processed one?
- Include `report_type` in the response

And then it would be nice to have these filters (or maybe I was just doing them wrong).
- Filter by `candidate_name`
- Filter by `date`
- Filter by `support_oppose_indicator`

**Comment by jontours** [comment]
@noahmanger All the supported filters are here: https://fec-dev-api.18f.gov/developers/#!/independent_expenditures/get_schedules_schedule_e_efile

But in short `support_oppose_indicator` is functioning, and for some reason I added a `candidate_id` filter instead of `_name`.  `date` is I'm guessing `expenditure_date` and should that be `max`, `min`?

**Comment by noahmanger** [comment]
Wow, I totally missed your last comment. That all sounds right and seems to work as expected. `candidate_id` really should be `candidate_name` because the ID is something that the FEC adds as part of their processing. Can you add that?

**Comment by noahmanger** [comment]
Ah ok. So I fixed it to use `candidate_name` with https://github.com/18F/openFEC-web-app/pull/1800 but I realized that the API seems to be case sensitive while filtering. Is this something we can fix?

**Comment by jontours** [comment]
I figured that was the problem, already fixed in the PR!   Good to be ahead every once in while.

**Comment by noahmanger** [comment]
Beautiful!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2159
