### ISSUE TITLE
Add missing 2017 - 2018 cycle tables for schedule A and B

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2136]
@jontours uncovered an issue in #2134 while trying to fix tests that started failing after the start of the new year, and it led both of us to realize an underlying problem:  we don't have child tables for the new, upcoming cycle of `2017 - 2018`.

I think this is doable relatively quickly and easily without needing to repartition completely unless we're missing data already, but I don't think we are (and I asked in the partners Slack channel to double check that).  In any case, here is what I believe this entails:

* Create a new management command, perhaps `add_itemized_partition_cycle` or something, and have it call the underlying `create_child` method in the partition objects directly with the specific cycle.
* Allow the user to specify a cycle, but by default have it just create one child table with the next cycle based off of last existing table and current calculated cycle (if the table already exists, then just print out a note to the user and exit the command immediately).
* Do this for both schedule A and schedule B together so they stay in sync.

Unfortunately we do need to take care of this now due to the fact that we are in 2017 and data will be coming soon.

**Comment by noahmanger** [comment]
Is this resolved by #2139?

**Comment by ccostino** [comment]
Yes, this is all set @noahmanger!  We do need to run a repartition in `dev`, but that's a separate task at this point.  I can take care of that over the holiday weekend.
