### ISSUE TITLE
Determine and implement how filters work w/o JS

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#214]
In the event that a person doesn't have JS, we should ensure that they can use the filters. Let's think about how best to do this and then implement our solution.

**Comment by noahmanger** [comment]
I just added a button inside a `<noscript>` tag like so:

![screen shot 2015-01-12 at 3 48 40 pm](https://cloud.githubusercontent.com/assets/1696495/5713565/868d2f06-9a72-11e4-925d-6df433135a49.png)

Haven't hooked it up to anything yet, but I think this is how we should handle it. If there's no objections, I'll close this out.
