### ISSUE TITLE
Add version status and amendment chain fields to efilng endpoints

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2147]
So that users can understand the version status and amendment chains of efiling data, include the same fields as on the processed data.

---

When I wrote the original API issue for adding amendment chain stuff, I neglected to specify that this should also be on the `/efile/filings` and `/efile/reports/*/` endpoints. So this issue is to add all the same fields to those endpoints so that when toggling between processed and raw data, all the same info is visible.

**Completion criteria:**
- [x] Add fields to `/efile/filings/` 
- [x] Add fields to base `/efile/reports/*/` endpoint (should exist on all report types within)

**Comment by jontours** [comment]
I'm hoping in the case of e-filings that the chain stays contained within the raw table; in that case this change will be easy to make.  It may be a question for @PaulClark2, specifically do all e-filed resources exist in the table for the raw efilings?

**Comment by jontours** [comment]
Looking at this now for feasibility.

**Comment by jontours** [comment]
I just verified that it is feasible to provide this, but there are a couple of ways to present it.  Right now I can write a pretty fast query (100 ms) that builds the amendment chain (but doesn't include the most_recent_filing).  Deriving the most_recent_filing bumps the query up to a second.  

So there are two options:  (1) do those queries live and take the performance hit or (2) build a materialized view with the fully processed chain, with the drawback that some records may not have an up to date chain (for only up to 24 hours), but it would be fast.  Depending on how often amendments are filed this may not be a problem (as the previous amendment in a newly updated chain may be provided already).  But again, I guess it just depends on how important the `most_recent` flag and `most_recent_filing` column is.

**Comment by noahmanger** [comment]
@jontours did your PR include this info on both endpoints listed above or just `/filings/`?

**Comment by jontours** [comment]
eep,  looks like I left it out for `reports`.  I'm working on a PR to add some missing columns for this off the release so I'll take care of it there.  Thanks for checking up on this.
