### ISSUE TITLE
Create 404 and server error pages

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#215]
When the server throws a 404 or other server error page, we should have pages to show that aren't the default webserver ones. We should design, come up with copy and implement these pages.

**Comment by noahmanger** [comment]
- [ ] Design
- [ ] Implement in code

**Comment by noahmanger** [comment]
Ok, I ended up mocking this up anyway. First, a question. Treating 404 and server pages differently as my understanding is that the 404 page is for the purpose of "the thing you're looking for can't be found, please try something new" and the server error page is "something weird went wrong on our end, please try that same thing again."

## 404
![4 1 - 404 error](https://cloud.githubusercontent.com/assets/1696495/5968851/40979e8e-a7d1-11e4-89e7-c9a10418ab94.png)

## Other server errors
![4 2 - server error](https://cloud.githubusercontent.com/assets/1696495/5968852/44e111c8-a7d1-11e4-95ed-6bf80b29ddb9.png)

**Comment by rjmajma** [comment]
I like the new logo creeping in. I think breaking them up into a 404 and general (usually a 500, right?) works. Maybe a suggestion around the copy (and we should check with Kate about this), but is it worth asking the user to recheck their URL (in instances where they typed it out)? Also, who do you envision the contact support reaching?

Regardless, both look good but not as fun as other stuff @kaitlin found around the web.

**Comment by noahmanger** [comment]
Yep – copy definitely placeholder. I want smarter people's minds on that. 

And yeah — wish we could be funnier but alas :*(

**Comment by rjmajma** [comment]
...we can't be funnier?

**Comment by kaitlin** [comment]
I always liked the politwoops 404 page: http://politwoops.sunlightfoundation.com/404

Make sure to check out the css animation in the header (it actually breaks!) although the new hat at the very top seems to be messing with it a bit.

**Comment by LindsayYoung** [comment]
I am a fan of this one:
http://transparencycamp.org/404/

**Comment by noahmanger** [comment]
Yesss. I love both those. Ok, I'm in favor of being funnier in the copy we use, but I don't wanna burn much more time on these. 

These are now up in [InVision](http://invis.io/UH24CA2KD) so go check em out.

**Comment by noahmanger** [comment]
Oh, and a question for @theresaanna : On the 500 server error page, I was thinking it would be cool if we could have a button that would basically submit their request again. Is this possible? If not, I can take it out of the mock.

**Comment by LindsayYoung** [comment]
I could imagine this being a problem if the server is already having problems and then it gets even more requests. Like if we are trying to get the server up again and the cache got cleared I imagine people pushing this button immediately over and over again.

**Comment by noahmanger** [comment]
Good call @LindsayYoung . I removed that for now. 

Alright, these are coded up and ready in this PR: https://github.com/18F/openFEC-web-app/pull/23

**Comment by noahmanger** [comment]
Merged
