### ISSUE TITLE
Add email endpoint to rad-analyst section

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC#2151]
This ticket is to track adding the email endpoint to the rad-analyst section of the openFEC API: https://api.open.fec.gov/developers/#!/filer_resources/get_rad_analyst

**Comment by patphongs** [comment]
Email has been added to the table on our side. Should be able to implement this into the API now.

**Comment by noahmanger** [comment]
_Sounds like an excellent pairing opportunity_ :)

**Comment by patphongs** [comment]
Thanks @LindsayYoung for pairing with me on this. I've committed my changes to this branch: https://github.com/18F/openFEC/tree/feature/rad-analyst-email

I haven't done a PR yet because I wanted to make sure the sql update_schema will work against my local db instance. But you're free to take a look and test it too and merge in the changes if you see it looks ok.

**Comment by noahmanger** [comment]
This is done and has been pushed to production.
