### ISSUE TITLE
Decide how to move forward with the Slate library

### ISSUE THREAD

**Issue by dogweather** [18F/openFEC#2154]
Our codebase depends on Slate, an open source pdf-to-text lib which [my repocheck.com app scores 0 out of 10](http://repocheck.com/#timClicks%2Fslate) for effectiveness. E.g., PR's with bug fixes aren't being merged, and there've been no new commits in 11 months.

**I got blocked for a couple of days using openFEC because of (1) a bug in the code, and (2) the workaround we've been using.** The Slate team hasn't merged [one or more PRs which address it](https://github.com/timClicks/slate/pulls). There are other bugs in the code which produce warnings/errors for us, such as its use of `distribute`.

We've hacked our app's load path to workaround the "utils" bug, but our hack didn't account for the particular way I had installed Python (creating multiple dev virtual envs to help with testing these issues).

The paths forward I can think of are one or more of:
* Remove our hack, and use a fixed fork of Slate.
* Remove our dependency on Slate and switch to a well supported lib like python/tikka.

**Comment by jontours** [comment]
I've used tika with Java and strongly endorse it.  For what it's worth.

**Comment by dogweather** [comment]
Yep, @jontours tika is the highest quality PDF-to-text I could find when I surveyed a bunch a few months ago. I've heard other 18F people mention it; it might be becoming a quasi-standard solution at this point.

I [shell out to it from Haskell](https://github.com/dogweather/analyze-oregon-law-haskell) to parse two-column PDFs. I couldn't find any other lib that could do that.

**Comment by jontours** [comment]
Yeah I found it be quite versatile, there were some small edge cases where some words would get parsed from one word to a word per letter, e.g. foo -> f o o.  But it was in very limited edge cases, and was I believe traced back to PdfParser, the plug-in chosen for the Java implementation.  Probably doesn't apply here.

**Comment by LindsayYoung** [comment]
We might want to sit on this or remove the code until the MURS have been cleared and scrubbed and we need this functionality again.
