### ISSUE TITLE
Incorrect amendment status data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2158]
I'm QAing the version status display on [filings](https://fec-stage-proxy.18f.gov/data/filings/) and one thing I'm seeing in random places is filings showing up as "past versions" even though no newer version is available. Here's a handful of examples:

![image](https://cloud.githubusercontent.com/assets/1696495/21996976/97b980ba-dbe1-11e6-91a0-80909a22b3b7.png)

![image](https://cloud.githubusercontent.com/assets/1696495/21996850/07f0f2b0-dbe1-11e6-8c7b-f23bf086a69a.png)

![image](https://cloud.githubusercontent.com/assets/1696495/21996906/4d310dec-dbe1-11e6-9487-4971363d29d1.png)

![image](https://cloud.githubusercontent.com/assets/1696495/21996961/87438438-dbe1-11e6-873e-5ce18e4b1abb.png)

![image](https://cloud.githubusercontent.com/assets/1696495/21997007/c7e3b292-dbe1-11e6-92a5-8971b268e1a2.png)

![image](https://cloud.githubusercontent.com/assets/1696495/21997039/f4344b5e-dbe1-11e6-94d7-a068ec3349f2.png)

I'm not sure if this is a bug from the front-end or back-end, so tagging in @jontours and @xtine .

**Comment by xtine** [comment]
I am checking for `most_recent === true`, so if it returns anything other than that, it will show as a past version. Maybe the data is incomplete so it still shows past versions without the most recent one?

**Comment by jontours** [comment]
I'd check to see if the rows that are showing as not most recent but have not amendments have `most_recent: null` from the api.  In that case all you can't say if it's a past filing or not.

**Comment by xtine** [comment]
@jontours: if `most_recent: null`, then is there a way to tell if it's the most recent or past version at all?

**Comment by noahmanger** [comment]
Spot-checking the reported issues above and they all seem to be resolved. This looks _much_ better. Nice work! I'm going to close this.
