### ISSUE TITLE
Simplify Elasticsearch document schema

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2160]
The schema for MURs has evolved to be very complex - some of the naming and the nesting can be simplified. In addition, we should distinguish between semantic content and formatting, and index only the former (e.g. URLs for statutes, eregs, etc).  Also, some fields should not be indexed (e.g. document id and document length) - they now result in _false positives_. As an example, searching for `29599` (a document id) or `191956` (a document length) would yield MUR 5089, even though those numbers/terms don't appear in the actual semantic content of the MUR.

**Comment by noahmanger** [comment]
@vrajmohan resolved by https://github.com/18F/openFEC/pull/2172 correct?

**Comment by vrajmohan** [comment]
Yes and no. 1 down (MURS), 3 to go (statutes, regulations, AOs). I am on it.
