### ISSUE TITLE
Add legal endpoints to API docs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2161]
So that API users (internal and external) can best understand the legal endpoints, add them to the API docs. 

---

We need to flesh this out with completion criteria when we want to prioritize it.

**Comment by LindsayYoung** [comment]
We might want to have a public variant that is formatted the same as the rest of the API with pagination, API version and results dictionaries.

Also flagging that our swagger fork is 508 accessible, but behind the main fork
