### ISSUE TITLE
disbursement committee total off 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2162]
It looks wrong on production-
https://beta.fec.gov/data/committee/C00003418/?tab=disbursements&cycle=2016

It looks better on stage and dev-
https://fec-stage-proxy.18f.gov/data/committee/C00003418/?tab=disbursements&cycle=2016
https://fec-dev-proxy.18f.gov/data/committee/C00003418/?tab=disbursements&cycle=2016

**Comment by noahmanger** [comment]
Might it be fixed with our release?

**Comment by LindsayYoung** [comment]
I haven't dug in, so don't know what is causing it. It is possible the release will fix it but I am not expecting it.

**Comment by LindsayYoung** [comment]
Repartitioning looks like it did the trick
https://beta.fec.gov/data/committee/C00003418/?cycle=2016&tab=disbursements

This is another reason we should work on #2130
