### ISSUE TITLE
Clean up AO reg and statute citation metadata and serve over API

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2164]
Clone of https://github.com/18F/openFEC/issues/2123 for AOs only.

**Completion criteria:**
- [x] Scrape citations from AO final opinions and add to metadata
- [ ] Allow more complex parsing of citations
- [x] Normalize all regulatory and statute citations in AOs to common format
- [x] Complete mapping of reclassified code 
- [x] Provide all citations in API response
- [ ] Allow AOs to be filtered by multiple citation using `AND` and `OR` logic

**Comment by vrajmohan** [comment]
Unlike the OCRs of MUR attachments, AO documents of type 'Final Opinion' produce OCRs of a quality that is suitable for searching for citations. E.g., the document https://cg-191800bb-c3e9-42e8-bbe9-66c882ad858f.s3.amazonaws.com/legal/aos/62842.pdf is OCR'd as:
[62842.txt](https://github.com/18F/openFEC/files/746509/62842.txt)

**Comment by noahmanger** [comment]
@vrajmohan just added the point about allowing citations to be filtered using AND and OR.

**Comment by vrajmohan** [comment]
Most of the items on the list were fixed by @anthonygarvan. I will move the outstanding items to a separate issue to simplify the tracking.
