### ISSUE TITLE
Investigate issues with the RDBMS subsetter tool

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2170]
It looks like our instructions and process for pulling a sample of test data with the rdbms-subsetter tool are not working at the moment.  We should take a look and get this fixed again to make life easier.

Some tweaks did need to be made to get the tool itself working again, but I'm not sure where those ended up or if they even took place yet.

**Comment by jontours** [comment]
I'd be willing to pair/help out with this, I'm also interested in the tool itself.
