### ISSUE TITLE
Inform fec of view change for schedule_d.

### ISSUE THREAD

**Issue by jontours** [18F/openFEC#2180]
`pg_date` was missing, just used one of the tables `pg_date` column that is referenced in the view `fec_vsum_sched_d_vw`, the table is `disclosure.nml_sched_d`.  This table represents the creation of the filing and best captures the `load_date`.  FEC should be informed of this, in case they have scripts that created these views.

**Comment by LindsayYoung** [comment]
That might have been a leftover from the warehouse switch. The new tables don't have pg_date
