### ISSUE TITLE
Refactor schema for advisory opinions

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2186]
Similar to MURs, advisory_opinions also have a 1-many relationship with documents. Currently, we store each document separately in `Elasticsearch` repeat the advisory opinion metadata in each one of them. We should use a schema similar to MURs and store one `Elasticsearch` document per advisory opinion with multiple (regular) documents inside it.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2203
