### ISSUE TITLE
Advanced AO search filters searches by document type of "Final Opinion", even when no document type is checked

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2189]
The document type "Final Opinion" is checked by default when doing an advanced search of AOs. However, if this is unchecked, and no document type is checked, the search still filters by "Final Opinion"  _behind the scenes_. Is this behavior valid? Is this evident to the user?
@nickykrause, please add your comments.

**Comment by noahmanger** [comment]
There's a new issue for implementing this https://github.com/18F/openFEC/issues/2341 , so I'm closing this one.
