### ISSUE TITLE
Missing candidate from the Candidate Search in beta.fec.gov

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2197]
When I search for this candidate by id in beta he doesn't come up. 

https://beta.fec.gov/data/candidates/?q=H6MS01198&election_year=2016&election_year=2014&election_year=2012&has_raised_funds=true

If I search in Filings he shows up as a row but if I click on him it returns an error.
https://beta.fec.gov/data/filings/?data_type=processed&candidate_id=H6MS01198&max_receipt_date=02%2F09%2F2017

We confirmed that he exists in public.f2_filer_vw and the public.ofec_cand_cmte_linkage_mv.

Also that if you call the api with candidate ID H6MS01198 it returns his data.

Could you please look at this and see why he isn't showing up correctly in beta?
@LindsayYoung @ccostino @hcaofec

**Comment by ccostino** [comment]
Hi @jwchumley, thanks for reporting this!  I think this is likely due to an issue with the nightly refresh that we're tracking and plan to fix ASAP.  We'll investigate further and take a look as a part of that and let you know what we've found.

**Comment by jwchumley** [comment]
Thanks @ccostino.

**Comment by ccostino** [comment]
You're welcome!  After a bit more investigation it appears there's something else going on with this, so I'll continue to dig a bit and provide more info.  I just caught up briefly with @LindsayYoung and it's possible that some committee information is either missing or doesn't exist for this candidate, which might be causing the record to fail in appearing as some of that information is looked for when pulling up the candidate record for viewing.

I'm also noticing something else interesting, which is that the cycle is being set to an odd number year, which I don't think is correct.  So like I said, I'll continue to dig some and provide more information as I and others find it!

**Comment by noahmanger** [comment]
Yeah, the issue seems to be that his cycle is set to 2015. When I remove all election year filters, he shows up:
![image](https://cloud.githubusercontent.com/assets/1696495/22808927/9d5a2ae6-eee3-11e6-8ee4-1e077a907971.png)

Is it right that all cycle values should be even years? Or is our front-end too brittle and should account for potential odd years?

**Comment by LindsayYoung** [comment]
All cycles should be even, the election year can be odd.

It looks like the front end is passing election year instead of cycle. 

This works:
https://api.open.fec.gov/v1/candidates/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&q=H6MS01198&cycle=2016&sort=name&per_page=30&page=1

**Comment by jwchumley** [comment]
When a candidate runs in an off year the actual election year is odd be we always lump them in with the next even year. Not that you shouldn't be able to search for all candidates that ran in 2015 but when you search for all candidates that ran in the 2016 cycle you should find those that ran in 2015 and those that ran in 2016.

**Comment by noahmanger** [comment]
So the front-end filter is using the `election_year` param rather than `cycle`. I know we went back and forth on this in the past and can't remember why we would use this over the other. Any idea?

**Comment by jwchumley** [comment]
No idea in this context. If you select 2015-2016 you should get everyone that ran in an election that happened during that time.


________________________________

**Comment by LindsayYoung** [comment]
Yes swapping out election_year for cycle will do that

**Comment by jwchumley** [comment]
More examples for you:  

Column A on the "2016 Candidates Missing from Beta" Tab in the spreadsheet linked below shows about 57 candidates that are missing from the candidate search for 2016 (https://beta.fec.gov/data/candidates/?election_year=2016) and they were involved in off year elections.

https://docs.google.com/spreadsheets/d/1P_KtGlStcniFZBy2aGw_-cR7KOmdeOFeq3ahrF06KlM/edit?usp=sharing

@ccostino @noahmanger @LindsayYoung

**Comment by noahmanger** [comment]
@jwchumley this release will fix the issue of 2015 candidates not showing up. You can see on staging: https://fec-stage-proxy.18f.gov/data/candidates/

As for the other, we need to figure out why that is.

**Comment by noahmanger** [comment]
These all look to be resolved. Closing.
