### ISSUE TITLE
Additional parameters needed for datatables

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC#2200]
### [Schedule F](https://api.open.fec.gov/developers/#!/party-coordinated_expenditures/get_schedules_schedule_f)

2 more parameters need to be added to the API for those filters to work:

- [x] payee_name
- [x] committee_id

Also noticed a typo in the schedule_f model: canidate_name, should be 'candidate_name'.

### [Schedule D](https://api.open.fec.gov/developers/#!/debts/get_schedules_schedule_d)

5 more parameters need to be added to the API for those filters to work:

- [x] committee_id
- [x] creditor_debtor_name
- [x] nature_of_debt
- [x] amount_incurred_period
- [x] payment_period

**Comment by noahmanger** [comment]
Resolved by #1829
