### ISSUE TITLE
Missing values on /committee/committee_id/totals

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2212]
While redesigning the committee pages, I noticed some missing fields on the API response for `/committee/[committee_id]/totals/` that I think should be there.

For presidential, house-senate and pac-party types:
- [x] Beginning cash on hand
- [x] Debts/Loans Owed To

For pac-party types:
- [x] Total transfers
- [x] Loan repayments made

For presidential:
- [x] Net contributions
- [x] Net operating expenditures

@jontours can you look into how difficult it is to add these?

**Comment by jontours** [comment]
Looking into this now.

**Comment by jontours** [comment]
I think the fields that cover all the types will be easy, the fields in these tables are by cycle.  So my first assumption is that, say for beginning cash on hand, it will be a summation for all the records for that committee, that were filed for that cycle.

**Comment by noahmanger** [comment]
@jontours I think the logic will vary. For instance, beginning cash on hand should just be the `beginning_cash_on_hand` for the first report of the period. I'm not sure about the others. @LindsayYoung or @PaulClark2 could shed some light, I bet.

**Comment by jontours** [comment]
@noahmanger yeah, that's the logic that I ended up going with.  I kind of got hung up on this because the committee reports tab on the old FEC website would give the summary for an isolated report, where our `totals` endpoint is summing fields across all reports past the provided `START_YEAR`, or the cycle year passed in as a parameter.  So, there isn't a really 1:1 comparision but I _think_ know what is intended.

**Comment by jontours** [comment]
I think we are good to go with these.  The only fields that I found actually missing where `cash_on_hand_beginning_period` and `last_debts_owed_to_committee` (those are the fields as now defined in the api).  If the other fields couldn't be found they may have just been named something a little off from what is expected.

We have multiple transfer fields for pac/part: nonfed_transfers, transfers_from_affiliated_party, transfers from_nonfed_account, transfers_from_nonfed_levin, transfers_to_affiliated_committee.

Loan repayments is `loan_repayments_made`.

For net_contributions and net_operating_expenditures for presidential committees we have: `net_contributions` and `operating_expenditures`.

This PR will be testable and ready to go shortly.

**Comment by jontours** [comment]
The formula you gleaned is correct: 
```
 committee_id | transfers_from_nonfed_levin | transfers_from_nonfed_account |    sum     
--------------+-----------------------------+-------------------------------+------------
 C00233361    |                     1180.82 |                      10164.53 |   11345.35
 C00105668    |                   247116.81 |                    4193659.01 | 4440775.82
 C00188367    |                   120178.66 |                     534050.68 |  654229.34
 C00261891    |                      735.00 |                       3111.80 |    3846.80
 C00135558    |                    75456.00 |                    1011140.04 | 1086596.04
 C00150672    |                     8000.00 |                     984068.36 |  992068.36
 C00010439    |                    23980.58 |                     430229.08 |  454209.66
 C00161067    |                   111721.77 |                     282799.28 |  394521.05
 C00453712    |                       13.76 |                      24079.31 |   24093.07
 C00430108    |                     6767.29 |                      31525.67 |   38292.96
 C00500330    |                    54160.96 |                     113099.56 |  167260.52
 C00158402    |                      800.00 |                     219939.81 |  220739.81
 C00041269    |                   168000.00 |                     984972.22 | 1152972.22
 C00031054    |                   196527.02 |                    1398319.72 | 1594846.74
 C00019331    |                    24382.84 |                    1625216.15 | 1649598.99
 C00390641    |                     7384.00 |                      41741.46 |   49125.46
 C00303628    |                        0.10 |                          0.10 |       0.20
 C00179408    |                   131920.82 |                     534232.48 |  666153.30
 C00068056    |                       11.00 |                          1.00 |      12.00
 C00402826    |                    98367.03 |                     278552.32 |  376919.35
 C00143743    |                      110.00 |                    2934442.25 | 2934552.25
 C00166710    |                    78518.68 |                    1557310.60 | 1635829.28
 C00114439    |                    98754.32 |                    2098358.90 | 2197113.22
 C00008227    |                   203493.53 |                    1512607.16 | 1716100.69
 C00010033    |                   235129.26 |                    1151846.98 | 1386976.24
 C00174334    |                     6146.00 |                      14197.00 |   20343.00
 C00492132    |                        0.66 |                          6.00 |       6.66
 C00167320    |                     6215.00 |                     164500.00 |  170715.00
 C00031088    |                    88501.19 |                     846428.71 |  934929.90
 C00300731    |                     3448.69 |                     763499.93 |  766948.62
 C00025254    |                   102060.89 |                    2745469.61 | 2847530.50
 C00167015    |                  1251298.55 |                     992587.07 | 2243885.62
 C00041160    |                   149936.40 |                    3757628.63 | 3907565.03
 C00140590    |                   474938.13 |                    1962297.67 | 2437235.80
 C00252551    |                     6000.00 |                     447500.00 |  453500.00
 C00020818    |                   173541.39 |                     527356.57 |  700897.96
```

This will be simple to implement.

**Comment by PaulClark2** [comment]
Should not be summed across reports

Beginning cash on hand (amount from first report of the period)
Ending cash on hand (amount from most recent report (for current cycle) or last report (for prior cycles) of the  period)
Debts and Obligations Owed to committee (amount from most recent report (for current cycle) or last report (for prior cycles) of the  period)
Debts and Obligations Owed by committee (amount from most recent report (for current cycle) or last report (for prior cycles) of the  period)

**Comment by noahmanger** [comment]
Ah. Thanks for clarifying @PaulClark2 .

**Comment by PaulClark2** [comment]
Looking at the @jontours table above, I guess I'm a little confused about the information. I'm looking at the first entry -- C00233361.

Form 3X 
Line 18(a)  - nonfederal - tranf_from_nonfed_acct_per
Line 18 (b) - Levin funds - tranf_from_nonfed_levin_per
Line 18 (c) - total transfers - ttl_nonfed_tranf_per

CMTE_ID	|	RPT_YR	|	RPT_TP	|	CVG_END_DT	|	TRANF_FROM_NONFED_ACCT_PER	|	TRANF_FROM_NONFED_LEVIN_PER	|	TTL_NONFED_TRANF_PER
----	|	----	|	----	|	----	|	----:	|	----:	|	----:
C00233361	|	2015	|	M2	|	1/31/2015	|	$1,635	|	$0	|	$1,635
C00233361	|	2015	|	M3	|	2/28/2015	|	$530	|	$0	|	$530
C00233361	|	2015	|	M4	|	3/31/2015	|	$0	|	$0	|	$0
C00233361	|	2015	|	M5	|	4/30/2015	|	$0	|	$0	|	$0
C00233361	|	2015	|	M6	|	5/31/2015	|	$0	|	$0	|	$0
C00233361	|	2015	|	M7	|	6/30/2015	|	$1,119	|	$0	|	$1,119
C00233361	|	2015	|	M9	|	8/31/2015	|	$0	|	$0	|	$0
C00233361	|	2015	|	M10	|	9/30/2015	|	$0	|	$0	|	$0
C00233361	|	2015	|	M11	|	10/31/2015	|	$0	|	$0	|	$0
C00233361	|	2015	|	M8	|	7/31/2015	|	$0	|	$0	|	$0
C00233361	|	2015	|	M12	|	11/30/2015	|	$0	|	$0	|	$0
C00233361	|	2015	|	YE	|	12/31/2015	|	$0	|	$0	|	$0
C00233361	|	2016	|	M2	|	1/31/2016	|	$0	|	$0	|	$0
C00233361	|	2016	|	M3	|	2/29/2016	|	$0	|	$0	|	$0
C00233361	|	2016	|	M4	|	3/31/2016	|	$0	|	$0	|	$0
C00233361	|	2016	|	M5	|	4/30/2016	|	$0	|	$0	|	$0
C00233361	|	2016	|	M6	|	5/31/2016	|	$0	|	$1,181	|	$1,181
C00233361	|	2016	|	M7	|	6/30/2016	|	$0	|	$0	|	$0
C00233361	|	2016	|	M8	|	7/31/2016	|	$1,146	|	$0	|	$1,146
C00233361	|	2016	|	M10	|	9/30/2016	|	$3,525	|	$0	|	$3,525
C00233361	|	2016	|	M9	|	8/31/2016	|	$0	|	$0	|	$0
C00233361	|	2016	|	12G	|	10/19/2016	|	$1,145	|	$0	|	$1,145
C00233361	|	2016	|	30G	|	11/28/2016	|	$604	|	$0	|	$604
C00233361	|	2016	|	YE	|	12/31/2016	|	$461	|	$0	|	$461
Total 	|		|		|		|	$10,165	|	$1,181	|	$11,345

**Comment by jontours** [comment]
@PaulClark2 we were just trying to figure out how `total_transfers` is computed.  That listing above is for all committees with nonfed_acct and nonfed_levin both being greater than zero for the cycle of 2016.

**Comment by jontours** [comment]
oh wait, I see, we should already have the summation...  Okay, that's easier than.

**Comment by PaulClark2** [comment]
Got it. 

There are for F3X filers there are two transfer numbers -- Line 12 (Transfers From Affiliated/Other Party Committees) and Line 18 (Transfers from Non-Federal and Levin Funds). They should not be summed.

**Comment by PaulClark2** [comment]
Yes. The non-federal/Levin funds has a sum line -- 18(c).

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2215
