### ISSUE TITLE
Test new AO features

### ISSUE THREAD

**Issue by anthonygarvan** [18F/openFEC#2222]

**Comment by nickykrause** [comment]
Users recruited, thanks to Cheryl! 

Updating this issue to track the actual testing

**Comment by nickykrause** [comment]
Testing finished last week:

- Observations and issues can be found in the testing repo, here: https://github.com/18F/fec-testing/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20created%3A%3E%3D2017-04-07%20label%3Alegal%20

- More detailed, question-by-question observations are available here: https://docs.google.com/spreadsheets/d/1PvnWy-DcOyrlcAyqRiwIiBu6es-wRr3amTfFkrQtD-E/edit#gid=0
