### ISSUE TITLE
Provide all candidate financial summary totals from the API

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2223]
In order to create a complete view of a candidate's financial summary as [sketched out here](https://gsa.invisionapp.com/share/ESA8FN046#/218195097_Candidate_-_Financial_Summary), the API needs to provide a way to get all of these fields for a candidate. 

What we're looking for is the equivalent to the `/committee/{committee_id}/totals/` [endpoint](https://api.open.fec.gov/developers/#!/financial/get_committee_committee_id_totals), except it returns combined values for all of a candidate's authorized committee's within the given two-year period so that we can show a detailed financial summary on candidate pages.

This is where I'm going to tag @PaulClark2 in and ask if there's any complicated logic we need to do when making these aggregates, or is it as simple as adding the lines for each committee? [For reference, this is what I'm referring to on the current fec.gov](https://cloud.githubusercontent.com/assets/1696495/23386232/211b31de-fd0a-11e6-812b-942e28e30191.png)

This should come after the cloud migration and ATO, but I wanted to get an issue started. 

---

**Completion criteria**
- [x] Given a cycle, the endpoint should return aggregated financial summary totals for all lines of a candidate's financial summary combining all the values for all committees that were active in the time period
- [x] If passed `full_election=true` , the endpoint should return 4 year totals for presidential candidates and 6 year totals for senate candidates
- [x] Response fields should be the same as the response for committee financial summaries

**Comment by PaulClark2** [comment]
I can't see the sketches. 

No, there's no complicated logic. Once you have identified the PCC and other authorized committee(s) for a given two-year period, you just sum the lines for each committee.

**Comment by noahmanger** [comment]
Oops, fixed the link to the designs. Ok, that's great and makes it much easier. So even things like transfers between the committees are still just added up? cc @jontours

**Comment by PaulClark2** [comment]
Yup, even the transfers. 

An other authorized committee transferring money to a PCC would be reported on Line 18 (transfers to other authorized committees), a disbursement line. 

A PCC receiving money from an other authorized committee would be reported on Line 12 (transfers from other authorized committees), a receipt line.

**Comment by LindsayYoung** [comment]
I think the url for that call should be: 
https://api.open.fec.gov/v1/candidate/<candidate_id>/totals?

**Comment by noahmanger** [comment]
Just updated this original issue with some completion criteria. I realized we're going to need to accept the `full_election` flag in order to return 4 and 6 year totals.

**Comment by jontours** [comment]
Trying to finalize my understanding of this after writing some prelimiary sql.  And I'm noticing that the Financial Summary for the candidate page, say for Tammy Baldwin, seems to be just a copy of the financial summary of the committee.  Is that to be expected?  Because it seems the feature that we are expecting from this is the aggregated total across all primary and authorized committees for a given candidate (and unless I'm looking in the wrong spot, doesn't exist on the current campaign finance site).

**Comment by noahmanger** [comment]
Most candidates only have one principal committee, so yeah, it'll be a carbon copy. For the candidates who have one principal and one or more additional authorized, it will aggregate, which is how the current Viewer works.

**Comment by jontours** [comment]
Ah!  That's what I was hoping, do we know of a candidate that this is the case?

**Comment by LindsayYoung** [comment]
https://beta.fec.gov/data/candidate/P00003392/?cycle=2016&election_full=true

**Comment by jontours** [comment]
McCain from 2008 also a great example.  Especially since multiple authorized committees for the same cycle.

**Comment by jontours** [comment]
I have the columns going for cycles, starting to work on `full_election` totals and feel maybe an example would help illustrate what is needed here.  For example McCain, ran for President in 2000 and 2008.  What would the totals consist of here?  For the 2008 race should the totals be for four years prior?

**Comment by noahmanger** [comment]
@jontours yep, exactly. So for a presidential election for the year 2016, there are two two-year cycles: 2013-2014 and 2015-2016. When looking at `election=2016&full_cycle=true` it should combine everything from 2013-2016. 

For a senate race, it should be the previous six years (three cycles). Does that make sense?

This logic is currently in place on the financial totals shown on the candidate endpoint that's used now.

**Comment by jontours** [comment]
Thanks @noahmanger, that does make sense.  And will be pretty easy to do.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2262
