### ISSUE TITLE
Improve date accuracy on /elections/search/

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2225]
In order to show correct election dates when looking up elections for a location, update the logic of `/elections/search` in the following ways:

- [x] Presidential elections should be every 4 years (e.g. remove the bug causing a 2018 election to show up)
- [x] Ensure that senate class elections are accurate
- [x] Given a cycle and a location, it should _only_ return contests that have  an election date in that cycle. (i.e. for `cycle=2018` don't show a presidential contest or any senate contest unless the state has one for that year)

**Comment by jontours** [comment]
I've been digging around trying to find instances of Senate elections showing up when they should (or shouldn't), is there any example of this?

**Comment by noahmanger** [comment]
Alaska doesn't have one in 2018: https://beta.fec.gov/data/elections/?cycle=2018&state=AK

There's three senate classes. I've coded them as constants here, with their next election year as well: https://github.com/18F/openFEC-web-app/blob/develop/openfecwebapp/constants.py#L368

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2297
