### ISSUE TITLE
Add line number filter for schedule A and B

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2228]
So that power users can more easily find the data they're looking for, allow users to filter schedule A and schedule B transactions by `line_number`.

This issue needs a bit more grooming to determine how we want to do this considering different line numbers mean different things on the different forms. 

---

### Update after grooming
We decided that want to the endpoint to accept parameters in the form of `[form number]-[line-number]`. e.g. `3-11a`, `3x-16`, `3P-16`. 

The response already includes the line number, but we also want to add a human readable label (maybe `line_number_label`?). This can be drawn from the labels on the forms itself. I extracted these already for my own use here: [line-numbers.txt](https://github.com/18F/openFEC/files/839826/line-numbers.txt)

**Completion critieria:**
- [x] Add `line_number` filter to `/schedules/schedule_a/` and `/schedules/schedule_b/`
- [x] Add `line_number_label` to responses from both endpoints
- [x] Benchmark performance to make sure it's not too big of a drag

**Comment by noahmanger** [comment]
Just updated this issue with new notes from grooming.

**Comment by jontours** [comment]
Benchmarking is left to do but this is done.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2363
