### ISSUE TITLE
Sort legal docs by appropriate fields

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2232]
We have implemented sorting by reverse chronological order (by AO number actually) for Advisory Opinions. We need to implement similar sorts for the rest of the legal documents:

- [ ] MURs (reverse chronological, by MUR number - descending)
- [ ] Statutes (by title, chapter, subchapter - ascending)
- [ ] Regulations (similar to Statutes, however the desired fields do not exist as individual fields currently)

Future:
- [ ] ADRs (reverse chronological, by ADR number - descending)
- [ ] AFs (reverse chronological, by AF number - descending)

**Comment by noahmanger** [comment]
Resolved by #2258
