### ISSUE TITLE
Remove unverified filers from candidate and committee endpoints

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2243]
So that users are only exposed by default to verified filers, remove all unverified candidates and committees from default views.

---

The FEC has a table of "unverified filers". We should use this table to flag all candidates and committees that match. This should be done on the main `/candidates/` and `/committees/` endpoints as well as the `/names/` endpoint so matches aren't suggested in the typeahead. 

**Completion criteria:**
- [ ] All unverified candidates removed from candidates endpoints
- [ ] All unverified committees removed from committees endpoints
- [ ] All unverified options removed from `/names/` endpoint
- [ ] Remove all their filings

**Comment by ccostino** [comment]
@noahmanger, do you happen to know what the name of the table/view is that contains the unverified filers?

Also, the last item, `Remove all their filings` - what do you mean by that?  Remove them from the display/results or remove them from our tables/views?

**Comment by ccostino** [comment]
And if it's latter, I would think that removing the info from our tables/views would resolve the first three items, right?

**Comment by noahmanger** [comment]
@PaulClark2 or @jwchumley should confirm, but that's my understanding: we just want to remove the data entirely. But yeah, stands to reason that removing the base filings would solve the problem.

**Comment by ccostino** [comment]
Great, thanks!

**Comment by ccostino** [comment]
@jwchumley, do you know what the name is of the table or view with the unverified filers?  Once I have that I can get started on this.  Thanks!

**Comment by ccostino** [comment]
Is it `unverified_filers_vw`?  It looks like this is just committee information though, right?  So this would mean having to tie that committee back to a candidate to remove unverified candidates as well?

**Comment by jwchumley** [comment]
@ccostino unverified_filers_vw looks correct. It has both committee and candidate ids in it.

"C00589382"
"C00584581"
"H6CA13157"
"C00588012"
"P60010063"

**Comment by jontours** [comment]
Yeah @ccostino I think if you limit the candidates built in candidate_history.sql using that view as a guide that will at least remove all candidates.  Committees not to sure at the moment.

**Comment by ccostino** [comment]
Awesome, thank you @jwchumley and @jontours!
