### ISSUE TITLE
Redis not working on govcloud

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2244]
It's not connecting. It is bound. 

I am going to try recreating redis.

I thought this worked before, but now I am doubting myself.

**Comment by LindsayYoung** [comment]
deleted and recreated in dev and it still doesn't work. It's giving a connection refused error

**Comment by noahmanger** [comment]
This got resolved, right?

**Comment by LindsayYoung** [comment]
Yes it did! many thanks to @jmcarp
