### ISSUE TITLE
Remove "space name" from the names of services

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2247]
When naming services, it looks like we include a `-spacename` suffix, but not consistently. As the services are _namespaced_, we should remove the spacename from the service name. E.g. ,we currently have:
```
cf services
Getting services in org fec-beta-fec / space dev as radhakrishnan.vrajmohan@gsa.gov...
OK

name                    service                     plan             bound apps                                                last operation
fec-dev-cms-backup-s3   s3                          basic                                                                      create succeeded
fec-eregs-db            aws-rds                     shared-psql      eregs                                                     create succeeded
fec-eregs-search        elasticsearch24             1x               eregs                                                     create succeeded
fec-eregs-creds         user-provided                                eregs
fec-search-dev          elasticsearch24             3x               api, celery-worker, celery-beat                           create succeeded
fec-s3-dev              s3                          basic-public     api, celery-worker, celery-beat                           create succeeded
content-s3              s3                          basic-public     s3-app                                                    create succeeded
service-account         cloud-gov-service-account   space-deployer                                                             create succeeded
fec-dev-cms             aws-rds                     shared-psql      cms                                                       create succeeded
fec-redis-dev           redis28                     standard         api, celery-worker, celery-beat                           create succeeded
dev-deployer            cloud-gov-service-account   space-deployer                                                             create succeeded
cms-creds-dev           user-provided                                cms
fec-creds-dev           user-provided                                proxy, eregs, api, celery-worker, cms, celery-beat, web
```

This would have the advantage of reducing the differences between the manifests.
In addition, we have a bug in looking up services by `label` - https://github.com/18F/openFEC/blob/develop/webservices/config.py#L65. As multiple instances of the service will have the same label (see `s3` or `elasticsearch24` in above example), this may pick up the wrong service. The alternative, look up service by name, will work more easily if we use the same name _across_ spaces.

@ccostino, @LindsayYoung, @jontours , @anthonygarvan , @dogweather, please comment.

**Comment by LindsayYoung** [comment]
I don't mind getting rid of the space in the name. I would like to keep the app name when there is an app specific thing. 

If naming is causing you a problem, feel free to re-name it as you need to, just drop a line in the dev channel so people know and make sure you have a pr open so other people can pull in your changes. 

I like the idea of doing a service name check. That check started when we did not have multiples of the same service but now that we do, checking service name would be much better.

Thanks @vrajmohan!

**Comment by dogweather** [comment]
100%!

**Comment by LindsayYoung** [comment]
I think this is done except for the credentials, and I like the idea that those are explicit. We can make a new issue in the future if I missed one
