### ISSUE TITLE
Data comparison - Presidential

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2251]
I compared the Top level figures for the top 25 presidential candidates and found only a single value discrepancy.

https://beta.fec.gov/data/candidate/P60007168/?cycle=2016&election_full=true

Bernie Sander's Total Receipts 
Beta:     237,642,226.02
Actual:  237,640,609.52

It's a small difference but we need to figure it out. There are no recent Sanders amendments that would point to a failure to transfer the data.

Also only a single value in House Candidate numbers in the first 110 I've checked.

H4TX18054  Has an issue with COH.
Beta:    132,159.39
Actual: 118,837.01

@LindsayYoung @ccostino @noahmanger

**Comment by ccostino** [comment]
Thanks, @jwchumley, we'll take a closer look!

**Comment by jwchumley** [comment]
I looked deeper and it didn't help. The itemized individual contribution amount is not the same in both systems:
Beta:  96,797,402
FEC: 97,145,068

When I manually total the amount from the fifteen reports in 2015-2016 I get the FEC figure. When I go straight to the API:
https://api.open.fec.gov/v1/reports/presidential/?committee_id=C00577130&sort=-coverage_end_date&api_key=DEMO_KEY&cycle=2016&per_page=20&most_recent=true&page=1

I get the FEC figure. I don't know where the Beta figure is coming from.

@noahmanger @LindsayYoung @PaulClark2

**Comment by LindsayYoung** [comment]
Thanks for doing the legwork on this! This is really weird

**Comment by jwchumley** [comment]
As of this morning, Paul and I think there is no problem on the Beta site for this issue. It is a processing problem where Sanders filed a Quarterly report instead of a Monthly and then amended the monthly and that final amendment doesn't appear to have ever been completely processed. We're working on figuring it out but we think solving the processing will solve the discrepancy.

**Comment by LindsayYoung** [comment]
Thanks @jwchumley! 

I am going to close the issue since it looks like you have it covered on your side. If you find anything else, go ahead and make a new issue. 

👢  🐛  <- squashing bugs
