### ISSUE TITLE
Check logs for CMS [ATO]

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2253]
AU-2a Parameter Requirement: 

- successful and unsuccessful account logon events, 
- account management events, 
- object access, 
- policy change, (Checking on the meaning)
- privilege functions, 
- process tracking, 
- and system events

**Comment by LindsayYoung** [comment]
The logs for unsuccessful login attempts are there, we need to add the successful events

**Comment by jontours** [comment]
Before doing any more feature development will try to get this wrapped up.

**Comment by LindsayYoung** [comment]
I was checking too to see if the cloud.gov logging can could for this

**Comment by LindsayYoung** [comment]
We are good since there are logs, we don't have to log them too
