### ISSUE TITLE
Senate candidate and committee number problem

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2255]
I;ve figured out the problem with the summary figures for Senate candidates and committees. Paper amendment filers often leave null any value that doesn't change from the previous filing. In FECP we handle this in the load process into the v_sum table where an amendment null value doesn't replace the previous reports non-null value so v_sum has all of the amounts. For example, Senate committee C00473371 has 11 as-amended reports in both systems:
Beta TR     -------- V_sum TR
7961.51    -------- 7961
71677       -------- 71677
42268.29- -------- 42268
360494.12 -------- 360494
null ----------------190436
null-----------------312484
377038.89 -------- 377038
null            -------- 389451
null            -------- 519515
553648.58 -------- 553648
null            -------- 118382

The only solution I see is to feed the reports end point from v_sum. 
@LindsayYoung @ccostino @noahmanger

**Comment by LindsayYoung** [comment]
The Senate reports come from [fec_vsum_f3_vw](https://github.com/18F/openFEC/blob/develop/data/sql_updates/reports_house_senate.sql#L99)

**Comment by jwchumley** [comment]
I have a thought. The reports endpoint is fed by the public.ofec_vsum_f3_vw which combines the disclosure.nml_form_3 (F3) table with the disclosure.v_sum_and_det_sum_report (VS) table but takes all the columns from the F3 table. If you rewrote it to take columns from v_sum then that would solve this issue. I don't know what else this endpoint is used for but changing to v_sum would lose all of the column B figures because they aren't stored there. Here is an example for the form 3 view:

SELECT f3.cmte_id,
    f3.cmte_nm,
    f3.cmte_st1,
    f3.cmte_st2,
    f3.cmte_city,
    f3.cmte_st,
    f3.cmte_zip,
    f3.cmte_addr_chg_flg,
    f3.cmte_election_st,
    f3.cmte_election_st_desc,
    f3.cmte_election_district,
    f3.amndt_ind,
    f3.amndt_ind_desc,
    f3.rpt_tp,
    f3.rpt_tp_desc,
    f3.rpt_pgi,
    f3.rpt_pgi_desc,
    f3.election_dt,
    f3.election_st,
    f3.election_st_desc,
    f3.cvg_start_dt,
    f3.cvg_end_dt,
    f3.rpt_yr,
    f3.receipt_dt,
    f3.rpt_yr + f3.rpt_yr % 2::numeric AS election_cycle,
    f3.tres_sign_nm,
    f3.tres_l_nm,
    f3.tres_f_nm,
    f3.tres_m_nm,
    f3.tres_prefix,
    f3.tres_suffix,
    f3.tres_sign_dt,
    vs.ttl_contb as ttl_contb_per,
    vs.ttl_contb_ref as ttl_contb_ref_per,
    vs.net_contb as net_contb_per,
    vs.op_exp_per as ttl_op_exp_per,
    vs.offsets_to_op_exp as ttl_offsets_to_op_exp_per,
    vs.net_op_exp as net_op_exp_per,
    --vs.coh_cop  AS coh_cop_line_8,
    vs.coh_cop AS coh_cop,
    vs.debts_owed_to_cmte,
    vs.debts_owed_by_cmte,
    vs.indv_item_contb,
    vs.indv_unitem_contb,
    vs.indv_contb,
    vs.pty_cmte_contb AS pol_pty_cmte_contb_per,
    VS.OTH_CMTE_CONTB AS other_pol_cmte_contb_per,
    VS.CAND_CNTB AS cand_contb_per,
    --f3.ttl_contb_column_ttl_per,
    vs.tranf_from_other_auth_cmte AS tranf_from_other_auth_cmte_per,
    VS.CAND_LOAN AS loans_made_by_cand_per,
    VS.OTH_LOANS AS all_other_loans_per,
    VS.TTL_LOANS AS ttl_loans_per,
    VS.offsets_to_op_exp AS offsets_to_op_exp_per,
    VS.OTHER_RECEIPTS AS other_receipts_per,
    --VS.ttl_receipts AS ttl_receipts_line_16,
    VS.ttl_receipts AS ttl_receipts_per,
    VS.OP_EXP_PER AS op_exp_per,
    VS.tranf_to_other_auth_cmte AS tranf_to_other_auth_cmte_per,
    vs.cand_loan_repymnt as loan_repymts_cand_loans_per,
    vs.OTH_LOAN_REPYMTS loan_repymts_other_loans_per,
    vs.ttl_loan_repymts as ttl_loan_repymts_per,
    vs.indv_ref as ref_indv_contb_per,
    vs.pol_pty_cmte_contb as ref_pol_pty_cmte_contb_per,  -- the vs column name is unfortunate but that's the way it goes
    vs.oth_cmte_ref as ref_other_pol_cmte_contb_per,
    vs.ttl_contb_ref as ttl_contb_ref_col_ttl_per,
    vs.other_disb_per as other_disb_per,
    --vs.ttl_disb AS ttl_disb_line_22,
    vs.ttl_disb AS ttl_disb_per,
    vs.coh_bop,
    --f3.ttl_receipts_ii AS ttl_receipts_line_24,
    --f3.subttl_per,
    --f3.ttl_disb_per_ii AS ttl_disb_line_26,
    --f3.coh_cop_ii AS coh_cop_line_27,
    --f3.ttl_contb_ytd,
    --f3.ttl_contb_ref_ytd,
    --f3.net_contb_ytd,
    --f3.ttl_op_exp_ytd,
    --f3.ttl_offsets_to_op_exp_ytd,
    --f3.net_op_exp_ytd,
    -- f3.ttl_indv_item_contb_ytd,
--     f3.ttl_indv_unitem_contb_ytd,
--     f3.ttl_indv_contb_ytd,
--     f3.pol_pty_cmte_contb_ytd,
--     f3.other_pol_cmte_contb_ytd,
--     f3.cand_contb_ytd,
--     f3.ttl_contb_col_ttl_ytd,
--     f3.tranf_from_other_auth_cmte_ytd,
--     f3.loans_made_by_cand_ytd,
--     f3.all_other_loans_ytd,
--     f3.ttl_loans_ytd,
--     f3.offsets_to_op_exp_ytd,
--     f3.other_receipts_ytd,
--     f3.ttl_receipts_ytd,
--     f3.op_exp_ytd,
--     f3.tranf_to_other_auth_cmte_ytd,
--     f3.loan_repymts_cand_loans_ytd,
--     f3.loan_repymts_other_loans_ytd,
--     f3.ttl_loan_repymts_ytd,
--     f3.ref_indv_contb_ytd,
--     f3.ref_pol_pty_cmte_contb_ytd,
--     f3.ref_other_pol_cmte_contb_ytd,
--     f3.ref_ttl_contb_col_ttl_ytd,
--     f3.other_disb_ytd,
--     f3.ttl_disb_ytd,
   --  f3.grs_rcpt_auth_cmte_prim,
--     f3.agr_amt_contrib_pers_fund_prim,
--     f3.grs_rcpt_min_pers_contrib_prim,
--     f3.grs_rcpt_auth_cmte_gen,
--     f3.agr_amt_pers_contrib_gen,
--     f3.grs_rcpt_min_pers_contrib_gen,
--     f3.cand_id,
--     f3.cand_nm,
--     f3.f3z1_rpt_tp,
--     f3.f3z1_rpt_tp_desc,
    f3.begin_image_num,
    f3.end_image_num,
    'F3' AS form_tp,
    f3.form_tp_desc,
    f3.file_num,
    f3.prev_file_num,
    f3.mst_rct_file_num,
    f3.sub_id,
    'Y' as most_recent_filing_flag
        -- CASE
--             WHEN vs.orig_sub_id IS NOT NULL THEN 'Y'::text
--             ELSE 'N'::text
--         END AS most_recent_filing_flag
   FROM disclosure.nml_form_3 f3
     LEFT JOIN disclosure.v_sum_and_det_sum_report vs ON f3.sub_id = vs.orig_sub_id
     where vs.cmte_id='C00473371'
     and vs.rpt_yr in (2015,2016);;

**Comment by jwchumley** [comment]
I can't check from here but I don't think fec_vsum_f3_vw actually uses v_sum. I looked at it yesterday and it uses the form 3 table

**Comment by PaulClark2** [comment]
I wonder if something like COALESCE(F3-value, VSUM-value) would be a better approach. This way if the F3 row has a value we use it. If there is no value in the F3 row then use the value from VSUM. Just a thought. 

If recall correctly, COALESCE returns the first non-null value.

**Comment by jwchumley** [comment]
Could do that but v_um already does that so populated columns in the form table should match the same column in v_sum.

Sent from my iPhone

On Mar 23, 2017, at 12:52 PM, Paul Clark <notifications@github.com<mailto:notifications@github.com>> wrote:


I wonder if something like COALESCE(F3-value, VSUM-value) would be a better approach. This way if the F3 row has a value we use it. If there is no value in the F3 row then use the value from VSUM. Just a thought.

If recall correctly, COALESCE returns the first non-null value.

**Comment by noahmanger** [comment]
Update from grooming: 18F needs to look into what else depends on this view.

**Comment by LindsayYoung** [comment]
Found another related thing, our last table switch was back to a table that provides duplicate values for the forms where they ask the same question more than once, but people don't always fill out things twice, so you need to take the greatest of both values.

Also can we get a copy of the view code?

**Comment by jwchumley** [comment]
V_sum isn't a view. It's a table and has scripts and many informatica mappings that feed it. I've asked Jerry to provide the Form 3 scripts and mappings. The scripts should be easy but I don't know if it is easy to get the code snippets from informatica.

________________________________

**Comment by jwchumley** [comment]
Jerry says he can sit down with you and show you the mappings but there is no export feature.


________________________________

**Comment by LindsayYoung** [comment]
Maybe we are talking about different things? The fec_vsum_f3_vw is a view in the public schema

**Comment by LindsayYoung** [comment]
I think talking with Jerry would be helpful, thanks!

**Comment by jwchumley** [comment]
Oh. I thought, nevermind.  Didn't you create the fec_vsum_f3_vw ?


________________________________

**Comment by LindsayYoung** [comment]
The vsum views come from the FEC side

**Comment by hcaofec** [comment]
Per Jeff's request:  

CREATE OR REPLACE VIEW public.fec_vsum_f3_vw AS 
 SELECT f3.cmte_id,
    f3.cmte_nm,
    f3.cmte_st1,
    f3.cmte_st2,
    f3.cmte_city,
    f3.cmte_st,
    f3.cmte_zip,
    f3.cmte_addr_chg_flg,
    f3.cmte_election_st,
    f3.cmte_election_st_desc,
    f3.cmte_election_district,
    f3.amndt_ind,
    f3.amndt_ind_desc,
    f3.rpt_tp,
    f3.rpt_tp_desc,
    f3.rpt_pgi,
    f3.rpt_pgi_desc,
    f3.election_dt,
    f3.election_st,
    f3.election_st_desc,
    f3.cvg_start_dt,
    f3.cvg_end_dt,
    f3.rpt_yr,
    f3.receipt_dt,
    f3.rpt_yr + f3.rpt_yr % 2::numeric AS election_cycle,
    f3.tres_sign_nm,
    f3.tres_l_nm,
    f3.tres_f_nm,
    f3.tres_m_nm,
    f3.tres_prefix,
    f3.tres_suffix,
    f3.tres_sign_dt,
    f3.ttl_contb_per,
    f3.ttl_contb_ref_per,
    f3.net_contb_per,
    f3.ttl_op_exp_per,
    f3.ttl_offsets_to_op_exp_per,
    f3.net_op_exp_per,
    f3.coh_cop_i AS coh_cop_line_8,
    GREATEST(f3.coh_cop_i, f3.coh_cop_ii) AS coh_cop,
    f3.debts_owed_to_cmte,
    f3.debts_owed_by_cmte,
    f3.indv_item_contb_per,
    f3.indv_unitem_contb_per,
    f3.ttl_indv_contb_per,
    f3.pol_pty_cmte_contb_per,
    f3.other_pol_cmte_contb_per,
    f3.cand_contb_per,
    f3.ttl_contb_column_ttl_per,
    f3.tranf_from_other_auth_cmte_per,
    f3.loans_made_by_cand_per,
    f3.all_other_loans_per,
    f3.ttl_loans_per,
    f3.offsets_to_op_exp_per,
    f3.other_receipts_per,
    f3.ttl_receipts_per_i AS ttl_receipts_line_16,
    GREATEST(f3.ttl_receipts_per_i, f3.ttl_receipts_ii) AS ttl_receipts_per,
    f3.op_exp_per,
    f3.tranf_to_other_auth_cmte_per,
    f3.loan_repymts_cand_loans_per,
    f3.loan_repymts_other_loans_per,
    f3.ttl_loan_repymts_per,
    f3.ref_indv_contb_per,
    f3.ref_pol_pty_cmte_contb_per,
    f3.ref_other_pol_cmte_contb_per,
    f3.ttl_contb_ref_col_ttl_per,
    f3.other_disb_per,
    f3.ttl_disb_per_i AS ttl_disb_line_22,
    GREATEST(f3.ttl_disb_per_i, f3.ttl_disb_per_ii) AS ttl_disb_per,
    f3.coh_bop,
    f3.ttl_receipts_ii AS ttl_receipts_line_24,
    f3.subttl_per,
    f3.ttl_disb_per_ii AS ttl_disb_line_26,
    f3.coh_cop_ii AS coh_cop_line_27,
    f3.ttl_contb_ytd,
    f3.ttl_contb_ref_ytd,
    f3.net_contb_ytd,
    f3.ttl_op_exp_ytd,
    f3.ttl_offsets_to_op_exp_ytd,
    f3.net_op_exp_ytd,
    f3.ttl_indv_item_contb_ytd,
    f3.ttl_indv_unitem_contb_ytd,
    f3.ttl_indv_contb_ytd,
    f3.pol_pty_cmte_contb_ytd,
    f3.other_pol_cmte_contb_ytd,
    f3.cand_contb_ytd,
    f3.ttl_contb_col_ttl_ytd,
    f3.tranf_from_other_auth_cmte_ytd,
    f3.loans_made_by_cand_ytd,
    f3.all_other_loans_ytd,
    f3.ttl_loans_ytd,
    f3.offsets_to_op_exp_ytd,
    f3.other_receipts_ytd,
    f3.ttl_receipts_ytd,
    f3.op_exp_ytd,
    f3.tranf_to_other_auth_cmte_ytd,
    f3.loan_repymts_cand_loans_ytd,
    f3.loan_repymts_other_loans_ytd,
    f3.ttl_loan_repymts_ytd,
    f3.ref_indv_contb_ytd,
    f3.ref_pol_pty_cmte_contb_ytd,
    f3.ref_other_pol_cmte_contb_ytd,
    f3.ref_ttl_contb_col_ttl_ytd,
    f3.other_disb_ytd,
    f3.ttl_disb_ytd,
    f3.grs_rcpt_auth_cmte_prim,
    f3.agr_amt_contrib_pers_fund_prim,
    f3.grs_rcpt_min_pers_contrib_prim,
    f3.grs_rcpt_auth_cmte_gen,
    f3.agr_amt_pers_contrib_gen,
    f3.grs_rcpt_min_pers_contrib_gen,
    f3.cand_id,
    f3.cand_nm,
    f3.f3z1_rpt_tp,
    f3.f3z1_rpt_tp_desc,
    f3.begin_image_num,
    f3.end_image_num,
    'F3' AS form_tp,
    f3.form_tp_desc,
    f3.file_num,
    f3.prev_file_num,
    f3.mst_rct_file_num,
    f3.sub_id,
        CASE
            WHEN vs.orig_sub_id IS NOT NULL THEN 'Y'::text
            ELSE 'N'::text
        END AS most_recent_filing_flag
   FROM disclosure.nml_form_3 f3
     LEFT JOIN disclosure.v_sum_and_det_sum_report vs ON f3.sub_id = vs.orig_sub_id;

**Comment by LindsayYoung** [comment]
Thanks @hcaofec

**Comment by jwchumley** [comment]
Here are three potential views to solve the rollup problem in the fec_vsum_form3_vw, fec_vsum_form3p_vw, and fec_vsum_form3x_vw. They only use v_sum and don't join with the form 3, 3x, or 3p tables. THey only include the columns that v_sum has so they exclude all of the "column b" columns and some of the subtotal columns.  The purpose of this is to resolve the problem with paper filings where amendments can leave out numbers and v_sum rolls up previous values for null values.


--Form 3p:
SELECT VS.cmte_id,
    VS.rpt_tp,
    VS.cvg_start_dt,
    VS.cvg_end_dt,
    VS.rpt_yr,
    VS.receipt_dt,
    VS.rpt_yr + VS.rpt_yr % 2::numeric AS election_cycle,  
    VS.coh_bop,
    VS.TTL_RECEIPTS AS ttl_receipts_per,
    VS.TTL_RECEIPTS AS ttl_receipts_SUM_PAGE_per, --IN V_SUM THE TTL_RECEIPTS_SUM_PAGE_PER IS MERGED WITH TTL_RECEIPTS_PER
    VS.TTL_DISB AS ttl_disb_per,
    VS.TTL_DISB AS ttl_disb_sum_page_per,  --  IN V_SUM THE TTL_DISB_SUM_PAGE_PER IS MERGED WITH TTL_DISB_PER
    VS.coh_cop,
    VS.debts_owed_to_cmte,
    VS.debts_owed_by_cmte,
    VS.fed_funds_per,
    VS.INDV_ITEM_CONTB AS indv_item_contb_per,
    VS.INDV_UNITEM_CONTB AS indv_unitem_contb_per,
    VS.INDV_REF AS ttl_indiv_contb_per,  -- UNFORTUNATELY A WRONG NAME IN V_SUM BUT MAPPED NONE THE LESS
    VS.PTY_CMTE_CONTB AS pol_pty_cmte_contb_per,
    VS.OTH_CMTE_CONTB AS other_pol_cmte_contb_per,
    VS.CAND_CNTB AS cand_contb_per,
    VS.TTL_CONTB AS ttl_contb_per,
    VS.TRANF_FROM_OTHER_AUTH_CMTE AS tranf_from_affilated_cmte_per,
    VS.CAND_LOAN AS loans_received_from_cand_per,
    VS.OTH_LOANS AS other_loans_received_per,
    VS.OFFSETS_TO_OP_EXP AS offsets_to_op_exp_per,
    VS.offsets_to_fndrsg AS offsets_to_fndrsg_exp_per,
    VS.OFFSETS_TO_LEGAL_ACCTG AS offsets_to_legal_acctg_per,
    VS.OTHER_RECEIPTS AS other_receipts_per,
    VS.OP_EXP_PER AS op_exp_per,
    VS.TRANF_TO_OTHER_AUTH_CMTE AS tranf_to_other_auth_cmte_per,
    VS.FNDRSG_DISB AS fndrsg_disb_per,
    VS.EXEMPT_LEGAL_ACCTG_DISB AS exempt_legal_acctg_disb_per,
    VS.CAND_LOAN_REPYMNT AS repymts_loans_made_by_cand_per,
    VS.OTH_LOAN_REPYMTS AS repymts_other_loans_per,
    VS.INDV_REF AS ref_indv_contb_per,
    VS.POL_PTY_CMTE_CONTB AS ref_pol_pty_cmte_contb_per,  --  BAD COLUMN NAME IN V_SUM
    VS.OTH_CMTE_REF AS ref_other_pol_cmte_contb_per,
    VS.OTHER_DISB_PER AS other_disb_per,
    --f3p.begin_image_num, -- IF WE NEED THISWE NEED TO LINK OT FORM 3
    --f3p.end_image_num,  -- IF WE NEED THISWE NEED TO LINK OT FORM 3
    'F3P' AS form_tp,
    'RPT OF RECEIPTS AND DISB BY AN AUTH COMMITTEE OF A CANDIDATE FOR THE OFFICE OF PRES OR VP' AS form_tp_desc,
    VS.FILE_NUM AS file_num,
    VS.ORIG_SUB_ID AS sub_id,
    'Y' AS most_recent_filing_flag
    FROM disclosure.v_sum_and_det_sum_report vs 



--Form 3x:
SELECT f3x.cmte_id,
VS.RPT_TP    AS    RPT_TP,
VS.CVG_START_DT    AS    CVG_START_DT,
VS.CVG_END_DT    AS    CVG_END_DT,
VS.RPT_YR AS RPT_YR,
VS.RECEIPT_DT AS RECEIPT_DT,
VS.rpt_yr + VS.rpt_yr % 2::numeric AS election_cycle,
VS.COH_BOP    AS    COH_BOP,
VS.TTL_RECEIPTS    AS    TTL_RECEIPTS,
VS.TTL_RECEIPTS    AS    ttl_receipts_sum_page_per,
VS.TTL_DISB    AS    TTL_DISB_SUM_PAGE_PER,
VS.COH_COP    AS    COH_COP,
VS.DEBTS_OWED_TO_CMTE    AS    DEBTS_OWED_TO_CMTE,
VS.DEBTS_OWED_BY_CMTE    AS    DEBTS_OWED_BY_CMTE,
VS.INDV_CONTB AS indv_item_contb_per,
VS.INDV_ITEM_CONTB    AS    INDV_ITEM_CONTB_PER,
VS.INDV_CONTB    AS    TTL_INDV_CONTB,
VS.PTY_CMTE_CONTB    AS    POL_PTY_CMTE_CONTB_PER_I,
VS.OTH_CMTE_CONTB    AS    OTHER_POL_CMTE_CONTB_PER_I,
VS.TTL_CONTB    AS    TTL_CONTB_COL_TTL_PER,
VS.TRANF_FROM_OTHER_AUTH_CMTE    AS    TRANF_FROM_AFFILIATED_PTY_PER,
VS.ALL_LOANS_RECEIVED_PER    AS    ALL_LOANS_RECEIVED_PER,
VS.LOAN_REPYMTS_RECEIVED_PER    AS    LOAN_REPYMTS_RECEIVED_PER,
VS.OFFSETS_TO_OP_EXP    AS    OFFSETS_TO_OP_EXP_PER_I,
VS.FED_CAND_CONTB_REF_PER    AS    FED_CAND_CONTB_REF_PER,
VS.OTHER_RECEIPTS    AS    OTHER_FED_RECEIPTS_PER,
VS.TRANF_FROM_NONFED_ACCT_PER    AS    TRANF_FROM_NONFED_ACCT_PER,
VS.TRANF_FROM_NONFED_LEVIN_PER    AS    TRANF_FROM_NONFED_LEVIN_PER,
VS.TTL_NONFED_TRANF_PER    AS    TTL_NONFED_TRANF_PER,
VS.SHARED_FED_OP_EXP_PER    AS    SHARED_FED_OP_EXP_PER,
VS.SHARED_NONFED_OP_EXP_PER    AS    SHARED_NONFED_OP_EXP_PER,
VS.OTHER_FED_OP_EXP_PER    AS    OTHER_FED_OP_EXP_PER,
VS.TTL_OP_EXP_PER    AS    TTL_OP_EXP_PER,
VS.TRANF_TO_OTHER_AUTH_CMTE    AS    TRANF_TO_AFFLILIATED_CMTE_PER,
VS.FED_CAND_CMTE_CONTB_PER    AS    FED_CAND_CMTE_CONTB_PER,
VS.INDT_EXP_PER    AS    INDT_EXP_PER,
VS.COORD_EXP_BY_PTY_CMTE_PER    AS    COORD_EXP_BY_PTY_CMTE_PER,
VS.OTH_LOAN_REPYMTS    AS    LOAN_REPYMTS_MADE_PER,
VS.LOANS_MADE_PER    AS    LOANS_MADE_PER,
VS.INDV_REF    AS    INDV_CONTB_REF_PER,
VS.POL_PTY_CMTE_CONTB    AS     pol_pty_cmte_refund,
VS.OTH_CMTE_REF    AS    other_pol_cmte_refund,
VS.TTL_CONTB_REF    AS  ttl_contb_refund,
VS.OTHER_DISB_PER    AS    OTHER_DISB_PER,
VS.SHARED_FED_ACTVY_FED_SHR_PER    AS    SHARED_FED_ACTVY_FED_SHR_PER,
VS.SHARED_FED_ACTVY_NONFED_PER    AS    SHARED_FED_ACTVY_NONFED_PER,
VS.NON_ALLOC_FED_ELECT_ACTVY_PER    AS    NON_ALLOC_FED_ELECT_ACTVY_PER,
VS.TTL_FED_ELECT_ACTVY_PER    AS    TTL_FED_ELECT_ACTVY_PER,
VS.TTL_DISB    AS ttl_disb_per_line_31,
VS.RPT_YR AS calendar_yr,
    'F3X' AS form_tp,
 'REPORT OF RECEIPTS AND DISBURSEMENTS FOR OTHER THAN AN AUTHORIZED COMMITTEE' AS form_tp_desc,
VS.FILE_NUM ASfile_num,
VS.ORIG_SUB_ID AS sub_id,
'Y' AS most_recent_filing_flag
disclosure.v_sum_and_det_sum_report vs


--Form 3:
SELECT 
 VS.TTL_CONTB                   AS TTL_CONTB_PER,
 VS.TTL_CONTB_REF               AS TTL_CONTB_REF_PER,
 VS.NET_CONTB                   AS NET_CONTB_PER,
 VS.OP_EXP_PER                  AS TTL_OP_EXP_PER,
 VS.OFFSETS_TO_OP_EXP           AS TTL_OFFSETS_TO_OP_EXP_PER,
 VS.NET_OP_EXP                  AS NET_OP_EXP_PER,
 VS.COH_COP                     AS COH_COP,
 VS.DEBTS_OWED_TO_CMTE          AS DEBTS_OWED_TO_CMTE,
 VS.DEBTS_OWED_BY_CMTE          AS DEBTS_OWED_BY_CMTE,
 VS.INDV_ITEM_CONTB             AS INDV_ITEM_CONTB,
 VS.INDV_UNITEM_CONTB           AS INDV_UNITEM_CONTB,
 VS.INDV_CONTB                  AS INDV_CONTB,
 VS.PTY_CMTE_CONTB              AS POL_PTY_CMTE_CONTB_PER,
 VS.OTH_CMTE_CONTB              AS OTHER_POL_CMTE_CONTB_PER,
 VS.CAND_CNTB                   AS CAND_CONTB_PER,
 VS.TRANF_FROM_OTHER_AUTH_CMTE  AS TRANF_FROM_OTHER_AUTH_CMTE_PER,
 VS.CAND_LOAN                   AS LOANS_MADE_BY_CAND_PER,
 VS.OTH_LOANS                   AS ALL_OTHER_LOANS_PER,
 VS.TTL_LOANS                   AS TTL_LOANS_PER,
 VS.OFFSETS_TO_OP_EXP           AS OFFSETS_TO_OP_EXP_PER,
 VS.OTHER_RECEIPTS              AS OTHER_RECEIPTS_PER,
 VS.TTL_RECEIPTS                AS TTL_RECEIPTS_PER,
 VS.OP_EXP_PER                  AS OP_EXP_PER,
 VS.TRANF_TO_OTHER_AUTH_CMTE    AS TRANF_TO_OTHER_AUTH_CMTE_PER,
 VS.CAND_LOAN_REPYMNT           AS LOAN_REPYMTS_CAND_LOANS_PER,
 VS.OTH_LOAN_REPYMTS            AS LOAN_REPYMTS_OTHER_LOANS_PER,
 VS.TTL_LOAN_REPYMTS            AS TTL_LOAN_REPYMTS_PER,
 VS.INDV_REF                    AS REF_INDV_CONTB_PER,
 VS.POL_PTY_CMTE_CONTB          AS REF_POL_PTY_CMTE_CONTB_PER, -- the vs column name is unfortunate but that's the way it goes
 VS.OTH_CMTE_REF                AS REF_OTHER_POL_CMTE_CONTB_PER,
 VS.TTL_CONTB_REF               AS TTL_CONTB_REF_COL_TTL_PER,
 VS.OTHER_DISB_PER              AS OTHER_DISB_PER,
 VS.TTL_DISB                    AS TTL_DISB_PER,
 VS.COH_BOP                     AS COH_BOP,
 'F3'                           AS FORM_TP,
'"REPORT OF RECEIPTS AND DISBURSEMENTS FOR AN AUTHORIZED COMMITTEE"' AS FORM_TP_DESC,
 VS.ORIG_SUB_ID                 AS SUB_ID,
'Y'                             AS MOST_RECENT_FILING_FLAG,
VS.rpt_yr + VS.rpt_yr % 2::numeric AS election_cycle
FROM disclosure.v_sum_and_det_sum_report vs

**Comment by jwchumley** [comment]
This one should be pre-flilp!

**Comment by ccostino** [comment]
Thanks for all of the investigation, @jwchumley, @hcaofec, @PaulClark2, and @LindsayYoung!  I'm trying to catch up on all of this and am still a bit confused.  Based on everything I've read, it looks like the views (`fec_vsum_f3` and all related views) on the FEC side should be updated to reflect the proper values, or at least adjusted so more columns should be coming from `disclosure. v_sum_and_det_sum_report` instead?  Has this happened yet and if not, could we get them re-adjusted soon to move forward on this?

Furthemore, @PaulClark2's comment about [`COALESCE`](https://www.postgresql.org/docs/current/static/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL) is correct, it'll return the first non `null` value passed into it.  Would it make sense to use that to determine which table to pull a value from, or would @LindsayYoung's remark about the greater value necessitate using [`GREATEST`](https://www.postgresql.org/docs/current/static/functions-conditional.html#FUNCTIONS-GREATEST-LEAST) instead (or in combination with to account for `null` values)?

**Comment by LindsayYoung** [comment]
You want greatest, because we found the when we used coalesce, it led to data errors. People we would see 0 in the first column, since that is not a null, the coalesce statement would not then take the real amount that was posted in the second column.

**Comment by ccostino** [comment]
Just to recapture notes from our sprint planning (cc @noahmanger):

* @jwchumley is creating a new view(s) for the data
* @ccostino will create a new endpoint(s) based on the view(s)
* ??? will update the web app to utilize the new endpoint(s)

Some documentation updates are probably in order with this too, and a new issue should be created for the longer term work of migrating the older API endpoints.

@LindsayYoung or @jwchumley did I miss anything?

**Comment by LindsayYoung** [comment]
@ccostino I can take this pre-flip priority off your plate

**Comment by ccostino** [comment]
Thanks, @LindsayYoung, I appreciate it!

**Comment by LindsayYoung** [comment]
closed by https://github.com/18F/openFEC/pull/2366
