### ISSUE TITLE
RAD Analyst API Update Request

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC#2261]
@LindsayYoung Currently the RAD Analyst API returns only analysts who have committees assigned to them. RAD has requested that the API also returns results for analysts who do not have a committee assigned. In the goldengate instance, `disclosure.rad_cmte_analyst_search_vw` and `disclosure.rad_active_analyst_vw` now exist. Would you be able to join these two views together so that the API will return all active analyst user data even if a committee is not assigned to them?

**Comment by fecjjeng** [comment]
- disclosure.rad_active_analyst_vw  include all active analysts' data, with or without committee assigned.
- disclosure.rad_cmte_analyst_search_vw include active analyst with their assigned committee information.

**Comment by vrajmohan** [comment]
1. Should the `cmte_id` and `cmte_nm` be `NULL` for the active analysts without committees?
2. `telephone_ext` in `disclosure.rad_cmte_analyst_search_vw`  is a pure extension, presumably the committee has an actual phone number? In `disclosure.rad_active_analyst_vw`, the analyst has an actual `anlyst_phone` which is a complete phone number. Should they be mapped to the same field or to 2 different fields?

**Comment by fecjjeng** [comment]
The anlyst_phone in disclosure.rad_active_analyst_vw is actually from the same field as the  telephone_ext field in disclosure.rad_cmte_analyst_search_vw.  The database table only has the telephone_ext, theanlyst_phone in  disclosure.rad_active_analyst_vw add prefix 202-694- to the telephone_ext to make the complete phone number, upon David's request.

**Comment by vrajmohan** [comment]
Does this call for a full outer join, i.e. do we have both the following cases?
1. Analysts who are in `rad_cmte_analyst_search_vw ` and not in `rad_active_analyst_vw`
2. Analysts who are in `rad_active_analyst_vw ` and not in `rad_cmte_analyst_search_vw`.

**Comment by fecjjeng** [comment]
As far as I understand, committees will only be assigned to active analysts.  And one analysts could have multiple committees assigned to him/her.  But there could be active analysts that has no committees assigned to him/her.  Please confirm with RAD.
rad_cmte_analyst_search_vw  is currently being used, while rad_active_analyst_vw is created based on what David think is needed for a separate API (maybe the one your are working on?) to show analyst information for all the active analysts (with or without committees assigned).  Does the API need to show active analysts with the assigned committeeS?
