### ISSUE TITLE
Delete EW apps

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2264]
We are moved to gov cloud so we can tear that down

---
Delete:
- [x] Apps
- [x] Databases

**Comment by ccostino** [comment]
Hard to believe the time has come!

**Comment by ccostino** [comment]
We're going to delete the apps and E/W setup in cloud.gov first, then about a week later we can tackle the databases (and coordinate that with Rohan and Jean).

**Comment by ccostino** [comment]
I also reached out to the folks helping with cloud.gov migrations to schedule a time to work with one of them next week on this.

**Comment by ccostino** [comment]
Quick follow-up - we need to reach out and let infrastructure folks know about the RDS instances, not cloud.gov folks.

**Comment by ccostino** [comment]
Apps and org are completely gone in E/W!  Just the older RDS instances remain.

**Comment by ccostino** [comment]
We're going to ping infrastructure to remove the old E/W RDS instances.

**Comment by ccostino** [comment]
@LindsayYoung did we ever get follow up on if the E/W RDS instances were removed, or should we reach back out to the infrastructure team?

**Comment by ccostino** [comment]
We're going to follow up and see if we can close this out.  The work is in the 18F Infrastructure team's hands now, but it'd be nice to close the loop.

**Comment by ccostino** [comment]
The databases are removed as of this morning!  Thanks for following up, @LindsayYoung!
