### ISSUE TITLE
Run update_all in cloud.gov dev, staging and production databases

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2267]
As discussed in grooming, we need to run the update_all script.

**Comment by ccostino** [comment]
This has been largely taken care of as a consequence of the fixes made to address #2286, but only staging will be complete as of today.  The `dev` and `prod` instances will still need the remaining updates run after the partitioning is complete in them.

Huge thank you to @LindsayYoung and @jontours for all of the help and support with getting these updates back on track with me!
