### ISSUE TITLE
Directly insert data instead of using queue tables

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2268]
This task is to look into using upsert for schedule A, B, and E aggregates after we've updated to the latest postgres version.

I'm not sure what all is included in this, so @ccostino feel free to edit this issue.

**Comment by ccostino** [comment]
Ah, thanks @noahmanger, but we already have an issue for this! :-) #2227 has all of the details; sorry for the confusion, I thought I had shared the link with you already!

**Comment by noahmanger** [comment]
Oh! My bad. Closing.
