### ISSUE TITLE
Introduce high-level Python version pinning

### ISSUE THREAD

**Issue by dogweather** [18F/openFEC#2271]
Soft Pinning with Python Package Dependency Resolution
----------------------------------------------------------
We'll create `requirements.in` files like [this one in OMB eRegs](https://github.com/18F/omb-eregs/blob/master/requirements.in#L2) which we'll write by hand, instead of manually editing `requirements.txt`. Then, we'll use [pip-tools](https://github.com/jazzband/pip-tools) to resolve Python package dependencies and fully manage `requirements.txt` for us. Pip-tools will also be how we install and upgrade the Python packages. This is also described in [Before you Ship](https://pages.18f.gov/before-you-ship/infrastructure/pinning-dependencies/).

The benefits of this, and why it's increasingly what projects do
---------------------------------------------------------------
This is SOP in Ruby, Elixir, and increasingly, Python, because;

* Packages can be upgraded with a much greater degree of safety and confidence.
* Teams upgrade more frequently because it's easy to, getting bug and security fixes faster, and reducing technical debt.
* Configuration is simpler because teams only need to list the high-level dependencies in `requirements.in`. This file is much shorter than `requirements.txt` and not cluttered with transitive dependencies
* Configuration is less error prone because there's a clear separation of concerns: people edit one file, and the software edits the other. Each file does its one job, better.

**Comment by ccostino** [comment]
@dogweather, definitely good to keep in mind, but we do pin our dependencies already in the FEC repos. :-)

This one, for example: https://github.com/18F/openFEC/blob/develop/requirements.txt

(I have a PR open to remove setuptools and wheel now that we fixed the Slate issue

**Comment by ccostino** [comment]
Ack, wrong button, didn't mean to close just yet!

**Comment by dogweather** [comment]
I added a full description to show how this differs from our current practices.

**Comment by ccostino** [comment]
Awesome, thank you!

**Comment by cmc333333** [comment]
I think the big win here is around transitive dependencies. Here's a specific example: 

* `cfenv` (which is [included](https://github.com/18F/openFEC/blob/develop/requirements.txt#L4) in the openFEC requirements file) [depends on](https://github.com/jmcarp/py-cfenv/blob/master/setup.py#L8) `furl`, version >= 0.4.8
* `furl`, in turn, [depends on](https://github.com/gruns/furl/blob/master/setup.py#L98-L99) a minimum version of both `orderedmultidict` and `six`. These three libraries aren't currently part of openFEC's `requirements.txt`.

So, when we run `pip install -r requirements.txt` we install all four libraries... but what _version_ of `six`, `orderedmutlidict` and `furl` will be used? All pip knows is that it has a lower bound; it'll default to grabbing the latest version of each, which means your operating environment may change over time.

You can think of `pip-tools` as one step up from `pip freeze > requirements.txt`. It adds a few niceties around tracking dependencies and gives some for updating libs, but I'd argue the core benefit is around those transitive dependencies.

**Comment by ccostino** [comment]
Yup, you're absolutely right, and we were bitten by this twice recently:  once with `flask-apispec` (the underlying `apispec` dependency suddenly changed on us, [requiring a fix](https://github.com/18F/openFEC/commit/6a1652bc9700d38d9d345ecb0af362fc8ea0ae18)), and again when trying to upgrade to using Python 3.6 with the `slate` dependency!
