### ISSUE TITLE
Redeploy apps every 3 days

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2291]
This sounds like something to automate with travis.

**Comment by LindsayYoung** [comment]
Sounds like Travis doesn't have too fine tuned of a cron job so we could do this daily if it is easier to execute. 74 hours is the max we want a container to live on production.

**Comment by anthonygarvan** [comment]
Set up to run daily rebuilds on `develop` for api / web / cms / eregs. Will set up on prod tomorrow assuming the overnight build on `develop` has no surprises.
