### ISSUE TITLE
Categorize RFQs as RFAIs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2292]
As reported in https://github.com/18F/FEC/issues/1136, many RFAIs aren't showing up as RFAIs. That's because they're RFQs. Lindsay outlined a solution here https://github.com/18F/FEC/issues/1136#issuecomment-286597051

- [x] Document description should start with `RFAI`
- [x] Filtering `form_type=RFAI` should include these as well

**Comment by PaulClark2** [comment]
RFAIs and FRQs are the same thing. You'll find FRQ in the `form_tp` column in `DISCLOSURE.F_RPT_OR_FORM_SUB` It's just a form type abbreviation. 

What's the source of the RFAIs?  I'm not seeing it quickly. I don't see 'nml_form_rfai` in public or disclosure.

**Comment by noahmanger** [comment]
Another comment just came in about this https://github.com/18F/FEC/issues/3950

**Comment by noahmanger** [comment]
A simple option for now could also be to just have a separate filter on the front end for `RFQ` in addition to the `RFAI` filter, but change the `document_description` to be `RFA:...`

**Comment by PaulClark2** [comment]
2 filters or 1 filter that includes both `RFQ` and `RFAI`?

**Comment by jontours** [comment]
I think the latter is what is needed.  I thought about it after the call a bit and I think it will be trivial to hook into the query filter logic for this.  So right now I'm saying easy peasey.

**Comment by noahmanger** [comment]
Ok great. Yeah if we can just send a single value from the app that makes it way easier.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2349 . Thanks!
