### ISSUE TITLE
Add the ability to change the number of results that are viewed on a page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#230]
User should be able to manually choose how many results to view

**Comment by noahmanger** [comment]
This feels like more of a @theresaanna task. Moving to you friend.

**Comment by theresaanna** [comment]
What do you want the input to be like? Drop down? Text field? If the latter, we'll probably have to implement a max number.

**Comment by noahmanger** [comment]
Dropdown works!

**Comment by jmcarp** [comment]
Added with datatables.
