### ISSUE TITLE
All filter and sort fields need indexes

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2300]
Found a lot of fields that were not indexed on the efiling records. It could be that we just removed inadvertently when we switched DBs

**Comment by noahmanger** [comment]
Temporary fix for now: take out index validation.

**Comment by noahmanger** [comment]
Is this the reason that the efiling reports endpoint is throwing 422s right now? https://api.open.fec.gov/v1/efile/reports/presidential/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&data_type=efiling&sort=-receipt_date&per_page=30&page=1
