### ISSUE TITLE
Bind all S3 buckets as services in GovCloud

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2301]
Now that we are running GovCloud and most (if not all) of our S3 buckets are running in the same environment as our apps.  We should consolidate our buckets and make sure they are named appropriately and bound to the correct apps so we do not have to manage them separately in multiple spots like our proxy app, envvars, etc.

One exception is the transition site bucket as @patphongs still needs direct access to that, but most of the others we should be able to clean up and consolidate to some degree.

@LindsayYoung, please feel free to correct or add anything here!

**Comment by LindsayYoung** [comment]
I do like content having its own bucket because we delete things out of the downlads/legal bucket nightly, That brings us to 3 buckets because the cms dump needs to be on a private bucket. 

How would you propose consolidating @ccostino ?

**Comment by ccostino** [comment]
Ah, if we're already down just to those 3 buckets then I think we should be good to go - it's easier to just clear out a bucket wholesale in the case of the downloads and legal buckets, this way we don't risk accidentally removing any content and it allows the content authors freedom to manage and organize the content bucket as they see fit.

Given all of that, then we're probably all set. :-)

**Comment by LindsayYoung** [comment]
high-five
