### ISSUE TITLE
Show FEC how to do on-demand legal doc refresh

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2307]

**Comment by vrajmohan** [comment]
During sprint planning, it was mentioned that we need to have the following FEC team members trained on this:

1. John Carroll
2. Jeff Chumley
3. Paul Clark
4. Pat Phongsvirajati

Did I miss anyone?

**Comment by PaulClark2** [comment]
Please add Jason Bucelato and Eileen Canavan Leamon to the list above

**Comment by vrajmohan** [comment]
The process was presented to the team listed above. @patphongs was able to successfully load AOs from a starting number on the `dev` environment. 

It was decided that the loads should be set up as a step in the publishing process by Salient. In the interim, Jason (and/or his team) would notify Pat (and/or her team) to load this on demand. 

We also discussed having the 0 downtime refresh happen automatically with the nightly loads. @jwchumley suggested that we hold off on that until we get an effort estimate from Salient.
