### ISSUE TITLE
Financial summary links

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2320]
The Links to transactions on the summary page should be filled out so all the types that have transactions supporting them should be linked to. The "Total" categories like Total Receipts and Total Disbursements should not have links. T.Receipts is problematic because it includes unitemized transaction totals and a link implies that you will find them there but they don't exist. I could be convinced that that's OK but only in conjunction with adding all the other links.

I see this a a post site-flip issue

**Comment by noahmanger** [comment]
We can remove links from the top level totals. Adding additional links is dependent on adding the line number filter to receipts and disbursements in #2228 .

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1966
