### ISSUE TITLE
"Raising Data Overview" link has unexpected result

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2321]
“Advance Data”, then “Raising”, when you click on “Raising Data Overview” or "Spending Data Overview", it takes you back to the homepage, is that correct?

**Comment by noahmanger** [comment]
Yeah, it's meant to take to the overview charts on the landing page.

**Comment by jenniferthibault** [comment]
This is part of the fix being implemented in https://github.com/18F/openFEC-web-app/pull/1966

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1966
