### ISSUE TITLE
Can't find form 2 list when looking at candidate profile

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2322]
Committee profile has a link to filings but candidate profile doesn't. It should. Otherwise you can't find the form 2 list from the profile.

Pre-flip if possible. If not possible first post-flip sprint I think.

**Comment by noahmanger** [comment]
Form 2s (along with any other miscellaneous filings) are located on the "About this Candidate" page.

**Comment by jwchumley** [comment]
It doesn't seem to include anything but disavowal notices. No Form 2s. No RFAIs. Hoyer over time should have 23 form 2s, 1 RFAI, and 12 Disavowal notices.


https://beta.fec.gov/data/candidate/H2MD05155/?tab=about-candidate&cycle=2016


________________________________

**Comment by noahmanger** [comment]
Closing in favor of https://github.com/18F/openFEC-web-app/issues/1962
