### ISSUE TITLE
"Years Active" incorrect in older committees.

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2323]
In the two party committee examples below the listed “Years Active”, both committees were registered back in 1975, though these list 1994 and 2012 respectively as the origin year.  Where is it pulling these inception years from?  I’m concerned a committee using this might become upset as it may give the perception the committee has not been active as long as it has.  Thanks

![image](https://cloud.githubusercontent.com/assets/12615919/25091757/bbef3588-2358-11e7-9ea7-12b41f5e577a.png)

![image](https://cloud.githubusercontent.com/assets/12615919/25091785/d957fa9c-2358-11e7-8211-134e9cc7db82.png)

**Comment by noahmanger** [comment]
Fixing this in https://github.com/18F/openFEC-web-app/pull/1957

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1957
