### ISSUE TITLE
add indexes to dev and staging

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2333]
We might want it in the data folder too but we don't want it run regularly, it is adding some indexes upstream of us. 

create index on real_efile.sb4 (repid);
create index on real_efile.sb4 (comid);
create index on real_efile.sb4 (transdesc); 
create index on real_efile.sb4 (amount);
create index on real_efile.sb4 (state);
create index on real_efile.sb4 (date_dis);

create index on real_efile.summary (repid);
create index on real_efile.summary (create_dt);

create index on real_efile.f3 (comid);
create index on real_efile.f3p (comid);
create index on real_efile.f3x (comid);
create index on real_efile.f3 (repid);
create index on real_efile.f3p (repid);
create index on real_efile.f3x (repid);
create index on real_efile.f3 (create_dt);
create index on real_efile.f3p (create_dt);
create index on real_efile.f3x (create_dt);

**Comment by ccostino** [comment]
Just to note, these have already been added to prod!
