### ISSUE TITLE
Automatically trigger the loading of AOs when new data available in Postgres 

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2337]
To ensure that AOs and MURs are available as soon as they are _published_, create a `celery` worker that polls the Postgres tables for new data based on the `pg_date` column. If new data is available, kick off the process to load these new AOs and MURs into Elasticsearch and S3.

This process will still not handle updating older AOs to recognize newer AOs referencing them (the older AOs). This would still be handled by invoking the `refresh_legal_docs_zero_downtime` process on a periodic basis (nightly or weekly).

**Comment by vrajmohan** [comment]
Discussed with @anthonygarvan, the job that polls the DB for new AOs and MURs would run every _15 minutes_. It would look for documents updated in the last _24 hours_ and pull them in. This has the following benefits:
1. Handling of failed jobs. If the job did not run for some reason, a subsequent job would still be able to pick it up as long as all jobs in a 24 hour window do not fail.
2. Less infrastructure - simpler code. The refresh of the documents is idempotent - re-loading the same doc again causes no harm.

**Comment by vrajmohan** [comment]
Will be fixed by #2425.

**Comment by noahmanger** [comment]
Now live in production.
