### ISSUE TITLE
Restrict AO search for greater consistency

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2339]
So that users who go between the universal legal search and the advanced search have a consistent experience and understand what their query is actually searching, update the AO search so that the keyword search searches **final opinions**, **AO name** and **AO number** only.

This will have the following consequences:
1. Keywords occurring **only** outside these, say as requestors, commenters, etc will not result in matches
2. Citations would be matched because they **always** occur in the text of final opinions.

Because the universal search only searches final opinions, we'll also add links in the universal search results to "search other documents". 

---

Update:
- [ ] After doing this, see if it also fixes the issue of the "requestor" field not filtering only by requestor name. If it doesn't, make a new issue.

**Comment by noahmanger** [comment]
Tag @AmyKort

**Comment by AmyKort** [comment]
Sounds like a good plan to us. Thanks!

**Comment by AmyKort** [comment]
spoke too soon. OGC would like to take a day to think about it.

**Comment by noahmanger** [comment]
Ok. We were also thinking it probably makes sense to search the AO summary as well. This has been a feature people have asked for.

**Comment by vrajmohan** [comment]
@AmyKort, has there been any decision on this?

**Comment by AmyKort** [comment]
I asked this morning but I haven't heard back. If I don't hear anything by tomorrow, we can look at other next steps. Thanks!

**Comment by AmyKort** [comment]
OK! We're good to go on this as you've described it here. Thank you for your patience.
