### ISSUE TITLE
Test expanding 100k download limit

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2342]
Lots of people have asked about the 100k download limit. The other day we talked about trying to increase it and seeing how it affects performance. This is a post-flip thing to look into.

- [ ] celery worker
- [ ] maximum download target (500,000)

**Comment by PaulClark2** [comment]
Related to celery worker

**Comment by vrajmohan** [comment]
I tested 10 concurrent users using downloads. I tested that the Celery workers successfully completed the task of assembling and uploading the download file to S3.

**Comment by vrajmohan** [comment]
This has been deployed and can be closed.
