### ISSUE TITLE
Duplicate report data 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2354]
@fec-issue-bot commented on [Thu Apr 27 2017](https://github.com/18F/FEC/issues/4000)

## What were you trying to do and how can we improve it?
https://beta.fec.gov/data/filings/?data_type=processed&amp;committee_id=C00019331

The committee only filed one 2016 Year End Report. However, on the committee&#39;s filings page of the beta site, the results show an original 2016 Year End as well as an Amended 2016 Year End. Both reports have the same FEC filing ID (FEC-1146407).

## Tell us about yourself
THIS IS QUY. THERE. I SAID IT.

## Details
* URL: https://beta.fec.gov/data/filings/?data_type=processed&amp;committee_id=C00019331
* User Agent: Amazon CloudFront

**Comment by noahmanger** [comment]
Verifying that this looks like a weird issue. @jwchumley can you take a look and see if anything comes to mind?

**Comment by jenniferthibault** [comment]
@noahmanger @jwchumley this has also been reported in another issue: https://github.com/18F/FEC/issues/3947

**Comment by noahmanger** [comment]
Taggging in @PaulClark2 to look into this from the data side.

**Comment by PaulClark2** [comment]
![image](https://cloud.githubusercontent.com/assets/11817734/25917620/b481386e-3596-11e7-8ddb-8794f8706461.png)

**Comment by PaulClark2** [comment]
I think we are mistakenly displaying the Levin Funds Aggregation Page (Schedule L) as the 2016 year-end amendment.  If agreed, we should exclude SLs from the filings display and from any calculation of report version. 

`select form_type, committee_id, beginning_image_num, file_number, report_year, report_type from public.ofec_filings_mv where committee_id = 'C00500330' and report_year = 2016 and report_type = 'YE' and sub_id in (4011120171359693282, 4011120171359693804);`

Form 3X sub_id = 4011120171359693282
http://docquery.fec.gov/cgi-bin/fecimg/?201701109041355412

Schedule L (page 16) of above Form 3X --- Schedule L sub_id = 4011120171359693804
http://docquery.fec.gov/cgi-bin/fecimg/?201701109041355427

**Comment by noahmanger** [comment]
Just checking in on this. Does this need to be resolved for flip? If so, maybe @jontours or @anthonygarvan can look into it.

**Comment by PaulClark2** [comment]
This would be nice to have pre-flip. I think it's just ensuring we are excluding Schedule L and Schedule I.

**Comment by LindsayYoung** [comment]
Since this is the filings page, it seems to me that it would be correct that they submitted a 3x and a  3L. Shouldn't we show the difference in our records instead of getting rid of the supporting documents?

**Comment by PaulClark2** [comment]
This is Schedule L not a Form 3L.  We should show Form 3L but not Schedule L.

**Comment by jontours** [comment]
I can take a look at this today.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2413
