### ISSUE TITLE
Add Form 13 to /totals/

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2357]
Currently the financial totals from Form 13 (which is filed by an [inaugural committee like this](https://beta.fec.gov/data/committee/C00629584/)) are not included in the `/committee/{committee_id}/totals` endpoint, but should eventually. 

There's only three fields that need to be included: total donations accepted, total donations refunded, net donations.

This is a post-flip issue.

**Comment by PaulClark2** [comment]
There are four inaugural committees. G.W. Bush's second inauguration was the first time Form 13 was required. 

C00629584 - Trump
C00540005 - Obama 2
C00458166 - Obama 1
C00409011 - Bush 2

These committees are non-qualified party committees: committee type `X` and committee designation `U`.
