### ISSUE TITLE
Change RAD mv source

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2359]
Move off of `public.rad_cmte_analyst_search_vw` construct our views from
`disclosure.rad_cmte_analyst_search_vw` and `disclosure.rad_active_analyst_vw` instead

**Comment by LindsayYoung** [comment]
after moving, delete `public.rad_cmte_analyst_search_vw`

**Comment by vrajmohan** [comment]
I see that the view `rad_cmte_analyst_search_vw` exists in both the `public` and `disclosure` schemas (it is missing a `pg_date` column in the latter). Is it just a matter of using the right schema? How does `rad_active_analyst_vw` get used?
