### ISSUE TITLE
API/query tuning

### ISSUE THREAD

**Issue by catherinedevlin** [18F/openFEC#236]
For satisfying user experience, API needs faster performance for two specific types of requests:

- Totals/Summary tuning 
- Typeahead 

- Collect actual API calls for each of these requests
- Measure present API response time
- Cut Totals/Summary response time to 50% and typeahead time to 25% of current
- Document changes made to accomplish
- (perhaps) write performance "regression tests" to ensure that we're alerted if performance on these tasks degrades in the future

**Comment by rjmajma** [comment]
Catherine, would you mind breaking this up into three tickets? Unless it's representative of one single task.

**Comment by catherinedevlin** [comment]
Replacing with #247, #248, and #249
