### ISSUE TITLE
Mid-year and quarterly calendar filters

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2360]
As @llienfec originally brought up in https://github.com/18F/fec-cms/issues/1011, the calendar should include mid-year reporting deadlines, which as far as I can see, it doesn't currently include. 

Separately, she was wondering about the ability to distinguish between the two types of quarterly dates: 1) for authorized committees and 2) for PACs and parties.

@AmyKort does this need to be something we figure out pre-flip?

**Comment by AmyKort** [comment]
Since the mid-year is coming right up, I think we need to make that a pre-flip priority. I worry the MY's absence will undermine confidence in the calendar. If pre-flip is going to be too aggressive, then it needs to be a very fast follow.

**Comment by llienfec** [comment]
Agree w/ @AmyKort.  Let me know how I can help.

**Comment by noahmanger** [comment]
@LindsayYoung you're the keeper of calendar data knowledge. Any idea of the tables we're getting support this?

**Comment by noahmanger** [comment]
Most important thing pre-flip: the mid year report needs to show up; whether there's a filter or not can happen later.

**Comment by noahmanger** [comment]
Good news! These were already correctly categorized on the API and we were just missing the filters from the front-end. So I added them here https://github.com/18F/fec-cms/pull/1050

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1050
