### ISSUE TITLE
fec.gov and www.fec.gov domain changes

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC#2369]
## **www.fec.gov** domain 
Lindsay will create new name servers within terraform for hosting provider to point this domain to.

## **fec.gov** domain
1. spin up web server with apache or nginx
2. make https cert for fec.gov domain
3. set up a 301 permanent redirect for fec.gov --> www.fec.gov (This will ensure browsers and search engines will understand that www.fec.gov is the official URL for the new site and to direct users there by default if anyone hits fec.gov)
4. Test by having hosting provider point fec.gov  to static IP of web server redirecting to new website.

**Comment by LindsayYoung** [comment]
https://github.com/18F/fec-proxy/pull/32

**Comment by noahmanger** [comment]
Can this be closed now?

**Comment by noahmanger** [comment]
This is essentially done, with remaining tasks captured in https://github.com/18F/openFEC-web-app/issues/2049
