### ISSUE TITLE
Bug: Aggregates in 2017-2018 seem to be broken

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2375]
I'm noticing that on any candidate or committee page with date for the 2018 cycle, the aggregates are broken

![image](https://cloud.githubusercontent.com/assets/1696495/25828602/ed0b6872-3405-11e7-87a6-206678cec229.png)

[Example random committee](https://beta.fec.gov/data/committee/C00420398/?tab=receipts)

**Comment by noahmanger** [comment]
Might be related: https://beta.fec.gov/data/committee/C00638874/?tab=disbursements

**Comment by ccostino** [comment]
Interesting, I started looking at this some and for the related issue, I'm seeing transactions set in the future for that PAC:  https://beta.fec.gov/data/committee/C00638874/?tab=disbursements (click on `All transactions`).

**Comment by ccostino** [comment]
This also seems fixed in staging, using your example committee: https://fec-stage-proxy.app.cloud.gov/data/committee/C00420398/?tab=receipts

I'm guessing the update_schemas took care of that.

**Comment by ccostino** [comment]
@LindsayYoung has been running materialized views and aggregate updates in production; once those are done we can check again to see how the beta site looks.

**Comment by noahmanger** [comment]
These are working now.
