### ISSUE TITLE
Request: Add state filter for filings and reports

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2378]
So that users with a particular geographic interest can track filings and reports in their area, add a state filter for filings and reports.

---

This request has come in a couple times, including https://github.com/18F/FEC/issues/4031 and https://github.com/18F/FEC/issues/4168 and https://github.com/18F/FEC/issues/4185

This would need to be added to the API before it can be added to the web app.

Form Form 2s, it would be the state of the candidate that they're running in; for all others it would be the state of the committee registration.

**Step 1**
- [x] Clarify user needs and design options for this

**Step 2: Add filters to API**
- [x] Add `state` filter to `/filings/` that filters by the state of the entity filing
- [x] Add `district` filter to `/filings/` that filters F2s to the district of the candidate
- [x] Add `office` filter to `/filings/` that filters F2s to the office of the candidate
- [x] Add `party` filter to `/filings/` that filters F2s to the party of the candidate
- [x] Add `first_filing_date` filter to `/candidates/` that filters by the date of the first F2 and add it to the reponse
- [x] Add a `first_filing_date` filter to `/committees/` and add it to the response

**Step 3: Update front-end**
- [ ] Create a page at `/filings/statements-of-candidacy` with filters for state, district, party, office, date and candidate name
- [x] Update the top-level `/candidates/` page with a column of `first_file_date` and with a filter for that
- [x] Update the top-level `/committees/` page with a column of `first_file_date` and with a filter for that

**Comment by noahmanger** [comment]
Ok here's some ideas and attempt at clarification. 

As it's been communicated, the need here is to be able to see new candidate registrations for a particular state and/or district so that you can keep tabs on a particular race or set of races as new people enter.

There's three ways we could go about this:

## Option 1: Add a filter to Filings
This would mean adding "Candidate state" and "Candidate district" filters to fec.gov/data/filings, which would only apply to form 2s (statements of candidacy). Perhaps like:
![image](https://user-images.githubusercontent.com/1696495/27158654-e1aaa630-511c-11e7-80b2-ebae2dbc4a20.png)

Because these only apply to F2s, the filters might seem a little odd on this page; we've tried to stick to a rule of having all filters make sense for all data on a given page.

Which leads to...

## Option 2: Separate Statements of Candidacy page
To stick with our principle, we could make a new statements of candidacy page that only shows F2s and the unique filters that make sense for them. If it makes sense, we could do the same for statements of organization (F1s). This maps closest to the experience on classic.fec.gov.

## Option 3: Enhance candidate and committee data pages
Alternatively, we could stick to the goal to separate the data from the form it was filed on and rely on the fec.gov/data/candidates fec.gov/data/committees. The problem with these pages currently, however, is that they do not show the first date filed or expose filters for these fields. If we go this route, we'd need to add that to the API. Additionally, it could be helpful to include links to the original F1 / F2 for each entry, either in the table or in the details panel. I know this has been requested before. 

These pages could be sorted by default on first file date, so newer entries are at the top. And then users could use the state/district filters to narrow the list. 

The advantages to this approach is it is modeled after the type of information rather than the source of information and keeps similar info together; the downside is that it's a departure from the old way of doing things so will be a minor learning curve.

**Comment by nickykrause** [comment]
Stayed on to talk with Noah about this after standup, just to make sure I understand what he's saying. A few things we thought about:

- The option of adding this to the filing table seems to resemble the kind of problem we had with the  Form/Line number filters, where we're talking about conditional logic (i.e., "if the statement of candidacy form is selected, then enable this filter for the candidate's state"). 
    - It might be helpful to avoid that kind of logic, if possible. Separating out statements of candidacy as their own table, as Noah suggested, might be one way to do that. ( 💡 This raises interesting questions about how, when, and why we decide to separate out unique tables for things.)

- Adding this to the candidate/committee tables seems like another way of avoiding the conditional logic problem, in addition to the benefits Noah mentioned above. 

- It may be worth adding the state functionality to _both_ tables, in the end, but, **to me, it seems like we may have a stronger case for adding it to the Candidate / Committee tables as a first pass.** 

Finally:

- We are talking about a situation where a user wants to track the status of a specific race (which is taking place in a specific state/district), with the specific question: "Who has recently registered as a candidate in this race?" This seems like the kind of need / question that would be relevant to whatever we design for the "election map," so I'm going to feed it into [that research issue](https://github.com/18F/openFEC-web-app/issues/2100).

**Comment by jenniferthibault** [comment]
👀  I don't yet have a specific opinion on whether to separate or not, but I wanted to add that the pattern of narrowing by state/district is often accompanied by `Office sought` and `Political party` as taken from the candidate search. It feels like we should keep that mental model consistent, even though WE know on the back end we know it's searching across different things:

![screen shot 2017-06-16 at 11 10 44 am](https://user-images.githubusercontent.com/11636908/27232566-80886f0e-5284-11e7-8625-0f0eb5c65664.png)

**Comment by noahmanger** [comment]
Makes sense. I've updated the issue with the tasks for this approach.

**Comment by PaulClark2** [comment]
Determine behavior of financial filings and F2s.

**Comment by jontours** [comment]
@noahmanger while implementing this trying to wrap my head around the filters, so for example this bullet point: Add district filter to /filings/ that filters F2s to the district of the candidate.

So would you only expect the results to contain F2 filers?

**Comment by jontours** [comment]
Sorry to be sputtering on this (most filters are done), but are we expecting `first_file_date` to be a boolean?  For example, if the filter is applied, filters down to all candidate filings by the first filings?

**Comment by LindsayYoung** [comment]
First file date should be the first time the committee filed, so it can be used as a founding date. It is usually the first Form 1 but non-committees don't file those so we have to look for the first document.

**Comment by jontours** [comment]
Yeah, that's pretty straightforward to understand.  If it's just adding a column to all the rows with the `first_filing_date` than that's simple.  But it's described as a filter, so what are we filtering?

**Comment by jontours** [comment]
Ah after reading the write up, it seems that a filter for first_filed, as well as a column for that field is what is needed.

**Comment by LindsayYoung** [comment]
It is helpful for sorting, and currently on the committees endpoint IIRC

**Comment by jontours** [comment]
Ok, I think I was just overthinking it.  Just a regular date filter is needed.  I was confusing myself because it seemed as though a regular date filter was needed, but that seemed pointless if you didn't know the first filing date.  Monday coding!!

**Comment by noahmanger** [comment]
Sorry, I didn't describe that great. It should be a range filter, like `min_first_file_date` and `max_first_file_date` (like our other date filters). It should also be a column. And it should be sortable.
