### ISSUE TITLE
Rotate tokens (due May 18)

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2387]
18F/openFEC-web-app keys to rotate in Travis
- [x]  FEC_CF_PASSWORD
- [ ]  ~SAUCE_ACCESS_KEY~
- [ ]  ~SAUCE_USERNAME~

**Comment by ccostino** [comment]
I've never seen anything having to do with Sauce Labs - @noahmanger do you know anything about this or if we have an account, and if so, are we still actively using it?  If we're not, we should just eliminate them (the best kind of rotation!).

**Comment by ccostino** [comment]
Come to think of it, @micahsaul do you know anything about the Sauce Labs account with the FEC project? :-)

**Comment by LindsayYoung** [comment]
FEC_CF_PASSWORD was from an old incident and we don't use that on govcloud, we use a deployer account for each environment

**Comment by micahsaul** [comment]
I believe @theresaanna initially set the sauce stuff up.

**Comment by noahmanger** [comment]
We don't use Sauce anymore, so we shouldn't need those, right?

**Comment by noahmanger** [comment]
We don't need Sauce, so this is resolved.
