### ISSUE TITLE
set cache per endpoint

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2389]
I propose we: 
 - give the totals an hour
 - give the real-time endpoints 5 minutes

We already have a function to add headers, once this is done we will want to take off the 10 max-age cache in the API umbrella

**Comment by PaulClark2** [comment]
Is it possible for the real-time endpoints' cache to be variable. 5 minutes is probably fine most of the time but the day before, day of and day after a filing deadline, 5 minutes will seem like a long time for a refresh.

**Comment by LindsayYoung** [comment]
The cache is most useful when people are heavily using the endpoint, so realistically making it longer during periods of low traffic is not helpful. 

How long do you think we should cache them for? My understanding from outsiders, which could be incorrect or outdated, is that the current cache on the data is 15minutes. I would be ok with going as low as 1 minute, it might have performance costs across the system during deadlines, but we could change it later if we need to. Generally, speaking I love fresh data.

**Comment by PaulClark2** [comment]
If folks you've been talking with say 15 minutes is ok.  Then, let's just stick with your original 5 minute suggestion.

**Comment by LindsayYoung** [comment]
I double checked and it looks like there is currently a 6 minute cache here:
http://docquery.fec.gov/cgi-bin/forms/

I can check other places too if you have better examples
