### ISSUE TITLE
Take out bata language in docs

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2404]
Current language: 
https://api.open.fec.gov/developers/

Let's get rid of the " (Beta)" in the title

Git rid of:
"This site is in beta, which means we’re actively working on it and adding new features. The official  site for Federal Election Commission (FEC) data is still the Campaign Finance Disclosure Portal. While we plan to version big changes that are not backwards compatible, expect things to change as the API develops."

Any other suggestions, @jameshupp

**Comment by jameshupp** [comment]
I think that's sufficient unless there's anything else that needs saying about official data.
