### ISSUE TITLE
Add API support for sorting AO documents 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2415]
So that users can see the AO documents in the order they occurred, add API support for sorting AO documents in reverse chronological order.

---

Supports https://github.com/18F/openFEC-web-app/issues/2007

**Comment by vrajmohan** [comment]
FYI, the document dates have no time component (although they are of datatype `timestamp`). We may want to consider a secondary sort key if would like to have _repeatable_ results.

**Comment by noahmanger** [comment]
Ah! Good catch. What about just sorting alphabetically by document name? cc @nickykrause

**Comment by nickykrause** [comment]
So, are they just sorted randomly now? I am just wondering if there is some logic to their current sorting that isn't obvious to us, but that apparently the FEC users have found okay/helpful.

Sorting alphabetically makes sense to me, as compared to a random arrangement.

**Comment by vrajmohan** [comment]
They appear to be alphabetical within date _ascending_ in the old system. On investigating this, I discovered that there are duplicates in the document names as well. See https://www.fec.gov/data/legal/advisory-opinions/2012-25/ and http://saos.fec.gov/saos/searchao?AONUMBER=2012-25.

**Comment by vrajmohan** [comment]
I recommend going with date descending (reverse chronological), followed by document name, followed by `document_id` (which is a purely artificial serial number that is not displayed, but will help keep the results repeatable).

**Comment by nickykrause** [comment]
@vrajmohan that sounds good to me
