### ISSUE TITLE
Schedule C (itemized Loans) not working

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2417]
It was a table and is now a view, we can't do triggers, I think we should move it to sql_updates and do a materialized view

**Comment by ccostino** [comment]
Ah, make it a materialized view as opposed to what we've done with the other schedule tables?

**Comment by noahmanger** [comment]
Let's add a synthetic once this is done.

**Comment by noahmanger** [comment]
Also happening for party coordinated expenditures: https://www.fec.gov/data/party-coordinated-expenditures/

**Comment by ccostino** [comment]
@jontours is going to tackle party coordinated expenditures while I tackle this!

**Comment by ccostino** [comment]
@noahmanger, what is a synthetic?  I heard it mentioned before but am forgetting and don't have the context.

**Comment by noahmanger** [comment]
A New Relic monitor.

**Comment by noahmanger** [comment]
Resolved on Friday.
