### ISSUE TITLE
Financial summary for committee with multiple committee types during two-year period

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2419]
We need to figure out a way to display the financial information of committees with multiple committee types during two-year period. Example below is committee C00583146.

FORM_TP_CD	|	RPT_YR	|	RPT_TP	|	CVG_END_DT	|	TTL_RECEIPTS	|	TTL_DISB
---	|	---	|	---	|	---	|	---	|	---
F3P	|	2015	|	Q3	|	20150930	|	$1,016,189.22	|	$442,253.62
F3X	|	2015	|	YE	|	20151231	|	$220,255.80	|	$739,161.20
F3X	|	2016	|	Q1	|	20160331	|	$6,465.99	|	$53,410.07
F3X	|	2016	|	TER	|	20160429	|	$14,325.21	|	$22,411.33

Form	|	TTL_RECEIPTS	|	TTL_DISB
---	|	---	|	---
F3P total	|	$1,016,189.22	|	$442,253.62
F3X total	|	$241,047.00	|	$814,982.60
Total 	|	$1,257,236.22	|	$1,257,236.22

![image](https://cloud.githubusercontent.com/assets/11817734/26416330/807fc948-4083-11e7-98ff-15a7083d9e63.png)

![image](https://cloud.githubusercontent.com/assets/11817734/26416343/8aa8bd62-4083-11e7-90e9-a95dc0ef83b5.png)

**Comment by jwchumley** [comment]
This is probably also a problem when a committee accidentally files the wrong form.

**Comment by noahmanger** [comment]
How do you deal with this in the old viewer, considering the different forms have different fields?

**Comment by PaulClark2** [comment]
I think the result set is correct and the behavior we designed. The "2018" list should show all 2017 and 2018 candidates, right? 

Mr. Ossoff and Mr. Gianforte are 2017 candidates in special elections in Georgia and Montana, respectively.

**Comment by jwchumley** [comment]
@noahmanger 

In the old system we combined all of the financial form data - F3, F3x, F3p, F5 etc. - into the v_sum table with a common format for common columns. It wasn't perfect because it didn't handle amendments of unlike forms. If a New report was filed on form 3P and amended with a form 3X both forms would be included and double the totals. We had to take care of this manually.
