### ISSUE TITLE
Begin looking at documents endpoint

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#242]
Begin looking at what will be required in an endpoint for the documents.

- [ ] Populate the rest of this list
- [X] Examine current state of the world on existing FEC page.
- [x] Contact FEC and ask about where the document metadata lives.
- [ ] Write up plan for endpoint, including mapping, with intent to begin implementing next sprint.

**Comment by rjmajma** [comment]
Moved to the backlog. Awaiting a response from FEC.
