### ISSUE TITLE
Fix 500 Error when accessing non-existent MUR #

### ISSUE THREAD

**Issue by anthonygarvan** [18F/openFEC#2420]
We are seeing this issue pop on production when people are checking to see if a mur number exists. 
`[2017-05-23 21:10:51,853] ERROR in app: Exception on /legal/matter-under-review/7040/ [GET]`

Problem is on this line in legal.py in the web app `load_legal_mur` function:
`mur = mur['docs'][0]`

Index[0] does not exist- no murs are returned.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2447
