### ISSUE TITLE
Database improvements for itemized schedule data

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2423]
Related to issue #2373 

We should investigate a bit more on the database side of things to see if there's anything else we can do in or leverage from PostgreSQL to make our itemize schedule data more performant, especially in the case of being able to browse/filter/search records across multiple cycles.

There are a small handful of things we could look at that'll let us know if anything is possible:

* Query performance tuning for schedule A and B queries
* Testing SELECTs across multiple cycles (read: multiple child tables) and whether or not we need to limit how many
* Current index setup and if any others would help or hinder
* Other server settings we haven't tweaked yet but are exposed to us in RDS

I think these are all relatively lightweight things to focus on with what we have to see if we really are pushing the boundaries of what's possible in our current setup.

This work is partially related to the PR we have open to refactor the itemized schedule data that we partition (#2410) as well as issue #2394 (more directly to that one), but they're not dependent on one another.  I'm just noting that these things might be easier to accomplish with a simpler setup. :-)

## UPDATE ON 8/1/2017

We've made several improvements to the PostgreSQL server settings (some in response to recent production performance issues we've experienced), implemented a large chunk of refactoring (#2498) of the itemized schedule A and B setup, and added an initial set of indexes (#2530) to support working with itemized schedule data across cycles.

We've also started conducted some performance and usability tests (from the API) of this work and early results are promising for the pieces we know to be working, but less so for other parts (e.g., filtering by occupation - @LindsayYoung please correct me if I'm wrong).  We need to continue with our testing and tweak/add any index combinations that are either not working as expected or currently missing.

**Comment by ccostino** [comment]
This work is happening as a part of #2446, it just breaks down the performance tuning pieces into more granular details.

**Comment by ccostino** [comment]
@anthonygarvan is it safe to say that this has been happening as a part of your Elasticsearch research for #2373?

**Comment by anthonygarvan** [comment]
Conclusion of [2373](https://github.com/18F/openFEC/issues/2373): performance should be acceptable across years if we have multicolumn indexes defined on ([query_field], [sort_field], sub_id), where query_field is any field we search by, and sort_field is either transaction date or transaction amount.

**Comment by ccostino** [comment]
The next stage of this work is dependent on #2446 being finished first.

**Comment by ccostino** [comment]
The initial refactoring has been completed as of #2498, paving the way for this work now.

**Comment by ccostino** [comment]
We recently completed work for adding indexes for the itemized schedule data (#2530), but some preliminary tests are yielding performance issues.  We either need to add some additional indexes we missed or tweak the existing ones.

This work is related to #2446 and is a specific improvement that must be made in order to move forward with allowing for filtering/searching/etc. across multiple cycles.

**Comment by ccostino** [comment]
We also have a WIP PR (#2558) to lift the two year restriction in the API and test with.

**Comment by ccostino** [comment]
With new indexes in place (which still need to be added across all environments and is currently happening for `dev` and `staging` - we're tracking the `update_all` runs in #2585), I think it's time we close this issue and open new ones with more specific criteria once we get more testing underway for the multi-cycle filtering/searching.
