### ISSUE TITLE
Recently-filed committees not showing up in search

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2426]
As reported in https://github.com/18F/FEC/issues/4107, there's an issue where committees that have recently filed aren't showing up in searches.

For example, C00641373 shows up  as a committee page (fec.gov/data/committee/C00641373) but not [when searching](https://www.fec.gov/data/committees/?q=C00641373).

This is a high priority issue.

**Comment by ccostino** [comment]
It also doesn't show up when you [use the site search](https://www.fec.gov/search/?type=candidates&type=committees&type=site&query=C00641373).

**Comment by PaulClark2** [comment]
On classic in the Viewer, EFO has a process that pushes that most recent candidate and committee information to a table the Viewer uses. These recently-filed committees and candidates are discoverable in the Viewer within a few minutes of receipt of the electronic filing.

**Comment by ccostino** [comment]
Okay good to know, thanks @PaulClark2!  The committee is available in the API itself and we can [see the committee details](https://www.fec.gov/data/committee/C00641373/), so it's something else on our side that's preventing it from showing up in these other endpoints.

**Comment by ccostino** [comment]
We think we uncovered the issue - our nightly refresh process needs to update the materialized views in the correct order.  We'll test and verify this shortly as a part of fixing #2416 since that hotfix will also require the materialized views to be updated.

**Comment by noahmanger** [comment]
This is now resolved https://github.com/18F/openFEC/issues/2426

**Comment by ccostino** [comment]
This is working now after an `update_schemas` was run and the fix is in place!
