### ISSUE TITLE
Problem with contributions by size on committee profile pages

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2430]
Reported by the press office:

The by size amounts here:
 https://www.fec.gov/data/committee/C00632232/?tab=receipts

are way wrong. 
They should be something like this:

1-between 200.01 and 499.99               242,937
 2-between 500 and 999.99                    201,717
 3-between 1000 and 1999.99                179,216.67
 4->=2000                                                162,700

**Comment by noahmanger** [comment]
Are the totals right? Wondering if we're missing a report?

**Comment by noahmanger** [comment]
These are now correct:
![image](https://cloud.githubusercontent.com/assets/1696495/26595714/3294f59e-4521-11e7-8df4-ab40166e359d.png)
