### ISSUE TITLE
Add archived MURs to API

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2444]

**Comment by vrajmohan** [comment]
The major differences between current and archived MURs at this point are:
1.  No `election cycle`, `commission_votes` in archived MURs
2. `url` field in current MURs is the URL for the canonical page; for archived MURs it is the URL of the single PDF comprising the MUR. There is no `documents` list for the archived MURs. To better handle this, should we add a `documents` list with a single document with the URL for the MUR PDF? Should we then make the `url` field the URL for the canonical page for this MUR?
3. Can we eliminate the `pdf_size` and `pdf_pages` fields? They don't seem very useful.
4. Archived MURs do not have participants with roles besides complainants and respondents.
5. Archived MURs do not have `dispositions` fields with citations in them. Instead there is a `citations` field with regulatory and statutory citations.
Tagging @anthonygarvan - we should have a quick discussion on next steps.

**Comment by vrajmohan** [comment]
After discussing with @anthonygarvan, we decided that there is no value to reconciling the structures of current and archived MURs. They have distinct UIs and search filters.

**Comment by vrajmohan** [comment]
The attached MURs were successfully loaded into `dev` as they have been merged into other MURs - https://docs.google.com/spreadsheets/d/1Lx20Coeo5P6syJE1cnP5_mI9FiFTOc3EklEudzG0CVw/edit#gid=0

**Comment by vrajmohan** [comment]
The attached list of MURs failed to be parsed due to other reasons - I tried a random sample and found that the PDFs could not be parsed as they were invalid.
[failed.txt](https://github.com/18F/openFEC/files/1136884/failed.txt)

**Comment by vrajmohan** [comment]
The code is merged - the remaining activities are:
- Load the archived MURs on `stage` and `prod`
- Follow up on MUR PDFs that cannot be parsed

**Comment by vrajmohan** [comment]
These failed on `stage` - [stage_failed.txt](https://github.com/18F/openFEC/files/1160210/stage_failed.txt)

**Comment by jwchumley** [comment]
Vraj,


I've looked at the first dozen pdfs on the failed in production list. They are all a mix of text that is good enough to OCR and text that is too poor including pages of handwritten scribble and images of checks and ledgers.  Most of the readable text is in the official FEC documents and most of the failed is in the attachments and printed respondents documents.


When you say fail, what does that mean? Is there no ocr text? is the ocr_text indicator -1?  I don't think the text could be improved by any re-OCR effort.


________________________________

**Comment by vrajmohan** [comment]
The following 3 MURs failed in all environments: `1829, 1999, 2229`. They do not exist on http://classic.fec.gov/disclosure_data/mur/.

**Comment by vrajmohan** [comment]
The rest of the archived MURs have been successfully loaded on `prod`, with the sole exception being 950, which is a 521MB PDF.

**Comment by vrajmohan** [comment]
https://www.fec.gov/files/legal/murs/950.pdf has also been loaded.
