### ISSUE TITLE
Bug: API should return empty string if no fecfile is present

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2455]
As noted in https://github.com/18F/FEC/issues/4173, when a filing or report has no FECfile the API is still returning a URL, just one that's missing the unique ID. As a result, we show a nonfunctional link on the front-end.

If there's no file the API should just return an empty string.

**Comment by LindsayYoung** [comment]
OK, we do check for nulls but there are 

I can see empty begin_image_num if I query 

`select begin_image_num, sub_id from disclosure.f_rpt_or_form_sub order by begin_image_num desc;`

  begin_image_num   │       sub_id        
────────────────────┼─────────────────────
                    │ 4102220021028265734
                    │ 1061920020000034179
                    │ 4041420031030751118
                    │ 4110420021028503724
                    │ 4092520021026890309
                    │ 4091720021026433765
                    │ 4082920021026177996
                    │ 4040320031030499309
                    │ 4091920021026544410
                    │ 4101520021027812636
                    │ 4050120021023905479
                    │ 4091920021026544411
                    │ 4110420021028503386
                    │ 4050120021023905480
but if 
```
fec=> select count(*) from disclosure.f_rpt_or_form_sub where begin_image_num = '';
 count 
───────
     0
(1 row)
fec=> select count(*) from disclosure.f_rpt_or_form_sub where begin_image_num = ' ';
 count 
───────
     0
(1 row)
fec=> select count(*) from disclosure.f_rpt_or_form_sub where begin_image_num = null;
 count 
───────
     0
```

**Comment by LindsayYoung** [comment]
I added some code to the python side to try an minimize this here https://github.com/18F/openFEC/pull/2485/files#diff-e5411531c5f9f547006ae961c1b88a0c
