### ISSUE TITLE
2017 Election Year for Presidential Candidates

### ISSUE THREAD

**Issue by gmj2053** [18F/openFEC#2456]
We are ingesting the 2017 special election candidates into our database for processing and noticed that we also have 5 candidates running for president this year.  
https://www.fec.gov/data/candidates/?election_year=2017&office=P
we are curious what this means.   are they actually registering for 2017/president even though there isn't an election in 2017?

**Comment by LindsayYoung** [comment]
Hi Gina,

Our data reflects what is filed with the FEC. Here is an example of candidate who registered to run in 2017: http://docquery.fec.gov/pdf/086/201508269001302086/201508269001302086.pdf 

You can double check this kind of data by clicking on the candidate profile and looking at the statement of organization in the about this candidate tab. 

We do correct any we make displaying or processing the paperwork, so please feel free to write in again if you find another error. 

Thanks for taking the time to write in.
