### ISSUE TITLE
Configure Postgres to parallelize queries

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2457]
This could give us a performance boost on some of our larger queries.

We can add parallelization to postgres by configuring the settings, It will automatically parallelize queries based on the comparative costs. 

https://www.postgresql.org/docs/9.6/static/when-can-parallel-query-be-used.html

**Completion criteria:**
- [x] Enable in the Postgres settings

**Comment by ccostino** [comment]
It looks like this is possible to take advantage of in RDS as well! https://aws.amazon.com/blogs/database/performing-parallel-queries-and-phrase-searching-with-amazon-rds-for-postgresql-9-6-1/

**Comment by ccostino** [comment]
According to the AWS article the only thing set was the `max_parallel_workers_per_gather` - no other values were configured to demonstrate the use of parallel query support.  I double checked and this is currently `0` in `dev` but we could test with a few different values to see.  I'll continue to dig to see if I come across any other recommendations!

**Comment by ccostino** [comment]
Other resources:

* [Parallel Query on the PostgreSQL Wiki](https://wiki.postgresql.org/wiki/Parallel_Query): recommends a `max_parallel_workers_per_gather` value between `1 - 4` with respect to the value of `max_worker_processes`.
* [Programster's Blog post on Parallel Queries](http://blog.programster.org/postgresql-parallel-queries/):  shares roughly the same tidbits of info as the documentation and AWS post but mentions restarting the server, which the AWS article didn't seem to have to do.

It really seems like it's just that one setting and you can opt to tweak the others but that's not as necessary.

For fun, [there's going to be more coming in PostgreSQL 10](http://rhaas.blogspot.com/2017/03/parallel-query-v2.html) it looks like. :-)

**Comment by ccostino** [comment]
I've enabled this in `dev` currently:

```sql
SET max_parallel_workers_per_gather=4;
```

After performing several tests with queries that can take advantage of this, there is a very noticeable improvement in performance!  We've been documenting these in the FEC shared folder.

**Comment by ccostino** [comment]
This would have to be enabled separately for each instance, including the read replicas.

**Comment by ccostino** [comment]
This is now enabled across all instances.  Let's monitor how things go for a day or so before closing this issue. :-)

**Comment by ccostino** [comment]
I checked the RDS instances this morning and it looks like the prod instances are all working just fine - CPU usage seems to be around 10% or so for all of them and the read IOPS graphs are showing a lot of usage, but it appears that everything is working just fine!

**Comment by ccostino** [comment]
It turns out the setting wasn't persistent, so we have to figure out how to make it stick.

**Comment by ccostino** [comment]
The work to support this is happening in https://github.com/18F/fec-infrastructure/pull/15

**Comment by ccostino** [comment]
Production support added with https://github.com/18F/fec-infrastructure/pull/17

**Comment by ccostino** [comment]
Parallel query support is now enabled and live across all instances!
