### ISSUE TITLE
Net Contributions and Net Operating Expenditures are wrong in API

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2458]
Looks like the API is adding all the net contributions and net operating expenditures during the two year period instead of taking the final one.  On the presidential report there is only the cycle to date figure which should be taken from the latest report in the period.

This is only a problem with Form 3P (presidentials) because the Form 3 (House and Senate) has a column A and it sums correctly.

@LindsayYoung @ccostino @noahmanger

**Comment by jontours** [comment]
@jwchumley I'm currently refactoring this work.  I'll make sure they are correct.

**Comment by jwchumley** [comment]
Thanks, Jon.


________________________________

**Comment by jontours** [comment]
@jwchumley would it be possible for me to get a known good value for these columns, say McCain 2008 race?

**Comment by jwchumley** [comment]
McCain 2008: 
Correct Net Contributions: -$465,163
Net Operating Expendigures: $13,612,459

How about Obama 2012:
Correct Net Contributions: $53,741,272.52
Correct Ne operating expenditures: $163,225,881.04

**Comment by jontours** [comment]
Thanks!

**Comment by jwchumley** [comment]
@jontours 
Confirmed. The correct method is to grab the latest report in the two year period. In these cases the YE but in the current cycle it would be the latest filed report.

**Comment by jontours** [comment]
Just verified this is remedied with the PR I'm working on, should be up on staging soon.

**Comment by noahmanger** [comment]
This still looks wrong in staging: https://fec-stage-proxy.app.cloud.gov/data/committee/C00431445/?cycle=2012

**Comment by jontours** [comment]
Not here though, they are correct: https://fec-stage-proxy.app.cloud.gov/data/candidate/P80003338/?election_full=True&cycle=2012.

Can't say I'm familiar with that view above, but looks like it is just the cycle of 2012 so _should_ be the same?  I don't know though, something is up I guess.

**Comment by noahmanger** [comment]
That view is just for a single committee just for the 2011-2012 period.

**Comment by jontours** [comment]
Ah ok, different logic but the fix should be the same.

**Comment by jenniferthibault** [comment]
Looks like the fix is in progress, but just in case there's any more details in it, this issue was reported again on Friday: https://github.com/18F/FEC/issues/4216

**Comment by noahmanger** [comment]
Resolved by #2472
