### ISSUE TITLE
Update AOs and MURs should be flagged in the Postgres DB so that we can do incremental indexing

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2460]
The automated process to refresh AOs looks at a timestamp column named `pg_date` to identify those AOs that have been modified in the last 24 hours. We have now learned that although modified AOs are unpublished and republished, the `pg_date` column may not be modified - this happens when the update happens through SQL UPDATE statements instead of SQL INSERT statements.

Tagging @noahmanger and @jwchumley.

**Comment by patphongs** [comment]
After discussing with @rjayasekera, it appears that pg_date may not be the best to identify modified AOs and MURs. This is particularly because that date will not change on republished/updated AOs.

**Comment by vrajmohan** [comment]
Is there an alternate strategy for identifying modified AOs and MURS? This was our last discussion on June 8:

> Pat Phongsvirajati [3:15 PM] 
thank you both! So does this mean that @rohan needs to update the pg_date every time a new document gets added to an AO?

> Rohan Jayasekera [3:15 PM] 
> we can write a trigger against AO table then is any record in it get updated I can set PG_DATE to be the current system date;
> 
> Vraj Mohan [3:15 PM] 
> That works.
> 
> Pat Phongsvirajati [3:15 PM] 
> makes sense, answers my question, thanks @rohan !
> 
> Vraj Mohan [3:15 PM] 
> We should also employ a similar strategy for MURs.

**Comment by patphongs** [comment]
We will have to get back about the solution for this. We need to find out what happens during data entry, how to update of records, and how to identify them.

**Comment by PaulClark2** [comment]
#2511
