### ISSUE TITLE
Add correct state_full label for aggregates from non-state states

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2465]
As reported in https://github.com/18F/FEC/issues/4209, occasionally aggregates are shown for states of invalid values like "AP" or blank values. [See here for an example](https://www.fec.gov/data/committee/C00578658/?tab=receipts&cycle=2016).

As @llienfec noted, this seems to be how they were reported, but we should probably not include aggregates for them, or if we do maybe we should aggregate them all under "State unknown"?

---

Update from the discussion below. It seems that what we really need to do is a few things to the `/schedule_a/by_state/` endpoint:

- [ ] Combine all "AE", "AP", and "AA" values under a single value labeled "Armed forces overseas"
- [ ] Label "ZZ" as "Overseas"
- [ ] Combine all other values that do not match a known entity ("ON", "BC", etc.) as a single group labeled "State unknown"

**Comment by PaulClark2** [comment]
There are 57 valid state abbreviations and one code used as a data convention. 

The 50 states, of course. 

DC, AS, PR and MP are valid states. 

AE, AP, or AA are military "state abbreviations." AE is used for armed forces in Europe, the Middle East, Africa, and Canada; AP is for the Pacific; and AA is the Americas excluding Canada.

"ZZ" is an FEC data convention that means "foreign." 

If the same state code, or abbreviation, is not one of the 57 valid states, we should aggregate them as "state unknown."  ZZ should be included in unknown.

**Comment by noahmanger** [comment]
Ah thanks. So then for the valid ones, we'll want to include them in the mapping we do to get the long names. Would it make sense to group all the armed forces together as `Armed forces overseas`? And can we map `ZZ` to `Foreign`?

**Comment by llienfec** [comment]
Interested to see what @PaulClark2 thinks.  I'm not 100% sure about using "foreign."  Maybe "overseas" is more accurate?  The locations are foreign but the contributors are usually Americans living abroad.  I'm worried that the public may conflate "foreign" with illegal foreign contributions.

**Comment by noahmanger** [comment]
Oh oh. That makes more sense.

**Comment by PaulClark2** [comment]
Using "overseas" makes sense to me.

My understanding was we landed on "foreign" to mean non-US postal addresses. However, "overseas" probably makes for sense especially considering the sensitivity nowadays to foreign contributions and influence.

Grouping the armed forces "states" together makes sense to me.

**Comment by noahmanger** [comment]
I've updated the original issue with more details about what needs to happen.
