### ISSUE TITLE
Create onboarding checklists

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2474]
To better socialize our policies, we should make on-boarding and off-boarding checklists. We think this will be easier for newcomers and make the policies more clear. (Moved over from https://github.com/18F/fec-accounts/issues/23)

**Comment by LindsayYoung** [comment]
Got that started here
https://docs.google.com/document/d/18ZjPvNrdW3wn9pUx7hSNbaMlaEaPPOGzOHh-WjLiVOg/edit#

**Comment by AmyKort** [comment]
This looks great! Are we ready to close this issue, with the understanding that we'll need to keep up our on-boarding document as our processes grow and change?

**Comment by LindsayYoung** [comment]
Yes! thanks Amy
