### ISSUE TITLE
Investigate negative page numbers

### ISSUE THREAD

**Issue by jontours** [18F/openFEC#2475]
Most likely is in the source data table but need to verify and find a solution.

**Comment by jontours** [comment]
related https://github.com/18F/FEC/issues/4232

**Comment by noahmanger** [comment]
I actually think this is a front-end issue, though there may be a back-end way to resolve it. To show the number of pages, we subtract the beginning number from the end number, but because the ints are so big, [we slice after 8 digits](https://github.com/18F/openFEC-web-app/blob/develop/static/js/modules/columns.js#L76). Apparently that's the wrong limit to slice at, which is resulting in the negative numbers. 

If it's easy enough to just do this math on the API side, that'd be nice, but otherwise we should just figure out a better way to do the math.

**Comment by noahmanger** [comment]
I think I have some insight in this. It looks like pre-2015, image numbers were shorter, only 11 digits: `15970170288`. But in 2015 they changed to a longer 18-digit format: `201601110300037958`. I think we can solve this on the front-end by checking the length of the image number, but I'm curious if there's any gotchas to be aware of.

**Comment by PaulClark2** [comment]
I should have paid more attention to this s issue.  We switched from 11-digit to 18-digit image numbers in June 2015. Here's an email. Sent to staff and data users about the 
-------
Dear FEC Staff and Data Users,

This e-mail provides information about a change to the image number format that the Commission assigns to all statements and reports filed with the agency including campaign finance statements and reports filed with the Secretary of the Senate.  Historically, the Commission has assigned filings with an 11-digit image number. Beginning June 29, 2015, the Commission will assign new filings with an 18-digit imagine number. 11-digit image numbers will not be converted to 18-digit image numbers.  The new 18-digit image number provides additional page numbers to accommodate increased page volume, includes the scan date in the image number and allows us to eliminate continuation reports.

Regards,
Paul


11-digit Image Number Format

YYOORRRFFFF

YY - scanning year
OO - office (01 - House, 02 - Senate, 03 - FEC Paper, 9x - FEC Electronic)
RRR - reel number
FFFF- frame number

Newer 18-digit Image Number Format

YYYYMMDDSSPPPPPPPP

YYYY - scanning year
MM - scanning month
DD - scanning day
SS - source (02 - Senate, 03 - FEC Paper, 9x - FEC Electronic)
PPPPPPPP - page (reset to zero every year on January 1)


-------

**Comment by noahmanger** [comment]
Awesome. That makes for a really easy fix then!

**Comment by noahmanger** [comment]
Will be resolved by https://github.com/18F/openFEC-web-app/pull/2139

**Comment by PaulClark2** [comment]
18-digit image numbers use the last 8 digits.  11-digit image numbers use the last 4 digits.
