### ISSUE TITLE
Presidential Individual Contribution amount is incorrect

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2477]
The total individual amount here is way off:
https://www.fec.gov/data/candidate/P00003392/?election_full=True&cycle=2016

it should be around 405 million instead of 5.9 million which is the actual amount for refunds of individual contributions. I'm pretty sure thi issue is here:
-- Materialized View: public.ofec_totals_candidate_committees_presidential_mv

This line:
sum(p.indv_ref) AS individual_contributions,
should be this:
sum(p.indv_contb) AS individual_contributions,

@PaulClark2

**Comment by jontours** [comment]
This is fixed with the next release: https://fec-stage-proxy.app.cloud.gov/data/candidate/P00003392/?election_full=True&cycle=2016

**Comment by noahmanger** [comment]
Closing as this has been fixed.
