### ISSUE TITLE
Duplicate transactions

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2481]
It looks like the receipts endpoint is not filtering out older transactions when a report is amended. Here is an example:

https://www.fec.gov/data/receipts/?two_year_transaction_period=2016&data_type=processed&committee_id=C00082925&contributor_name=C00619437&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016

Focus on the four $40,000 transactions.  There should only be two. 

Old Link_id= 4042720171400522346 (Should not be there)
Latest Link_id = 4060220171405965339 (Should be there)

The older transactions are not in f_item and don't appear on Classic.

**Comment by noahmanger** [comment]
This should be resolved by https://github.com/18F/openFEC/pull/2483

Does this look right [on staging](https://fec-stage-proxy.app.cloud.gov/data/receipts/?two_year_transaction_period=2016&data_type=processed&committee_id=C00082925&contributor_name=C00619437&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016)?

![image](https://user-images.githubusercontent.com/1696495/27544727-0508e54a-5a5c-11e7-9038-83a4cb21fa69.png)
