### ISSUE TITLE
Doubling candidate totals on this candidate

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2482]
Just pointing to this from the feedback repository. I've confirmed the issue and also that it doesn't seem to be an issue in the underlying data. Correct on Classic.

https://github.com/18F/FEC/issues/4236

**Comment by noahmanger** [comment]
Thanks Jeff. I already made an issue for this https://github.com/18F/openFEC/issues/2480, but I'll copy your comment over there.
