### ISSUE TITLE
Tune typeahead

### ISSUE THREAD

**Issue by catherinedevlin** [18F/openFEC#249]
Use the tuning framework (#247) against typeahead requests to the REST server:

    https://fec.18f.us/rest/candidate?name=%QUERY&fields=name,candidate_id,office_sought
    https://fec.18f.us/rest/committee?name=%QUERY&fields=name,committee_id

Get response time for both to 25% of initial

**Comment by noahmanger** [comment]
Yay! :clap:

**Comment by catherinedevlin** [comment]
new /name endpoint has muuuuuuuch less than 25% of earlier response time

**Comment by LindsayYoung** [comment]
:clap: :clap:

**Comment by noahmanger** [comment]
Yay! I'll be hooking this up in #260 in the next sprint.
