### ISSUE TITLE
24- and 48-hour Independent Expenditure data filing amendment indicator

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2491]
The 24- and 48-hour Independent Expenditure data does not include the amendment indicator of the filing. This is "form" level data that needs to be included. Data users need this data to help them dedupe these reports/transactions. See the amendment indicator information presented in the Data Catalog version of these data: http://classic.fec.gov/data/IndependentExpenditure.do. 

The download also needs to include file number and previous file number.

**Comment by LindsayYoung** [comment]
All the schedule data is as amended so we don't have explicit indicators for that like we do with filings where we show things that have been amended. 

File number is already included in the API so if that is not showing up in downloads, that should be an easy fix. 

Is `back_ref_tran_id` the previous file number? That is in `fec_fitem_sched_e_vw` if it is in the other views that make up the data we could add that.

**Comment by PaulClark2** [comment]
I don't think transactions of 24- and 48-hour reports of IEs are as-amended. The joins for `fec_f57_notice_vw` and `fec_sched_e_notice_vw` do not take care of new and amended reports.

**Comment by LindsayYoung** [comment]
OK, we will want to add a filter for the as amended filings too.

**Comment by PaulClark2** [comment]
`back_ref_tran_id` is _not_ the previous file number. 

How do we programmatically, reliably determine the correct set of as-amended 24- and 48-hour IE reports and their transactions?
