### ISSUE TITLE
24- and 48-hour Independent Expenditure transactions seem to be missing

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2492]
24- and 48-hour Independent Expenditure transactions seem to be missing from web-app results

Returns no results:
https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00053553&cycle=2018&is_notice=true&candidate_id=H8GA06195&max_date=06%2F16%2F2017

Returns 6 rows:
`select cmte_id, pye_nm, s_o_cand_id, s_o_cand_nm, exp_amt, exp_dt, dissem_dt from public.fec_sched_e_notice_vw where cmte_id = 'C00053553' and (exp_dt between '01-JAN-2017' and '16-JUN-2017' or dissem_dt between '01-JAN-2017' and '16-JUN-2017') and s_o_cand_nm like '%OSSOFF%';`

**Comment by noahmanger** [comment]
Could this be related to https://github.com/18F/FEC/issues/4246 ?

**Comment by PaulClark2** [comment]
Yes. I was just going to send you a message on Slack.

**Comment by jontours** [comment]
As far as these go the root problem is that none of the records in this queue are being written out to the ofec_sched_e table: 

This query,  select count(*) from ofec_nml_24_queue_new where s_o_cand_id = 'H8GA06195'; 

Has 170 rows.  Can investigate why those aren't getting processed.

**Comment by ccostino** [comment]
Hmm, so could be two issues then - making sure that the records in the queues are being processed properly and that they're being added to the queues in the first place (as we've noted, the triggers are currently running against the views, which wouldn't work).

**Comment by jontours** [comment]
Disregard; there is a problem with the queues but it seems to not be related, as the 6 records from up above aren't in the queues.  Which, is weird.

**Comment by ccostino** [comment]
Okay, @jontours and I think we have this worked out via the trigger updates we'll need to make to get the queue processing working correctly again.

**Comment by ccostino** [comment]
@LindsayYoung created a hotfix to rebuild schedule E on a nightly basis while we work on fixing the update mechanisms, especially since we need the `fitem`-based views in staging and production before they can be released.

**Comment by ccostino** [comment]
We've also addressed this with another hotfix in the web app: https://github.com/18F/openFEC-web-app/pull/2140

**Comment by noahmanger** [comment]
Verifying that the API fixes this release seem to fix this. https://api-stage.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY&sort_hide_null=true&data_type=processed&committee_id=C00053553&cycle=2018&is_notice=false&candidate_id=H8GA06195&max_date=06%2F16%2F2017&sort=-expenditure_date&per_page=30

Once we restore the 24/48 toggle they'll show up in the app as well.

**Comment by noahmanger** [comment]
Er, scratch that. Those are the Form 3X transactions, not Form 24.

**Comment by noahmanger** [comment]
Double-scratch that. I had `is_notice=false`. When `is_notice=true` you get 0 results:  https://api-stage.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY&sort_hide_null=true&data_type=processed&committee_id=C00053553&cycle=2018&is_notice=true&candidate_id=H8GA06195&max_date=06%2F16%2F2017&sort=-expenditure_date&per_page=30

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by ccostino** [comment]
I'm not sure...  @PaulClark2 would you be able to verify if we're still seeing an issue with this?

**Comment by PaulClark2** [comment]
I think we are good.  


![image](https://user-images.githubusercontent.com/11817734/32064223-392d4636-ba47-11e7-85b9-1201cbfaf9a7.png)
