### ISSUE TITLE
To help users find leadership PACs, link them to candidates

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#250]
I remember seeing something in the data that made me think this was not a problem but I am not seeing the linkages in the API. I need to make sure they are displaying properly.

(The test case that I generally use is PAC to the Future, Nancy Pelosi's PAC because the name is memorable.)

I will look at this later unless this is pressing for @noahmanger or @theresaanna .

**Comment by LindsayYoung** [comment]
The FEC has the info as displayed -http://www.fec.gov/data/Leadership.do but most leadership pacs don't seem to be linked via the `/dimlinkages` table. I was using PAC to the Future as the example. which shows up as linked to Pelosi on the FEC website but not that table.

**Comment by LindsayYoung** [comment]
The underlying form on this is terrible, I would still like to do it, but it would be more work. :/

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/z29nqCY-zmuCVznUEFZhfg

**Comment by LindsayYoung** [comment]
Talked to Paul and Jeff and they are going to investigate adding this to the F1 intake process so that leadership PACs are connected to candidates in the candidate committee linkage table. That would be ideal.

**Comment by LindsayYoung** [comment]
Got comment from public in support of this

https://github.com/18F/FEC/issues/239
