### ISSUE TITLE
Doubled numbers in candidate totals endpoint

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2505]
This is an issue that we had some time ago and appears to be back. It looks like any candidate that has an off-year election and then files for the next regular elections is being doubled.

Example - Greg Gianforte, in Montana:
https://www.fec.gov/data/candidate/H8MT01182/?cycle=2018&election_full=False
Total receipts should be 4880918.47 NOT 9761836.94

The problem is here:
SELECT link.cand_id AS candidate_id,
            max(election.cand_election_year) AS election_year,
            totals.cycle,
            false AS is_election,
            sum(totals.receipts) AS receipts,
            sum(totals.disbursements) AS disbursements,
            sum(totals.receipts) > 0::numeric AS has_raised_funds,
            sum(totals.last_cash_on_hand_end_period) AS cash_on_hand_end_period,
            sum(totals.last_debts_owed_by_committee) AS debts_owed_by_committee,
            min(totals.coverage_start_date) AS coverage_start_date,
            max(totals.coverage_end_date) AS coverage_end_date,
            array_agg(totals.federal_funds_flag) @> ARRAY[true] AS federal_funds_flag
           FROM **ofec_cand_cmte_linkage_mv l**ink
             JOIN totals ON link.cmte_id::text = totals.committee_id::text AND link.fec_election_yr = totals.cycle::numeric
             LEFT JOIN ofec_candidate_election_mv election ON link.cand_id::text = election.candidate_id::text AND totals.cycle <= election.cand_election_year AND totals.cycle > election.prev_election_year
          WHERE link.cmte_dsgn::text = ANY (ARRAY['P'::character varying, 'A'::character varying]::text[])
          GROUP BY link.cand_id, totals.cycle

Candidates that run in off years often end up with two rows with the same fec_election_yr one (for example) where the cand_election_yr=2017 and one where it =2018 (after they file for the next election)
Like this:
select * from   ofec_cand_cmte_linkage_mv
where cand_id='H8MT01182';

So it's doubling the totals.

**Comment by jontours** [comment]
Thanks Jeff this is resolved with the next release: https://fec-stage-proxy.app.cloud.gov/data/candidate/H8MT01182/?cycle=2018&election_full=False

**Comment by jwchumley** [comment]
Great Jon! I was pretty sure the work had been done but I thought it was already released.

**Comment by jontours** [comment]
Ha, I did too actually, it was early in the Sprint.

**Comment by noahmanger** [comment]
Closing this since the work has been resolved.
