### ISSUE TITLE
Salient to insert directly from raging wire AO and MUR tables to PG

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2511]
This will automatically cut out a half hour from the time it takes between Jason publishing and the new or changed information to show up on the new website. Right now there is latency built into the export from raging wire to FECP and then from FECP to PG and then PG has to run the elastic search update process.

In order to get this moved along I think we will need to lay it out for Srini and probably have Wei prioritize it.

Completion criteria: Anything published or unpublished should bypass FECP and insert directly from Raging Wire tables to PG tables.

- [x] Salient development work to begin 8/7
- [x] UAT to begin 8/28
- [x] final testing with OGC and Public Records to being 10/5

**Comment by PaulClark2** [comment]
This moved to production 10/20 or 10/21.
