### ISSUE TITLE
Salient update the datestamp in the AO/MUR main table when any child table is updated

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2512]
When Jason makes an edit that doesn't impact the parent table in AO or MUR it doesn't update the date stamp in the parent table so the Elastic search indexer doesn't start. This issue is just a reminder that Wei may need to help Salient Prioritize.

Completion Criteria: All child table activity updates parent table time stamp.

- [x] final testing with OGC and Public Records to being 10/5

**Comment by AmyKort** [comment]
this appears to be complete
