### ISSUE TITLE
Export Audit system data to Postgres

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2515]
Set up an export workflow in GG to get data loaded into Postgres and allow for display of the data publicly

**Comment by rjayasekera** [comment]
Audit Search tables and views created on FR_DEV, FR_STG, and FR_PRD GovCloud instances and initial data load is done.

**Comment by noahmanger** [comment]
Thanks @rjayasekera ! Sounds like we can close this then?

**Comment by PaulClark2** [comment]
@rjayasekera the initial load is complete. We also need to set-up a refresh (daily or triggered by new audit publication), right? Do you want to do that work on this issue, or close this issue and make a new issue for the refresh?

**Comment by jwchumley** [comment]
Lets make that a separate issue to make it easier to see what's been done. Rohan, would you create it in the openFEC repo?


________________________________

**Comment by noahmanger** [comment]
This is done. Next steps in here https://github.com/18F/openFEC/issues/2542
