### ISSUE TITLE
To make sure the API is usable, make sure it's up to standards

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#252]
I think we are fine with most of it but there are a few tweaks we should make.

https://github.com/18F/api-standards

**Comment by LindsayYoung** [comment]
This resulted in issues #265 #266 #267

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/iP_VyxlBWXBzijnUEFZhfg
