### ISSUE TITLE
Remove QuantifiedCode badge

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2522]
[QuantifiedCode is shutting down on July 22nd](https://www.quantifiedcode.com/blog/quantifiedcode-shutdown) so we should remove the Badge from the README.md. Fortuitously, @LindsayYoung and I were also having a conversation with @cmc333333 around a variety of things including automated linting and style guide checks (e.g., HoundCI, which we do have setup for JS in the other repos).

@PaulClark2:  A follow-up issue (#2517) can be slotted in a later sprint when it makes sense to spend more time researching an alternative.  It's something we'll want to look at, but it's not critical!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2523
