### ISSUE TITLE
Add html_url value for /efile/filings/ and fix missing html_url for /filings

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2533]
We've received a few comments recently about people looking for the links to the web-based view of filings. While we have a place to include these in the main filings tables, the `html_url` is currently `null` for many filings, though not all. (e.g. https://api.open.fec.gov/v1/efile/filings/?api_key=DEMO_KEY&form_type=F3). Also, it's completely absent from the `/efile/filings/` endpoint. 

(Note: It seems to work fine on the `/reports/` endpoints, which is why it shows up in the details panels. Those are populated by additional calls to that endpoint, whereas the table itself is just the filings endpoint).

**Completion criteria:**
- [ ] Fix missing `html_url` values on `/filings/`
- [ ] Add `html_url` property on `/efile/filings/`

**Comment by ccostino** [comment]
@noahmanger:  In the case of the `html_url` property being `null` for some filings, is that because they're not being pulled in properly or is it just a straight up data issue and the data is not there?

Also, just to make sure we're understanding this correctly, this property is exposed on the `/filings/` endpoint but not at all on the efiling version (`/efile/filings/`), correct?

**Comment by PaulClark2** [comment]
_electronic filings_ 
http://docquery.fec.gov/cgi-bin/forms/COMMITTEE_ID/REPORT_ID
example
http://docquery.fec.gov/cgi-bin/forms/C00213512/1157174/

_paper filings (only when the report id / file number is positive)_
http://docquery.fec.gov/cgi-bin/paper_forms/COMMITTEE_ID/REPORT_ID
example
http://docquery.fec.gov/cgi-bin/paper_forms/C00148999/1142242/

**Comment by jontours** [comment]
Thanks @PaulClark2.  So for the `filings` endpoint, it looks like the case statement at https://github.com/18F/openFEC/blob/develop/data/sql_updates/filings.sql#L77, can just be made a regular statement.  I think what happened there was I first added it as a case to be sensitive to paper filings, then decided that some paper filings should be captured (with file_num > 0) and forgot to remove the case statement.  So the function itself is resilient to bugs.  Sorry!!

And for efilings, the function call just needs to added probably, haven't checked but that's my guess.

**Comment by jontours** [comment]
Ditto for this block too https://github.com/18F/openFEC/blob/develop/data/sql_updates/filings.sql#L150

**Comment by ccostino** [comment]
@jontours thanks!  Do you mean to just remove the `CASE` statements and call `report_html_url` directly instead?

**Comment by ccostino** [comment]
Okay yes, I see what you mean in the `report` SQL it just calls the method directly and the method already accounts for these things.  Nice!
