### ISSUE TITLE
Election dates endpoint fixes

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2544]
While checking the election dates work from https://github.com/18F/openFEC/pull/2485 , I noticed a couple things:
- [ ] Duplicative results when filtering for GA: https://fec-dev-api.app.cloud.gov/v1/elections/search/?api_key=&cycle=2018&state=GA
- [ ] States without senate elections in 2018 (e.g. Oregon, Colorado) show up as having a senate election. This is not a problem on production.

Additionally, would be good to have someone from Info perhaps look through.

**Comment by LindsayYoung** [comment]
Thank you!

**Comment by noahmanger** [comment]
Closing in favor of a consolidated issue in https://github.com/18F/openFEC/issues/2590
