### ISSUE TITLE
Revisit downloads code for improvement

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2549]
The recent work in improving and upgrading our Celery infrastructure has yielded an opportunity for code improvement that should be looked at in the future.

With the move to Celery 4.0.2, the default serialization changed from using Python's `pickle` module to using `JSON`.  This necessitated a change in the way a parameter was passed to the download task ([see here](https://github.com/18F/openFEC/pull/2543/files#diff-f47cfb25cbf1d6d6506049b3f1d5533fR130)), which involved using `base64` encoding and decoding (thus requiring `UTF-8` encoding and decoding as well).

We'd like to improve this and remove the need to pass along data to a task that can't normally be serialized as JSON, but it will require a bit of extra work as there is quite a bit of processing going on with the download resource and task.

**Comment by noahmanger** [comment]
Is this still relevant after the work we've already done?

**Comment by ccostino** [comment]
It is, but I'm questioning whether it's worth doing or not.  @LindsayYoung, if you don't see value in pursuing this then I'm totally fine with just closing the issue.

**Comment by LindsayYoung** [comment]
Let's close it. It would be nice if we had less other things going on,
