### ISSUE TITLE
Improve RDS logging

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2564]
Let's get cloudwatch going so the sql logs are less of a PIA

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html

**Comment by LindsayYoung** [comment]
Notes:
Regions and endpoints
http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html
cloud watch:
monitoring.us-gov-west-1.amazonaws.com
cloud watch events: 
events.us-gov-west-1.amazonaws.com
cloud tail:
cloudtrail.us-gov-west-1.amazonaws.com

**Comment by LindsayYoung** [comment]
https://github.com/18F/fec-infrastructure/pull/23

**Comment by ccostino** [comment]
@LindsayYoung is there anything left to do or are we ready for a code review with Josh again?

**Comment by ccostino** [comment]
We're in the process of finalizing the role and policy setup for this and as soon as we have it figured out we should be on our way!

**Comment by ccostino** [comment]
We're currently stuck in this with some form of invalid configuration with Terraform.  The details are being tracked in https://github.com/18F/fec-infrastructure/issues/35

**Comment by ccostino** [comment]
@LindsayYoung and I just finished this up this morning!

**Comment by LindsayYoung** [comment]
Logs
![giphy-downsized 3](https://user-images.githubusercontent.com/4406333/29842353-9882a6b0-8cd6-11e7-891a-a527e5fbf350.gif)

**Comment by PaulClark2** [comment]
love the Shawshank Redemption image
