### ISSUE TITLE
follow up on API limits

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2569]
It seems like the keys are not defaulting to 120 requests per minute like they should. we should follow up on this with the api.data.gov team

**Comment by qntnrbns** [comment]
It seems that the rate limits are being set at 1000 per hour instead of 120 per minute.

Also, would it be possible to display the time when the limit will reset in the headers?

**Comment by LindsayYoung** [comment]
We can adjust your key if you email 18f-fec@gsa.gov with the email you used to sign up for your key.

Here are the docs on rate limiting https://api.data.gov/docs/rate-limits/

Thanks for writing in!

**Comment by qntnrbns** [comment]
@LindsayYoung, thanks so much for the rate limit docs!

I emailed about a week go and haven't heard back yet. I made the mistake of emailing on labor day and want to make sure I didn't get lost in the queue.

**Comment by LindsayYoung** [comment]
done
