### ISSUE TITLE
Random bug: Last_index pagination sometimes doesn't work for certain committees

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2582]
In testing [the fix](https://github.com/18F/openFEC-web-app/pull/2241) for committee page pagination I uncovered a weird bug. While the fix there fixes it in many cases, there's others that still don't work. For example on on the individual contributions table on [this page](http://localhost:3000/committee/C00575795/?tab=spending) you can't page past the second page. 

The same is true if you look at the disbursements main page, filtered down to that committee: http://localhost:3000/disbursements/?two_year_transaction_period=2018&data_type=processed&committee_id=C00575795&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018

This is true for other committees as well, but I can't find a pattern. It seems that there's an issue with the `last_index` value being accurate, but I'm not sure. 

cc @jontours

**Comment by jontours** [comment]
Looking into it.

**Comment by jontours** [comment]
Arghhhhh!  This is the issue with `last_index` losing precision, I verified it just playing around in the browser.  Let me see if I can fix this without resorting to just casting `last_index` to a string.

**Comment by jontours** [comment]
To elaborate on how this bug pops up, if you look at the last sub_id when requesting 10 rows for Hillary for America, the `sub_id` for the last entry in the JSON is `4071820171419809123`.  But in the json for `pagination` we have:
```
last_indexes: {
  last_index: 4071820171419809300,
  last_disbursement_date: "2017-06-30T00:00:00"
}
```
That last_index is clearly wrong, this little piece of JSON is being generated by the Marshallow paginator, which we are extending, I'll see if there is a way to hack around it and prevent the loss of precision.

**Comment by jontours** [comment]
@noahmanger actually I'm not sure that it is the issue, but out of curiosity, for the pagination that isn't working, what is the `last_index` value on the web-app that you are using for the next request?

**Comment by noahmanger** [comment]
Ah gotcha. Here's one: `4021720171371815400`. Every time I've checked it's always ended in two or three zeros.

**Comment by jontours** [comment]
Okay, I'm still a bit confused.  Reason being is that in the JSON payload there actually isn't a precision problem.  Here is a snippet of the JSON taken from the PAC in question up above: 
```
{"last_disbursement_date":"2017-06-30T00:00:00","last_index":4071820171419809123}
```

The browser displays the rounding error, but you are saying you see the rounding error too?  Is that from the web-app?  It might be the library we are using to parse the json if that's the case.

**Comment by jontours** [comment]
I've been debugging this and believe it's how the JSON is parsed on the front-end.  I'll keep you posted.

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by jontours** [comment]
Yes this is no longer an issue.

**Comment by AmyKort** [comment]
Thanks!
