### ISSUE TITLE
Nightly refresh process failing/not working correctly in the dev environment

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2585]
We have been having some issues with the nightly processing in our development environment:

* Status emails haven't been going out
* Queries are getting locked up in the database
* The nightly refresh job has hung up and doesn't fully complete
* Celery sometimes doesn't get shut down gracefully and throws a small stack trace
* The nightly retry processing for schedule A and B data is still causing issues

I've been doing a lot of digging around this morning into the issues we've been having with the `dev` database and I'm reaching a couple of conclusions:  the extra nightly retry processing I had tried to put in place to catch records that we couldn't initially process with the schedule A and B queues appears to be causing far more problems than it is helping anything, and what happens if our nightly refresh ends up in a state where it's still running at the point it gets triggered again the next day (this should never be the case, it takes 1 - 2 hours at most to run on average).

Some extra context into things:

We started noticing these issues around July 29th.  I'm still not sure what ultimately started causing the deadlocks and row contention with the aggregate processing, but that's when the errors start getting reported (looking into the cloud.gov logs of the `dev` `celery-worker` app).  These ultimately culminate in the emails never getting sent out and a Mandrill (the email processing app we use) max retry error to be thrown, hence the lack of emails being sent out for `dev` from the nightly update bot we have setup.

Another thing to note:  even with the nightly processing itself shut off (we had done this as a hotfix recently), the triggers are still active, and I'm seeing errors in the RDS logs with duplicate keys trying to be inserted (even though we have code to remove existing records with matching keys first before inserting!).  Potentially due to these,  I've noticed some EOF and connection timeout errors too in the Celery worker logs.

Updating Celery in `dev` in prep for our next release seems like a good idea as there are a host of bug fixes in it, and I have caught several times when it throws a small stack trace when it shuts down, which may leave jobs in an unstable state.  `staging` and `prod` seem to be okay and have been updating fine each night, but they're still running on the 3.x series of Celery.

We also had the Redis connectivity issue early this week too, compounding a bit of this but not a direct cause (the initial errors happened a few days before).

Back to the problem at hand:

The main problem is the aggregate updates, those have gotten hung up in dev due to deadlocked processes when they attempt to run (and generally get stuck on the very first step, updating zip codes for schedule A).

Because the processes get locked, the main nightly refresh task doesn't quite "finish" despite having thrown some success messages - the underlying update aggregate queries are still active and locked in the DB.

For some reason despite reporting itself as having finished, the refresh task/job is still in a pending state of sorts so no email is sent out and eventually causes the email code to throw an error of max retries being hit.

As soon as I kill these processes/locked queries in the DB that should free things up and finally finish the tasks.  This was the case the last time we ran into this, and shutting off the nightly retry processing alleviated the issue in `staging` and `prod`.  It appears something is still not quite right with `dev`, and the Celery version is the main difference in that respect.  The recent update might help alleviate some issues.

Next steps:

* [x] Submit a PR to update Celery in `dev`
* [x] Submit a PR to rip out all remaining nightly retry processing - it has caused more problems than it is has helped solve
* [ ] Begin work on next phase of schedule A and B refactoring to focus on keep track of record updates and improving/removing the original queue processing (will work with @vrajmohan on this - tracked by #2423)
* [ ] Potentially add support to detect an already running nightly refresh job and kill it before starting a new one, despite this being a situation that should not happen (thanks, @jontours, for talking through this)

**Comment by ccostino** [comment]
After removing all of the deadlocked `select update_aggregate()` queries all of the backed up jobs and emails seemed to have finished and the GoldenGate transfer were able to be resumed successfully.  I have PRs in place to upgrade Celery (already merged) and to remove the nightly retry processing (ready for review), once the latest GoldenGate transfers are done in `dev` I can make sure those changes are in place and restart the `update_all` process in `dev`.

**Comment by ccostino** [comment]
Both PRs have now been merged to address the immediate issues and I've run `update_functions` and `update_itemized` for schedule A and B in `dev`.  I will wait to see what the nightly refresh does tomorrow and run `update_all` then if things look better.

**Comment by ccostino** [comment]
The `update_all` process is currently running in the `dev` environment and we're just waiting for it to finish.  It does seem to be taking a long time so we're keeping an eye on it and may have to make some other adjustments.

The nightly refreshes have been successful over the weekend, though.

**Comment by ccostino** [comment]
The `update_all` task ended up restarting itself while repartitioning schedule B, and then failed with a deadlock error when it reached preparing schedule A (setting up the triggers and queue tables).  We'll investigate to see what's been going on to get it restarted and hopefully successful this time.

**Comment by LindsayYoung** [comment]
last night the updates on dev only ran once after removing the acknowledge late was set to false

**Comment by ccostino** [comment]
Ah, we still need a successful `update_all` to run in `dev` though, that hasn't happened yet since the last round of changes.

**Comment by ccostino** [comment]
We're in the process of running `update_all` in `dev` and `stage` right now.  As soon as these complete, we'll close this issue.

**Comment by ccostino** [comment]
We're going to close this issue in favor of opening a new one specific to the `update_all` issue(s) we're working on.
