### ISSUE TITLE
Error messages include stray comma

### ISSUE THREAD

**Issue by rshorey** [18F/openFEC#2591]
Hi, the `OVER_RATE_LIMIT` error message reads `OVER_RATE_LIMIT,`

I understand that fixing it would be a breaking change for some, but it costs me like 10 minutes of debugging time every time I write any code that hits the api a lot, so might be a nice add-on fix if you ever do an API release with any other breaking changes?

Thanks!

**Comment by LindsayYoung** [comment]
The error messages are in html but I can see why the commas would through off your code. I removed the commas, I don't think that should be too impactful, but it does depend on how people are writing their code. If this doesn't message still gives you trouble, you might want to check the status code before parsing, if it is 429 that means you hit the API limit. 

new message:

<html>
<body>
<h1>OVER_RATE_LIMIT</h1>
<p>You have exceeded your rate limit of 1000 calls an hour for the DEMO_KEY or 120 calls per minute for a personal key. Try again later or contact us at <a href="https://github.com/18F&/openFEC/issues">https://github.com/18F&/openFEC/issues</a> for assistance</p>
</body>
</html>

**Comment by noahmanger** [comment]
Did you make a PR for this yet?

**Comment by LindsayYoung** [comment]
No PR needed, this is a api.data.gov console fix. I left it open to make sure there wasn't any additional issues with it but I will close it now and feel free to reach out again @rshorey if you need anything.
