### ISSUE TITLE
Figure out how to switch schedules A and B to use FEC managed tables Data / API

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2592]
1 - Switch to using data from the FECP tables.

*Push to future sprint. Long term initiative.

**Comment by ccostino** [comment]
I think we should be ready to tackle this after sprint 3.4; we're still wrapping up work now regarding the nightly processing as the last major part of the refactoring we started on, and the index adjustments we might still need to make this coming sprint based on testing will likely yield valuable information too.
