### ISSUE TITLE
Switch New Relic alert emails to the fec joint email

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2597]
This is needed in synthetics and we should set up the new [alerts view](https://alerts.newrelic.com/accounts/956561/incidents/open/page/0) for the APM monitoring

This is needed across apps.

**Comment by noahmanger** [comment]
This is done.

**Comment by LindsayYoung** [comment]
for all the synthetics too?

**Comment by noahmanger** [comment]
Oh I don't know. I thought you set it up.

**Comment by LindsayYoung** [comment]
I checked and it looks good :+!:
