### ISSUE TITLE
migrate to circle CI

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2598]
We should make the move by Sept 12.

**Comment by ccostino** [comment]
We're still working through this but making some progress.  During my research I came across one thing I think we'll definitely want to come back to:  [Workflows](https://circleci.com/docs/2.0/workflows/)

**Comment by hollyallen** [comment]
FYI: This repository has been using Travis CI, however access to Travis CI is now turning off.

**Comment by ccostino** [comment]
Thanks, @hollyallen!  We've moved this repo over and should be okay here now aside from the change propagating over to production (pending our next release); once that's done we'll be marking this done!
