### ISSUE TITLE
Refactor typeahead to use new API

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#260]

**Comment by rjmajma** [comment]
Dependency here seems to be typeahead being completed. Doesn't look like this will fall into being completed this sprint. We should consider adding it to the next.

**Comment by noahmanger** [comment]
This got added mid-sprint after it we decided to create a new endpoint, mid-sprint. Probably shoulda put it in next sprint from the get-go, but yeah, it'll happen next.

**Comment by noahmanger** [comment]
Ready to go here: https://github.com/18F/openFEC-web-app/pull/20

**Comment by noahmanger** [comment]
Donezo.
