### ISSUE TITLE
Test out new elasticsearch capabilities

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2600]
Making a issue for this so we can save some time for these cloud.gov infrastructure improvements. 

- [ ] set up
- [ ] make sure data is loaded on new instances

**Comment by cnelson** [comment]
👋 Is there anything y'all need from cloud.gov on this at this point?  It seems like the first step here is for you to provision an instance of the `3x-ha` plan we made available and run your test suite against it.

Once we have those results, we can review together and discuss changes to the plan sizing / configuration to meet your requirements.

Does that sound right?  If so, when could we expect to see some test results?

**Comment by mogul** [comment]
@vrajmohan have you had any time to work on this yet? We're kind of stuck until we have some test results from you.

**Comment by vrajmohan** [comment]
It is scheduled for the current sprint but I haven't had time to work on it due to having to fight some fires. The good(bad?) news is that ES crapped out in `prod` this morning, making it imperative that we move to an HA service.

**Comment by mogul** [comment]
OK, just waiting to know that it's sized appropriately for this project before we expose it to the world and you can switch to it... Let us know!

**Comment by LindsayYoung** [comment]
The current cluster is 1.4gb and we don't anticipate fast growth. Thanks @mogul!

**Comment by mogul** [comment]
Thanks but we need more info!
* What’s the average document size
* What level of concurrency do you expect to see over what %age of your index

**Comment by LindsayYoung** [comment]
To be honest we have a small set of data with small docs with not very many users (who are all very important to us)
- average doc size 23.7K ( in the cluster stats I see1545505112 bytes / 65053 docs)
- looking at google analytics on busy day this quarter we had 14,000 users on the site as a whole, but for the legal parts of the site 259 page views a day is the quarterly high

**Comment by jmcarp** [comment]
Like @cnelson said at the top of the thread, the next step is for the fec team to run tests against the new instance to see whether performance is adequate. I took a look at the [load test](https://github.com/18F/openFEC/blob/develop/locustfile.py), but without knowing the performance of the single-instance elastic plan, I'm not sure what kind of results would be acceptable.

I also noticed that the load test of the legal search endpoint returns large documents--for example, `/v1/legal/search?q=obama` returns ~850kb of json and takes >5s from my machine. Is that a realistic use of that endpoint? If that result is generating a page like https://www.fec.gov/data/legal/search/?search_type=all&search=obama, I'm guessing you could return a (much) smaller payload.

Also, no problem if there isn't time to run tests soon--if not, we can release the new elastic plan as-is, and if you all turn out to need more resources, we'll set up a bigger plan as needed. Let us know when/whether you'll have capacity to look at this.

**Comment by LindsayYoung** [comment]
Thanks @jmcarp. What was happening before is if there were 5 concurrent requests on the legal search, elasticsearch failed. So if it isn't failing, that is progress!

@vrajmohan was running point on this and is consumed by non-fec things this week. I love the idea of moving forward and adjusting in the future as necessary!

**Comment by vrajmohan** [comment]
I was able to pick this up again. The load test performed no worse than the non-HA version. However, it did not perform all that better either. Given that the objective here is high availability and we have been hit by Elasticsearch crashes before, I think it should be OK to go ahead with the HA service. I'll tabulate my results here.

**Comment by mogul** [comment]
Great to hear it, thanks!

**Comment by vrajmohan** [comment]
Failure of Elasticsearch in `prod` yesterday (September 13, 2017) had us move to the HA plan in a hurry. I'll be moving `stage` to HA today.

**Comment by vrajmohan** [comment]
`stage` configured to use HA plan as well.
