### ISSUE TITLE
add re-indexing test

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2617]
We need to get this out the door for release, but even a simple integration test would be helpful

- [ ] for the reindexing SQL on itemized OFEC tables

**Comment by ccostino** [comment]
@vrajmohan do we still need this and if so, is there a way to get this in relatively soon?  Moving to sprint 4.1 of our next PI in the meantime.

**Comment by LindsayYoung** [comment]
I would be in favor of closing now (Also feel free to reopen this if you don't agree)

**Comment by vrajmohan** [comment]
Agree with @LindsayYoung: with the work being done on automated schema migration, this should be a non-issue.
