### ISSUE TITLE
wrong candidate in search return for state/district house candidate list.

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2618]
https://www.fec.gov/data/elections/house/CA/01/2018/

Montes shouldn't be there. He last ran in 2016 but his committee has filed in 2017. I'm wondering if the filter is using candidate election year OR "form 3 filed in" instead of AND.

**Comment by jontours** [comment]
The release resolved this (there are many, many bugs like this on production currently): https://fec-stage-proxy.app.cloud.gov/data/elections/house/CA/01/2018/
