### ISSUE TITLE
Implement hiding extra related entities in code

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#263]
(Don't be confused...this was entered by Noah, just on Micah's computer).

**Comment by noahmanger** [comment]
Here's the mockups for how it should work:
![view more](https://cloud.githubusercontent.com/assets/1696495/5905926/a18f0d16-a548-11e4-9179-92e103ca4aba.png)
![expanded](https://cloud.githubusercontent.com/assets/1696495/5905929/a5b1e918-a548-11e4-9469-d91a27050b2f.png)

And if there's no related entities:
![no committees](https://cloud.githubusercontent.com/assets/1696495/5905922/99dbf58e-a548-11e4-9703-035289fdb552.png)

**Comment by noahmanger** [comment]
@theresaanna do you have a vision for how you want to organize jquery things like this?

**Comment by noahmanger** [comment]
Ok, to capture the conversation I just had with @LindsayYoung : 

- We actually shouldn't be showing Leadership PACs or Joint Fundraising Committees in the header -- this space should be reserved just for principal and authorized committees (but these committees will still be present on the page, under a heading differentiating them from the P & A committees)
- The Joint Committees are really the only ones for which a candidate might have a bunch of related records, so this situation of needing to account for a big overflow is an edge case we don't need to worry about right now.

Unless anyone objects, I say we don't worry about this at the moment and either close the issue or move to the backlog.

**Comment by rjmajma** [comment]
Moving to the backlog, per Noah's comments above.

**Comment by jmcarp** [comment]
Can this be closed @noahmanger? I think the candidate pages have changed enough so that this doesn't apply.

**Comment by noahmanger** [comment]
Yep

On Mon, Aug 31, 2015 at 2:33 PM, Joshua Carp <notifications@github.com>
wrote:

> Can this be closed @noahmanger <https://github.com/noahmanger>? I think
> the candidate pages have changed enough so that this doesn't apply.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/263#issuecomment-136507807>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
