### ISSUE TITLE
Add additional fields and filters to /totals/{committee-type} endpoint

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#2631]
@noahmanger commented on [Tue Aug 29 2017](https://github.com/18F/openFEC-web-app/issues/2282)

In order to allow users to view a data table of committees' totals, we need to add the following fields to the `/totals/{committee-type}/` endpoint:

- Add these fields to the API response:
- [ ] `committee_name` - Show the committee's name
- [ ] `committee_type_full` - Show the full label of the committee's type
- [ ] `committee_designation_full` - Show the full label of the committee's designation
- [ ] `party_full` - Show the full label of the committee's political party if applicable

- Add filters for:
- [ ] `committee_id` - Allow filtering by `committee_id`
- [ ] `designation` - Allow filtering by one-letter designation code
- [ ] `type` - Allow filtering of committee type by one-letter type code

This is a dependency for https://github.com/18F/openFEC-web-app/issues/2274

Does this make sense @pkfec ? Anything anyone else wants to add?

**Comment by pkfec** [comment]
@PaulClark2 
Can you have some update the materialized view and add indexes for the above fields?

**Comment by pkfec** [comment]
The following four columns are derived from to totals_combined.sql
•  cmte_nm,  
• cmte_tp,
• cmte_dsgn,
• cmte_pty_affiliation_desc

The above 4 columns should be added to the following materalized views: 
• ofec_totals_combined_mv
• ofec_totals_house_senate_mv
• ofec_totals_ie_only_mv
• ofec_totals_pacs_mv
• ofec_totals_pacs_parties_mv
• ofec_totals_parties_mv
• ofec_totals_presidential_mv

@PaulClark2 @rjayasekera @fecjjeng

**Comment by pkfec** [comment]
the above materialized views are updated with the four new columns. 
filters are added to 3 columns. 
changes have been made on the API and unit tested. 
waiting on code review.
@LindsayYoung : Please review PR when you get a chance.

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by fecjjeng** [comment]
Yes

**Comment by AmyKort** [comment]
Thanks!
