### ISSUE TITLE
Document data update changes

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2633]
So that developers understand changes to the data update process especially around SA, SB and aggregates, we should document what we had; what we changed and the new state of the update process. 

@ccostino @vrajmohan @LindsayYoung

**Comment by ccostino** [comment]
We'll want to do this soon so we don't lose context.  I'll move it to sprint 4.1 and see if there's time to at least start it when we do sprint planning.

**Comment by ccostino** [comment]
[Documentation](https://docs.google.com/document/d/1iaxGrO1aaYJUZCRGlI2vx8kdyv_LX6BOr7lX7gIH5kc/edit) is now written up!

**Comment by ccostino** [comment]
I've also asked @LindsayYoung and @vrajmohan for additional feedback on it just in case there's something missed or incorrect.
