### ISSUE TITLE
Switch off Mandril

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2634]
18F is ending our subscription we need to transfer off. Doing slack messages would be easiest and we can hook them into fec slack :)

- [ ] switch to Slack integration
- [x] Check with Jay.
- [ ] research and implement, see reference links below:

Links on how to implement:
https://circleci.com/blog/slack-integration/
https://get.slack.help/hc/en-us/articles/232289568-Use-GitHub-with-Slack

**Comment by LindsayYoung** [comment]
chatting with @JayRibeiro next week

**Comment by patphongs** [comment]
Waiting for security discussion and approval before implementation can begin

**Comment by patphongs** [comment]
This was approved by security and implemented today. There's now a #bots channel in our slack for Circle and Github notifications.

**Comment by LindsayYoung** [comment]
One outstanding task on the API- I hope to have that going today

**Comment by PaulClark2** [comment]
Can we close this?

**Comment by LindsayYoung** [comment]
Just linked the PR. This should be closed when this is merged: https://github.com/18F/openFEC/pull/2703
