### ISSUE TITLE
Handling nulls in columns that are aggregated by

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2639]
Currently, when we aggregate by, say `employer`, and the `employer` column is `null` in the receipts data, each such null is aggregated separately (as `nulls` are never equal to each other). There are 3 possible solutions:
1. Leave the current behavior
2. Ignore `null` values, ie, _leave out_ receipts with `nulls` from the aggregation
3. Aggregate the rows with `null` values in a `null` bucket.

How should we proceed? Tagging @ccostino, @jwchumley, @PaulClark2.

**Comment by LindsayYoung** [comment]
I propose we exclude nulls from these aggregates, the amount of blank lines isn't informative as a subtotal. 

For context, here is the way the data appears on the site
![screen shot 2017-09-06 at 5 08 37 pm](https://user-images.githubusercontent.com/4406333/30135174-da19ae5a-9327-11e7-925c-fc61e8a11ffc.png)

It would be nice to so some grouping of things like self-employed and self employed in the future.

**Comment by ccostino** [comment]
I definitely agree @LindsayYoung about the blank lines, but if we flat out exclude them that could be a rather large amount of money left out of the totals, right?  I'm concerned that we'd be leaving out too much.  Given that, I'm in favor of grouping all of the `NULL` values into a single bucket (or possible combined with other similar values, e.g., an empty string, `N/A`, `NA`, `Not available`, `not reported`, etc.).

Furthermore, this is in line with your suggestion of grouping other things such as `self-employed`, `self employed`, `self`, `individual` (and so on), which I think makes sense as well.

What do you think?  We could pull a distinct list of values in that column to see what we're dealing with and whether or not there's value in spending time creating groupings from that list.
