### ISSUE TITLE
Check logs 09/27/2017

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2643]
https://github.com/18F/FEC/wiki/Security-Event-Review-Checklist

make issues for next month

**Comment by lbeaufort** [comment]
[Done with checklist #1 and #2]

The Django for the cms, should be running the latest patch, so that looks like a false alarm

Eregs has 1.8, only 1.11 and 1.10 have the patch = false alarm

https://www.djangoproject.com/weblog/2017/sep/05/security-releases/

**Comment by lbeaufort** [comment]
Completed checklist with @patphongs and added tickets for October.
