### ISSUE TITLE
Nightly data transfer from Oracle(DC4) to Postgres(AWS) using Golden Gate

### ISSUE THREAD

**Issue by rjayasekera** [18F/openFEC#2653]
Currently we are using Golden Gate to transfer FECP/Oracle data to AWS/Postgress.

When we received over 1 million records, we are unable to transfer them to AWS in a timely manner.
On average it takes about 24 hrs to transfer 1 million records to AWS.  

We need to either improve the current process or find an alternative method or a work around for this.

**Comment by PaulClark2** [comment]
Closing in favor of https://github.com/18F/openFEC/issues/2686
