### ISSUE TITLE
Need warning about sale and use of campaign information on API page

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2657]
Laura thought of this. The api page:
https://api.open.fec.gov/developers/
needs to have a warning about the legal vs illegal uses for contributor data.

**Comment by PaulClark2** [comment]
The warning is at the bottom of this page, https://www.fec.gov/data/advanced/?tab=raising. And, the warning is more fully explained on the transition site, https://transition.fec.gov/pages/brochures/saleuse.shtml.

**Comment by jwchumley** [comment]
@ jonellaculmer  would you like to write a blurb with links to the relevant information?

**Comment by JonellaCulmer** [comment]
Language on the restricted use of the information for commercial purposes is already included on the page. 
It is the second to last sentence:

> A few restrictions limit the way you can use FEC data. For example, you can’t use contributor lists for commercial purposes or to solicit donations. [Learn more here.](https://transition.fec.gov/pages/brochures/saleuse.shtml)

I went ahead and added in additional information if it's determined that what was previously included is not robust enough. You can find the updated language here: https://docs.google.com/document/d/1UYTx2foeO0juKreZnDoUohvbfpRIlPUFuBk6N-N5lIk/edit#

**Comment by jwchumley** [comment]
Thanks Jonella. I shouldn't have been in such a hurry when I checked it. I think it's fine for now. We can revisit later if necessary.
