### ISSUE TITLE
implement since for filing dates and load dates

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#266]
When we get that beautiful data.

**Comment by rjmajma** [comment]
Can you describe the dependency here a bit?

**Comment by LindsayYoung** [comment]
This would depend on us getting real load dates from the data warehouse.

**Comment by LindsayYoung** [comment]
We have better date filtering, but we don't use "since" I am OK closing this

**Comment by noahmanger** [comment]
What did "Since" refer to?

**Comment by LindsayYoung** [comment]
It is from the API standards, we aren't' doing that but we do have date filtering. I think we should just close.
