### ISSUE TITLE
Audit search: category & subcategory, performance, sort parameters & index checks

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2677]
- [x] Display category & subcategory as one row (by materialized view or by using SQL join)
- [x] Performance enhancements for audit search has no dependencies
- [x] Review Sort Parameters for election cycle & final report on the API
- [x] look at what is exposed in resource & the argument used + index checks

@hcaofec

**Comment by AmyKort** [comment]
This portion of the work is complete.

**Comment by PaulClark2** [comment]
Can we close this? Is there another issue (or other issues) tracking work that still needs to be completed?
