### ISSUE TITLE
Terraform and concourse autopilot 

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2680]
Learn how to handle terraform and concourse autopilot 
- [ ] Have a training and make documentation, leverage cloud.gov resources if we can

**Comment by LindsayYoung** [comment]
@ccostino and I had a training with Gashaw and Rohan. We identified the Terraform documentation and showed how the code corresponds to the AWS setting. Showing the console is the best we could without being able to get the AWS accounts going.  This should get people a basic understanding that we can build on once the accounts are settled.
