### ISSUE TITLE
Setup time to discuss SQL tests with CM

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2682]
Once we're able to get a time with @cmc333333 we'll bring in folks from FEC as well for the review.

**Comment by ccostino** [comment]
@cmc333333 has a PR started that is a WIP around this (#2638).  Work is largely on hold at the moment pending more feedback in addition to completion of the work @vrajmohan is currently involved with, but we feel it'd still be good to schedule an introductory session about what this is, the philosophy behind it, and where things currently.  This way folks gain a better understanding of what we're trying to accomplish and how this will fit in with the project and be used, and can ask questions that might also help inform the efforts of the work too. :-)

Afternoons generally work better for @cmc333333, is there a day that would work well for folks on the FEC side @PaulClark2?

**Comment by ccostino** [comment]
Meeting scheduled!  We'll be having an intro session on 10/12 at 3 PM EST for an hour.
