### ISSUE TITLE
Add MUR date to /legal/ API endpoint

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2683]
Determine if  MUR date is available in elastic search/API
- [x] Ask Vraj if the data is already there
- [x] Add `open_date` and `close_date` to /legal/ - see Vraj's notes below 
- [x] Add to "description" like we do here: https://github.com/18F/openFEC/blob/develop/webservices/args.py#L163-L166
- [X] Add automated tests

**Comment by vrajmohan** [comment]
The _indexed_ MUR data already has `open_date` and `close_date`: https://github.com/18F/openFEC/blob/develop/webservices/legal_docs/current_murs.py#L143. However, the API endpoint does not allow search by these fields. They need to be added in https://github.com/18F/openFEC/blob/develop/webservices/resources/legal.py#L155.

@AmyKort: Assuming that this task includes adding those fields to the search parameters?

**Comment by AmyKort** [comment]
Yes! Thank you!

**Comment by lbeaufort** [comment]
Thank you @vrajmohan for going over this with me! When it comes time, I'd like to take a shot at implementing this, if that's ok.

**Comment by vrajmohan** [comment]
@lbeaufort, go for it! We are committing to add it in the current sprint, I will be happy to pair with you. Please take a look at https://github.com/18F/openFEC/blob/develop/webservices/resources/legal.py#L247-L261.

**Comment by AmyKort** [comment]
Awesome! Thank you @vrajmohan !

**Comment by lbeaufort** [comment]
Resolved by PR 18F/openFEC#2712. Thanks for all your help, @vrajmohan!
