### ISSUE TITLE
Make next election year for Senate classes (function)

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2692]
Branching off from #2621

- [ ] Make next election year a formula (in `utils.py`?)  instead of listing it in `constants.py`

Background:
Currently, constants.py has NEXT_SENATE_ELECTIONS hard-coded for Senate classes 1-3. This means that the next election for Senate class 1 will need to be manually updated to 2024 after 2018, and so on.

NEXT_SENATE_ELECTIONS = {
    '1': 2018,
    '2': 2022,
    '3': 2020
}

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by lbeaufort** [comment]
Thanks @AmyKort! I couldn't find this because I put it in the wrong repo. 

Resoved by https://github.com/18F/fec-cms/pull/1529
