### ISSUE TITLE
Restore connectivity to data transfer machine

### ISSUE THREAD

**Issue by catherinedevlin** [18F/openFEC#270]
EC2 instance used to connect to FEC's CFDM data warehouse (Oracle) is currently not responsive.  

- Restore connectivity
- Document steps taken to help with future problems of the sort
- If possible, determine & document why machine lost contact

**Comment by catherinedevlin** [comment]
I wasn't able to figure out why the connectivity was lost, but restarting it did restore connectivity, and I did record the machine's name in our documentation so it should be easy to restart if needed in the future.

**Comment by rjmajma** [comment]
Nice! Thanks, @catherinedevlin.
