### ISSUE TITLE
Modify public.ofec_candidate_history_mv

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2706]
See: https://github.com/18F/FEC/issues/4568

For Zink:  the inactive flag should be 2014 **f**, 2016 **f** and  2018 **t**

`public.ofec_candidate_history_mv` has 2014 **t**,, 2016 **t** and 2018 **f**

two_year_period | cand_election_yr |cand_id | name | candidate_inactive| active_through
-- | -- | -- | -- | -- | --
2014 | 2014 | H4MT01041 | ZINKE | t | 2018
2016 | 2016 | H4MT01041 | ZINKE | t | 2018
2018 | 2018 | H4MT01041 | ZINKE | f | 2018

Suggested fix: 
`LEFT JOIN disclosure.cand_inactive inactive ON fec_yr.cand_id::text = inactive.cand_id::text AND fec_yr.fec_election_yr < inactive.election_yr`

this shoud be  `...AND fec_yr.fec_election_yr >= inactive.election_yr`

Question: Does this solution handle cases were a candidate is active 2014, inactive in 2016 but active again in 2018?

**Comment by ccostino** [comment]
@PaulClark2 this is a bit trickier than the proposed modification.  @hcaofec and I were looking into this more and determined that `>=` wouldn't be appropriate, but just a straight `=` might.  However, this did not fix the issue either and caused some other unintended side effects.

In looking at some more of the data, here are a couple examples of the current state:

```
select * from disclosure.cand_inactive where cand_id = 'H4MT01041';

  cand_id  | election_yr |          pg_date
-----------+-------------+----------------------------
 H4MT01041 |        2018 | 2017-03-05 09:23:56.845682
(1 row)


select candidate_id, candidate_election_year, name, candidate_status, candidate_inactive from ofec_candidate_history_mv where candidate_id = 'H4MT01041';

 candidate_id | candidate_election_year |     name      | candidate_status | candidate_inactive
--------------+-------------------------+---------------+------------------+--------------------
 H4MT01041    |                    2014 | ZINKE, RYAN K | C                | t
 H4MT01041    |                    2016 | ZINKE, RYAN K | C                | t
 H4MT01041    |                    2018 | ZINKE, RYAN K | C                | f
(3 rows)


select * from disclosure.cand_inactive where cand_id = 'H4MT01041';

  cand_id  | election_yr |          pg_date
-----------+-------------+----------------------------
 H4MT01041 |        2018 | 2017-03-05 09:23:56.845682
(1 row)


select candidate_id, candidate_election_year, name, candidate_status, candidate_inactive from ofec_candidate_history_mv where name ilike '%Becerra%';

 candidate_id | candidate_election_year |      name       | candidate_status | candidate_inactive
--------------+-------------------------+-----------------+------------------+--------------------
 H2CA30143    |                    1992 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    1994 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    1996 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    1998 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2000 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2002 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2004 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2006 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2008 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2010 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2012 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2014 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2016 | BECERRA, XAVIER | C                | t
 H2CA30143    |                    2018 | BECERRA, XAVIER | C                | f
(14 rows)


select * from disclosure.cand_inactive where cand_id = 'H2CA30143';

  cand_id  | election_yr |          pg_date
-----------+-------------+----------------------------
 H2CA30143 |        2018 | 2017-03-01 13:46:26.543826
```

If we can start to identify a pattern as well as determine what should ultimately happen in these cases, we might be able to narrow it down.

h/t to @jontours for the help this morning!

**Comment by PaulClark2** [comment]
yay and Hi @jontours

**Comment by hcaofec** [comment]
Is there a place we can deply the hotfix that has '=' and take a look at the history table to see if the values are flipped correctly, and then go from there? We did not check the tables in dev before we reversed back this morning @ccostino @PaulClark2 @jwchumley 
I am seeing comments in elections.py related to this issue ( line 80, line 137 )

**Comment by ccostino** [comment]
@hcaofec and I caught up about this, we're going to abandon the hotfix as this is more involved to fix and work on it as a regular branch/PR off of `develop` - we'll resume in the morning and get ourselves setup! :-)

**Comment by hcaofec** [comment]
PR #2727 was created

**Comment by hcaofec** [comment]
PR was merged into develop

**Comment by hcaofec** [comment]
This feature was put into release branch yesterday. @LindsayYoung @ccostino 
Just want to make sure that you agree it's ready to go to release.

**Comment by LindsayYoung** [comment]
Yes,  thank you for your work on this @hcaofec! It was approved 9 days ago here https://github.com/18F/openFEC/pull/2727
