### ISSUE TITLE
Explore charting options

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#272]
**Goal:** Determine what 1-3 options we might want to use for generating the charts on the candidate and committee pages.

**Steps:**
- [x] Do some research and come up with a list
- [x] Discuss options with the team
- [x] Make a recommendation

**Comment by noahmanger** [comment]
There's two main types of charts we need to be able to make now:
### 1:
![candidate charts](https://cloud.githubusercontent.com/assets/1696495/5763245/b310b2d2-9c9d-11e4-90dd-21b44a001dd6.jpg)

### 2:
![by type](https://cloud.githubusercontent.com/assets/1696495/5763257/cb99c866-9c9d-11e4-8ade-ae4a64ece5af.png)

#2 is probably easiest just with HTML? For #1 here's some options I'm looking at:
- [Chartjs](http://www.chartjs.org/docs/#bar-chart-introduction) - non-d3 charting
- [NVD3](http://nvd3.org/index.html) - Library for d3
- [DimpleJS](http://dimplejs.org/) - Library for d3
- [C3](http://c3js.org/) - Library for d3
- [XCharts](http://tenxer.github.io/) - Library for d3

I _think_ it makes sense to go with a d3 library instead of the full d3 experience for simplicity's sake, but maybe not.

**Comment by noahmanger** [comment]
@theresaanna do you have thoughts on this?

**Comment by rjmajma** [comment]
Ping, @theresaanna.

**Comment by theresaanna** [comment]
@noahmanger I agree that it makes sense to use a d3 lib. I've only ever used nvd3, which seems like it has the least-friendly code interface of them all.

I'd say it makes sense to pick a couple promising ones, implement a realistic but basic example and see how it holds up. I find its hard to really evaluate how good documentation or options are without doing that. I imagine most of them are roughly the same in functionality, but exceptional interface and documentation can really push it above the others.

Does that help?

**Comment by noahmanger** [comment]
That makes sense to me! Closing this out.
