### ISSUE TITLE
Functional testing audit doc

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#273]
Create a document that lays out functionality that has yet to be tested in automated functional tests on the site. We can then better plan and account for what tests need to be created.

**Comment by contolini** [comment]
@theresaanna I'll soon be auditing and improving how CFPB builds/tests/deploys front-end code. You're my personal hero when it comes to testing so can I pick your brain some time? I'll find you on the chats.

**Comment by theresaanna** [comment]
@contolini You need to be finding yourself some better heroes, my friend. But I will happily chat anytime. I would bother you more but idk where to find you.

**Comment by rjmajma** [comment]
May not be worth doing. Theresa is not entirely sure if we need to lean on the functional tests as much now. Will update the tests and revisit when we know more.
