### ISSUE TITLE
Image number search not working

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2730]
https://www.fec.gov/data/

![pasted image at 2017_11_02 10_41 am](https://user-images.githubusercontent.com/11817734/32331993-b9472878-bfba-11e7-8812-6bcb8fde9fd8.png)

https://www.fec.gov/data/search/?search=201707149066644302

**Comment by lbeaufort** [comment]
Fixed by https://app.zenhub.com/workspace/o/18f/fec-cms/issues/1440
