### ISSUE TITLE
Candidate profile doubles amounts when filers files wrong form and amends with correct form

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2743]
We fixed this for committees a long time ago but it looks like it is still an issue for candidates.

https://www.fec.gov/data/committee/C00649954/  shows the correct amounts (ttl receipt for example)

https://www.fec.gov/data/candidate/H8NY23175/ doubles the amount. 

@hcaofec

**Comment by hcaofec** [comment]
This committee ( C00649954 ) had F3P as its new filing, then F3 amendment and ends up with two rows in V_SUM. It's a single case.
@jwchumley

**Comment by jwchumley** [comment]
It isn't a single case though because it happens fairly often. People mistakenly file on the wrong form then amend with the correct form.


Jeff Chumley

Electronic Filing, Web and Disclosure Branch Manager

Federal Election Commission



________________________________

**Comment by hcaofec** [comment]
This issue is resolved by inserting the row into V_SUM_F3_AMENDED_BY_F3X table
