### ISSUE TITLE
Document how all chart data will be received

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#275]
**Goal:** Written plan for how we will populate the data of each of the charts, confirming that we will be able to get what we need from the API.

**Steps:**
- [x] Create google doc with images of the charts
- [x] @LindsayYoung annotate

**Comment by noahmanger** [comment]
This document is here: https://docs.google.com/a/gsa.gov/document/d/1PXOEFjcnSKcFEi4b-awGx6CKhn_7yYYQL2QHQQX8MYc/edit?usp=sharing

**Comment by LindsayYoung** [comment]
I annotated all that was in there. Feel @noahmanger and @theresaanna, free to add more images to the document and assign me a task in GitHub to annotate it.
