### ISSUE TITLE
Add more logging to these processes - API 

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2751]
Collective research task.

- [ ] Part of Redis/Celery class
- [ ] During walkthrough of downloads take note of where logging can be improved. 
- [ ] Logging in python examples (see Lindsay for examples in this project).

**Comment by lbeaufort** [comment]
I tagged myself on this one even though I'll be out next week so I can spend time researching this issue.

**Comment by lbeaufort** [comment]
Created issue #2754 as a research task for myself and took myself off this task, as I'll miss next week's redis/celery training

**Comment by LindsayYoung** [comment]
We did not cover this as much in the class, but we made a lot of general progress on this:
https://github.com/18F/openFEC/pull/2755
https://github.com/18F/openFEC/pull/2759
