### ISSUE TITLE
Fix issues surrounding API timeouts on 2017-11-15

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2756]
- [x] Configure NewRelic for better granularity
- [x] Increase app instances and workers
- [ ] Create a dummy Flask app to investigate why gunicorn logging is not available
- [x] Turn DEBUG off
- [ ] Investigate slow queries

**Comment by LindsayYoung** [comment]
We ended up getting the logs going in #2759 
We will still want to confirm with cloud.gov that app is logging what we think it is.

**Comment by patphongs** [comment]
Post mortem document started by @LindsayYoung is [here](https://docs.google.com/document/d/1tizrfTK0o7j2CrptDvXX_7MqopL7LoSlt3sy2gsDj1A/edit#) :lock:

**Comment by AmyKort** [comment]
closing. Additional work continues at https://github.com/18F/openFEC-web-app/issues/2343
