### ISSUE TITLE
Add more logs for celery-beat

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2771]
In diagnosing production issues on 11/29, we discovered that celery-beat doesn't have very verbose logs. [Example in Kibana](https://logs.fr.cloud.gov/goto/ee7a59d0997fe42da408cf1ae09d2550)

So that we can better track its activities, add more logging for `celery-beat` app.

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by lbeaufort** [comment]
Thanks @AmyKort! Yes - resolved by https://github.com/18F/openFEC/pull/2774
