### ISSUE TITLE
Investigate morning timeouts 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2779]
It seems like when the morning updates finish (succeed or fail) We are seeing timeouts on the API. These time outs seem to coincide with an increase in updates. 

- [x] look at logs
- [x] consider this in conjunction with investigation of slow queries https://github.com/18F/fec-cms/issues/1534

**Comment by AmyKort** [comment]
moving this task to https://github.com/18F/fec-cms/issues/1653

- [ ] research how to get read queries to execute even if underlying data has changed
