### ISSUE TITLE
Start public-facing docs

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#278]
Once we decide what we want, lets create a bare-bones version and throw what we have in there

**Comment by LindsayYoung** [comment]
Here is the documentation template that I was talking about:
https://github.com/USG-Website-Templates/USG-Website-Templates.github.io

**Comment by micahsaul** [comment]
I'm playing with things here: https://github.com/micahsaul/developer-hub

We'll figure out where this lives for real in the future.

Closing this out and opening #297 to find this a permanent home.
