### ISSUE TITLE
Switching API to the new aggregate tables

### ISSUE THREAD

**Issue by hcaofec** [18F/openFEC#2784]
This is to deploy the work completed in derived from [#2724](https://github.com/18F/openFEC/issues/2724)

We are switching API to access new aggregate tables in order to improve performance.

- [ ] make API code changes to use new tables
- [ ] modify view definition scripts that utilize these new tables
- [ ] drop old aggregate tables via flyway
- [ ] move new aggregate tables to public schema for consistency purpose

**Comment by hcaofec** [comment]
As we discussed on Friday's standup, a separate issue was created for the deployment of this task.  Please feel free to add If I missed anything.
@fecjjeng @LindsayYoung @ccostino @jwchumley

**Comment by jwchumley** [comment]
@hcaofec  Could you clarify this please?

**Comment by hcaofec** [comment]
I checked the sql files under openFEC/data/migrations, and only found ddl.  The scripts that loads the data into table are not there yet.  @jwchumley

**Comment by LindsayYoung** [comment]
I don't think the we need to move the aggregate tables to the public schema. The API already uses data across multiple schema. Just make sure the table or view starts with `ofec_` that is how we signify this a a website resource.

**Comment by fecjjeng** [comment]
I don't think it is "necessary" to move them to public.  However, the reason we put these tables in disclosure schema was just to avoid interfering with current aggregate tables.  Anyway we will have to rename these tables so we can change the owner at the same time to make it consistent with other public accessable tables.

**Comment by fecjjeng** [comment]
@ccostino @LindsayYoung The issue #2784 passed all the test and a pull request had been submitted.  However, we would like to hold that until we can have some discussion on the process of handling alter migration.  Would you mind don't approve it at this moment?

**Comment by fecjjeng** [comment]
@ccostino @LindsayYoung  After we talked to Vraj this afternoon. Also coordinated with Laura on her V## on the migration script she is working on, the pull request for this issue should be good to go, IF it pass your review.

**Comment by ccostino** [comment]
@hcaofec and @fecjjeng I just took a look and things appear to be in good shape for the most part!  I had a couple of questions regarding the index renaming, and wanted to check on whether or not the changes to the `package-lock.json` file were intentional.  We may have to do a bit of cleanup with that.  Please see the review for the details!

**Comment by fecjjeng** [comment]
@ccostino I had removed the extra line to make the migration script cleaner following your suggestion.

**Comment by hcaofec** [comment]
An PR [#2858](https://github.com/18F/openFEC/pull/2858) was approved.
