### ISSUE TITLE
Add command for installing test database

### ISSUE THREAD

**Issue by vrajmohan** [18F/openFEC#2788]
Add a command in `tasks.py` for invoke to use that creates the roles, runs migrations, and finally loads subset data from a data only dump. Although the current subset data dump is still usable for creating the subset database, it includes the database schema and may not warn us when there are changes to the schema migrations in `data/migrations`. Creating this task will have the benefit of continually validating the data subset.

**Comment by vrajmohan** [comment]
This issue is a result of #2681.

**Comment by ccostino** [comment]
It might not be a bad idea to take a look at upgrading `invoke` itself as a part of this too, [we're several versions behind](http://www.pyinvoke.org/changelog.html), but that could also be a separate issue on upgrading several dependencies in general. :-)

**Comment by vrajmohan** [comment]
There are several _broken windows_ in the FEC databases - temporary tables that were created, tables that are no longer being used, etc. With the deployment of automated DB migration, this would be a good opportunity to clean these up and never let them back in again. Tagging @AmyKort  to assign an intrepid DBA who can work with @ccostino and me on this.

**Comment by vrajmohan** [comment]
Noticed that `disclosure.nml_form_2z_bk` and perhaps some other tables are not readable by `fec_read`. @ChingKuan, can you take care of this?

**Comment by vrajmohan** [comment]
Additionally, the following tables in schema `real_efile` need to be readable by `fec_read`: `f3pz2, f3pz1, f3z1, f3z2`.
