### ISSUE TITLE
Create icons for Candidates and Committees

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#279]

**Comment by noahmanger** [comment]
Here's a couple concepts I'm working on. Will continue to workshop with other designers.

![screen shot 2015-01-14 at 5 52 03 pm](https://cloud.githubusercontent.com/assets/1696495/5751299/394ccbac-9c16-11e4-9324-2b062e0ac0b6.png)
![screen shot 2015-01-14 at 5 52 22 pm](https://cloud.githubusercontent.com/assets/1696495/5751298/39492e70-9c16-11e4-9e88-4150732793e3.png)

**Comment by noahmanger** [comment]
What do y'all think of these icons for now? 
![icons](https://cloud.githubusercontent.com/assets/1696495/5909151/bcc7d9ae-a562-11e4-9ca8-6e47664ec7e1.png)

**Comment by rjmajma** [comment]
I like the new committee icon idea. :+1: to both.
