### ISSUE TITLE
Restore swagger-tools install line in README

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2795]
Our recent change/fix to build Swagger UI in the app itself left the [`npm install -g swagger-tools` line in the CircleCI config](https://github.com/18F/openFEC/blob/develop/.circleci/config.yml#L53), which enabled [the Swagger test](https://github.com/18F/openFEC/blob/develop/tests/test_integration.py#L79-L85) to pass that will fail locally.

@xtine and @LindsayYoung, would this still be a valid test to run and we just need to modify something, or should we remove it?

**Comment by xtine** [comment]
I'm sorry I overlooked this! So I'm honestly not sure what `swagger-tools` does in this context. @ccostino do you know about this test?

**Comment by ccostino** [comment]
Not much other than that it exists. :-)  I missed it too and should've picked up on it since I saw the instructions in the README removed.  Given that we're now dealing with a heavily customized fork and the test is being derived from `apispec`, I'm not sure it's going to be all that useful, but I'd hate to just remove it too if it serves as a quick catch on something being broken with the generated documentation and interactive examples.

**Comment by xtine** [comment]
Yeah I now realize I was quick to remove `swagger-tools` from the npm install, I thought it was needed for the fork but now see that it is for the test!

**Comment by ccostino** [comment]
Oh, that explains it!  So we should keep it then?

**Comment by LindsayYoung** [comment]
The test makes sure we don't break the swagger documentation by making sure we are generating a valid swagger- I missed it before because I already had it installed locally

**Comment by ccostino** [comment]
Sounds like we should just keep them both then. :-)  All this should require is restoring the line in the README and making sure folks keep it installed!
