### ISSUE TITLE
Per ATO, do a mandatory January accounts audit

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2815]
Per ATO, we need to do mandatory January accounts audit.
Tagging @LindsayYoung 

More details: 
https://github.com/18F/fec-accounts/blob/master/README.md#how-we-maintain-accounts

**Comment by AmyKort** [comment]
Closing in favor of 
https://github.com/18F/openFEC/issues/2930 
https://github.com/18F/openFEC/issues/2929 and
https://github.com/18F/openFEC/issues/2928

**Comment by LindsayYoung** [comment]
Just making a note for the future that accounts tickets should be in the accounts repo
