### ISSUE TITLE
API keys claim to give you 120 calls per minute but they don't

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2819]
@rshorey commented on [Fri Dec 15 2017](https://github.com/18F/FEC/issues/4816)

I just got a new api key (I lost my previous one, sorry) which promises 120 calls per minute.

But it's not resetting after a minute. (I waited 65 seconds, and it's still not finding the key "results").

![screen shot 2017-12-15 at 4 38 27 pm](https://user-images.githubusercontent.com/901091/34061469-8276678c-e1b6-11e7-94aa-14c61cb9071a.png)

Could you please either change the permissions for the keys or change the documentation so I know what to expect?

Thanks!

**Comment by jwchumley** [comment]
@LindsayYoung @lbeaufort  Was there an issue on Friday with the API that would have caused this?

**Comment by LindsayYoung** [comment]
The limit is 1,000 an hour by default. Our documentation is wrong, but before, we were planning on changing the default to 120 calls a minute. The previous time we tried to up the limit, there was another setting that has been overriding the new limit.  Laura and I have the instructions on how to increase the setting.  Though, now we have a lot of database improvements in flight, so we might want to take a base line before we increase the default call limit. 

@jwchumley I recommend we get a doc change into this release and increase the default in a upcoming sprint. Sound good?

**Comment by LindsayYoung** [comment]
We updated the docs so I am closing this. If we want to increase defaults we can make a new ticket and do that in the future.
