### ISSUE TITLE
Decode committee type consistently 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#2827]
Noticed a variation in the audit search on how we label the committee types for consistency we may want to switch the committee type labels created in data/migrations/V0044__auditsearch_view.sql to match the rest of the site .

We can get this info as a relation to this table (We can alter the casing for consistency as well)- staging.ref_filed_cmte_tp;

| filed_cmte_tp_cd   | filed_cmte_tp_desc                                        | pg_date                 |
|--|--|--|
| C                  | COMMUNICATION COST                                        | 2017-02-08 21:18:50.685 |
| D                  | DELEGATE                                                  | 2017-02-08 21:18:50.701 |
| H                  | HOUSE                                                     | 2017-02-08 21:18:50.711 |
| N                  | NON-QUALIFIED NON-PARTY                                   | 2017-02-08 21:18:50.721 |
| P                  | PRESIDENTIAL                                              | 2017-02-08 21:18:50.731 |
| Q                  | QUALIFIED NON-PARTY                                       | 2017-02-08 21:18:50.741 |
| S                  | SENATE                                                    | 2017-02-08 21:18:50.75  |
| X                  | NON-QUALIFIED PARTY                                       | 2017-02-08 21:18:50.766 |
| Y                  | QUALIFIED PARTY                                           | 2017-02-08 21:18:50.776 |
| Z                  | NATIONAL PARTY ORGANIZATION. NON FED ACCT.                | 2017-02-08 21:18:50.785 |
| V                  | NON-QUALIFIED NON-PARTY WITH NON-CONTRIBUTION ACCOUNT     | 2017-02-08 21:18:50.796 |
| W                  | QUALIFIED NON-PARTY WITH NON-CONTRIBUTION ACCOUNT         | 2017-02-08 21:18:50.806 |
| I                  | INDEPENDENT EXPENDITURE - PERSON OR GROUP NOT A COMMITTEE | 2017-02-08 21:18:50.816 |
| U                  | SINGLE CANDIDATE INDEPENDENT EXPENDITURE COMMITTEE        | 2017-02-08 21:18:50.826 |
| O                  | INDEPENDENT EXPENDITURE-ONLY COMMITTEE                    | 2017-02-08 21:18:50.835 |
| E                  | ELECTIONEERING COMMUNICATION                              | 2017-02-08 21:18:50.845 |

**Comment by fec-jli** [comment]
Thanks @LindsayYoung 
will do it.

**Comment by LindsayYoung** [comment]
This is done Thanks @fec-jli
