### ISSUE TITLE
Fix management, nightly update, and related commands to always run against master DB

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2829]
We uncovered an issue with the most recent production deployment that showed the updates were actually running against the read replicas, which we do not want.  Anything of that nature, be it the nightly update tasks, other management commands, etc., always needs to run against the master database, not the read replicas.

The problem stems from the fact that the [custom DB routing session](https://github.com/18F/openFEC/blob/develop/webservices/common/models/base.py#L8-L44) we have, which manages the connection to the database before any query is executed, will always randomly select a follower by default as long as the follower connection string(s) is/are set.  In the case of production these are set with the two read replicas we have, so the updates have likely been executing against a follower the entire time.

I'm not entirely sure why the other statements would have worked in the past while the `REFRESH MATERIALIZED VIEW [CONCURRENTLY]` wouldn't, but that's what tipped us off as we're now able to refresh the materialized views directly again instead of rebuilding them with the recent DB migration work.  I confirmed this by running the code locally, printing out which connection was being used in the router, and stepping through the code in the refresh task to see the connection info.

In order to fix this, we need to adjust the DB routing so that it always points to master in the case of management commands, regardless of whether or not the are run manually or automatically via Celery.  Compounding this a bit is the fact that the `celery-worker` we have running accesses the same user-provided credentials as the main API app, which means that it also sees the read replica connection strings set and would therefore use them.

My recommendation would be to fix this in the routing code itself as much as possible (though it will likely require some adjustments in the calls being made, too, e.g., the `refresh_materialized` task) and as a hot fix, otherwise production updates will fall behind very quickly and require manual updates each night/morning until this is fixed.

**Comment by ccostino** [comment]
We've looked into a few more details and uncovered the following:

* The `SQLA_RESTRICT_FOLLOWER_TRAFFIC_TO_TASKS` environment variable (which [optionally restricts only a set of configured tasks](https://github.com/18F/openFEC/blob/develop/webservices/common/models/base.py#L26-L38) to run against followers) is not set in prod, which means that all queries/operations will go against followers.
* The permissions appear to be okay:  we checked in production and everything is owned by the main account as it should be, and the read-only account has `SELECT` privileges on the materialized views as well.
* Connections are being made with the correct account
* When I ran the code locally, I had set the `SQLA_CONN` and `SQLA_FOLLOWERS` environment variables to the exact same values as production to verify the attempt to connect to a read replica and execute the refresh.

**Comment by ccostino** [comment]
For additional context, these commands like the nightly updates shouldn't ever run against a read replica, they should always go against master since that's the source of truth and any changes there automatically get applied to the replicas.

If these run against directly against a replica, stuff goes out of sync and only one replica would get the updates.

**Comment by LindsayYoung** [comment]
Also, we might want to change the read replicas so that they are default_transaction_read_only  true to create a brighter line if we are having errors in which we are routing to the read DB when we shouldn't.

**Comment by ccostino** [comment]
Per the [AWS RDS documentation on read replicas](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html):

>When you create a Read Replica, you first specify an existing DB instance as the source. Then, Amazon RDS takes a snapshot of the source instance and creates a read-only instance from the snapshot. Amazon RDS then uses the asynchronous replication method for the DB engine to update the Read Replica whenever there is a change to the source DB instance. The Read Replica operates as a DB instance that allows only read-only connections. Applications connect to a Read Replica the same way they do to any DB instance. Amazon RDS replicates all databases in the source DB instance.

**Comment by ccostino** [comment]
But note that the read replicas also have copies of all of the accounts and permissions we have set, and we're connecting to them with the main account.  I wonder if there'd be a conflict with that, though it seems odd.

**Comment by ccostino** [comment]
Mystery solved!  This hasn't been an issue before and was only an issue with the newly released `refresh_materialized` method because of a small distinction when interacting with the `db` (SQLAlchemy) object in the app.  All management commands refer to `db.engine`, which is always bound directly to the master database, and the new code was using `db.session`, which hooks into the custom router we have setup.  This is simply a matter of swapping `db.session` to `db.engine` (or equivalent) in the `refresh_materialized` method.
