### ISSUE TITLE
Districts missing from election pages

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2844]
**What we’re after:**
We should display all congressional districts of a state. The endpoint is incorrectly constructed.  It does not include open seat districts. The status of the candidates involved in the race is irrelevant. All congressional districts of a state should be included on the state's election page.  

**Current state:** 
The endpoint is incorrectly constructed. It does not include open seat districts. It might be excluding other districts. Examples: 

- WA-08: `https://www.fec.gov/data/elections/?cycle=2018&state=WA`
- https://api.open.fec.gov/v1/elections/search/?page=1&cycle=2018&api_key=DEMO_KEY&sort=-_office_status&state=WA&per_page=20
- MI-11: `https://www.fec.gov/data/elections/?cycle=2018&state=MI`
https://api.open.fec.gov/v1/elections/search/?page=1&cycle=2018&api_key=DEMO_KEY&sort=-_office_status&state=MI&per_page=20
- CO-02: `https://www.fec.gov/data/elections/?cycle=2018&state=CO&district=2`
Candidates running: https://www.fec.gov/data/candidates/house/?cycle=2018&state=CO&district=02
- NV-03: `https://www.fec.gov/data/elections/?cycle=2018&state=NV&district=3`
Candidates running: https://www.fec.gov/data/candidates/house/?cycle=2018&state=NV&district=03
*Add'l information on CO and NV can be found in fec-cms #[1648](https://github.com/18F/fec-cms/issues/1648) 

Flag: Do we have a way to display a race page if there are no candidates registered?

**Completion criteria:**
- [ ] refactor endpoint (might not be necessary)
- [ ] display all congressional districts of a state
- [ ] possibly use `dim_race_inf` for all state/district information

**Comment by jwchumley** [comment]
Comprehensive list of missing district and senate elections for 2018:
Congressionals:

Arizona Congressional Districts 1, 8 and 9 are missing: https://www.fec.gov/data/elections/?cycle=2018&state=AZ.

California Congressional District 34 is missing: https://www.fec.gov/data/elections/?cycle=2018&state=CA

Florida Districts 9, 10, and 27 are missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=FL

Georgia Congressional District 6 is missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=GA

Idaho Congressional District 1 is missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=ID

Illinois Congressional District 4 is missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=IL

Indiana Congressional Districts 4 and 6 are missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=IN.

Kansas Districts 3 and 4 are missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=KS

Louisiana  District 4 is missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=LA

Massachusetts District 3 is missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=MA

Maryland Districts 4 and 6 are missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=MD

Michigan Districts 9 and 13 are missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=MI

Minnesota District 1 is missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=MN

Montana-At-Large District is missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=MT

Nevada District 3 is missing from the Election Map. https://www.fec.gov/data/elections/?cycle=2018&state=NV

New Jersey District 2 missing from the Election Map. https://www.fec.gov/data/elections/?cycle=2018&state=NJ

New Mexico Districts 1 and 2 are missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=NM

North Carolina District 13 is missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=NC

Ohio Districts 12 and 16 are missing from the Election Map. https://www.fec.gov/data/elections/?cycle=2018&state=OH

Pennsylvania District 9 and 11 are missing from the Election Map: https://www.fec.gov/data/elections/?cycle=2018&state=PA

South Dakota-At-Large District is missing from the Election Map. https://www.fec.gov/data/elections/?cycle=2018&state=SD

Tennessee Districts 2, 6, and 7 are missing from the Election Map. https://www.fec.gov/data/elections/?cycle=2018&state=TN

Texas Districts 2, 3, 5, 6, 16, 21, 27, 29 are missing from the Election Map. https://www.fec.gov/data/elections/?cycle=2018&state=TX

Virginia District 6 is missing from the Election Map. https://www.fec.gov/data/elections/?cycle=2018&state=VA

Washington District 8 is missing from the Election Map. https://www.fec.gov/data/elections/?cycle=2018&state=WA

**Comment by jwchumley** [comment]
Senate missing elections 2018:

https://www.fec.gov/data/elections/?cycle=2018&state=AZ
https://www.fec.gov/data/elections/?cycle=2018&state=MA
https://www.fec.gov/data/elections/?cycle=2018&state=ME
https://www.fec.gov/data/elections/?cycle=2018&state=MA
https://www.fec.gov/data/elections/?cycle=2018&state=ND
https://www.fec.gov/data/elections/?cycle=2018&state=TX
https://www.fec.gov/data/elections/?cycle=2018&state=UT

**Comment by jwchumley** [comment]
Possibly a separate issue but here it is:

American Samoa, Guam, Northern Mariana Islands, Puerto Rico, and the U.S. Virgin Islands are missing from making an appearance somewhere on the Election Map. https://www.fec.gov/data/elections/

**Comment by jwchumley** [comment]
Also related. The drop down list of states is ordered by state abbreviation but shows state names so some of them look out of order. Like District of Columbia is before Delaware because DC is before DE

**Comment by lbeaufort** [comment]
Look at elections.ElectionList, '/elections/search/'
