### ISSUE TITLE
Time period incorrect for House special election candidates 

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2845]
**What we’re after:**
We should display the correct two-year period (`Time period:`) for all candidates. 

**Current state:**
The two-year period (`Time period:`) for House special election candidates is incorrect. The `Time period:` of odd-year special elections should be the election year plus one not election year minus one. 

Examples:

- `https://www.fec.gov/data/candidate/H8GA06195/`
- `https://www.fec.gov/data/candidate/H8GA06286/`

Screenshot:
![image](https://user-images.githubusercontent.com/11817734/34418238-eeeaa310-ebca-11e7-8a59-3e9f3062d747.png)

**Completion criteria:**
- [x] determine cause of the incorrect `Time period:`: front-end or API issue
   This was a front-end issue 
- [x] display the correct `Time period:`
   This was resolved by PR1708/Issue#1644 Election Year correction

**Related issues or PRs:**
https://github.com/18F/fec-cms/issues/1644
https://github.com/18F/fec-cms/issues/1642
https://github.com/18F/fec-cms/pull/1677

**Comment by LindsayYoung** [comment]
This is a front end task. We calculate the time period depending on the 2-4-6 aspect of the data. I think we will want to start off the the calculation by getting the end year of the cycle with something like  `n = n + n % 2`

**Comment by cptechiegal** [comment]
Financial Summary page displays 1 election year: 2017 for time period (cycle) 2016-2017
The financial Summary page is currently displaying the election year incorrectly as: 2017  (should  display  as 2018)
However, the Raising page has the correct election year: 2018 
(but this data seems to be coming from cycles data - see issue#2811)

API testing below indicates that API returns 2017 for elections years and 2018 for cycles.
API Testing: https://api.open.fec.gov/developers/#!/candidate/get_candidate_candidate_id_history_cycle

request:
https://api.open.fec.gov/v1/candidate/H8GA06195/history/?per_page=20&api_key=DEMO_KEY&sort=-two_year_period&page=1&election_full=false

"results": [
    {
      "flags": "H8GA06195",
      "address_state": "GA",
      "election_districts": [
        "06"
      ],
      "party_full": "DEMOCRATIC PARTY",
      "name": "OSSOFF, T. JONATHAN",
      "incumbent_challenge": "O",
      "district_number": 6,
      "two_year_period": 2018,
      "candidate_inactive": false,
      "address_zip": "31145",
      "last_f2_date": "2017-04-03",
      "last_file_date": "2017-04-03",
      "party": "DEM",
      "state": "GA",
      "election_years": [
        2017
      ],
      "candidate_id": "H8GA06195",
      "district": "06",
      "address_city": "ATLANTA",
      "first_file_date": "2017-01-03",
      "candidate_election_year": 2017,
      "cycles": [
        2018
      ],
      "active_through": 2017,
      "load_date": "2017-04-05T21:00:18",
      "office": "H",
      "office_full": "House",
      "address_street_1": "PO BOX 450326",
      "address_street_2": null,
      "candidate_status": "C",
      "incumbent_challenge_full": "Open seat"
    }
  ]

**Comment by cptechiegal** [comment]
Same issues for House Candidate: Handel
https://www.fec.gov/data/candidate/H8GA06286/

- Webpage Time Period not matching the Coverage Dates
Webpage/ GUI Display 
Election | Time Period    | Filings |  
Years     | Years (Cycles) | Coverage Dates: |  
2017      | 2016-2017       | 01/01/2017 to 09/30/2017 |  

- API Filings Coverage Start/End dates are null
API request:
https://api.open.fec.gov/v1/candidate/H8GA06286/filings/?page=1&per_page=20&api_key=DEMO_KEY&sort=-receipt_date

API response:
 "results": [
    {
      "election_year": 2017,
      "report_type": null,
      "state": "GA",
      "amendment_indicator": "A",
      "treasurer_name": null,
      "is_amended": false,
      "previous_file_number": 1160407,
      "committee_name": null,
      "file_number": 1161282,
      "document_description": "Statement of candidacy 2017",
      "committee_id": "H8GA06286",
      "debts_owed_to_committee": null,
      "cash_on_hand_end_period": null,
      "form_type": "F2",
      "coverage_start_date": null,
      "total_individual_contributions": null,
      "most_recent": true,
      "cash_on_hand_beginning_period": null,
      "report_type_full": null,
      "net_donations": null,
      "document_type": null,
      "office": "H",
      "csv_url": "http://docquery.fec.gov/csv/282/1161282.csv",
      "party": "REP",
      "document_type_full": null,
      "senate_personal_funds": null,
      "amendment_chain": [
        1148340,
        1160407,
        1161282
      ],
      "sub_id": "4050520171404032402",
      "pages": 3,
      "house_personal_funds": null,
      "opposition_personal_funds": null,
      "fec_url": "http://docquery.fec.gov/dcdev/posted/1161282.fec",
      "html_url": "http://docquery.fec.gov/cgi-bin/forms/H8GA06286/1161282/",
      "coverage_end_date": null, ...

- Also issue with Election Year set to 2017 but should display instead 2018

Webpage / GUI Display
Election | Filings
Years.    | Coverage Dates:
2017      | 01/01/2017 to 09/30/2017






API request:
https://api.open.fec.gov/v1/candidate/H8GA06286/history/?page=1&sort=-two_year_period&election_full=true&api_key=DEMO_KEY&per_page=20

Response
  "results": [
    {
      "address_street_1": "3085 ROXBURGH DRIVE",
      "active_through": 2017,
      "office": "H",
      "cycles": [
        2018
      ],
      "party_full": "REPUBLICAN PARTY",
      "last_file_date": "2017-05-05",
      "last_f2_date": "2017-05-05",
      "election_years": [
        2017
      ],
      "incumbent_challenge_full": "Incumbent",
      "candidate_election_year": 2017,
      "district_number": 6,
      "address_city": "ROSWELL",
      "name": "HANDEL, KAREN CHRISTINE",
      "election_districts": [
        "06"
      ],
      "load_date": "2017-08-01T20:57:28",
      "incumbent_challenge": "I",
      "address_state": "GA",
      "two_year_period": 2018,
      "state": "GA",
      "address_zip": "30076",
      "flags": "H8GA06286",
      "candidate_inactive": false,
      "address_street_2": null,
      "party": "REP",
      "candidate_status": "C",
      "first_file_date": "2017-02-09",
      "district": "06",
      "candidate_id": "H8GA06286",
      "office_full": "House"
    }
  ]

**Comment by cptechiegal** [comment]
Technical research:
The Time Period is handled in the subcycle-select component (GUI template) 
<div class="subcycle-select"><span class="cycle-select__label">Time period:</span> 
<span class="t-block">2016–2017</span> 
</div> 
 
The Time Period sub cycle component is displayed using the Handlebars templates: 
electionCycle.hbs and electionCycles.hb 
The initCycles code in cycle-select.js is where the min and max cycle is determined.
The code uses the selected cycle (assuming even year) to setup the min and max cycles
For single cycle (house) setting max=selected and min= selected -1
This seems to be coded correctly when input cycle is correct end year.

This is working correctly now, once PR1708 (issue#1644) is released, correcting the issue with the odd value Election year changed to even Election year which ensures the input is the correct end year.

**Comment by patphongs** [comment]
should be fixed in the next release with this merged PR https://github.com/18F/fec-cms/pull/1708

Closing this issue
