### ISSUE TITLE
Setup CircleCI with cron jobs for Auto Deploys

### ISSUE THREAD

**Issue by cptechiegal** [18F/openFEC#2855]
TravisCI was setup with Auto Deploy cron jobs.
Now that we are using CircleCI, we need to:
- [ ] discuss whether this feature is needed under CircleCI
- [ ] if yes, setup again under CircleCI

**Comment by LindsayYoung** [comment]
This is needs to be done for ATO

Here are the instructions:
https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow
