### ISSUE TITLE
Move archived MURs to their own index on staging and production environments

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2860]
This arises out of issue [#2810](https://github.com/18F/openFEC/issues/2810)

Although we can backup and restore _all_ the legal documents quite easily, we needed to figure out a way to do this for just archived MURs. Whenever there is a schema change in Elasticsearch, all legal documents need to be reloaded. As this takes an excessively long time for archived MURs (over 10 hours, and due to errors it can take 3-4 days), we created a new index `archived_murs` and moved all archived MURs there.

Back up and move the existing archived MURs from `docs` to `archived_murs` using the bulk reindex command (this has to be done once only) on 

**`stage` after the RSB-4 release is cut (1/24)**
- [x] Backup `prod` - ([Backup instructions])(https://github.com/18F/openFEC/wiki/Elasticsearch-backup-instructions)
- [x] Reload

**`prod` after deploy**
- [x] Backup  `prod` - ([Backup instructions])(https://github.com/18F/openFEC/wiki/Elasticsearch-backup-instructions)
- [x] Reload

 **Steps to move archived MURs:**
```
./manage.py create_archived_murs_index
./manage.py move_archived_murs
```
(wait to make sure they've all moved over)
```
cf ssh api
curl -XGET '[INSERT_URI]/archived_murs/_count' -d'
{
  "query": { "match": { "mur_type" : "archived" } }
}
' | python -m json.tool | less
```
```
./manage.py refresh_current_legal_docs_zero_downtime
```

**Comment by AmyKort** [comment]
What's the status of this?

**Comment by lbeaufort** [comment]
@AmyKort I'm sorry, this one slipped off my radar when it got automatically changed to "ready" and I didn't notice. I'll need to confirm this is all done, because it's been a while.
