### ISSUE TITLE
RDS Dev instance needs a little TLC

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2863]
Our dev instance hasn't been reporting nightly updates for a few days now, and the last few updates that ran were also erroring out.  We should address these things soon so that we are in good shape for the next release.

The last update was on January 10, and the error was with the Schedule B update:

```
ERROR:manager:Refreshing ofec_sched_b_master failed: (psycopg2.IntegrityError) duplicate key value violates unique constraint "idx_ofec_sched_b_2017_2018_sub_id"
DETAIL:  Key (sub_id)=(1110220170035988742) already exists.
CONTEXT:  SQL statement "INSERT INTO ofec_sched_b_2017_2018 VALUES ($1.*)"
```

**Comment by LindsayYoung** [comment]
We got this going and dev db is back in order
