### ISSUE TITLE
Refactor district-to-zip lookup to use new table

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2875]
- [x] Use the new `ref_zip_to_district` table created by https://github.com/18F/openFEC/pull/2877
- [x] Take inventory of all the places the old tables `ofec_fips_states` and `ofec_zips_districts`are used
```
openFEC/manage.py
openFEC/utils.py:
openFEC/data/sample_db.sql
openFEC/webservices/config.py
openFEC/data/migrations/V0039.1__ofec_sched_a_aggregate_state_recipient_totals_mv.sql
openFEC/data/migrations/V0047__alter_ofec_sched_a_aggregate_state_recipient_totals_mv.sql
```
- [x] Create duplicate (renamed) materialized views that use this table instead of the old fips/zips csv tables. Replace all [references to the old MV](https://github.com/18F/openFEC/search?utf8=%E2%9C%93&q=ofec_sched_a_aggregate_state_recipient_totals_mv&type=) with the new MV
```
openFEC/data/migrations/V0039.1__ofec_sched_a_aggregate_state_recipient_totals_mv.sql
openFEC/data/migrations/V0047__alter_ofec_sched_a_aggregate_state_recipient_totals_mv.sql
```
- [x] Update ElectionsListView resource to reference this new MV
`openFEC/webservices/resources/elections.py`
- [x] Remove old views after successful deploy of the renamed views

Currently, the elections search endpoint and other views use tables created from csv's to map congressional district to zip code (`ofec_fips_states` and `ofec_zips_districts`). @PaulClark2 created a table in `FECPDEV` called `STAGING.REF_ZIP_TO_DISTRICT`. We should refactor the elections/search endpoint to use this table instead of csv's in the materialized view `ofec_elections_list_mv` to make updating this data easier.

```
select * from STAGING.REF_ZIP_TO_DISTRICT order by state_name, district, zip_code;

zip_district_id (17) - concatenation of date, fips_state_code, district and zip_code
state_abbrevation (2)
state_name (24)
fips_state_code (2)
district (2)
zip_code (5)
active (1)
notes (200)
```

**Comment by LindsayYoung** [comment]
@lbeaufort I think this is done but wanted to confirm with you that it met all the criteria

**Comment by lbeaufort** [comment]
@LindsayYoung yes! Thank you!
