### ISSUE TITLE
Create new table - staging.ref_zip_to_district

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2876]
**What we are after**:
We want to use a database table as source data for website's election page ZIP code to congressional district look-up.

**Current state**:
The website uses a .csv file.

**Completion criteria**:
- [x] add table to FECP
- [x] add table to transfer process
- [x] create migration script
    - [x] add table to PG 

**Related issues or PRs**:
https://github.com/18F/openFEC/issues/2875

**Table structure**:

Column Name	|	Data Type
----	|	----
ZIP_DISTRICT_ID	|	NUMBER (17)
STATE_ABBREVATION	|	VARCHAR2 (2 Byte)
STATE_NAME	|	VARCHAR2 (24 Byte)
FIPS_STATE_CODE	|	VARCHAR2 (2 Byte)
DISTRICT	|	VARCHAR2 (2 Byte)
ZIP_CODE	|	VARCHAR2 (5 Byte)
ACTIVE	|	VARCHAR2 (1 Byte)
CENSUS_YEAR	|	NUMBER (4)
REDISTRICTED_ELECTION_YEAR	|	NUMBER (4)
UPDATE_DATE	|	DATE
NOTES	|	VARCHAR2 (200 Byte)

**Comment by rjayasekera** [comment]
All done
