### ISSUE TITLE
Add AS, GU, MP, PR and VI to state drop down list

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2887]
**What we are after**:
We need to display American Samoa, Guam, Northern Mariana Islands, Puerto Rico, and the U.S. Virgin Islands in the state drop-down on the election page. 

**Current state**:
American Samoa, Guam, Northern Mariana Islands, Puerto Rico, and the U.S. Virgin Islands are not listed. Users cannot find candidates from these "states" using the election search page. 

**Completion criteria**:
- [x] add American Samoa, Guam, Northern Mariana Islands, Puerto Rico, and the U.S. Virgin Islands to the drop-down list

**Comment by lbeaufort** [comment]
Addressed by https://github.com/18F/fec-cms/pull/1721
