### ISSUE TITLE
Alphabetize by state name instead of state abbreviation

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2888]
**What we are after**:
We need to alphabetize the drop-down list of states of the election page by state name instead of state abbreviation.

**Current state**:
The drop-down list of the election page is alphabetize by state name instead of state abbreviation. For example, District of Columbia is before Delaware because DC is before DE.

**Completion criteria**:
- [x] alphabetize drop-down list by state name

**Comment by lbeaufort** [comment]
Addressed by https://github.com/18F/fec-cms/pull/1721
