### ISSUE TITLE
return coverage end date to  /elections/ endpoint

### ISSUE THREAD

**Issue by johnnyporkchops** [18F/openFEC#2891]
In order to show coverage end date on pages like https://www.fec.gov/data/elections/house/CO/04/2018/, we need to return coverage_end_date on /elections endoint

For issue: https://github.com/18F/fec-cms/issues/1470 - Add Coverage end date to Source reports column on election pages

WIP PR: https://github.com/18F/fec-cms/pull/1701

**Comment by lbeaufort** [comment]
(elections.ElectionView, '/elections/')

**Comment by LindsayYoung** [comment]
this is on dev
