### ISSUE TITLE
Investigate slack notifications for failed nightly updates

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2894]
Investigate why the [slack notifications](https://github.com/18F/openFEC/blob/3ead11a2c0e2ecda0811c1a1741b9e1c1d2bb7a6/webservices/tasks/refresh.py#L29) weren't occurring when nightly updates were failing

`cf run-task api "./manage.py slack_message 'Test'"`

- basic slack functionality seems to be running properly on `dev`, `stage` and `prod`

**Comment by LindsayYoung** [comment]
- see the logs triggering the task in celery beat https://logs.fr.cloud.gov/goto/990d181f59775e218ffdb9bbf2035210
- The celery worker has not run the task since the 25th https://logs.fr.cloud.gov/goto/f68626eabfeb1fd3f0f23583da304c10
