### ISSUE TITLE
Broaden search capabilites

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#291]
Ideally, these things should work in the search:
- zipcode  (returns candidates that represent that zipcode)
- candidate_id 
- committee_id
(I haven't tried an id search but I think it would be easy to deal with three cases at once)

**Comment by rjmajma** [comment]
The purpose of this is to allow users to search for elections, candidates, and committees that affect them locally. Our goal is to provide users with the most flexibility and ease of search for things that matter to them.

**Comment by jmcarp** [comment]
Looks like this isn't relevant anymore; closing.
