### ISSUE TITLE
Rename public.ofec_candidate_flag

### ISSUE THREAD

**Issue by rjayasekera** [18F/openFEC#2912]
Currently public.ofec_candidate_flag materialized view was created without the "_mv" at the end.  We will rename it to be public.ofec_candidate_flag_mv to be consistent with our other materialized view naming standards.

This rename is going to effect all the interfaces referencing this materialized view.

**Comment by rjayasekera** [comment]
I only found this view is being used only in following places. 
webservices/common/models/candidates.py
manage.py

**Comment by AmyKort** [comment]
Thanks, @rjayasekera !

**Comment by pkfec** [comment]
Reopened this issue to link the PR.

**Comment by AmyKort** [comment]
Awesome! Thanks, @pkfec ! This will make it a lot easier for us if we need to look back at this issue in the future,
