### ISSUE TITLE
Circle CI nightly redeploy - change ATO

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2914]
What we're after:
The ATO specifies nightly redeploy of Circle CI. Lindsay says it will be easier to update the ATO to specify a less frequent redeploy than to actually do a nightly re-deploy. 

Currently, have redeploys on pushes.

Completion: 
- [ ] ATO is updated for Circle CI to redeploy less frequently.
- [ ] Document Circle CI autodeploy process (step by step)

**Comment by LindsayYoung** [comment]
This wasn't even mentioned in the upcoming ATO.  I updated the deploy documentaion
