### ISSUE TITLE
Transfer state election office information to postgres

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC#2919]
@AmyKort commented on [Fri Feb 09 2018](https://github.com/18F/fec-cms/issues/1770)

We're building a graphic overview of House and Senate races by district to help users get more comprehensive at-a-glance information about particular races. Part of this work includes offering compliance information for users who are participating in the election of have particular compliance questions about the election.

What we're after in this ticket: We want to display appropriate state-level contact information on each district race visualization. This information is currently contained in trc_state_election_office. We want to migrate that information to postgres.

Completion criteria:
- [x] Data transfer from FECP.fecapp
- [ ] add in postgres a view that is equivalent to the TRC_ELECTION_DATES_VW currently in FECP

**Comment by fecjjeng** [comment]
After discussed with Jun Li, the necessity and structure of a view/materialized view is TBD.  What we currently need is fecapp.trc_st_elect_office table, which contains the information for the state offices' phone number.

**Comment by AmyKort** [comment]
Thanks, @fecjjeng !
