### ISSUE TITLE
Refine AuditCase endpoint to allow users to get results by selecting only a primary category.

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC#2920]
Filter functionality on the classic audit search allows users to filer by Primary category to produce a list of results. Users can then limit these results by choosing a subcategory. We want to keep this search flexibility on the new site by allowing users to see results for just the primary category filter, rather than having to choose both a primary and a subcategory in order to receive results.

This is only need refine AuditCase api endpoint. no impact to front-end code.

**Comment by fec-jli** [comment]
I have fixed this issue. and tested on local.
and create an new PR to merge to dev. Thanks

**Comment by AmyKort** [comment]
Thanks!

**Comment by AmyKort** [comment]
Since this is merged, I'll close.
