### ISSUE TITLE
Mandatory Audit of Accounts: AWS; Cloud.gov; RDS

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC#2929]
As a requirement of our ATO, we need to do a mandatory accounts audit. This work is high-urgency in that we should have completed our review last month.

More details:
https://github.com/18F/fec-accounts/blob/master/README.md#how-we-maintain-accounts

Completion criteria:

- [ ]  AWS
- [ ] Cloud.gov
- [x] RDS
cc @wluoFEC , @jwchumley @PaulClark2

**Comment by rjayasekera** [comment]
RDS account review done. 2/16/18

 [https://app.zenhub.com/files/23116127/39f5a00a-e068-4212-b06f-151272565847/download](https://app.zenhub.com/files/23116127/39f5a00a-e068-4212-b06f-151272565847/download)

**Comment by AmyKort** [comment]
Moving to accounts repo
