### ISSUE TITLE
Implement MVP version of the glossary

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#296]
**Goal:** A working version of the glossary with basic definitions. No search. Nothing fancy.

- [ ] Get "low hanging fruit" definitions
- [ ] Connect current terms on site to definitions

**Comment by rjmajma** [comment]
Trello card is here: https://trello.com/c/kUdUaLmw/76-allow-users-to-look-up-definitions-of-terms-as-they-browse-data

**Comment by LindsayYoung** [comment]
This is the lowest hanging fruit may be from these sources: 
http://www.fec.gov/ans/answers.shtml
http://www.fec.gov/pages/brochures/fecfeca.shtml#Disclosure

**Comment by noahmanger** [comment]
Oh here's a pretty good doc too: http://www.fec.gov/info/conference_materials/2013/candidateterminologymarch13.pdf

**Comment by noahmanger** [comment]
Spreadsheet of terms and defs started here: https://docs.google.com/a/gsa.gov/spreadsheets/d/1uPSBq4rAKcsB76RPwHQJ9dXbKQ0q5PEHDypDBB1LCk0/edit?usp=sharing

There's a handful of basic terms we need defined then I think we'll be good on the low hanging fruit.

**Comment by noahmanger** [comment]
This is coming along nicely. Here's a (very poor quality) preview. Will PR soon.

![demo](https://cloud.githubusercontent.com/assets/1696495/6517562/2953d300-c351-11e4-836b-bc68c20ae862.gif)

**Comment by LindsayYoung** [comment]
This is so exciting!
