### ISSUE TITLE
Check Logs 03/07/18

### ISSUE THREAD

**Issue by pkfec** [18F/openFEC#2965]
=====Follow this checklist to do check logs=======
https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist

-[X] Review Gemnasium
1)FEC-CMS: 2 alerts:
a)current Django>=1.10,<1.11, the latest is 2.0.2
b)moment.js current 2.17.1 has issue for fullcalendar(issue: 18F/fec-cms#1672), the latest one is
2.21.0
2)FEC-EREGS: No Alerts.
3)FEC-PATTERN-LIBRARY: 1 alert: moment.js current is 2.17.1, the latest one is 2.21.0
4)OPENFEC: 1 alert: for development tab, current handlebars3.0.3 is used for dependence.
for runtime tab, handlebars is 4.0.0 (is ok).

-[X] check user account
log in Kibana logs.
cms accounts : previous week: No new accounts
this week: No new accounts

-[X] cloud.gov users:
service keys: 10 service keys this week.

(every end of month.Create 4 issues for next month)

**Comment by hcaofec** [comment]
Reviewed the logs this week . 
cc @fec-jli @pkfec @fec-jli @ChingKuan
