### ISSUE TITLE
Create official location for API documentation

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#297]
For now, exploratory work has been done here: https://github.com/micahsaul/developer-hub

This needs to either be integrated into the openFEC site or we need to find some other permanent home for it.

**Comment by micahsaul** [comment]
Open Questions/Tasks:

- [ ] Styling
- [ ] Deploy (where? how?)
- [ ] Field descriptions
- [ ] More prose
- [ ] Send to Gray and/or Sean for once over

**Comment by LindsayYoung** [comment]
When #569 is done

**Comment by leahbannon** [comment]
Need to include...
- [ ] Welcome message
- [ ] Terms of Service
- [ ] Feedback link

Want to add next...
- [ ] Status Dashboard

Possible?
- [ ] App Gallery (things built on the API) and list of open source projects
- [ ] Developer mailing list?

**Comment by LindsayYoung** [comment]
One important TOS item for FEC data is that you can not use it for soliciting fundraising from individuals.

http://www.fec.gov/pages/brochures/sale_and_use_brochure.pdf

**Comment by jmcarp** [comment]
Done--we now generate API docs automagically.
