### ISSUE TITLE
Server Error retrieving MUR-6875

### ISSUE THREAD

**Issue by rjayasekera** [18F/openFEC#2977]
Try to retrieve MUR#6875 and getting a "Server Error" . This happens in PROD and STAGE environments and works on DEV

https://fec-dev-proxy.app.cloud.gov/data/legal/matter-under-review/6857/ -- DEV works
https://fec-stage-proxy.app.cloud.gov/data/legal/matter-under-review/6857/ -- STG error
https://fec-prod-proxy.app.cloud.gov/data/legal/matter-under-review/6857/ -- PROD error

I also noticed following in Kibana logs and they may or may not be related.
This only appearing in PROD environment logs
`ERROR`/ForkPoolWorker-4] Error uploading document ID `100487438` for `MUR Case 6857`: `No file image`
`ERROR`/ForkPoolWorker-2] Error uploading document ID `100174` for `MUR Case 4852`: `No file image`

**Comment by lbeaufort** [comment]
@rjayasekera I was able to get production working but there's still some wonkiness going on with the data. `dev` and `stage` are out-of-sync with production - that's a WIP and with another office. Until we can get those environments up-to-date, I'm not sure how much progress I can make on issues with `dev` and `stage`.

**Comment by lbeaufort** [comment]
Production issue is fixed - `dev` and `stage` databases out of sync - Salient plans to add the data transfer by next month.
