### ISSUE TITLE
Code charts on candidate and committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#300]
Goal: Working charts on the committee boxes on candidate pages and the financial details tab on committee pages (showing the big four numbers).

**Comment by rjmajma** [comment]
Dependency: #272.

**Comment by rjmajma** [comment]
Dependency over!

**Comment by rjmajma** [comment]
This may be done working from cached, local data.

**Comment by noahmanger** [comment]
Goal for this sprint: implement on candidate pages with dummy data.

**Comment by noahmanger** [comment]
Just pushed this up into 'adding-charts'. I just added some fake data to the `tmpl_vars` variable passed to `render_template()` in views.py. 

@theresaanna if you pull down the latest on that branch you should see it working as expected on the candidate page.

**Comment by rjmajma** [comment]
Checking in on the status of this task.

**Comment by theresaanna** [comment]
I am crap at keeping up with mentions. Will check this out today. Literally.
