### ISSUE TITLE
Create new table that unifies financial summary totals

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#304]
Financial summary totals should be pre-generated and loaded to a new table.

- [ ] Add all of the calculations as tasks below:

**Comment by rjmajma** [comment]
Hey @micahsaul, just spoke with @arowla and she'll tackle this over the course of the sprint. Assigning it to her. I'd like it if you two could sync up afterwards and discuss how she completed it, etc.

**Comment by arowla** [comment]
Replacing this with #395 just to get things down in light of API Refactor.
