### ISSUE TITLE
Donations API endpoint

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#305]
Create Schedule A endpoint.

**Comment by LindsayYoung** [comment]
I made good progress on the substance of this but, counting the entries is taking forever so I need to add indexes or something.

**Comment by LindsayYoung** [comment]
So, there are 88million records in schedule A, so we will need to only deal with the current or maybe last 2 campaign cycles to make it more manageable.

**Comment by arowla** [comment]
It is possible that with a table that size, we should look into
partitioning it.

On Tue, Feb 3, 2015 at 5:04 PM, Lindsay Young <notifications@github.com>
wrote:

> So, there are 88million records in schedule A, so we will need to only
> deal with the current or maybe last 2 campaign cycles to make it more
> manageable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/305#issuecomment-72745178>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by rjmajma** [comment]
Dependency on #317.

**Comment by LindsayYoung** [comment]
replaced by #836
