### ISSUE TITLE
Design what happens when no results returned

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#306]
On both Search Disambiguation and Category search pages.

**Comment by noahmanger** [comment]
Ok, I have solutions for this. I'm pasting the images with associated links to those pages on InVision. If you have comments on specific functionality, please log them there.

## 1. The general search results page, with all results returned - [InVision link](http://invis.io/G824VX5RS)
![2 1 search disambiguation](https://cloud.githubusercontent.com/assets/1696495/6011597/8ef57d84-aaf2-11e4-9318-d6e889436a31.png)

## 2. If only one time of results are returned - [InVision link](https://projects.invisionapp.com/share/G824VX5RS#/screens/61339726?maintainScrollPosition=false)
![2 1a search disambiguation - no results of 1 type](https://cloud.githubusercontent.com/assets/1696495/6011607/aea6e398-aaf2-11e4-940a-f6d875fa525a.png)

## 3. If no results are returned - [InVision link](https://projects.invisionapp.com/share/G824VX5RS#/screens/61339723?maintainScrollPosition=false)
![2 1b search disambiguation - no results](https://cloud.githubusercontent.com/assets/1696495/6011612/c69d266a-aaf2-11e4-813c-d9523f940c04.png)

**Comment by rjmajma** [comment]
2 is a great workaround for the time being. 

I also really like the way the redirect in 3 works. Great stuff. Looking forward to discussing with Kate later this week.

**Comment by noahmanger** [comment]
@theresaanna these work for you? If so, I'll close it out.

**Comment by noahmanger** [comment]
Kate will be helping out with copy, but I think as far as the goal of this ticket, it's satisfied. Closing out.
