### ISSUE TITLE
Complete draft of API documentation

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#307]
- [x] Finish documenting Candidates endpoint
- [x] Document Committee endpoint
- [x] Document totals (soon to be summary) endpoint
- [x] Add pages for one-letter abbreviations, full text, and descriptions for:
     - [x] Parties
     - [x] Committee types
- [x] Transfer ownership from micahsaul to 18F

**Comment by micahsaul** [comment]
This is done. Documentation lives at https://github.com/18F/openFEC-documentation and can be viewed at http://18f.github.io/openFEC-documentation/

**Comment by LindsayYoung** [comment]
so awesome
