### ISSUE TITLE
Web App Hallway Usability Testing

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#308]
Raph and Noah will conduct usability testing for the web app in the 18F hallways. Helpful to determine what needs further clarification, look and feel, etc. 

Let's aim for 3 lay testers each? What do you think, @noahmanger

**Comment by noahmanger** [comment]
For this sprint I'm going to focus on just 18F people so I can test the script. But yeah, 3 people.

**Comment by rjmajma** [comment]
Agreed, all 18F people. I am going to try to avoid some of those that have experience with this data though (I think Kailtin and Allison also worked with it at Sunlight, but could be wrong).

**Comment by rjmajma** [comment]
Duplicate of #352. Closing.
