### ISSUE TITLE
Figure out page titles

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#310]
Currently, pages aren't distinguished. Completion is having a first draft of page titles for each of the web app's pages.

**Comment by rjmajma** [comment]
I have completely dropped the ball on this one. I can come up with something quick and dirty, but I didn't follow up with Kate.

**Comment by LindsayYoung** [comment]
@rjmajma is this done?

**Comment by rjmajma** [comment]
I believe @theresaanna took a stab at this for our Google Analytics account. I'll let her chime in.

**Comment by theresaanna** [comment]
Yup, I invented a version. Take a look at the current page titles or in the templates to see.

**Comment by rjmajma** [comment]
Thank you! Closing for the time being then until a new need arises.
