### ISSUE TITLE
Quick once over and minor CSS tweaks for API documentation

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#312]
The API documentation, especially the Models/ Model Schema section, could use some CSS love before the API usability tests.

**Comment by noahmanger** [comment]
@micahsaul you still want me to look at this? I'll have time this sprint.

**Comment by micahsaul** [comment]
It's a nice to have in the future, I think. Not necessary this sprint.

**Comment by LindsayYoung** [comment]
I am going to include this in #569
