### ISSUE TITLE
Finish new round of design refresh

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#314]
**Goal:** Finish the latest round of design which will unify various aspects of the app and create a look and feel that can be the foundation for the public beta release.

**Steps:**
- [x] Review with Eric / Erica
- [x] Finish remaining pages
- [x] Review with FEC Team
- [x] Map to app diagram
- [x] Organize into a single place

**Comment by noahmanger** [comment]
Ok all, these are up here. I'm feeling pretty good about this direction, but please take a look and make any comments along the way: http://invis.io/F423SFKGE

**Comment by rjmajma** [comment]
So the thing that sticks out the most to me are the placement of the filters for candidates/committees. How will this look on a non-desktop device? 

Also, can you run these mocks by Nick Bristow for 508 accessibility issues? I imagine some things may come up.

**Comment by noahmanger** [comment]
Re: mobile -- I actually think this version will work better. Slide out menus are very common on small screens, so this approach should work gracefully and actually be more similar to the desktop version.

Re: 508 -- are you just concerened about color contrast? I've checked it throughout so we should be good.

**Comment by rjmajma** [comment]
Re: mobile - sounds good. 

Re: 508 - just a general concern. Nothing triggered it, but I figured it would be good to make sure Nick had a chance to look at things as we continue down our plan to launch.

**Comment by noahmanger** [comment]
Ok, 508 concerns satisfied. Closing this out.
