### ISSUE TITLE
add coverage dates in /total

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#317]
Add coverage dates and sort reports by end date.

We need the data reloaded to get the coverage dates.

**Comment by LindsayYoung** [comment]
This doesn't need a data refresh, we misidentified the problem earlier. The problem was that the cvg_date in the fact tables wasn't matching the dimdates foreign keys because they were using the foreign key 1 for things without dates.

This ticket just is to make sure we have coverages dates for the reports endpoints.

**Comment by rjmajma** [comment]
I believe this can be closed.
