### ISSUE TITLE
Fix visual bugs with typeahead

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#320]

**Comment by noahmanger** [comment]
Is this the type of bug you're talking about @rjmajma ?

![screen shot 2015-01-28 at 3 18 56 pm](https://cloud.githubusercontent.com/assets/1696495/5949302/0dcb6aec-a701-11e4-88ab-2e48c239cefb.png)

**Comment by rjmajma** [comment]
Yes it is.

**Comment by noahmanger** [comment]
Ah, yeah that was there before. An issue with the name being too long and bumping the office off the line. I'll come up with something better.

**Comment by noahmanger** [comment]
Ok this is in a forthcoming PR. I solved this by setting a widh for both the name and office, and set the text overflow to an ellipsis:

![screen shot 2015-01-28 at 4 59 02 pm](https://cloud.githubusercontent.com/assets/1696495/5950443/15a7e8d6-a70f-11e4-90de-941ce68f7239.png)

**Comment by rjmajma** [comment]
That's a great adjustment. Good call.

**Comment by cmc333333** [comment]
Aside: that's a beautiful autocomplete.

**Comment by noahmanger** [comment]
Aw shucks. I'm now seeing that the type is a _little_ too big, but i can fix that.

**Comment by noahmanger** [comment]
Fixed in latest PR
