### ISSUE TITLE
Finalize the app diagram

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#322]
**Goal:** Capture all screens we will be showing on the MVP release and the flows between them.

**Comment by noahmanger** [comment]
Here's the current draft. Can people please review and let me know if anything is missing or wrong?
 
![fec mvp diagram](https://cloud.githubusercontent.com/assets/1696495/5949082/367cc37a-a6ff-11e4-8951-dac4b9ef2a10.png)

**Comment by noahmanger** [comment]
Can I just get a confirmation from folks on the team that this is good? @LindsayYoung @theresaanna @rjmajma ?

Thanks!

**Comment by LindsayYoung** [comment]
Looks good to me!

**Comment by noahmanger** [comment]
Here it is in a slightly more readable format with straight lines and angels:

![fec mvp diagram](https://cloud.githubusercontent.com/assets/1696495/5966613/dea82240-a7ba-11e4-9213-27f784933002.png)

**Comment by rjmajma** [comment]
Second look reads much better. I may have some questions around contributions and the data we'll actually display, but this works for now.

**Comment by noahmanger** [comment]
Yeah, we need to figure out the particulars of those pages, but we know how they fit in the flow. 

I'm going to close this out. I've got this in InVision as well, so any future changes will be reflected there: http://invis.io/942400PNH

I've added boxes for the two error pages as well.
