### ISSUE TITLE
Make election cycle dropdown work using the new history endpoint

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#323]
1) should be pre-selected with the right cycle
2) when selected, should basically filter by election cycle = latest year in cycle

Dependency:
adding a list of years that a candidate ran to /candidate endpoint.

**Comment by LindsayYoung** [comment]
Aside from hooking up the years on the candidate and committee pages, we also need to look at the candidate and committee search. The candidate query-builder needs to default to 2014 and users have to select a an election cycle. The committee query-builder is not filtering by date, so let's hide that.

**Comment by theresaanna** [comment]
Talking with Lindsay, we realized that there's a dependency on this work. We need to know what years a candidate ran in order to populate the drop down accordingly.

**Comment by arowla** [comment]
@theresaanna Gimme 20 minutes... ;)

**Comment by rjmajma** [comment]
@arowla needs her own Bat-Signal.

**Comment by theresaanna** [comment]
+1

**Comment by arowla** [comment]
Ok, slightly more than 20 minutes. It was a bit more involved than I remembered. +1 to the bat-signal, though.

**Comment by theresaanna** [comment]
It always is. No rush. I definitely won't get there today.

**Comment by rjmajma** [comment]
We have a new history endpoint from #534 that needs to be implemented to make this work.

**Comment by LindsayYoung** [comment]
This can be implemented with the 
 - candidate/id/history/year endpoint for the information in the blue bar on the top
 - filtering totals by year=
 - filtering reports by year=

**Comment by jmcarp** [comment]
Can this be closed @LindsayYoung?

**Comment by LindsayYoung** [comment]
yes
