### ISSUE TITLE
rename /total /summary

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#325]
It is confusing to api users since we have totals and reports in that endpoint

**Comment by LindsayYoung** [comment]
I also want `afiliated_committees` on the candidate endpoint to be `mentioned_by_committee' or something that does not imply a relationship

**Comment by micahsaul** [comment]
Other notes:

Candidate endpoint:
- [ ] primary_committee doesn't need election_year
- [ ] should election_year on mentioned_by_committee be renamed to something like "year_mentioned"

Committee endpoint:
- [ ] Candidate doesn't need designation or designation_full
- [ ] Candidate doesn't need type or type_full

**Comment by LindsayYoung** [comment]
I am not sure we want to rename election_year because it is the year that the election is taking place, and I do want to keep the names close to the FEC names when we can. I completely agree on the others.

**Comment by micahsaul** [comment]
Also in committee:
 - [ ] Description form_type is redundant with the tope level-form type, no?

**Comment by LindsayYoung** [comment]
Form type is listed a few times because the information can be updated with different forms, when we have the forms linked properly I want users to be able to track down the source for any section of the data.

**Comment by micahsaul** [comment]
Gotcha.

**Comment by LindsayYoung** [comment]
After talking to @arowla, I think we might want to split out totals and reports to separate endpoints.

**Comment by arowla** [comment]
Yep, this reflects our API Standards
https://github.com/18f/api-standards#api-endpoints

> *Avoid single-endpoint APIs.* Don't jam multiple operations into the same
endpoint with the same HTTP verb.

On Tue, Feb 3, 2015 at 4:59 PM, Lindsay Young <notifications@github.com>
wrote:

> After talking to @arowla <https://github.com/arowla>, I think we might
> want to split out totals and reports to separate endpoints.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/325#issuecomment-72744302>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by LindsayYoung** [comment]
office and office_sought are redundant we need to get rid of one.

**Comment by arowla** [comment]
Let's pick, shall we? 'office' is more direct, but 'office_sought' is
clearer in the case of a sitting federal politician who may be sitting in
one office and running for another.

On Wed, Feb 4, 2015 at 3:57 PM, Lindsay Young <notifications@github.com>
wrote:

> office and office_sought are redundant we need to get rid of one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/325#issuecomment-72937216>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by rjmajma** [comment]
What will someone not familiar with FEC data and wanting to use our API prefer? Sounds like "office_sought" to me, but that may be my uneducated take.

**Comment by LindsayYoung** [comment]
I think this renaming became creating 2 endpoints and that is covered in issues #395 and #401
