### ISSUE TITLE
Clean up incumbent_challenge_full field

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#332]
Just discovered that if the `incumbent_challenge_full` field is `open_seat` it just displays as so:

![screen shot 2015-01-28 at 4 26 47 pm](https://cloud.githubusercontent.com/assets/1696495/5950471/59637afe-a70f-11e4-8bb7-67c1cc82961d.png)

We should probably clean that up and while we're at it capitalize Incumbent and Challenger.

**Comment by rjmajma** [comment]
Has been dealt with in the database.
