### ISSUE TITLE
API throws error when no q param is given to /name endpoint

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#341]
Go to http://localhost:5000/name and you'll see:

`AttributeError: 'NoneType' object has no attribute 'split'`

This should fail more gracefully-- tell the user that they need to include a `q` param, perhaps.

**Comment by jmcarp** [comment]
This should be addressed in #571. Omitting a `required` parameter raises a 400 with a sensible JSON error.

**Comment by jmcarp** [comment]
Confirmed that this is fixed, for this endpoint and for any other endpoint with required query parameters, in #571.
```
± http localhost:5000/names
HTTP/1.0 400 BAD REQUEST
Access-Control-Allow-Methods: GET
Server: Werkzeug/0.10.4 Python/3.4.3

{
    "message": "Required parameter \"q\" not found."
}
```

**Comment by arowla** [comment]
Since we know this will be fixed and it's low priority/low risk, let's close this.
