### ISSUE TITLE
Come up with a plan for handling support emails

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#347]
There should be a way that users can contact us if something is wrong or the like. The simplest solution would be to just have an email address they can contact. But we need a plan for who receives those and how we process them.

Assigning to @rjmajma for now.

**Comment by rjmajma** [comment]
That's a good point. I think we can create an 18F-FEC email address for things like this. Would that work?

**Comment by rjmajma** [comment]
@theresaanna is finalizing the account stuff. She is super helpful.

**Comment by rjmajma** [comment]
Account created and management given to Leah. Donezo!
