### ISSUE TITLE
Pilot usability script with 18Fers

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#352]
*Goal:* Make sure that the usability script tasks are achievable and informative, and make sure that the entire usability test process feels smooth.

**Comment by rjmajma** [comment]
Dependency with #300.

**Comment by noahmanger** [comment]
Update: did a couple tests and got some good feedback. Going to tweak the script a little.

**Comment by noahmanger** [comment]
Alright. Closing this out. Did a couple tests, got some good feedback and made tweaks. Ready to actually start testing in the wild.
