### ISSUE TITLE
Field Name Mismatch FEC & API

### ISSUE THREAD

**Issue by cmc333333** [18F/openFEC#359]
There are multiple "mappings" between FEC field names and API field names. Right now, all of the user parameters (API field names) are converted (FEC) before the query is made, then the results are converted back.

It might be better if the database itself used the API field names, so this conversion didn't need to occur (and the complexity could be centralized into the import scripts).

**Comment by LindsayYoung** [comment]
Agreed, we have been talking about this for a while.

**Comment by arowla** [comment]
Also agreed. In the summary table I am making for candidates, this is taken
care of.

On Thu, Feb 5, 2015 at 9:39 AM, Lindsay Young <notifications@github.com>
wrote:

> Agreed, we have been talking about this for a while.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/359#issuecomment-73056039>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by arowla** [comment]
This is starting to be addressed for candidates in #360 .
