### ISSUE TITLE
Use Candidate model to reimplement /candidate/<id> endpoint

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#362]
We probably want to create a new resource in /resources/candidates.py called `CandidateView` or somesuch...

This may also run into where we want to split general candidate metadata from their reports, making them separate endpoints. We might need to spec this out a bit first.

**Comment by LindsayYoung** [comment]
I got this working locally and pushed it to a branch: https://github.com/18F/openFEC/tree/reimplement_candidate_id_view

@arowla I tried to implement what you described but I will make changes if this is not what you had in mind.

Thanks!

**Comment by rjmajma** [comment]
Replaced by work in sprint 9.
