### ISSUE TITLE
Write SQL view for committee search

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#364]
- [ ] Encapsulate all the fields the `/committee` endpoint needs to return.
- [ ] Should be named `ofec_committees_view`.
- [ ] Should not be filtered on anything by default.
- [ ] SQL file to create it should go in `/data/sql_updates`

Lindsay's spreadsheet (see Slack channel) will be a good resource to help with this.

**Comment by arowla** [comment]
Hey @micahsaul, any progress on this? If you don't have time to work on it, I might steal it back from you.

**Comment by micahsaul** [comment]
I had briefly started on it, but got sucked back into documentation. If you want to steal it back and have the time, that's cool.

**Comment by LindsayYoung** [comment]
Would it be helpful if I jumped in on this?

**Comment by rjmajma** [comment]
Replaced by work in sprint 9.
