### ISSUE TITLE
Add Flask migrations

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#369]
In order to do deploys on Cloud Foundry, database migrations need to be built into our app. There's an integration tool for Flask that uses Alembic, which is lightweight migrations for SQLAlchemy:

https://flask-migrate.readthedocs.org/en/latest/
https://alembic.readthedocs.org/en/latest/

TODO:
- [ ] Move any .sql scripts in `/data/sql_updates` (in `api_performance` branch) into migration form
- [ ] Delete said scripts

**Comment by jmcarp** [comment]
I think this has been taken care of. @arowla can we close this one?

**Comment by jmcarp** [comment]
Pinging @arowla & @LindsayYoung for updates.
