### ISSUE TITLE
ensure more consistent capitalization 

### ISSUE THREAD

**Issue by gbinal** [18F/openFEC#371]

**Comment by arowla** [comment]
I built a library to do this: https://github.com/sunlightlabs/name-cleaver

Only question is whether we should use it on the front-end or back-end. It may not be 100% reliable, so I'm inclined to just use it to pretty up the front end.

**Comment by rjmajma** [comment]
Pinging @noahmanger to weigh in on this.

**Comment by noahmanger** [comment]
Big +1 on using name cleaver. Frontend sounds like it makes sense. This will help with readability of the site. 

But before we do that, @gbinal can you explain the need a little more? Is it that people weren't sure what would be capitalized? Or found the capitalization of names confusing?

**Comment by LindsayYoung** [comment]
Our codes as they are spelled out are lower case, the Parties you get from the FEC are title cased, and then the case in the underlying data varies depending what you are looking at. For example, Treasurer names are usually titlecased but candidate names are usually uppercase.

**Comment by LindsayYoung** [comment]
Talked with @noahmanger we can always shoot for title case
