### ISSUE TITLE
Have code references in the API itself

### ISSUE THREAD

**Issue by gbinal** [18F/openFEC#373]

**Comment by LindsayYoung** [comment]
An endpoint that explains the codes

**Comment by jmcarp** [comment]
Not entirely sure what we're looking for here, but I'm wondering whether this is resolved by the updated Swagger documentation and browsable API--what do you think @LindsayYoung?

**Comment by LindsayYoung** [comment]
They wanted the list for available codes for things like committee type. I think or documentation has gotten better about this.
