### ISSUE TITLE
Add links to terms/forms/etc. where possible 

### ISSUE THREAD

**Issue by gbinal** [18F/openFEC#376]
in the api documentation

**Comment by LindsayYoung** [comment]
We are working on this. The dependency on this is the underlying data. We will be getting some new tables tables to address this as early as this week.

**Comment by noahmanger** [comment]
Is this about links to the actual filing documents? Or like, to a blank Schedule A form and definitions of terms? (Outside of my purview, but just trying to clarify).

**Comment by LindsayYoung** [comment]
They wanted document links, which I would love to add when we get that data, it could be as soon as later this week.

**Comment by LindsayYoung** [comment]
This is covered by the /filings endpoint ticket
