### ISSUE TITLE
To make API docs more usable, include parenthetical examples for each field in documentation

### ISSUE THREAD

**Issue by gbinal** [18F/openFEC#382]

**Comment by LindsayYoung** [comment]
I think one narrative example in the overview that spanned a few endpoints would be nice. I could write that when we get a bit further along.

**Comment by LindsayYoung** [comment]
use full to keep in mind for #569

**Comment by LindsayYoung** [comment]
This would be nice in the future

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/iP_VyxlBWXBzijnUEFZhfg
