### ISSUE TITLE
include comprehensive list of potential values

### ISSUE THREAD

**Issue by gbinal** [18F/openFEC#383]

**Comment by LindsayYoung** [comment]
adding a dropdown of codes in swagger would be nice

**Comment by micahsaul** [comment]
Yup, I had intended to do that but totally spaced. There are a lot of enums in the API that are not yet actually enumerated in the documentation.

**Comment by LindsayYoung** [comment]
Also, maybe the API could return something that would make that task automated? I think @theresaanna  was saying automating those fields would be useful for the website as well.

**Comment by LindsayYoung** [comment]
Adding this to #569
