### ISSUE TITLE
President label

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#388]
The top says "Candidate for Presidential" instead of "Presidential Candidate" or "Candidate for President".

**Comment by noahmanger** [comment]
Just looked at this and the frontend is just getting that "Presidential" term straight from the data. Should we just change it in the database?

**Comment by LindsayYoung** [comment]
I don't think we should change the data but How about saying, Presidential Candidate, House Candidate and Senate Candidate? If you hate that, we can talk about more options.

**Comment by rjmajma** [comment]
:+1: to the three options Lindsay outlined.

**Comment by LindsayYoung** [comment]
Just took another look @noahmanger and changing to President is easier than I thought, and doesn't mess with the underlying data. Want me to change that now?

**Comment by LindsayYoung** [comment]
The down side would be that it doesn't map to the current FEC docs http://www.fec.gov/finance/disclosure/metadata/CommitteeTypeCodes.shtml

**Comment by arowla** [comment]
I think your original three options (with "Candidate for...") are a better
choice, since it keeps all three types of candidate naming consistent, and
I think it's more accurate wording, as well.

On Fri, Feb 27, 2015 at 1:47 PM, Lindsay Young <notifications@github.com>
wrote:

> Just took another look @noahmanger <https://github.com/noahmanger> and
> changing to President is easier than I thought, and doesn't mess with the
> underlying data. Want me to change that now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/388#issuecomment-76449098>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by noahmanger** [comment]
So is there no office-sought field actually assigned to the candidate? It's just the committee type of their principal committee?

**Comment by LindsayYoung** [comment]
Sorry to be confusing, it is part is filled out on Form 2 by the candidate. I sent you to the codes for committees on accident but they are candidate codes, which are [here](http://www.fec.gov/finance/disclosure/metadata/metadataforcandidatesummary.shtml)

That says President which is not the way Committee codes are, that seems inconsistent to me.

I don't mind changing it to President. just write me a ticket. (Sorry this is turning in to such a long thread.)

**Comment by noahmanger** [comment]
Hm, so this seems like a slightly [different problem](https://github.com/18F/openFEC-web-app/blob/master/openfecwebapp/data_prep/candidates.py#L36).

It's currently: `candidate['office'] = c_e['primary_committee'].get('type_full', '')` 

But really it should be: `candidate['office'] = c_e['office_sought']` right?

But right now `candidate.elections[x].office` and `.office_sought` are both just set to the one letter office code.

**Comment by LindsayYoung** [comment]
This is getting flattened and there will be `office`as the one letter code and `office_full` as office written out. That will happen in pr #444. That should fix things for you, correct?

**Comment by noahmanger** [comment]
Great. That should do it. I'll push up this small fix. It'll be `office_full` not `office_sought` in the candidate object, correct?

**Comment by noahmanger** [comment]
Ok this is ready in [PR 50](https://github.com/18F/openFEC-web-app/pull/50) whenever #444 gets merged.

**Comment by noahmanger** [comment]
I can't tell if this is fixed or not. It's not working on staging but maybe changes aren't updated yet?

**Comment by noahmanger** [comment]
Ok this looks like it's fixed. Closin'
