### ISSUE TITLE
Visually separate principal committees from other committees

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#389]
On the overview part of the committee page, In version 1 and version 2 of the mocks we had a strong demarcation between principal committees and other committees that are of interest but the candidate is not legally responsible for. I would like some kind of title that gives a visual clue that the principal committee has the closest relationship with the candidate.

**Comment by noahmanger** [comment]
Not sure why I ditched this from earlier versions, but here's a draft of how we could do this.

## Option 1
![3 1x candidate - alt 1](https://cloud.githubusercontent.com/assets/1696495/6175816/c765bdfa-b2ae-11e4-87d3-d0e1861c82fb.png)

## Option 2
![3 1x candidate - alt 2](https://cloud.githubusercontent.com/assets/1696495/6175818/cad50388-b2ae-11e4-8cf0-f6181c6c394b.png)

**Comment by LindsayYoung** [comment]
These are great options. Thanks!

**Comment by rjmajma** [comment]
I prefer the "Other Committees" tab. The pages may get a little long for some candidates if all are listed there.

**Comment by noahmanger** [comment]
Ok I went with Option 2. It's implemented now.
