### ISSUE TITLE
Database performance tuning 

### ISSUE THREAD

**Issue by catherinedevlin** [18F/openFEC#39]
Goal: Satisfying speed when end-users query via the app or API
Criteria: The following queries against production complete within the specified desired times:
  (TBD)
Steps: 
  - Determine criteria queries
  - Create script to time the criteria queries
  - Much DBA black magic which I am forbidden to reveal until the desired time is achieved.  

Dependencies: None (except getting the criteria queries)
User need: Coddle short postmodern attention spans

**Comment by LindsayYoung** [comment]
I think this is covered in htsql to sqlalchmy move
