### ISSUE TITLE
Fix link to "fec.gov" on web app

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#390]
Clicking on the link (in screenshot) on the current incarnation of the web app doesn't seem to work. It currently takes you to https://fec.gov. Unfortunately, the FEC isn't using HTTPS. 

![screen shot 2015-02-11 at 10 38 38 pm](https://cloud.githubusercontent.com/assets/3649037/6161437/c089ae44-b23e-11e4-969d-fda93ca2ca18.png)

**Comment by noahmanger** [comment]
d'oh. fixed in the 'adding-charts' branch.
