### ISSUE TITLE
Showing stats for Joint Committees

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#391]
When we had talked about Joint Committees as of version 2 of the comps we were going to show the portion of money form the joint fundraising committee that went to the Principal committee and not all of that committee's stats. 

It is a little confusing to show the entire stats for the joint fundraising committee because it includes funds going to other candidates. Since the purpose of a candidate page is to hi-light information we have about that candidate, if they want to find out more about the committee, they can go to that committee page. 

Another way to solve this would be to only show principal committees on the first tab and show joint fundraising committees and PACs on the "outside spending" page.

**Comment by noahmanger** [comment]
So as I understand it, the task here is to design how Joint Fundraising committees look on candidate pages, correct? Do we just want to show how much money they contributed towards that candidate? Do we care about showing anything else?

**Comment by LindsayYoung** [comment]
I think that we should probably just list the joint committees for now. And when you click on them, you can get all their details on their committee profile page.

In the future, we could add what they gave to that candidate. (We need info from a table that we don't have hooked up to an endpoint yet.) I think that is great to add money to that candidate as long as we are clear that that money is a subset of the money reported by the principal committee.

I don't like having full stats because that represents money that is not going to the candidate, which seems outside the focus of the candidate page.

**Comment by rjmajma** [comment]
Noah fixed this.
