### ISSUE TITLE
Fix Indexing Error 

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#393]
When looking for Obama, typeahead shows three results. The second, Obama/Senate, creates an index error. 

![screen shot 2015-02-12 at 5 00 52 pm](https://cloud.githubusercontent.com/assets/3649037/6177962/be673eb6-b2d8-11e4-8eac-99f06b0592c3.png)

https://fec.18f.us/candidates/S4IL00180

**Comment by cmc333333** [comment]
Odd error message, but I think it derives from `incumbent_challenge` not being present in the context.

Also that Werkzeug debugger is super cool.

**Comment by LindsayYoung** [comment]
It could degrade more gracefully but the underlying issue is that the candidate pages are using the default year filtering on the API, so, if there are not records in the last 4 years, the records that it is expecting are not going  to be there. I think the easiest way to fix that would be to add the year to the call.

**Comment by theresaanna** [comment]
Just talked to Lindsay. In the current master branch of the API, filtering by election year in the URL has a bug where the default filtering isn't actually overridden. I'm going to implement fixes to stop this bug and prepare for refactor changes Lindsay is making to the candidate endpoint. The result for now is going to be a near empty candidate page for these candidates that aren't in the last two election cycles. Once we merge Lindsay's work, that should be fixed.

**Comment by rjmajma** [comment]
That's awesome. Thanks @theresaanna and @LindsayYoung.

**Comment by theresaanna** [comment]
https://github.com/18F/openFEC-web-app/pull/39
