### ISSUE TITLE
Implement totals API refactor changes to front end Flask app

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#399]
When @arowla reworks and breaks up the totals endpoint, implement changes in the front end Flask app.

Dependency:
Alison's API refactor for totals

**Comment by theresaanna** [comment]
https://github.com/18F/openFEC/pull/449

**Comment by theresaanna** [comment]
https://github.com/18F/openFEC-web-app/pull/65

**Comment by rjmajma** [comment]
Pinging @arowla or @LindsayYoung to take a look at this.

**Comment by arowla** [comment]
On it.

**Comment by arowla** [comment]
This was merged. Closing.
