### ISSUE TITLE
Create Workflow of FEC.gov

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#400]
Related to our current sitemap thinking, we'll start framing our thinking around the five main areas of the new FEC.gov. 

Our goal is to identify how pages are going to be displayed, organized within their bucket, and how workflows will take place. This will not include individual solutions for how various pages will look or how features can be improved.

**Comment by noahmanger** [comment]
Ok I have an initial draft of this up on InVision: http://invis.io/XU296W1SZ

Please make comments there...it'll be easier to track.

**Comment by rjmajma** [comment]
I've read this a few times. I think it works really well. We're making a few guesses on what needs a new web app, which I think is okay. But this definitely helps make things feel less daunting, somehow.

**Comment by noahmanger** [comment]
Yeah, the app distinction is murky. Mainly wanted to differentiate what will be content that can be maintained by FEC via a more traditional CMS of some sort vs that which will we'll be building some custom interfaces too.

**Comment by noahmanger** [comment]
Ima go ahead and closet his out.

**Comment by rjmajma** [comment]
:+1:
