### ISSUE TITLE
Rework or rewrite Selenium tests

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#404]
- Micah and Theresa should determine whether it makes sense to rework existing tests or start fresh.
- Theresa should share with Micah what the deal is with Sauce Labs and Travis
- We should write some tests iteratively so that wherever we stop, there's some value added. Alison wants a test to hit each page and make sure its a 200.

**Comment by micahsaul** [comment]
Initial tests are there. Sauce/ Travis are not yet configured.

**Comment by theresaanna** [comment]
Besstttt.

Do you want me to tackle that integration or will you?

**Comment by micahsaul** [comment]
I'm going to close this out. I'll add a new issue for figuring out how to do the travis/sauce integration.
