### ISSUE TITLE
Implement `/committee/<id>/candidates` route, et al

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#407]
- [x] `/committee/<id>/candidates` should show candidate list for that committee
- [x] `/candidate/<id>/committees` should show committee list for that candidate
- [ ] The route showing committees should support a `type` parameter accepting multiple comma-separated committee types
- [ ] Both should support filtering by `year` or `election_year`

**Comment by arowla** [comment]
This could be either @LindsayYoung or @arowla, whoever gets it first.

**Comment by LindsayYoung** [comment]
I think I am going to jump on `/candidate/<id>/committees` because that will be needed for implementing  candidate pages. Then I will shift to making the CommitteeView.

**Comment by rjmajma** [comment]
/candidate/<id>/committees is being changed and is in PR #419.

**Comment by arowla** [comment]
This is all being done in other tickets. I'm going to close this and pull out separate tickets to just do a pass to check that those filter params (committee `type` and `year`/`election_year`) work.
