### ISSUE TITLE
 adding the list of election years in the results returned from /candidate

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#411]
New /candidate results will contain a list of all elections that a candidate participated in. That will make implementing the year dropdown on candidate pages easy.

**Comment by arowla** [comment]
I added this to the CandidateList endpoint, but this should be added to the CandidateView endpoint, too, right?

**Comment by LindsayYoung** [comment]
I think that it would be nice to have CandidateView but we don't need it now, so we can either close this or move it to backlog.

**Comment by rjmajma** [comment]
Why do we not need it now?

**Comment by LindsayYoung** [comment]
All the information the webapp was pulling from the /candidate/<id> branch is available on the refactored /candidate?candidate_id=<id> and /candidate/<id>/committee We should refactor /candidate/<id> to expose all the data, even if we are not using it right now, but it makes sense to prioritize the tasks that our website needs over the tasks that will eventually be useful to API users.

**Comment by rjmajma** [comment]
Completed!
