### ISSUE TITLE
Clean escaped quotes from data

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#412]
Names  of committees have the quotes escaped so it looks like \"WE THE PEOPLE\" OF THE THIRD CONGRESSIONAL DISTRICT in instead of"WE THE PEOPLE" OF THE THIRD CONGRESSIONAL DISTRICT I think this might be a problem elsewhere too.

It is just annoying. Putting it in backlog so we don't forget to clean that up at some point.

**Comment by jmcarp** [comment]
Not sure what changed here, but this seems to be working as expected now: http://fec-dev-web.cf.18f.us/committee/C00116574. @LindsayYoung can this be closed?

**Comment by LindsayYoung** [comment]
Awesome!
