### ISSUE TITLE
Get selenium tests running with Travis/ Sauce

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#422]
Need to figure out a way to run the selenium tests on Travis.

There are two possible paths here:

1) Set up a test server with API and frontend that the tests can be pointed at.
2) Determine a way to use mocked data on Travis but actual data locally. This would be, in my mind, a temporary fix as I'm not entirely clear on the benefit of browser tests that do not function as integration tests.

**Comment by micahsaul** [comment]
I think we're going to stick with option 1, so this depends on #469

**Comment by jmcarp** [comment]
I see that this has been flagged `stealable`. Can I steal it @micahsaul?

**Comment by jmcarp** [comment]
Proposed changes in https://github.com/18F/openFEC-web-app/pull/85

**Comment by jmcarp** [comment]
Implemented in 18F/openFEC-web-app#85.
