### ISSUE TITLE
Candidates showing no results

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#425]
Certain candidates, like Nancy Pelosi or John Boehner, are showing as not associated with no committees and bring back no results. 

https://fec.18f.us/candidates/H0OH08029

**Comment by LindsayYoung** [comment]
I think this is the join error, I will check again after this round of PRs that fix that error.

**Comment by LindsayYoung** [comment]
I think this is covered by #418

**Comment by LindsayYoung** [comment]
This is looking good
These links are working and I got there using search, the candidate list and the search disambiguation. 
https://fec.18f.us/candidate/H0OH08029
https://fec.18f.us/candidate/H8CA05035
