### ISSUE TITLE
Implement visual transition notification

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#426]
@noahmanger At one point we were talking about doing a white overlay or something while the page was loading to indicate that something is happening. Do you still want to do that? What should it look like?

Putting this here for reference:
https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload

**Comment by theresaanna** [comment]
Kicking to @noahmanger for whatever modifications he'd like to make to https://github.com/18F/openFEC-web-app/pull/46.

**Comment by rjmajma** [comment]
I believe this was completed, but I want to make sure before closing. @noahmanger?

**Comment by noahmanger** [comment]
Yep. Completed.

On Mon, Mar 2, 2015 at 12:05 PM, Raphael Majma <notifications@github.com>
wrote:

> I believe this was completed, but I want to make sure before closing.
> @noahmanger <https://github.com/noahmanger>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/426#issuecomment-76752221>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
