### ISSUE TITLE
Implement new homepage design

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#433]
**Goal:** A beautiful new home page with good copy.

- [ ] Finish copy with Kate
- [x] Make any design changes
- [x] Implement

**Comment by noahmanger** [comment]
Still working on the designs for this based on feedback from Kate and others. Latest version is up on InVision: http://invis.io/F423SFKGE

The new design does a couple things:
- Moves the search bar back to the hero area
- Relabels the "browse by category" section to be more about an introduction to the data (with links to browse each set). This allows us to explain the terminology a bit more, provide examples of the kind of records people can pull up, and also space for the shortcut type links that pull up a browse view with filters prepopulated (i.e. all 2016 presidential candidates)

Curious what folks think.

**Comment by rjmajma** [comment]
A few comments: 

- Let's leave off the Most Vieweds and Shortcuts. We don't have the means of adding those in currently and I'd rather not add in any dummy data or take a guess. 
- Where'd you pull the definitions from?

Otherwise, love the changes. Looks great and the added content seems very inviting. Great work.

**Comment by noahmanger** [comment]
Ok, that makes sense for now. I was thinking a little further ahead re: shortcuts. Here's a design for how it could be implemented right now. I removed the refernces to contributions, but also added boxes explaining the report totals and filings so it's very clear what data is in.

![1b home - mvp](https://cloud.githubusercontent.com/assets/1696495/6512964/63d87172-c32c-11e4-887e-668078b7caca.png)

I've just been writing these definitions myself but was going to enlist Kate to help improve clarity. @LindsayYoung are this right?

**Comment by LindsayYoung** [comment]
We might want to add that committees can be individuals too.

**Comment by noahmanger** [comment]
How common is that? If it's enough of an edge case it might just be confusing to put that info here.

**Comment by LindsayYoung** [comment]
I would say "group or person" instead of "legal entities". Every now an then there is someone with a lot of money who wants to do their own thing. It is not frequent but on occasion, it is in the news.  But, if that confuses people, disregard the comment.
