### ISSUE TITLE
Add more selenium tests

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#436]
Currently, tests are just verifying that pages load. Begin testing actual behaviors:

- [x] Searching for candidates or committees and navigating through search results page.
- [x] Use candidate and committee browse page, including use of filters.
- [ ] Search for candidate, navigate through to candidate detail page.
- [ ] Search for committee, navigate through to committee detail page.
- [x] Test glossary (when it's there...this may get pushed back to next sprint).

**Comment by micahsaul** [comment]
Didn't get single candidate/committee pages done this sprint. Pushing it back to the next.

**Comment by rjmajma** [comment]
I know a PR was merged for something selenium related. Is this wrapped? Can we close?

**Comment by micahsaul** [comment]
Yup, this can be closed. Once filings are added, we'll need to add more tests, but we'll start a new issue for that.
