### ISSUE TITLE
Ensure totals data is actually present on candidate / committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#448]
Currently, many pages that have totals data show `unavailable`. We should look into this.

For review after @arowla 's refactor.

**Comment by LindsayYoung** [comment]
Mitt's money is being attributed to the wrong cycle- I need to check on this too.

**Comment by LindsayYoung** [comment]
So, the cycle that we are importing is wrong, it needs to be derived by the coverage end date and not the date of the filing. This is another thing that I need to see is still a problem in the new data.

**Comment by LindsayYoung** [comment]
Take that back- the cycle date is looking ok, but the totals are still off compared to the FEC. I sill need to check again when we do the next update.

**Comment by LindsayYoung** [comment]
Ok, the problem is that both the amended report and the original report are being counted. We should be able to fix this by only counting the unexpired reports. I would like to add a flag for this- `" is_amended": True`. I will confirm that this is the case after I after we update.

**Comment by LindsayYoung** [comment]
I think this is fixed and the parts that are still not working are covered by #618
