### ISSUE TITLE
Public API documentation

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#45]
Before deploying our API into the public, or shortly thereafter, we should write good documentation around it.

**Comment by LindsayYoung** [comment]
We should have our first round of documentation by the beginning of February.

We need to figure out the details, how ambitious we want to be, who is doing what and where this falls in our list of priorities.

**Comment by noahmanger** [comment]
What have other 18F APIs used? I imagine it'd be great to be as consistent as possible.

**Comment by LindsayYoung** [comment]
Replaced by #569
