### ISSUE TITLE
in committee/<id> "active_through" is really "election_year"

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#453]
The best solution is to show the most recent entry for the candidate with an active through. Changing "active_through" to "election_year" is easier and correct as well.

**Comment by arowla** [comment]
I think I would go for something like `election_year_latest` or something, to help disambiguate it from the `election_years` list.

**Comment by arowla** [comment]
I am going to close this, since we are going to make the records over time much more distinct from the summary or most recent records with API refactor v2.
