### ISSUE TITLE
Too many candidates in committee page

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#460]
Listing the candidate multiple times on the committee page.
The API is showing each linkage so a candidate is listed with a unique election year each time. It would probably be more desirable to just show the candidate once.
https://fec.18f.us/committees/C00213512

**Comment by LindsayYoung** [comment]
In the models, the 'ofec_name_linkage_vw' needs an primary_key set to the linkage_key for the candidate endpoints. For the committee endpoints, using the linkage_key as the primary key produces too many results, I would like to use candidate_key as the primary key. I can't have the same table with 2 primary keys, even if I make them separate models.I have not been able to specify to select distinct by canidate_id in the committee endpoints. 

1) I feel like I could copy the table so that I could specify different foreign keys, but that would be hacky.
2) I could try to make the committee endpoints more responsive to time so that they work like the candidate endpoints. This was a less pressing concern because the important thing for committees that can change is the designation. Committee designation is not tracked over time by dimcmteproperties, it is linked by foreign key to dimcmtetpdsgn and only the most recent designation is available. Though it would be good to have the treasurers to be responsive over time, so it might be good to do anyway.

**Comment by arowla** [comment]
This was terribly hard to fix. We are going to remove candidates from being nested in committee results instead.

**Comment by LindsayYoung** [comment]
I am still seeing candidate name repeated-
committee/C00431445

**Comment by arowla** [comment]
This will be taken care of in #511.
