### ISSUE TITLE
Make sure that refactored committee endpoints can be filtered by committee `type`

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#463]
such as:
* `/candidate/<id>/committees?type=P`
* `/committees?type=P`

@LindsayYoung am I missing any endpoints above?

**Comment by arowla** [comment]
So the actual filter is called `committee_type`, and it seems to be working on the top-level `/committees` endpoint, but not on the nested resource version. I think this might be due to the embedded candidate data. Let's hold off on trying to fix anything until we refactor to separate the resources.

**Comment by rjmajma** [comment]
Moving to the backlog for the time being.

**Comment by jmcarp** [comment]
Is this still an issue?

**Comment by LindsayYoung** [comment]
It works

http://fec-dev-api.cf.18f.us/v1/committees?type=P

**Comment by arowla** [comment]
It works on the nested endpoint but only with `committee_type`, not `type`

https://fec-dev-api.cf.18f.us/v1/candidate/P80003338/committees?committee_type=P

On Tue, Jun 9, 2015 at 11:04 AM, Lindsay Young <notifications@github.com>
wrote:

> It works
>
> http://fec-dev-api.cf.18f.us/v1/committees?type=P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/463#issuecomment-110394371>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by jmcarp** [comment]
It doesn't look like *any* resource responds to a query parameter called `type`. The `CommitteeList` resource checks `committee_type`, regardless of the endpoint it's mounted at. If that's not the desired behavior, we can rename the `"committee_type"` key in `args#committee` to `"type"`, although that might be confusing, since there's also an `"organization_type"` key in the same args dictionary.

**Comment by LindsayYoung** [comment]
This was referring to committee type. (Which Alison wrote the proper query for) it was just called type at one point, but that was confusing so now we call it committee_type.

**Comment by arowla** [comment]
And I mentioned 'type' because that was the parameter @lindsaynyoung's
query used. ;)
