### ISSUE TITLE
Make sure that refactored endpoints can be filtered by `year` or `election_year`

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#464]
Should we be standardizing on one or the other?

@LindsayYoung

**Comment by theresaanna** [comment]
We want to use 'year'.

**Comment by theresaanna** [comment]
Doesn't make sense to work on just yet given that we're rethinking summary and single record endpoints. When the API settles a bit more, we should pick this back up.

**Comment by rjmajma** [comment]
Moving to the backlog in the meantime.

**Comment by LindsayYoung** [comment]
I think this is satisfied by the election cycle filters
