### ISSUE TITLE
Interview Greg and Judy at FEC

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#466]
**Goal:** Talk with people in the public information department to understand their content needs.

**Tasks:** 
- [x] Schedule meeting
- [x] Have meeting
- [x] Synthesize notes

**Comment by LindsayYoung** [comment]
I would find this meeting very interesting, could I tag along?

**Comment by noahmanger** [comment]
Sure!

**Comment by noahmanger** [comment]
These notes are synthesized in a new column on the Trello board called "New from Interviews".
