### ISSUE TITLE
Begin detailed site map

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#468]
**Goal:** To develop a deep enough understanding of the content to identify our 1st and 2nd level navigation items.

**Comment by rjmajma** [comment]
Pinging for an update before sprint planning later today.

**Comment by noahmanger** [comment]
Ok so here's what I've been putting together. 

![fec_content_map](https://cloud.githubusercontent.com/assets/1696495/6832014/fca1ad7e-d2e0-11e4-99d0-78f26424f640.png)

This isn't a _sitemap_ per se, but instead an effort to identify the different types of content / questions that we need to provide and how that roughly maps onto current content on the site. 

The way we actually _organize_ this content is a separate question. i.e. I think that these verticals don't correspond to site sections, but are instead one way of thinking about the content.
