### ISSUE TITLE
Add auth to nosetests

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#479]
For the API, auth needed to be moved from nginx to the python side for cloud foundry. So, the tests now need to be adapted so they have auth.

**Comment by arowla** [comment]
Auth is just for demo purposes, right? I would just turn on auth in the
case that DEBUG=False.

On Mon, Mar 16, 2015 at 10:24 AM, Lindsay Young <notifications@github.com>
wrote:

> Auth needed to be moved from nginx to the python side for cloud foundry.
> So, the tests need to be adapted to have auth.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/479>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by LindsayYoung** [comment]
I love when there is an easier solution! Thanks @arowla
