### ISSUE TITLE
Contributor notes on setting up repo for first time.

### ISSUE THREAD

**Issue by msecret** [18F/openFEC#482]
As I mentioned in the chat, @ultrasaurus has tasked me with checking out the openFEC app pretending to be an outside contributor to see what is confusing and what I get stuck with. This is for the hack day she has planned for late March.

I was able to fix a couple of problems with the front end build. Here are some notes I wrote up on what I still had problems with and what I found confusing.

- [ ] Whats the [fec repo](https://github.com/18F/fec) for? It's linked to in this repos docs but all issues seem to be old. Should the link to it be removed?
- [ ] There are no instructions or links to instructions on how to install sass. Will fix this myself.
- [ ] How do I run the rest API? How do I link the web-app to the rest API so I can run the full web-app experience?
- [ ] On the openFEC app what does the `python openfec/entities/pipeline.py CleanData --local-scheduler` command do? I'm unsure at this point what that repo is even for.
- [ ] there are links in the openFEC app README which point to itself, which is confusing.
- [ ] It would technically help to have some instructions on how to setup a py virtual env, although its understandable to require users to go to the virtualenv docs for this.

**Comment by LindsayYoung** [comment]
I think @ccostino and @emileighoutlaw have done a good job on this. 

Feel free to reopen if I missed anything.
