### ISSUE TITLE
Pelosi Bug

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#484]
Searching for Pelosi and clicking on the typahead result led to an typeerror:
https://fec.18f.us/candidate/H8CA05035

**Comment by LindsayYoung** [comment]
I think the root cause is incomplete incumbent data.

**Comment by arowla** [comment]
This was a front-end bug, then... I think we talked about it the other day.
cc @theresaanna

On Wed, Mar 18, 2015 at 1:16 PM, Lindsay Young <notifications@github.com>
wrote:

> I think the root cause is incomplete incumbent data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/484#issuecomment-83064634>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by LindsayYoung** [comment]
The front end should be more forgiving, but Nancy Pelosi is an incumbent and the data should say so.

**Comment by theresaanna** [comment]
This ticket now represents the investigation and fix(es) that might be necessary on the API side to pull in incumbent data.

The front end should handle this better, which is here: https://github.com/18F/openFEC/issues/498.
