### ISSUE TITLE
Limit ips 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#485]
For for the API, it make sense to do this by integrating with api.data.gov

**Comment by cmc333333** [comment]
Just to make sure - you'd be limiting the IPs to 18f servers? That'd mean no JS interacting directly with the API (as the IP would then be the user's browser), which it sounded like you all wanted?

**Comment by LindsayYoung** [comment]
We would be limiting the production API to api.data.gov servers. The production website would then call api.data.gov.

**Comment by cmc333333** [comment]
Ah, I read that as the opposite. Makes sense now, thanks!

**Comment by LindsayYoung** [comment]
closed by #564
