### ISSUE TITLE
Implement election cycle chooser

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#489]
This includes implementing the drop down, but also a piece of data that weaves into most operations and informs what data is used and rendered.

- Implement drop down
- Load/select API data based on cycle
- Other things I'll think of

This is a very basic implementation. Conditional persistence to come later.

See Trello for info on defaults.

**Comment by theresaanna** [comment]
Candidates are working, but I have yet to write tests. I'm having trouble getting Selenium tests passing. 

Committees aren't implemented yet because the active years aren't available from the API currently.

**Comment by theresaanna** [comment]
@LindsayYoung says, wrt implementing this on committees:
"For candidates the changes over time were in the dimcandproperties table. There isn't really a corresponding table for committees. I think we would have to get that information from form 1 which is trickier. Now that we can pull things through golden gate soon, we should check in with Paul and Jeff and see what views they already have that they could share with us."

We should probably create a new ticket for implementing this on committees. It won't happen this sprint.

**Comment by jmcarp** [comment]
Can this be closed @LindsayYoung?

**Comment by LindsayYoung** [comment]
yes let's close #489
