### ISSUE TITLE
Financials for principal committees not showing up on many single candidate pages

### ISSUE THREAD

**Issue by micahsaul** [18F/openFEC#495]
/candidate/H4MA09052 incorrectly claims that there are no associated committees, despite /committees/C00550715 being correctly listed as Principal Committee.

This leads to the financials not being displayed, as well.

Let me know if you need more examples.

**Comment by LindsayYoung** [comment]
The headers seem correct- I am seeing the candidate on the committee page and the committee listed on the candidate page. 

The financials are not being displayed on candidate page but they are on being displayed on the committee page, which makes me think it might be a front end bug. I don't know why the same thing does not happen for other committees. 

I don't know the current status of switching to the new totals endpoint- that is #399 @theresaanna is assigned to it. 

We will want to double check this when the refactor is completed hopefully that will take care of it.
