### ISSUE TITLE
Consistent incumbent status reporting

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#499]
This should be done after the work to split summary and history endpoints is done.

https://fec.18f.us/candidate/H8CA05035

**Comment by arowla** [comment]
This was originally #484. This also has a front-end component in #498.

**Comment by LindsayYoung** [comment]
The most recent dimcandproperties entry doesn't have the incumbent status. There are 2 places where you can see this information, there is an ICI status table too but Paul and Jeff said dimcandproperties was the better table to use.

**Comment by arowla** [comment]
We may want to add a not null check when the summary endpoint joins in the
most recent candidate status, in more SQL-y words, join on most recent
where status is not null.

On Tue, Mar 24, 2015 at 4:36 PM, Lindsay Young <notifications@github.com>
wrote:

> The most recent dimcandproperties entry doesn't have the incumbent status.
> There are 2 places where you can see this information, there is an ICI
> status table too but Paul and Jeff said dimcandproperties was the better
> table to use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/499#issuecomment-85683506>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by LindsayYoung** [comment]
We might want to just fix this on our side rather than wait for the underlying fix?

**Comment by jmcarp** [comment]
Fixed by @LindsayYoung in #767.

![screen shot 2015-05-14 at 5 35 59 pm](https://cloud.githubusercontent.com/assets/1633460/7642539/be3f85fa-fa5f-11e4-9421-cc41938e01d4.png)
