### ISSUE TITLE
Factor pagination into a common class

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#502]
Pagination from each endpoint should be factored into a common class.

- [x] Create a `Pagination` class in `webservices/common/util`
- [x] The `__init__` should take the request object
- [x] The class should set page_num and per_page as attributes
- [x] The class should have an `as_json()` method to return pagination info for the API
- [ ] Each endpoint should initialize that class in an instance variable
- [ ] Each endpoint should no longer deal with pagination directly, but delegate to the class
- [x] Check/write automated tests of pagination behavior

Please let me know if anything is unclear or something in this plan doesn't work out.

**Comment by LindsayYoung** [comment]
This has been pretty straight-forward except for `/names`. That endpoint doesn't produce a count of possible matches it always limits to 20. I was wondering if that was done on purpose to make that endpoint faster.

**Comment by LindsayYoung** [comment]
In `test_api.py` the following tests check pagination:

test_header_info
test_per_page_defaults_to_20
test_per_page_param
test_invalid_per_page_param
test_page_param
