### ISSUE TITLE
Remove nested candidates from committee results

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#503]
`/committee/<id>` should have candidate nesting removed from the Python side.

**Comment by LindsayYoung** [comment]
[ ] Remove nested field marshaling for candidates on the committee endpoint
 [ ] Remove or comment out any db.relationships on the Committee and CommitteeDetail models.
 [ ] Update automated tests

**Comment by LindsayYoung** [comment]
This is taken care of in pr #516

**Comment by LindsayYoung** [comment]
dependency web app refactor #511

**Comment by LindsayYoung** [comment]
Covered by #588
