### ISSUE TITLE
Run Card Sorting Exercise

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#508]
**Goal:** Run card sorting exercises with people inside and outside of FEC to give us data on where informational content should live. This will help us develop the overarching site architecture and land on a working set of top-level page sections.

**Task:**
- [x] Create cards
- [ ] Find 4 outside participants 
- [x] Find 3 FEC participants
- [ ] Synthesize findings

**Comment by rjmajma** [comment]
This may be delayed a bit because of scheduling conflicts for participants.

**Comment by noahmanger** [comment]
No longer relevant.
