### ISSUE TITLE
Create HTML + CSS for report summary view

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#509]
**Goal:** Static markup and CSS for report summary tab that Theresa can hook up the data to.

**Comment by noahmanger** [comment]
So I was about to code up the report summary page, but looking back over the previous design I felt it needed more work to simplify things. So I really dug into the committee page and think I've got a better approach.

Here's my thinking:

I don't think we actually need a "report summary" view. We need a "Two-Year Summary" view that includes the big numbers as well as their granular components (which now lives on the first tab), but what is on the "Report Summary" on the current site is just the first page of each report, so it's really redundant. So instead there's two tabs: 

## 1. Two-Year Summary
![3 2 committee](https://cloud.githubusercontent.com/assets/1696495/6953344/8ebb8774-d87d-11e4-8d19-d0b9d410de96.png)

-  This view includes the breakdown of each sub-total as well as the time series charts from the committee boxes currently on the candidate page
- The two-year summary like this allows for a more visual approach, rather than just a big page of numbers. 
- By default the Receipts tab is open as that's what most people are most concerned with. But each other row can be collapsed or opened to get more details on the composition of the top-level number.
![3 2a committee - disbursements](https://cloud.githubusercontent.com/assets/1696495/6953533/cb577dc2-d87e-11e4-91a3-52aaf0fe0aa2.png)

![3 2b committee - cash](https://cloud.githubusercontent.com/assets/1696495/6953535/ccb88198-d87e-11e4-854b-4984ca4e45f9.png)

Also a few comments on the updated header area to the page:
- I've also redesigned the header slightly, proposing we combine the Designation, Type and Org Type into a single line under the committee name, similar to how we talked about treating it in the filters and results tables. 
- Also in the header I made the committee ID less prominent, as most people don't really need it.

## 2. Filings

![3 2c committee - reports](https://cloud.githubusercontent.com/assets/1696495/6953559/fd43dd94-d87e-11e4-9233-72c6c9c0d7da.png)

- This table includes all filings made within the selected two-year period. 
- To view the filing in a particular way, the user clicks "view" which brings up the various options (PDF, CSV, etc.)
- On the right we can include links to whatever itemized data is included in the filing. That will be nothing for now, but once we have Schedule A, B, etc. up we can include links to those, allowing users to quickly click into the granular data. 
- I added the ability to filter the reports so that people can, say, hide 48 hour reports
- Instead of showing all amendments for a particular form, we just show the most recent, with all previous versions nested and hidden within it. The user can expand to view those older versions:
![3 2d committee - reports - open](https://cloud.githubusercontent.com/assets/1696495/6953612/527980e8-d87f-11e4-86ba-0817d5c12b70.png)

**Comment by rjmajma** [comment]
We've gotten to a good place with FEC on this. Further tweaks may need to be made (which @noahmanger can provide an update on). Next step is coding it up.
