### ISSUE TITLE
Fill out candidate page charts with quarters data

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#510]
Remove fake data for the charts and implement real data instead.
Implement api calls to quarterly endpoints.

Dependency:

**Comment by rjmajma** [comment]
Dependency: @arowla needs to implement the API for this.

**Comment by theresaanna** [comment]
I think @msecret may have done this?

cc: @rjmajma @leahbannon

**Comment by LindsayYoung** [comment]
Not yet, we are charting each report as a first step, and then we will aggregate by quarters to add consistency. That will require a new endpoint but we will format it the data the same, so the only change on the front end will be swapping out the url that function calls.
