### ISSUE TITLE
Update web app for unembedding-resources API refactor

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#511]
- Talk to Lindsay and Alison about new endpoint structure
- Rework api_caller.py in a way that makes sense with the changes

Dependency:
#503 #504

**Comment by arowla** [comment]
Related: #507

**Comment by arowla** [comment]
Took me a while to get accustomed to where everything is in the web app. Also experimenting with using Marshmallow for more powerful data munging between API input -> template variables. Not quite done, had to drop this for now to prioritize Cloud Foundry work.

**Comment by arowla** [comment]
This has highlighted the need for #639, the committee history/recent endpoint, since committees are showing up multiple times on the candidate pages. (For instance, Al Franken shows up with three primary committees, two of which have the exact same name but different FEC IDs.)

**Comment by arowla** [comment]
This is 99% done... The PR, 18F/openFEC-web-app/#104 is open for review.

**Comment by jmcarp** [comment]
:shipit:
