### ISSUE TITLE
Redesign search interaction

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#514]
**Goal:** Solve the confusion around how search works on the site by redesigning the search forms and search results. This will result in mocks, not implemented code.

**Comment by noahmanger** [comment]
Ok so here's what I'm thinking for this (Screens 18, 19, 20):

http://invis.io/CR2JSQFGM

It does a few things:

1. Remove the header search bar if you're on the home page
2. Default to just searching candidate names, but you can switch to committees
3. Candidate and committee results displayed similarly (still need to design committee results) with an emphasis on making them easier to scan and differentiate.
4. Sidebar elements that can lead the user to further exploration

Happy to talk more about my rationale, but I'd love to get this coded up sooner than later to actually see how people respond. 

Comments in InVision are preferable, but maybe drop a note in here to say you left comments.

**Comment by noahmanger** [comment]
So @LindsayYoung raised a good point on InVision and want to repost it here for further discussion: 

> I think we would need to improve our search to be able to show fewer results. (I we should probably improve or search anyway.) Even if it was improved, less results would be tricky for common names currently have 47 Smiths and 32 Millers etc., and that is with the year defaulting on. 

> I don't know if you were planning this for committees too, but the committees are even harder to do good search with because they all sound the same. The current default browse committees that shows them alphabetically by default is not that inviting to me. 

> We may be able to improve search, if we weighted the committees so that principal and authorized or weighted the search results or perhaps big fundraisers were weighted higher. I would like to hear what kind of weighting scheme users would like the most. 

> This looks great and is very informative. That might out weigh the above considerations.

**Comment by noahmanger** [comment]
I'd really like to open up with we need to do to make the search more intelligent. We definitely know that search is _the_ thing users need on this site. 

One strong assumption I have is that a generic search like "Miller" is probably unlikely. I think much more likely is people will search a full name if it's a common last name. I think the situation when we'd need to show 32 candidate results are probably pretty rare.

My less strong assumption is that this will also hold true for committees. I'd expect most searches to be for things like "Democratic congressional campaign" with the expectation that it would surface "Democratic Congressional Campaign Committee". 

Either way, I could see weighting by type, year active, etc. could help. 

But again, I don't know anything about search engineering. Is this something that Elasticsearch could help with? 

To reiterate, I think it's super important that we nail this.

**Comment by LindsayYoung** [comment]
User testing may prove me wrong, but I could imagine someone knows their congressman and searched for Rep. Miller or whatever, I think pagination is fine but the mock showed three results, which is a high bar. There are 45 different committees with Obama in their name. Though, perhaps people who search for committees will already know what they are doing. 

We can get better search without moving to elasticsearch. But we do need a strategy, like finding good matches and floating the big spending fish to the top. There are just a couple of words and a few qualities to distinguish the 67,876 committees we have in the default time range.

**Comment by noahmanger** [comment]
Word. Sorry, I should have specified that I don't expect to show three
results for everything, but instead to show _all_ results that match it.
And we can paginate if necessary.

On Fri, Mar 27, 2015 at 11:13 AM, Lindsay Young <notifications@github.com>
wrote:

> User testing may prove me wrong, but I could imagine someone knows their
> congressman and searched for Rep. Miller or whatever, I think pagination is
> fine but the mock showed three results, which is a high bar. There are 45
> different committees with Obama in their name. Though, perhaps people who
> search for committees will already know what they are doing.
>
> We can get better search without moving to elasticsearch. But we do need a
> strategy, like finding good matches and floating the big spending fish to
> the top. There are just a couple of words and a few qualities to
> distinguish the 67,876 committees we have in the default time range.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/514#issuecomment-87037762>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
That seems reasonable.

**Comment by noahmanger** [comment]
Nice. Curious what @theresaanna thinks about all this and then would be cool if we could code it up next sprint.

**Comment by noahmanger** [comment]
I updated this screen here: http://invis.io/AB2K3J9HY

![new search results](https://cloud.githubusercontent.com/assets/1696495/6906162/df9fc864-d6e1-11e4-8664-30382ba0e920.png)

**Comment by theresaanna** [comment]
I was waiting to evaluate implementation but then I realized...

No. This makes a whole ton more sense than what we have currently so it doesn't matter. I think its the way to go.

**Comment by noahmanger** [comment]
Coolio. I'm going to close this out then and we can tackle implementation next sprint.

**Comment by rjmajma** [comment]
Quick question: are the filters under more? Or are they still on the side?

**Comment by noahmanger** [comment]
There are no filters on this view. This is search results, not Browse.

On Mon, Mar 30, 2015 at 2:21 PM, Raphael Majma <notifications@github.com>
wrote:

> Quick question: are the filters under more? Or are they still on the side?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/514#issuecomment-87834669>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by rjmajma** [comment]
You're right. My bad!
