### ISSUE TITLE
Whitelist IPs for API access, including data.gov ones

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#518]
We need to restrict access to the API instances by whitelisting IPs. We should include data.gov addresses.

Per Kaitlin, we should do this in Python so that it works on Cloud Foundry and a note from her taken from Slack:

"depending on how flask interprets the headers, it may put the forwarded IP (the actual client) and the data.gov IP on the header
so you might need to investigate and make sure you're checking the right one"

**Comment by LindsayYoung** [comment]
- [ ] Add data.api.gov whitelist
 - [ ] Make sure it works
