### ISSUE TITLE
Thoughts on type/designation/org merging

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#519]
Hey @noahmanger Here are some ideas for making things slightly less confusing.

Jeff and Paul pointed to an existing FEC tool that seems less confusing-
( go to http://www.fec.gov/finance/disclosure/candcmte_info.shtml look under advanced search)

#### Here are the combined options- 
Users can check more than one. Looking at the site will make more sense.

 - Presidential
 - Senate
 - House
 - Political Party
 - Political Action Committee (PACs) (All)
 Nonconnected PACs (All)
 - Independent Expenditure-Only Committees ("Super PAC")
 - Political Committees with Non-Contribution Accounts
 - Leadership PACs
 - Lobbyist/Registrant PACs
Separate Segregated Funds (SSFs) (All)
 - Corporation
 - Corporation w/o Stock
 - Labor Organization
 - Membership Organization
 - Trade Association
 - Cooperative
Independent Expenditure (All)
 - Single Candidate Independent Expenditure Committee
 - Independent Expenditures by Person or Group (not a committee)
 - Independent Expenditures by "SuperPACs"
 - Independent Expenditures by Political Committees with Non-Contribution Accounts
 - Electioneering Communications
 - Joint Fundraising Committee
 - Convention / Host
 - Delegate
 - Communication Cost

I am also wondering if we could have the description in a merged fashion under "type"
So show designation, type, organization type and just don't include the nulls.

Examples:
```
Unauthorized, PAC, Labor Union
Principal Committee, Senate
Joint Committee, House
Delegate Committee, Authorized
```

(Just a thought, if this makes it more confusing ignore that last part.)

**Comment by noahmanger** [comment]
Yes! My mind was totally going here. I'm really interested in trying this. I think checkboxes that maybe show a limited set at first with just the most common but then you can expand to see more options. 

I love the idea of listing them all in the same column, too.

We'd want to think a little about how the logic works. Like, are these AND or OR relationships. I think it should be AND (show me Joint Committees for House, not Joint Committees OR House Committees) but we'll need to make that clear.

**Comment by noahmanger** [comment]
Nice problem solving on this today. The way we basically solved this in that meeting makes me feel super positive with how this will go.

**Comment by noahmanger** [comment]
Just remembered that we never implemented this. But it's definitely something we want to do for the launch, right?

**Comment by rjmajma** [comment]
I think it would be nice as a fast-follow. Maybe even something we can do next sprint.

**Comment by noahmanger** [comment]
Here's a couple concepts for this. Both of them consolidate the "Committee Type" and "Designations" dropdowns into a single fieldset, with an attempt at showing the most popular options (or what we suspect are the most popular options) by default with the rest of the options under "More" and with group labels. 

Option 1 still maintains a separate field for "Organization Type", adding some helper text. 
![flow 1](https://cloud.githubusercontent.com/assets/1696495/8295699/1b85e92e-18fc-11e5-8236-30c002a19630.png)

Option2 combines "Organization Type" with "Committee Type" and "Designation"
![flow 2](https://cloud.githubusercontent.com/assets/1696495/8295700/1b85ffd6-18fc-11e5-8308-772c2e2bc037.png)

**Comment by noahmanger** [comment]
I'd like quick thoughts on the team and then get feedback from FEC.

**Comment by noahmanger** [comment]
Quick clarification: The dropdowns would actually have checkboxes in them, like they do on the site now. I just forgot to put them there :)

**Comment by PaulClark2** [comment]
@noahmanger Thanks for putting this together.   Let's go with Option 2.   In the "Committee Type & Designation" list we can remove "Principle Campaign Committee" and "Authorized by a Candidate."  I think most people outside the FEC don't really care about this distinction.   When a user selects "Presidential," "House" or "Senate" we should return both PCC and Other Authorized (committee designations "P" and "A") committees.  

In the "More" list we probably need to make it clearer that "Separate Segregated Funds" are also PACs.

**Comment by noahmanger** [comment]
Ah that's a great idea to hide P and A. Is there a better label we can come up with for Separate Segregated Funds that also captures that they're PACs? Maybe something like: "Organization PACs" or "PACs Backed by Organizations"?

**Comment by noahmanger** [comment]
Ok here's one that breaks out Presidential, House and Senate under "Authorized Committees" and then puts the rest under "Other Committees", with SSFs nested under PACs:

![option 1](https://cloud.githubusercontent.com/assets/1696495/8367015/775da93a-1b4f-11e5-8468-1654799d3709.png)

Considering that list is so long, though, I also tried what it's like to break it out in a more logical way:

![option 2](https://cloud.githubusercontent.com/assets/1696495/8367023/8d732f2e-1b4f-11e5-9c4b-086aa0fdcd5b.png)

**Comment by LindsayYoung** [comment]
You don't want to use the title "Authorized Committees" for House, Senate and Presidential, because those types aren't necessarily candidate committees, they can be parties, PACs etc.

**Comment by PaulClark2** [comment]
"Authorized Committees" is probably fine.   We would not refer to a PAC or party committee as an authorized committee.  "Authorized" is a term we use internally to generically talk about both PCCs (committee types "H," "S," or "P" and committee designation "P,") and Other Authorized Committees (committee types "H," "S," or "P" and committee designation "A").  As you know, candidates are required to have a PCC and may have none, one or more than one other authorized committee.  See Form 1 Line 5(a) and 5(b).  http://www.fec.gov/pdf/forms/fecfrm1.pdf

If you don't want to use "Authorized Committees," we could use "Candidate Committees" instead.

**Comment by PaulClark2** [comment]
@noahmanger Again, let's go with Option #2.   The shorter lists make more sense to me.  I think nesting the SSFs under PAC makes it pretty clear SFFs are a variety of PAC.

**Comment by noahmanger** [comment]
So decided :hammer: . We'll obviously be testing this with users, but this sounds like a good plan. I'll make a separate ticket for the implementation.
