### ISSUE TITLE
Most recent .fec ID number for regular and senate filings

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#521]
This is a good idea for the APIf from the general FEC repo- issue 31. It would make it easier for heavy data users to keep an eye on new data, especially for knowing when Senate paper forms are processed. 

I am adding it here so we don't forget it, but it won't be useful until we have our data infrastructure squared away.

**Comment by saizai** [comment]
Would also be useful to have the first/last .fec #s by version. That's mostly static (except for ones being currently filed), but useful to have a canonical reference.

**Comment by saizai** [comment]
Also, it would be useful to have right now — I use Fech to iterate through individual .fec files, so I'd like to know what number I should stop at w/ a simple curl.

I hope that this is pretty trivial to implement; it's just a URL that outputs max(filing_number), which is eminently cacheable.

**Comment by dwillis** [comment]
In the interim, you can use the [NYT Campaign Finance API](http://developer.nytimes.com/docs/campaign_finance_api/#h2-electronic) to get a list of available IDs by date or form type.

**Comment by LindsayYoung** [comment]
I am consolidating the id issues, this is now being tracked in #1355
