### ISSUE TITLE
Add committee id and candidate id to full text search

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#524]
The original implementation was names, addresses and treasurers it should be names and ids but the ids aren't being found in the full text search.

**Comment by LindsayYoung** [comment]
Candidate id seems to be working but searching by committee id is not working

**Comment by jmcarp** [comment]
@LindsayYoung is this in reference to the `/names` endpoint / typeahead search? That endpoint uses `name_search_fulltext_mv`, which is only searching on candidate / committee names and not on IDs. The fulltext views for separate resources (`dimcand_fulltext_mv` and `dimcmte_fulltext_mv`) *do* include IDs as well. Is the desired behavior to add IDs to the typeahead search as well? I'll add if so.

**Comment by LindsayYoung** [comment]
Ok, the candidate id is working in the main search now!

I think this is good for now, I think we should keep those out of the name search unless users ask for it.

Thanks again, Josh!
