### ISSUE TITLE
Implement Collapsible Banner

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#529]
@noahmanger and I have discussed it and we think a banner will help set expectations with users for what the site is/does. We're borrowing the idea from openFOIA #647. 

The banner should be open when a user visits the site and can be collapsed. 

Suggested banner copy is:

**This site is in development. Tell us what you think!**

openFEC uses a snapshot of disclosure data taken in 2014. If you’re looking for current campaign finance data, please visit here [FEC link]. 

We're working hard to make openFEC a useful addition to the resources available at FEC.gov. Your feedback is important to us as we build this site. Email [X] and let us know how it’s working for you.

**Comment by rjmajma** [comment]
For reference, here's how it looks on openFOIA:


![](https://cloud.githubusercontent.com/assets/5911280/6738160/5c8ea8ee-ce2d-11e4-8ef6-ce734b1e4803.png)

**Comment by rjmajma** [comment]
Spoke with folks at the FEC and they're onboard with the language we've proposed.

**Comment by noahmanger** [comment]
Ok, this is mostly coded, but still need to devise a way to track the state so when you close it it stays closed across pages. 

What behavior do we want this to have? I think it should stay closed until someone leaves the site, but when they come back it's back there.

![screen shot 2015-04-08 at 5 40 13 pm](https://cloud.githubusercontent.com/assets/1696495/7058431/9d949846-de16-11e4-8d66-0f7ba2672349.png)

**Comment by LindsayYoung** [comment]
I think it should expand every time they come back to the site. It will be a little annoying but better to be explicit about it.

**Comment by rjmajma** [comment]
Agreed. It should be open every time you visit the site. Once you close it, it should stay closed for as long as you're on the site. That behavior should at least be persistent.
