### ISSUE TITLE
Duplicated / inconsistent data in join table

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#543]
The `CandidateCommitteeLink` join table includes (non-primary) fields that are also included in the `Candidate` and `Committee` tables: `committee_name`, `candidate_name`, `committee_type`, etc. Ideally there would be one source of truth for these fields, and the join table would only include primary keys and fields that don't belong on either `Candidate` or `Committee`.

At least for the data in the pgdump, some of these fields are also inconsistent between tables--for example, some committees have different values for `committee_type` on the `Committee` and `CandidateCommitteeLink` tables:

```
cfdm_test=# select cm.committee_type, ln.committee_type from ofec_committees_mv cm join ofec_name_linkage_mv ln using (committee_key) where cm.committee_type is not null and cm.committee_type != ln.committee_type;
 committee_type | committee_type
----------------+----------------
 Y              | Q
 H              | S
 H              | S
 H              | S
 H              | S
...
```

Based on the import scripts, I'm guessing the `cmte_tp` values from the original data aren't always consistent between `dimlinkages` and `dimcmte`. It might be helpful to check for this kind of inconsistency in the production database (not sure where that lives), and figure out which data to trust in case of conflicts.

**Comment by LindsayYoung** [comment]
Where there were more than one place to get the same data, like incumbency status, I asked the FEC which field would be more reliable and went with that table.

**Comment by jmcarp** [comment]
Thanks! In that case, I think it would be clearer to only import the columns we're actually going to be using in the views scripts. For example, we might delete either https://github.com/18F/openFEC/blob/master/data/sql_updates/create_committees_vw.sql#L15-L33 or https://github.com/18F/openFEC/blob/master/data/sql_updates/create_linkage_names_vw.sql#L11-L29, depending on which version of `committee_type` is more reliable. Based on the code in `resources`, it looks like only the `committee_type` on `Committee` is used, so I would guess we should delete the `committee_type` on the join table.

Also, any chance the FEC has documented this kind of issue? Would be helpful to include something in the docs about it, or include correspondence with them if that's allowed.

**Comment by LindsayYoung** [comment]
Don't take that out yet, it might be useful later. We should also double check if there is a real problem. There are two things to be aware of Committee types and designations can change over time. Changes like N to Q would be a very normal progression, after a PAC turns in their qualifying paperwork and meet the requirements. Also, test data is good enough most of the time, but I wouldn't  use it to make data decisions.

**Comment by jmcarp** [comment]
:+1:

**Comment by jmcarp** [comment]
Closing for now--as @LindsayYoung pointed out, we're using the columns recommended by FEC.
