### ISSUE TITLE
CF Database Migrations

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#547]
The DB migrations need a standard way of being done, preferably not totally manually via someone using `cf-ssh` as I've done now. Figure out the best way to do this reliably on future deploys.

**Comment by arowla** [comment]
The `refresh_db` command does double-duty as a data refresh and as a schema change command. The primary thing we need to figure out is the best way to run this command on our Cloud Foundry instances in response to schema changes. So there are two possibilities:

1. run whenever something in the `/data/sql_updates` directory changes;
2. or in conjunction with every code deploy (`cf push`).

(In the future, we'll also need to run this command nightly to keep the data up to date, which is something to consider, but that shouldn't be part of this task.)

You can refer to the [CF migration docs](http://docs.cloudfoundry.org/devguide/services/migrate-db.html), the catch being that our `refresh_db` command almost certainly takes longer than their minute-long timeout allowed by default for application startup under `cf push`. I am not certain whether it can fit within the maximum three minutes, or whether we can expect it to as we start to receive more data from the client.

**Comment by arowla** [comment]
Also, in case it matters for this task at all, we are not using a CF "service" to host the databases, but rather a standalone AWS RDS instance located within the CF VPC.

**Comment by jmcarp** [comment]
Can this be closed @arowla?
