### ISSUE TITLE
Implement new committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#548]
**Goal:** Code these mockups into new committee pages: 

![3 2 committee](https://cloud.githubusercontent.com/assets/1696495/7054206/e0f90512-ddef-11e4-8aab-7b35c031bc03.png)

![3 2a committee - disbursements](https://cloud.githubusercontent.com/assets/1696495/7054239/14a216c4-ddf0-11e4-8bb1-0732b84f42f0.png)
![3 2b committee - cash](https://cloud.githubusercontent.com/assets/1696495/7054240/14b37766-ddf0-11e4-94d9-4f389e12e5f4.png)
![3 2c committee - reports](https://cloud.githubusercontent.com/assets/1696495/7054241/14b5ead2-ddf0-11e4-9dca-58300f80b3ce.png)
![3 2d committee - reports - open](https://cloud.githubusercontent.com/assets/1696495/7054242/14b7206e-ddf0-11e4-8415-c90fbcb296ca.png)

**Comment by arowla** [comment]
Let me and @LindsayYoung know if this requires anything not already in the existing committee endpoints.

**Comment by rjmajma** [comment]
Implementation up to the two-year summary tab. We shouldn't include the Filings tab stuff.
