### ISSUE TITLE
Conduct Browser Testing

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#549]
Conduct browser testing to see how openFEC degrades across older browsers. Come up with a plan, if necessary, to fix on older versions. 

May be worth getting it set up and ready to go.

**Comment by msecret** [comment]
Plan to use https://github.com/18F/automated-testing-playbook to set up testing.

**Comment by msecret** [comment]
Bug, minor: text in search input boxes is too low

![screen shot 2015-04-29 at 4 25 43 pm](https://cloud.githubusercontent.com/assets/1701077/7403830/dac42320-ee8e-11e4-9049-af91318a8aae.png)
![screen shot 2015-04-29 at 4 25 57 pm](https://cloud.githubusercontent.com/assets/1701077/7403831/dad8dcb6-ee8e-11e4-9884-187f0ca53a0f.png)

**Comment by msecret** [comment]
Bug, medium: linked images have white borders around them

![screen shot 2015-04-29 at 4 45 02 pm](https://cloud.githubusercontent.com/assets/1701077/7403840/0104fcb2-ee8f-11e4-9ca5-a856b2b0b091.png)

**Comment by msecret** [comment]
Bug, minor, IE10: no padding on beta bar.

![screen shot 2015-04-29 at 4 48 01 pm](https://cloud.githubusercontent.com/assets/1701077/7403862/7b0e257e-ee8f-11e4-9c8f-6b7a1ae759fc.png)

**Comment by msecret** [comment]
Fixed with https://github.com/18F/openFEC-web-app/pull/123
