### ISSUE TITLE
Device Testing

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#550]
Test openFEC across devices to determine where there are responsive design issues.

**Comment by LindsayYoung** [comment]
Wei also mentioned that they are mostly on the iphone 5.

**Comment by msecret** [comment]
The beta panel is very large on mobile, taking up too large a portion of the screen

![screen shot 2015-05-04 at 4 22 27 pm](https://cloud.githubusercontent.com/assets/1701077/7464671/b8a7ab42-f279-11e4-9693-e0c3c2d28f98.png)

**Comment by msecret** [comment]
The sticky header sticks at the wrong point on mobile

The header starts to stick in the middle of the gray section with basic candidate/committee information. On the desktop app, the header sticks when the top of the window meets the top of year filter section.

![screen shot 2015-05-04 at 4 23 43 pm](https://cloud.githubusercontent.com/assets/1701077/7464687/f8157ad4-f279-11e4-85e9-3b32b95e51b2.png)

**Comment by msecret** [comment]
Mobile breakpoint has two links in footer with very little padding

![screen shot 2015-05-04 at 4 29 47 pm](https://cloud.githubusercontent.com/assets/1701077/7464762/b0c5e7e4-f27a-11e4-819a-9ab02323294b.png)

**Comment by msecret** [comment]
Committee charts on mobile breakpoint have very hard layout

The Y-axis label is too large horizontally, which is pushing the whole chart too far to the left, creating a very narrow chart.

![screen shot 2015-05-04 at 4 30 22 pm](https://cloud.githubusercontent.com/assets/1701077/7464783/e3c73d1e-f27a-11e4-96ec-436ca85cd138.png)

**Comment by msecret** [comment]
Accordion icons are off-center on mobile breakpoint

![screen shot 2015-05-04 at 4 32 26 pm](https://cloud.githubusercontent.com/assets/1701077/7464810/11b7093e-f27b-11e4-9daa-66d42b37a24e.png)

**Comment by msecret** [comment]
Filter's sticky header on browser page on mobile breakpoint "sticks" at wrong point

The filter's sticky header sticks before the top of the screen reaches the actual filters section, creating a jarring transition

![screen shot 2015-05-04 at 4 34 42 pm](https://cloud.githubusercontent.com/assets/1701077/7464838/5b8c03e8-f27b-11e4-9120-d8726c74943b.png)

**Comment by msecret** [comment]
On browser page, on mobile breakpoint, filters overlap stick header

![screen shot 2015-05-04 at 4 35 38 pm](https://cloud.githubusercontent.com/assets/1701077/7464845/7c988e62-f27b-11e4-97a6-f07116a741c2.png)

**Comment by msecret** [comment]
Browse table not 100% on mobile breakpoint and does not have enough space

![screen shot 2015-05-04 at 4 35 59 pm](https://cloud.githubusercontent.com/assets/1701077/7464850/96896788-f27b-11e4-8aba-1842dc5ac864.png)

**Comment by msecret** [comment]
Search results page table doesn't have enough room on mobile breakpoint

![screen shot 2015-05-04 at 4 37 27 pm](https://cloud.githubusercontent.com/assets/1701077/7464865/c64dcc20-f27b-11e4-89aa-78ccc65eaafd.png)

**Comment by msecret** [comment]
View all button is overlapped on mobile breakpoint 

![screen shot 2015-05-04 at 4 37 27 pm](https://cloud.githubusercontent.com/assets/1701077/7464869/d1dcdbd0-f27b-11e4-9913-f40a759432c3.png)

**Comment by noahmanger** [comment]
This is helpful, thanks. 

The issue with charts is already captured here: https://github.com/18F/openFEC/issues/658 (see my last comment there for an idea on a simple temporary fix)

The filters / browse table stuff is addressed here: https://github.com/18F/openFEC-web-app/pull/116

But I don't think that addresses the search results page.

**Comment by noahmanger** [comment]
Ok, here's what I see as the remaining issues:
- Footer links: created separate issue (#712)
- Accordion icons: created separate issue (#713)
- Alpha banner: I think we should leave this as is, because it's really important for people to see this.
- Sticky nav: I'm inclined to just remove the sticky nav entirely for now as it's not adding much value at any screen size.
