### ISSUE TITLE
Implement New Relic or other error monitoring tool

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#555]

**Comment by LindsayYoung** [comment]
- [ ] Research what other projects are using 
 - [ ] Implement solution API
 - [ ] Implement solution web app

**Comment by LindsayYoung** [comment]
Options:
- New Relic, there is 18F-wide license
- logstash, it's open source, peace corps is using this

**Comment by LindsayYoung** [comment]
I think we should go with New Relic, that seems simplest to me.

**Comment by arowla** [comment]
+1

**Comment by LindsayYoung** [comment]
I got New Relic reporting data about the API on the test space in cloudfoundry. Though, the app is not really working there. I think I am having cloudfoundry problems and not new relic problems.

**Comment by LindsayYoung** [comment]
I got info from both apps running in the test space. I will increase the security settings tomorrow.

**Comment by LindsayYoung** [comment]
I got them to both run on test. The high security setting is on. We will need to confirm that this is working in production when we have a working production. But this is taken care of in pr #570
