### ISSUE TITLE
Design responsive screens

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#556]
**Goal:** Design smaller screen sizes for separate page views and comp a general responsive styleguide. 

**Tasks**:
- [x] Typography
- [x] Home page
- [x] Search results
- [x] Candidate page
- [x] Committee page
- [x] Browse page

**Comment by noahmanger** [comment]
Ok, making progress on this. First, here's a first swipe at adjusting the font-sizes for the different headings as part of a modified type system for smaller screens:

![mobile typography](https://cloud.githubusercontent.com/assets/1696495/7139081/53a0b5b4-e292-11e4-9b2c-1a8fe435f329.png)

And here's a small and medium sized version of the home page:
![home - medium](https://cloud.githubusercontent.com/assets/1696495/7139091/6095afd6-e292-11e4-9173-10731549c7d4.png)
![home - small](https://cloud.githubusercontent.com/assets/1696495/7139090/6094db38-e292-11e4-9408-8fd579e0b15a.png)

Tapping the menu icon brings up a full screen menu with the search field:
![site nav - small](https://cloud.githubusercontent.com/assets/1696495/7139106/72eb67ca-e292-11e4-8447-66a619abfcf7.png)

And here's the glossary, which works the same way:
![glossary - small](https://cloud.githubusercontent.com/assets/1696495/7139120/83002696-e292-11e4-8310-16bdfab1995d.png)

More coming in the next comment...

**Comment by noahmanger** [comment]
So for the filter view, I think it should default to a list view, with expandable details:
![filters - small](https://cloud.githubusercontent.com/assets/1696495/7139162/b2bba48c-e292-11e4-92af-f75e04cc7db2.png)

But in the filter menu you can toggle to a table view:
![filters - small - open](https://cloud.githubusercontent.com/assets/1696495/7139172/c03418a6-e292-11e4-83d7-b79d52808d90.png)

With the table view, the first column is fixed, and the other columns scroll underneath it:
![filters - small - table](https://cloud.githubusercontent.com/assets/1696495/7139179/c3d1dfa2-e292-11e4-974d-535bdc27a5e7.png)

**Comment by msecret** [comment]
Everything looks pretty good and straight-forward to implement. The highest risk item would be the responsive table, as the fixed first column might be hard to create. We should do quick experimentation to see how feasible that would be, or maybe you've seen an actual example somewhere.

Here are some questions that came up as I looked at these. They probably don't need to be addressed with wireframes/designs, but things we should have in our minds while implementing.
- What does the little man icon on the search bar expand to? It would be good to know how that expands on mobile.
- In search, what happens when candidate/committee name being searched for is wider then screen?
- Will search suggestions appear below search bar in mobile view, same as desktop?
  If so
  - What if names are wider then screen width?
  - What amount of names means the suggestions go below bottom of screen?
- On the filters tab, what if one of the items in a select dropdown is wider then the select box? Does is move to next line?
- For the responsive table, it's hard to get a sense of how it will transform at different screen sizes, but I'm guessing we could get it done similar to this: https://css-tricks.com/examples/ResponsiveTables/responsive.php. Although if that first column is "absolute" it might be a little tough to do with a table. I'm hoping we don't have to mess with the html.
- The "+" icons when browsing candidates stuck out to me a little. They gave me the impression that I was "adding" them to a filter rather then expanding. I think it's important that we test with users.

**Comment by noahmanger** [comment]
Great feedback, @msecret . Thanks. Here's some thoughts:

- Re: responsive table, I've seen this done before and know that there's libraries for it. [Here's an example](http://zurb.com/playground/playground/responsive-tables/index.html)
- The candidate icon is meant to signify that it is searching candidates (on wider displays, it will say "candidates"). But the dropdown options should contain the words.
- The way I've been handling long names is by truncating with `text-overflow: ellipsis`. I think we should try this to avoid line wrapping in the search suggestions. 
- Re: the number of suggestions pushing it to the bottom of the screen, that's a good call and think we should actually therefore move it to the top like so: 
![site nav - small](https://cloud.githubusercontent.com/assets/1696495/7186491/257268f2-e438-11e4-8f4b-c38fda57a3ae.png)
- Let's try out different options regarding select dropdown line breaks. Might be ok to cut it off but might need multiple lines.
- Last, for the "+" icons, I was exploring using this as the icon for disclosure / "show more" (and then converts to a "-" to hide something). Part of me finds this clearer than the typical caret icons, which I can never tell which direction (up or down) means which. But I definitely want to see how people respond.

**Comment by noahmanger** [comment]
Oh, and for the responsive table, I agree. That's part of why I like the idea of being able to toggle between list view and table view, but agree that we'll want to do a lot of exploration on this.

**Comment by noahmanger** [comment]
Ok, here's search results. 

For reference, here's the large view:
![new search results](https://cloud.githubusercontent.com/assets/1696495/7188987/b6e3b956-e449-11e4-8621-af056f658c6b.png)

I think we default to just showing the "Candidate name includes" field in the search options box, but you can expand to view the other options.

![search results - small](https://cloud.githubusercontent.com/assets/1696495/7188978/a2fc40ac-e449-11e4-82ac-fe0d9346b7bf.png)
![search results - small - search options](https://cloud.githubusercontent.com/assets/1696495/7188981/a5abd060-e449-11e4-9c3b-75e2b18c4811.png)

Putting the sidebar boxes at the bottom, I think there needs to be more of a visual distinction between them and the search results, which is why I put the blue gray background as a full bleed behind the boxes. Not sure if we'll keep this or not. Need to see how things feel.

**Comment by noahmanger** [comment]
Couple other notes: Still playing with the disclosure patterns. This option with the advanced options box is kind of novel. I could see other ways too, but we don't need to trouble shoot exactly. All that reallly matters is having a button that expands and collapses additional info.

**Comment by noahmanger** [comment]
## Candidate page
![candidate - small](https://cloud.githubusercontent.com/assets/1696495/7191848/84ac9d08-e45e-11e4-8f73-0dc031e2fc2b.png)

A note on the tabs (currently there's no tabs on the candidate page, but there will be eventually, so put them here): I tried a couple methods on this and this seems to work. Basically we only show the active tab, but have a dropdown select for "more" that gives the other tab options. I can talk more through how this looks.

Here's the charts open (I just showed the first chart, but it should include both). Shawn suggested rotating the charts 90 degrees, and I like how this works, but not sure if this is a huge pain code wise.

![candidate - small charts open](https://cloud.githubusercontent.com/assets/1696495/7191893/fac17ac2-e45e-11e4-8c50-eb9398360bb8.png)

## Committee Page
Very similar idea here. The header is a little bit more of a problem because of the content in it. I might revisit this idea later. Again, just showing one chart on the mock, but it should have both. I'm going to tackle the filing table later after we figure out how we're doing responsive tables.

![committee - small - two year summary](https://cloud.githubusercontent.com/assets/1696495/7191915/397f932a-e45f-11e4-9ea7-de8f1e5d7073.png)

**Comment by noahmanger** [comment]
@msecret when you get a chance today let me know if you see anything worrisome here. Otherwise I'll close this issue and we can figure out how we're going to tackle coding it.
