### ISSUE TITLE
Finalize Production Workflow

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#558]

**Comment by arowla** [comment]
Also see #553

**Comment by arowla** [comment]
I have our current production workflow outlined in this doc here:

https://docs.google.com/a/gsa.gov/document/d/14PcnqVyxCsJ9GkrF88IydPp4TE5gSdgew-6cHLrW350/edit

There are a couple of outstanding questions, but we will deal with them as needed.

**Comment by arowla** [comment]
We still need to set up auto-deploys and get everyone switched over to the gitflow workflow. I think there is a ticket for the former out there that belonged to @theresaanna . But the basic CF instances and the conceptual framework is in place.
