### ISSUE TITLE
Empty committee result set that should be filled

### ISSUE THREAD

**Issue by msecret** [18F/openFEC#565]
A committee is returning both totals and reports but the actual committee is returning empty.

Reproduction:
On both my localhost database, and on staging site:
`GET /committee/C00000422/reports` returns a full result set
`GET /committee/C00000422/totals` returns a full result set
`GET /committee/C00000422` returns an empty result set.

Expected:
I would expect `GET /committee/C00000422` to return a full result set with committee information such as name, etc.

May potentially be blocking me from completing #560 as I will need the correct data for it.

**Comment by LindsayYoung** [comment]
The migrations are not up to date on that server. Either we can run them or, ideally we will have a working cloudfoundry instance.  I will ping @arowla on Monday and see how close she is to having cf set up. If not, we can run the migrations. 

Sorry for the inconvenience Marco. I will get back to you when this is fixed.

**Comment by LindsayYoung** [comment]
Just read you are on test data, I can find/make you an example on Monday. I can do that first thing.
