### ISSUE TITLE
DAP integration

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#573]
Add the google government-wide analytics.

**Comment by konklone** [comment]
The way this is currently handled on 18f.gsa.gov, and several other 18F-managed projects, is to use this snippet:

```html
<script id="_fed_an_ua_tag" src="https://analytics.usa.gov/dap/dap.min.js"></script>
```

That's all it takes. However, it is a non-final URL, and only suitable for 18F-managed projects as a temporary measure. The DAP is in the process of finalizing a centralized snippet at a separate domain and URL (`dap.digitalgov.gov`) and when that goes live, it's what you should use.

**Comment by msecret** [comment]
@konklone , is there a requirement that this script be placed at the top of the page, or can it be placed at the bottom or load asynchronously with the "async" attribute?

**Comment by konklone** [comment]
I believe it's the integrator's choice -- if you find that your preferred approach doesn't work, https://github.com/GSA/DAP-Gov-wide-GA-Code might be a good place to post it.

**Comment by leahbannon** [comment]
closing in favor of https://github.com/18F/openFEC-web-app/issues/373 which has more recent code link
