### ISSUE TITLE
Add team chat integrations

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#587]
We need PR notifications, et al in the channel.

**Comment by msecret** [comment]
I've asked Ozzy to do this.

Currently we are receiving notifications for new PRs. We could also add notifications for other things such as:
- New issues
- Comments or updates to a PR

If anybody would like anything else, please inform Ozzy or I and we can close this out.

**Comment by LindsayYoung** [comment]
I like it the way it is now. Thanks for setting this up!

**Comment by arowla** [comment]
Thanks!
