### ISSUE TITLE
Manual QA Test Pages on Production Instance

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#592]
The FEC Team and 18F team will each do manual tests on the production instance. We'll note any thing that doesn't work as the user would expect it to.

The 18F team may identify some selenium tests that would be worth running as a separate ticket.

**Comment by LindsayYoung** [comment]
Dependency is getting the committee and candidate pages in a final-ish state.

**Comment by LindsayYoung** [comment]
So far this has resulted in issues:
#620 #621 #623
