### ISSUE TITLE
SSL and Domains Sorted Out

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#596]

**Comment by arowla** [comment]
- [ ] open.fec.gov pointed to production CF web app
- [ ] SSL set up ^^
- [ ] api.open.fec.gov pointed to api.data.gov
- [ ] SSL set up ^^

**Comment by arowla** [comment]
@dlapiduz and Nick M. (whose github handle is not autocompleting) are creating an ELB at api.data.gov for us as we speak, and are coordinating on getting the certificate uploaded to it.

**Comment by dlapiduz** [comment]
https://api.open.fec.gov/ looks good to me now.

**Comment by arowla** [comment]
BAM!

**Comment by arowla** [comment]
Missed one problem with running CF under the new host name. Reopening until that is fixed.

**Comment by dlapiduz** [comment]
@arowla what is the problem?

**Comment by rjmajma** [comment]
Hey @arowla, was this cleared up?
