### ISSUE TITLE
Committee addresses missing their state

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#615]
Clicking around on the web app and found that a number of committees are missing the state from their address.

![](https://files.slack.com/files-pri/T03QPNR5D-F04J9NR3E/screen_shot_2015-04-27_at_12.33.14_pm.png)

![screen shot 2015-04-27 at 12 36 25 pm](https://cloud.githubusercontent.com/assets/3649037/7352504/094ace62-ecda-11e4-9492-713795de08ac.png)

**Comment by LindsayYoung** [comment]
I see state in the API:
https://api.open.fec.gov/committee/C00548776?api_key=xxx

**Comment by arowla** [comment]
I'm pretty sure I fixed this bug in the (WIP) unnesting frontend task.

On Mon, Apr 27, 2015 at 1:50 PM, Lindsay Young <notifications@github.com>
wrote:

> I see state in the API:
> https://api.open.fec.gov/committee/C00548776?api_key=xxx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/615#issuecomment-96756820>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by rjmajma** [comment]
:+1:

**Comment by arowla** [comment]
This is fixed in 18F/openFEC-web-app/#104
