### ISSUE TITLE
Search results count number should be human readable

### ISSUE THREAD

**Issue by khandelwal** [18F/openFEC#617]
Putting commas in the number of search results would make it easier to read. 

![screen shot 2015-04-27 at 12 37 07 pm](https://cloud.githubusercontent.com/assets/636752/7352600/af5ed6ae-ecda-11e4-9a09-66c132dda73d.png)

**Comment by noahmanger** [comment]
+1.

**Comment by jmcarp** [comment]
Added in https://github.com/18F/openFEC-web-app/pull/220.
