### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by khandelwal** [18F/openFEC#618]
The fields being empty is confusing. Is the data missing? Or is that an error in the app I'm using?

![screen shot 2015-04-27 at 12 32 07 pm](https://cloud.githubusercontent.com/assets/636752/7352616/d3d5b7b4-ecda-11e4-8eb5-d08bbaab8ae7.png)

**Comment by LindsayYoung** [comment]
We don't have any reports for him. 
https://api.open.fec.gov/committee/C00168492?api_key=xxx
https://api.open.fec.gov/committee/C00168492/reports?api_key=xxx
https://api.open.fec.gov/committee/C00168492/totals?api_key=xxx

**Comment by khandelwal** [comment]
Right. However, what's more important here is to display that fact to the user. It being empty as displayed above leads to confusion.

Maybe put 'No Data Available' in the right places?

**Comment by LindsayYoung** [comment]
Agreed, I was trying to confirm that it was not a data error, since we have a few bugs like that, which I am trying to hunt now.

This guy in particular has only filed a pre-convention report and right now, we are only showing data from "F3s"

**Comment by noahmanger** [comment]
So is it possible for us to show the "No Data Available" message?

On Mon, Apr 27, 2015 at 12:09 PM, Lindsay Young <notifications@github.com>
wrote:

> Agreed, I was trying to confirm that it was not a data error, since we
> have a few bugs like that, which I am trying to hunt now.
>
> This guy in particular has only filed a pre-convention report and right
> now, we are only showing data from "F3s"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/618#issuecomment-96783031>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
I think this is actually brings up a larger issue too, I would like it if the "browse" candidates or committee views with no filters should return something more interesting than the A's of the alphabet. 

Maybe we could the browse view ordered by the top 100 spenders for the cycle or something interesting? That would make it less likely for people to stumble on random outliers.

This is not necessary for launch, but I think it would be nice.

**Comment by LindsayYoung** [comment]
I think we could triggered a no results template when `results=[]` but, I spend less time on the front so it might be more complicated than that for some reason.

**Comment by noahmanger** [comment]
+1 to having a better set of candidates that show up initially on Browse.

We do have a "No Results" message that shows up in certain situations like
this: /candidate/H4UT04052

Shouldn't this be showing in Shashank's example as well?

On Mon, Apr 27, 2015 at 12:19 PM, Lindsay Young <notifications@github.com>
wrote:

> I think we could triggered a no results template when results=[] but, I
> spend less time on the front so it might be more complicated than that for
> some reason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/618#issuecomment-96785704>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
In the case of AAlders, we have no committees associated with him. Perhaps that is the difference?

**Comment by noahmanger** [comment]
Oh yeah. I'll file an issue for this.

On Mon, Apr 27, 2015 at 12:30 PM, Lindsay Young <notifications@github.com>
wrote:

> In the case of AAlders, we have no committees associated with him. Perhaps
> that is the difference?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/618#issuecomment-96789305>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
This should have data and doesn't
Webiste candidate page broken:
http://open.fec.gov/candidate/H0IL01087

Website committee page working:
http://open.fec.gov/committee/C00347583

API for reports working:
http://api.open.fec.gov/committee/C00347583/reports?api_key=xxx
API for totals working:
http://api.open.fec.gov/committee/totals/reports?api_key=xxx

**Comment by arowla** [comment]
We should still check what's going on here, but the original example has a straightforward "No Financial Data" box showing on it now.

**Comment by LindsayYoung** [comment]
I think this bug occurs when election_years=0
example:
https://api.open.fec.gov/v1/candidate/H0IL01087?api_key=xxx

I will try and fix that now.

**Comment by LindsayYoung** [comment]
Remaining work is documented in #657
