### ISSUE TITLE
Force HTTPS by default

### ISSUE THREAD

**Issue by seanherron** [18F/openFEC#619]
Dependent on https://trello.com/c/mKH3vlfk/34-add-hsts-and-redirect-http-https-in-gorouter

**Comment by dlapiduz** [comment]
You can use [djangosecure](https://pypi.python.org/pypi/django-secure) like Foia: https://github.com/18F/foia-hub/blob/master/foia_hub/settings/production.py#L15.

We are not doing the router stuff for a few weeks at least.

**Comment by LindsayYoung** [comment]
Ok, we are using flask so maybe something like this -
https://github.com/kennethreitz/flask-sslify
