### ISSUE TITLE
Committee start date issue

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#624]
One of the things I am looping back on now is using the `committee_origination_ date` in `create_committee_view.sql` and `create_committe_view` we are using the most recent load date, when we would want the oldest load date for that committee in dimcmteproperties. `` and start date of the committee.

In theory, they should be giving us the `committee_origination_ date` in `dimcmteproperties` now. Is this something you can see in Golden Gate @jmcarp? (The older version of the data we got from the vpn had that column with nothing populated so we were calculating it ourselves.)

If we keep using the wrong origination date, the result filtering by year will be incorrect.

**Comment by jmcarp** [comment]
There's a `orig_registration_dt` column in `dimcmteproperties`, but it's empty for almost every row. I don't see a column called `committee_origination_date`. Will check other columns / tables for something similar.

**Comment by LindsayYoung** [comment]
You found the right name. I thought they fixed that. I will email FEC to follow up.

**Comment by LindsayYoung** [comment]
This is being merged to #649
