### ISSUE TITLE
Sorting not really supported

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#625]
On the committee and candidate list tables we have in-browser sorting but that doesn't really sort all the results most of the time, there are results being paginated in the API.

I propose we disable the sorting feature until we complete #176 (or a new issue that accounts for making the API sortable by categories of the user's choice)

**Comment by rjmajma** [comment]
I agree with this. We've heard about it more than once and the user expectation of what the sort will do never lives up to it's functionality.

**Comment by noahmanger** [comment]
Good call. I'll disable it.

On Mon, Apr 27, 2015 at 6:13 PM, Raphael Majma <notifications@github.com>
wrote:

> I agree with this. We've heard about it more than once and the user
> expectation of what the sort will do never lives up to it's functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/625#issuecomment-96836569>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
