### ISSUE TITLE
Show which years are applied on browse pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#626]
If we're applying a year filter to the Browse Candidate and Browse Committee pages, we need to show that on the filter screen.

**Comment by LindsayYoung** [comment]
Committee year filtering is on the fritz #649

**Comment by noahmanger** [comment]
What's the status on this? Can we tackle it yet?

**Comment by LindsayYoung** [comment]
Go ahead and go for it. We coded around the data quality issues. We start off on the browse page looking at the last four years. 

You probably want to tackle #671 at the same time.
