### ISSUE TITLE
Inconsistent charting

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#627]
On Obama, the charts on the candidate and committee pages are only showing the last report (I think) when they should be showing the last 4.

And the cash and debt chart on Obama isn't working.

![screen shot 2015-04-27 at 10 22 21 pm](https://cloud.githubusercontent.com/assets/1696495/7361730/ecb8f3e4-ed2b-11e4-8f9a-4fec7384723e.png)

On Pelosi's candidate and committee pages though they work fine:

![screen shot 2015-04-27 at 10 24 10 pm](https://cloud.githubusercontent.com/assets/1696495/7361743/343d6bb4-ed2c-11e4-9052-b1debc339e1f.png)

But her cash and debt one on the candidate page isn't working.
![screen shot 2015-04-27 at 10 23 09 pm](https://cloud.githubusercontent.com/assets/1696495/7361746/3964283a-ed2c-11e4-842d-a33ca7592f43.png)

**Comment by LindsayYoung** [comment]
Cash and Debt not showing up is issue #621

**Comment by LindsayYoung** [comment]
I think the problem with the chart is that we don't have the whole page playing by the same date rules  when we implement the undying logic of the dropdown menu in issue #323

**Comment by LindsayYoung** [comment]
Another problem with the reports that is making their display wrong- #631

**Comment by LindsayYoung** [comment]
made a pr for #631
