### ISSUE TITLE
Duplicate related candidates on committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#628]
Pelosi's campaign commitee (/committee/C00213512) shows her listed a bunch of times. She should only show up once.

![screen shot 2015-04-27 at 10 23 40 pm](https://cloud.githubusercontent.com/assets/1696495/7361768/7708759c-ed2c-11e4-93b0-b512fb7bd5be.png)

Obama for America shows Barack Obama twice as well.

**Comment by LindsayYoung** [comment]
This will be fixed with the refactor. How about we deal with it on the web app side for now? I will make a pr

**Comment by LindsayYoung** [comment]
that is pr #91 on the webapp side [https://github.com/18F/openFEC-web-app/pull/91](https://github.com/18F/openFEC-web-app/pull/91)

**Comment by LindsayYoung** [comment]
I looks right, so I am closing this issue. The data will be updated with the API un-nesting refactor #516
