### ISSUE TITLE
Fix cash on hand and debt 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#637]
The cash on hand and debt that is showing in committee box of the candidate page needs to pull from the most recent report. Right now, it is showing the data from the earliest report on the chart. 

Example:
`/candidate/H8CA05035`
![screen shot 2015-04-28 at 12 11 00 pm](https://cloud.githubusercontent.com/assets/4406333/7374333/a72711f2-ed9f-11e4-80f3-e37bad6d1024.png)

**Comment by jmcarp** [comment]
Looking into this @LindsayYoung. It looks like the web app makes a separate reports request for each committee, and overwrites the data from previous committees on each iteration.

**Comment by jmcarp** [comment]
Could this have been fixed by #632? As far as I can tell, responses from production are correct now.

**Comment by LindsayYoung** [comment]
You are right this is fine! 

The chart reads in the opposite direction, from what I expected, I was looking at the wrong thing.
