### ISSUE TITLE
Pagination returning inconsistent record count for committees

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#638]
When I browse committee records, the page says that records 1-20 are being displayed, but fewer than 20 records appear on the screen:

![screen shot 2015-04-28 at 2 21 01 pm](https://cloud.githubusercontent.com/assets/10507124/7377036/e0ac407a-edb1-11e4-99fe-c2323e4992e6.png)

When I select "Next 20", the next set of records is pulled up, which also has fewer than 20 records, but a different row count than the first set of data:

![screen shot 2015-04-28 at 2 24 22 pm](https://cloud.githubusercontent.com/assets/10507124/7377073/2651c410-edb2-11e4-9444-54d88dddb053.png)

I'm on Google Chrome 42.0.2311.90 (64-bit).  Not sure if this is related to #612.

**Comment by rjmajma** [comment]
Yup. We spotted this earlier. I believe it's connected to #612, but worth waiting for @LindsayYoung to chime in.

**Comment by LindsayYoung** [comment]
Yes, Josh is making headway on #612 now. I will close this since it is a duplicate.
