### ISSUE TITLE
committee history

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#639]
Create an endpoint for how committee information changes over tim.e

`/committee/id/history/year` endpoint 

`/candidate/<id>/committees` will just show the relationships with start and end date and have the most recent information for the committee. 

I think we should also filter out unauthorized committees, they are linked through paperwork but not really. We don't need that data and it could easily lead our API users astray.

**Comment by jmcarp** [comment]
We now have a committee history endpoint. Unauthorized committees are still included here--the only place we're filtering them out so far is in the candidate-committee linkage table. @LindsayYoung: Should we be excluding unauthorized committees, or can this be closed?

**Comment by LindsayYoung** [comment]
We should keep them as committees but they shouldn't be used to construct
relationships in `candidate/id/committees' or 'committee/id/candidate`

**Comment by jmcarp** [comment]
Sounds like this is working as expected.
