### ISSUE TITLE
correct number of results for charts

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#641]
(This is less of a priority because we will want to move these to normalized quarterly data, so we could just to the work then)

Too many receipts and disbursements showing:
 example `/candidate/H8CA05035`
![screen shot 2015-04-28 at 2 41 46 pm](https://cloud.githubusercontent.com/assets/4406333/7377584/57a2af68-edb5-11e4-8d59-b1254edbed1a.png)

Not enough cash and debt showing:
example `/candidate/P80003338`
![screen shot 2015-04-28 at 2 47 42 pm](https://cloud.githubusercontent.com/assets/4406333/7377644/c4076900-edb5-11e4-960c-64c5aee197a8.png)

It may have something to do with the pagination error on the API- since that is a wildcard too

**Comment by LindsayYoung** [comment]
I don't think this is a problem now, but something to keep in mind, @noahmanger, when we normalize the data based on quarters. 

Right now we wanted 4 of each but if we are showing 2 year periods with four quarters, we will want to show 8 , or make the the charts have some type of time select functionality.

**Comment by msecret** [comment]
I think this may have been due to inconsistent results from setting `per_page` on the API. Previously, I was setting `per_page=8` because of these inconsistencies, but now am setting it to `4`. So if that bug is fixed, seeing too many results shouldn't be a problem anymore.
