### ISSUE TITLE
As a user ,Im overwhelmed by drop down menus in left hand column.

### ISSUE THREAD

**Issue by jtag** [18F/openFEC#644]
Gah! Is this an awkward way to leave feedback? Do what you want with this....

Also, with length of drop drop downs, can you offer a type to complete functionality on the drop downs? I assume prof folks will know what they are looking for.

**Comment by noahmanger** [comment]
Thanks! Current version is temporary, but you prompted me to actually file an issue with what I want to redesign: https://github.com/18F/openFEC/issues/645
