### ISSUE TITLE
Fix Copy to Reflect Timeliness of Data

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#650]
I believe we currently state that we're using a snapshot of data collected in 2014. Thankfully, that is no longer the case. The copy on the site should reflect the timeliness of our data.

**Comment by rjmajma** [comment]
What it currently says: 

```openFEC uses a snapshot of disclosure data taken in 2014. If you’re looking for current campaign finance data, please visit here the Campaign Finance Disclosure Portal.```

What it should say:

```openFEC is a prototype that uses current disclosure data collected by the FEC. Things may not work as expected. Please continue your regular work on the Campaign Finance Disclosure Portal [LINK].```

If you're good with this Noah, then implement it and close it out.

**Comment by LindsayYoung** [comment]
We might want to add that we haven't yet imported all of the FEC's data.

**Comment by rjmajma** [comment]
That's a good point Lindsay. Will tweak in a second.

Also, another possible copy change here: https://github.com/18F/openFEC/issues/675

**Comment by rjmajma** [comment]
openFEC is a prototype that uses current disclosure data collected by the FEC. Things may not work as expected. Please continue your regular work on the Campaign Finance Disclosure Portal [LINK].

**Comment by rjmajma** [comment]
I am typing from my phone and learning that github mobile site doesn't let you edit a post. Sorry for being annoying. Updated language:

openFEC is a prototype that uses current disclosure data, but is not inclusive of all data made available by the FEC. Things may not work as expected. Please continue your regular work on the Campaign Finance Disclosure Portal [LINK].

**Comment by noahmanger** [comment]
So I just realized that we never use the term `alpha` anywhere, and we probably should. What do you think about saying:

> This site is in alpha. Learn more

And then the banner reads:

> This site is in alpha. Tell us what you think!

> This is the first public release of openFEC, a new app for exploring the FEC's disclosure data. OpenFEC uses current campaign finance disclosure data but is not inclusive of all data made available by the FEC and things may not work as expected. Please continue your regular work on the Campaign Finance Disclosure Portal [LINK].

> We're working hard to make openFEC a useful addition to the resources available at FEC.gov. Your feedback is important to us as we build this site. Email [X] and let us know how it’s working for you.

**Comment by noahmanger** [comment]
I think we can expect a number of early visitors will be familiar with the "alpha" terminology, so it's important that we include it.

**Comment by LindsayYoung** [comment]
makes sense to me
