### ISSUE TITLE
Missing data in web app that is in the api

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#657]
This should have data and doesn't
Webiste candidate page broken:
http://open.fec.gov/candidate/H0IL01087

Website committee page working:
http://open.fec.gov/committee/C00347583

API for reports working:
http://api.open.fec.gov/committee/C00347583/reports?api_key=xxx
API for totals working:
http://api.open.fec.gov/committee/totals/reports?api_key=xxx

**Comment by LindsayYoung** [comment]
This branched out from #618

**Comment by leahbannon** [comment]
Found an example with Rep. Norton http://open.fec.gov/candidate/H0DC00058

**Comment by LindsayYoung** [comment]
So the problem is in the /candidate/id endpoint having incomplete info on the candidate I can see that the info exists in the underlying data.

**Comment by LindsayYoung** [comment]
The problem we identified earlier is fixed but there is still something that is preventing some information we have from displaying

**Comment by LindsayYoung** [comment]
I think it is all resolved in #151 on the web app

**Comment by LindsayYoung** [comment]
It is!

**Comment by leahbannon** [comment]
![bc-alternative-dance](https://cloud.githubusercontent.com/assets/4323988/7540452/d5a87cf8-f57b-11e4-9d63-2669823c3ada.gif)
