### ISSUE TITLE
Make charts responsive

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#658]
Make the charts repsonsive according to the new screens.

![candidate - small charts open](https://cloud.githubusercontent.com/assets/1696495/7396418/d9e801e4-ee6e-11e4-9135-bb4f2c17da29.png)
![committee - small - two year summary](https://cloud.githubusercontent.com/assets/1696495/7396419/d9ed532e-ee6e-11e4-975a-a56451f209d8.png)

**Comment by noahmanger** [comment]
So there might be a quicker fix to this, curious what people think. Because we're only showing the last four, if we hide the Y-axis labels, they actually condense pretty well. 

![screen shot 2015-05-01 at 12 26 50 pm](https://cloud.githubusercontent.com/assets/1696495/7433318/e188f440-efe4-11e4-9983-031da4920dc7.png)

The downside is that to actually see any number you need to tap on each bar. 

Not how we'll want things ultimately, but probably gets the job done in the short term. Thoughts?

**Comment by LindsayYoung** [comment]
I like that idea.

**Comment by msecret** [comment]
Finished in https://github.com/18F/openFEC-web-app/pull/128
