### ISSUE TITLE
Unable to expand/scroll to see long glossary definitions

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#661]
When I view the definition for the term "FEC", the definition is too long to completely display in the glossary pane.  When I try to scroll to view the rest of the definition, it scrolls the content behind the glossary pane, rather than the glossary content.  Since the glossary pane cannot be resized or scrolled, there does not appear to be a way to view the entire definition.

![screen shot 2015-04-29 at 1 54 03 pm](https://cloud.githubusercontent.com/assets/10507124/7397544/2cde2be6-ee77-11e4-806e-ae31e0ee9a1b.png)

Google Chrome: Version 42.0.2311.90 (64-bit)

**Comment by rjmajma** [comment]
The FEC has its own definition? Meta.

**Comment by LindsayYoung** [comment]
We don't have FEC in the glossary anymore- Perhaps we should add it with "Federal Election Commission" as the answer. I noticed we don't spell out Federal Election Commission anywhere on the homepage.
