### ISSUE TITLE
Fix API key and rate limiting for typeahead search

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#667]
We're currently using a temporary API key to support AJAX requests for typeahead search directly to the API. This means we'll quickly hit the rate limit for this key and periodically break search. We should choose a different key and/or disable rate limiting for this endpoint.

**Comment by LindsayYoung** [comment]
I think disabling the rate limit for that endpoint would be best. Would that be easy to implement?

**Comment by LindsayYoung** [comment]
@jmcarp do you remember if we did this?
