### ISSUE TITLE
Candidate/committee filter usability: Typing Enter after entering a name clears out field

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#669]
1) Open either the Candidate or Committee browse page
2) Enter a value in the Name filter field
3) Press "Enter"
4) The Name field is blanked out and the cursor remains in the Name field

I would expect different behavior -- most likely for the query to execute. 

Discovered on Chrome 42.0.2311.90 (64-bit)

**Comment by noahmanger** [comment]
Oh good catch. I noticed this myself.
