### ISSUE TITLE
Add 2016 to the election cycle choices for candidate browse view

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#671]
Allow filtering for 2015 2016 to the dropdown-
https://open.fec.gov/candidates
![image](https://cloud.githubusercontent.com/assets/4406333/7424091/495d98b6-ef6b-11e4-97a5-e4b5f1a8d299.png)

**Comment by jmcarp** [comment]
This will be fixed in https://github.com/18F/openFEC-web-app/pull/156.
