### ISSUE TITLE
Typeahead search showing different committees than committee page

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#676]
When I do a typeahead search for Brownback, a committee named "Sam Brownback for U S Senate" is listed as one of the options.  However, when I search for Brownback on the Committees page, this is not a listed option.  If I select "Sam Brownback for U S Senate" from the dropdown, it takes me to the page for Friends of Brownback (C00320051).

![screen shot 2015-05-01 at 10 31 51 am](https://cloud.githubusercontent.com/assets/10507124/7431510/2677cdf8-efed-11e4-92cc-29ba1d68ed30.png)

Chrome 42.0.2311.90 (64-bit)

**Comment by jmcarp** [comment]
Good catch! I'll take a look.

**Comment by LindsayYoung** [comment]
This is a date filtering issue, the committee search is focused on the last
few years. You should be able to choose the a particular year once we
re-enable the year dropdown
