### ISSUE TITLE
So that users can find the source data, include report name and link in chart tooltip

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#679]
It shouldn't be hard to add the report name to the chart tooltip, right? 

So that it would say "From the September 2014 quarterly report" or something?

![screen shot 2015-05-01 at 10 08 23 am](https://cloud.githubusercontent.com/assets/1696495/7433830/1efb98c8-efea-11e4-9eef-6c0278356b80.png)

**Comment by LindsayYoung** [comment]
That sounds like a good idea. That information is in the reports so it
shouldn't be hard to add.

**Comment by noahmanger** [comment]
I actually still want to do this. Assinging to myself.

**Comment by noahmanger** [comment]
New card under "finding committee reports": https://18f.storiesonboard.com/m/fec/!card/5PdofGInK-ULFDnUEM13oA
