### ISSUE TITLE
No way to filter candidates/committees by territories

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#683]
The candidate and committee results include entries with values of Puerto Rico (PR), the US Virgin Islands (VI), American Samoa (AS), the Northern Mariana Islands (MP), and Guam (GU) in the state field, but there is currently not a way to filter for those values in the State dropdown.

![screen shot 2015-05-01 at 3 35 53 pm](https://cloud.githubusercontent.com/assets/10507124/7436040/71076264-f017-11e4-8200-02bf4b2dd67c.png)

**Comment by LindsayYoung** [comment]
good eye!
