### ISSUE TITLE
weird browser result on committee filters

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#687]
committee filters loaded oddly, using chrome

![screen shot 2015-05-02 at 9 33 22 am](https://cloud.githubusercontent.com/assets/4406333/7441280/6f17cf4c-f0ae-11e4-9b85-1a33bac86ad0.png)

**Comment by jmcarp** [comment]
Looks like a responsiveness issue, but I think it will be resolved by https://github.com/18F/openFEC-web-app/pull/116.

**Comment by LindsayYoung** [comment]
:+1:

**Comment by LindsayYoung** [comment]
sounds like this is covered
