### ISSUE TITLE
Candidate cycle dropdown should apply to statements, not candidates

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#692]
[transferred from https://github.com/18F/openFEC-web-app/issues/120]

Currently, selecting an election cycle on a candidate detail page (e.g. 2013-2014) sends a request to the API at `/candidate/<candidate_id>?year=<year>`. Then we request *all* financial statements associated with that candidate's committees--meaning we don't apply the election cycle filter to the statement listing. I may be interpreting this incorrectly, but I would think that we should be filtering the statements by year instead of the candidate. This will be possible once @LindsayYoung's new `/reports` and `/totals` endpoints are added, so that we can send a request to e.g. `/reports?candidate_id=<candidate_id>&year=<year>`.

We will want to fix this *before* re-enabling the cycle filter on the candidate detail page, which FEC has requested we fix soon.

**Comment by jmcarp** [comment]
To clarify this report, the issue I'm talking about only is only related to the webapp, and there are other, distinct issues that we'll need to handle before cycle filtering is good to go. Here's a (hopefully) better description of what's going on with the webapp:

* User selects the 2011-2012 election cycle
* Webapp makes a request to the API filtering by year
    * `GET /v1/candidate/H8CA05035?year=2012`
* For each committee associated with the candidate, webapp makes a request to list its reports
    * `GET /v1/committee/C00213512/reports?per_page=4&page=1`
    * These requests are *not* filtered by year
    * If a committee operates across several election cycles, we can get reports that are not in the cycle specified by the user

**Comment by LindsayYoung** [comment]
To get the right candidate information, you will need
 - GET /v1/candidate/H8CA05035/history/2012

**Comment by jmcarp** [comment]
Fixed with updates election cycle filtering on candidate and committee pages.
