### ISSUE TITLE
Certain fields in committee summary are not bound to real data

### ISSUE THREAD

**Issue by msecret** [18F/openFEC#695]
The "Fundraisings" and "Exempt legal and accounting" are not displaying any real data. It is currently unknown what data fields they should be using.

This bug should be closed when we find what data should be used for them and the code is changed so they use the actual data rather then some default as they are now.

**Comment by arowla** [comment]
The "Transfer **from** a Committee" line item has also been displaying the value of "transfers_**to**_affiliated_committee". This is fairly easily fixed for House/Senate and Presidential committees, but PACs and Party committees don't have an obvious direct analog.

**Comment by LindsayYoung** [comment]
I would like to make this part of the work proposed in #705

**Comment by LindsayYoung** [comment]
fixed in pr #138 on the web app
