### ISSUE TITLE
508 accessibility contrast issues

### ISSUE THREAD

**Issue by msecret** [18F/openFEC#702]
These were all reported by Nick Bristow:

- Placeholder text in search boxes needs to be darker --global
- Labels on the filter form have insufficient contrast
- The blue name text on the dark rows has insufficient contrast

**Comment by noahmanger** [comment]
Are these the labels he was looking at? The contrast shows up as 6.62:1 for me:

![screen shot 2015-05-05 at 5 16 33 pm](https://cloud.githubusercontent.com/assets/1696495/7485437/b6606960-f34a-11e4-9c84-959221f51387.png)

**Comment by msecret** [comment]
I'm getting 1.83:1. This means its OK at 16px font.

**Comment by noahmanger** [comment]
1.83:1? I'm getting 6.62:1 (#515A61:#F8F8F8) using http://webaim.org/resources/contrastchecker/

**Comment by msecret** [comment]
Sorry must have written that number incorrectly. I think Nick these labels are fine and this should be closed.
