### ISSUE TITLE
Use repeated query parameters for list arguments

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#706]
Several API endpoints accept query parameters that can either be scalars (`year=2015`) or lists (`year=2015,2016`). This means developers have to remember which parameters can be list-like and split on commas as appropriate. We also miss out on simple type validation with flask-restful's reqparse (or with webargs if #662) is merged in its current state): we're forced to validate list-like arguments as strings, and then manually validated each item after comma-splitting later on.

I propose using repeated query parameters for list-like arguments (`/candidates?year=2015&year=2016`). It gives us a simpler API to work with internally (just add `action='append'` for reqparse or `list=True` to webargs), and we get validation as normal, without having to write and debug extra code. This is also, in my limited experience, the more "standard" way of handling list-like fields for GET requests.

If folks are all right with the proposed change, I'd be happy to implement it--I don't see this taking much time. I'm also open to being convinced that the current approach is better :smiley:!

**Comment by LindsayYoung** [comment]
Do you know how much work it would be to change this in the web app?

**Comment by jmcarp** [comment]
AFAIK, this wouldn't require change on the web app at the moment--I don't know of any instances in which the web app passes lists back to the API. But even if we were passing lists, this wouldn't take much code to change.

**Comment by arowla** [comment]
:+1: I don't think this would change anything in the web app as it stands, either.

**Comment by noahmanger** [comment]
So I was playing around with styling the election year filter as a `<select multiple>`. And it generated repeated query parameters. So this probably even makes the implementation of multi-year selects on the frontend even easier.

**Comment by noahmanger** [comment]
Like so: 
![screen shot 2015-05-06 at 9 48 53 am](https://cloud.githubusercontent.com/assets/1696495/7498376/2ae0ce94-f3d5-11e4-9911-ad8f045a01d0.png)

**Comment by jmcarp** [comment]
@noahmanger :+1:

**Comment by LindsayYoung** [comment]
awesome
