### ISSUE TITLE
Typo in Learn More banner

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#707]
There is a typo ("Wwe're working hard...") in the Learn More banner.

![screen shot 2015-05-06 at 12 11 15 pm](https://cloud.githubusercontent.com/assets/10507124/7497509/ebfb86c4-f3e8-11e4-872f-5beee15ac81e.png)

**Comment by noahmanger** [comment]
Fixed it here, but maybe not redeployed yet. https://github.com/18F/openFEC-web-app/pull/131/files

**Comment by rdpiazza** [comment]
Great!
