### ISSUE TITLE
Update animated gif to reflect current site text

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#710]
The site text for the animated gif that demonstrates the glossary feature no longer matches the current site text.

**Comment by rdpiazza** [comment]
The new animated gif appears not to be animating.  Should this be reopened?

**Comment by noahmanger** [comment]
Sorry, I explained in the commit message that I replaced it with a static
jpg because I couldn't get the gif to not be fuzzy.

On Wed, May 13, 2015 at 8:48 AM, Rebecca Piazza <notifications@github.com>
wrote:

> The new animated gif appears not to be animating. Should this be reopened?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/710#issuecomment-101721699>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by rdpiazza** [comment]
Ah, got it.  For future readers: see #616
