### ISSUE TITLE
API throws 502 error with a per_page value of 10000

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#716]
This hangs and then throws a 502.

http://api.open.fec.gov/v1/committees?api_key=DEMO_KEY&per_page=10000

If we can't return this many records at once, then we need to institute a max limit. However, I am curious as to why this failed, and we should be returning as many records as we can.

**Comment by arowla** [comment]
See also #299

**Comment by arowla** [comment]
So far I have tried returning up to 4000 records successfully. I guess it's possible we just ran out of free memory on our app instance. That would be easy enough to try out increasing on CF. It's set to 512MB right now.

**Comment by jmcarp** [comment]
Page sizes have been capped at 100. Closing.
