### ISSUE TITLE
Show "remove button" on cycle select upon page load

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#726]
The election cycle select that has options selected needs to have the remove button visible when the page first loads.

![screen shot 2015-05-11 at 3 02 40 pm](https://cloud.githubusercontent.com/assets/1696495/7576044/df9bd960-f7ee-11e4-9aca-a2dd9f0ec337.png)

**Comment by jmcarp** [comment]
Good catch. Should be fixed in #159.

**Comment by jmcarp** [comment]
Working on dev now.
