### ISSUE TITLE
Link to API from webapp frontpage

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#737]
As @noahmanger pointed out, the webapp should link to the API and API documentation.

**Comment by noahmanger** [comment]
Do people need an API key to access the docs?

**Comment by jmcarp** [comment]
Good call. I'm not sure that we should require an API key for the docs. We should be able to make that endpoint work without a key if that's the behavior we want.

**Comment by noahmanger** [comment]
Cool. Yeah that would be my preference. And would be great to include instructions on how to get an API key.

**Comment by LindsayYoung** [comment]
These are good ideas

**Comment by LindsayYoung** [comment]
Thanks @jenniferthibault I love the link and the picture! It is hard to make an API visually compelling.
