### ISSUE TITLE
Committee addresses no longer showing their ZIP codes

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#742]
Related to #615.  Appears fix to committee addresses no longer showing their state led to committee addresses no longer showing their ZIP codes.

![screen shot 2015-05-13 at 12 00 20 pm](https://cloud.githubusercontent.com/assets/10507124/7614836/7911a740-f967-11e4-81cd-d2ade41859d3.png)

**Comment by arowla** [comment]
Fixed in 18F/openFEC-web-app/#168
