### ISSUE TITLE
Search results do not include committee results

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#743]
When I search for a term and select the magnifying glass icon, the search results only return matching Candidate results. They do not include matching Committee results.

When I search for "Money", there are a number of Committee results displayed in the typeahead:
![screen shot 2015-05-13 at 11 53 39 am](https://cloud.githubusercontent.com/assets/10507124/7615376/5bf75dd6-f96b-11e4-8c0b-38ca470eb028.png)

But if I select the magnifying glass, only Candidate results are displayed:
![screen shot 2015-05-13 at 12 29 11 pm](https://cloud.githubusercontent.com/assets/10507124/7615415/8315d7b2-f96b-11e4-98e3-6aa94fb09efd.png)

Tested on open.fec.gov on May 13.  Similar results also seen on dev.

**Comment by arowla** [comment]
Assigning this to @jmcarp since we seem to have a similar-but-opposite problem now, possibly related to  #750
