### ISSUE TITLE
Candidate Page dev fixes

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#744]
- Committee designation missing where it should say Principal etc.
- Add date range to "reports calculated from" cycle -1 to cycle
- Add pdf link to source

**Comment by LindsayYoung** [comment]
here is a screen shot for reference

![screen shot 2015-05-13 at 1 35 13 pm](https://cloud.githubusercontent.com/assets/4406333/7616757/eee66aa2-f974-11e4-98f8-63e824eb3b54.png)

**Comment by noahmanger** [comment]
Remembered another thing you had on here that got lost: a list of election years. I'm adding it.

**Comment by LindsayYoung** [comment]
I thought you just didn't like it. :)

**Comment by noahmanger** [comment]
Haha. I'm not _that_ passive aggressive :)

On Wed, May 13, 2015 at 4:23 PM, Lindsay Young <notifications@github.com>
wrote:

> I thought you just didn't like it. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/744#issuecomment-101847052>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
These are on dev.
