### ISSUE TITLE
Separate totals from recent report

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#746]
They are getting too long so we can house them in separate tabs. This will be a clean up step after #705 is finished. 

@noahmanger I will ping you when the full reports and totals are done.

**Comment by LindsayYoung** [comment]
Underlying work is finished in [158](https://github.com/18F/openFEC-web-app/pull/158)

**Comment by noahmanger** [comment]
Did we solve this already?

**Comment by LindsayYoung** [comment]
yes. Go Team!
