### ISSUE TITLE
Candidate results include values from years not included in filter

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#749]
When I filter by year on the Candidate page, results are included that are outside of the year I selected in the filter.  

Example:  When I filter by year 2012, results are included for 2014 for Gary Ackerman and John Adams.

![screen shot 2015-05-13 at 3 15 23 pm](https://cloud.githubusercontent.com/assets/10507124/7618816/baabd890-f982-11e4-8320-399fb8c12cf4.png)

Seen both on dev and prod.

**Comment by LindsayYoung** [comment]
The results are filtered. The election being shown is really the most recent election. 

Perhaps we should call that column recent election?

**Comment by noahmanger** [comment]
Ah yes, good catch. Let's do that.

On Wed, May 13, 2015 at 12:24 PM, Lindsay Young <notifications@github.com>
wrote:

> The results are filtered. The election being shown is really the most
> recent election.
>
> Perhaps we should call that column recent election?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/749#issuecomment-101782746>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
Fixed in https://github.com/18F/openFEC-web-app/pull/176.
