### ISSUE TITLE
Party descriptions contain extra/invalid text

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#755]
The following party descriptions contain extra/invalid text.  These descriptions are displayed both on the Candidate detail page and in the Candidate list.

"Green Party" currently displays as "Green Party Added)"
![screen shot 2015-05-14 at 10 27 11 am](https://cloud.githubusercontent.com/assets/10507124/7633846/0b3fc06c-fa25-11e4-9e7a-068262557bc1.png)

"Independent American Party" displays as "Independent American Party (Added)"
![screen shot 2015-05-14 at 10 27 59 am](https://cloud.githubusercontent.com/assets/10507124/7633848/10bd02d4-fa25-11e4-9cff-b860b7a26643.png)

"Taxpayers" displays as "Taxpayers (Old Doc was "TXT")"
![screen shot 2015-05-14 at 10 31 52 am](https://cloud.githubusercontent.com/assets/10507124/7633856/1641be66-fa25-11e4-976c-f4160c9bf430.png)

"Communist Party" displays as "Communist Party (Old Doc was "M")"
![screen shot 2015-05-14 at 10 34 26 am](https://cloud.githubusercontent.com/assets/10507124/7633860/1d076d9a-fa25-11e4-9fe2-baeaf23d0c98.png)

Related:  Are these two different parties or two references to the same party?  
![screen shot 2015-05-14 at 10 30 05 am](https://cloud.githubusercontent.com/assets/10507124/7633936/af76d166-fa25-11e4-87c0-5a39c674a070.png)
There are no results for "Peace Freedom Party".

**Comment by LindsayYoung** [comment]
This is coming from the underlying data, we used to just formulate it ourselves but if we do that we are less sensitive to changes in the data like new parties, etc. We could also just add formatting that filters out  the (...)

**Comment by rdpiazza** [comment]
Is there a way to alert the data owners, and see if they'll cleanse?  Or is that unlikely?

**Comment by jmcarp** [comment]
How about the same strategy we're using for #754: put in the quick fix now (clean out parenthetical remarks), let FEC know about the issue, and remove the temporary fix when / if the underlying data are corrected? I need to get in touch about other data issues anyhow, so I can go ahead with this if you all think it's reasonable.

**Comment by rdpiazza** [comment]
Sounds good to me!

**Comment by arowla** [comment]
A simple regex may do it, but FYI somebody I know quite well wrote a library for cleaning up names coming from the FEC.

https://github.com/sunlightlabs/name-cleaver

**Comment by rdpiazza** [comment]
Related to #762?

**Comment by rdpiazza** [comment]
@jmcarp - there may be an issue with this.  When I search for Green party now, it gives an Oops I messed up error.

**Comment by jmcarp** [comment]
@rdpiazza Sorry, I'm not following. Do you mean you're encountering problems searching for candidates or committees by party, (http://fec-dev-web.cf.18f.us/candidates?party=GRE or http://fec-dev-web.cf.18f.us/committees?party=GRE), or using the generic search (http://fec-dev-web.cf.18f.us/?search=green+party), or something else? All of the above seem to work as expected.

**Comment by rdpiazza** [comment]
Imprecise language on my part: I was filtering, not searching.  I went to the Candidate page and filtered by Green Party.  However!  I just retried it and it worked.

**Comment by jmcarp** [comment]
Interesting. There have been a bunch of patches merged into develop today, which means a bunch of deploys to the dev api and webapp, which means intermittent downtime. That might be the culprit here, since the error you described is what you'd see if the api were down. Implementing #764 should address this.

**Comment by jmcarp** [comment]
@rdpiazza Unless you have reservations, I think this one is safe to close.

**Comment by rdpiazza** [comment]
Closed!
