### ISSUE TITLE
Some party descriptions incorrect in the Candidate list

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#762]
When I search for Candidates from the Constitutional Party, some results are displayed with the description "Invalid Party Code":

![screen shot 2015-05-14 at 10 25 22 am](https://cloud.githubusercontent.com/assets/10507124/7637547/bf85282a-fa3c-11e4-8d27-cc32e467c2a6.png)

Additionally, when I search for Candidates from the Democratic-Farm-Labor party, some results are displayed with the description "Democratic Party".  These results are not displayed when I search for them as members of the Democratic Party, so there appears to be a conflict between the code indicating their party and the display value.
![screen shot 2015-05-14 at 10 26 17 am](https://cloud.githubusercontent.com/assets/10507124/7637549/c2ce74c8-fa3c-11e4-9a51-24b15914f164.png)

**Comment by arowla** [comment]
@rdpiazza Care to check that this is fixed on dev, and close this if so?

**Comment by LindsayYoung** [comment]
If I remember correctly, the invalid party code problem is in the data.

**Comment by arowla** [comment]
It's fine for a record to be marked "Invalid Party Code"-- that's totally valid. However, the problem where records marked that were coming up under searches for another party was a bug on our end, fixed in #765

**Comment by rdpiazza** [comment]
Tested and fixed!  Thanks @arowla @LindsayYoung !
