### ISSUE TITLE
Show election years instead of election cycles for candidates

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#771]
That makes special elections obvious in a way that it currently isn't.

for example Scott Brown
/candidate/S0MA00109

```
"cycles": [
  2010,
  2012,
  2014
],

"election_years": [
  2009,
  2010,
  2012,
  2014
],
```

I think that we should list election_years as "election years" on the candidate profile page `/candidate/S0MA00109` and I think we should use this as the range we show in the candidate browse view. 

this started in pr [181](https://github.com/18F/openFEC-web-app/pull/181)

**Comment by jmcarp** [comment]
I think this makes sense. Just one question: should the year filter on the candidate search page allow users to filter on election year or cycle? IMO, the filters and table columns should be aligned as well as possible (see #772).

**Comment by LindsayYoung** [comment]
The filter needs to use cycle because that is how we do totals. The list of elections a candidate participates in is a separate issue.

**Comment by LindsayYoung** [comment]
Good point! I did not document it here, the filter and title are  both going to be called "Election Years"

**Comment by jmcarp** [comment]
Implemented by @LindsayYoung in https://github.com/18F/openFEC-web-app/pull/185.
