### ISSUE TITLE
Harmonize filters and column titles

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#772]
In general, I would expect that the fields in the candidate and committee filters (name, election cycle, etc.) would correspond to the columns of the results tables as follows:

* Fields in the filters also appear in the results tables
* Fields in the filters and results tables appear in the same order
* Fields are named consistently across filters and results tables

This isn't always the case. For example, the committees search page allows users to filter on "Committee Type", but labels the header of the corresponding results column as just "Type". Users can filter on "Election Cycle", but there is no corresponding results column. And the order of the state and party fields is reversed from the filters to the results table.

Feel free to close if this is too nitpicky, but I think it would be worth a quick audit of the candidate and committee search pages to clean up issues like these.

**Comment by LindsayYoung** [comment]
I am ok with condensing the heading text because we have so little room, but I see the case to be made for standardization. 

@noahmanger should we close this?

**Comment by noahmanger** [comment]
I'd like to take a general look at the columns we're showing and the order we show them in throughout the app, including exploring the ability to add or remove columns. I'll create a new issue for that for us to pick up after launch.

**Comment by noahmanger** [comment]
New issue: https://github.com/18F/openFEC-web-app/issues/815
