### ISSUE TITLE
Multiple principal campaign committees

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#776]
Here's an interesting issue. Hillary Clinton (Presidential candidate) has two Principal Campaign Committees. One has filed its termination report and the other has yet to file a report. Not sure how we want to deal with this but wanted to flag it:

![screen shot 2015-05-15 at 11 02 43 am](https://cloud.githubusercontent.com/assets/1696495/7658902/088a32de-faf3-11e4-8a83-4b84cb7c0a47.png)

**Comment by LindsayYoung** [comment]
Yea, that is correct, she started a new committee . We will only see one at a time once we implement date filtering. Which will make it less confusing. Right now the only filing for that committee is [here](http://docquery.fec.gov/pdf/528/15031411528/15031411528.pdf)

**Comment by noahmanger** [comment]
Cool. Yeah I figured this would be happening with date filtering but wanted to flag it.

Separately, though, we need a more graceful fall back for when there's a registered committee but no reports filed yet.

**Comment by noahmanger** [comment]
e.g. 
![screen shot 2015-05-15 at 11 43 45 am](https://cloud.githubusercontent.com/assets/1696495/7659553/ad87ab78-faf7-11e4-9eaa-013c341fb519.png)

**Comment by LindsayYoung** [comment]
Hopefully we will have a list of all the filings soon, so that will give us more to show too. 

:+1:
