### ISSUE TITLE
Scott Brown's summary is not showing up

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#780]
http://fec-dev-web.cf.18f.us/candidate/S0MA00109

**Comment by noahmanger** [comment]
Huh. What happened to his principal committee?

On Fri, May 15, 2015 at 3:31 PM, Lindsay Young <notifications@github.com>
wrote:

> http://fec-dev-web.cf.18f.us/candidate/S0MA00109
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/780>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
The corresponding committee is here:
http://fec-dev-web.cf.18f.us/committee/C00494294

It is showing up as a joint instead of Primary in the API? looking into that now

**Comment by LindsayYoung** [comment]
So the committee was a principal committee and became a joint committee. I think proper date filtering will resolve this but we will need to keep an eye on this.

**Comment by LindsayYoung** [comment]
This is sill a problem because we are not grabbing date-specific information in `candidate/id/committees?cycle=xxx` So, since the primary committee has since become a joint committee so Brown Victory Committee (C00561886) doesn't get a profile and is listed with the joint committees.

**Comment by LindsayYoung** [comment]
@jmcarp do you think we could do this with existing views and a change in sqlalchmey, or do we need to re-write that view?

**Comment by jmcarp** [comment]
@LindsayYoung we already have the information needed to get this right in the committee history view. We could add another endpoint to the committee history view at e.g. `/candidate/<candidate_id>/committees/history/<year>, and then query the new endpoint to render the candidate detail page.
