### ISSUE TITLE
"You do not have permission" error when viewing Committee PDF

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#788]
For "10TH DISTRICT REPUBLICAN CONGRESSIONAL COMMITTEE" (C00005462), when I select the following View PDF link:

![screen shot 2015-05-18 at 2 59 04 pm](https://cloud.githubusercontent.com/assets/10507124/7687861/427a5f0a-fd6e-11e4-97ab-c3aa028a269e.png)

I get a 403 Forbidden error:
![screen shot 2015-05-18 at 2 59 21 pm](https://cloud.githubusercontent.com/assets/10507124/7687865/4ecac8d0-fd6e-11e4-8f75-bc019d797083.png)

Tested on Dev.

**Comment by LindsayYoung** [comment]
I had that problem before we should be generating the last 3 digits for the url after `pdf\` that only has 2.

**Comment by rdpiazza** [comment]
@LindsayYoung -- great troubleshooting!  If I change it to http://docquery.fec.gov/pdf/083/15970344083/15970344083.pdf, it pulls up the PDF.  Looks like the code that is generating the URL is dropping leading zeros in the triplet after PDF.

**Comment by jmcarp** [comment]
Should be fixable by zero-padding the digits in `last_n_characters`. Good catch!
