### ISSUE TITLE
Use districts from dimcandproperties

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#794]
it seems better than dimoffice and a district variable should be there now.

**Comment by jmcarp** [comment]
I don't see anything that looks like a district on `dimcandproperties`. @LindsayYoung help!

**Comment by LindsayYoung** [comment]
I think I emailed fec about that. We saw that Paul had that column there when he went over things with us, and his district data was cleaner. I thought that we had access to it but just didn't know. Turns out we still don't have access to it. Sorry for the confusion
