### ISSUE TITLE
Load candidate and committee search results asynchronously

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#797]
Loading candidate or committee search results is currently a synchronous operation, meaning that the entire page is re-rendered server-side on selecting a different results page or updating search filters. This makes the search slower than it has to be and puts unnecessary load on the webapp server. Proposal: fetch search results asynchronously, ideally by making a request directly to the API and bypassing the webapp entirely.

Separate but related: revisiting the way we fetch search data would also give us an opportunity to use a table library with more features (sorting, more complete paging interface) before we start building those features ourselves. I've had good results with datatables in the past, but would be open to any library (or none).

https://www.datatables.net/

**Comment by jmcarp** [comment]
@marco and/or @noahmanger: any preferences on table libraries, or do you think it's better to stick with our homegrown implementation?

**Comment by noahmanger** [comment]
Oooh. Datatables looks really interesting. How much of a pain is it to
configure and customize? How bulky is it? The capabilities it adds out of
the box definitely make it attractive.

On Tue, May 19, 2015 at 11:46 PM, Joshua Carp <notifications@github.com>
wrote:

> @marco <https://github.com/marco> and/or @noahmanger
> <https://github.com/noahmanger>: any preferences on table libraries, or
> do you think it's better to stick with our homegrown implementation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/797#issuecomment-103745464>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
I don't *love* datatables--it's been in development for a long time, and there's a certain amount of cruft in the codebase. But it's also very mature and supports all the features we need out of the box (including server-side sorting and pagination, which isn't hard, but I'm generally in favor of writing less code if possible). Then again, using datatables might also require adding a custom API endpoint (not hard, but kind of annoying!), so maybe it's not worth it. I'll think about this more--any feedback / alternatives welcome.

**Comment by jmcarp** [comment]
Based on discussion with @msecret, I think we can forget about datatables, since the new search format looks much less like a table. The main point here still stands, though: when time permits, we should think through how we want to switch rendering of content like this from the server to the client.

**Comment by noahmanger** [comment]
Ok. FYI, the search is different, but the browse /candidates and
/committees will still be tables.

On Thu, May 21, 2015 at 4:07 PM, Joshua Carp <notifications@github.com>
wrote:

> Based on discussion with @msecret <https://github.com/msecret>, I think
> we can forget about datatables, since the new search format looks much less
> like a table. The main point here still stands, though: when time permits,
> we should think through how we want to switch rendering of content like
> this from the server to the client.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/797#issuecomment-104406156>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
Understood. Not to second-guess (I'm sure there are good reasons for this!), but that's not what I would expect. Searching for a candidate by typing her name into the search bar will list *exactly* the same candidates as loading the candidate search page and typing that name into the name field--so searching and browsing seem like two entry points into the same information. It also seems potentially duplicative to build two interfaces that do (what seem to me like) very similar things--the current browse views and the new search views will show the same candidates, and potentially potentially be filterable and sortable on at least some of the same fields. As a user, how will I distinguish between the two views and understand the purpose of each one?

**Comment by noahmanger** [comment]
Totally valid points! You're right, there's some redundancy, which I _think_ was introduced partly because we improved the way the browse pages worked (i.e. showing the dates applied, improving the way the name search works). 

My thoughts on having a different interface for showing search results was to have an interface that was easier to quickly scan in order to find the result you're actually looking for, while also providing a slightly more dense view of the info with showing the links to their committees. My hypothesis (that we need to validate) is that modeling the search results page after a more traditional search results pattern be more friendly to new people looking for a particular record (as opposed to a list of records). 

But! Ultimately, we won't know what works until we get it in front of users and this could totally be wrong. Please keep ask these questions and raise these points! I just wanted to share the background rationale.

**Comment by jmcarp** [comment]
Sounds good to me :+1:

**Comment by jmcarp** [comment]
Added in https://github.com/18F/openFEC-web-app/pull/220.
