### ISSUE TITLE
To begin improving performance, profile the webapp

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#798]
Based on discussion with @msecret, we should profile the webapp and see if there are things we should do to make pages load and render faster. This will almost certainly tell us that we should be minifying and gzipping static assets, and hopefully other useful stuff too.

Related: https://github.com/18F/openFEC-web-app/issues/101

**Comment by noahmanger** [comment]
Is this still something we need to do?

Captured on a card here: https://18f.storiesonboard.com/m/fec/!card/RSbBJcI1eMw5YjnUELlqgg

**Comment by msecret** [comment]
If this is done, ensure you track performance as you make changes to things. I'm currently drafting a document for the front end guild here: https://docs.google.com/document/d/1JmzzIBEDTWD2AyGLN6mBxx6JjDw7ZHE8WOgnlewQmks/edit
