### ISSUE TITLE
Add API.md for openFEC-web-app

### ISSUE THREAD

**Issue by theresaanna** [18F/openFEC#80]
We haven't documented the way that the API and web app live together, how to develop with them both, how to configure nginx. We should add a file that describes how to set that up.

**Comment by LindsayYoung** [comment]
Did we do this?

**Comment by jmcarp** [comment]
I vote we close this, and open new issues if there's still work to be done. Preferences @LindsayYoung?

**Comment by LindsayYoung** [comment]
sounds good.
