### ISSUE TITLE
Set up user-provided service in CF to keep track of sensitive env vars

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#800]
It's recommended to set up a user-provided service to broker sensitive environment variables that don't go in source control out to our various CF apps. Let's set that up. I'm not sure how to coordinate that across spaces, so we'll have to figure that part out.

**Comment by jmcarp** [comment]
I agree so enthusiastically that I asked for much the same thing in #796. @arowla, I'd be happy to tackle this.

**Comment by arowla** [comment]
Hah! Be my guest.
