### ISSUE TITLE
Restrict committee reports to monthly and quarterly

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#805]
Currently, committee report charts show up to the four most recent reports, regardless of report type. This can be confusing when monthly, year-end, post-election, etc., reports are all combined into a single chart, with no indication of each report's type. Based on discussion with @LindsayYoung, we should restrict reports for the charts to monthly and quarterly reports. I'll take a look at this.

**Comment by LindsayYoung** [comment]
It will make the charts make more sense, because then we are not showing overlapping data.

**Comment by jmcarp** [comment]
After discussion with FEC, we don't need this change after all--seems like sometimes committees just file at irregular date intervals.
