### ISSUE TITLE
Bug: In order to have accurate committee addresses, separate PO boxes from street addressses

### ISSUE THREAD

**Issue by arowla** [18F/openFEC#815]
This is super minor, but this committee's address_1 and address_2 lines constitute their street and PO Box addresses. Not sure what the solution is, but displaying them as if they are one address looks odd.

/committee/C00509745

**Comment by leahbannon** [comment]
Check to see if this is a larger issue. If it's just this one committee, we'll postpone for later.

**Comment by jmcarp** [comment]
I don't remember how we were displaying addresses back in May, but now the first and second address lines are displayed on separate lines, which seems right to me. There's nothing wrong with the data AFAICT.
