### ISSUE TITLE
Aggregate financials across multiple authorized committees

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#832]
For candidates with multiple authorized committees, FEC has requested that we show totals across the committees before showing reports for each committee on its own. For example, John Kerry had three authorized committees in 2004 (http://fec-dev-web.cf.18f.us/candidate/P80000235); before showing financials for each committee, we should show total receipts, disbursements, etc., summed across all authorized committees.

This shouldn't be complicated to implement, but we do have a few decisions to make:
* Should aggregated financials look like committee financials, or should they have a distinct look?
* Should we also aggregate charts, or just two-year numbers? Aggregating charts should be possible, but we would need to watch out for different committees reporting on different coverage dates
* How should we compute aggregate cash on hand? It's not clear from the current FEC site exactly how this is being done; I'll ping them and get more information.

Pinging @noahmanger and @LindsayYoung for suggestions.

**Comment by LindsayYoung** [comment]
Thanks for hammering this out Josh, I know this is something that Paul and Jeff care deeply about. 

My two cents:

 - I would suggest that we  have a title above it that says something like,  "Totals for all Principal and Authorized Committees" in its own section above the Authorized committees section and have a hr separating the sections. (I will defer to Noah if he thinks of a better way to separate things visually.) 
 - I don't think we should aggregate the charts until we have standardized all charts on quarters. Just in case they are on different reporting schedules. We can always add the charts later.
 - Talking to Jeff and Paul for that is definitely a good idea

**Comment by jmcarp** [comment]
Based on some initial feedback from FEC, we should be able to calculate all the summary line items (receipts, disbursements, cash on hand, etc.). We're just waiting on some clarification about exactly how some of those items should be aggregated. I also agree with @LindsayYoung that holding off on aggregated charts until we've standardized on quarterly filings is a good idea. @noahmanger, I can put this together once you have time to figure out how it should look.

**Comment by noahmanger** [comment]
So here's a couple ways I could see doing it. I guess we don't need to worry about a specific implementation at the moment, as the only difference is stylistic. The main challenge I see is how to correctly describe the sources. 

![sum totals a](https://cloud.githubusercontent.com/assets/1696495/7825124/2fa1299e-03be-11e5-80c4-16f7f5b7f9a0.png)
![sum totals b](https://cloud.githubusercontent.com/assets/1696495/7825125/2fa19898-03be-11e5-8030-5ea3ac9c16b2.png)
