### ISSUE TITLE
Enhance search with pacronyms 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#839]
Use the FEC data to make the committees searchable by their common acronym

[resource here](http://www.fec.gov/pubrec/pacronyms/pacronyms.shtml )

**Comment by noahmanger** [comment]
Yessssss

On Tue, May 26, 2015 at 10:49 AM, Lindsay Young <notifications@github.com>
wrote:

> Use the FEC data to make the committees searchable by their common acronym
>
> resource here <http://www.fec.gov/pubrec/pacronyms/pacronyms.shtml>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/839>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
