### ISSUE TITLE
Time-standardized endpoint for charts

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#840]
basically standardized the data that covers less time into quarters so that the charts are more standardized.

We have already had some discussion about this in an email a while ago I can find it and forward it.

**Comment by jmcarp** [comment]
This looks similar to (and maybe the same as) #496. Can we close one issue in favor of the other? Are we ready to start work on this? Ping @arowla @LindsayYoung.

**Comment by arowla** [comment]
Agree this looks like a duplicate of #496. @LindsayYoung ?

**Comment by LindsayYoung** [comment]
agreed
