### ISSUE TITLE
Add address to committee history endpoint

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#846]
Address not showing when accessing committee page via the filter.  When I access the 10,000 Lakes committee via the Committee page and date filter, only the state displays:

![screen shot 2015-05-27 at 12 37 27 pm](https://cloud.githubusercontent.com/assets/10507124/7841760/eef8c776-046c-11e5-90cb-d63ea73913d2.png)

But when I search for 10,000 Lakes via the search box and access the page via the search results, the full address is displayed:

![screen shot 2015-05-27 at 12 37 40 pm](https://cloud.githubusercontent.com/assets/10507124/7841761/f50921d8-046c-11e5-94ea-f1b91a20decd.png)

Address is also not showing correctly for http://fec-dev-web.cf.18f.us/committee/C00522771?cycle=2012 and http://fec-dev-web.cf.18f.us/committee/C00498212?cycle=2016

Tested on dev.

**Comment by LindsayYoung** [comment]
this is because we don't have full address in committee history - good catch!
