### ISSUE TITLE
Design way to show sub-totals on committee page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#847]
We want to list things like "Total Individual Contributions" and "Total Operating Expenses" but need to design the report summary view to accomodate.

**Comment by noahmanger** [comment]
So here's a couple ideas. In both cases I think it's good to show the sub-sub-totals in the same row as the sub-total, rather than having an extra layer of collapse. 

The one challenge I see is how to show the bar chart. In option 1, we could do it by showing the proportion each sub-sub-total constitutes.

![option 1](https://cloud.githubusercontent.com/assets/1696495/8011699/b5e08d84-0b6f-11e5-909f-37f26ceb113e.png)

In option 2, we just show bars for each sub-sub-total but not the sub-total. 

![option 2](https://cloud.githubusercontent.com/assets/1696495/8011702/c155ba7c-0b6f-11e5-8fe6-f09e81e4a55e.png)

Thoughts?

**Comment by LindsayYoung** [comment]
I really like the first one.

**Comment by noahmanger** [comment]
First one will require tweaking the chart js. @msecret what do you think?

**Comment by noahmanger** [comment]
@LindsayYoung we still need to implement this, don't we?

**Comment by LindsayYoung** [comment]
yes, that ticket is #898 

(We should close one of these tickets- I don't have a preference on which one.)

**Comment by noahmanger** [comment]
Oh cool. Let's close this one. I'll move the comps over to #898.
