### ISSUE TITLE
Update Joint Fundraiser page to show that related candidate list not exhaustive

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#848]
## Option 1
On Joint Fundraisers, move the related candidate list out of the top and add a message about how this isn't all the data so there's other committees that may be related.

## Option 2
Show a new box, like "Related Committees" but explain that we don't have the data yet and say "Coming Soon".

**Comment by noahmanger** [comment]
Another idea: We could include a glossary definition for "Related Candidates" in the header that said something like "These are the candidates listed on this committee's Form 1 filing. This is not the complete list of any candidate or committee who has received money from this joint fundraiser."

**Comment by noahmanger** [comment]
Also: we could extend this same concept to "Filings" (showing a Coming Soon box on that tab).

**Comment by noahmanger** [comment]
Just realized we never resolved this. @LindsayYoung what do you recommend?

**Comment by LindsayYoung** [comment]
I like the glossary option the best

**Comment by noahmanger** [comment]
Is this still something we need to worry about?

**Comment by LindsayYoung** [comment]
We have the explanation as text, which is works for me.
