### ISSUE TITLE
Don't transform committee names to lowercase in site title

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#851]
Little bug that'd be nice to fix:

![screen shot 2015-05-27 at 9 43 48 am](https://cloud.githubusercontent.com/assets/1696495/7842060/a7cf492c-0455-11e5-94b8-73f845dcf64e.png)

Should be `NRSC`.

**Comment by jmcarp** [comment]
Fixed in https://github.com/18F/openFEC-web-app/pull/208.
