### ISSUE TITLE
To make search more flexible, enable searching by nicknames

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#854]
the `q=` kinds of searches are not catching nick names or slight misspellings. I am guessing we could make a more forgiving search if we use sounds like `~`, rather than`=` (I might not be thinking of postgres syntax but I mean whatever will do a more forgiving search)

**Comment by jmcarp** [comment]
Looks like we have a few different options here.

* Postgres full-text search allows the use of custom synonym dictionaries, which could help with nicknames (liz => elizabeth, betsy => elizabeth, bob => robert).
* For a small number of idiosyncratic nicknames (John Ellis => Jeb), we could use the approach we're taking with PACronyms: make a table of name mappings, and join them to the candidate full text search view
* For typos and misspellings, Postgres also has a range of similarity queries (trigram similarity seems to be the most full-featured, but there are other options). This can be used to to suggest better queries on searches with no results ("Did you mean...?").

Thoughts @arowla @LindsayYoung? Have you run into this before @catherinedevlin?

**Comment by arowla** [comment]
If we want to go the route of having a list of idiosyncratic nicknames-- which I think would be a good option in concert with perhaps some fuzzy matching in postgres, like levenshtein distance or soundex-- there are a couple lists of nickname mappings that I/we developed at Sunlight in response to data from the FEC:

https://github.com/sunlightlabs/name-cleaver/blob/master/name_cleaver/nicknames.py
https://github.com/sunlightlabs/datacommons/blob/a8b33cc5a24afe7b8ffcc690ab58b3c84fb0c348/dcentity/tools/nicknames.txt

**Comment by jmcarp** [comment]
Great! So adding a synonym dictionary based on `nicknames.txt` might be a good place to start.

For similarity measures, I get the impression that different methods (soundex, trigram, etc.) have different performance characteristics and handle different use cases better or worse--this would probably require some experimentation to make a good choice.

**Comment by noahmanger** [comment]
Not sure if this is covered with fuzzy matching, but it's also important to account for common misspellings (e.g. "hilary" with one L).

**Comment by LindsayYoung** [comment]
I like where this is headed! Adding nicknames is a great idea and I don't have a preference to which kind of fuzzy matching, as long as we have something.

**Comment by arowla** [comment]
One thing we'll need to find out is whether we can add custom dictionaries
in RDS.

**Comment by noahmanger** [comment]
Story card: https://18f.storiesonboard.com/m/fec/!card/71Cv_9xvjTU3dTnTx3CXqg
