### ISSUE TITLE
Candidate filtering

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#855]
It would be useful to filter House, Senate or Presidential.

**Comment by noahmanger** [comment]
You can do this, no? "Office Sought"

**Comment by LindsayYoung** [comment]
Yes, it is `office=P`, `S` or `H` on the `/candidates` endpoint. It just needs a filter tool.

**Comment by noahmanger** [comment]
Like this? Am I missing something? 
![screen shot 2015-05-27 at 12 53 19 pm](https://cloud.githubusercontent.com/assets/1696495/7845975/657fe88c-046f-11e5-85f9-f972094020d8.png)

**Comment by LindsayYoung** [comment]
It is already on the page !!

Sorry for being slow about that

**Comment by noahmanger** [comment]
The best kind of issue: one that's already been solved :)
