### ISSUE TITLE
add an api key input for the try it out feature

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#863]
Currently, users can't add an api key and therefor can't use the try it out function in the docs on api.open.fec.gov

**Comment by jmcarp** [comment]
Proposal: Add a required `api_key` parameter, but only when running in production. We could also include a default API key so that users don't have to register just to mess with the API. Thoughts @LindsayYoung?

**Comment by LindsayYoung** [comment]
I like it! My only worry is if the sample api key gets over used and then it will look like the API is broken.

**Comment by jmcarp** [comment]
Good point. I submitted a patch without the default key. The API docs link to api.data.gov, so users should be able to figure out how to get a key. If people find it confusing, we can reconsider the default key.
