### ISSUE TITLE
API version in response should match url spacing

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#868]
We say v1 in the url and 0.2 in the body. The 0.2 was really just a placeholder.  We should set that in a central location while we are at it.

**Comment by jmcarp** [comment]
I'm working on some API docs updates at the moment. Will take care of this.

**Comment by LindsayYoung** [comment]
You write code faster than I can write issues :)

**Comment by jmcarp** [comment]
Fixed in https://github.com/18F/openFEC/commit/e510bc55a863150e1c3f0076f4285c993c876616.
