### ISSUE TITLE
Glossary needs response when someone searches for something we don't have

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#869]
Now, users just think it is unresponsive or broken.

**Comment by andrewmaier** [comment]
I think we should list all the terms by default (in the side panel) and have the search work as a filter. Showing all the options helps people understand the vocabulary, especially in a situation where they're unfamiliar for what they might search for.

**Comment by noahmanger** [comment]
Agreed. I've been wanting to shift to this style as well. Happy to work on
it if we want to prioritize.

On Fri, May 29, 2015 at 7:52 AM, Andrew Maier <notifications@github.com>
wrote:

> I think we should list all the terms by default (in the side panel) and
> have the search work as a filter. Showing all the options helps people
> understand the vocabulary, especially in a situation where they're
> unfamiliar for what they might search for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/869#issuecomment-106837324>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
We are chugging along on the other bugs. Can we prioritize this, now?

**Comment by noahmanger** [comment]
Yep! This is a [WIP] PR over here: https://github.com/18F/openFEC-web-app/pull/231

Would be great if someone could take a look to address the couple points I mentioned.

**Comment by LindsayYoung** [comment]
Thanks!

**Comment by jmcarp** [comment]
18F/openFEC-web-app#231 is merged.
