### ISSUE TITLE
Filter out old links on web app

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#870]
Don't link to pdfs before 1994.

**Comment by jmcarp** [comment]
I think this is a another argument in favor of building PDF links on the API side--IMO it makes more sense for business rules like this (PDFs are only available for 1994 and later) in the API than in the webapp.

**Comment by LindsayYoung** [comment]
Agreed!

**Comment by dcpcc1967** [comment]
More details about pdf availability 

Older paper reports are availabe with the following limitations:  
	PAC and party reports since 1993 
	House committee reports since May 1996
	Senate filings since May 2000

http://www.fec.gov/finance/disclosure/help_candidate_committee_viewer.shtml

**Comment by LindsayYoung** [comment]
Thanks Paul moving this to issue #901
