### ISSUE TITLE
Hamburger nav: ESC key should close the menu

### ISSUE THREAD

**Issue by andrewmaier** [18F/openFEC#872]
![image](https://cloud.githubusercontent.com/assets/2970/7885352/5f2108f8-05f1-11e5-861f-cf80f6c88337.png)

The escape key is usually used to "get people out of a mode" (lightboxes, spotlight search, etc.). In this case it should close the menu. Also, the "close menu" box covers the content at small sizes.

**Comment by jmcarp** [comment]
Fixed in https://github.com/18F/openFEC-web-app/pull/253.
