### ISSUE TITLE
Display browser warning

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#875]
IIRC, we were only asked to support IE 10+ right? If so, we need to show a warning for older versions.

**Comment by LindsayYoung** [comment]
Yes, that is what Wei said. Feel free to email him to confirm. It seems like quite a few people in the FEC were having ie problems.

**Comment by noahmanger** [comment]
In my experience, they all have other browsers available. I think we just
need to tell them.

On Fri, May 29, 2015 at 10:45 AM, Lindsay Young <notifications@github.com>
wrote:

> Yes, that is what Wei said. Feel free to email him to confirm. It seems
> like quite a few people in the FEC were having ie problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/875#issuecomment-106884090>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by msecret** [comment]
We built one of these for Peace Corps, it used a condition in the HTML like this:

```
<!--[if lte IE 8]>
  <section>
    <h2>Your browser is out of date.</h2>
    <p style="color: #000;">
      You are using an older version of Internet Explorer. For a better
      experience, please update your browser to the latest version.
    </p>
    <p>
      <a target="_blank"
         href="http://browsehappy.com/">Learn how to update your browser.</a>
    </p>
  </section>
<![endif]-->
```

**Comment by noahmanger** [comment]
Oh nice. So I just looked at it in IE 8 and it's *super* broken. What do
you think about doing this through a js alert so it's super obvious?

On Mon, Jun 1, 2015 at 11:50 AM, Marco Segreto <notifications@github.com>
wrote:

> We built one of these for Peace Corps, it used a condition in the HTML
> like this:
>
> 
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/875#issuecomment-107669644>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by emileighoutlaw** [comment]
I like the language @msecret provided. If we go with that, I'd suggest a minor tweak to something like:

"You're using an older version of Internet Explorer. Please update your browser for a better experience."

**Comment by noahmanger** [comment]
I like it. Maybe on more slight tweak: 

```
Your browser is  out of date

You are using an older version of Internet Explorer. Please update your browser or switch to another browser like Chrome, Firefox or Safari for a better experience

Learn how to update your browser.
```

**Comment by emileighoutlaw** [comment]
Last round of input, I promise!:

Your browser is outdated.

You're using an older version of Internet Explorer. Please update or switch to another browser like Chrome, Firefox, or Safari for a better experience.

Learn how to update your browser.

**Comment by noahmanger** [comment]
:+1:

**Comment by noahmanger** [comment]
Implemented https://github.com/18F/openFEC-web-app/pull/238
