### ISSUE TITLE
Candidates and Committees triggering "Oops We Messed Up" errors

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#879]
The following candidates/committees consistently trigger an "Oops: We messed up. We just experienced a server issue. Please try reloading the page." error on dev:

http://fec-dev-web.cf.18f.us/committee/C00262121
http://fec-dev-web.cf.18f.us/committee/C00486647?cycle=2012
http://fec-dev-web.cf.18f.us/candidate/P20000378

**Comment by LindsayYoung** [comment]
I am seeing info on the API for those

**Comment by LindsayYoung** [comment]
/committee/C00486647?cycle=2012 is still outstanding, will look at that now

**Comment by LindsayYoung** [comment]
It is working locally for me on develop

**Comment by rdpiazza** [comment]
Still seeing the error on dev.  Not sure when your last deployment was.

**Comment by rdpiazza** [comment]
To clarify, just seeing the error on dev for /committee/C00486647?cycle=2012.  Other two are working.

**Comment by LindsayYoung** [comment]
confirmed with @rdpiazza that it is working
