### ISSUE TITLE
Bootstrap script doesn't export all necessary env vars

### ISSUE THREAD

**Issue by jeremiak** [18F/openFEC#894]
Following the directions on the readme for installation results in an error when trying to run the web-app. The manifestation of the problem is that the web-app doesn't start and just hangs on the terminal.

I think it is because [the bootstrap script](https://github.com/18F/openFEC/blob/develop/scripts/bootstrap/fec_bootstrap.sh#L46-L47) exports two env vars for use by the [web-app](http://github.com/18f/openFEC-web-app) but the app also needs `FEC_WEB_DEBUG`, the value of which is a boolean.

**Comment by LindsayYoung** [comment]
We are not maintaining the bootstrap script and the set up instructions are pretty good at this point.

Feel free to re-open if needed.
