### ISSUE TITLE
Summary charts are not dealing with negatives

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#895]
Negative numbers are charted as if they are positive
example -$10,000 in http://fec-dev-web.cf.18f.us/committee/C00105973
![screen shot 2015-06-02 at 4 48 10 pm](https://cloud.githubusercontent.com/assets/4406333/7946839/2e905442-0947-11e5-97d3-cbfda0ca77ec.png)

from #884

**Comment by msecret** [comment]
@LindsayYoung finished with this: https://github.com/18F/openFEC-web-app/pull/230
