### ISSUE TITLE
Summary charts are not handling "None"

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#896]
None is treated as 100%

It is important to show it as "None" instead of 0 because, if it is none it could be that the data is not processed and you would want to look at the original document for the real amount.

example: http://fec-dev-web.cf.18f.us/committee/C00523274?cycle=2012
![screen shot 2015-06-02 at 5 00 47 pm](https://cloud.githubusercontent.com/assets/4406333/7947111/06ee194a-0949-11e5-82b4-d0e3e75b0e32.png)

from #884

**Comment by msecret** [comment]
@LindsayYoung fixed here: https://github.com/18F/openFEC-web-app/pull/229
