### ISSUE TITLE
Look at recipts and disbursements at the same time

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#897]
Right now I can't check a whole form at once. It would be easier for people that care about reports to seel the whole report summary if they want to. 

This is more of a feature request, than a bug. 

from #884

**Comment by msecret** [comment]
Just so this is clear, we want to ensure that opening one accordion item will not close any others?

**Comment by LindsayYoung** [comment]
I would prefer that they stay open. 

I think other power users would too. I am up for not doing it if we think it will impede other users. And it is something we can test with users later, either way.

**Comment by msecret** [comment]
Fixed here: https://github.com/18F/openFEC-web-app/pull/228, @LindsayYoung please verify.

**Comment by LindsayYoung** [comment]
Yes, this is great, thank you!
