### ISSUE TITLE
make the "None" result in table generate a (?) link to the glossary

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#899]
We can explain why something is "none" and encourage people to look at the source documents.

This depends on None being added to the glossary 18F/openFEC-web-app#231 and correct charting  of None #896. 

@msecret, if you have time I think you could get this done faster than I can, but I am happy to jump in on this one if you are busy. Thanks!

**Comment by noahmanger** [comment]
Waiting here: https://github.com/18F/openFEC-web-app/pull/235

**Comment by jmcarp** [comment]
18F/openFEC-web-app#235 is merged and deployed to develop. Closing.
