### ISSUE TITLE
Allow users to toggle between list and table views

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#903]
On small screens it would be great to allow users the ability to toggle the presentation of the datatables between a collapsible list and a table with a fixed left column and overflow scrolling. 

Not important, but Josh and I talked about it and wanted to log it here.

Toggle could look something like this and could live in the filters area.

![toggle-icon](https://cloud.githubusercontent.com/assets/1696495/7967450/03c92674-09df-11e5-91c4-8c0d089db942.png)

**Comment by jmcarp** [comment]
For record-keeping: we're going to use https://datatables.net/extensions/responsive/ for now, and could implement fixed columns with https://datatables.net/extensions/fixedcolumns/.

**Comment by leahbannon** [comment]
No longer relevant
