### ISSUE TITLE
Minify and gzip assets

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#905]
Our bundled JS currently clocks in at 2.4 MB on develop. Not pretty on 3G. We should minify assets in production and serve gzipped assets for client that accept it.

**Comment by noahmanger** [comment]
YIKES. Yes, def.

On Wed, Jun 3, 2015 at 12:28 PM, Joshua Carp <notifications@github.com>
wrote:

> Our bundled JS currently clocks in at 2.4 MB on develop. Not pretty on 3G.
> We should minify assets in production and serve gzipped assets for client
> that accept it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/905>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
