### ISSUE TITLE
Add warning if javascript is disabled

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#911]
The datatable filters don't work without javascript. We should either have a server side fallback or just show a warning. While we're in beta I think it's fine to show a warning.

**Comment by msecret** [comment]
Should this warning only appear on certain pages (such as the ones that have broken functionality)? What should the UI be for the warning?

**Comment by noahmanger** [comment]
What do you think about just replicating the old IE warning we're using? It would be universal, but I think that's ok. We could keep the wording sufficiently broad, like:

> **Javascript Required**
OpenFEC uses Javascript to provide the best possible user experience. Please enable Javascript in your browser or visit fec.gov.

@emileighoutlaw what do you think about the language?

For an example, here's what Facebook uses: 
>JavaScript Required
We're sorry, but Facebook doesn't work properly without JavaScript enabled. If you can't enable JavaScript try visiting the mobile-optimized website.

**Comment by jmcarp** [comment]
:+1: to a universal warning. Lots of stuff is going to break without JS, and I don't want to deal with the overhead of updating per-page warnings when we add or remove JS from different pages.

**Comment by msecret** [comment]
https://github.com/18F/openFEC-web-app/pull/260

**Comment by jmcarp** [comment]
Merged.
