### ISSUE TITLE
Social media tags

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#931]
So it looks pretty when users share the new site on social media.

**Comment by noahmanger** [comment]
I'll work on the code. @jenniferthibault is on the images. @emileighoutlaw I'll probably want help on text here soon.

**Comment by noahmanger** [comment]
So we need a description tag. How does this work: 

```OpenFEC is the Federal Election Commission's new app for exploring federal campaign finance data. Use OpenFEC to see how much money candidates raised and how they raised it; how much they spent and how they spent it; and more.```

Should we mention it's in beta?

**Comment by LindsayYoung** [comment]
Please mention that it is a beta. 

For now, we might want to say something like:

OpenFEC is the Federal Election Commission's new app for exploring federal campaign finance data. Use OpenFEC to see how much money candidates raise and spend on elections; and more.

We don't have the "how they raised it" and the "how they spent it" yet, that will be schedule A and schedule B, respectively.

**Comment by jenniferthibault** [comment]
4 options: these are the sizes for twitter, but I have large FB sizes ready too.

Aesthetically, I like the two options that rely on the OpenFEC logo best, BUT I think the other two that do not rely on this logo might be more future-proof if we decide to un-brand the page when it migrates into the FEC site proper later on. 

Option 1
![twitter copy 2](https://cloud.githubusercontent.com/assets/11636908/8070650/d31ffefc-0ed0-11e5-9b92-d6f9bb9b33b9.png)

Option 2
![twitter copy](https://cloud.githubusercontent.com/assets/11636908/8070649/d31e9fb2-0ed0-11e5-9452-48cd887240bc.png)

Option 3
![twitter](https://cloud.githubusercontent.com/assets/11636908/8070651/d320a262-0ed0-11e5-8c00-f39e325f24a1.png)

Option 4
![twitter copy 3](https://cloud.githubusercontent.com/assets/11636908/8070652/d321766a-0ed0-11e5-835f-385482bd7f93.png)

**Comment by noahmanger** [comment]
Oh nice. Yeah I think I'm with you. I like the idea of the candidate and committee icons, but still not happy enough with the icons themselves to think they work. Also, should we put a little "beta" bug on here somewhere? Like in the corner?

I think that something with the graphs might work. But probably would just want to do bars without all the other numbers, which you can't read.

**Comment by noahmanger** [comment]
This is ugly but an idea?

![twitter copy](https://cloud.githubusercontent.com/assets/1696495/8070966/9579e4fc-0eba-11e5-8e3f-796b4f4c7665.png)

**Comment by noahmanger** [comment]
Separate Q: If someone shares a candidate or committee page, should the title when shared show up as the person's name? Or stay general?

**Comment by LindsayYoung** [comment]
I think it should include name of candidate or committee if it is a profile page.

**Comment by jenniferthibault** [comment]
I dig it @noahmanger ! I'll play around a bit with that concept tomorrow morning

**Comment by jenniferthibault** [comment]
A couple iterations on that concept: 
I keep leaning toward a dark background in order to contrast with facebook and twitter's native design, which would be a light background color.

![twitter copy 4](https://cloud.githubusercontent.com/assets/11636908/8087577/ca57467e-0f69-11e5-876a-9742b778ae56.png)
![twitter copy 5](https://cloud.githubusercontent.com/assets/11636908/8087578/ca5745f2-0f69-11e5-9b2c-81b6716c8b58.png)

**Comment by noahmanger** [comment]
Oooh yeah! I love the dark one. That's slick.

**Comment by rdpiazza** [comment]
I like the dark one!  Looks slick, @jenniferthibault!

**Comment by jmcarp** [comment]
PR merged.
