### ISSUE TITLE
To help more users access the API , build API clients with swagger-codegen

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#932]
Since we have Swagger markup for our API, we get API clients in many languages for free through https://github.com/swagger-api/swagger-codegen. Minimally, I think we should roll out clients for python 2/3. These can be released to the PyPI after the public release.

**Comment by jmcarp** [comment]
Would this be useful to you @boblannon?

**Comment by boblannon** [comment]
oh yeah, possibly.  i'd be interested to see what it generates, though.  as i mentioned in #980, the interactive docs are currently generating incorrect request URLs.

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/uQ5Q2HFupU4M3znUEFZhfg

**Comment by evankroske** [comment]
I'm not sure what the point is of GitHub issues linked to private content.
Is there a way for outside contributors to view the 18F story board?

**Comment by noahmanger** [comment]
@evankroske We're using Stories on Board just for planning purposes, there's not much additional information and the link is just for reference. But that's a good point and I'm going to look into if it's possible to open the board to the public, or alternatively just include more information alongside the link.

**Comment by noahmanger** [comment]
@evankroske just to follow up, I was able to make the story map public in a read-only view. Thanks for bringing this up!
