### ISSUE TITLE
point dev api back at the dev db

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#936]
So dev and production are separate again.

Dependent on #935

**Comment by arowla** [comment]
I just checked and this seems to already be the case..?

**Comment by jmcarp** [comment]
Yep, the dev API should have switched back to the dev RDS with the merge of blue-green deploys. Going forward, `SQLA_CONN` is set through CF user-provided services and can be updated with `cf uups -p '{"SQLA_CONN": "..."}'`.

**Comment by LindsayYoung** [comment]
Ok, we are asking the FEC is still testing on dev, and the dev db doesn't have all the data. We need to get #935 done quickly if we can.

**Comment by jmcarp** [comment]
All right, I'll get on #935 next.
