### ISSUE TITLE
Document deployment workflow

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#942]
I'd like to agree on and document our branching workflow for clarity, and to validate our continuous deployment logic. I've written up the workflow that (I think--correct me if I'm wrong!) is implied by @arowla's latest work on  #783. If I'm describing everything correctly and nobody wants to make changes, we can merge #783 and add this to the README. I would definitely like to clarify exactly how and when releases get released--see my question at the bottom.

Pinging @arowla @LindsayYoung @noahmanger @msecret.

Feature:
Developer creates feature branch
Reviewer merges feature branch into develop and pushes to origin
[auto] Develop is deployed to dev

Hotfix:
Developer creates hotfix branch
Reviewer merges hotfix branch into master and pushes to origin
[auto] Master is deployed to prod

Release:
Developer creates release branch
Developer pushes release branch to origin
[auto] Release branch is deployed to stage
<something happens>
Developer merges release branch into master and pushes to origin
[auto] Master is deployed to prod

I think this is a reasonable approach, with a few uncertainties. When do we start a release branch? How do we know when a release is ready to merge into master? I've indicated the uncertainty above with <something happens>. Are we doing QA on staging? Getting review from FEC?

**Comment by LindsayYoung** [comment]
Thank you for documenting this!

**Comment by jmcarp** [comment]
This still needs work--comments appreciated!

**Comment by arowla** [comment]
This looks good to me! I think that we should have some sort of QA process on staging. We should check all the features that were slated to be released, as well as each type of "entity" page and that features such as typeahead work.

**Comment by arowla** [comment]
To that end ^^ we might want to figure out how to roll up a Changelog for each release...

**Comment by jmcarp** [comment]
Ok, I'm going to write this up with a little more detail and add to the docs. Then I'll merge the related PRs from @arowla and we'll have a flawless CD workflow.

**Comment by arowla** [comment]
Looking forward to the flawlessness.

**Comment by LindsayYoung** [comment]
I have never been flawless before I wonder what it will feel like.

**Comment by arowla** [comment]
:gem:
