### ISSUE TITLE
To help users find the most relevant results, develop a better method of weighting search and typeahead results

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#943]
Improve search

**Comment by jmcarp** [comment]
Search results aren't sorted alphabetically now: they're ordered by text similarity rank (`ts_rank_cd`) with the input query. Based on conversation earlier today, maybe what we're looking for is a combined weighting by text similarity and some index of importance--maybe total funds raised or something similar.

**Comment by LindsayYoung** [comment]
That it looks alphabetical on the web app

http://fec-dev-web.cf.18f.us/?search_type=committees&search=dccc

http://fec-dev-web.cf.18f.us/?search_type=committees&search=republican

**Comment by jmcarp** [comment]
Oh, I was looking at typeahead search. If the ordering of the typeahead results is correct (or correct enough), it would be really easy to make the `search_type` results use the same order.

**Comment by jmcarp** [comment]
After a bit of digging into this, it actually looks like our sorting on full-text columns has been kind of random all along. Our text vectors and queries are simple enough that text similarity values are mostly small integers that effectively count up the number of times the query tokens occur in the vector (example below). That means that searching for a query like "republican" more or less returns a randomly ordered list of committees that include "republican" in their names.

Postgres includes some normalization methods that weight by the inverse of the length of the string, which makes some intuitive sense--basically weighting by the proportion of words in the vector that belong to the query. But in practice, this just weights towards shorter names, which probably isn't a great proxy for relevance. Again, maybe weighting be recency, money raised, etc. would be helpful.

Thoughts @LindsayYoung @arowla @noahmanger? What are good metrics of search relevance for our users?

```
fec=> select name, ts_rank_cd(fulltxt, query) as rank from ofec_committee_fulltext_mv, to_tsquery('republican' || ':*') query where query @@ fulltxt order by rank desc;
                                                          name                                                          | rank
------------------------------------------------------------------------------------------------------------------------+------
 NEW ALLIANCE OF CALIFORNIA REPUBLICANS-FEDERAL                                                                         |    2
 REPUBLICAN CLUB OF DALLAS: FKA DALLAS COUNTY REPUBLICAN MEN'S CLUB PAC                                                 |    2
 ARIZONA FEDERATION OF COLLEGE REPUBLICANS AZ COLLEGE REPUBLICANS                                                       |    2
 FUND FOR A REPUBLICAN MAJORITY (FKA-REPUBLICAN WHIP LEADERSHIP FUND)                                                   |    2
 TEXAS REPUBLICAN-INDEPENDENT POLITICAL ACTION COMMITTEE                                                                |    2
 REPUBLICANS FOR REPUBLICAN VALUES                                                                                      |    2
 COMMITTED REPUBLICANS FOR A REPUBLICAN PRESIDENT (UNCOMMITTED)                                                         |    2
 REPUBLICAN WOMEN'S NETWORK OF THE ILLINOIS FEDERATION OF REPUBLICAN WOMEN                                              |    2
 REPUBLICAN NATIONAL COMMITTEE - CONTRIBUTIONS (AKA REPUBLICAN NATIONAL FINANCE COMMITTEE                               |    2
 REPUBLICAN VICTORY COMMITTEE (RVC) CLARK COUNTY REPUBLICAN PARTY                                                       |    2
```

**Comment by LindsayYoung** [comment]
I would think money first, to make the big players easier to find, and then recency.

**Comment by noahmanger** [comment]
I agree: money first, recency second...in theory. But are we looking at money in the current two year period or overall? Maybe it's a moot point, but I can imagine a scenario where the "more popular" term had a bunch of activity 10 years ago, but less now. Not sure which one we'd want to weight higher.

**Comment by noahmanger** [comment]
I imagine this as just being an issue with common words like "republican", "democrat", "america", etc. Two other ideas come to mind (and I'm getting out of my depth a bit, so pardon):
1. What if we built a table of the most popular pages, and those were elevated as a separate group of results in typeahead? 
2. There might be an intermediate, MVP-type step where we just hand curate a list of the top 10 or 20 pages we'd expect to be in this list and do the same.

**Comment by LindsayYoung** [comment]
I think the most popular searches are going to be about things in the news
 - Candidates
 - High-profile big spending groups
 - New committees, more so now at this early stage, when people first announce. (Ironically there is nothing interesting there yet)

Do we have a doc of things we want to validate with usability testing? Because, I would like user feedback on this.

**Comment by LindsayYoung** [comment]
@noahmanger I think money raised or spent would be a good proxy for a hand-curated list of well known groups.

**Comment by noahmanger** [comment]
Agreed. This sounds like a great thing to test with a prototype. I'll start a doc. Also, I think it'd be great to label issues where questions pop up that we want to evaluate (so I'll do that too).

**Comment by jmcarp** [comment]
Should this be implemented now and adjusted after more research, or should we hold off entirely until getting user feedback?

**Comment by LindsayYoung** [comment]
Maybe this would be an easy thing to add when we are doing #854

**Comment by LindsayYoung** [comment]
It looks like the API adding default alphabetical sorting to the search results, so they are not returned by relevance:

http://fec-dev-api.cf.18f.us/v1/committees?q=republican

**Comment by jmcarp** [comment]
I was thinking the same thing, but that's not exactly what's going on. Here's what happens:

* When a `q` query param is passed, we order by text vector similarity
* Then we apply the default sort, or any other user-specified sort

What this means is that we're currently using name to break ties in text vector similarity. And because almost all matching rows are going to have the same text similarity (see the sql output I pasted earlier in the issue), all rows are tied--meaning we're effectively sorting by name.

So the good news is that our sort logic is working. The bad news is that our relevance metric is lousy, and rates all matching candidates with a value of 1.

**Comment by noahmanger** [comment]
Just some updates:
- Relabled the title of the issue
- See https://github.com/18F/openFEC/pull/1252 for additional discussion; the main takeaway being that weighting by some combination of last year active and money raised will help
- And then just a reminder that this needs to be thought of as part of an overall search redesign happening after launch

**Comment by noahmanger** [comment]
Captured in this card: https://18f.storiesonboard.com/m/fec/!card/wSGgSXZuf80AgDnTp-lBUQ

**Comment by noahmanger** [comment]
Bumping this into this sprint. Sorry, forgot to assign this to someone, so assigning to @jmcarp as Lindsay has a good chunk of things this sprint.

**Comment by noahmanger** [comment]
This has been implemented. If we learn we need to refine the weighting, we can make a new issue.
