### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#944]

**Comment by rdpiazza** [comment]
Sent draft to FEC on 15 June

**Comment by emileighoutlaw** [comment]
Revised version ready for resend to FEC.

https://docs.google.com/document/d/1P9xfQ0aysfSgqstPS32WmSTzshDBF74ZkYxsXsKDPGY/edit

**Comment by noahmanger** [comment]
This is done, right?

**Comment by emileighoutlaw** [comment]
I'm going to close it here, because we have an open issue for it in blog-drafts. We can review again when it's time to actually publish.
