### ISSUE TITLE
Ethnio

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#946]

**Comment by leahbannon** [comment]
- write questions for pop up
- ensure this is cleared as part of our ATO
- embed javascript

**Comment by onezerojeremy** [comment]
Thanks for starting this, Leah! Here's the link to details on placing the JS, which @msecret mentioned he might be able to help us out on.  
http://help.ethn.io/hc/en-us/articles/200202455-Placing-Ethnio-Javascript-The-Details

Not sure how to check on the ATO side of things, Can you handle or assign that part @leahbannon ? 

I'll work with Noah and Andrew on a couple simple questions.

**Comment by konklone** [comment]
A small note, Ethnio's docs say this:

> src="//ethn.io/remotes/xxxxx" - the // allows you to place it on a SSL or regular HTTP page without changing the code. It cleverly assigns HTTPS or HTTP dynamically.

Don't use the protocol-relative version -- use a full `https://` URL.

**Comment by leahbannon** [comment]
great catch, thanks @konklone

**Comment by noahmanger** [comment]
Where are we at on this?

**Comment by noahmanger** [comment]
This is added to the developer docs but we should look into adding it to fec.gov

**Comment by leahbannon** [comment]
Yep! I'm working out upgrading our account (which seems like it will be much easier than I expected) and I just gave Wei a heads up.
