### ISSUE TITLE
to be professional looking, we should add a favicon for the API

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#948]
I think it would me nice if it had the same favicon as the web app.

**Comment by noahmanger** [comment]
:+1: @jenniferthibault is going to redesign the web app favicon, so we can drop that in to the API when it's done.

**Comment by noahmanger** [comment]
Part of restyled visuals for the API docs: https://18f.storiesonboard.com/m/fec/!card/CyMvgJfu79y4FznTzDMKww
