### ISSUE TITLE
Obama 2012 Transfers are "None", should have value

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#950]
Obama for America, Details Summary 2011-2012 shows "None" for 'Transfer from Affiliated Committees' and 'Transfer to Authorized Committees.' There is an FEC Glossary link to click, but none of the suggested common reasons apply in this situation. Value should be 181,700,000. The number looks good in the database.

http://fec-dev-web.cf.18f.us/committee/C00431445?cycle=2012

**Comment by LindsayYoung** [comment]
The real problem is that the development box is pointing at incomplete data. This is fixed in production, but to see this in development we need to address #935

**Comment by jmcarp** [comment]
This one looks to be a typo. I am working on #935 though :smiley:

**Comment by LindsayYoung** [comment]
Ok, I have a fix for that waiting in 18F/openFEC-web-app#255

**Comment by jmcarp** [comment]
Lindsay's patch has been merged. Closing.
