### ISSUE TITLE
review blog post draft

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC#953]
(I want to keep track of this in our pre-launch check list.)
https://docs.google.com/document/d/1P9xfQ0aysfSgqstPS32WmSTzshDBF74ZkYxsXsKDPGY/edit

People who need to review https://github.com/18F/blog-drafts/issues/205#issuecomment-110179071 (everyone is welcome to):
- [x] @LindsayYoung 
- [ ] @noahmanger 
- [x] @leahbannon

**Comment by kategarklavs** [comment]
Also @NoahKunin!
