### ISSUE TITLE
Disambiguate typeahead results for Scott Brown

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#955]
Scott Brown has run for Senate in two states, so he gets two results in the typeahead search that are difficult to disambiguate--both say "Scott Brown - Senate", modulo a middle initial. To handle cases like these, we could change the office label from "Senate" to e.g. "NH Senate". Or maybe it's too rare an edge case to worry about. Thoughts?
![screen shot 2015-06-10 at 3 34 34 pm](https://cloud.githubusercontent.com/assets/1633460/8092282/acecc998-0f86-11e5-80b6-7ae03442141c.png)

**Comment by arowla** [comment]
I'd be in favor of changing it to "Senate - NH"

On Wed, Jun 10, 2015 at 3:38 PM, Joshua Carp <notifications@github.com>
wrote:

> Scott Brown has run for Senate in two states, so he gets two results in
> the typeahead search that are difficult to disambiguate--both say "Scott
> Brown - Senate", modulo a middle initial. To handle cases like these, we
> could change the office label from "Senate" to e.g. "NH Senate". Or maybe
> it's too rare an edge case to worry about. Thoughts?
> [image: screen shot 2015-06-10 at 3 34 34 pm]
> <https://cloud.githubusercontent.com/assets/1633460/8092282/acecc998-0f86-11e5-80b6-7ae03442141c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/955>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by LindsayYoung** [comment]
Are we talking about changing it everywhere or just for Scott Brown?

**Comment by LindsayYoung** [comment]
The more I think about it, I would rather the typeahead have more room for the name, since that is the most important part. If people don't know which choice they want they can hit enter and see the search results with full descriptions.

**Comment by arowla** [comment]
I am not sure the UI is clear on that. Thinking back on it, I almost never
hit "enter"-- I always just arrow key or mouse down to the typeahead result
I want.

On Wed, Jun 10, 2015 at 3:58 PM, Lindsay Young <notifications@github.com>
wrote:

> The more I think about it, I would rather the typeahead have more room for
> the name, since that is the most important part. If people don't know which
> choice they want they can hit enter and see the search results with full
> descriptions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/issues/955#issuecomment-110893035>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by LindsayYoung** [comment]
It sounds like we could use some usability testing for this feature
