### ISSUE TITLE
Include cycles from principal committee in candidate active cycles

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC#956]
We currently compute a candidate's active election cycles from her `election_yr` values. During discussion of a related issue (see https://github.com/18F/openFEC-web-app/pull/247#issuecomment-110759148), we learned that the current FEC site computes active cycles based on filings from associated principal campaign committees. @PaulClark2 confirmed that we should be doing this for OpenFEC as well.

**Comment by noahmanger** [comment]
Is this still relevant?

**Comment by jmcarp** [comment]
Relevant, but should be solved for free when we switch over to the new tables we're going to get from FEC. Let's defer for now.

**Comment by jmcarp** [comment]
After taking a closer look at this, it turns out that the years in `cand_valid_fec_yr` don't match the years that appear on FEC Viewer. Based on earlier discussion with @PaulClark2 and the data I looked at in the new views, I think we want to derive the two-year periods a candidate was active by joining `cand_valid_fec_yr` on `cmte_valid_fec_yr` like so (this example fetches active cycles for candidate George W Bush):

```
select distinct(cand.fec_election_yr)
from cand_valid_fec_yr cand
join cand_cmte_linkage link on
    cand.cand_id = link.cand_id and
    cand.fec_election_yr = link.fec_election_yr and
    link.linkage_type in ('P', 'A')
where cand.cand_id = 'P00003335';

 fec_election_yr
-----------------
            2000
            2002
            2004
            2006
            2008
(5 rows)
```

This is the same as or very similar to the output of FEC Viewer for the examples I've checked. One difference is that the query above shows cycles for Bill Clinton from 1992 to 2014, but FEC Viewer shows 1994 to 2016.

A few questions for @PaulClark2 and @jwchumley:
* Overall, is this a good approximation of what's currently happening on FEC Viewer?
* Should we be joining on both Principal and Authorized committees, or just Principal?
* To determine linked committee type, are we better off using `linkage_type` or `cmte_dsgn`?
* Is the `cand_status` column relevant for calculating active years?

cc @LindsayYoung

**Comment by jwchumley** [comment]
I'm surprised the cand_valid table doesn't match up with the viewer but 
using the linkage table should be fine.

The viewer only goes back to 93/94 for the most part. That would account 
for the missing 92 data for Clinton.

**Comment by jmcarp** [comment]
The issue with using `cand_valid_fec_yr` alone is that it includes many two-year periods for which the candidate wasn't active:

```
fec=> select fec_election_yr from cand_valid_fec_yr where cand_id = 'P00003335';
 fec_election_yr
-----------------
            1998
            2000
            2002
            2004
            2006
            2010
            2008
            2012
            2014
            2016
(10 rows)
```

We could try filtering `cand_valid_fec_yr` on `cand_status != 'P'`, or something similar, but that also wouldn't match up with FEC Viewer very well--for the example of George W Bush, that would give us 1998-2004, when the current site gives 1998-2008. I also vaguely remember @PaulClark2 saying that the desired behavior was to use a candidate's principal committee(s) to determine her/his two-year periods to show.

@LindsayYoung, does that ring a bell to you?
