### ISSUE TITLE
Give correct API instructions

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#958]
It should be:
No api_key was supplied. Get one at https://api.data.gov/signup/
![screen shot 2015-06-10 at 5 53 56 pm](https://cloud.githubusercontent.com/assets/4406333/8097637/c64aad52-0f99-11e5-9869-0ef1c69b05d7.png)

**Comment by jmcarp** [comment]
Done. For evidence, see https://api.open.fec.gov/v1/candidates.
