### ISSUE TITLE
don't show date options we don't have info on in the dropdown

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#960]
Looking at the committee page. 

I want to keep the data intact, but we don't want to include the 70s in the filter
http://localhost:3000/committee/C00005462?cycle=1976

**Comment by LindsayYoung** [comment]
This looks like after they were turning in f3 forms

http://localhost:3000/committee/C00347583?cycle=2000

**Comment by LindsayYoung** [comment]
Maybe we could create the options based on the cycles we have totals for. What do you think @jmcarp

**Comment by jmcarp** [comment]
Part of this is simple: we shouldn't show cycles before 1980 in the cycle picker, which I'll change now. Part of it is more complicated: the second committee you mentioned *does* have totals for 2000, but for some reason we're missing their F1s pre-2002, which means we get an error trying to load their committee information in the 2000 cycle. FEC does have an F1 for this committee from 1999--if we had that, there wouldn't be an error.

**Comment by jmcarp** [comment]
I'm going to close this, since the dropdown is fixed, and the data issue is documented in #961.
