### ISSUE TITLE
Replace multi-select

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC#965]
For a number of UX reasons, we should replace the election-cycle filter multi-select with checkboxes. This will both make it more user friendly on desktop, as well as actually make it work properly on mobile (see the way iOS renders t below :cry: )

![ios simulator screen shot jun 15 2015 10 39 08 am](https://cloud.githubusercontent.com/assets/1696495/8162366/c9c7ea80-134a-11e5-8dbc-84de2076179b.png)

Of course, this poses a challenge as there's so many years, but I'm playing with design options for how to handle that. 

I'm also interested in moving towards checkboxes (or radio buttons) for the other filters as well. Curious what @jmcarp thinks as far as how hard this will be to implement.

**Comment by jmcarp** [comment]
As far as the backend goes, I don't see any problem switching to checkboxes or radio buttons--they're going to generate the same query parameters as a multi-select.

**Comment by noahmanger** [comment]
Did you want to tag-team this? I can work on the UI if you want to do the JS (I could try to figure it out, but my guess is you could do it super quick).

**Comment by noahmanger** [comment]
Began work here: https://github.com/18F/openFEC-web-app/pull/270

**Comment by jmcarp** [comment]
Sure, I'll take a look later today.

**Comment by noahmanger** [comment]
Solved in https://github.com/18F/openFEC-web-app/pull/270
