### ISSUE TITLE
"View Charts" button doesn't do anything if an Authorized Committee has no financial data

### ISSUE THREAD

**Issue by rdpiazza** [18F/openFEC#969]
1) Open a candidate page for a candidate where the Authorized Committee does not have financial data. Example on dev: H2KY02109
2) Select the View Charts button
![screen shot 2015-06-15 at 2 01 57 pm](https://cloud.githubusercontent.com/assets/10507124/8166710/81a27b86-1367-11e5-9f26-0bda95c53747.png)
3) The button text changes to Hide Charts, but no charts are displayed
![screen shot 2015-06-15 at 2 02 10 pm](https://cloud.githubusercontent.com/assets/10507124/8166714/86695fb8-1367-11e5-8751-09b2ecaefac7.png)

![screen shot 2015-06-15 at 2 03 42 pm](https://cloud.githubusercontent.com/assets/10507124/8166699/72bfd280-1367-11e5-9e21-2f33b6bedddb.png)

**Comment by LindsayYoung** [comment]
Yea, I think the whole totals for none section should not be their either. 

Also agree it is not a deal-breaker.

**Comment by noahmanger** [comment]
No longer relevant
