### ISSUE TITLE
Misleading Error Message for No Results

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC#979]
Reproduce by: 
1. Search by Candidate, type Obama
2. Select Obama, Barack H for House
![screen shot 2015-06-15 at 10 04 54 pm](https://cloud.githubusercontent.com/assets/12799132/8174441/a2770bfe-13aa-11e5-9c80-ea8b1b98d6c1.png)
3. No Results screen returns "None election cycle", which is confusing. Would expect the text to reference the selected election cycle or some alternative text.
![screen shot 2015-06-15 at 9 52 54 pm](https://cloud.githubusercontent.com/assets/12799132/8174373/c6e23dde-13a9-11e5-80c2-17cdd6849df4.png)

**Comment by jmcarp** [comment]
Thanks @patphongs for reporting! This has been fixed in https://github.com/18F/openFEC-web-app/pull/275. The fix will be deployed soon.

**Comment by LindsayYoung** [comment]
This formats no results nicely but we need to fix the underlying data issue, I am documenting that separately in issue #986.
