### ISSUE TITLE
entering multiple arguments for array types yields zero results

### ISSUE THREAD

**Issue by boblannon** [18F/openFEC#980]
cause: entering multiple values in a field that the docs suggest accepts an array
expected behavior: return the union of results for each argument in the array
actual behavior: zero results returned.

example:

```python
state_query = 'http://fec-dev-api.cf.18f.us/v1/candidates?sort=name&candidate_status=C&office=H&state={}&cycle=2012&per_page=20&page=1'

for state in ('PA', 'NY', 'NJ'):
    num_results = requests.get(state_query.format(state)).json()['pagination']['count']
    print(state,num_results)
```
returns
```
('PA', 17)
('NY', 37)
('NJ', 14)
```
but
```python
requests.get(state_query.format('PA,NY,NJ')).json()['pagination']['count']
```
returns
```
0
```

The issue seems to be a general one. The following also returns an empty set:
```
http://fec-dev-api.cf.18f.us/v1/candidates?candidate_status=C%2CF&office=P&cycle=2016
```

**Comment by LindsayYoung** [comment]
I think we need to document that better, you can do multiples but you need to write them out individually:
`http://fec-dev-api.cf.18f.us/v1/candidates?candidate_status=C&candidate_status=F&office=P&cycle=2016`

**Comment by boblannon** [comment]
oh, i see. the documentation actually contradicts this.  when you multiple-select using the interactive documentation, it constructs 

```http://fec-dev-api.cf.18f.us/v1/candidates?sort=name&candidate_status=C%2CF%2CN&per_page=20&page=1```

that's pretty standard API design, actually. with the "repeated param" approach, it's going to be difficult/counterintuitive to use the API with, for example, python-requests, which lets you specify GET params using a python dict. that might complicate the task of writing a wrapper in the future.

**Comment by boblannon** [comment]
let the record show that i feel a fool for using "actually"

**Comment by LindsayYoung** [comment]
You couldn't be a fool if you tried, Bob!

**Comment by LindsayYoung** [comment]
Yea, we are using Swagger so I think it should be able to handle it. I will read the docs.

**Comment by boblannon** [comment]
i am told by colleagues that i'm being too prescriptive and that my django-centric worldview is clouding my sensibilities. i'll rescind my insistence on "arg1,arg2,arg3" style.

...but certainly the docs should be updated so that they don't suggest that "NY,PA,NJ" is a licit request.  I can open a separate ticket for that, if it'd help.

**Comment by LindsayYoung** [comment]
I agree that we need to update documentation- I will do that today

**Comment by boblannon** [comment]
wow, i was even totally wrong about python-requests, which absolutely DOES support this pattern.

```python
payload = {'candidate_status[]': ['C', 'F']}
r = requests.get('http://fec-dev-api.cf.18f.us/v1/candidates', params=payload)
r.url
```
```
u'http://fec-dev-api.cf.18f.us/v1/candidates?candidate_status%5B%5D=C&candidate_status%5B%5D=F'
```

**Comment by LindsayYoung** [comment]
Swagger documentation corrected
