### ISSUE TITLE
/candidates and /candidates/search redundant?

### ISSUE THREAD

**Issue by boblannon** [18F/openFEC#981]
It seems like the `/candidates/search` endpoint returns a superset of what is returned by `/candidates` for equivalent query params. Having both is a bit confusing, especially because, on the `/committees` branch, there is no corresponding `/committees/search` endpoint.  

There's nothing really *wrong* here, but symmetry and non-redundant endpoints can really help when getting to know a new API.

**Comment by LindsayYoung** [comment]
The /candidates/search provides a nested list of principal committees for each candidate. We are using it for our main search, but maybe we could give it a more intuitive name?

**Comment by boblannon** [comment]
I guess what I'm suggesting is that there be only one endpoint, that it be `/candidates`, and that it return what `/candidates/search` currently returns

**Comment by jmcarp** [comment]
Separating into two endpoints means that we can save a JOIN in `/candidates`, but this is probably an optimization we can live without. I wouldn't mind making the endpoint a few tens of milliseconds slower for the sake of a simpler API.

**Comment by boblannon** [comment]
the join shouldn't be too bad if you perform it after querying the candidate table, right?

**Comment by boblannon** [comment]
like 

```
with (select * from candidates where blah blah blah) as candidate_result
select 
   candidate.*,
   committee.*
from 
   candidate_result cr
      inner join
   candidate_to_principal_committees cpc on cr.candidate_id = cpc.candidate_id
      inner join
   committee c on c.committee_id = cpc.committee_id
```

**Comment by jmcarp** [comment]
Yeah, like I said, probably not a worthwhile optimization :smiley:--we save a little time, but probably not enough to justify the duplication. We're dealing with an ORM, so our code looks different but does nearly the same thing: https://github.com/18F/openFEC/blob/develop/webservices/resources/candidates.py#L75-L80.

**Comment by boblannon** [comment]
gotcha.  thanks for the in-depth response!
