### ISSUE TITLE
Missing results in `candidate/id/committees`

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#986]
http://localhost:5000/v1/candidate/H0IL01087/committees/history

2000 is listed in "cycles"  but doesn't get its own entry

**Comment by jmcarp** [comment]
I looked into this, and the problem seems to be a missing F1 for the Obama campaign from 1999 described in #961.

**Comment by LindsayYoung** [comment]
Ok I will close that since the ticket for this already exists. Thanks Josh
