### ISSUE TITLE
incorrect candidate metadata?

### ISSUE THREAD

**Issue by boblannon** [18F/openFEC#987]
Not sure how widespread this is, but, eg: Obama is marked as non-statutory.

```json
{
      "active_through": 2012,
      "candidate_id": "P80003338",
      "candidate_status": "N",
      "candidate_status_full": "Not yet a statutory candidate",
      "cycles": [
        2008,
        2010,
        2012
      ],
      "district": null,
      "election_years": [
        2008,
        2012
      ],
      "incumbent_challenge": "I",
      "incumbent_challenge_full": "Incumbent",
      "name": "OBAMA, BARACK",
      "office": "P",
      "office_full": "President",
      "party": "DEM",
      "party_full": "Democratic Party",
      "state": "US"
    }
```

The candidate master file lists him as having candidate status "C", which is what I expected.

**Comment by LindsayYoung** [comment]
Looks like it is not picking up the most recent record-- looking into it now.

**Comment by LindsayYoung** [comment]
Ok I am looking at: 
openFEC/data/sql_updates/create_candidate_history_view.sql

We are not given the date of the form in the underlying data, so I think we should use form_sk for now, as a proxy for the order they came in. I know the FEC is working on giving us dates I would like to order on receipt date.

**Comment by boblannon** [comment]
okay, yeah, looking more broadly it seemed systemic.  looks like you found the source, though
