### ISSUE TITLE
candidate count low

### ISSUE THREAD

**Issue by boblannon** [18F/openFEC#988]
comparing 2012 counts in the API (`/candidates?cycle=2012`) and in the candidate master file aka cn12.txt (where `CAND_ELECTION_YR == 2012`)

 office | CM | API
---------|------|------
 H | 2595 | 2066
S | 481 | 427
P | 438 | 423

**Comment by LindsayYoung** [comment]
First thing that comes to mind is that we are taking our ballot candidates because the data quality for them is not good, but they don't appear in the website, so I did not think they appeared in the bulk data either.

**Comment by LindsayYoung** [comment]
Ok I did find a ballot candidate in the bulk data, which leans toward my hypothesis.  

I found H4UT04052 AALDERS, TIM in the 2014 file. 

The problem with ballot candidates is that they never filed paperwork with the FEC so the information in the data warehouse is not very good for them. All their districts show up as 99 and there were other data quality issues along those lines. 

We could add them some time in the future, I would want to add them in a separate category or take some measure to keep the data the website is using clean.

**Comment by LindsayYoung** [comment]
This might also be an effect of #961

**Comment by LindsayYoung** [comment]
Actually, it shouldn't be because that issue is about committees.

**Comment by boblannon** [comment]
is it possible that their district might show up at "00" instead of "99"?  This table is a count of the district numbers within the candidates that are found in the bulk data and not through the API:

CAND_OFFICE_DISTRICT | count
-------------------------------------|--------
 00  |  689
 02  |  243
 01  |  242
 03  |  218
 04  |  160
 05  |  138
 07  |  114
 08  |  102
 06  |   98
 09  |   65
 13  |   63
 10  |   63
 11  |   46
 12  |   42
 17  |   33
 14  |   33
 19  |   31
 20  |   26
 23  |   24
 24  |   22
 16  |   20
 18  |   20
 15  |   18
 25  |   16
 27  |   14
 28  |   13
 21  |   13
 22  |   12
 26  |   11
 29  |   10
 36  |   10
 33  |    9
 32  |    9
 30  |    9
 47  |    8
 37  |    7
 50  |    6
 31  |    5
 52  |    5
 35  |    4
 45  |    4
 34  |    4
 48  |    4
 39  |    3
 46  |    3
 42  |    3
 51  |    3
 53  |    3
 38  |    2
 43  |    2
 41  |    2
 49  |    1
 44  |    1
 40  |    1

I thought that "00" might refer to presidential and senatorial candidates. It seems like most of them are, but many of the entries with "00" districts are house candidates, too:

| CAND_OFFICE | non-matching candidates | all candidates |
| -------- | ----------------- | --------- |
| H |	  70 	| 129 | 	 	
| P |   181 | 608 |
| S |   438 | 861 |

**Comment by LindsayYoung** [comment]
They were 99 in the tables that I was looking at, The results for them look better in the download.
